### ISSUE TITLE
Flowchart 下 NodePanelBody 中 "通用节点" 这个Panel 能否加个参数控制显示👑 [需求]

### ISSUE THREAD

**Issue by Delicate90** [ant-design/ant-design-charts#1000]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
Flowchart 下 NodePanelBody 中 "通用节点" 这个Panel 能否加个参数控制显示

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
也可以类似toolbarPanelProps 中的 commands 参数一样加以控制，目前这个“通用节点”是写死在代码里的，影响使用

**Comment by lxfu1** [comment]
可以默认收起 nodePanelProps. defaultActiveKey = ['custom'],

**Comment by lxfu1** [comment]
也可以通过 css 隐藏掉。
