### ISSUE TITLE
🧐[问题]圆环如何设置圆角

### ISSUE THREAD

**Issue by fynh518** [ant-design/ant-design-charts#1007]
![image](https://user-images.githubusercontent.com/19990325/144822078-6aa2e4ab-9407-40c0-baf3-1ed530b55df7.png)

圆环的末尾如何设置成圆角？
例如：
![image](https://user-images.githubusercontent.com/19990325/144822168-8e185ad7-50e2-44c7-adb6-b7484a83f5b6.png)

**Comment by lxfu1** [comment]
试试 lineCap: 'round',
