### ISSUE TITLE
🐛[BUG]混合图表中(堆叠图和折线图)使用自定义tooltip，只能获取到柱状图的数据，获取不到折线图的数据

### ISSUE THREAD

**Issue by overcastsky** [ant-design/ant-design-charts#101]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
混合图表中(堆叠图和折线图)使用自定义tooltip，只能获取到柱状图的数据，获取不到折线图的数据

### 🏞 期望结果 [描述你原本期望看到的结果]
我希望的是可以实现自定义tooltip
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
tooltip: {
                custom: {
                  customContent: (title, items) => {
                    return (
                      <div style={{ padding: '16px 8px' }}>
                        <h5>提示</h5>
                        <p>年份：{title}</p>
                        <p style={{ margin: 0 }}>值：{items[0] && items[0].data.value}</p>
                        <p style={{ margin: 0 }}>值：{items[0] && items[1].data.value}</p>
                        <p style={{ margin: 0 }}>值：{items[2] && items[2].data.value}</p>
                      </div>
                    );
                  },
                },
              },

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Houngtze** [comment]
应该是第一次点击的时候是，点击第二次就不会

**Comment by overcastsky** [comment]
不是点击，就是在自定义tooltip的时候，函数里能获取到的只有柱状图的数据

**Comment by lxfu1** [comment]
欢迎使用 1.0 。
