### ISSUE TITLE
🧐[问题]在对y轴label进行formatter时动画效果不好

### ISSUE THREAD

**Issue by zhaoqiang1024** [ant-design/ant-design-charts#1011]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在使用line折线图对y轴label进行formatter设置后整个图的效果呈现了类似全部重绘的样式，xy轴和折线跳动的厉害
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
antd charts版本1.3.1
代码库：https://github.com/zhaoqiang1024/monitor
以下是我的config设置
const config3 = {
    data: [],
    height: 200,
    autoFit: false,
    xField: 'timestamp',
    yField: 'value',
    seriesField: 'type',
    xAxis: {
      tickLine: {
        length: 5,
      },
      tickCount: 5,
      animate: false,
    },
    yAxis: {
      label: {
        formatter: (text: string) => {
          return `${text}MB`;
        },
      },
    },
  };
在更新动态属性时使用了嵌套setTimeout方式来更新
const asyncFetch = () => {
    request('http://127.0.0.1:8080/jvmMonitor', { method: 'get' }).then((value) => {
      // chartsRef.current.changeData(value);
      // chartsRef2.current.changeData(value);
      const heapArray: { type: string; timestamp: any; value: any }[] = [];
      const threadArray: { type: string; timestamp: any; value: any }[] = [];
      if (value) {
        value.forEach(
          (v: {
            timestamp: any;
            heapUseMemory: any;
            heapMaxMemory: any;
            heapCommitMemory: any;
            threadCount: any;
            peakThreadCount: any;
            tartedThreadCount: any;
          }) => {
            heapArray.push({
              type: 'use',
              timestamp: v.timestamp,
              value: v.heapUseMemory,
            });
            heapArray.push({
              type: 'commit',
              timestamp: v.timestamp,
              value: v.heapCommitMemory,
            });
            threadArray.push({
              type: '当前活动数量',
              timestamp: v.timestamp,
              value: v.threadCount,
            });
            threadArray.push({
              type: '已启动总数',
              timestamp: v.timestamp,
              value: v.tartedThreadCount,
            });
          },
        );
      }
      chartsRef3.current.changeData(heapArray);
      // chartsRef4.current.changeData(threadArray);
    });
    const newTime = setTimeout(asyncFetch, 1000);
    setTimer(newTime);
  };
  useEffect(() => {
    asyncFetch();
  }, []);
使用嵌套的setTimeout方式来更新data时会出现类似于整个图形重绘的跳动（y轴、x轴、折线全部跳动），而使用setInterval时则没有，同时在setTimeout方式下去掉对yAxisk.label.formatter的设置后跳动消息只留下数据更新的动效
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
已在antv2群提出问题，但无人解答，本人后端研发希望有前端大佬指点迷津

**Comment by lxfu1** [comment]
setTimer 会导致整个页面重新渲染

**Comment by zhaoqiang1024** [comment]
确实是，刚找到问题，我看下用什么办法可以解决，感谢大佬
