### ISSUE TITLE
🐛[BUG] chartInstance overrides previous chart instances in other components

### ISSUE THREAD

**Issue by MarkLyck** [ant-design/ant-design-charts#1012]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

When rendering multiple charts, the chartInstance of the last rendered chart will override any other chartInstance on the page.

In this case I am trying to download a chart image of 2 charts:

![Screen Shot 2021-12-08 at 15 06 58](https://user-images.githubusercontent.com/6841110/145276832-d393bb77-87a6-4cb3-af3d-535210e6b6e1.png)

If I click the "export" button on the left chart, it exports an image of the right chartt
If I click the "export" button on the right chart, it also exports an image of the right chart.

I followed the code example on the github ReadMe:

```
  let chart: any

  const downloadImage = () => {
    chart?.downloadImage()
  }

  return (
    <>
      <button type="button" onClick={downloadImage} style={{ marginRight: 24 }}>
        Export Image
      </button>
      <Pie
        {...config}
        style={{ width: '100%' }}
        onReady={(chartInstance) => (chart = chartInstance)}
      />
    </>
  )
```

I tried providing a unique key, or id, or className to the chart with no luck.

The parent that renders the charts, already provides a unique key to each child component (in this case just 2). So it's not a problem with React keys.

**Comment by lxfu1** [comment]
Can you provide an online example?

**Comment by hmz22** [comment]
> ### 🐛 bug description [describe the bug in detail so that everyone can understand it]
> When rendering multiple charts, the chartInstance of the last rendered chart will override any other chartInstance on the page.
> 
> In this case I am trying to download a chart image of 2 charts:
> 
> ![Screen Shot 2021-12-08 at 15 06 58](https://user-images.githubusercontent.com/6841110/145276832-d393bb77-87a6-4cb3-af3d-535210e6b6e1.png)
> 
> If I click the "export" button on the left chart, it exports an image of the right chartt If I click the "export" button on the right chart, it also exports an image of the right chart.
> 
> I followed the code example on the github ReadMe:
> 
> ```
>   let chart: any
> 
>   const downloadImage = () => {
>     chart?.downloadImage()
>   }
> 
>   return (
>     <>
>       <button type="button" onClick={downloadImage} style={{ marginRight: 24 }}>
>         Export Image
>       </button>
>       <Pie
>         {...config}
>         style={{ width: '100%' }}
>         onReady={(chartInstance) => (chart = chartInstance)}
>       />
>     </>
>   )
> ```
> 
> I tried providing a unique key, or id, or className to the chart with no luck.
> 
> The parent that renders the charts, already provides a unique key to each child component (in this case just 2). So it's not a problem with React keys.

I have so this problem

**Comment by lxfu1** [comment]
https://codesandbox.io/s/objective-dhawan-czhys?file=/index.js

**Comment by hmz22** [comment]
You just use @ant-design/plots package but we used @ant-design/charts
you can see this sample:
https://codesandbox.io/s/solitary-river-0i9ke?file=/App.js

**Comment by lxfu1** [comment]
> You just use @ant-design/plots package but we used @ant-design/charts you can see this sample: https://codesandbox.io/s/solitary-river-0i9ke?file=/App.js

Delete node_modules and lock.json, then install again.

**Comment by hmz22** [comment]
I did it

**Comment by lxfu1** [comment]
There is no locked version, you used CDN ？
![image](https://user-images.githubusercontent.com/31396322/147665933-1ee3bc47-5d99-4106-ba8f-b31ddec4a3cd.png)

**Comment by hmz22** [comment]
U mean I must install this 4 package not @and-design/chart 1.3.3?

**Comment by hmz22** [comment]
https://charts.ant.design/en/docs/manual/getting-started
Import by CDN in browser
We provide Ant Design Charts npm package:

// Recommended usage
npm install @ant-design/charts --save
You can use import or require to start.

import { Line } from '@ant-design/charts';

**Comment by lxfu1** [comment]
No, you just need install @and-design/charts again, and check '@ant-design/plots version, make sure it is 1.0.6.

**Comment by hmz22** [comment]
I reinstalled package and in node_modules check plot version before update is 1.0.5 and now 1.0.6 and problem fix but must install tslib package.
Thank you for fix it. ❤️
