### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by MarkLyck** [ant-design/ant-design-charts#1015]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

The leftmost and rightmost columns in a simple Column chart starts in the middle of the x value. This causes the column to overlap the yAxis on the left, and half of the column to be missing on the right...

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

![Screen Shot 2021-12-09 at 14 32 00](https://user-images.githubusercontent.com/6841110/145463381-1833db98-b419-4ee5-bbad-983470f8ac8a.png)

It should not overlap at the ends

Here's the code example that causes the above issue:

```
const config = {
    data,
    height: 320,
    loading,
    xField: 'x',
    xAxis: {
      nice: true,
      type: 'time',
      mask: 'MM/DD/YYYY HH:mm',
    },
    yField: 'value',
  }

  return (
    <Column {...config} />
  )
```

i've tried setting "nice" to false, in the xAxis but that didn't help either.

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

"@ant-design/charts": "1.3.2",

**Comment by lxfu1** [comment]
[range](https://charts.ant.design/zh/docs/manual/faq#4%E6%80%8E%E4%B9%88%E8%AE%BE%E7%BD%AE%E6%A8%AA%E8%BD%B4%E4%BB%8E-0-%E5%BC%80%E5%A7%8B): [0.1, 0.9]
