### ISSUE TITLE
🐛[BUG]  当 meta 的 type: "quantile" 和 ticks 同时用的时候 坐标轴的刻度就对不上了

### ISSUE THREAD

**Issue by eternallycyf** [ant-design/ant-design-charts#1017]
### 🐛 bug 描述 
 - 当meta 同时使用 ticks:[xxx] 和 type:"quantile" 的时候 y轴的刻度线对不齐了 
<img width="647" alt="截屏2021-12-10 下午3 10 08" src="https://user-images.githubusercontent.com/63464198/145532541-2897a28a-ec32-435c-871b-0bbf9bf12b65.png">

### 📷 复现步骤 

 - https://github.com/ant-design/ant-design-charts/issues/889
 - 在这个 issue 的 codesandbox 中 加入一个 type: "quantile"
```js
  meta: {
      type: { alias: "类别" },
      sales: {
        alias: "销售额",
        min: 0,
        max: 500,
        ticks: [10, 20, 50, 100, 150, 300],
        type: "quantile"
      }
    }
```

### 🏞 期望结果 [描述你原本期望看到的结果]
- 纵坐标可以自适应 && 加入自定义的 ticks && 自定义的ticks与数据对齐
- 我的代码现在是这样
   - y轴 0%-100%
   - 数据一般是 80%-100%, 但是可能会有80以下的 
      - 如果不使用 meta , 我需要着重显示的 80%-100% , 但图表是均匀分配的
<img width="709" alt="截屏2021-12-10 下午3 19 59" src="https://user-images.githubusercontent.com/63464198/145533617-6c659457-e29f-40b4-a80b-447153e27b1c.png">
      - 如果只使用 meta的 type:"quantile"  不能达到需求 , 因为还有两个动态显示的 annotations 区域着色
<img width="618" alt="截屏2021-12-10 下午3 25 31" src="https://user-images.githubusercontent.com/63464198/145534389-6701dc4c-de3d-4836-8d6d-1a62f58a3b62.png">
     - 当同时使用    type: "quantile"      ticks: [10, 20, 50, 100, 150, 300], 就会变成这样  对不齐, 96%的 y坐标是 91%
<img width="729" alt="截屏2021-12-10 下午3 16 43" src="https://user-images.githubusercontent.com/63464198/145534481-b8d69b41-2f77-4d06-b191-31df03bc7569.png">
- 期望效果
<img width="687" alt="截屏2021-12-10 下午3 32 12" src="https://user-images.githubusercontent.com/63464198/145535051-620307d3-5167-4c65-8587-95d119ca471a.png">
- 我目前能想到的办法就只能 直接写死, ticks写一个固定值，

### © 版本信息

- ant-design-charts 版本:  "@ant-design/charts": "^1.1.4",
- 浏览器环境 chrome 最新版
- 开发环境 [e.g. mac OS]

**Comment by eternallycyf** [comment]
已解决
## 原因参考 [scale](https://g2.antv.vision/zh/docs/manual/tutorial/scale#quantile)
- `type= "quantize"` 的时候 所有在一个区间的数值都映射到开始的数值 这就是刻度线对不齐的原因
## 解决方法
- 由于`quantize` 精度是按照自定义的`ticks`的  而我传入的是 `[0,lower,high,100]` 这也就失去了小数的映射
- 因此手动生成了下 带小数点的精度 也可以直接自定义 `tickMethod`
- 然后对数组处理下 在 `yAxis label` 配置下就Ok了
- 其次是最大值的 `lable` 超出了范围且不固定,最后我把`100`删掉了, 用 `annotations` 在左上角加了个

```js
 let initTicksArr = []
 let addTicksArr= [0,lower,high,100]
 for (let i = lower - 10; i < 100; i += 0.1) {
    initTicksArr.push(Number((i + 0.1).toFixed(1)));
  }
  initTicksArr.push(...addTicksArr);
  initTicksArr.sort((a, b) => a - b);
```

```js
config = {
  meta: {
    xxx: {
      ticks: [...new Set([...initTicksArr])],
      type: 'quantile',
    }
  },
  yAxis: {
    label:{
      formatter: (precent) => { 
         .....
         return addTicksArr.includes(~~Number(precent)) ? ~~Number(precent) : ''
      }
    }
  }
}
```

**Comment by eternallycyf** [comment]
## 映射区间的做法
```js
 function findMaxNum(val, type) {
    let number = [];
    val.map((res) => {
      if (typeof res[type] === 'number') number.push(res[type]);
    });
    let max = Math.max(...number) * 1.1 > 100 ? 100 : Math.max(...number) * 1.1;
    let min = Math.min(...number) * 0.9;
    return {
      min: min,
      max: max,
    };
  }
let config = { 
  ...,
  yAxis: {
      min: findMaxNum(chartData, 'trendPoint').min,
      max: findMaxNum(chartData, 'trendPoint').max,
  },
  annotations: [
      {
        type: 'region',
        start: [
          'start',
          findMaxNum(chartData, 'trendPoint').min >= lower ? lower : 'min',
        ],
        end: [
          'end',
          findMaxNum(chartData, 'trendPoint').max >= lower ? lower : 'max',
        ],
        style: {
          fill: '#F85746',
          fillOpacity: 0.1,
        },
      },
      findMaxNum(chartData, 'trendPoint').max >= lower &&
      findMaxNum(chartData, 'trendPoint').min <= high && {
        type: 'region',
        start: [
          'start',
          findMaxNum(chartData, 'trendPoint').min >= lower ? 'min' : lower,
        ],
        end: [
          'end',
          findMaxNum(chartData, 'trendPoint').max >= high ? high : 'max',
        ],
        style: {
          fill: '#FAAD14',
          fillOpacity: 0.1,
        },
      },
      findMaxNum(chartData, 'trendPoint').max >= high && {
        type: 'region',
        start: [
          'start',
          findMaxNum(chartData, 'trendPoint').min >= high ? 'min' : high,
        ],
        end: ['end', 'max'],
        style: {
          fill: '#18C54B',
          fillOpacity: 0.1,
        },
      },
  ]
  ...
}
```

**Comment by YuZongYangHi** [comment]
我现在也遇到这个问题了，这么搞是不是太复杂了？

**Comment by YuZongYangHi** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/35584408/236774911-02896b9f-9331-4b63-94ba-1f122570148a.png">
