### ISSUE TITLE
🐛[BUG]项目引入 ant-design-charts 无法编译

### ISSUE THREAD

**Issue by Foodtoinvincible** [ant-design/ant-design-charts#1019]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
=============
Failed to compile.

./node_modules/@antv/xflow-core/es/command-contributions/graph/graph-layout.js
Attempted import error: 'Layouts' is not exported from '@antv/layout' (imported as 'AntvLayout').

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
`{

    "@ant-design/charts": "^1.3.2",

    "@ant-design/icons": "^4.7.0",

    "antd": "^4.17.3",

    "react": "^17.0.2"
}`

使用 <Area />

### 🏞 期望结果 [描述你原本期望看到的结果]
编译通过
### © 版本信息

- ant-design-charts 版本: [1.3.2]
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
用的什么图？

**Comment by lyn-boyu** [comment]
![image](https://user-images.githubusercontent.com/47809781/145721014-fe169392-8b0a-4ff1-bca0-7cde803b9f77.png)
1.1.19的antv/layout 是有export的，更新下nodeModuels？

**Comment by AliRezaBeigy** [comment]
Same issue, could you please update @antv/layout to v0.1.17

**Comment by lxfu1** [comment]
update.

**Comment by lxfu1** [comment]
@ant-design/flowchart: 1.0.5
