### ISSUE TITLE
🧐[问题]对ant-design-charts的一些疑惑

### ISSUE THREAD

**Issue by overcastsky** [ant-design/ant-design-charts#102]
关于堆叠图和折线图混合图表类型
	（1）、需求：在tooltip中给其中折线图指标数值添加单位后缀
		问题点：在使用formatter函数的时候发现是拿不到折线图的数据的，在API中tooltip仅仅支持visible、domStyle这两个属性配置
	（2）、需求：将legend放在同一位置展示
		问题：目前官方demo是将其根据坐标轴的位置排列
	（3）、需求：坐标轴网格线，希望可以设置成虚线
		问题：目前给到的API中只是提到了支持一个style配置，但是style中支持哪些样式的属性并没有详细的说明

**Comment by changjiang-bai** [comment]
tooltip的格式化问题，你的需求可以通过设置tooltips的fields属性实现，formatter的参数值跟fields的值逐一对应，相关的属性可以在G2Plot官网中看到
![image](https://user-images.githubusercontent.com/35088699/87652436-cd2c5080-c786-11ea-82fe-aef9e68e89a1.png)
![image](https://user-images.githubusercontent.com/35088699/87652865-53489700-c787-11ea-84c0-7037284552a9.png)

**Comment by overcastsky** [comment]
我指的是堆叠图和折线图的混合图表自定义tooltip实现，这个API好像是在单一图表中是可以的

**Comment by lxfu1** [comment]
更新 1.0 版本。
