### ISSUE TITLE
🧐[问题]圆环Pie文本标签的内容怎么配置

### ISSUE THREAD

**Issue by 18870728245** [ant-design/ant-design-charts#1021]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
想配置成这样
![image](https://user-images.githubusercontent.com/74346349/146106325-0a311c49-ffc3-4cd4-b99a-87a58b8ec6ae.png)
想把Legend上的对应分类展示在值的前面
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/74346349/146106779-aa63a191-3a2f-49b2-9a89-9d9dd7df4074.png)
由于API文档上显示的content是string，获取不到对应分类，所以暂时没找到在哪里配置

**Comment by lxfu1** [comment]
看下典型案例里面的自定义 tooltip
