### ISSUE TITLE
👑 [需求] 优化项目依赖规则，防止基础库多版本共存

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design-charts#1024]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

优化项目依赖规则，防止基础库多版本共存，造成打包文件较大！

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

统一依赖匹配方式，例如全部使用 `^` 匹配，不要 `^0.0.1`，`~0.0.1`，`0.0.1` 等方式共存！

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/1730277/146136988-d064973f-aa7c-4842-9fe2-942c08f60213.png)

**Comment by lxfu1** [comment]
这个建议直接给G仓库提issue
