### ISSUE TITLE
🐛[BUG] 1.3.0 版本升级是 Breaking Change，不符合语意化版本

### ISSUE THREAD

**Issue by DremyGit** [ant-design/ant-design-charts#1025]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

https://github.com/ant-design/ant-design-charts/blob/master/CHANGELOG.md?plain=1#L17-L33

1.3.0 版本需要在应用中额外手动引入 `antd`、`@ant-design/icons`、`lodash`，否则直接报错 `can't resolve xxx`，导致依赖 `@ant-design/charts@^1.0.0` 的应用重新构建出错。

此举违背了 Semver 语义化规则，应该升级大版本至 2.0.0

### 🏞 期望结果 [描述你原本期望看到的结果]

`@ant-design/charts` 应该升级版本至 2.0.0，而不是 1.3.0

### © 版本信息

- ant-design-charts 版本: 1.3.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
这个问题之前也有考虑过，`antd`、 `@ant-design/icons`、 `lodash`仅在流程图里面被依赖，如果使用子包的话是不需要的，最终决定使用 1.3.0。

**Comment by DremyGit** [comment]
这些拆分的子包也是在1.3.0版本提供的，只要用户不能平滑无感升级依赖，导致之前可以正常构建的应用无法构建，就是 Breaking Change。不按照 Semver 来编排版本号，除了说明项目维护者自私的心理之外，也想不到其它的原因了
