### ISSUE TITLE
🧐 HOW TO SHOW ONLY INTERGERS IN Y AXIS 

### ISSUE THREAD

**Issue by carolinavreis** [ant-design/ant-design-charts#1026]
const config = {
    data: statisticByGender
    isGroup: true,
    appendPadding: 60,
    xField: "ageLabel",
    yField: "Quantity",
    xAxis: {
      label: {
        autoHide: true,
        autoRotate: false,
      },
    },
    seriesField: "Gender",
    color: ["#00c2ff", "#5051f3"],
  };

render => <Column {...config} />

WHICH PROP SHOULD I USE?
![1](https://user-images.githubusercontent.com/71522035/146156694-a8c5259b-01c7-439f-8a77-9baa648b931c.PNG)

**Comment by lxfu1** [comment]
yAxis.label.formatter: (name) => (name || '')
