### ISSUE TITLE
🐛[BUG] CSS imported by a dependency

### ISSUE THREAD

**Issue by AlexandreMouyen** [ant-design/ant-design-charts#1028]
Hello,

I was trying to use the TinyArea when I had an error on my NextJS project.

You can find here the detailed error: https://nextjs.org/docs/messages/css-npm.

The location of the trouble could be there: node_modules\@antv\x6-react-components\es\color-picker\index.js

It is possible to fix it?

Greetings,

**Comment by aboveyunhai** [comment]
@AlexandreMouyen  
the current solution I had so far it to roll back to `1.2.10` instead of `latest` version
```ts
const Line = dynamic<LineConfig>(
  () => import("@ant-design/charts/lib/plots/line"),
  {
    ssr: false,
  }
);
```
This does not work in latest version

**Comment by AlexandreMouyen** [comment]
@aboveyunhai 

Thanks you, this workaround is working.

**Comment by askurat** [comment]
@AlexandreMouyen @aboveyunhai It looks like they just moved the location of plots. You could just install the subpackage: 

`@ant-design/plots`

and use
```
const DualAxes = dynamic(
  () => import('@ant-design/plots/lib/components/dualAxes'),
  { ssr: false }
);
```

This seems to work for me on the latest version.

**Comment by abdallanayer** [comment]
I am facing the issue with 
`import { Area } from "@ant-design/charts";
import { Column } from "@ant-design/charts";
import { Line } from "@ant-design/charts";
import { Mix } from "@ant-design/charts";
`
I used @askurat workaround and it is working, but shouldnot that be fixed and not depending on a workaround ? 

@AlexandreMouyen can you reopen the issue ? or i will create a new one

**Comment by AlexandreMouyen** [comment]
> @AlexandreMouyen can you reopen the issue ? or i will create a new one

Yes for sure

**Comment by aseph8083** [comment]
you can change the import chart as an example `import { Area } from '@ant-design/plots';`
