### ISSUE TITLE
🐛流程图案例崩了

### ISSUE THREAD

**Issue by yxkt** [ant-design/ant-design-charts#1029]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by yxkt** [comment]
流程图案例崩了

**Comment by lxfu1** [comment]
样式问题， 手动引入 import "@ant-design/flowchart/dist/index.css" 可正常使用，我稍后更新一波官网。

**Comment by hyzx86** [comment]
问题依旧嘞。。
![Uploading image.png…]()

**Comment by lxfu1** [comment]
```ts
import "antd/dist/antd.css";
import "@ant-design/flowchart/dist/index.css";
```

**Comment by hyzx86** [comment]
加了 。没用
![image](https://user-images.githubusercontent.com/15613121/177265694-49724d48-9657-4488-8ba3-e7419a37cbbb.png)
![image](https://user-images.githubusercontent.com/15613121/177265722-9a65ae7f-face-4332-8a9b-1ec66eab6407.png)
[index.tsx.txt](https://github.com/ant-design/ant-design-charts/files/9043889/index.tsx.txt)

**Comment by lxfu1** [comment]
你的示例我去掉 PageContainer是可以的，检查下你这个目录 `antd/dist/antd.css` 是否有文件  antd4

**Comment by hyzx86** [comment]
我这儿去掉也不行~
有的哦  
![image](https://user-images.githubusercontent.com/15613121/177268808-8805c757-411a-4c21-92e2-adf0935ff6e6.png)

**Comment by hyzx86** [comment]
![image](https://user-images.githubusercontent.com/15613121/177271118-7cbe65ab-acc4-437e-8595-c42129eca087.png)
