### ISSUE TITLE
👑 [需求] 双折线图展示优化

### ISSUE THREAD

**Issue by linhf123** [ant-design/ant-design-charts#1031]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
让折线内容在区域内显示,比如 G2 这个[双 y 轴折线图](https://g2.antv.vision/zh/examples/line/basic#double-y-axes)
最好能让两个 y 轴的坐标点数量保持一致,并与线条对齐
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/32009993/146345757-98fafa9f-10ab-41e5-9099-2b4e96c1a047.png)
![image](https://user-images.githubusercontent.com/32009993/146345095-f6c9cfa7-1cbc-4c3c-a173-2e35e7f719cf.png)

**Comment by lxfu1** [comment]
刻度线对齐是不合理的，因为两者用了不同的比率尺，可以选择关闭一侧的刻度线，[参考 V2](https://ant-design-charts-next.antgroup.com/zh/examples/statistics/dual-axes/#dual-multi-line)
