### ISSUE TITLE
水波图的外圈与内圈间距的白色有没有配置项进行修改

### ISSUE THREAD

**Issue by poison111222333** [ant-design/ant-design-charts#1033]
![image](https://user-images.githubusercontent.com/65275963/146476210-03f89fc5-d9d0-4fb3-8f9c-a51fc9dc72fb.png)
水波图的外圈与内圈间隔的颜色目前为白色，有没有配置项能进行修改

**Comment by pearmini** [comment]
因为技术上的一些困难，暂时没有哈
