### ISSUE TITLE
🐛[BUG] 1.3.2 版本 百分比条形图合计为0请求下图表报错

### ISSUE THREAD

**Issue by ZhaoCSS** [ant-design/ant-design-charts#1034]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
https://codesandbox.io/s/zealous-hodgkin-4u789?file=/index.js
当数据如下
  const data = [
    {
        "id": "安徽甩手集团@160275@2021/12/14",
        "rowTitle": "安徽甩手集团",
        "value": 0,
    },
    {
        "id": "安徽甩手集团@160275@2021/12/13",
        "rowTitle": "安徽甩手集团",
        "value": 0,
    },
    {
        "id": "安徽甩手集团@161237@2021/12/14",
        "rowTitle": "安徽甩手集团",
        "value": 1,
    },
    {
        "id": "安徽甩手集团@161237@2021/12/13",
        "rowTitle": "安徽甩手集团",
        "value": -1,
    },
  ];
会导致情况如下
![image](https://user-images.githubusercontent.com/21076533/146482337-eaa6edaa-76c0-4b26-a78c-0c4589e1a43c.png)
但是这种数据下
  const data = [
    {
        "id": "安徽甩手集团@160275@2021/12/14",
        "rowTitle": "安徽甩手集团",
        "value": 1,
    },
    {
        "id": "安徽甩手集团@160275@2021/12/13",
        "rowTitle": "安徽甩手集团",
        "value": -1,
    },
    {
        "id": "安徽甩手集团@161237@2021/12/14",
        "rowTitle": "安徽甩手集团",
        "value": 0,
    },
    {
        "id": "安徽甩手集团@161237@2021/12/13",
        "rowTitle": "安徽甩手集团",
        "value": 0,
    },
  ];
图表就可以正常展示

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://codesandbox.io/s/zealous-hodgkin-4u789?file=/index.js
这是复现地址，可根据上述数据进行测试。
### 🏞 期望结果 [描述你原本期望看到的结果]
正常展示图表
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/zealous-hodgkin-4u789?file=/index.js
### © 版本信息

- ant-design-charts 版本: [1.3.2]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
重新安装下依赖
