### ISSUE TITLE
🧐[问题] How do exclude @ant-design/icons and antd

### ISSUE THREAD

**Issue by jun094** [ant-design/ant-design-charts#1035]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
I know that **flowChart** has been added since version 1.3.x.
So from this version, `@ant-design/icons` and `antd` are included in peerdependency.

But I don't use **flowChart**. So I am using 1.2.x.

However, when 1.2.x is installed, the **flowChart** is installed in **node_modules**, and `@ant-design/icons` and `antd` are required.
Is there any way to embed a **flowChart** in **node_modules**?

<br/>

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```
// package.json
"dependencies": {
    "@ant-design/charts": "^1.2.14",
     ...
```
1. delete `package-lock.json` 
2. `npm i`
3. Check the `@ant-design` in **node_modules**

<br/>

#### Previous
<img width="732" alt="normal" src="https://user-images.githubusercontent.com/42564107/146663711-6a98b57e-dc94-42b2-91da-e7e7f4218aab.png">

#### Present

<img width="667" alt="problem" src="https://user-images.githubusercontent.com/42564107/146663712-eda13613-851b-48f7-80f2-b7692b89fa45.png">
<img width="638" alt="problem2" src="https://user-images.githubusercontent.com/42564107/146663713-30d6d380-cd8e-4a85-a2a0-f8f9407fbbd8.png">

**Comment by lxfu1** [comment]
Use subpackages

`@ant-design/charts` includes
Plots: @ant-design/plots
Maps: @ant-design/maps
Flowchart: @ant-design/flowchart
Relation Graphs: @ant-design/graphs

**Comment by jun094** [comment]
Thank you for quick respons : )
