### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by my-Sakura** [ant-design/ant-design-charts#1036]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
折线图和面积图数据过多导致图表混乱，加上 slider 参数后能够正常展示，具体情况如下：
![image](https://user-images.githubusercontent.com/69021934/146681965-fe68516b-a97e-4ace-b16d-5116c48398b2.png)
正常情况
![image](https://user-images.githubusercontent.com/69021934/146682042-a003c82d-0fa2-4884-bd9d-6d4d29331613.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
```
import { Area } from '@ant-design/charts';
import React from 'react';

const StaticRefChart = (props) => {
  const { data } = props;

  const config = {
    data,
    xField: 'row',
    yField: 'value',
    seriesField: 'name',
    legend: {
      position: 'top',
    },
    // slider: {
    //   start: 0.1,
    //   end: 0.9,
    // },
    color: ({ name }) => {
      switch (name) {
        case 'ZeroRef':
          return '#9BE8E8';
        case 'MeasureRef':
          return '#9E9BEB';
      }
    },
    smooth: false,
  };

  return <Area {...config} />;
};

export default StaticRefChart;

```

**Comment by lxfu1** [comment]
确认下是不是数据有问题

**Comment by my-Sakura** [comment]
横坐标数据没有重复，xField 类型是 number，只是数据量过大，数组长度为 256。

**Comment by lxfu1** [comment]
> xField 类型是 number

xField 类型是 number 是问题， 需要  string 类型。
