### ISSUE TITLE
🐛[BUG] 折线图y轴刻度出现浮点数精度问题

### ISSUE THREAD

**Issue by easyterry** [ant-design/ant-design-charts#1038]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
折线图y轴刻度出现浮点数精度问题

![image](https://user-images.githubusercontent.com/24635847/146705516-d99ac76a-1c09-4df6-be12-4a857e81c7d7.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
在官方demo中，将数值修改为截图里的数值，即可复现，业务中也出现这种问题。

### 🏞 期望结果 [描述你原本期望看到的结果]
y轴刻度不会出现多位小数

### © 版本信息

- ant-design-charts 版本: 1.3.2
- 浏览器环境 Chrome 96.0.4664.110
- 开发环境 Win10

**Comment by lxfu1** [comment]
这个问题使用一下 formatter,  yAxis.label.formatter: (name) => Number(name).toFixed(2)

**Comment by liuvigongzuoshi** [comment]
> 这个问题使用一下 formatter, yAxis.label.formatter: (name) => Number(name).toFixed(2)

@easyterry
