### ISSUE TITLE
🐛[BUG]  多轴折线图开启 缩略图功能后的 展示bug

### ISSUE THREAD

**Issue by WeiShengv99** [ant-design/ant-design-charts#1039]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
多轴折线图开启 缩略图功能后的 展示上  线条跑到x轴的下面去了

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://charts.ant.design/zh/examples/dual-axes/column-line#column-line
只需要在g官方 demo 里加上 `  slider: {},`选项，就可以看到问题。

### 🏞 期望结果 [描述你原本期望看到的结果]
正常展示

### © 版本信息

- ant-design-charts 版本:  最新
- 浏览器环境 chrome 版本 96.0.4664.110（正式版本） (arm64)
- 开发环境 [e.g. mac OS] maos big suger 11.6

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/35689628/146764002-3d1261a2-e275-49d2-b6a3-be2d97a2e559.png)

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/489

**Comment by WeiShengv99** [comment]
> #489
@lxfu1  抱歉，我补下  code 吧
```
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { DualAxes } from '@ant-design/charts';

const DemoDualAxes = () => {
  const data = [
    {
      time: '2019-03',
      value: 350,
      count: 800,
    },
    {
      time: '2019-04',
      value: 900,
      count: 600,
    },
    {
      time: '2019-05',
      value: 300,
      count: 400,
    },
    {
      time: '2019-06',
      value: 450,
      count: 380,
    },
    {
      time: '2019-07',
      value: 470,
      count: 220,
    },
  ];
  const config = {
    data: [data, data],
    xField: 'time',
    yField: ['value', 'count'],
    slider: {},
    geometryOptions: [
      {
        geometry: 'column',
      },
      {
        geometry: 'line',
        lineStyle: {
          lineWidth: 2,
        },
      },
    ],
  };
  return <DualAxes {...config} />;
};

ReactDOM.render(<DemoDualAxes />, document.getElementById('container'));

```

**Comment by lxfu1** [comment]
看我给你发的链接，点进去看下配置。

**Comment by WeiShengv99** [comment]
> 看我给你发的链接，点进去看下配置。

谢谢你的回复，我现在知道怎么做了
