### ISSUE TITLE
[BUG]词云（WordCloud）组件渲染汉字失败

### ISSUE THREAD

**Issue by 1e9** [ant-design/ant-design-charts#104]
WordCloud组件不能渲染出汉字如 ‘成都’，但多次刷新页面后有可能出现。若测试结果成功渲染，请多次刷新以复现问题。

**Comment by lxfu1** [comment]
试试 1.0.0 版本，https://charts.ant.design/demos/word-cloud#%E8%AF%8D%E4%BA%91%E5%9B%BE-%E4%BA%A4%E4%BA%92%E6%95%88%E6%9E%9C
