### ISSUE TITLE
👑 [需求]允许每个node根据数据来控制width和height

### ISSUE THREAD

**Issue by lovekonakona** [ant-design/ant-design-charts#1043]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
组织架构图需要允许每个node根据数据来控制width和height

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
增加nodeCfg.size可以传入函数
```tsx
{
  nodeCfg: {
    size: (item) => {
      return [item.width, item.height];
    }
  }
}
```

**Comment by lxfu1** [comment]
这个size是最小宽高，不等于最终效果，回调的意义不大，可以使用
