### ISSUE TITLE
🐛[BUG] xAxis 或者 meta 中设置 x 轴 range: [0, 1], 开启 point 时打点位置错位

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design-charts#1044]
### 🐛 BUG 描述

xAxis 或者 meta 中设置 x 轴 range: [0, 1], 开启 point 时 打点位置错位！

### 💻 复现代码

```tsx
<Line
  smooth
  autoFit
  xField="time"
  yField="value"
  point={{ size: 3 }}
  data={online || []}
  yAxis={{ alias: '在线人数' }}
  legend={{ position: 'bottom', offsetY: 16 }}
  xAxis={{ alias: '日期', tickCount: 12, range: [0, 1] }}
/>
```

### © 版本信息

- ant-design-charts 版本: ^1.3.2
- 浏览器环境: Chrome 96
- 开发环境: Windows 11

### 🚑 其他信息

![企业微信截图_20211222113740](https://user-images.githubusercontent.com/1730277/147048030-adc83dda-e676-4038-89fe-920978561222.png)

**Comment by lxfu1** [comment]
提供个在线示例，你这个配置没发现问题~

**Comment by nuintun** [comment]
@lxfu1 https://codesandbox.io/s/antd-charts-wsjxu?file=/src/App.tsx

有点迷，示例没问题，项目中直接 root 只渲染 Line 也对不齐，我排查下😩

**Comment by nuintun** [comment]
`@antv/g2plot: ^2.4.4` 已修复
