### ISSUE TITLE
🐛[BUG] 组织架构图，连接线的 label 展示问题

### ISSUE THREAD

**Issue by RJM1996** [ant-design/ant-design-charts#1046]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
使用 edgeCfg 的 label 中的 content 自定义连接线的 label 展示，初始展示正常，当鼠标移入连接线时，content 回调函数再次执行，此时无法访问到外部变量，导致返回 undefined

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://stackblitz.com/edit/react-5jhez7

### © 版本信息

- ant-design-charts 版本: [1.3.2]
- 浏览器环境 chrome
- 开发环境 [mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/33800707/147072742-7e73b675-147c-4767-a99c-bdd7a7520d43.png)

**Comment by lxfu1** [comment]
```ts
const mapRef = useRef();
mapRef.current = edgeLabelMap;

const labelStr = mapRef.current[edge.id];
```

**Comment by RJM1996** [comment]
谢谢大佬
