### ISSUE TITLE
🐛[BUG] 折线图缩略轴以外的数据没有隐藏

### ISSUE THREAD

**Issue by iambool** [ant-design/ant-design-charts#1054]
### 🐛 bug 描述
如下图所示，缩略轴部分的数据仅显示在图表区域的小部分范围内，其他区域的数据不应该展示的，但还是打上了点，只是没有连线，这样看起来视觉上很乱
![image](https://user-images.githubusercontent.com/30134533/147331813-c5c8be3d-8b14-4aa9-a8cd-1245d9072b06.png)

### 🏞 期望结果
期望折线图内仅显示缩略图部分的数据，显示效果如下：
sandbox：https://codesandbox.io/s/6x5th?file=/App.tsx
![image](https://user-images.githubusercontent.com/30134533/147332521-f026075a-1c62-4653-b592-beb480c40ca9.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
sandbox：https://codesandbox.io/s/solitary-frog-2r0h9?file=/index.js

**Comment by lxfu1** [comment]
你提供的在线示例是正常的呀~

**Comment by iambool** [comment]
> 你提供的在线示例是正常的呀~

请看最底部的示例，第一个示例是正确的，第二个才是有问题的

**Comment by lxfu1** [comment]
V2 `slider: {x: {}}`
