### ISSUE TITLE
🧐[问题]Unhandled Rejection (Error): Module "./@ant-design/charts" does not exist in container. while loading "./@ant-design/charts" from webpack/container/reference/mf

### ISSUE THREAD

**Issue by guoqingshuai** [ant-design/ant-design-charts#1055]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1108" alt="图片" src="https://user-images.githubusercontent.com/29349771/147363293-6c5af7f9-e383-492a-9a80-165bd794d2b4.png">
请问我用npm 报错 但是我用yarn 添加 没有问题， 但是在代码引入报这个错误

**Comment by guoqingshuai** [comment]
自己的问题

**Comment by haojieZzz** [comment]
> 自己的问题

真辣鸡
