### ISSUE TITLE
使用双轴线图DualAxes时，设置yAxis中的min为0，左右两边的图会被遮盖

### ISSUE THREAD

**Issue by Wangyan-oo** [ant-design/ant-design-charts#1056]
### 🐛 bug 描述 
使用双轴线图DualAxes时，设置yAxis中的min为0，左右两边的图会被遮盖，这么处理这个被遮盖的问题？还有怎么设置两边有留白（例如echarts 中的boundaryGap属性）

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
<DualAxes
          loading={isLoading}
          height={300}
          data={[orderTrend, orderPayableTrend]}
          xField="date"
          yField={['count', 'count2']}
          xAxis={{
            title: {
              text: '订单趋势图',
              style: { fontSize: 16 },
            },
            label: {
              autoHide: true,
            },
          }}
          yAxis={{
            count: {
              min: 0,
            },
            count2: {
              min: 0,
            },
          }}
          meta={{
            count: {
              alias: '订单数',
            },
            count2: {
              alias: '订单金额（万元）',
            },
            yField: {
              range: [2,2],
            },
            xField: {
              range: [2, 2],
            },
          }}
          legend={{
            position: 'bottom',
          }}
          animation={ {
            appear: {
              animation: 'path-in',
              duration: 5000,
            },
          }}
          geometryOptions={[
            {
              smooth: true,
              point: {
                size: 5,
                shape: 'diamond',
              },
              label: {
                formatter: (datum) => {
                  return `${datum.count}`;
                },
              },
            },
            {
              smooth: true,
              color: '#D62A0D',
              point: {
                size: 5,
                shape: 'diamond',
              },
              label: {
                offsetY: 26,
                formatter: (datum) => {
                  return `${datum.count}`;
                },
              },
            },
          ]}
        />

### © 版本信息

- ant-design-charts 版本: ^1.2.14
- 浏览器环境：Chrome
- 开发环境 : Windows 10

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![1640585426(1)](https://user-images.githubusercontent.com/66104492/147441874-7a57c68a-4ef7-4843-a9d3-fabea7f4b042.jpg)

**Comment by lxfu1** [comment]
limitInPlot: false,

**Comment by Wangyan-oo** [comment]
> 你好，十分感谢。设置limitInPlot: false后标注点被遮挡的问题解决了；但还有一个问题想请教你，padding: [100, 200] 是设置左右两边的留白吗，我设置之后是这样的（如下图所示）
![1640595456(1)](https://user-images.githubusercontent.com/66104492/147454637-924009a4-a4a9-426a-90c9-ebeaca0f967c.jpg)

**Comment by lxfu1** [comment]
padding 逻辑和 css padding 类似， [100, 200] 等价于 [100, 200, 100, 200]

**Comment by Wangyan-oo** [comment]
> 如果我想这样的效果（如下图)，左右有些留白，需要设置什么属性呢,

![image](https://user-images.githubusercontent.com/66104492/147455725-460005f0-411f-4219-a41f-3ee075181b88.png)

**Comment by lxfu1** [comment]
https://charts.ant.design/zh/docs/manual/faq#4%E6%80%8E%E4%B9%88%E8%AE%BE%E7%BD%AE%E6%A8%AA%E8%BD%B4%E4%BB%8E-0-%E5%BC%80%E5%A7%8B

**Comment by Wangyan-oo** [comment]
设置之后，还是没有效果（第一张图是代码，第二张图是效果图）
![image](https://user-images.githubusercontent.com/66104492/147457643-4ccd6716-d835-4dbd-a472-05edc3c2341b.png)
![image](https://user-images.githubusercontent.com/66104492/147457686-8e70d999-91d7-44ac-b09b-676aad028b90.png)
