### ISSUE TITLE
🧐[问题] flowchart 自定义节点 连接锚点如何自定义配置？

### ISSUE THREAD

**Issue by jx-zyf** [ant-design/ant-design-charts#1061]
### 🧐  flowchart 自定义节点 连接锚点如何自定义配置？

如何配置节点为输入点（不能将边连接到此节点）和输出点（不能从此节点连接边）

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

```ts
nodePanelProps={{
  position: { width: 200, top: 40, bottom: 0, left: 0 },
  defaultActiveKey: ['custom'],
  registerNode: {
    title: '基础组件',
    nodes: [
      {
        component: IndicatorNode,
        popover: () => <div>基础组件'</div>,
        name: 'custom-node-indicator',
        width: 120,
        height: 50,
        label: '自定义节点',
        // ports: {
        //   items: [{ id: 'datasource-port', type: AnchorType.INPUT, group: AnchorGroup.RIGHT }]
        // },
        ports: [{ id: 'datasource-port', type: AnchorType.INPUT, group: AnchorGroup.RIGHT }],
      },
    ],
  },
}}
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/26456842/147627127-54e24f82-d38d-4b7e-a7e1-a5b47cb03dea.png)

**Comment by lxfu1** [comment]
```ts
  ports: {
    items: [
      { group: 'top', id: 'top1' },
      { group: 'bottom', id: 'bottom1' },
    ],
    groups: {
      top: {
        position: { name: 'top' },
        attrs: {
          circle: {
            r: 4,
            magnet: true,
            stroke: '#31d0c6',
            strokeWidth: 2,
            fill: '#fff',
            style: {
              visibility: 'hidden',
            },
          },
        },
        zIndex: 10,
      },
      bottom: {
        position: { name: 'bottom' },
        attrs: {
          circle: {
            r: 4,
            magnet: true,
            stroke: '#31d0c6',
            strokeWidth: 2,
            fill: '#fff',
            style: {
              visibility: 'hidden',
            },
          },
        },
        zIndex: 10,
      },
    },
  },
```

**Comment by jx-zyf** [comment]
谢谢

**Comment by jx-zyf** [comment]
> ```ts
>   ports: {
>     items: [
>       { group: 'top', id: 'top1' },
>       { group: 'bottom', id: 'bottom1' },
>     ],
>     groups: {
>       top: {
>         position: { name: 'top' },
>         attrs: {
>           circle: {
>             r: 4,
>             magnet: true,
>             stroke: '#31d0c6',
>             strokeWidth: 2,
>             fill: '#fff',
>             style: {
>               visibility: 'hidden',
>             },
>           },
>         },
>         zIndex: 10,
>       },
>       bottom: {
>         position: { name: 'bottom' },
>         attrs: {
>           circle: {
>             r: 4,
>             magnet: true,
>             stroke: '#31d0c6',
>             strokeWidth: 2,
>             fill: '#fff',
>             style: {
>               visibility: 'hidden',
>             },
>           },
>         },
>         zIndex: 10,
>       },
>     },
>   },
> ```

谢谢

**Comment by Luxiyaya** [comment]
![image](https://user-images.githubusercontent.com/33415408/158729573-16b2c085-f518-4949-8fc9-2677ed1490bb.png)
我想问下 这俩显示是配置的吗
