### ISSUE TITLE
分组柱状图如果数据为0的话，拿不到data？，点击空白的地方为undefined

### ISSUE THREAD

**Issue by yhwtest** [ant-design/ant-design-charts#1065]
有什么办法点击可以获取到x轴的字段吗
https://codesandbox.io/s/goofy-sara-wsn83?file=/index.js

**Comment by lxfu1** [comment]
https://charts.ant.design/zh/docs/api/case#%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A
