### ISSUE TITLE
🐛[BUG]关系图 FlowAnalysisGraph 中，layout属性为any，无明确声明属性关系，无法调整布局和自适应高度

### ISSUE THREAD

**Issue by UserRunway** [ant-design/ant-design-charts#1066]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
FlowAnalysisGraph 在使用时，现在我们需要进行布局调整和自适应高度，看到ts声明里面有layout这个属性，但是在用的时候，里面显示传入any。并且height在不传入时是500，我们无法进行自适应高度
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/96331325/147650029-8fd2e2ca-4828-4c34-801b-8f364e6e4f3f.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
期望能够明确指出layout里面的属性，和实现自适应高度
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
https://github.com/antvis/layout/blob/90a29de32abbd7d2a1dda55c9c72d1778d7c5fea/src/layout/dagre.ts#L15
