### ISSUE TITLE
🐛[BUG] DagreGraph 在 1.3.0 版本中被删除，项目未锁版本误升级时出现奔溃

### ISSUE THREAD

**Issue by coder-layne** [ant-design/ant-design-charts#1067]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

DagreGraph 在 1.3.0 版本中被删除，项目未锁版本误升级时出现奔溃

### © 版本信息

- ant-design-charts 版本: [e.g. 1.3.x]
- 浏览器环境 Chrome 96
- 开发环境 [ mac OS]

**Comment by lxfu1** [comment]
DagreGraph 和完善后的重复了，版本没管控好`[鞠躬]`

**Comment by coder-layne** [comment]
和哪个组件重复了，API 兼容么？目前我锁了版本，最好可以轻量地升级到最新版本

**Comment by lxfu1** [comment]
> 和哪个组件重复了，API 兼容么？目前我锁了版本，最好可以轻量地升级到最新版本

这个没法平滑升级，因为 API 设计不一致，最新版本已经恢复。
