### ISSUE TITLE
🧐Range bar based on time?

### ISSUE THREAD

**Issue by anako126n** [ant-design/ant-design-charts#1068]
### 🧐 
Is it possible to display the ranged bars based on time instead of numbers? 

After changing the values to time format , the graph renders correctly but there is no bars. 
![image](https://user-images.githubusercontent.com/3118846/147675694-9cda5a25-b750-489b-abe0-1817f52720d5.png)

```ts
  const data = [
    {
      type: 'two',
      values: ["2021-12-13 10:10:23","2021-12-13 10:15:34"],
    },
  ];

  const config = {
    data: data,
    meta: {
      values: {
        type: "timeCat",
        mask: "YYYY-MM-DD HH:mm:ss"
      }
    },
    xField: 'values',
    yField: 'type',
    isRange: true,
  };
```

**Comment by anako126n** [comment]
Just if anyone else is facing similar issue, the below works as desired. 

```ts
    meta: {
      range: {
        type: "time",
        min: "2021-12-13 10:00:00",
        max: "2021-12-13 11:00:00",
        mask: "YYYY-MM-DD HH:mm:ss",
        tickMethod: 'time'
      }
    },
```

**Comment by Hemanth7** [comment]
I am facing a similar problem.. cant solve it still

```
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Bar } from '@ant-design/plots';

const DemoBar = () => {
  const data = [
  { type: '1', values: ["2021-12-13 10:10:23","2021-12-13 10:15:34"] },
  { type: '1', values: ["2021-12-13 10:20:23","2021-12-13 10:25:34"] },
  ];
  const config = {
    data: data.reverse(),
    xField: 'values',
    yField: 'type',
    isRange: true,
    meta: {
      values: {
        type: "timeCat",
        mask: "YYYY-MM-DD HH:mm:ss"
      },
      range: {
        type: "time",
        min: "2021-12-13 10:00:00",
        max: "2021-12-13 11:00:00",
        mask: "YYYY-MM-DD HH:mm:ss",
        tickMethod: 'time'
      }
    },

  };
  return <Bar {...config} />;
};

ReactDOM.render(<DemoBar />, document.getElementById('container'));
```
Trying to render it directly here https://charts.ant.design/en/examples/bar/range#basic

**Comment by yuenzp** [comment]
> I am facing a similar problem.. cant solve it still
> 
> ```
> import React, { useState, useEffect } from 'react';
> import ReactDOM from 'react-dom';
> import { Bar } from '@ant-design/plots';
> 
> const DemoBar = () => {
>   const data = [
>   { type: '1', values: ["2021-12-13 10:10:23","2021-12-13 10:15:34"] },
>   { type: '1', values: ["2021-12-13 10:20:23","2021-12-13 10:25:34"] },
>   ];
>   const config = {
>     data: data.reverse(),
>     xField: 'values',
>     yField: 'type',
>     isRange: true,
>     meta: {
>       values: {
>         type: "timeCat",
>         mask: "YYYY-MM-DD HH:mm:ss"
>       },
>       range: {
>         type: "time",
>         min: "2021-12-13 10:00:00",
>         max: "2021-12-13 11:00:00",
>         mask: "YYYY-MM-DD HH:mm:ss",
>         tickMethod: 'time'
>       }
>     },
> 
>   };
>   return <Bar {...config} />;
> };
> 
> ReactDOM.render(<DemoBar />, document.getElementById('container'));
> ```
> 
> Trying to render it directly here https://charts.ant.design/en/examples/bar/range#basic

Try to use this tick method

`tickMethod: ()=> ["2021-12-13 12:00:00 am", "2021-12-13 03:00:00 am", "2021-12-13 06:00:00 am", "2021-12-13 09:00:00 am", "2021-12-13 12:00:00 pm", "2021-12-13 03:00:00 pm", "2021-12-13 06:00:00 pm", "2021-12-13 09:00:00 pm", "2021-12-14 12:00:00 am"],`

**Comment by yuenzp** [comment]
> I am facing a similar problem.. cant solve it still
> 
> ```
> import React, { useState, useEffect } from 'react';
> import ReactDOM from 'react-dom';
> import { Bar } from '@ant-design/plots';
> 
> const DemoBar = () => {
>   const data = [
>   { type: '1', values: ["2021-12-13 10:10:23","2021-12-13 10:15:34"] },
>   { type: '1', values: ["2021-12-13 10:20:23","2021-12-13 10:25:34"] },
>   ];
>   const config = {
>     data: data.reverse(),
>     xField: 'values',
>     yField: 'type',
>     isRange: true,
>     meta: {
>       values: {
>         type: "timeCat",
>         mask: "YYYY-MM-DD HH:mm:ss"
>       },
>       range: {
>         type: "time",
>         min: "2021-12-13 10:00:00",
>         max: "2021-12-13 11:00:00",
>         mask: "YYYY-MM-DD HH:mm:ss",
>         tickMethod: 'time'
>       }
>     },
> 
>   };
>   return <Bar {...config} />;
> };
> 
> ReactDOM.render(<DemoBar />, document.getElementById('container'));
> ```
> 
> Trying to render it directly here https://charts.ant.design/en/examples/bar/range#basic

Use xAxis instead of meta.

```
xAxis: {
      type: "time",
      min: "2021-12-13 00:00:00 am", 
      max: "2021-12-14 12:00:00 am", 
      mask: "hh:mm:ss a",
      tickMethod: ()=> ["2021-12-13 12:00:00 am", "2021-12-13 03:00:00 am", "2021-12-13 06:00:00 am", "2021-12-13 09:00:00 am", "2021-12-13 12:00:00 pm", "2021-12-13 03:00:00 pm", "2021-12-13 06:00:00 pm", "2021-12-13 09:00:00 pm", "2021-12-14 12:00:00 am"],
    },

**Comment by Hemanth7** [comment]
@yuenzp Thank you so much! works like a charm
