### ISSUE TITLE
请教一下，多折线点击当前的点，怎么拿到当前点的数据

### ISSUE THREAD

**Issue by yhwtest** [ant-design/ant-design-charts#1069]
const productJump = (plot) => {
    console.log(plot,'plot');
    plot.on("plot:click", (evt) => {
     const { x, y } = evt;
     const tooltipData = plot.chart.getTooltipItems({ x, y });
     console.log(tooltipData,'tooltipData');
   });
 }
这样就是4个数据了

https://charts.ant.design/zh/examples/line/multiple#marker-active

**Comment by lxfu1** [comment]
element:click
