### ISSUE TITLE
🐛[BUG] [折线图初始化代码时会出现叠在一起的问题]

### ISSUE THREAD

**Issue by zb-0819** [ant-design/ant-design-charts#107]
### bug 描述   [折线图初始化代码时会出现叠在一起的问题] 
折线图初始化代码时会出现叠在一起的问题

### 📷 复现步骤
刷新页面或执行官方代码
![image](https://user-images.githubusercontent.com/22267596/86573835-829d1e00-bfa7-11ea-8ea7-6a5a4161c2e8.png)

### 🏞 期望结果
正常展示

### 💻 复现代码
无

### © 版本信息
最新版

- ant-design-charts 版本: [e.g. 0.9.6]
- 浏览器环境 [83.0.4103.116（正式版本） （64 位）]
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
padding 设置大一点或者用 auto
