### ISSUE TITLE
使用代码控制Pie组件的高亮分类

### ISSUE THREAD

**Issue by zhi114** [ant-design/ant-design-charts#1073]
### 🚑 
![image](https://user-images.githubusercontent.com/4452972/148016556-45606f79-667b-416f-8549-4b85d4218ee4.png)
如图所示，由于右侧的列表略微复杂，就没有使用Pie的legend api，现在想要实现选择右侧列表的某一项时，左侧的Pie对应的分类能够高亮起来。请问这种功能现在是否可以实现？

**Comment by lxfu1** [comment]
```ts
onReady: (plot)=>{
  // TODO
  plot.setState('selected', (item)=>{
    return item.type === '分类四'
  })
}
```

**Comment by zhi114** [comment]
> ```ts
> onReady: (plot)=>{
>   // TODO
>   plot.setState('selected', (item)=>{
>     return item.type === '分类四'
>   })
> }
> ```

**Comment by zhi114** [comment]
> ```ts
> onReady: (plot)=>{
>   // TODO
>   plot.setState('selected', (item)=>{
>     return item.type === '分类四'
>   })
> }
> ```

感激不尽，但是这个是初始化加载的设置吧？如何在运行时进行设置呢？activeAdd是我定义的state，但是state变化时，并不会触发callback..
`<Pie
      {...config}
      chartRef={ref}
      fallback={
          <div className="loading-pie">
              <Spin></Spin>
          </div>
      }
      onReady={(plot: Options) => {
          plot.setState('selected', (item: ProjectDistributionItem)=>{
              console.log(activeAdd);
              return item.symbolAddr === activeAdd;
          })
      }}
  />`

**Comment by lxfu1** [comment]
你点击的时候去调用， 把  '分类四' 换成你想要高亮的数据传入即可。
plot.setState('selected', (item)=>{
    return item.type === '分类四'
  })

**Comment by zhi114** [comment]
thanks a lot!

**Comment by StevenRogers** [comment]
如何在运行中进行多次单选设置呢

**Comment by DPGZl** [comment]
@lxfu1 请问hover 自定义图例时，想实现内置action: `element-active` 的效果，该怎么做呢？
我尝试这样做：
1. 在 onReady 中注册交互：
```
registerInteraction('custom-legend-active', {
    start: [{ trigger: 'legendItemHover', action: ['element:active'] }],
    end: [{ trigger: 'mouseleave', action: ['element:inactive'] }],
})
```
2. 在 Pie props 中加上：
`interactions: [{ type: 'custom-legend-active' }]`
3. 鼠标 hover Legend Item 时触发（plot 是在 onReady 中获取的 plot 实例）：
`plot.emit('custom-legend-active')`

问题：
1. 在第一步中调用 registerInteraction 时，正确的 `action` 应该是什么？
2. 这样注册自定义交互事件对吗？能生效吗？
