### ISSUE TITLE
多折线特殊标注了点，onclick如果拿到当前点的数据

### ISSUE THREAD

**Issue by yhwtest** [ant-design/ant-design-charts#1075]
https://codesandbox.io/s/boring-voice-9zjwr?file=/index.js
多折线特殊标注了点，onclick如果拿到当前点的数据
  const productJump = (plot) => {
    plot.on("click", (evt) => {
       if(type !== 'click') return ''
       try {
        const { x, y } = evt;
        const data = plot.chart.getTooltipItems({ x, y });
        console.log(data,'data');
        console.log(evt,'evt');
        const clickData = data.filter(
          (item) => evt.data.data[0].category === item.data.category
        );
        console.log(clickData[0].data,'clickData[0]?.data');
        handelTestOk(clickData[0]?.data);
       } catch (error) {
         console.log(error);
       }
    });
  };
这样写的话特殊点的坐标拿不到，且会覆盖下一个邻近未标注为特殊点的数据？

![image](https://user-images.githubusercontent.com/86184329/148045539-81cbd1f9-7ce9-4727-810e-5186e4fd483b.png)

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/1071
