### ISSUE TITLE
🧐[问题]Question regarding the format and order of dates on x-axis

### ISSUE THREAD

**Issue by XiZ-Foresters** [ant-design/ant-design-charts#1076]
Hi there,

I'm using x-axis to display the dates, but noticed the format has to be in "yyyy-MM-dd". Is it possible to display them in a different format, such as "dd-MM-yyyy"?

Second question is to do with the order of data on x-axis. For example, if the data I supply to the chart is sorted in ascending order of date, is there a way to make the chart to be rendered in descending order of date?

Thanks in advance.

**Comment by lxfu1** [comment]
```ts
xAxis: {
  type: 'cat',
  label: {
    formatter: (label) => xxx
    }
}
```

**Comment by lxfu1** [comment]
Second question, can you provide some sample code?

**Comment by XiZ-Foresters** [comment]
Sure, for example in the below code, the dates on x-axis is in ascending order. Is there possible to re-order the data so they're displayed in descending order, eg. 01-09-2016 -> 01-01-2015 -> 01-05-2013 -> 01-09-2011?

import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Area } from '@ant-design/charts';

const DemoArea = () => {
  const [data, setData] = useState([]);

  useEffect(() => {
    asyncFetch();
  }, []);

  const asyncFetch = () => {
    fetch('https://gw.alipayobjects.com/os/bmw-prod/1d565782-dde4-4bb6-8946-ea6a38ccf184.json')
      .then((response) => response.json())
      .then((json) => setData(json))
      .catch((error) => {
        console.log('fetch data failed', error);
      });
  };
  const config = {
    data,
    xField: 'Date',
    yField: 'scales',
    xAxis: {
      range: [0, 1],
      tickCount: 5,
      label: {
        formatter: (label) => {
          const dateArray = label.split('-');
          const date = new Date(dateArray[0], dateArray[1], 1);
          return String(date.getDate()).padStart(2, '0') + "-" + String(date.getMonth()).padStart(2, '0') + "-" + date.getFullYear();
        }
      }
    },
    areaStyle: () => {
      return {
        fill: 'l(270) 0:#ffffff 0.5:#7ec2f3 1:#1890ff',
      };
    },
  };

  return <Area {...config} />;
};

ReactDOM.render(<DemoArea />, document.getElementById('container'));


![image](https://user-images.githubusercontent.com/94545704/148229851-df82e443-850d-40ed-bc6b-23438675eb6b.png)

**Comment by lxfu1** [comment]
```ts
const config = {
    data: [
      {
        "Date": "2010-04",
        "scales": 1818
      },  
      {
        "Date": "2010-03",
        "scales": 1720
      },
       {
        "Date": "2010-02",
        "scales": 1850
      },
       {
        "Date": "2010-01",
        "scales": 1998
      },
    ],
    xField: 'Date',
    yField: 'scales',
    xAxis: {
      type: 'cat',
      range: [0, 1]
    },
  };
```

**Comment by lxfu1** [comment]
Sort Data.
