### ISSUE TITLE
为什么demo网站的demo点开全是404页面🧐[问题]

### ISSUE THREAD

**Issue by cuiyimeng** [ant-design/ant-design-charts#108]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我想查看例如图表联动这个demo,点开后却是404页面
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://charts.ant.design/demos/advanced#%E5%9B%BE%E8%A1%A8%E8%81%94%E5%8A%A8

**Comment by lxfu1** [comment]
额 图表联动demo丢失了 你先看看G2PLot 的 ～

**Comment by ashuai** [comment]
这个问题还没有修复吗？

**Comment by lxfu1** [comment]
1.0 已经修复，欢迎使用。
