### ISSUE TITLE
👑 [需求] 柱形图的数据过少， 不居中显示

### ISSUE THREAD

**Issue by sjm-study** [ant-design/ant-design-charts#1080]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
柱形图的数据过少时，能否不居中显示柱形图
![企业微信截图_16414550648388](https://user-images.githubusercontent.com/50009276/148347224-bebaf8c1-b852-45b3-ac90-695d98226666.png)

**Comment by lxfu1** [comment]
正常是会居中显示的，特殊情况可以处理一下配置 https://charts.ant.design/zh/docs/manual/faq#4%E6%80%8E%E4%B9%88%E8%AE%BE%E7%BD%AE%E6%A8%AA%E8%BD%B4%E4%BB%8E-0-%E5%BC%80%E5%A7%8B
