### ISSUE TITLE
🐛[BUG] 使用文档中的interactions配置无法生效且报错

### ISSUE THREAD

**Issue by LMarnon** [ant-design/ant-design-charts#1081]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
https://charts.ant.design/zh/docs/api/options/interactions#%E9%85%8D%E7%BD%AE%E4%BA%A4%E4%BA%92
参考该示例在demo中进行配置，页面崩溃
### 🏞 期望结果 [描述你原本期望看到的结果]
可以正常配置 interactions。
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

```js
// 修改 tooltip 触发事件
interactions: [
  { 
    type: 'tooltip',
    cfg: { start: [{ trigger: 'element:click', action: 'tooltip:show' }] } 
  }
]
```

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
Update.
