### ISSUE TITLE
🧐[flowchart 更新节点信息]

### ISSUE THREAD

**Issue by jx-zyf** [ant-design/ant-design-charts#1097]
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

![image](https://user-images.githubusercontent.com/26456842/148917456-7a69b6dd-c47c-41de-8437-e23dcc281674.png)

使用 updateNodeKeyById 未生效

**Comment by jx-zyf** [comment]
如何手动删除边呢？
我看到 graph实例上有 removeEdge方法，但好像并不生效。

原始需求是 不允许边的target是输入节点，不允许边的source是输出节点，一个输出节点只能有一个输入。

麻烦帮忙看一下，谢谢！

**Comment by lxfu1** [comment]
不要截图，点击 codesandbox直接提供在线demo，或者加钉钉沟通
![image](https://user-images.githubusercontent.com/31396322/149162379-acc52bdf-9b21-404d-aa41-cec3eedc6dbc.png)

**Comment by jx-zyf** [comment]
> 不要截图，点击 codesandbox直接提供在线demo，或者加钉钉沟通 ![image](https://user-images.githubusercontent.com/31396322/149162379-acc52bdf-9b21-404d-aa41-cec3eedc6dbc.png)

https://codesandbox.io/s/compassionate-tesla-54e5g?file=/index.js

**Comment by lxfu1** [comment]
```ts
 graphObj && graphObj.updateNodeKeyById(node.id, "data", {
        label: "test"
      });
```

**Comment by jx-zyf** [comment]
> 如何手动删除边呢？ 我看到 graph实例上有 removeEdge方法，但好像并不生效。
> 
> 原始需求是 不允许边的target是输入节点，不允许边的source是输出节点，一个输出节点只能有一个输入。
> 
> 麻烦帮忙看一下，谢谢！

如何手动删除边呢？

**Comment by jx-zyf** [comment]
> ```ts
>  graphObj && graphObj.updateNodeKeyById(node.id, "data", {
>         label: "test"
>       });
> ```

可以了，谢谢！
