### ISSUE TITLE
🧐[问题]请问柱状图(Column)组件能否支持横向的布局

### ISSUE THREAD

**Issue by frostace** [ant-design/ant-design-charts#1107]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在柱状图的api里查阅了一下，没有找到类似layout/align之类的字段，不知道Column组件是不是不支持横向的布局，类似下图：

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
无代码，纯咨询

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/32981745/149727249-d4b9edf2-a05d-49e1-9a2d-730f7a77f3a5.png)

**Comment by visiky** [comment]
直接使用 Bar 组件？

**Comment by frostace** [comment]
get，多谢，我以为bar组件本质上和column组件应该是同一个
