### ISSUE TITLE
Module '"@antv/g2plot"' has no exported member 'Violin'🐛[BUG]

### ISSUE THREAD

**Issue by suyue0731** [ant-design/ant-design-charts#1112]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
@antv/g2plot 已经把Violin和ViolinOptions移除了

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
import { Violin as G2plotViolin, ViolinOptions as G2plotConfig } from '@antv/g2plot';
### © 版本信息
"@antv/g2plot": "^2.2.11"
"@ant-design/plots": "^1.0.7"

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/18397351/150315644-c4b8ffc7-1d73-4424-92a5-35c9f742b81a.png)

**Comment by suyue0731** [comment]
/ant-design-charts/packages/plots/src/components/violin/index.tsx 
这个文件引用了@antv/g2plot的Violin组件，现在已经找不到了

**Comment by lxfu1** [comment]
https://charts.ant.design/zh/examples/more-plots/violin#basic

**Comment by suyue0731** [comment]
> https://charts.ant.design/zh/examples/more-plots/violin#basic

我不是在问Violin组件怎么用，而是想反馈@antv/g2plot里删了一些东西，包括Venn，Violin，CirclePacking什么的，但是ant-design/charts里面还对这些组件有依赖。

你们自己的代码master拉下来，eslint都过不了

**Comment by visiky** [comment]
你确定你看了 G2Plot 删了？

**Comment by suyue0731** [comment]
![image](https://user-images.githubusercontent.com/18397351/150327668-7e92acef-76d9-4102-9eb1-0b592c122c8e.png)

**Comment by suyue0731** [comment]
这是从你们的master拉下来之后install的截图

**Comment by suyue0731** [comment]
> 先检查版本问题吧，或者就去 G2Plot 仓库 master 分支看，而不是看自己本地的代码

最开始是2.3.17，我看ant-design/charts写明的依赖是2.2.11，就把之前的删了，强制指定了2.2.11，发现也不对

**Comment by suyue0731** [comment]
g2的changelog里有这么一句：“Venn  以及 Violin  几何标记暂时移除，后续考虑以更好的方式支持。”

**Comment by visiky** [comment]
> g2的changelog里有这么一句：“Venn 以及 Violin 几何标记暂时移除，后续考虑以更好的方式支持。”

G2 !== G2Plot

**Comment by visiky** [comment]
> > 先检查版本问题吧，或者就去 G2Plot 仓库 master 分支看，而不是看自己本地的代码
> 
> 最开始是2.3.17，我看ant-design/charts写明的依赖是2.2.11，就把之前的删了，强制指定了2.2.11，发现也不对

^version

兼容某个版本

版本号中最左边的非0数字的右侧可以任意

如果缺少某个版本号，则这个版本号的位置可以任意

如：^1.1.2 ，表示>=1.1.2 <2.0.0，可以是1.1.2，1.1.3，.....，1.1.n，1.2.n，.....，1.n.n

如：^0.2.3 ，表示>=0.2.3 <0.3.0，可以是0.2.3，0.2.4，.....，0.2.n

如：^0.0，表示 >=0.0.0 <0.1.0，可以是0.0.0，0.0.1，.....，0.0.n

**Comment by suyue0731** [comment]
> > g2的changelog里有这么一句：“Venn 以及 Violin 几何标记暂时移除，后续考虑以更好的方式支持。”
> 
> G2 !== G2Plot

G2Plot依赖了G2呀

"@antv/g2": "^4.1.0-beta.20", 这是G2Plot v2.2.11的package.json

**Comment by suyue0731** [comment]
> > > 先检查版本问题吧，或者就去 G2Plot 仓库 master 分支看，而不是看自己本地的代码
> > 
> > 
> > 最开始是2.3.17，我看ant-design/charts写明的依赖是2.2.11，就把之前的删了，强制指定了2.2.11，发现也不对
> 
> ^version
> 
> 兼容某个版本
> 
> 版本号中最左边的非0数字的右侧可以任意
> 
> 如果缺少某个版本号，则这个版本号的位置可以任意
> 
> 如：^1.1.2 ，表示>=1.1.2 <2.0.0，可以是1.1.2，1.1.3，.....，1.1.n，1.2.n，.....，1.n.n
> 
> 如：^0.2.3 ，表示>=0.2.3 <0.3.0，可以是0.2.3，0.2.4，.....，0.2.n
> 
> 如：^0.0，表示 >=0.0.0 <0.1.0，可以是0.0.0，0.0.1，.....，0.0.n

不用你跟我科普，我是想说写在你们package.json里2.2.11这个版本的G2Plot里就已经缺少上面提到的那些组件和类型了，另外你回复我之前能不能把github仓库ant-design/charts的master拉下来install一下看看是不是缺了东西，我觉得我们在这浪费时间

**Comment by suyue0731** [comment]
再回复一次吧，首先明确一个事实，@antv/g2plot 2.3.17版本是有问题的，里面缺了Violin，Venn等组件，最新的2.4.7是好的

然后，ant-design-charts master的代码是有问题的，问题出在packages/plots/package-lock.json
这里面锁了个@antv/g2plot的2.3.17版本
`"@antv/g2plot": {
      "version": "2.3.17",
      "resolved": "http://npm.zhenguanyu.com/@antv/g2plot/download/@antv/g2plot-2.3.17.tgz",
      "integrity": "sha1-jbiJ4IPnfEkAPhcjIKNQBmgH4os=",
      "requires": {
        "@antv/event-emitter": "^0.1.2",
        "@antv/g2": "^4.1.0",
        "d3-hierarchy": "^2.0.0",
        "d3-regression": "^1.3.5",
        "size-sensor": "^1.0.1",
        "tslib": "^2.0.3"
      }
    },`

然后是npm install @ant-design/charts的问题，@ant-design/plots的package.json里指明了"@antv/g2plot": "^2.2.11"，按照npm版本匹配原则，理论上应该能匹配到@antv/g2plot的最新版本2.4.7，但实际上还是安装了2.3.17，这里是我比较迷惑的点，明明node_modules里面没有package-lock.json，为什么还是锁到了2.3.17这个版本？我开始怀疑是我npm cache的问题，但清除npm cache之后重新装还是2.3.17。

随后我强行在自己的项目里把@antv/g2plot的版本指定为2.4.7，重新安装后问题解决

**Comment by visiky** [comment]
一般来说，不会存 package-lock.json 文件（我去看了 Charts 的master，没有提交 lock 文件）所以你自己本地的 lock 删除就好了，没有什么必要，就不要 lock

**Comment by visiky** [comment]
一般来说，不会存 lock 文件。我看了下 Charts 的 master 代码，并没有 package-lock 文件。

没有特殊情况的话，就用最新的代码好了。

**Comment by suyue0731** [comment]
> 一般来说，不会存 lock 文件。我看了下 Charts 的 master 代码，并没有 package-lock 文件。
> 
> 没有特殊情况的话，就用最新的代码好了。

那应该是我没注意是我自己安装留下来的lock文件，但是我自己遇到的问题还是没法解释。。为何我本地总是自动安装2.3.17这个版本

**Comment by suyue0731** [comment]
我和朋友测试的结果都是本地安装@ant-design/charts后，@antv/g2plot的版本都是2.3.17这个有问题的版本，你那边能帮忙测试一下吗？

**Comment by lxfu1** [comment]
你这个可能是其它包依赖了 G2Plot，建议删除 node_moduels, npm i @ant-design/charts -S 看下依赖。
