### ISSUE TITLE
🧐[问题]flowchart 异步获取的画布数据，通过setState的方式更新，画布未重新渲染

### ISSUE THREAD

**Issue by jx-zyf** [ant-design/ant-design-charts#1117]
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

https://stackblitz.com/edit/react-dzc5vu

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

或者有没有什么api可以手动更新画布data？

**Comment by lxfu1** [comment]
更新一下
```ts
onReady={(graph, app) => {
  // graph.loadData(DATA);
}}
```
