### ISSUE TITLE
🐛[BUG] 安装依赖出错

### ISSUE THREAD

**Issue by weiman-133** [ant-design/ant-design-charts#1119]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

最近安装chart总是报错，希望能稳定一点
![image](https://user-images.githubusercontent.com/86717611/150906591-7d0056da-2b3b-4281-823b-4e428c294bb4.png)

**Comment by liuvigongzuoshi** [comment]
@weiman-133 没有问题，npm 上刚发 L7 的版本，你用的 yarn 应该是镜像没有同步完成
