### ISSUE TITLE
👑 关于可配置参数的文档说明不明确和不清晰

### ISSUE THREAD

**Issue by hxguo** [ant-design/ant-design-charts#112]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
我从隔壁的echarts转过来，不得不说echarts比较容易入手很大优势在于它的文档写的好，尤其是关于所有可配置参数的说明，没法说，对于开发人员一目了然。
但是它的UI方面确实让人不喜欢，所以转g2,但是g2的文档全看完一遍还是一头雾水。基础理论部分花了很大长文讲，这无可厚非也有助于理解g2，但是这每种图形可配置参数的说明就懵逼了。
这种结合demo说明可配置参数的模式，可以理解，但是让人看不懂全局或者某种图像整体的可配置的参数尤其是图形的公共配置部分，还有就是有些参数的配置都是点到为止，有些样式、属性就只提到，没讲具体有哪些。完全不知道怎么去配置出符合实际需求的图形。
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
G2整体还是比echarts差不了多少，就是文档不利于开发者。希望文档能够改进一下，建议从全局参数到图形参数再到扩展参数进行说明，属性可配置的内容尽量介绍全吧。
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
如果说大家都觉得文档可读性没问题，就当我没说吧。

**Comment by lxfu1** [comment]
我们正在重构文档

**Comment by Maple512** [comment]
顶一下
