### ISSUE TITLE
🧐[问题]柱状图click事件如何添加选中的效果？和鼠标hover一样的效果

### ISSUE THREAD

**Issue by dumbbell0720** [ant-design/ant-design-charts#113]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我需要动态的去选中某一个柱子
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/30950222/87526468-6f800180-c6bd-11ea-8110-7cd3dfa28e43.png)

**Comment by WangJM001** [comment]
+1，一样的问题

**Comment by lxfu1** [comment]
V 1.0  参考： https://charts.ant.design/demos/pie/#%E9%A5%BC%E5%9B%BE-%E8%AE%BE%E7%BD%AE%E6%9D%A1%E4%BB%B6%E7%8A%B6%E6%80%81
