### ISSUE TITLE
🧐[问题] 请教风险转化标签是否能支持反向？

### ISSUE THREAD

**Issue by thelaurelyy** [ant-design/ant-design-charts#1135]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

1、现在官网上的风险转化标签，由于业务需要，最近日期的数据在最前面，因此风险转化标签需要从右向左（反向），请问如何实现呢？
2、当部分刻度对应统计数据为0时，是否能将转化标签隐藏？

期待回复，谢谢！

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

https://charts.ant.design/zh/examples/column/basic#conversion-tag

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/27723220/151473885-ca46e9cb-251e-4466-b02b-05370e07b50f.png)

**Comment by lxfu1** [comment]
目前不支持配置，但可以通过 annotations 自定义实现。

**Comment by lxfu1** [comment]
参考 [2.0 自定义实现](https://github.com/ant-design/ant-design-charts/blob/v2/packages/plots/src/core/annotation/conversion-tag.ts)
