### ISSUE TITLE
🐛[BUG]最新版本(1.3.5)无法运行官网示例，导致整个应用白屏,当data为[]且配置了annotations包含line或者text类型的时候会报Cannot read properties of null (reading 'addGroup')

### ISSUE THREAD

**Issue by upwinder** [ant-design/ant-design-charts#1137]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

最新版本(1.3.5)无法运行官网示例，导致整个应用白屏,当data为[]且配置了annotations包含line或者text类型的时候会报Cannot read properties of null (reading 'addGroup')，然后整个页面白屏挂掉

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

比如运行这个官网示例：
https://charts.ant.design/zh/examples/area/basic#basic-annotation

当异步ajax还没有加载到数据的时候，此时data为[]，就可以复现出现以下错误：

![20220204175054](https://user-images.githubusercontent.com/2017107/152508812-97d7b36c-9ab2-44bb-91bc-fb2fd0b7dfcc.jpg)

### © 版本信息

- ant-design-charts 版本: [1.3.5]
- 浏览器环境[edge]
- 开发环境 [mac OS]

**Comment by truonglx-dev** [comment]
you can try comment annotations in config
