### ISSUE TITLE
🧐[问题]当线只有一条的时候，怎么展示图例

### ISSUE THREAD

**Issue by wj86611199** [ant-design/ant-design-charts#1146]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://user-images.githubusercontent.com/17016971/153145658-5b7373b3-47dd-474c-aabb-57424ac879b5.png)
希望在这里显示这条线的图例，这个怎么做啊

**Comment by lxfu1** [comment]
单图不支持图例配置
