### ISSUE TITLE
🧐 @ant-design/charts在IE11下出现兼容性问题

### ISSUE THREAD

**Issue by gaoxiong1230** [ant-design/ant-design-charts#115]
### 🧐 在IE11下使用图表插件时，d3-regression箭头语法出错导致程序无法运行，页面空白，umi的targets配置无效
![image](https://user-images.githubusercontent.com/35324346/87646487-7ff9b000-c781-11ea-95e3-fdc908f26f50.png)
![image](https://user-images.githubusercontent.com/35324346/87646556-94d64380-c781-11ea-8e05-7813d9e10fd0.png)
![image](https://user-images.githubusercontent.com/35324346/87649586-1084c000-c783-11ea-8ffd-17b24253a6e0.png)

### 🚑 版本信息如下：
![image](https://user-images.githubusercontent.com/35324346/87647531-fbf3f800-c781-11ea-9348-56ab3a289692.png)

### 复现步骤：
1. 使用npm create umi创建umi项目，项目类型选择app，开启dva和typescript支持
2. 使用yarn add @ant-design/charts添加图表插件库
3. 使用yarn命令下载插件库
4. 修改src/pages/index.tsx，使用官网上任一图表示例代码替换内容
5. 修改.umirc.ts文件，添加targets:{ie:11}
6. 使用yarn start启动，并在IE11浏览器访问，页面空白，F12调试时发现d3-regression包报错

**Comment by lxfu1** [comment]
参考这个 https://g6.antv.vision/zh/docs/manual/FAQ/supportIE  g6换成 d3-regression 即可

**Comment by 0123cf** [comment]
解决方案里面，写了umi用browserslist， 不过，为啥这个是deprecated了的，用不了呀。那应该是用`targets`代替，不过好像没啥用。

**Comment by lxfu1** [comment]
把 @antv/g6 换成有兼容性问题的包即可
```ts
{
    test: /\.js$/,
    loader: 'babel-loader',
    include: [resolve('src'), resolve('node_modules/@antv/g6')]
}
```

**Comment by 0123cf** [comment]
补充一下， umi的targets去兼容ie，记得加nodeModulesTransform这个属性。type为all就是所有的，可以为none再加补充。不过，有一点问题是，无法错误没办法，引入的时候需要引入lib包。es里面的还是会报错，如下。

import Area, { AreaConfig } from '@ant-design/charts/lib/area/index';

**Comment by 0123cf** [comment]
> 把 @antv/g6 换成有兼容性问题的包即可
> 
> ```ts
> {
>     test: /\.js$/,
>     loader: 'babel-loader',
>     include: [resolve('src'), resolve('node_modules/@antv/g6')]
> }
> ```

umi是隐藏webpack配置的，也不适合打开配置，话说为啥antv的lib包不是编译过的.

**Comment by 0123cf** [comment]
还有一个问题， 
```
nodeModulesTransform: {
    type: 'none',
    exclude: ['@ant-design'],
  },
```

我这样配置是无效的，请问exclude我要怎么配置ant-design-charts.

**Comment by 0123cf** [comment]
> 还有一个问题，
> 
> ```
> nodeModulesTransform: {
>     type: 'none',
>     exclude: ['@ant-design'],
>   },
> ```
> 
> 我这样配置是无效的，请问exclude我要怎么配置ant-design-charts.

@lxfu1

**Comment by lxfu1** [comment]
https://github.com/lxfu1/charts-ie
