### ISSUE TITLE
柱状图Y轴怎样设置最小刻度为1🧐[问题]

### ISSUE THREAD

**Issue by God-gill** [ant-design/ant-design-charts#1150]
### 🧐 问题描述 [详细地描述问题，让大家都能理解
因为数据不可能为小数，所以产品让坐标轴的刻度不能出现小数、

**Comment by lxfu1** [comment]
```ts
 yAxis: {
  tickInterval: 10
},
```

**Comment by God-gill** [comment]
谢谢

**Comment by Cherry860** [comment]
__How to dynamically set the minimum scale? If the data reaches 100 and tickInterval is set to 1, the interaction is bad.

**Comment by lxfu1** [comment]
const tickInterval =  fn;

**Comment by zhouchunguang2020** [comment]
> 

这样设置的话，刻度值全部为固定值了，能不能设置最小刻度为1？
