### ISSUE TITLE
🧐[问题]多折线图或者分组/堆叠柱图如何只显示某一条线或柱子的数值标签

### ISSUE THREAD

**Issue by wj86611199** [ant-design/ant-design-charts#1151]
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image](https://user-images.githubusercontent.com/17016971/153328573-bb16e847-dd7b-4cf6-9108-1415fd4eaf4d.png)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
如何实现echarts这样的功能，我只需要某一条线的数值标签显示，其他线的数值标签不显示

**Comment by lxfu1** [comment]
```ts
    label: {
      formatter: (...args)=>{
        return  xxx
      }
    },
```
