### ISSUE TITLE
🧐[问题]大佬们，求教最值问题

### ISSUE THREAD

**Issue by wj86611199** [ant-design/ant-design-charts#1152]
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image](https://user-images.githubusercontent.com/17016971/153339105-7266db68-3ac4-4c09-a92d-eb5d9f174846.png)

如何像echarts一样指定每条线的最大值最小值，并且自定义图标样式

**Comment by lxfu1** [comment]
看下annotations , https://charts.ant.design/zh/examples/component/annotation#text-annotation1

**Comment by tanggd** [comment]
1. 如果只是用文字标记最大值，可以这样配置：
```
// 假设最大值
const max = 123;
// chart配置
const config = {
// ...
      label: {
                  formatter: (l, a) => {
                      if (l.xxx === max) {
                          return l.xxx;
                      }
                  },
      },
// ...
}
```
如图：
<img width="581" alt="image" src="https://user-images.githubusercontent.com/23456667/188534590-bbc0c6d4-bbe5-4c4c-b4da-baf9fec410ec.png">


2. 如果需要增加图标，可以参考例子增加marker：https://g2plot.antv.vision/zh/examples/line/basic#line-with-data-marker
