### ISSUE TITLE
🧐[问题]基本折线图，数据条数超过120条之后，显示的首尾连线如何去掉？

### ISSUE THREAD

**Issue by rawbin-** [ant-design/ant-design-charts#1157]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/8169783/153797163-3291248e-7e86-488f-988f-f6604cf715cd.png">

[复现代码](https://codesandbox.io/s/heuristic-carson-woqp7)

**Comment by lxfu1** [comment]
复现代码有问题，确认下是不是数据重复了或是数据类型不对，xField 需要 string 类型

**Comment by rawbin-** [comment]
> 

数据没问题的  https://codesandbox.io/s/heuristic-carson-woqp7

**Comment by lxfu1** [comment]
数据重复了
1： "series": "02-14 10:49:30",
2： "series": "02-14 10:49:35",

**Comment by rawbin-** [comment]
> 数据重复了 1： "series": "02-14 10:49:30", 2： "series": "02-14 10:49:35",

这个是每5s一次的采样数据，怎么算做重复的呢，其实任意删除两条数据都可以复现，跟这个120数量有关系

**Comment by visiky** [comment]
有两个这个数据：
<img width="383" alt="image" src="https://user-images.githubusercontent.com/15646325/154036309-8b64de09-f160-4624-b91f-d55ad27bae34.png">

看下这个 [demo](https://codesandbox.io/s/shu-ju-chong-fu-s8ln7) 的注释部分

**Comment by rawbin-** [comment]
> 
还真是，尴尬了，多谢多谢~
