### ISSUE TITLE
🧐[问题] Antv in deps and bundle size

### ISSUE THREAD

**Issue by Endevir** [ant-design/ant-design-charts#116]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Hi everybody!
I'm using ant-design/charts for a small project and recently I've run into a problem with uncommonly big bundle size. A quick investigation has shown, that npm package @ant-design/charts uses @antv/g2-plot, which brings now (as it seems) almost entire AntV library with it. Is it a bug or maybe there is some way to omit some unnecessary antv dependencies?

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
Well, actually, the simplest example to represent is to show bundle size with different versions of @ant-design/charts:

####  Bundle size with latest v0.9.7
![Bundle size with latest v0.9.7](https://user-images.githubusercontent.com/10272238/87729335-5e221c80-c7c5-11ea-8dfa-7babf143efdf.png)

####  Bundle size with earlier v0.9.6
![Bundle size with v0.9.6](https://user-images.githubusercontent.com/10272238/87729557-f7e9c980-c7c5-11ea-85ec-745d4b7c2e7e.png)

**Comment by ChenYu29** [comment]
请问你是怎么优化这个打包的体积呢， 我也遇到同样的问题

**Comment by lxfu1** [comment]
升级 1.0， 参考： https://charts.ant.design/guide/faq
