### ISSUE TITLE
🧐[问题]柱图柱间距问题

### ISSUE THREAD

**Issue by wj86611199** [ant-design/ant-design-charts#1168]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://user-images.githubusercontent.com/17016971/154217885-204eb645-bba1-42ca-9afe-7d942ee0e284.png)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image](https://user-images.githubusercontent.com/17016971/154221726-703be45f-f2f3-4241-adb8-1406f1eae8b4.png)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
我这生成的条形图柱子间的间隔比较大，怎么才可以调成官方示例的间隔，不通过改    barWidthRatio，和minBarWidth 我看官方示例也没有设置这两个属性

**Comment by lxfu1** [comment]
调整容器高度
