### ISSUE TITLE
🧐Question

### ISSUE THREAD

**Issue by sabitalizade** [ant-design/ant-design-charts#1169]
I can`t find customize filter bar , can i do it as dropdown menu?

**Comment by lxfu1** [comment]
Could you describe it in more detail?

**Comment by sabitalizade** [comment]
![image](https://user-images.githubusercontent.com/54733296/154228568-b75404d0-879a-47f0-8be9-fbfb17bd85f1.png)

**Comment by sabitalizade** [comment]
i want to customze all filter option exp: initialValues, design ect. its posible?

**Comment by lxfu1** [comment]
```ts
const DemoColumn = () => {
  const data = [
    {
      name: 'London',
      月份: 'Jan.',
      月均降雨量: 18.9,
    },
    {
      name: 'London',
      月份: 'Feb.',
      月均降雨量: 28.8,
    },
    {
      name: 'Berlin',
      月份: 'Jan.',
      月均降雨量: 12.4,
    },
    {
      name: 'Berlin',
      月份: 'Feb.',
      月均降雨量: 23.2,
    },
    {
      name: 'Berlin',
      月份: 'Mar.',
      月均降雨量: 34.5,
    },
  ];
  const config = {
    data,
    isGroup: true,
    xField: '月份',
    yField: '月均降雨量',
    seriesField: 'name',
    legend: false,
    onReady: (plot)=> {
      plot.chart.filter('name', (_, item) => item.name ==='London');
      plot.chart.render(true)
    }
  };
  return <Column {...config} />;
};
```

**Comment by sabitalizade** [comment]
> ![image](https://user-images.githubusercontent.com/54733296/154228568-b75404d0-879a-47f0-8be9-fbfb17bd85f1.png)

your example don`t do same think as picture

**Comment by lxfu1** [comment]
You turn off the legend  and use custom components to simulate.

**Comment by sabitalizade** [comment]
if I can Change London to Berlin dinamic load all bar dont filter

**Comment by lxfu1** [comment]
https://codesandbox.io/s/funny-kowalevski-z2kymb?file=/index.js

**Comment by sabitalizade** [comment]
Thanks for 1 year after reply

**Comment by sabitalizade** [comment]
Thanks for 1 year after response
