### ISSUE TITLE
🧐[问题] 条形图滚动条示例中的功能与期望不一致

### ISSUE THREAD

**Issue by Guitenbay** [ant-design/ant-design-charts#117]
### 🧐 问题描述
滚动条应该是滚动后，图形内容能上下移动，但是 demo 里的图形内容是缩放

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![滚动前](https://user-images.githubusercontent.com/22017608/87843693-3926ca00-c8e9-11ea-8bf0-18b1b63f39be.PNG)
![滚动后](https://user-images.githubusercontent.com/22017608/87843699-3e841480-c8e9-11ea-8aab-fbcfbc5db2ac.PNG)

**Comment by lxfu1** [comment]
update
