### ISSUE TITLE
🐛[BUG] XSS in charts tooltips

### ISSUE THREAD

**Issue by semdejong** [ant-design/ant-design-charts#1170]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
XSS in charts tooltips 
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
Treemap:
![image](https://user-images.githubusercontent.com/46659151/154280006-04469b05-e007-4af3-bbe2-697e3a85c688.png)
![image](https://user-images.githubusercontent.com/46659151/154274548-4c9ae4e4-cdbe-49e3-bc97-0ca50781bff8.png)
the same issue occurs in other tooltips (like column chart as well).

### 🏞 期望结果 [描述你原本期望看到的结果]
It should be escaped. Like it should just show it as plain text.
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
`<style>@keyframes x{}</style><xss style="animation-name:x" onanimationstart="PERFORM ANY JS YOU WANT"></xss>`

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
LATEST
- 浏览器环境
 At least Firefox, Google Chrome, Opera, Edge, and Safari
- 开发环境 [e.g. mac OS]
All

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/pull/434
