### ISSUE TITLE
🧐[flowchart 阅读态 禁用键盘事件]

### ISSUE THREAD

**Issue by jx-zyf** [ant-design/ant-design-charts#1176]
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
通过监听document的keydown事件不能阻止，在onReady的 graph 实例上监听也一样不生效

```ts
document.on('keydown', e => {
  if (e.code === 'Delete') {
      e.preventDefault();
    }
})
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

有什么方法可以禁用键盘修改画布内容吗？

**Comment by lxfu1** [comment]
更新一下版本， keyBindingProps： false。

**Comment by jx-zyf** [comment]
keyBindingProps 的值如果通过 state 控制，state 变化后画布的键盘绑定事件没有变化
