### ISSUE TITLE
在多折线图的情况下，一条数据的一个点没有数据，这个数据的附近两个点可以不连接么，采用短点形式展示

### ISSUE THREAD

**Issue by is-cool** [ant-design/ant-design-charts#1178]
在多折线图的情况下，一条数据的一个点没有数据，这个数据的附近两个点可以不连接么，采用短点形式展示（register这条折线图，五号数据没有的情况下，4号和6号还是连接了，可以不连接不啦）

https://codesandbox.io/s/kind-ully-mk7b9h?file=/demo.tsx

<img width="320" alt="截屏2022-02-22 14 30 29" src="https://user-images.githubusercontent.com/78067806/155075826-f49196a7-e3dd-4af0-a403-6956998a58bd.png">

**Comment by lxfu1** [comment]
不支持这种，处理下数据为 0  ？

**Comment by is-cool** [comment]
好的吧，谢谢~
