### ISSUE TITLE
🐛[BUG] 使用antv-chart的时候，build出现Super expression must either...的问题

### ISSUE THREAD

**Issue by Houngtze** [ant-design/ant-design-charts#118]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.94]
- 浏览器环境
- 开发环境 [e.g. Windows10]

**Comment by lxfu1** [comment]
charts 对版本没有特殊要求，支持hooks的都可以，有可能是charts版本有问题，期待下次提供复现例子。
