### ISSUE TITLE
Question About Bar Charts and Dates

### ISSUE THREAD

**Issue by philcho1224** [ant-design/ant-design-charts#1180]
I am creating a Range Bar Chart using Ant Design. I'm displaying a range of dates as the x intervals. My data looks like this.
[{
   activity: 1, 
   dates: [
       Wed Feb 17 2021 17:03:32 GMT-0500 (Eastern Standard Time),
       Wed Mar 31 2021 00:00:00 GMT-0400 (Eastern Daylight Time)
    ]
} ].
The dates array is made up of Date objects. But the x-axis has these number values, it seems like its the Date number value when using Date.getTime() method. How should I fix it so that the bottom displays dates, where the tick interval is every month and can display "February 2020" or something like that?
<img width="1673" alt="Screen Shot 2022-02-22 at 11 49 26 AM" src="https://user-images.githubusercontent.com/58188470/155181202-4ead3ffb-6d33-43cb-aec2-dc445a4c1c49.png">

**Comment by lxfu1** [comment]
```ts
label: {
  formatter: () => xxx
}
```

**Comment by philcho1224** [comment]
@lxfu1 yeah that suggestion worked, thanks!
