### ISSUE TITLE
🧐[问题]Area 关于color的配置 回调函数只能获取seriesField 不能获取其他字段来配置 颜色？

### ISSUE THREAD

**Issue by OnePieceLiu** [ant-design/ant-design-charts#1184]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我想 0一下的跟0以上的两种颜色无法实现？

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

    { country: '北美', date: 2013, value: 2738.3 },
    { country: '北美', date: 2014, value: 2766.8 },
    { country: '北美', date: 2015, value: 2739.7 },
    { country: '北美', date: 2016, value: 2761.9 },
    { country: '北美', date: 2017, value: 2772.8 },
    { country: '中南美', date: 1965, value: -809.2 },
    { country: '中南美', date: 1966, value: -615.7 },
    { country: '中南美', date: 1967, value: -420.5 },
    { country: '中南美', date: 1968, value: -228 },
    { country: '中南美', date: 1969, value: -134.4 },
    { country: '中南美', date: 1970, value: -142.2 },

    colorField: 'key', // 部分图表使用 seriesField
    seriesField: 'country',
    line: {
      color: (v) => {
        // console.log(v, a);
        if (v.country === '北美') {
          return 'red';
        }
        return 'blue';
      },
    },
    color: (v: any) => {
      console.log(v);
      if (v.country === '北美') {
        return '#ffffff';
      }
      return 'blue';
    },

**Comment by OnePieceLiu** [comment]
我既想配置 不同国家的k线颜色，又想配置value 正负的颜色 无法做到？

**Comment by lxfu1** [comment]
rawFields: ['country', 'value'] 试试

**Comment by OnePieceLiu** [comment]
> rawFields: ['country', 'value'] 试试
<img width="301" alt="1645687422(1)" src="https://user-images.githubusercontent.com/26754729/155477754-44bcedd5-31b7-4270-b146-4237af3d9e1a.png">

**Comment by OnePieceLiu** [comment]
> rawFields: ['country', 'value'] 试试

好像是能拿到的，但是为啥是个数组，能帮我解惑一下吗兄弟

**Comment by OnePieceLiu** [comment]
> rawFields: ['country', 'value'] 试试

![image](https://user-images.githubusercontent.com/26754729/155478390-ead7b946-3848-477e-aee6-5197f033f142.png)
![image](https://user-images.githubusercontent.com/26754729/155478443-25427c59-7220-4e28-9841-98487c39d07f.png)
好像并不能实现我想要的效果

**Comment by OnePieceLiu** [comment]
![image](https://user-images.githubusercontent.com/26754729/155478539-0d8bcc1c-eb61-455b-84cc-032d2e448ef7.png)
这是想要的

**Comment by calimanco** [comment]
> rawFields: ['country', 'value'] 试试

麻烦补齐这个字段的 ts 描述和文档。
其实我觉得这个将数据过滤出特定字段的隐藏功能蛮鸡肋的，传入啥，输出啥就行了。

**Comment by StevenGardnerGMJ** [comment]
我来冒昧总结一下楼主的需求:
使用 基础面积图Area, 
想要实现位于某一特定Y值之下的面积部分呈现不同颜色, 
其他面积部分颜色仍然正常显示.

例如:公司的盈利趋势
某个时间段是负值(在0.0%以下)呈现红色
其他时间段是正值(在0.0%以上) 呈现绿色
[详细效果见:](https://github.com/ant-design/ant-design-charts/issues/1184#issuecomment-1049571543)
就上8楼面的图

**Comment by zyk2891** [comment]
同求 有时候需要按照数据来指定颜色 包括柱状图中 有一些数据为负的时候需要柱体指定为特殊颜色

**Comment by MaoMervyn** [comment]
> > rawFields: ['country', 'value'] 试试
> 
> 麻烦补齐这个字段的 ts 描述和文档。 其实我觉得这个将数据过滤出特定字段的隐藏功能蛮鸡肋的，传入啥，输出啥就行了。

同意，确实鸡肋。估计是为了避免用户给的数据出现嵌套引用一类的情况导致内部逻辑bug，其实可以做层数据过滤提醒就行。
数据作为参量就应该原样返回，处理事件时有很多数据需求。
像 https://charts.ant.design/zh/examples/component/legend/#legend-item-value这种，数据循环遍历找出特定数据项，本身就不合理。

**Comment by lxfu1** [comment]
[2.0 已经规避了这个问题](https://ant-design-charts-next.antgroup.com)

**Comment by MaoMervyn** [comment]
邮件已收到，谢谢。
