### ISSUE TITLE
🧐[问题] FlowAnalysisGraph的minimapCfg配置在mac谷歌上面拖拽时有 ’小地球‘ 是为什么

### ISSUE THREAD

**Issue by UserRunway** [ant-design/ant-design-charts#1185]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在mac电脑上面使用谷歌浏览器打开FlowAnalysisGraph组件展示的页面进行拖拽时，会出现小地球这样的展示，请问这里是为什么呢
![image](https://user-images.githubusercontent.com/96331325/155504988-62c53966-b96c-479f-8090-0641eaf2b84d.png)

**Comment by lxfu1** [comment]
没发现问题，覆盖 cursor 试一下

**Comment by UserRunway** [comment]
> 没发现问题，覆盖 cursor 试一下

试过了，用css解决不了，只能改原生的drap事件才可以
