### ISSUE TITLE
🧐[问题]堆叠柱状图Column，跟例子相同配置但是有很大的差别

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-charts#1188]
使用版本1.3.5
    "@ant-design/charts": "^1.3.5",
config代码完全使用例子中的，区别是例子使用javaScript，我是用ts
跟Demo相比，
1、第一个侧边便签的上部边缘被覆盖，该情况只有在中文的时候会发生，
2、Demo中便签在鼠标悬浮时右侧有个定位的图标，我这里没有，

![image](https://user-images.githubusercontent.com/12421552/155675123-e1018499-7ada-4c1e-a6ed-a084528ea2da.png)

![image](https://user-images.githubusercontent.com/12421552/155675409-0936203f-727e-4e7f-9610-1c89c7a9add1.png)

**Comment by lxfu1** [comment]
第二个可能是版本问题，对比一下安装的版本和示例版本
```ts
 legend: {
    itemHeight: 20
  },
```
