### ISSUE TITLE
🐛[BUG] colorFields的值不能为 'title'

### ISSUE THREAD

**Issue by sunny-daisy** [ant-design/ant-design-charts#119]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
colorField的值不能为title，会报错

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
将data里返回的数据type修改为title,colorField也修改为tittle，代码报错，修改为其他字段可以正常显示

### 🏞 期望结果 [描述你原本期望看到的结果]
值为title可以正常显示，如果说真的不能写title，文档里需要注明

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
代码为在官方基础代码上进行修改后，复制截图

import { Pie } from '@antv/g2plot';

const data = [
  {
    title: '分类一',
    value: 27,
  },
  {
    title: '分类二',
    value: 25,
  },
  {
    title: '分类三',
    value: 18,
  },
  {
    title: '分类四',
    value: 15,
  },
  {
    title: '分类五',
    value: 10,
  },
  {
    title: '其它',
    value: 5,
  },
];

const piePlot = new Pie(document.getElementById('container'), {
  forceFit: true,
  title: {
    visible: true,
    text: '多色饼图',
  },
  description: {
    visible: true,
    text:
      '指定颜色映射字段(colorField)，饼图切片将根据该字段数据显示为不同的颜色。指定颜色需要将color配置为一个数组。\n当把饼图label的类型设置为inner时，标签会显示在切片内部。设置offset控制标签的偏移值。',
  },
  radius: 0.8,
  data,
  angleField: 'value',
  colorField: 'title',
  label: {
    visible: true,
    type: 'inner',
  },
});

piePlot.render();

在上述代码情况下，提示代码错误；
若删除colorFields,饼图可以显示，但是颜色为蓝色，tootip也只显示value

### © 版本信息

- ant-design-charts 版本: 0.9.6
- 浏览器环境
- 开发环境 mac OS

**Comment by lxfu1** [comment]
title  换个字段表示， 例如 type。
