### ISSUE TITLE
🧐[问题]请问条形图，数据如何从上往下，而不是居中展示

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-charts#1190]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
查了一下文档，没找到相关位置设置。

当我设置好最大最小宽度，并且固定好表格高度后，
只有少数数据，不能够占满整个表格高度，从上往下排，而不是居中显示？？

![image](https://user-images.githubusercontent.com/12421552/155919734-8d7ce6a9-cbe6-4cd9-899b-3121e6fd64a2.png)

**Comment by lxfu1** [comment]
少量数据为什么下面需要留白这么多呢？ 补全一下空值数据吧 `[{type: 'xx', scales: 0}]`

**Comment by edifangyi** [comment]
就是，现在数据量还比较少，所以希望是从上往下排，做成固定宽高的排行榜样式

**Comment by visiky** [comment]
设置下 meta 中的 range
