### ISSUE TITLE
🧐[问题]legend如何自定义selected为false的itemName的样式

### ISSUE THREAD

**Issue by weiman-133** [ant-design/ant-design-charts#1191]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

例如：深色背景下，点击图例的某一项后变为不显示，但是color变为了白色，不知道怎么可以自定义这个颜色
![image](https://user-images.githubusercontent.com/86717611/155937173-9e72b8d9-d37a-460e-8a07-f60903ad44ed.png)

**Comment by lxfu1** [comment]
```ts
    legend: {
        unchecked: {
          markerStyle: {
            stroke: 'red'
          },
          nameStyle: {
            fill: 'red'
          },
        },
      }
    },
```

**Comment by weiman-133** [comment]
![image](https://user-images.githubusercontent.com/86717611/156095632-78923d9f-6fda-4449-a55a-1fa76486f753.png)
请问是哪个版本的，直接使用无效

**Comment by lxfu1** [comment]
写错了 
```ts
  legend: {
    itemStates: {
      unchecked: {
      markerStyle: {
        stroke: 'red',
        fill: 'red'
      },
      nameStyle: {
        fill: 'red'
      },
    },
    }
  }
```

**Comment by lxfu1** [comment]
有点小问题，先这样处理一下
![image](https://user-images.githubusercontent.com/31396322/156097886-e6fe0653-fe58-45d8-9c92-a3840863decf.png)

**Comment by weiman-133** [comment]
好的，谢谢，辛苦啦~

**Comment by iolh** [comment]
这个如果能在文档里说明下，就更好了
