### ISSUE TITLE
🐛[BUG] Custom items in legend don't use the same colour as the chart data

### ISSUE THREAD

**Issue by Alazoral** [ant-design/ant-design-charts#1192]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

Hi there! I'm trying to use a custom sort order for legends, but when I try and use legend items to define them, it just uses blue for them all, unrelated from the colours actually shown in the chart.

Thanks for your assistance on this, I really appreciate it. Sorry for the English!

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

Code sandbox reproduction is here: https://codesandbox.io/s/ant-design-charts-custom-legend-items-bug-reproduction-p6yohn?file=/src/App.js

**Comment by lxfu1** [comment]
Customization needs to specify the color.
```ts
  { 
    name: "first", 
    value: "first", 
    marker: {
      symbol: 'circle',
      style: {
        fill: 'red'
      }
    } 
  },
```
