### ISSUE TITLE
🧐[问题]请问antd charts中的地图可以自定义在线底图吗

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#1195]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
譬如想使用高德地图自定义的其他样式的底图

**Comment by lvisei** [comment]
@CNFeffery 
https://l7plot.antv.vision/zh/docs/api/plot-api#code-classlanguage-textmapcodestyle

**Comment by CNFeffery** [comment]
@lvisei 感谢回复❤️，请问可以自定义其他底图服务吗，比如mapbox、osm、天地图或者自己发布的瓦片、矢量切片地图服务

**Comment by lvisei** [comment]
> @lvisei 感谢回复❤️，请问可以自定义其他底图服务吗，比如 mapbox、osm、天地图或者自己发布的瓦片、矢量切片地图服务


地图底图类型，支持以下两种类型：

amap: 高德地图
mapbox: Mapbox 地图

对于自己发的服务与其它服务，可借助 mapbox 底图容器能力，加载它支持的服务。

https://l7plot.antv.vision/zh/docs/api/plot-api#code-classlanguage-textmapcodetype
