### ISSUE TITLE
🐛[BUG]下载图片水印消失

### ISSUE THREAD

**Issue by 0408jiahuicao** [ant-design/ant-design-charts#1197]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
水印是自己加的吧？ 试试 html2canvas 插件

**Comment by 0408jiahuicao** [comment]
> 

水印是在图表的onReady回调里面 graph实例调用setTextWaterMarker 加上的  导出图片用的downloadFullImage，水印没有了
