### ISSUE TITLE
👑 [需求]流程图： nodeCfg  type=image提供自定义图片配置

### ISSUE THREAD

**Issue by 0408jiahuicao** [ant-design/ant-design-charts#1198]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
nodeCfg: {
type: 'image'
}

目前图片的默认的图片https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*eD7nT6tmYgAAAAAAAAAAAABkARQnAQ

希望能自定的图片

**Comment by lxfu1** [comment]
![image](https://user-images.githubusercontent.com/31396322/156482355-09585108-577c-48e6-aa39-84208edab369.png)
