### ISSUE TITLE
🐛[BUG]Column show abnormal

### ISSUE THREAD

**Issue by sunny-daisy** [ant-design/ant-design-charts#120]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
柱状图显示不正常

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
将data返回的第一个对象的值修改为字符串，页面显示异常

### 🏞 期望结果 [描述你原本期望看到的结果]
柱状图正常显示

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
代码为官方示例修改
import { Column } from '@antv/g2plot';

const data = [
  {
    type: '家具家电',
    sales: '38',
  },
  {
    type: '粮油副食',
    sales: 52,
  },
  {
    type: '生鲜水果',
    sales: 61,
  },
  {
    type: '美容洗护',
    sales: 145,
  },
  {
    type: '母婴用品',
    sales: 48,
  },
  {
    type: '进口食品',
    sales: 38,
  },
  {
    type: '食品饮料',
    sales: 38,
  },
  {
    type: '家庭清洁',
    sales: 38,
  },
];

const columnPlot = new Column(document.getElementById('container'), {
  title: {
    visible: true,
    text: '基础柱状图',
  },
  forceFit: true,
  data,
  padding: 'auto',
  data,
  xField: 'type',
  yField: 'sales',
  meta: {
    type: {
      alias: '类别',
    },
    sales: {
      alias: '销售额(万)',
    },
  },
});

columnPlot.render();

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0] 0.9.6
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
V 1.0
