### ISSUE TITLE
图表数据增量更新不整体重绘的例子🧐[问题]

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#1200]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

在官网没有看到相关的例子，可以提供基于`antd charts`的实现例子吗

**Comment by lxfu1** [comment]
setState(newData)

**Comment by CNFeffery** [comment]
@lxfu1 想实现类似echarts中的这种不整体刷新的效果：
![demo](https://user-images.githubusercontent.com/49147660/157682809-b5e235dc-9dc3-48c8-b255-8cbc8ab4676b.gif)

**Comment by visiky** [comment]
拿到 plot 实例，调用 changeData

**Comment by CNFeffery** [comment]
可以了，感谢🌹

**Comment by Icyrockton** [comment]
> 可以了，感谢rose

老哥请教下,这个plot示例是什么? 有react的例子吗

**Comment by lvanwenhai** [comment]
> > 可以了，感谢rose
> 
> 老哥请教下,这个plot示例是什么? 有react的例子吗

https://g2plot.antv.vision/zh/docs/api/plot-api

**Comment by lxfu1** [comment]
https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx

**Comment by lxfu1** [comment]
https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx

**Comment by Harry-Wei** [comment]
> 拿到 plot 实例，调用 changeData

Hi Visiky, 我该如何在一个react 函数组件里拿到plot？我的多折线图，点数在不断增加，现在用 <Line>data={myData}...</Line>每次增加一个点每条线都全部重新render，效率很低。谢谢！

**Comment by Harry-Wei** [comment]
> 

谢谢，我已经能用chartRef了，之前是因为Chart里的Line和g2plot里的Line重名导致无法useRef

**Comment by wozien** [comment]
> 拿到 plot 实例，调用 changeData

看了下源码， 如果config针对一些JSX配置化，列入tootip的customContent， 每次更新手动changeData也还是会重新渲染
