### ISSUE TITLE
🐛[BUG]堆叠分组柱状图-折线图横坐标错位

### ISSUE THREAD

**Issue by YiYChao** [ant-design/ant-design-charts#1202]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/48342992/156957923-e382ad3b-ae40-402e-9d9f-852b3eb9ae82.png)
折线图去除Jan的数据后，折线图统一往左便宜了一个单位
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by yangda666** [comment]
我也遇到了，当双轴数据时，第二个数据集对象少一组就会发生偏移

**Comment by lxfu1** [comment]
V1只能补空数据来实现，V2默认支持
