### ISSUE TITLE
🧐[问题]在官方示例中import路径问题

### ISSUE THREAD

**Issue by 904192063** [ant-design/ant-design-charts#1203]
### 🧐 问题描述 [事情是这样的，我在多折线图中，跟着示例引入了
[https://charts.ant.design/zh/examples/line/multiple#line-large-data](url)
`import { Line } from '@ant-design/plots';`
但是后面发现一直报错，找不到路径，重新安装库后仍然解决不了。]

### 🚑 其他信息 [后面我想起我之前也有项目调用了这个库，回去找才发现，正确的路径应该像快速上手页面的示例一样
[https://charts.ant.design/zh/docs/manual/getting-started](url)
`import { Line } from '@ant-design/charts';`
可能是示例的代码更新比较滞后，也可能是有其他的导入方法但是我没有掌握，给我带来了一些困扰，希望后面可以跟进更新，十分感谢]

**Comment by lxfu1** [comment]
`@ant-design/plots` 需要单独安装，是 `@ant-design/charts` 的一个子包。
