### ISSUE TITLE
👑 [需求]甘特图

### ISSUE THREAD

**Issue by lin-mt** [ant-design/ant-design-charts#1206]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

提供甘特图的功能

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
https://github.com/neuronetio/gantt-schedule-timeline-calendar

**Comment by bsgarage45** [comment]
> ### 需求描述 [详细地描述需求，让大家都能理解]
> 提供甘特图的功能
> 
> ### 解决方案 [如果你有解决方案，在这里清晰地阐述]
> ### 其他信息 [如截图等其他信息可以贴在这里]
> https://github.com/neuronetio/gantt-schedule-timeline-calendar

https://github.com/alibaba/nacos/projects/3#card-38704445

**Comment by ai-qing-hai** [comment]
@lin-mt  https://github.com/ant-design/ant-design-charts/issues/1912 可以看这个
