### ISSUE TITLE
🐛[BUG]依赖组件库immer@8.0.4包含漏洞，希望可以修复

### ISSUE THREAD

**Issue by ifunplus** [ant-design/ant-design-charts#1207]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
依赖组件库immer@8.0.4包含漏洞

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
npm ls immer
--@ant-design/charts@1.3.5
【】【】  |--@ant-design/flowchart@1.0.4
      【】【】 【】【】  |--@antv/xflow@1.0.7
            【】【】【】【】【】【】  |--immer@8.0.4

### 🏞 期望结果 [描述你原本期望看到的结果]
期望升级到无漏洞版本

### © 版本信息

- ant-design-charts 版本: [e.g. 1.3.5]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
最新版本已经修复
