### ISSUE TITLE
🧐[问题]  桑基图有没有办法设置每层都一一对齐

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [ant-design/ant-design-charts#1210]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
就是每层之间都一一对齐顶部， 如下图所示
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://codesandbox.io/s/heuristic-keller-zv52th?file=/src/App.tsx

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/24669431/157634820-8fd02311-29d0-4715-8ad2-35bdb6f90a20.png)

**Comment by lxfu1** [comment]
不支持，这块布局算法和 D3 Sankey 类似
