### ISSUE TITLE
🧐使用DualAxes,第一次渲染时，底部slide的宽度和图表的宽度不一致

### ISSUE THREAD

**Issue by zhi114** [ant-design/ant-design-charts#1214]
### 💻 
 const config = {
        data: [coinsPercent, coinsPercent],
        xField: 'date',
        yField: ['stableRate', 'ethRate'],
        theme: pageMode === 'dark' ? ANT_CHARTS_DARK : undefined,
        geometryOptions: [
            {
                lineStyle: LINESTYLE_WIDTH
            },
            {
                lineStyle: LINESTYLE_WIDTH
            }
        ],
        yAxis: {
            stableRate: {
                label: {
                    formatter: (text: string) => {
                        return Global.formatYAxis(text, f);
                    },
                },
                ...Global.findMinAndMax(coinsPercent.map((item: CoinsPercentItem) => {
                    return item.stableRate;
                })),
                grid: null,
                line: {
                    style: {
                        stroke: CHART_AXIS_COLOR,
                        ...LINESTYLE_WIDTH
                    },
                },
            },
            ethRate: {
                label: {
                    formatter: (text: string) => {
                        return Global.formatYAxis(text, f);
                    },
                },
                ...Global.findMinAndMax(coinsPercent.map((item: CoinsPercentItem) => {
                    return item.ethRate;
                })),
                grid: null,
                line: {
                    style: {
                        stroke: CHART_AXIS_COLOR,
                        ...LINESTYLE_WIDTH
                    },
                },
            }
        },
        slider: {
            ...ANT_CHARTS_DARK.components.slider.common,
            start: 0,
            end: 1,
            formatter(time: number) {
                return moment(Number(time)).format('YYYY/MM/DD')
            },
            padding: [0,0,-22,0]
        },
        padding: [20, 20, 30, 20],
        tooltip: {
            title: 'time'
        },
        meta: {
            //稳定币占比
            stableRate: {
                alias: f('stableRate'),
                formatter: (stableRate: number) => {
                    return `${stableRate}%`
                },
            },
            //eth占比
            ethRate: {
                alias: f('ethRate'),
                formatter: (ethRate: number) => {
                    return `${ethRate}%`
                },
            },
            date: {
                sync: false,
            },
        },
        xAxis: {
            tickCount: 10,
            label: {
                formatter: (time: string) => {
                    return moment(Number(time)).format('yyyy/MM/DD')
                },
            },
            line: {
                style: {
                    stroke: CHART_AXIS_COLOR,
                    ...LINESTYLE_WIDTH
                },
            },
        },
    }
<div style={{height: '312px',position: 'relative',marginTop: 20}}>
        <DualAxes
            {...config}
            fallback={
                <div
                    style={{
                        width: '100%',
                        height: '200px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                    }}
                >
                    <Spin></Spin>
                </div>
            }
        />
        <img style={{
            position: 'absolute',
            right: '100px',
            top: '194px',
            width: '123px',
            opacity: 0.5
        }} src="/images/line-watermark.svg" />
    </div>
### 🚑 
<img width="888" alt="image" src="https://user-images.githubusercontent.com/4452972/158550928-5697d4b3-9875-437b-bf4c-9c120ad6efb0.png">

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/489
