### ISSUE TITLE
图例旁边的指示器可以通过参数关闭吗🧐[问题]

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#1216]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

 鼠标悬浮于图例之上时，这个“瞄准器”似的指示器可以通过参数关闭吗

![image](https://user-images.githubusercontent.com/49147660/159112324-5b7ec69b-32b7-4265-89c4-cf16083466b2.png)

**Comment by CNFeffery** [comment]
@lxfu1 有时间的话麻烦帮忙看看，谢谢啦

**Comment by visiky** [comment]
`radio` 设置为 false

**Comment by CNFeffery** [comment]
@visiky 我在`antd charts`和`g2plot`都试了没有效果：
![image](https://user-images.githubusercontent.com/49147660/161095916-37ce4a8a-58a7-4e22-b296-a6835ad1bb49.png)

**Comment by CNFeffery** [comment]
@visiky 原来是`legend`参数下面设置！有效果了，感谢😀！
![image](https://user-images.githubusercontent.com/49147660/161096510-e34f0c52-41a0-40f8-8c5a-f08363fd6b18.png)
