### ISSUE TITLE
🐛[BUG] 折线图 Line 更换主题颜色错误

### ISSUE THREAD

**Issue by LinruoT** [ant-design/ant-design-charts#1217]
### 🐛 bug 描述
使用主题，折线图的颜色错误：分类1的颜色始终为默认颜色。

### © 版本信息

- ant-design-charts 版本: 1.3.5
- 浏览器环境 Chrome
- 开发环境 Windows

**Comment by lxfu1** [comment]
无效issue，提供复现demo后重新打开。
