### ISSUE TITLE
🧐【关系图】下的 data 对象中的字段都只能 string 类型，**直接写 JSX 会报错，怎么写才能支持 React.ReactElement 或 JSX 呢？**

### ISSUE THREAD

**Issue by hnldlsjzt** [ant-design/ant-design-charts#1218]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
1、【关系图】下的 data 对象中的字段都只能 string 类型，**直接写 JSX 会报错，怎么写才能支持 React.ReactElement 或 JSX 呢？**这样做可以更灵活的实现布局与样式。
现在只能 string，不知道如何实现自定义布局。

2、自定义【tooltip】内容，鼠标一离开节点就会马上消失。我想把鼠标放上自定义【tooltip】元素上执行自定义事件，有什么思路可以实现吗？
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```
// 具体参考示例代码
interface Data {
  id: string;
  value: {
    title: string;
    items: Array<{
      text: string;
      value: string;
      icon: string;
    }>;
  };
}


```
官方 [demo](https://charts.ant.design/zh/examples/relation-graph/decomposition-tree-graph#basic)

**Comment by lxfu1** [comment]
目前不支持，暂无支持计划。
