### ISSUE TITLE
## Flowchart这个组件怎么禁用画布的某些事件啊。

### ISSUE THREAD

**Issue by yangxin18728391039** [ant-design/ant-design-charts#1219]
###就是在预览的时候，只展示流程图的数据，只能拖动画布，节点禁止选中和移动，怎么实现这种效果

**Comment by promise6512** [comment]
- 可以禁用新增边，但是选中和移动节点目前考虑不禁用，可以再帮忙想想还有哪些需要禁用吗？

**Comment by yangxin18728391039** [comment]
> * 可以禁用新增边，但是选中和移动节点目前考虑不禁用，可以再帮忙想想还有哪些需要禁用吗？

我目前就是主要想禁用掉node节点的拖动和鼠标移入高亮这些事件。我们业务场景需要。请问怎么处理呢

**Comment by yangxin18728391039** [comment]
onReady: graph=>{
    graph.on('node.moving', e => {
           console.log(e)
    })
} 在onReady里面能监听到拖动的事件，怎么禁用掉呢。。   


事件通过 on 统一绑定到 graph 上，通过 off 移除，onReady 会返回 graph 实例。
graph.on(eventName, (evt) => {});
graph.off(eventName, (evt) => {});
这个是api的方法，但是我用off方法移除不了方法。。

**Comment by promise6512** [comment]
应该是 node: moved 吧

**Comment by yangxin18728391039** [comment]
> 应该是 node: moved 吧

这两个我都试了，都能监听到，但是都移除不了

**Comment by yangxin18728391039** [comment]
你们文档太简陋，找了一天原来是写可以直接配置。
canvasProps={{
                          position: {
                                        top: 0,
                                        left: 0,
                                        right: 0,
                                        bottom: 0,
                                    },
                                    config: {
                                         interacting: {
                                             nodeMovable: false,
                                         }
                                    }
                                }}
FlowChart官方给的文档说明太少了。我都是试出来的。
