### ISSUE TITLE
🐛[BUG]饼图在异步获取数据时数据显示不正确

### ISSUE THREAD

**Issue by xiejun** [ant-design/ant-design-charts#122]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
饼图显示数据为null
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
在useEffect里给饼图set数据
饼图的config里label type设置为"spider",则饼图周围有数据，鼠标移上去显示null
type设为”inner“的话，则直接显示null
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/boring-tereshkova-x9bxg?fontsize=14&hidenavigation=1&theme=dark
### © 版本信息

- ant-design-charts 版本: "@ant-design/charts": "^0.9.8",
- 浏览器环境 chrome
- 开发环境 Mac OS

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/1418991/88161342-74efc580-cc42-11ea-9a77-e9c3a9606747.png)
![image](https://user-images.githubusercontent.com/1418991/88161394-8507a500-cc42-11ea-9fbc-364a1b3403b9.png)

**Comment by Nathanielna** [comment]
通用的问题 求官方解决谢谢

**Comment by lxfu1** [comment]
V 1.0
