### ISSUE TITLE
两个柱形图放在一行,对其中一个进行排序更新操作时,另一个柱形图也发生了重绘🐛[BUG]

### ISSUE THREAD

**Issue by HOLLY-ZYP** [ant-design/ant-design-charts#1220]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![12](https://user-images.githubusercontent.com/57129767/159223239-be143657-5029-4735-a29b-9e1f1616fcf0.gif)
点击左侧柱形图进行排序时,右侧柱形图也会进行刷新

![32](https://user-images.githubusercontent.com/57129767/159223323-594acd08-4241-4fec-80a6-4fbded39ba6c.gif)

两个组件数据状态等都分别独立
下面附上代码结构截图
![1](https://user-images.githubusercontent.com/57129767/159223728-d20f2946-b214-4e81-b10e-f5018f45f6d0.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
进行任一柱形图排序按钮后,只对当前柱形图进行重绘.另一柱形图保持不变.

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
参考下这个， https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx

**Comment by HOLLY-ZYP** [comment]
您好，邮件已收到，我会尽快给您回复。

**Comment by HOLLY-ZYP** [comment]
感谢您的帮助,但是我好像没看懂连接上demo展示的效果.我把项目在本地运行,然后调出控制台,点击demo上的功能,每次都引发了重绘.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-charts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-charts] 两个柱形图放在一行,对其中一个进行排序更新操作时,另一个柱形图也发生了重绘🐛[BUG] (Issue #1220)





 
参考下这个， https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HOLLY-ZYP** [comment]
> 参考下这个， https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx

我把demo做了两个,依然会重绘  他们的数据等全部独立
![34](https://user-images.githubusercontent.com/57129767/159231154-32b52dd5-a242-4f3a-ae1f-e9a1d4229a72.gif)
