### ISSUE TITLE
运行官方示例报错 Uncaught TypeError: extensionRegistry.addExtension is not a function

### ISSUE THREAD

**Issue by an9el** [ant-design/ant-design-charts#1221]
![image](https://user-images.githubusercontent.com/10058691/159261939-736757ad-9bc8-4d98-ab25-32391fa3e6db.png)

示例地址：https://charts.ant.design/zh/examples/flowchart/basic#complex-form

**Comment by lxfu1** [comment]
重新安装试试

**Comment by an9el** [comment]
> 
试过了，还是这样
"@ant-design/flowchart": "^1.0.9",
"react": "^17.0.2",
