### ISSUE TITLE
多余的重绘🐛[BUG]

### ISSUE THREAD

**Issue by HOLLY-ZYP** [ant-design/ant-design-charts#1223]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
同一页面上,存在两个相同的图表,对其中任一变更数据后,两个图表均发生重绘

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
两个柱形图,改变其中之一排序,两个一起重绘.
![12](https://user-images.githubusercontent.com/57129767/159416456-a4baf8a4-f882-4341-9609-4d0ac9d968d8.gif)
![32](https://user-images.githubusercontent.com/57129767/159416484-6966c42e-9134-483b-9d4a-a1f1fc7d5642.gif)
昨天提问后,官方给出了链接   https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx
将链接demo做两份放在同一页面,两个饼状图中任一数据变化时,两个图发生重绘
![34](https://user-images.githubusercontent.com/57129767/159416740-f418b114-e862-451a-93a2-ecf6e30bbf0a.gif)
以上所有图表,数据 状态等全都分别独立
猜想过重绘由react diff引发,判定相同图表之间为兄弟组件从而引发重绘,但是在对图表进行再封装之后,重回现象依然存在

### 🏞 期望结果 [描述你原本期望看到的结果]
重绘只发生在当前图表,其余同类型图表不发生重绘

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zhangqiqi-engineer** [comment]
我也遇到了，请问该如何解决？？？

**Comment by HOLLY-ZYP** [comment]
您好，邮件已收到，我会尽快给您回复。

**Comment by HOLLY-ZYP** [comment]
> 
没有得到解决...

**Comment by zhangqiqi-engineer** [comment]
我解决了，用useMemo(()=>{
return <RadialBar {...config}/>
}，[config])

**Comment by HOLLY-ZYP** [comment]
我有试过用这个诶,没解决...你方不方便多贴一点代码出来,我再试下~谢谢你呀~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 下午5:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-charts] 多余的重绘🐛[BUG] (Issue #1223)





 
我解决了，用useMemo(()=&gt;{
 return <RadialBar {...config}/&gt;
 }，[config])

**Comment by lxfu1** [comment]
参考这个 https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx
