### ISSUE TITLE
🧐[问题]图表功能实现问题请教

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design-charts#123]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://user-images.githubusercontent.com/20501316/88498211-1d13de80-cff5-11ea-8c75-a1914e572d77.png)
**图1**

![image](https://user-images.githubusercontent.com/20501316/88498269-42a0e800-cff5-11ea-8fa5-2f5c72102805.png)
**图2**

如上图，
图1中月份中插入年份显示如何实现？
图2中图例中的数据显示如何实现？

**Comment by lxfu1** [comment]
1、  xAxis: {
        title: {
    			visible: true,
          text: '123'
				},
      },

2、暂不支持，隐藏图表legend，上层实现。

**Comment by WangJM001** [comment]
图一不是显示x轴title，是在跨年的位置显示后面日期的年，所以它的位置不是固定的
