### ISSUE TITLE
🧐[问题] - I need to rotate y axis title in a bar charts. 

### ISSUE THREAD

**Issue by Anjula1996** [ant-design/ant-design-charts#1236]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
How do I rotate the y-axis title on a bar graph? I have used the stacked column chart and the basic column chart. Are there props? I could not find it in the document.

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/69517709/160332627-20b3d093-1321-4939-9c54-b78123164c46.png)

**Comment by lxfu1** [comment]
```ts
yAxis: {
  title: {
    content: '123',
    rotate: 0
  }
},
```

**Comment by Anjula1996** [comment]
> ```ts
> yAxis: {
>   title: {
>     content: '123',
>     rotate: 0
>   }
> },
> ```

thank you it works for me
