### ISSUE TITLE
🐛[BUG] xAxis. type 设置为 timeCat 时 绘制的线多了

### ISSUE THREAD

**Issue by Dawnwangzi** [ant-design/ant-design-charts#1237]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
折线图中 设置
xAxis: {
      type: 'timeCat',
    },

画出来的线多了

设置为
xAxis: {
      type: 'time',
    },
就是正常的

![image](https://user-images.githubusercontent.com/20938424/160361988-ff1ef897-fc54-473d-8b03-abbb26550e16.png)

timeCat

### 🏞 期望结果 [描述你原本期望看到的结果]

期望 timeCat 时没有多余的线条

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
在这个例子上就可以试出来
https://charts.ant.design/zh/examples/line/multiple#line-large-data

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
数据问题
