### ISSUE TITLE
🐛[BUG]区间条形图，当区间为时间时，Bar无法展示蓝色条形

### ISSUE THREAD

**Issue by lixin0812** [ant-design/ant-design-charts#1238]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
区间条形图，当区间为时间时，Bar无法展示蓝色条形
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/35521819/160430570-e051678c-8409-4e2c-a0d2-ce99114aea8e.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
正确展示蓝色条形图
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
`import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Bar } from '@ant-design/plots';

const DemoBar = () => {
  const data = [
        {
          ClusterId: '分类一',
          部署时间: ['2022-03-26 18:34:15', '2022-03-27 18:34:15'],
        },
        {
          ClusterId: '分类二',
          部署时间: ['2022-03-26 18:34:15', '2022-03-27 18:34:15'],
        },
        {
          ClusterId: '分类三',
          部署时间: ['2022-03-26 18:34:15', '2022-03-27 18:34:15'],
        },
        {
          ClusterId: '分类四',
          部署时间: ['2022-03-26 18:34:15', '2022-03-27 18:34:15'],
        },
        {
          ClusterId: '分类五',
          部署时间: ['2022-03-26 18:34:15', '2022-03-27 18:34:15'],
        },
        {
          ClusterId: '分类六',
          部署时间: ['2022-03-26 12:34:15', '2022-03-27 18:34:15'],
        },
        {
          ClusterId: '分类七',
          部署时间: ['2022-03-26 17:34:15', '2022-03-27 18:34:15'],
        },
        {
          ClusterId: '分类八',
          部署时间: ['2022-03-26 18:34:15', '2022-03-28 18:34:15'],
        },
      ];
  const config = {
    data: data.reverse(),
    xField: '部署时间',
    yField: 'ClusterId',
    xAxis: {
          type : 'timeCat',
          mask: 'YYYY-MM-DD HH:mm:ss',
          // mask: 'MM/DD HH:mm:ss',
          tickCount: 8,
        },
    isRange: true,
    label: {
      position: 'middle',
      layout: [
        {
          type: 'adjust-color',
        },
      ],
    },
  };
  return <Bar {...config} />;
};

ReactDOM.render(<DemoBar />, document.getElementById('container'));`

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
用法不对，是数值映射，不能通过字符串映射

**Comment by lixin0812** [comment]
请问一下要怎么数值映射呢？用时间戳吗？

**Comment by lixin0812** [comment]
@lxfu1
