### ISSUE TITLE
🧐[问题] 漏斗图 - conversionTag 渲染文本过长时显示不完整

### ISSUE THREAD

**Issue by LazyJoke** [ant-design/ant-design-charts#1240]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://user-images.githubusercontent.com/23025622/160528632-303b808e-f4d1-4e30-9b9f-0a463b8aff51.png)

**Comment by lxfu1** [comment]
设置一下 padding: [20, 200]
