### ISSUE TITLE
🧐[问题] 截取数据中的一部分数据，坐标轴不能适配

### ISSUE THREAD

**Issue by Dawnwangzi** [ant-design/ant-design-charts#1241]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

这个例子中 https://charts.ant.design/zh/examples/line/multiple#line-large-data
1.  将数据存下来，放到折线图中。
2. 截取数据中的一部分，比如1893-1931年的数据，传给Line组件
3.  如图，只显示半个图，x坐标轴没有适配使图填满整个图表。期望是能data变化，能按新的data 重新渲染整个图表
![image](https://user-images.githubusercontent.com/20938424/160529198-353a48ef-7840-4a00-ab5a-51c471ce3e88.png)
4. 但是换一组完全不相关的数据进去 x坐标轴可以适配使图填满整个图表
5. config   
    xAxis: {
      type: 'time',
    },
   timeCat的时候是可以做到按新数据填充整个图表的，但是这时候会多绘制线条
![image](https://user-images.githubusercontent.com/20938424/160530314-e67f2faf-8047-459b-943c-b5323862932d.png)

timeCat 多绘制线条：
![image](https://user-images.githubusercontent.com/20938424/160530545-a86d57b1-6465-427c-9691-a6cafbf657f5.png)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
父组件中
![image](https://user-images.githubusercontent.com/20938424/160529802-dfff5cdb-0883-4b2c-8446-962b816bf559.png)

![image](https://user-images.githubusercontent.com/20938424/160529756-d8bd95b6-2567-46df-be97-dd81cc70d398.png)

![image](https://user-images.githubusercontent.com/20938424/160529661-01f89917-2688-4454-a5d6-b79acadee21f.png)

子组件中 （子组件里封了下Line）
![image](https://user-images.githubusercontent.com/20938424/160529597-6830a824-bc4c-4868-b2a3-7632181ad21a.png)

![image](https://user-images.githubusercontent.com/20938424/160530010-baccb206-747f-4625-978b-3175a03db769.png)

![image](https://user-images.githubusercontent.com/20938424/160529965-3b854c5a-e2da-49b8-810f-ca3ba26ee7c1.png)

**Comment by deviluncle** [comment]
相同问题

**Comment by lxfu1** [comment]
在codesandbox 上提供一下复现，建议检查下数据。
