### ISSUE TITLE
🧐[问题] Adjust spacing between Column along with Column width

### ISSUE THREAD

**Issue by xeusteerapat** [ant-design/ant-design-charts#1244]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Is it possible to adjust the spacing between column and column width together?

I know that it needs to configure `marginRatio` but it seems doesn't work if we also adjust `columnWidth`

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
I've tried config as below but still too wide

```javascript
const consfig = {
   maxColumnWidth: 40,
   marginRatio: 0,
}
```
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1169" alt="Screen Shot 2565-03-29 at 19 32 27" src="https://user-images.githubusercontent.com/37167919/160612367-189ceca6-133c-4a1a-845a-1610c20703f9.png">

**Comment by lxfu1** [comment]
```ts
dodgePadding: 40,
```
