### ISSUE TITLE
🧐[问题]如何在HeatMap上给国内行政区自定义底色呢？以及如何在ChoroplethMap添加特殊的点？

### ISSUE THREAD

**Issue by yctjb1** [ant-design/ant-design-charts#1248]
### 🧐 问题描述
    "@ant-design/charts": "^1.3.6",

map.type: "amap",均是高德
问题1：
我想在热力图HeatMap的style: "blank"皮肤下，给行政区域着色，请问有法子吗？

问题2：
我想在ChoroplethMap上添加一些“点”，这些点能显示在地图上，请问如何实现呢？

问题3：
【如果】上述要求是通过“高级图表”实现的，比如“问题2”，我的理解是ChoroplethMap和DotMap进行……图层组合？
请问可以提供一下简单示例吗，我甚至不知道该从哪个包去引哪个组件去实现

。。。如果不能实现，也劳烦告知一下orz

**Comment by lvisei** [comment]
问题1，热力图，底图设置为 "blank" 没有行政区域

问题2、3，高级图表实现，多图表或多图层去做，用 L7Plot，看官网demo  ，chart 没有封装 L7Plot 多图层的实现
