### ISSUE TITLE
🐛[BUG] 条状图 `Bar` color 和 meta 字段冲突，同时设置时 meta字段未生效

### ISSUE THREAD

**Issue by JaylanChen** [ant-design/ant-design-charts#1249]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
条状图 `Bar` color 和 meta 字段冲突，同时设置时 meta字段未生效；

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

使用条状图 Bar ，同时设置color 和 meta 字段，字段别名则不生效；
![image](https://user-images.githubusercontent.com/7055008/160969504-0d83b0ee-488f-41a1-a6a0-00bbc738f060.png)

### 🏞 期望结果 [描述你原本期望看到的结果]

color 和 meta 字段 不冲突
![image](https://user-images.githubusercontent.com/7055008/160969573-312a0b4c-a2ee-48b0-8205-95a3cdf89454.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
[https://charts.ant.design/zh/examples/bar/basic#color](https://charts.ant.design/zh/examples/bar/basic#color)

### © 版本信息

- ant-design-charts 版本: 1.3.6 （@ant-design/plots@1.0.9）
- 浏览器环境 Chrome 、 Edge 最新稳定版
- 开发环境 Win10

**Comment by liixing** [comment]
柱状图也有这个问题

**Comment by zhouzhiyang-git** [comment]
现在color 和 meta 字段冲突的这个问题解决了么？

**Comment by JaylanChen** [comment]
> 目前还没修复，可以看下上方官方demo的示例；

**Comment by lxfu1** [comment]
升级到V2吧，https://ant-design-charts-next.antgroup.com/options/plots/component/tooltip
