### ISSUE TITLE
为啥折线图的x轴时间不对🧐[问题]

### ISSUE THREAD

**Issue by malusama** [ant-design/ant-design-charts#125]
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://codesandbox.io/s/frosty-firefly-z4sri?file=/demo.tsx:236-260

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

时间是
2020-07-24T12:24:00.000Z
但是x轴显示的却是08:24 为啥查了4个小时

**Comment by lxfu1** [comment]
注意下 T ， 时区问题。
