### ISSUE TITLE
🐛[BUG]环图图例的标题设置不生效

### ISSUE THREAD

**Issue by CHENJing11111** [ant-design/ant-design-charts#1251]
### 🐛 bug 描述 [
图例legend属性，title的值设置不生效，展示的title内容是data数据type的key值
]

### 📷 复现步骤 [
legend: {
      title: {
        title: '中心问题',
        spacing: 20,
        style: {
          cursor: 'point',
          fontSize: 20,
        },
      },
    },]

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [

![image](https://user-images.githubusercontent.com/52558013/161226437-4ade046c-18e5-4f11-821a-1002d55b80bc.png)
]

**Comment by lxfu1** [comment]
```ts
  legend: {
    title: {
      text: '123'
    }
  },
```
