### ISSUE TITLE
🐛[BUG] 右击动态增加dom，图autoFit失效

### ISSUE THREAD

**Issue by Jarryxin** [ant-design/ant-design-charts#1252]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
右击图节点，在对应位置展示一个Menu组件，原本自适应绘制的图缩小

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
打开复现代码，右击节点

### 🏞 期望结果 [描述你原本期望看到的结果]
期望不缩小

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/laughing-sound-njj4je?file=/index.js

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
试了一下没有复现，最新版本应该已经修复。
