### ISSUE TITLE
🐛[BUG] 折线图启用数据点后崩溃

### ISSUE THREAD

**Issue by yinyanfr** [ant-design/ant-design-charts#1253]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

按照示例 [配置折线数据点样式](https://charts.ant.design/zh/examples/line/basic#line-point-style) 编写代码后无法渲染，

报错 element.getTotalLength is not a function （见图）

去掉数据点(point) 属性之后才能渲染。

![报错](https://s1.ax1x.com/2022/04/05/qLKj6s.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

参见复现代码。

### 🏞 期望结果 [描述你原本期望看到的结果]

期望能如同示例，正确渲染数据点。

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/antd-chart-issue-reproduction-ll5pld?file=/index.js

默认是可以正常渲染的状态，将Line组件的point属性的注释去掉后将崩溃 （代码第33行起）。

### © 版本信息

- ant-design-charts 版本: 1.3.6
- 浏览器环境 Chrome 99
- 开发环境 Ubuntu

**Comment by ai-qing-hai** [comment]
@yinyanfr  
point 不适用 path-in 的动画， https://github.com/antvis/G2/pull/4035 在 g2 中加了回调,但还没发布

**Comment by ai-qing-hai** [comment]
@yinyanfr  可以使用 wave-in  试试
