### ISSUE TITLE
🧐[问题]flowchart 官方demo报错

### ISSUE THREAD

**Issue by 0212lewis** [ant-design/ant-design-charts#1255]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
用的是官方的flowchart组件demo，但是报错如图，并且为什么上面headerbar的保存之类的按钮不能点击？
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/23690175/162400869-2c5761cb-17f3-46dc-9650-50364070fdef.png)

**Comment by lxfu1** [comment]
图片没上传？

**Comment by 0212lewis** [comment]
> 



> 图片没上传？

上传了，看着很正常，拖动也没啥问题，就是保存按钮点了没用，另外左边【通用节点】tab点击一直都是展开的状态

**Comment by lxfu1** [comment]
你这个看上去是样式丢失了，你上层用 css 全局覆盖一下，右侧toolbar 遮挡了左侧 toolbar,审查元素就可以看到了。
