### ISSUE TITLE
🧐[问题] 地图按照api都配置完了为何不显示呢？

### ISSUE THREAD

**Issue by JonathanZay** [ant-design/ant-design-charts#1256]
![image](https://user-images.githubusercontent.com/38530758/162554559-f88f888b-a43c-4e33-8794-7f84186b3416.png)

![image](https://user-images.githubusercontent.com/38530758/162554547-065230f9-6b76-47e1-8840-29b13f80a71d.png)

**Comment by zlxu1984** [comment]
我也有同样问题，我还怀疑我配置错了 直接复制官方的行政区域地图的代码
https://charts.ant.design/zh/examples/map-choropleth/administrative#china-map
也是同样效果

我用的是mapbox 还去注册了token 设置token进去也是没有效果
我同样尝试过高德，稍有不同

高德的情况下组件（legend和zoom）也不会显示
mapbox的情况下会显示

<img width="916" alt="截屏2022-06-06 下午4 58 02" src="https://user-images.githubusercontent.com/24378336/172129893-705d0c2c-5404-4636-b12e-bf0dd9ab3717.png">

因为用了Ant Design Pro框架
我在config.js里面还尝试添加一下代码

`
scripts: {
   'https://api.tiles.mapbox.com/mapbox-gl-js/v1.5.0/mapbox-gl.js',
}
`
同样没有作用。

**Comment by JonathanZay** [comment]
官方的代码在自己代码示例下面的在线编辑器中也无效果。

**Comment by JonathanZay** [comment]
> 我也有同样问题，我还怀疑我配置错了 直接复制官方的行政区域地图的代码 https://charts.ant.design/zh/examples/map-choropleth/administrative#china-map 也是同样效果
> 
> 我用的是mapbox 还去注册了token 设置token进去也是没有效果 我同样尝试过高德，稍有不同
> 
> 高德的情况下组件（legend和zoom）也不会显示 mapbox的情况下会显示
> 
> <img alt="截屏2022-06-06 下午4 58 02" width="916" src="https://user-images.githubusercontent.com/24378336/172129893-705d0c2c-5404-4636-b12e-bf0dd9ab3717.png">
> 
> 因为用了Ant Design Pro框架 我在config.js里面还尝试添加一下代码
> 
> `scripts: { 'https://api.tiles.mapbox.com/mapbox-gl-js/v1.5.0/mapbox-gl.js', }` 同样没有作用。

而且官方的代码在自己代码示例下面的在线编辑器中也无效果。🥲

**Comment by lxfu1** [comment]
容器设置宽高试一下

**Comment by zlxu1984** [comment]
> 容器设置宽高试一下

这个我尝试过了， 我在config里面写过height和width 在外面容器的style里面也写过 没有什么用

**Comment by lxfu1** [comment]
在 codesandbox 上提供个示例

**Comment by zlxu1984** [comment]
我解决了 不要放在Card里面 我包了个DIV就出来了
![截屏2022-06-06 下午6 23 23](https://user-images.githubusercontent.com/24378336/172143339-89686e44-d15f-46a7-b9d7-1e8442b46bd6.png)
这个BUG也迷了

**Comment by JonathanZay** [comment]
已解决，跟父级容易宽度高度有关系。
