### ISSUE TITLE
🐛[BUG] 折线图  当 smooth  配置为true, 时， 无法触发 ‘element:click’ 等事件

### ISSUE THREAD

**Issue by jayrom123** [ant-design/ant-design-charts#1257]
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1. 设置 smooth  配置为true, 时， 
2. 无法触发 ‘element:click’ 等事件

### 🏞 期望结果 [描述你原本期望看到的结果]
可以触发

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/loving-poitras-jvqfd5?file=/index.js
### © 版本信息
- ant-design-charts 版本:1.3.5
- 浏览器环境 chrome 90 +
- 开发环境  macos

**Comment by royalrover** [comment]
同遇到这个问题，这个隐藏的bug耗费了1个小时才找到，希望尽快修复

**Comment by wozien** [comment]
很奇怪的是，有些情况就可以触发

**Comment by wozien** [comment]
试了一下，在设置 {point： null} 的情况是异常的，如果设置数据点的话是正常的

**Comment by wozien** [comment]
https://github.com/antvis/G2Plot/issues/3602

**Comment by lxfu1** [comment]
V2 
```ts
    shapeField: 'smooth',
    onReady: ({chart})=> {
      chart.on('element:click', ()=>{
        console.log(123)
      })
    }
```
