### ISSUE TITLE
🐛[BUG]  react-dom/test-utils 不应该在生产环境使用

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-charts#126]
```
import ReactTestUtils from 'react-dom/test-utils';
```

https://github.com/ant-design/ant-design-charts/blame/master/src/hooks/useChart.ts#L2

**Comment by lxfu1** [comment]
直接 PR 不香吗！

**Comment by lxfu1** [comment]
> ```
> import ReactTestUtils from 'react-dom/test-utils';
> ```
> 
> https://github.com/ant-design/ant-design-charts/blame/master/src/hooks/useChart.ts#L2

update
