### ISSUE TITLE
🧐[问题] Different color strokes on bars

### ISSUE THREAD

**Issue by philxo** [ant-design/ant-design-charts#1260]
I want different color strokes on bars depending on a field called status in my data. The color param lets you pass a function to do this, but for the barstyle, only strings can be passed as far as I can tell. Is there any way to do the same thing for color with the stroke color of the bar?
<img width="1532" alt="Screen Shot 2022-04-12 at 4 05 54 PM" src="https://user-images.githubusercontent.com/96539254/163044880-996f77d0-dd78-4d15-95f5-1013aa5316ad.png">

**Comment by lxfu1** [comment]
Can't,  you can implement this using Annotations.

**Comment by philxo** [comment]
Which annotation? And my stroke I mean border color, that's what the documentation seems to call it.

**Comment by lxfu1** [comment]
https://codesandbox.io/s/vigorous-wind-h6i8h8?file=/index.js
