### ISSUE TITLE
🧐[问题]可支持 L7多图表吗？

### ISSUE THREAD

**Issue by mengbo-ji** [ant-design/ant-design-charts#1261]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
可否支持中国地图 + 气泡图

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

类似于：https://antv-l7plot.gitee.io/zh/examples/advanced-plot/muti-plots#china-bubble 这里的，目前我发现 ant-design-charts中 dot area等都是分开的，怎么在ant-design-charts中做到 这样的图呢？

<img width="652" alt="image" src="https://user-images.githubusercontent.com/54396390/163123313-b658767b-0c86-4c9a-83b6-0d8d53ce5d4c.png">

**Comment by lxfu1** [comment]
暂时没有，后续会加上。
