### ISSUE TITLE
🧐[问题] 关于 DecompositionTreeGraph 目标拆解图，配置项 level

### ISSUE THREAD

**Issue by JaylanChen** [ant-design/ant-design-charts#1263]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

DecompositionTreeGraph 目标拆解图，配置项level ，官方描述为：`设置默认展开层级，默认 100。`；

但是放我设置level2,时，却只能渲染2级的，并不是默认展开2级；

不知道是我理解的有偏差，还是bug；

如果我理解的有问题，level 是最大渲染级别，那么怎么实现默认展开2级，2级之后，可以手动展开；

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
[https://codesandbox.io/s/42go5y](https://codesandbox.io/s/42go5y)

**Comment by lxfu1** [comment]
level 是默认展开层级，是否可以手动展开可以结合 marker 配置和异步请求， https://charts.ant.design/zh/examples/relation-graph/decomposition-tree-graph#async-load

**Comment by JaylanChen** [comment]
> level 是默认展开层级，是否可以手动展开可以结合 marker 配置和异步请求， https://charts.ant.design/zh/examples/relation-graph/decomposition-tree-graph#async-load

目前只能这么解决了；
