### ISSUE TITLE
🐛 [BUG] tooltips are throwing errors in React 18

### ISSUE THREAD

**Issue by MarkLyck** [ant-design/ant-design-charts#1269]
### 🐛 bug 

After upgrading to React 18, hovering over a chart with a tooltip throws the following error:

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

Looking into the code a bit I found this file: https://github.com/ant-design/ant-design-charts/blob/master/packages/plots/src/util/createNode.ts

```
// @ts-ignore
import ReactDOM from 'react-dom';
var createNode = function (children, type) {
    var mountPoint = document.createElement('div');
    if (type === 'tooltip') {
        mountPoint.className = 'g2-tooltip';
    }
    ReactDOM.render(children, mountPoint);
    return mountPoint;
};
export default createNode;
```

This is using the old way to render in reactDOM and needs to be upgraded to use React 18's createRoot method. It's a very simple upgrade to do.

Please see this short guide: https://reactjs.org/link/switch-to-createroot

### 📷

![Screen Shot 2022-04-18 at 15 28 57](https://user-images.githubusercontent.com/6841110/163865061-d19ad7da-4864-4251-903c-93f0b5210bf7.png)

- ant-design-charts 版本: 1.3.6

**Comment by MarkLyck** [comment]
Created a PR for this: https://github.com/ant-design/ant-design-charts/pull/1270

**Comment by lxfu1** [comment]
`@ant-design/plots 1.2.0`
