### ISSUE TITLE
🐛[BUG] Getting error when running the Quick Start example: Module not found: Error: Can't resolve '@antv/xflow-extension'

### ISSUE THREAD

**Issue by mdaguerre** [ant-design/ant-design-charts#1273]
### 🐛 bug 
When i start my app (create react app) that only have the [quickstart demo](https://charts.ant.design/en/docs/manual/getting-started) I'm getting this error in the CLI:
```
ERROR in ./node_modules/@ant-design/flowchart/es/index.js 5:0-71
Module not found: Error: Can't resolve '@antv/xflow-extension'
```

- ant-design-charts: Latest (1.3.6)
- Mac OS

**Comment by lxfu1** [comment]
Try the subpackages
- Plots: @ant-design/plots
- Maps: @ant-design/maps
- Flowchart: @ant-design/flowchart
- Relation Graphs: @ant-design/graphs

**Comment by lxfu1** [comment]
update, `@ant-design/flowchart@1.1.2`
