### ISSUE TITLE
🐛[BUG]双折线图（DualAxes类）添加slider拖拽，两条线不对应，一条线会超出x轴，造成数据根据x轴对应不上，数据混乱

### ISSUE THREAD

**Issue by Mr-jili** [ant-design/ant-design-charts#1274]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
双折线图（DualAxes类）添加slider拖拽，两条线不对应，一条线会超出x轴，造成数据根据x轴对应不上，数据混乱
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
🐛[BUG]双折线图（DualAxes类）添加slider拖拽，两条线不对应，一条线会超出x轴，造成数据根据x轴对应不上，数据混乱，但执行resize事件会变正常，slider拖拽也会出现数据对应不上，导致混乱
### 🏞 期望结果 [描述你原本期望看到的结果]
数据根据x轴进行对应
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { DualAxes } from '@ant-design/plots';

const DemoDualAxes = () => {
  const data = [{"label":"2022-04-01","total":4.96,"fee":4.27,"index":1},{"label":"2022-04-02","total":7.14,"fee":6.89,"index":2},{"label":"2022-04-03","total":5.44,"fee":4.99,"index":3},{"label":"2022-04-04","total":5.17,"fee":4.79,"index":4},{"label":"2022-04-05","total":4.13,"fee":3.94,"index":5},{"label":"2022-04-06","total":4.52,"fee":4.13,"index":6},{"label":"2022-04-07","total":1.14,"fee":1.24,"index":7},{"label":"2022-04-08","total":1.14,"fee":1.16,"index":8},{"label":"2022-04-09","total":1.12,"fee":1.14,"index":9},{"label":"2022-04-10","total":1.1,"fee":1.09,"index":10},{"label":"2022-04-11","total":1.72,"fee":1.56,"index":11},{"label":"2022-04-12","total":5.76,"fee":4.92,"index":12},{"label":"2022-04-13","total":30,"fee":28.49,"index":13},{"label":"2022-04-14","total":21.45,"fee":21.85,"index":14},{"label":"2022-04-15","total":1.16,"fee":1.06,"index":15},{"label":"2022-04-16","total":8.45,"fee":6.89,"index":16},{"label":"2022-04-17","total":11.76,"fee":12.78,"index":17},{"label":"2022-04-18","total":14.65,"fee":11.94,"index":18},{"label":"2022-04-19","total":19.89,"fee":16.34,"index":19},{"label":"2022-04-20","total":12.05,"fee":14.14,"index":20},{"label":"2022-04-21","total":0,"fee":0,"index":21},{"label":"2022-04-22","total":0,"fee":0,"index":22},{"label":"2022-04-23","total":0,"fee":0,"index":23},{"label":"2022-04-24","total":0,"fee":0,"index":24},{"label":"2022-04-25","total":0,"fee":0,"index":25},{"label":"2022-04-26","total":0,"fee":0,"index":26},{"label":"2022-04-27","total":0,"fee":0,"index":27},{"label":"2022-04-28","total":0,"fee":0,"index":28},{"label":"2022-04-29","total":0,"fee":0,"index":29},{"label":"2022-04-30","total":0,"fee":0,"index":30}];
  const config = {
    data: [data, data],
    xField: 'label',
    yField: ['total', 'fee'],
    geometryOptions: [
      {
        geometry: 'line',
        color: '#5B8FF9',
      },
      {
        geometry: 'line',
        color: '#5AD8A6',
      },
    ],
    slider: {}
  };
  return <DualAxes {...config} />;
};

ReactDOM.render(<DemoDualAxes />, document.getElementById('container'));
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/489

**Comment by Mr-jili** [comment]
thank you
