### ISSUE TITLE
Next js problem with @ant-design/charts, error location: node_modules\@antv\x6-react-components\es\toolbar\item.js

### ISSUE THREAD

**Issue by kostazol** [ant-design/ant-design-charts#1275]
I got error on compile

./node_modules/antd/es/popover/style/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\@antv\x6-react-components\es\color-picker\index.js

Import trace for requested module:
./node_modules/@antv/x6-react-components/es/color-picker/index.js
./node_modules/@antv/x6-react-components/es/index.js
./node_modules/@antv/xflow-extension/es/canvas-context-menu/components/index.js
./node_modules/@antv/xflow-extension/es/canvas-context-menu/index.js
./node_modules/@antv/xflow-extension/es/index.js
./node_modules/@ant-design/flowchart/es/index.js
./node_modules/@ant-design/charts/es/index.js
./features/nodeInfo/view/NodeChart/NodeChart.tsx
./features/nodeInfo/index.tsx
./modules/HomePage/HomePage.tsx
./modules/index.ts
./pages/index.tsx

I don't have this error on version 1.1.16, and I have this error on version 1.3.6

**Comment by williampeterpaul** [comment]
temp solution described in #556 by rolling back to an older version of @ant-design/charts and using next/dynamic to dynamically import the modules

**Comment by williampeterpaul** [comment]
Related to @antv/g2 version 4.2.0, manually installing that sub-package at version 4.1.50 fixed

**Comment by devgurbir** [comment]
Hi @williampeterpaul, 

I'm getting this error. Could you please explain the solution in a simplified manner? Noob here.

**Comment by williampeterpaul** [comment]
@devgurbir 

@ant-design/charts requires @ant/g2 but the latest version (4.2.0) of g2 seems to be causing this issue. By manually installing an older version of g2 (4.1.50) and rebuilding the dependency tree (delete package-lock) you can temporarily circumvent the issue

**Comment by devgurbir** [comment]
@williampeterpaul Had to mess around a bit but it worked eventually :) 

Thank you so much.

**Comment by williampeterpaul** [comment]
@devgurbir No problem man, glad I could help.

**Comment by showarp** [comment]
Please repair this bug as soon as possible

**Comment by lxfu1** [comment]
The problem lies in `@ant-design/flowchart`, it is recommended to use subpackages or configure:

```ts
import dynamic from "next/dynamic";
const Line = dynamic(
  () => import("@ant-design/charts").then((mode) => mode.Line),
  { ssr: false }
);
```
