### ISSUE TITLE
Donut圆环图value为null

### ISSUE THREAD

**Issue by liujiayu10** [ant-design/ant-design-charts#128]
@ant-design/charts": "^0.9.9"  还没有修复，前面已经有人提过了！

https://github.com/ant-design/ant-design-charts/issues/96

**Comment by lxfu1** [comment]
这个问题已经修复，如果更新无效的话建议删除node_modules 重新install。

**Comment by liujiayu10** [comment]
前几天就看到了，确实更新了，版本号还是0.99，但已经更新了。谢谢。@lxfu1
