### ISSUE TITLE
🧐[问题] 地图气温气泡，点击事件如何阻止冒泡

### ISSUE THREAD

**Issue by tpc-ht** [ant-design/ant-design-charts#1280]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
如何在点击气泡的时候不触发全局的点击事件
![image](https://user-images.githubusercontent.com/59469126/164586609-75fb9642-d47c-43ab-be10-5ff32a124375.png)

**Comment by lvisei** [comment]
@tpc-ht 通过事件源，判断点击事件来自哪里

```js
evt.target
// or
evt.feature

```
