### ISSUE TITLE
🧐[问题] Pie 的label属性可以使用html自定义吗？

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/ant-design-charts#1281]
### 🚑 其他信息 ：
![image](https://user-images.githubusercontent.com/33271366/164956911-550021f5-0c2c-4e6d-84dc-d1bab085aa17.png)

**Comment by lxfu1** [comment]
不支持，可以用canvas绘制， https://charts.ant.design/zh/examples/pie/basic#pie-custome-label

**Comment by PLUTO06210331** [comment]
ok
