### ISSUE TITLE
🐛[BUG]pie在window下legend被遮住

### ISSUE THREAD

**Issue by xiaoXiang-l** [ant-design/ant-design-charts#1285]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
pie组件配置renderer: 'canvas'在window下图例被遮住，在mac下可以正常显示，但是如果改成renderer: 'svg'，又会出现https://github.com/ant-design/ant-design-charts/issues/717   这种情况
### 🏞 期望结果 [描述你原本期望看到的结果]
window下图例不应该被遮住
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
renderer: 'canvas'
### © 版本信息
"@ant-design/plots": "^1.0.9"
- 浏览器环境
- chrome
- 
### 🚑 其他信息 
<img width="372" alt="image" src="https://user-images.githubusercontent.com/35293312/164973896-0c558298-93e7-4bf8-97be-23326ed5d4f3.png">

**Comment by yanzi123** [comment]
请问解决了吗？我也遇到这个问题，图例丢失或者被遮挡

**Comment by lxfu1** [comment]
设置一下 `legend.itemHeight: 20` 试试
