### ISSUE TITLE
🐛[BUG] Critical security vulnerabilities [immer and minimist]

### ISSUE THREAD

**Issue by erendabanlioglu** [ant-design/ant-design-charts#1289]
### 🐛  Bug description [describe the bug in detail so that everyone can understand]

Library used outdate version of immer and minimist which have critical security issues.

### 📷  Steps to reproduce [describe the steps to reproduce clearly so others can see the problem]

Run audit. (yarn audit)

### 🏞  Desired outcome [Describe the outcome you would have expected to see]

No crititcal security issue.

### 💻  Reproducible code [provide reproducible code, repository, or online example]

![image](https://user-images.githubusercontent.com/8245836/165113861-7a4e4de8-12f6-402e-a831-22cec561d942.png)
![image](https://user-images.githubusercontent.com/8245836/165113902-ad851325-32f6-40e4-a0c6-a9d085070d30.png)

### © Version information

"@ant-design/charts@^1.3.6":
  version "1.3.6"
  resolved "https://registry.yarnpkg.com/@ant-design/charts/-/charts-1.3.6.tgz#edf652c89ca3edd75e0caa07347b957ef608fc66"
  integrity sha512-4mKvm6C03JkQiUhxHE8XLSZ2oQeLQL8pL0B+e77DvFRZpDztAxm4I6AlDcCuSq45ZIsv7K+XQcozJGs6NV+g6g==

- ant-design-charts version: 1.3.6
- Browser environment: Inapplicable
- Development environment: Inapplicable

**Comment by tiarebalbi** [comment]
+1

**Comment by ma101an** [comment]
+1
