### ISSUE TITLE
🐛[BUG] OrganizationGraph: dragging nodes does not always work

### ISSUE THREAD

**Issue by yay** [ant-design/ant-design-charts#1291]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

This pretty much says it all:

https://user-images.githubusercontent.com/1799756/165179671-ecc97e32-06de-4a87-a066-d0cd9914a6e6.mp4

It seems like I can only drag the rectangles by clicking and holding the right-hand side of it, not the left-hand side.

### 🏞 期望结果 [描述你原本期望看到的结果]

I would expect to be able to drag by clicking anywhere in a rect, including the text.

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://charts.ant.design/en/examples/relation-graph/organization-graph#basic

### © 版本信息

```
macOS 12.3.1 (darwin-arm64)
@ant-design/graphs: 1.1.1
antd: 4.19.5
react: ^18.0.0
react-dom: ^18.0.0
typescript: ^4.6.3
```

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/1742
