### ISSUE TITLE
Attempted import error: 'EditorPanels' is not exported from '@antv/xflow-extension'

### ISSUE THREAD

**Issue by williamjiangsa** [ant-design/ant-design-charts#1293]
Attempted import error: 'EditorPanels' is not exported from '@antv/xflow-extension'

    "@ant-design/charts": "^1.3.6",
    "@ant-design/icons": "^4.6.2",
    "@antv/data-set": "^0.11.8",
    "@antv/xflow": "^1.0.45",

**Comment by lxfu1** [comment]
Update, `@ant-design/flowchart@1.1.2`
