### ISSUE TITLE
🐛[BUG]行政区域钻取图例显示为上一个区域数据

### ISSUE THREAD

**Issue by 7NZ** [ant-design/ant-design-charts#1295]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
下钻返回后，图例总是显示上一个下钻区域数据
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
下钻一个省，返回，再下钻另一个省，图例数据显示的是上一个省
### 🏞 期望结果 [描述你原本期望看到的结果]
图例数据总是和当前下钻区域一致
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://charts.ant.design/zh/examples/map-choropleth/drill#drill-callback
### © 版本信息

- ant-design-charts 版本: 1.3.6
- 浏览器环境 firefox 99
- 开发环境  window 10

**Comment by lvisei** [comment]
依赖的 L7PLot 用最新的就行，不会出现这个问题 @7NZ 

@lxfu1 官网重新打包一下，升级最新的 L7PLot

**Comment by Veveue** [comment]
还有就是这个  [示例](https://charts.ant.design/zh/examples/map-choropleth/drill#drill-callback )  市区 的`value` 无效 没正常显示 @lvisei
