### ISSUE TITLE
🧐[问题]如何默认显示tooltip

### ISSUE THREAD

**Issue by aphen** [ant-design/ant-design-charts#1297]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
当组件渲染完成时，默认显示一个tooltip, 以及当active时，根据条件显示某一个tooltip
现在鼠标放上去才能显示
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
就像之前f2当中的
![image](https://user-images.githubusercontent.com/8229846/165497456-69689f2a-c204-4e34-af88-8bdb9ed41aef.png)
![image](https://user-images.githubusercontent.com/8229846/165497961-69f5bf3d-5c69-4b36-98d7-efd27dcbfd37.png)

**Comment by lxfu1** [comment]
```ts
    onReady: (plot)=>{ 
      const  {x, y} = plot.chart.getElements()[0].getModel(); 
      plot.chart.showTooltip({x, y});
    }
```

**Comment by Fengfa101126** [comment]
这个写在 tooltip：{ ................}  里面么？
