### ISSUE TITLE
🧐[问题]网格布局时，如何配置图表响应resize事件重绘？

### ISSUE THREAD

**Issue by wangmeijian** [ant-design/ant-design-charts#1299]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
网格布局时，如何配置图表响应resize事件重绘？
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
demo: https://codesandbox.io/s/wang-ge-bu-ju-shi-ru-he-pei-zhi-tu-biao-xiang-ying-resizeshi-jian-chong-hui-5ukoym?file=/src/App.js
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
放大浏览器窗口，正常重新渲染了，**缩小浏览器窗口，图表不响应resize事件**，如何配置？

**Comment by lxfu1** [comment]
正常是支持的，检测下为什么 grid 模式下没有触发 resize

**Comment by wangmeijian** [comment]
> 正常是支持的，检测下为什么 grid 模式下没有触发 resize

看看上面的demo要如何配置呢？

**Comment by wangmeijian** [comment]
没有人维护的样子
