### ISSUE TITLE
🐛[BUG]官网safari浏览器打不开

### ISSUE THREAD

**Issue by lovelyyl** [ant-design/ant-design-charts#1300]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

https://charts.ant.design

SyntaxError: Invalid regular expression: invalid group specifier name

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
无法复现啊，提供Safari版本号后再打开
