### ISSUE TITLE
👑 [需求]  Multi-View for range-area

### ISSUE THREAD

**Issue by BobForCat** [ant-design/ant-design-charts#1301]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

Hi, From the list of MultiView of [ant-design/charts](https://charts.ant.design/en/examples/gallery#category-MultiViewPlot%F0%9F%94%A5) there is one missing regarding [g2plot](https://g2plot.antv.vision/en/examples/plugin/multi-view#range-area)

The one that have a line combined with a range/interval around.

![image](https://user-images.githubusercontent.com/68346563/166102879-36b0dc10-b8f0-41b8-9ba8-fa0fe87030ce.png)

Is that something willing to be done ? Is there another way to do it (in react so) ? Is there no solution ? 

Thanks

**Comment by flekpy** [comment]
Hi, I need this type of graph too, have you found a solution?

**Comment by lxfu1** [comment]
https://codesandbox.io/s/empty-cookies-fziq2d?file=/index.js
