### ISSUE TITLE
保存数据

### ISSUE THREAD

**Issue by BrickerZou** [ant-design/ant-design-charts#1304]
请问有没有类似于X6的toJson fromJson的保存 流程图 数据的API？

**Comment by BrickerZou** [comment]
Flowchart

**Comment by lxfu1** [comment]
试一下直接使用x6实例

**Comment by lgh-qt** [comment]
onSave 无法生效问题有遇到吗

**Comment by lxfu1** [comment]
> onSave 无法生效问题有遇到吗

更新一下，之前可能是被 scale 遮挡了，点击失效。
