### ISSUE TITLE
🐛[BUG] React.StrictMode 下导致 OrganizationGraph 的重复出现

### ISSUE THREAD

**Issue by Nativu5** [ant-design/ant-design-charts#1305]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
对于 [OrganizationGraph 的例子](https://charts.ant.design/zh/examples/relation-graph/organization-graph#basic)，如果父组件为 `<React.StrictMode>` 会导致 OrganizationGraph 在页面上重复出现。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1. 使用 CRA 初始化一个项目。将 index.js 改为：
```js
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
// import App from './App';
import { DemoOrganizationGraph } from './chart';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <DemoOrganizationGraph />
  </React.StrictMode>
);
```
2. 新建 chart.js:
```js
import React from 'react';
import { OrganizationGraph } from '@ant-design/graphs';

export const DemoOrganizationGraph = () => {
此处省略，内容与官方文档中的实例完全相同。
}
```
3. 查看渲染效果：
![image](https://user-images.githubusercontent.com/44155313/166655840-28263b42-2bc4-4efe-83d0-5913b74a81a1.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
如上图，图表出现了两次。

期望只出现一次。

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

复现代码如上。
经过测试发现，只要去掉 `<React.StrictMode>` 就能正确渲染。

### © 版本信息

- ant-design-charts 版本: 1.3.6
- 浏览器环境：Microsoft Edge 版本 101.0.1210.32 (正式版本) (64 位)
- 开发环境：Windows 11 x64

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
截图如上。

**Comment by lxfu1** [comment]
感觉和React.StrictMode没啥关系，可能是18的问题

**Comment by h1530687053** [comment]
有什么解决方式么？似乎关系图都有这个问题

**Comment by wsy19961129** [comment]
请问这个问题有没有解决方案呢？React版本 18.2.0

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/1554
