### ISSUE TITLE
👑 [需求]是否可以将lodash依赖改为lodash-es

### ISSUE THREAD

**Issue by faner11** [ant-design/ant-design-charts#1306]
能否将lodash升级为lodash-es ，降低打包大小，如果可以，我可以贡献代码

**Comment by lxfu1** [comment]
非常感谢，由于 lodash 是底层库依赖，charts 层改不了，而且在 util 稍多的时候，es并不理想，非常期待你的贡献
![image](https://user-images.githubusercontent.com/31396322/167350212-2cb09e16-4e4c-4e63-b4d7-3b30179e8575.png)
