### ISSUE TITLE
👑 [需求]柱线混合图形，折线图坐标轴是感觉数据最大值进行等分的，并不会像柱形图一样自动取整。

### ISSUE THREAD

**Issue by 863183638** [ant-design/ant-design-charts#131]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

柱线混合图中，会出现折线图的坐标轴数据不是整数的情况，发现是根据数据的最大值进行等分的，而不是像柱形图或者单纯的折线图那样进行取整的。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
https://codesandbox.io/s/eloquent-leaf-qvw1g?file=/demo.tsx
![image](https://user-images.githubusercontent.com/11581040/88775977-f3ef7b80-d1b7-11ea-8ea2-8a0ff9416794.png)

**Comment by lxfu1** [comment]
升级到 1.0 版本， 参考： https://charts.ant.design/demos/dual-axes#%E6%9F%B1%E7%BA%BF%E6%B7%B7%E5%90%88%E5%9B%BE%E8%A1%A8-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
```ts
 yAxis: [
        {
          max: 2000,
        },
        {
          max: 1200
        },
      ],
geometryOptions: []
```
