### ISSUE TITLE
🧐[问题] 如何设置 DecompositionTreeGraph 的主题或修改背景色

### ISSUE THREAD

**Issue by jakelynngh** [ant-design/ant-design-charts#1310]
DecompositionTreeGraph 的 theme 设置似乎没有效果 在基础配置里也没有找到修改背景色的属性 
求教如何设置主题或者修改背景色 来满足与系统主题的协调一致 求指点

**Comment by lxfu1** [comment]
DecompositionTreeGraph 目前不支持 theme，但节点所有样式都是支持个性化设置的，能细化一下你的诉求吗？

**Comment by jakelynngh** [comment]
谢谢回复 其实就是想修改整体的背景颜色 在黑暗模式下 背景色白色太突兀了
经过测试发现 通过设置 style 下的 backgroundColor 可以直接修改背景色 可以达到预期效果
