### ISSUE TITLE
🧐[问题] 堆叠柱线图表 隐藏右侧的Y轴?

### ISSUE THREAD

**Issue by StevenGardnerGMJ** [ant-design/ant-design-charts#1311]
### 🧐 问题描述 
使用 堆叠柱线图表 如何隐藏右侧的Y轴? 我试了很多参数,但是都不成功,是不是我遗漏了什么方式.

### 💻 示例代码 

> geometryOptions: [
      {
        geometry: "column", // 柱形图对应的配置
        isStack: true,
        seriesField: "type",
        columnWidthRatio: 0.1, // 柱子变细
        columnStyle: {
          radius: 20, // 设置柱状带有圆角
        },
        legend: {
          // 把marker从square变成 左右圆角点
          marker: {
            symbol: (x, y, r, ctx) => {
              return [
                ["M", x + r, y - r], // 落点
                ["A", r, r, 0, 0, 0, x + r, y + r], // 终点0 + 左半圆
                ["L", x + r + 4, y + r], // 直线
                ["A", r, r, 0, 0, 0, x + r + 4, y - r], // 终点0 - 右半圆
                ["z"], // 闭环
              ];
            },
            style: (oldStyle) => {
              return {
                ...oldStyle,
                r: 2,
                lineWidth: 1,
                // square marker 只有填充色，赋给 line 的 stroke
                stroke: oldStyle.fill,
              };
            },
          },
        },
      },
      {
        geometry: "line",
        seriesField: "type",
        yAxis: true,
        smooth: true,
        label: {
          style: { fill: "#f00" },
        },
        legend: {
          marker: {
            spacing: 2,
          },
        },
      },
    ],
  };

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
[
<img width="453" alt="881D695F79357D8970861BD7F0EB92FE" src="https://user-images.githubusercontent.com/8157683/167330192-410b9f0f-5249-4759-990e-89c730b44e5b.png">
](url)

**Comment by lxfu1** [comment]
```ts
 yAxis: [{}, false],
```

**Comment by StevenGardnerGMJ** [comment]
我阅读了部分示例代码发现是遗漏了一个点, 
正确配置方式是:

> yField: ["value", "count"],
    yAxis: {
      value: {
        tickCount: 4, //期望的坐标轴刻度数量 实际以整除等分计算为准
      },
      count: false, // 右侧Y轴隐藏
    },
其中`yField: ["value", "count"]` 是你的两个数据项
与之对应的 `yAxis` 也应该是这两个参数 `value `  和  `count `,
说以只要 设置与之对应 `count: false` 就可以隐藏右侧 Y轴
目前是不支持中文的参数.
