### ISSUE TITLE
🐛[BUG] BarConfig type is not compatible

### ISSUE THREAD

**Issue by donghoon-song** [ant-design/ant-design-charts#1313]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
https://charts.ant.design/en/examples/bar/basic#basic
I tried the example code with Typescript but config type is not compatible.
### 🏞 期望结果 [描述你原本期望看到的结果]
<img width="1628" alt="image" src="https://user-images.githubusercontent.com/32301380/167536602-226cb0d2-0fc0-43b4-a5ec-a3e6478eaed6.png">

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
```ts
legend: {
    position: 'top-left' as 'top-left',
  },

OR

const config = {} as const;
```
