### ISSUE TITLE
🐛[BUG] @ant-design/charts 1.3.6 have 648 warning in webpack compile

### ISSUE THREAD

**Issue by hamidgarousi** [ant-design/ant-design-charts#1314]
### 🐛 bug@ant-design/charts 1.3.6 have 648 warning in webpack compile

hi everyone 
I use this library with react 17 and antd but the library has too many warnings when compiled with webpack 

project is implemented with create-react-app

the warnings are like this :
```
WARNING in ./node_modules/inversify/lib/utils/serialization.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\garou\Desktop\Projects\nyx\node_modules\inversify\src\utils\serialization.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\garou\Desktop\Projects\nyx\node_modules\inversify\src\utils\serialization.ts'
```

package.json file :
```
{
  "name": "nyx",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@ant-design/charts": "^1.3.6",
    "@ant-design/icons": "^4.7.0",
    "@reduxjs/toolkit": "^1.8.1",
    "@sentry/react": "^6.19.7",
    "@sentry/tracing": "^6.19.7",
    "antd": "^4.20.3",
    "axios": "^0.27.2",
    "i18next": "^21.8.0",
    "i18next-http-backend": "^1.4.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "react": "^17.0.2",
    "react-beautiful-dnd": "^13.1.0",
    "react-cookie": "^4.1.1",
    "react-dom": "^17.0.2",
    "react-i18next": "^11.16.9",
    "react-redux": "^7.2.8",
    "react-router-dom": "^6.3.0",
    "react-scripts": "^5.0.1",
    "styled-components": "^5.3.5",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/node": "^17.0.31",
    "@types/react": "^17.0.45",
    "@types/react-beautiful-dnd": "^13.1.2",
    "@types/react-dom": "^17.0.16",
    "@types/react-router-dom": "^5.3.3",
    "@types/styled-components": "^5.1.25",
    "typescript": "^4.6.4"
  }
}

```

**Comment by NatsGt** [comment]
I had the same issue, but I think is a react-script issue, I added `GENERATE_SOURCEMAP=false` to my `env `and worked fine.

**Comment by jianzhicangqiong** [comment]
> ### 🐛 bug@ant-design/charts 1.3.6 have 648 warning in webpack compile
> hi everyone I use this library with react 17 and antd but the library has too many warnings when compiled with webpack
> 
> project is implemented with create-react-app
> 
> the warnings are like this :
> 
> ```
> WARNING in ./node_modules/inversify/lib/utils/serialization.js
> Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from 'C:\Users\garou\Desktop\Projects\nyx\node_modules\inversify\src\utils\serialization.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\garou\Desktop\Projects\nyx\node_modules\inversify\src\utils\serialization.ts'
> ```
> 
> package.json file :
> 
> ```
> {
>   "name": "nyx",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@ant-design/charts": "^1.3.6",
>     "@ant-design/icons": "^4.7.0",
>     "@reduxjs/toolkit": "^1.8.1",
>     "@sentry/react": "^6.19.7",
>     "@sentry/tracing": "^6.19.7",
>     "antd": "^4.20.3",
>     "axios": "^0.27.2",
>     "i18next": "^21.8.0",
>     "i18next-http-backend": "^1.4.0",
>     "jwt-decode": "^3.1.2",
>     "lodash": "^4.17.21",
>     "react": "^17.0.2",
>     "react-beautiful-dnd": "^13.1.0",
>     "react-cookie": "^4.1.1",
>     "react-dom": "^17.0.2",
>     "react-i18next": "^11.16.9",
>     "react-redux": "^7.2.8",
>     "react-router-dom": "^6.3.0",
>     "react-scripts": "^5.0.1",
>     "styled-components": "^5.3.5",
>     "web-vitals": "^2.1.4"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject"
>   },
>   "eslintConfig": {
>     "extends": [
>       "react-app",
>       "react-app/jest"
>     ]
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
>   "devDependencies": {
>     "@types/node": "^17.0.31",
>     "@types/react": "^17.0.45",
>     "@types/react-beautiful-dnd": "^13.1.2",
>     "@types/react-dom": "^17.0.16",
>     "@types/react-router-dom": "^5.3.3",
>     "@types/styled-components": "^5.1.25",
>     "typescript": "^4.6.4"
>   }
> }
> ```

change "react-scripts": "^5.0.1"  to "react-scripts: 4.x"
