### ISSUE TITLE
load component failed DOMException: Failed to construct 'Worker': Access to the script at 'blob:http://localhost:8000/1161b980-c8f9-4339-9864-68a26a43d200' is denied by the document's Content Security Policy.🧐[问题]

### ISSUE THREAD

**Issue by XingToYang** [ant-design/ant-design-charts#1315]
### 问题截图
![image](https://user-images.githubusercontent.com/9374545/167577746-4cbc74f3-aa15-4691-a6c8-f67e72531928.png)

### 代码
`import { Line } from '@ant-design/charts';

export const IsNewCarPremium: React.FC = () => {
  const data = [
    { year: '1991', value: 3 },
    { year: '1992', value: 4 },
    { year: '1993', value: 3.5 },
    { year: '1994', value: 5 },
    { year: '1995', value: 4.9 },
    { year: '1996', value: 6 },
    { year: '1997', value: 7 },
    { year: '1998', value: 9 },
    { year: '1999', value: 13 },
  ];

  const config = {
    data,
    width: 800,
    height: 400,
    autoFit: false,
    xField: 'year',
    yField: 'value',
    point: {
      size: 5,
      shape: 'diamond',
    },
    label: {
      style: {
        fill: '#aaa',
      },
    },
  };

  let chart;

  // Export Image
  const downloadImage = () => {
    chart?.downloadImage();
  };

  // Get chart base64 string
  const toDataURL = () => {
    console.log(chart?.toDataURL());
  };

  return (
    <div>
      <button type="button" onClick={downloadImage} style={{ marginRight: 24 }}>
        Export Image
      </button>
      <button type="button" onClick={toDataURL}>
        Get base64
      </button>
      <Line {...config} onReady={(chartInstance) => (chart = chartInstance)} />
    </div>
  );
};
`

**疑似问题所在：nodu_modules/@antv/g2/esm/geometry/label/layout/hide-overlap.js中使用createWorker，触发了blob违反CSP错误**

**Comment by iamsourabhh** [comment]
Facing the same issue.

**Comment by iamsourabhh** [comment]
Any updates? @visiky

**Comment by mizhousoft** [comment]
The same issue
![image](https://user-images.githubusercontent.com/4065604/171806601-25730d60-3239-4efb-af64-3eb67fbb7b3d.png)

**Comment by mizhousoft** [comment]
solve it, add http header, like this;
add_header Content-Security-Policy "worker-src blob:;"

**Comment by iamsourabhh** [comment]
@mizhousoft Adding worker-src blob is a security vulnerablity.

**Comment by mizhousoft** [comment]
@iamsourabhh 

specifies valid source

**Comment by yosdanybm** [comment]
any updates? @visiky, @mizhousoft @iamsourabhh I have tried different ways to add explicitly worker-src and always the same error, note: This error is with chrome 
<img width="1868" alt="Screenshot 2023-01-17 at 11 42 29 PM" src="https://user-images.githubusercontent.com/12848126/213086692-ee707b29-5409-4d30-9647-f3d38413c11c.png">
