### ISSUE TITLE
🧐[问题] 基础玫瑰图(南丁格尔图)是否支持添加背景图片

### ISSUE THREAD

**Issue by StevenGardnerGMJ** [ant-design/ant-design-charts#1316]
### 🧐 问题描述 
有这样的业务需求: 在玫瑰图添加一圈外圈使得更加美观
思路有两种:
1, 使用SVG path 绘制一个外圈
2, 添加背景图片
请问是否支持添加背景图片?

### 💻 示例代码 

> import { Rose } from "@ant-design/plots";
> autoFit: true,
    data,
    xField: "type",
    yField: "value",
    seriesField: "type",
    radius: 0.6, // 玫瑰图的半径
    innerRadius: 0.5,
    padding: [0, 0, 0, -200],

### 🚑 其他信息 

[
![jichmeiguitu](https://user-images.githubusercontent.com/8157683/167606017-57085d2b-c995-4791-82cc-dd06193815a9.png)
](url)

**Comment by lxfu1** [comment]
https://codesandbox.io/s/loving-http-wgymgx?file=/index.js
