### ISSUE TITLE
🧐[问题]折线图Line如何配置Y轴的缩略图呢？文档只看到配置X轴的缩略图。slider

### ISSUE THREAD

**Issue by zhangzongbin** [ant-design/ant-design-charts#1317]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
折线图Line如何配置Y轴slider？

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
  const config = {
    data: dataSource?.values,
    height: 500,
    autoFit: true,
    padding: 'auto',
    xField: 't',
    yField: 'v',
    seriesField: 'n',
    xAxis: { tickCount: 10 },
    slider: {
      start: 0,
      end: 1,
    },
    interactions: [{ type: 'brush' }],
    meta: {
      t: {
        // type: 'time',
        // mask: 'YYYY-MM-DD HH:mm:ss',
      },
      v: {
        type: 'pow',
        formatter: (v: number) => {
          return v.toFixed(2);
        },
      },
      n: {
        formatter: (v: string) => {
          return dataSource?.columns[v]?.name;
        },
      },
    },
    tooltip: {
      position: 'bottom ',
    },
    legend: {
      layout: 'vertical',
      position: 'right-top',
    },
  };

**Comment by lxfu1** [comment]
y轴用scrollbar
