### ISSUE TITLE
🧐[问题] 刻度线能否根据图表宽度自动撑满？

### ISSUE THREAD

**Issue by BluesVN** [ant-design/ant-design-charts#1324]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/27759401/168508608-5d559be1-02e0-466d-8b84-2fc7c1674fad.png">

如图红色虚线 与x轴平行。
由于网格线 grid 已经不支持自定义 formatter 。
所以采用的tickLine进行绘制。
问题是 length 目前是固定的 无法根据图表宽度变化自适应 如何解决？有没有一个属性配置直接撑满？

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
    tickLine: {
  
      length: -Number(
        document.querySelector(
          "#root > section > section > main > div > div:nth-child(2) > div:nth-child(1)",
        )?.clientWidth || 680,
      ),
}
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
    "@ant-design/charts": "^1.3.6",

**Comment by lxfu1** [comment]
没看懂你要做什么~~

**Comment by eternallycyf** [comment]
是否指刻度线太少?  
通过这几个属性调整(tickCount,tickMethod,nice任选其一)
```js
xAxis:{
  nice: true,
  min: 0,
  max: 35,
  tickInterval: 7,
  tickCount: 8,
  tickMethod: function tickMethod(_ref) {
          var max = _ref.max;
          var interval = Math.ceil(max / 9);
          return [
            0,
            interval,
            interval * 2,
            interval * 3,
            interval * 4,
            interval * 5,
            interval * 6,
            ~~max,
          ];
        },
}           
```
