### ISSUE TITLE
🧐[问题] Typescript Mix chart legend

### ISSUE THREAD

**Issue by donghoon-song** [ant-design/ant-design-charts#1325]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
I am using Typescript.
I am using Mix chart with column, line plots. I want to add legend to the chart but I can't find the way.
It says legend should be Record<string, Legend> type but I can't find what to write as key. Can you help?
<img width="404" alt="image" src="https://user-images.githubusercontent.com/32301380/168509828-18169e42-bcd1-420c-8707-71ae0b6b218a.png">

```	const config = {
		appendPadding: 8,
		tooltip: {
			shared: true,
		},
		syncViewPadding: true,
		legend: {
			chart: {
				position: 'top-left' as const,
			},
		},
		plots: [
			{
				type: 'column' as const,
				options: {
					data: [
						{
							date: '2021-01',
							value: 370,
						},
						{
							date: '2021-02',
							value: 520,
						},
						{
							date: '2021-03',
							value: 580,
						},
						{
							date: '2021-04',
							value: 500,
						},
						{
							date: '2021-05',
							value: 320,
						},
						{
							date: '2021-06',
							value: 420,
						},
						{
							date: '2021-07',
							value: 520,
						},
						{
							date: '2021-08',
							value: 410,
						},
					],
					xField: 'date',
					yField: 'value',
					meta: {
						date: {
							sync: true,
						},
					},
					color: '#2A7DE1',
				},
			},
			{
				type: 'line' as const,
				options: {
					data: averageData,
					xField: 'date',
					yField: 'value',
					meta: {
						date: {
							sync: true,
						},
					},
					color: '#F3A77E',
				},
			},
		],
	};
```
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
"@ant-design/charts": "^1.3.6"

**Comment by donghoon-song** [comment]
@lxfu1 sorry for tagging but its been a month since it has opened. Can you help?

**Comment by lxfu1** [comment]
```ts
legend: {
  [xFiled]:  {}, // eg: date: {}  
}
```

**Comment by yaoqicaicaicai** [comment]
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Mix } from '@ant-design/plots';

const DemoMix = () => {
  const averageData = [
    {
      date: '2015-02',
      value: 21168,
    },
    {
      date: '2015-08',
      value: 21781,
    },
    {
      date: '2016-01',
      value: 23818,
    },
    {
      date: '2017-02',
      value: 25316,
    },
    {
      date: '2018-01',
      value: 26698,
    },
    {
      date: '2018-08',
      value: 27890,
    },
  ];
  const config = {
    legend:{
      position:'top',
      date:{position:'top'}
    },
    appendPadding: 20,
    tooltip: {
      shared: true,
    },
    syncViewPadding: true,
    plots: [
      {
        
        type: 'column',
        options: {
          legend:{
      date:{position:'top'}
    },
          region: { start: { x: 0, y: 0 }, end: { x: 0.48, y: 1 } },
          data: [
            {
              date: '2015-02',
              value: 160,
            },
            {
              date: '2015-08',
              value: 245,
            },
            {
              date: '2016-01',
              value: 487,
            },
            {
              date: '2017-02',
              value: 500,
            },
            {
              date: '2018-01',
              value: 503,
            },
            {
              date: '2018-08',
              value: 514,
            },
          ],
          xField: 'date',
          yField: 'value',
          yAxis: {
            type: 'log',
            max: 100000,
          },
          meta: {
            date: {
              sync: true,
            },
            value: {
              alias: '店数(间)',
            },
          },
          label: {
            position: 'middle',
          },
        },
      },
      {
        type: 'line',
        options: {
          data: averageData,
          xField: 'date',
          yField: 'value',
          xAxis: false,
          yAxis: {
            type: 'log',
            max: 100000,
          },
          label: {
            offsetY: -8,
          },
          meta: {
            value: {
              alias: '平均租金(元)',
            },
          },
          color: '#FF6B3B',
          annotations: averageData.map((d) => {
            return {
              type: 'dataMarker',
              position: d,
              point: {
                style: {
                  stroke: '#FF6B3B',
                  lineWidth: 1.5,
                },
              },
            };
          }),
        },
      },
      {
        type: 'line',
        options: {
          data: [
            {
              date: '2015-02',
              value: null,
            },
            {
              date: '2015-08',
              value: 0.029,
            },
            {
              date: '2016-01',
              value: 0.094,
            },
            {
              date: '2017-02',
              value: 0.148,
            },
            {
              date: '2018-01',
              value: 0.055,
            },
            {
              date: '2018-08',
              value: 0.045,
            },
          ],
          xField: 'date',
          yField: 'value',
          xAxis: false,
          yAxis: {
            line: null,
            grid: null,
            position: 'right',
            max: 0.16,
            tickCount: 8,
          },
          meta: {
            date: {
              sync: 'date',
            },
            value: {
              alias: '递增',
              formatter: (v) => `${(v * 100).toFixed(1)}%`,
            },
          },
          smooth: true,
          label: {
            callback: (value) => {
              return {
                offsetY: value === 0.148 ? 36 : value === 0.055 ? 0 : 20,
                style: {
                  fill: '#1AAF8B',
                  fontWeight: 700,
                  stroke: '#fff',
                  lineWidth: 1,
                },
              };
            },
          },
          color: '#1AAF8B',
        },
      },
    ],
  };
  return <Mix {...config} />;
};

ReactDOM.render(<DemoMix />, document.getElementById('container'));

**Comment by lxfu1** [comment]
Legend can only be used in groups or stacks.   https://codesandbox.io/s/vigorous-ardinghelli-1936gp?file=/index.js

**Comment by NARUTOyuyang** [comment]
> Legend can only be used in groups or stacks. https://codesandbox.io/s/vigorous-ardinghelli-1936gp?file=/index.js

3Q，解决了
