### ISSUE TITLE
Pie组件在父组件数据变动重新渲染时数据未更新界面也会刷新🐛[BUG]

### ISSUE THREAD

**Issue by zl59503020** [ant-design/ant-design-charts#1327]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在父组件中更新了某个兄弟组件的参数会导致Pie子组件也重新渲染，但Pie子组件参数没有任何变化也会类似重新加载一次一样的图表会刷新一遍

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx
