### ISSUE TITLE
🐛[BUG]基础折线图无法显示图例legend

### ISSUE THREAD

**Issue by BluesVN** [ant-design/ant-design-charts#1329]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/27759401/168719819-f970c3a4-0f4b-4ece-a3cc-7e74b9e51d1b.png">

如图官方的例子里 

###
`import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Line } from '@ant-design/plots';

const DemoLine = () => {
  const [data, setData] = useState([]);

  useEffect(() => {
    asyncFetch();
  }, []);

  const asyncFetch = () => {
    fetch('https://gw.alipayobjects.com/os/bmw-prod/1d565782-dde4-4bb6-8946-ea6a38ccf184.json')
      .then((response) => response.json())
      .then((json) => setData(json))
      .catch((error) => {
        console.log('fetch data failed', error);
      });
  };
  const config = {
    data,
    padding: 'auto',
    xField: 'Date',
    yField: 'scales',
    legend: {
      title:{text:'hhhh'},
      position: 'top'
    },
    xAxis: {
      // type: 'timeCat',
      tickCount: 5,
    },
  };

  return <Line {...config} />;
};

ReactDOM.render(<DemoLine />, document.getElementById('container'));
`

**Comment by CNFeffery** [comment]
你的数据得支持设置`seriesField`产生多系列折线图例才有意义

**Comment by BluesVN** [comment]
> 

现在的需求就是产品和设计 要在单条线的时候也要显示出来这个图例，做到样式上的统一性。

**Comment by BluesVN** [comment]
> 



现在的需求就是产品和设计 要在单条线的时候也要显示出来这个图例，做到样式上的统一性。

**Comment by BluesVN** [comment]
> 
试了一下没效果啊

**Comment by BluesVN** [comment]
> 

找一个官网例子，在里面添加如下代码：
  legend: {
    position:'top',
    custom: true,
    flipPage: false,
    items: [
      {

        name: "图例一",
        marker: {
          symbol: "square",
          style:{

            fill: "#6395f9"
          },
          clickable: false
        },
      },
      {

        name: "图例二",
        marker: {
          symbol: "circle",
          style:{

            fill: "#f59a23"
          },
          clickable: false
        },
      }
    ]
  },

**Comment by lxfu1** [comment]
> custom: true,
> flipPage: false,

需要是多折线图，单图图例没意义吧。

**Comment by lxfu1** [comment]
目前单一数据不支持图例，可以上层模拟实现一个。

**Comment by gys15232166552** [comment]
组合图表 Mix 的图例怎么添加呢  https://ant-design-charts.antgroup.com/zh/examples/plugin/multi-view/#combo-plot

**Comment by gys15232166552** [comment]
@lxfu1
