### ISSUE TITLE
🐛[BUG]如果在折线图中使用秒,那么数据自动丢失

### ISSUE THREAD

**Issue by BenLampson** [ant-design/ant-design-charts#133]
官网demo即可复现
![image](https://user-images.githubusercontent.com/15414750/88781006-66fbf080-d1be-11ea-9a7f-658018896af4.png)
![image](https://user-images.githubusercontent.com/15414750/88781060-754a0c80-d1be-11ea-9a7f-9e8ba48bc6ba.png)

**Comment by lxfu1** [comment]
用 tooltip - formatter 实现一下

**Comment by BenLampson** [comment]
> 用 tooltip - formatter 实现一下

不晓得您有没有发现,tooltip只是其中一个问题而已.
X轴的名称也没有,
另外经过调试,是从TIME.JS那里就已经凉了.
如果数据内容不包含年月日信息直接提示为非法数据.

另外,formatter是无法处理这个问题的因为回调函数中的文字内容已经省略掉了HH:mm:ss内容
您可以自行测试

**Comment by BenLampson** [comment]
贵库的代码我并不是非常清楚由于没有MAP文件与对应的JS源码,也就只是从控制台报错来解释这个问题,多有纰漏,望谅解.
