### ISSUE TITLE
🐛[BUG]水波图的宽大于高时显示矩形不正确

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design-charts#1333]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
水波图的矩形形状，当宽大于高时，显示不正确
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
```
const DemoLiquid = () => {
  const config = {
    width: 200, 
    height:150,
    padding:0,
    percent: 0.25,
    autoFit: false,
    shape: 'rect',
    outline: {
      border: 1,
      distance: 0,
    },
    wave: {
      length: 80,
    },
  };
  return <Liquid {...config} />;
};
```
上面是宽大于高，结果是下面的形状
![图片](https://user-images.githubusercontent.com/4978379/168965418-0d777a9a-f939-4814-a974-799718ae4f1c.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
希望是正确的宽高形状

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
升级到V2，https://ant-design-charts-next.antgroup.com/zh/examples/statistics/liquid/#liquid-custom-shape
