### ISSUE TITLE
🐛[BUG] Line组件部分数据点的数值未显示

### ISSUE THREAD

**Issue by iambool** [ant-design/ant-design-charts#1335]
### 🐛 bug 描述
折线图没有显示全部数据点的值

### 🏞 期望结果
期望渲染出的折线图每个数据点都能显示对应的数值

### 💻 复现代码
https://stackblitz.com/edit/react-qipn7q?file=index.js

### © 版本信息

- ant-design-charts 版本: 1.0.9
- 浏览器环境: chrome
- 开发环境: mac OS

### 🚑 其他信息
<img width="552" alt="image" src="https://user-images.githubusercontent.com/30134533/169194315-13cc81a2-0ed5-4c72-86e3-3043c68a2d05.png">

**Comment by lxfu1** [comment]
可以重置底层 layout 布局算法
```TS
 label: {
        layout: []
      },
```
