### ISSUE TITLE
🧐[问题] Column 图的 columnStyle 里找不到 groupField 字段

### ISSUE THREAD

**Issue by calimanco** [ant-design/ant-design-charts#1336]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
需求是一个“堆叠分组柱状图”，并且添加圆角。
理论上我需要根据数据的正负判断哪个柱子段需要圆角。
但我在 columnStyle 设置的函数回调参数中不能找的 groupField 设置的值，这样我就无法的在数据源里找到对应的那组数据。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

期望能在回调中拿到那个柱段段完整源数据，不要是被筛选后段结果。

**Comment by lxfu1** [comment]
rawFields: [xx, xx, groupField]

**Comment by calimanco** [comment]
> rawFields

可以了，谢谢。希望补充一下文档，方便后人
