### ISSUE TITLE
🧐[关系图的text有办法设置过长自动省略或者换行吗]

### ISSUE THREAD

**Issue by 480131785** [ant-design/ant-design-charts#1338]
### 🧐 问题描述 
请问，关系图的text有办法设置过长自动省略或者换行吗？

### 🚑 其他信息 
![image](https://user-images.githubusercontent.com/72115444/169475481-b29c2c1f-a5a3-464b-81a2-fa825b29ea9b.png)

**Comment by 480131785** [comment]
或者自适应宽度也可以

**Comment by lxfu1** [comment]
nodeCfg:  {autoWidth:  true}

**Comment by 480131785** [comment]
里面text宽度可以自适应吗？
![image](https://user-images.githubusercontent.com/72115444/169488094-d144599c-c72f-4d86-9b83-58d378751ff5.png)

**Comment by lxfu1** [comment]
这个看上是bug了，近期修复
