### ISSUE TITLE
🐛[BUG]柱线混合图表的tooltips内容不能进行定制

### ISSUE THREAD

**Issue by 863183638** [ant-design/ant-design-charts#134]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
柱线混合图表的tooltips内容不能进行定制

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

https://codesandbox.io/s/rough-bird-y1d85?file=/demo.tsx

**Comment by lxfu1** [comment]
update，g2plot 已经发布新版本1.1.23 。
