### ISSUE TITLE
🧐[问题]堆叠分组柱状图如何只显示一个柱的 Tooltip

### ISSUE THREAD

**Issue by calimanco** [ant-design/ant-design-charts#1340]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

需求就是在一个“堆叠分组柱状图”上鼠标移入只显示当前柱的 Tooltip 信息。
按照已有的示例，只能获取到的是整组的 Tooltip 信息。
如果将 Tooltip 组件的 shared 改为 false，获取到的是一个柱段段信息，并不是整个柱。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

希望能获取到一个柱子的信息。

**Comment by lxfu1** [comment]
目前不支持怎么做，可用使用 tooltip.customContent 结合鼠标事件实现，比较复杂。

**Comment by lxfu1** [comment]
```ts
tooltip: { shared: false }
```
