### ISSUE TITLE
🐛[BUG]关系图的graph.zoom()不生效？

### ISSUE THREAD

**Issue by 480131785** [ant-design/ant-design-charts#1344]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
给关系图设置了 graph.zoom 但是貌似不生效？
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
```
return <FlowAnalysisGraph
    onReady={(graph)=>{
        graph.zoom(0.5)
    }}
    {...config} 
   />;
```

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
```ts
 setTimeout(()=>{
      graph.zoom(0.5)
    })
```

**Comment by 480131785** [comment]
这里由于数据量不同，渲染出的初始大小也不同 ，统一采用相同的百分比缩放可能效果并不理想，有什么办法让节点初始渲染保持同等大小吗？

**Comment by lxfu1** [comment]
`autoFit: false`
