### ISSUE TITLE
🐛[BUG]x轴grid间距不一致

### ISSUE THREAD

**Issue by yuruwang** [ant-design/ant-design-charts#135]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
数据正常的情况下，x轴的grid间距不一致

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
online Demo: https://codesandbox.io/s/purple-sunset-j2i4m

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
0.9.7

- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/31492974/88921217-bc103300-d2a0-11ea-89d1-e5213dfc06b6.png)

**Comment by lxfu1** [comment]
这个是正常的  内部算法会对刻度进行优化  如果一定要等分 可以加上 
yAxis: {
      tickCount: 6
}
