### ISSUE TITLE
👑 [需求]  如何屏蔽自带的点击legend-item 显隐这一条数据的方法？

### ISSUE THREAD

**Issue by gongxinle** [ant-design/ant-design-charts#1350]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
目前有个需求是点击legend-item 去显示一个详情弹窗 监听了click事件 但是无法屏蔽掉自带的选中效果，能屏蔽掉么？

**Comment by visiky** [comment]
interactions: [{ type: 'legend-filter', enable: false  }]

**Comment by gongxinle** [comment]
谢谢！
