### ISSUE TITLE
🧐[问题] Flowchart 无法触发onSave，我通过官网案例，无法触发onSave

### ISSUE THREAD

**Issue by lgh-qt** [ant-design/ant-design-charts#1352]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
无法通过点击触发onSave
![image](https://user-images.githubusercontent.com/33716733/170903286-eb68b226-c59a-4ac9-9e1a-73a85646b559.png)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

![image](https://user-images.githubusercontent.com/33716733/170903349-6390a82d-f40a-4172-9d63-7bca609eeee3.png)

**Comment by lxfu1** [comment]
官网示例有点问题，保存按钮被上层容器给遮挡了，配置一下样式。
```tsx
  scaleToolbarPanelProps={{
          layout: 'horizontal',
          position: {
            right: 0,
            top: -40,
          },
          style: {
            background: 'transparent',
             left: 'auto', // 这里
          },
        }}
```
