### ISSUE TITLE
👑 [需求]来源去向图，items是否也能够支持autoEllipsis 超出自动隐藏？

### ISSUE THREAD

**Issue by hanchenxu** [ant-design/ant-design-charts#1353]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
![image](https://user-images.githubusercontent.com/36257490/170933447-2f719160-5888-4b13-aee6-3ba15caf330f.png)

**Comment by lxfu1** [comment]
items 不支持，可以考虑使用 customContent
