### ISSUE TITLE
🧐[问题] 如何不刷新动态改变legend-item的颜色

### ISSUE THREAD

**Issue by aphen** [ant-design/ant-design-charts#1356]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
饼状图，每一项改变，legend对应item的颜色跟随改变，目前能实现的是每次要render，饼状图也会重新渲染
如何不刷新，更改对应legend颜色？如饼状图的setState('selected')，设置完后直接改变，无刷新
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
更改了官方的demo,可在官方例子中直接运行
`import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Pie, measureTextWidth } from '@ant-design/plots';

const DemoPie = () => {
  function renderStatistic(containerWidth, text, style) {
    const { width: textWidth, height: textHeight } = measureTextWidth(text, style);
    const R = containerWidth / 2; // r^2 = (w / 2)^2 + (h - offsetY)^2

    let scale = 1;

    if (containerWidth < textWidth) {
      scale = Math.min(Math.sqrt(Math.abs(Math.pow(R, 2) / (Math.pow(textWidth / 2, 2) + Math.pow(textHeight, 2)))), 1);
    }

    const textStyleStr = `width:${containerWidth}px;`;
    return `<div style="${textStyleStr};font-size:${scale}em;line-height:${scale < 1 ? 1 : 'inherit'};">${text}</div>`;
  }

  const data = [
    {
      type: '分类一',
      value: 27,
    },
    {
      type: '分类二',
      value: 25,
    },
    {
      type: '分类三',
      value: 18,
    },
    {
      type: '分类四',
      value: 15,
    },
    {
      type: '分类五',
      value: 10,
    },
    {
      type: '其他',
      value: 5,
    },
  ];
  const config = {
    appendPadding: 10,
    data,
    angleField: 'value',
    colorField: 'type',
    radius: 1,
    innerRadius: 0.64,
    meta: {
      value: {
        formatter: (v) => `${v} ¥`,
      },
    },
    label: {
      type: 'inner',
      offset: '-50%',
      style: {
        textAlign: 'center',
      },
      autoRotate: false,
      content: '{value}',
    },
    statistic: {
      title: {
        offsetY: -4,
        customHtml: (container, view, datum) => {
          const { width, height } = container.getBoundingClientRect();
          const d = Math.sqrt(Math.pow(width / 2, 2) + Math.pow(height / 2, 2));
          const text = datum ? datum.type : '总计';
          return renderStatistic(d, text, {
            fontSize: 28,
          });
        },
      },
      content: {
        offsetY: 4,
        style: {
          fontSize: '32px',
        },
        customHtml: (container, view, datum, data) => {
          const { width } = container.getBoundingClientRect();
          const text = datum ? `¥ ${datum.value}` : `¥ ${data.reduce((r, d) => r + d.value, 0)}`;
          return renderStatistic(width, text, {
            fontSize: 32,
          });
        },
      },
    },
    // 添加 中心统计文本 交互
    interactions: [
      {
        type: 'element-selected',
      },
      {
        type: 'element-active',
      },
      {
        type: 'pie-statistic-active',
      },
    ],
  };
  let interId;
  return <Pie {...config} onReady={ (piePlot)=>{
    
      let obj = {
        1: '分类一',
        2: '分类二',
        3: '分类三',
        4: '分类四',
        5: '分类五',
        6: '其他',
      }
      let index = 1;
      clearInterval(interId)
      interId = setInterval(()=>{
       piePlot.setState('selected', (data) => {

        
          if(data.type === obj[index] ) return true;
        }, true);
        piePlot.setState('selected', (data) => {

        
          if(data.type !== obj[index] ) return true;
        }, false);
       

        piePlot.chart.legend({
        position: 'right',
        itemName: {
          style: (item, i)=>{
          
            if(item.name===obj[index]){
              return {
                fill: '#f00'
              }
            }
          }
        },      
      })
        
      piePlot.chart.render()
        index++;
        if(index > 6) index = 1
      }, 6000)
       
    }} />;
};

ReactDOM.render(<DemoPie />, document.getElementById('container'));`
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
实现的效果
![企业微信截图_16539892017964](https://user-images.githubusercontent.com/8229846/171141835-ef528610-144e-47a3-b22c-50cf312e0928.png)

**Comment by aphen** [comment]
可以支持吗

**Comment by lxfu1** [comment]
可以使用自定义 legend  https://codesandbox.io/s/funny-kowalevski-z2kymb?file=/index.js
