### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by aayushave** [ant-design/ant-design-charts#1359]
你好，
我正在使用甜甜圈图，
我想使用渐变来改变颜色。
我该怎么做？

![image](https://user-images.githubusercontent.com/31796139/172161935-ad1a90fc-8582-46ea-b6e4-7e7676616728.png)

**Comment by lxfu1** [comment]
color: ['l(0) 0:#ffffff 1:#1890ff',  xx, xx],
