### ISSUE TITLE
🐛[BUG] Adding seriesField to Area Chart removes upper border

### ISSUE THREAD

**Issue by ilprincipecolo** [ant-design/ant-design-charts#1360]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Area Chart: adding the field `seriesField` it removes the area border from all shapes. 
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
Try to add a `seriesField` to an existing Area with more annotations inside it.
### 🏞 期望结果 [描述你原本期望看到的结果]
<img width="1196" alt="Screenshot 2022-06-07 at 17 00 25" src="https://user-images.githubusercontent.com/44315806/172414602-4252aaa4-d8e5-4a31-89a2-7fffb5e59eb5.png">

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

Adding the property `seriesField` to the Area chart will provide the following result:

<img width="1189" alt="Screenshot 2022-06-07 at 17 00 08" src="https://user-images.githubusercontent.com/44315806/172415271-a4b196f5-937c-4639-bd3e-f501c025e0d6.png">

### © 版本信息

- ant-design-charts 版本: 1.3.6
- 浏览器环境: Chrome browser
- 开发环境: macOS

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

I had to add the property because my custom legend wasn't showed correctly.

**Comment by lxfu1** [comment]
line: false
