### ISSUE TITLE
smooth自定义平滑度

### ISSUE THREAD

**Issue by EmbraceAn** [ant-design/ant-design-charts#1361]
回台返回的数据太多，并且密集，需求中不能添加滚动条，如何自定义平滑度？
![image](https://user-images.githubusercontent.com/61671389/172815656-5a41a442-37db-4ced-b2f4-afb993fcf638.png)

**Comment by lxfu1** [comment]
目前只支持 boolean 类型

**Comment by EmbraceAn** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by EmbraceAn** [comment]
> 当前只支持 boolean 类型

有方法来解决这个平滑度的问题麻？

**Comment by CNFeffery** [comment]
你这个数据太密集了，保证数据点不失真的前提下是没办法获得很高的平滑程度的

**Comment by lxfu1** [comment]
最新版本支持自定shape，可以参考 https://g2.antv.antgroup.com/examples/interesting/interesting/#25d-column
