### ISSUE TITLE
中国省份地图涉及到收费吗？

### ISSUE THREAD

**Issue by nuonuonuonuoyan** [ant-design/ant-design-charts#1365]
我在项目中用到了 ***https://charts.ant.design/zh/examples/map-area/division#chinese-provinces*** 这个中国省份的地图，看了下地图的底图是mapbox，请问这个会涉及到收费吗？

**Comment by CNFeffery** [comment]
你发的例子链接没有用到在线底图啊，只用到geojson的数据

**Comment by lxfu1** [comment]
在官网申请相关 Key 就好，免费的。
