### ISSUE TITLE
🧐 Add formatting to Slider below AreaChart

### ISSUE THREAD

**Issue by ilprincipecolo** [ant-design/ant-design-charts#1366]
### 🧐 问题描述
How to format date on the Slider chart added from the property `slider` on the Area Chart above to `YYYY-MM-DD`.
### 💻 示例代码 
```
 <Area
        seriesField={props.seriesField}
        ref={ref}
        data={props.data}
        padding="auto"
        slider={{
                start: 0.1,
                end: 0.9,
                trendCfg: {
                  isArea: true,
                }}
        }
        {...config}
      />
```
### 🚑 其他信息
<img width="371" alt="image" src="https://user-images.githubusercontent.com/44315806/173796574-300d2fad-1d45-4b88-afdb-178982bfef92.png">

**Comment by ilprincipecolo** [comment]
> slider.formatter

I tried to set the slider property like that, but still doesn't work:
```
 {
                start: 0.1,
                end: 0.9,
                formatter: (val, datanum, idx) => {
                  return "Hello";
                },
                trendCfg: {
                  isArea: true,
                },
 }
```

**Comment by lxfu1** [comment]
![image](https://user-images.githubusercontent.com/31396322/173799099-c3d2a415-00db-4142-bfeb-34b387ed7001.png)

**Comment by ilprincipecolo** [comment]
> ![image](https://user-images.githubusercontent.com/31396322/173799099-c3d2a415-00db-4142-bfeb-34b387ed7001.png)

Ops, worked now after removing values from the funct. Thank you!! 
Very appreciated, you're the MAN !
