### ISSUE TITLE
父元素设置zoom或transform都会导致图表组件坐标错乱🐛[BUG]

### ISSUE THREAD

**Issue by spring-xql** [ant-design/ant-design-charts#1368]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
公司项目需要整体缩放：
<img width="245" alt="image" src="https://user-images.githubusercontent.com/59687677/174037274-527ff005-89f6-466f-94b4-879d6e6e422a.png">

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/59687677/174036961-22cb5130-4e66-4a50-8dc5-a99a7b344f57.png)
### 🏞 期望结果 [描述你原本期望看到的结果]
把图表坐标正常就好了，图表不缩放也行。希望遇到这个问题的朋友能给出解决方案。
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
给父元素/祖元素设置zoom或transform: scale(.80)
body{
   zoom:.80;
}
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境[版本 101.0.4951.54（正式版本） (arm64)]
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
supportCSSTransform: true

**Comment by WenDaaa** [comment]
@lxfu1 
大佬我也是在body上加了zoom:0.8 导致错位。
supportCSSTransform: true这个属性
使用前：鼠标跟实际的point差的很大 ，
使用后：只有在x为零的时候 是正常的 ，鼠标往后移动还是有偏移量，越后面坐标位置的偏移越大这个是什么原因
