### ISSUE TITLE
🧐 Move the first line tick to the right

### ISSUE THREAD

**Issue by ilprincipecolo** [ant-design/ant-design-charts#1369]
### 🧐 问题描述
How to move the first line tick to the right or show it in the center.
### 💻 示例代码 
```
 <Area
        seriesField={props.seriesField}
        ref={ref}
        data={props.data}
        padding="auto"
        slider={{
                start: 0.1,
                end: 0.9,
                trendCfg: {
                  isArea: true,
                }}
        }
        {...config}
      />
```
Current state:

<img width="318" alt="image (2)" src="https://user-images.githubusercontent.com/44315806/174077194-4c7ddedc-b89c-497b-805f-b2e71e2d65df.png">

### 🚑 其他信息
Expected result:
<img width="374" alt="image (1)" src="https://user-images.githubusercontent.com/44315806/174077488-a0e5f135-d3b1-4b5d-8fe7-e05e25b559c9.png">

**Comment by lxfu1** [comment]
This is automatically generated and can be controlled using formatter，
```ts
 xAxis: {
      label: {
        autoHide:false,
        formatter: ()=>{
          return ''
        }
      }
    },
```
