### ISSUE TITLE
👑 [需求]支持自定义图表错误信息的展示

### ISSUE THREAD

**Issue by yuruwang** [ant-design/ant-design-charts#137]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
业务上需要能够支持自定义的图表错误样式，同时仍需要拿到底层具体的错误信息。

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
建议提供一个配置项，比如errorContent，这个配置项接收一个函数，其入参是具体的错误信息，函数返回的react node或者string渲染到图表上

**Comment by lxfu1** [comment]
1.0 版本， https://charts.ant.design/guide/common
