### ISSUE TITLE
🧐[Unable to remove ":" in tooltip label]

### ISSUE THREAD

**Issue by uchihamalolan** [ant-design/ant-design-charts#1370]
### 🧐 问题描述
- There's a `:` in tooltip which I would wish not to have.
- this `:` exists outside of any controllable entity in tooltip (i.e `name`, `value` & `marker`)
- It would be 

### 💻 示例代码
```ts
  tooltip: {
    formatter: (datum) => {
      if (!isNaN(datum.dso)) {
        return { name: '', value: `${Math.floor(datum.dso)} Days` };
      }
      const value = formatAmountLong(datum.amount);

      return { name: '', value };
    },
    customItems: (originalItems) => {
      return originalItems.map((item) => ({
        ...item,
        name: '',
      }));
    },
  },
```

Result:
![image](https://user-images.githubusercontent.com/24520586/174090012-37328f13-ae0c-4e91-b6e0-d9d517f39dce.png)

HTML Element:
```html
<li class="g2-tooltip-list-item" data-index="" style="list-style-type: none; padding: 0px; margin: 12px 0px;">
  <span class="g2-tooltip-marker" style="background: rgb(91, 143, 249); width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
  <span class="g2-tooltip-name"></span>:
  <span class="g2-tooltip-value" style="display: inline-block; float: right; margin-left: 30px;">$ 243,133,221.18</span>
</li>
```

### 🚑 其他信息 [Possible Solutions]
- Keep `:` under `.g2-tooltip-name` element
- Create a new class to indicate this `.g2-tooltip-separator` or something and it could allow user to use custom separator like `-` instead of `:` if needed or entirely remove it like in my case...

**Comment by lxfu1** [comment]
https://charts.ant.design/zh/docs/api/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip
