### ISSUE TITLE
🧐[问题] 通过rotateY把两个Area拼接在一起怎么对齐

### ISSUE THREAD

**Issue by kjstart** [ant-design/ant-design-charts#1371]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我想通过翻转Y轴把量个Area表拼接在一起. 下图表借用上图表x轴的label. 这样就需要两个图表的宽度尽量一致.
由于两个图表Y轴label的宽度不一样, 导致图表的宽度不一样. 能否固定axis的label的宽度? 我传入style提示无效参数.版本1.3.5

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image](https://user-images.githubusercontent.com/2688027/174228795-330aa68e-d63c-42f1-b661-86f48963a34f.png)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/2688027/174228440-354deb67-cce6-4499-8e6d-501b8721d06f.png)

**Comment by lxfu1** [comment]
配置一下padding: [60, 100]

**Comment by kjstart** [comment]
好用, 谢谢!
