### ISSUE TITLE
🐛[BUG] Label of column charts are being cut out if label position is set to 'top'

### ISSUE THREAD

**Issue by praveen1143-debug** [ant-design/ant-design-charts#1372]
In Column charts, if i set label position as 'top', then for some of the items, the label is not shown if it is near the maximum 'Y' value. Please refer the image below.
<img width="634" alt="image" src="https://user-images.githubusercontent.com/107688169/174298027-da6f7ca6-c73b-4ef5-b5e7-2c05fad57e52.png">

<img width="374" alt="image" src="https://user-images.githubusercontent.com/107688169/174298183-ff857cba-3e13-4dbc-9ee6-88dfa8c12b75.png">

Is there any workaround available to get this resolved? Please help. We have a prod release next week and this defect is a blocker.

**Comment by lxfu1** [comment]
config={ limitInPlot: true }

**Comment by nerdess** [comment]
Actually, this lead me to a solution when studying the docs in depth:
 
 `appendPadding: 10`
 
 fixed it for me!
 
 Found this property here: https://g2plot.antv.vision/en/docs/api/plots/liquid
