### ISSUE TITLE
🧐[问题]请问如何实现x轴分级，支持多级

### ISSUE THREAD

**Issue by SmartNourth** [ant-design/ant-design-charts#1378]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
请问大佬们怎么样实现x轴分级展示呢，如下图那样
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/106938279/174732909-4343c1b5-89c9-4135-93a6-4f33d93a629c.png)

**Comment by lxfu1** [comment]
不支持

**Comment by lxfu1** [comment]
V2, paddingBottom + annotations: [{type: 'text'}]
