### ISSUE TITLE
🧐[问题] 辐射树图怎么去修改文字颜色

### ISSUE THREAD

**Issue by fanmingfei** [ant-design/ant-design-charts#1382]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
https://charts.ant.design/zh/examples/relation-graph/radial-tree-graph#layout
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
按照右侧文档上写的方法没有生效
```
nodeCfg: {
  type: 'diamond',
  label: {
    style: {
      fill: 'red'
    }
  }
},
```

**Comment by lxfu1** [comment]
先用 title ，后续支持一下 label。
```ts
 title: {
        style: {
          fill: 'red',
        },
      },
```
