### ISSUE TITLE
🧐[问题]如何为辐射树图增加尺寸变化

### ISSUE THREAD

**Issue by fanmingfei** [ant-design/ant-design-charts#1383]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
如何实现右侧种带大小区别的
https://echarts.apache.org/examples/zh/editor.html?c=graph-label-overlap

**Comment by lxfu1** [comment]
可以放到 data  里面
![image](https://user-images.githubusercontent.com/31396322/176078586-a5607ef6-7723-4f08-8ada-e1e47b3bcbc1.png)
