### ISSUE TITLE
🧐[问题]如何让柱状图下面的描述文字竖排展示或斜着展示

### ISSUE THREAD

**Issue by fanmingfei** [ant-design/ant-design-charts#1384]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
现在柱状图下面的文字横排展示，如果空间不够会间隔隐藏。
如何实现如下效果？
<img width="658" alt="image" src="https://user-images.githubusercontent.com/4632277/176077187-71ef729e-94cf-49f5-a93f-11bbadf16417.png">

**Comment by lxfu1** [comment]
```ts
label:{
  rotate: Math.PI / 2
},
```

**Comment by lxfu1** [comment]
横坐标的话 xAxis.label.rotate

**Comment by fanmingfei** [comment]
有没有竖着展示的方法。例如
<img width="489" alt="image" src="https://user-images.githubusercontent.com/4632277/176079657-c5bcf6c2-f11e-4002-9bec-2bda3393b694.png">

**Comment by lxfu1** [comment]
```ts
 xAxis: {
      label: {
        rotate: -Math.PI / 2,
        style: {
          textAlign: 'end'
        }
      },
    },
```

**Comment by fanmingfei** [comment]
谢谢
