### ISSUE TITLE
👑 [需求]迷你进度条可以设置圆角

### ISSUE THREAD

**Issue by Richt20** [ant-design/ant-design-charts#1386]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
如下图所示，希望可以设置圆角
<img width="193" alt="image" src="https://user-images.githubusercontent.com/68462838/176146963-823ffa5e-f53e-4b63-9741-56abddfe3a17.png">

**Comment by lxfu1** [comment]
底层实现有点问题，建议先直接用 div !
```ts
 progressStyle: {
      radius:20,
    }
```
@visiky

**Comment by visiky** [comment]
暂时不支持圆角。等后续支持了，再通知
