### ISSUE TITLE
🧐使用ref绑定组件时，getChart方法未找到ts定义

### ISSUE THREAD

**Issue by G-02** [ant-design/ant-design-charts#1388]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
getChart方法怎么ts定义，目前找到了changeData方法，但是并没有外层包的getChart
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
import React from 'react';
import {Bullet } from '@ant-design/charts';

const Demo: React.FC = () => {
  const data = [];
  const config = {};
  const ref = React.useRef();
  React.useEffect(() => {
    console.log(ref.current.getChart().changeData());
  }, []);

  return <Bullet {...config} ref={ref}  />;
};

export default Demo;

**Comment by lxfu1** [comment]
这个是上层类型声明问题；

**Comment by G-02** [comment]
> 


> 这个是上层类型声明问题；
> 
> const ref: any = React.useRef();

后续会补充这个类型的声明么

**Comment by lxfu1** [comment]
还有问题的话，参考这个实现 https://github.com/ant-design/ant-design-charts/blob/master/packages/plots/src/components/bar/index.tsx
