### ISSUE TITLE
Pie饼图点击图例，饼图resize时有bug🧐[问题]

### ISSUE THREAD

**Issue by houkeepmoving** [ant-design/ant-design-charts#1389]
点击图例时，饼图resize时，在饼图上方会闪现出一个饼图，并且是在数据量多时出现的概率很大，基本上必现

饼图配置代码如下图：
![image](https://user-images.githubusercontent.com/29296595/176663768-3a70ae95-7b0c-447d-9855-65dbf09203a2.png)

现象如下图：
![image](https://user-images.githubusercontent.com/29296595/176663252-b7ad65df-fd0b-4515-9ab3-7e48bf9e1b49.png)

**Comment by lxfu1** [comment]
animation: false, 先跳过一下 @visiky

**Comment by lxfu1** [comment]
[V2 已修复](https://ant-design-charts-next.antgroup.com)
