### ISSUE TITLE
文档错误，环图的 statistic.content 接受的类型时 object 而不是 string🐛[BUG]

### ISSUE THREAD

**Issue by Tom9402** [ant-design/ant-design-charts#139]
这是文档
![image](https://user-images.githubusercontent.com/17630802/89246831-8e2f4380-d63e-11ea-87bf-2c6f24cb1af9.png)

这是你们的示例
![image](https://user-images.githubusercontent.com/17630802/89246893-b028c600-d63e-11ea-9316-c9fb2dfd5a77.png)

**Comment by lxfu1** [comment]
666 +1

**Comment by lxfu1** [comment]
欢迎使用最新版本
