### ISSUE TITLE
🐛[BUG]通过pnpm 安装 @ant-design/charts，项目启动时会有一些告警

### ISSUE THREAD

**Issue by Elliott-Hu** [ant-design/ant-design-charts#1390]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
WARNING in ./node_modules/.pnpm/registry.npmmirror.com+@antv+algorithm@0.1.9/node_modules/@antv/algorithm/es/dijkstra.js 112:53-66
"export '__spreadArray' was not found in 'tslib'
 @ ./node_modules/.pnpm/registry.npmmirror.com+@antv+algorithm@0.1.9/node_modules/@antv/algorithm/es/index.js
 @ ./node_modules/.pnpm/registry.npmmirror.com+@antv+g6-core@0.3.3/node_modules/@antv/g6-core/es/graph/graph.js
 @ ./node_modules/.pnpm/registry.npmmirror.com+@antv+g6-core@0.3.3/node_modules/@antv/g6-core/es/index.js
 @ ./node_modules/.pnpm/registry.npmmirror.com+@antv+g6-pc@0.3.3/node_modules/@antv/g6-pc/es/util/index.js
 @ ./node_modules/.pnpm/registry.npmmirror.com+@antv+g6-pc@0.3.3/node_modules/@antv/g6-pc/es/index.js
 @ ./node_modules/.pnpm/registry.npmmirror.com+@antv+g6@4.3.3/node_modules/@antv/g6/es/index.js
 @ ./node_modules/.pnpm/registry.npmmirror.com+@ant-design+graphs@1.1.4_react-dom@16.13.1+react@16.13.1/node_modules/@ant-design/graphs/es/index.js
 @ ./node_modules/.pnpm/registry.npmmirror.com+@ant-design+charts@1.3.6_f702db7307e95eda5bb3544843af5822/node_modules/@ant-design/charts/es/index.js
 @ ./src/local-apps/mp/views/operations/performance/index.tsx
 @ ./src/local-apps/mp/views/operations/router.ts
 @ ./src/local-apps/mp/views sync router\.tsx?$
 @ ./src/local-apps/mp/app-routes.tsx
 @ ./src/local-apps sync app-routes\.tsx?$
 @ ./src/router/routes.tsx
 @ ./src/router/index.tsx
 @ ./src/app.tsx
 @ ./src/main.tsx
 @ multi react-hot-loader/patch ./src/main.tsx webpack-dev-server/client?http://localhost:6789/ webpack/hot/dev-server
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
通过pnpm启动项目
### 🏞 期望结果 [描述你原本期望看到的结果]
内部处理好tslib依赖声明
### © 版本信息

- ant-design-charts 版本: 1.3.6
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/1375
