### ISSUE TITLE
how to display only three blue points on the line?

### ISSUE THREAD

**Issue by flekpy** [ant-design/ant-design-charts#1392]
there are a lot of points on my graph on the x-axis, the task is to limit the number of points, how can I do this?

how to display only three blue points on the line?

![image](https://user-images.githubusercontent.com/91248380/176917093-aa1c70d3-8970-4524-8ea2-41a8352e6dea.png)

Thanks

**Comment by lxfu1** [comment]
```ts
    rawFields: ['key1', 'key2'],
    point: {
      size: (...arg) => {
        console.log(arg);  // key1: value1,  key2: value2
        return  0;
      }
    }
```
