### ISSUE TITLE
交流群500人群 已经满了啊。。🧐[问题]

### ISSUE THREAD

**Issue by hyzx86** [ant-design/ant-design-charts#1394]
![daa8ad31cd7f13ebc767537f2c64695](https://user-images.githubusercontent.com/15613121/177277017-289e6dae-1d45-4a13-bddf-f6a40a2d972c.jpg)

**Comment by lxfu1** [comment]
钉钉搜索这个群： 32183967

**Comment by lxfu1** [comment]
首页二维码已经更新

**Comment by ianzone** [comment]
还有新群吗？都失效了
