### ISSUE TITLE
使用tooltip customContent，里面找不到data为什么呢？👑 [需求]

### ISSUE THREAD

**Issue by hou-bo** [ant-design/ant-design-charts#1395]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1066" alt="a7ab80263a692d7cb388062983a17e9" src="https://user-images.githubusercontent.com/20338636/177282380-fa9718fd-eb40-4311-bac1-e0e4425a6c2c.png">

**Comment by lxfu1** [comment]
?.data 试一下，初始化的时候 items 应该是 []

**Comment by hou-bo** [comment]
> 

大佬牛皮，在哪 请你吃饭
