### ISSUE TITLE
👑 [需求]流程图 如何去除通用节点选项 

### ISSUE THREAD

**Issue by 9527jfLi** [ant-design/ant-design-charts#1396]

**Comment by lxfu1** [comment]
上层 css 样式先隐藏一下，已经有支持配置的版本，还未发布 `.xflow-node-panel-body .ant-collapse-item:first-child {display: none}`

**Comment by lxfu1** [comment]
`nodePanelProps.showOfficial: false`

**Comment by owecbxz** [comment]
能去掉部分通用节点吗？保留部分
