### ISSUE TITLE
👑 [需求]请问：柱状图Y轴的最小刻度值为1该怎么设置？

### ISSUE THREAD

**Issue by zhouchunguang2020** [ant-design/ant-design-charts#1399]

**Comment by lxfu1** [comment]
```ts
    yAxis: {
      min: 1,
      tickInterval: 1
    },
```

**Comment by zhouchunguang2020** [comment]
![1657187424986](https://user-images.githubusercontent.com/68039784/177745518-883d71c6-25af-49f8-a9f9-b93ea02fbe93.png)
如果按照你给出的，坐标轴最小值为1，刻度间隔也是1，不是想要的效果
