### ISSUE TITLE
🐛[BUG]自定义Tooltip会频繁闪烁

### ISSUE THREAD

**Issue by XiaoJiuDYS** [ant-design/ant-design-charts#140]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
这里给的是官方的样例，在图表中移动鼠标的时候，ToolTip明显闪烁（怀疑是多次渲染）
https://charts.ant.design/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip

### 🏞 期望结果 [描述你原本期望看到的结果]
自定义Tooltip在鼠标移动时可以正常显示，不会出现闪烁
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://charts.ant.design/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
G2 的问题 已提PR： https://github.com/antvis/G2/pull/2733

**Comment by XiaoJiuDYS** [comment]
OK，这里更新下的[复现链接](https://codesandbox.io/s/cocky-liskov-egbn2)【原先的链接可能在修复后失效】

**Comment by lxfu1** [comment]
G2 已经发布， update 。

**Comment by goalbased** [comment]
在餅圖遇到一樣的狀況，目前無法提供重現連結，因為在提供的sandbox連結上，將版本升到 ```"@ant-design/charts": "0.9.12",```會報錯。且在 https://charts.ant.design/guide/case#%E5%8F%82%E6%95%B0 的自定义 Tooltip的範例上，閃爍情況還是會發生，並非完全平滑，當然已經比```0.9.10```版本改善許多。

![image](https://user-images.githubusercontent.com/9757794/91386489-ad984580-e865-11ea-8648-6bdca3f47701.png)

**Comment by XiaoJiuDYS** [comment]
# 0.9.12+ 在sanbox 都会有这个问题（invalid left-hand）
在sanbox 现在好像都有这个问题了（面积图，饼图，折线图 已验证 其余图表未验证），版本在0.9.12与0.9.13 会报 `Invalid left-hand` 的错. 0.10-beta 版本则不会报错，但是图表不会被渲染  。
![image](https://user-images.githubusercontent.com/36301924/91387757-83945280-e868-11ea-8d3d-53e4cd93ed2e.png)
# G2-plot 也有这个问题，怀疑是G2-plot导致的
貌似是G2-plot 的问题 在G2-plot的官方例子我也复现了这个问题。G2-plot 有问题的版本是[1.1.24](https://github.com/antvis/G2Plot/releases/tag/1.1.24).

**Comment by XiaoJiuDYS** [comment]
> 在餅圖遇到一樣的狀況，目前無法提供重現連結，因為在提供的sandbox連結上，將版本升到 `"@ant-design/charts": "0.9.12",`會報錯。且在 https://charts.ant.design/guide/case#%E5%8F%82%E6%95%B0 的自定义 Tooltip的範例上，閃爍情況還是會發生，並非完全平滑，當然已經比`0.9.10`版本改善許多。
> 
> ![image](https://user-images.githubusercontent.com/9757794/91386489-ad984580-e865-11ea-8648-6bdca3f47701.png)

# 0.9.12+ 在sanbox 都会有这个问题（invalid left-hand）
在sanbox 现在好像都有这个问题了（面积图，饼图，折线图 已验证 其余图表未验证），版本在0.9.12与0.9.13 会报 `Invalid left-hand` 的错. 0.10-beta 版本则不会报错，但是图表不会被渲染  。
![image](https://user-images.githubusercontent.com/36301924/91387757-83945280-e868-11ea-8d3d-53e4cd93ed2e.png)
# G2-plot 也有这个问题，怀疑是G2-plot导致的
貌似是G2-plot 的问题 在G2-plot的官方例子我也复现了这个问题。G2-plot 有问题的版本是[1.1.24](https://github.com/antvis/G2Plot/releases/tag/1.1.24).
