### ISSUE TITLE
🧐[问题]环图如何触发statistic显示

### ISSUE THREAD

**Issue by Richt20** [ant-design/ant-design-charts#1400]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在环图中，除了hover相应分类可以显示statistic外，自定义图例如何点击Dom触发相应的statistic

**Comment by ai-qing-hai** [comment]
@Richt20  环图 hover 改变 statistic 的原理就是 删除 原先的所有 annotations， 然后 对 config 中的 annotations 和 statistic 分别重新渲染。 当前实现 是否困难，因为内部对 statistic  和 annotations 都做了优化和兼容的处理。      如果能导出 transformStatisticOptions 和 renderStatistic 这两个方法 内部就十分简单 这边尝试导出这两个方法 
![image](https://user-images.githubusercontent.com/65594180/179926812-f3c71979-b230-4507-bf4d-755a5c9325db.png)

**Comment by visiky** [comment]
关于”自定义图例如何点击Dom触发相应的statistic” 这个问题，可以考虑使用自定义交互。

具体实现方案：
1、先看下目前 statistic 交互是如何实现的，内部自定义了一个 pie-statistic 的 interaction，然后会去监听 Element 的触发事件，去执行 pie-statistic 相关的一个交互反馈（action）
<img width="480" alt="image" src="https://user-images.githubusercontent.com/15646325/179936394-6c698a1c-3b12-49f9-9514-62deceefa5b6.png">
2、外部自定义图例的时候，可以调用 plot.chart.emit 去触发事件，然后去触发 pie-statistic 反馈的执行
```ts

registerInteraction('custom-pie-statistic', {
  // 需要外部去触发 customLegendClick 这个事件. plot.chart.emit('customLegendClick', { type: 'customLegendClick', /** 传递其他参数，pie-statistic 交互需要的内容，详细看源码 */ })
  start: [{ trigger: 'customLegendClick', action: 'pie-statistic:change' }],
  // plot 双击，重置 statistics
  end: [{ trigger: 'plot:dblclick', action: 'pie-statistic:reset' }],
});
```

这里举一个例子：https://codesandbox.io/s/custom-interaction-y7fi0c

**Comment by ai-qing-hai** [comment]
@Richt20 
参考以下代码
`import React from 'react';
import ReactDOM from 'react-dom';
import { Pie, measureTextWidth, G2 } from '@ant-design/plots';

const DemoPie = () => {
  function renderStatistic(containerWidth, text, style) {
    const { width: textWidth, height: textHeight } = measureTextWidth(text, style);
    const R = containerWidth / 2; // r^2 = (w / 2)^2 + (h - offsetY)^2

    let scale = 1;

    if (containerWidth < textWidth) {
      scale = Math.min(Math.sqrt(Math.abs(Math.pow(R, 2) / (Math.pow(textWidth / 2, 2) + Math.pow(textHeight, 2)))), 1);
    }

    const textStyleStr = `width:${containerWidth}px;`;
    return `<div style="${textStyleStr};font-size:${scale}em;line-height:${scale < 1 ? 1 : 'inherit'};">${text}</div>`;
  }

  const data = [
    {
      type: '分类一',
      value: 27,
    },
    {
      type: '分类二',
      value: 25,
    },
    {
      type: '分类三',
      value: 18,
    },
    {
      type: '分类四',
      value: 15,
    },
    {
      type: '分类五',
      value: 10,
    },
    {
      type: '其他',
      value: 5,
    },
  ];
  const config = {
    appendPadding: 10,
    data,
    angleField: 'value',
    colorField: 'type',
    radius: 1,
    innerRadius: 0.64,
    meta: {
      value: {
        formatter: (v) => `${v} ¥`,
      },
    },
    label: {
      type: 'inner',
      offset: '-50%',
      style: {
        textAlign: 'center',
      },
      autoRotate: false,
      content: '{value}',
    },
    statistic: {
      title: {
        offsetY: -4,
        customHtml: (container, view, datum) => {
          const { width, height } = container.getBoundingClientRect();
          const d = Math.sqrt(Math.pow(width / 2, 2) + Math.pow(height / 2, 2));
          const text = datum ? datum.type : '总计';
          return renderStatistic(d, text, {
            fontSize: 28,
          });
        },
      },
      content: {
        offsetY: 4,
        style: {
          fontSize: '32px',
        },
        customHtml: (container, view, datum, data) => {
          const { width } = container.getBoundingClientRect();
          const text = datum ? `¥ ${datum.value}` : `¥ ${data.reduce((r, d) => r + d.value, 0)}`;
          return renderStatistic(width, text, {
            fontSize: 32,
          });
        },
      },
    },
    // 添加 中心统计文本 交互
    interactions: [
      {
        type: 'element-selected',
      },
      {
        type: 'element-active',
      },
      {
        type: 'pie-statistic-active',
      },
      {
        type: 'custom-interaction',
      },
    ],
  };

  G2.registerInteraction('custom-interaction', {
    start: [
      {
        trigger: 'customClick',
        action: ['pie-statistic:change'],
        arg: {
          statistic: {
            title: {
              ...config.statistic.title,
              style: { fontWeight: 300, color: '#4B535E', textAlign: 'center', fontSize: '20px', lineHeight: 1 },
            },
            content: {
              ...config.statistic.content,
              style: {
                fontWeight: 'bold',
                color: 'rgba(44,53,66,0.85)',
                textAlign: 'center',
                fontSize: '32px',
                lineHeight: 1,
              },
            },
          },
        }
      }
    ],
    end: [
      {
        trigger: 'mouseleave',
        action: ['reset-button:hide']
      }
    ]
  })

  return <Pie {...config} ref={(e) => {
    setTimeout(() => {
      e.getChart().chart.emit('customClick',
        {
          type: '1',
          data: {
            data: {
              type: '分类一',
              value: 27,
            }
          }
        })
    }, 1000)
  }} />;
};

ReactDOM.render(<DemoPie />, document.getElementById('container'));
`

**Comment by ai-qing-hai** [comment]
@Richt20 
参考以下代码
`
import React from 'react';
import ReactDOM from 'react-dom';
import { Pie, measureTextWidth, G2 } from '@ant-design/plots';

const DemoPie = () => {
  function renderStatistic(containerWidth, text, style) {
    const { width: textWidth, height: textHeight } = measureTextWidth(text, style);
    const R = containerWidth / 2;

    let scale = 1;

    if (containerWidth < textWidth) {
      scale = Math.min(Math.sqrt(Math.abs(Math.pow(R, 2) / (Math.pow(textWidth / 2, 2) + Math.pow(textHeight, 2)))), 1);
    }

    const textStyleStr = `width:${containerWidth}px;`;
    return `<div style="${textStyleStr};font-size:${scale}em;line-height:${scale < 1 ? 1 : 'inherit'};">${text}</div>`;
  }

  const data = [
    {
      type: '分类一',
      value: 27,
    },
    {
      type: '分类二',
      value: 25,
    },
    {
      type: '分类三',
      value: 18,
    },
    {
      type: '分类四',
      value: 15,
    },
    {
      type: '分类五',
      value: 10,
    },
    {
      type: '其他',
      value: 5,
    },
  ];
  const config = {
    appendPadding: 10,
    data,
    angleField: 'value',
    colorField: 'type',
    radius: 1,
    innerRadius: 0.64,
    meta: {
      value: {
        formatter: (v) => `${v} ¥`,
      },
    },
    label: {
      type: 'inner',
      offset: '-50%',
      style: {
        textAlign: 'center',
      },
      autoRotate: false,
      content: '{value}',
    },
    statistic: {
      title: {
        offsetY: -4,
        customHtml: (container, view, datum) => {
          const { width, height } = container.getBoundingClientRect();
          const d = Math.sqrt(Math.pow(width / 2, 2) + Math.pow(height / 2, 2));
          const text = datum ? datum.type : '总计';
          return renderStatistic(d, text, {
            fontSize: 28,
          });
        },
      },
      content: {
        offsetY: 4,
        style: {
          fontSize: '32px',
        },
        customHtml: (container, view, datum, data) => {
          const { width } = container.getBoundingClientRect();
          const text = datum ? `¥ ${datum.value}` : `¥ ${data.reduce((r, d) => r + d.value, 0)}`;
          return renderStatistic(width, text, {
            fontSize: 32,
          });
        },
      },
    },
    // 添加 中心统计文本 交互
    interactions: [
      {
        type: 'element-selected',
      },
      {
        type: 'element-active',
      },
      {
        type: 'pie-statistic-active',
      },
      {
        type: 'custom-interaction',
      },
    ],
  };

  G2.registerInteraction('custom-interaction', {
    start: [
      {
        trigger: 'customClick',
        action: ['pie-statistic:change'],
        arg: {
          statistic: {
            title: {
              ...config.statistic.title,
              style: { fontWeight: 300, color: '#4B535E', textAlign: 'center', fontSize: '20px', lineHeight: 1 },
            },
            content: {
              ...config.statistic.content,
              style: {
                fontWeight: 'bold',
                color: 'rgba(44,53,66,0.85)',
                textAlign: 'center',
                fontSize: '32px',
                lineHeight: 1,
              },
            },
          },
        }
      }
    ],
    end: [
      {
        trigger: 'mouseleave',
        action: ['reset-button:hide']
      }
    ]
  })

  return <Pie {...config} ref={(e) => {
    setTimeout(() => {
      e.getChart().chart.emit('customClick',
        {
          type: '1',
          data: {
            data: {
              type: '分类一',
              value: 27,
            }
          }
        })
    }, 1000)
  }} />;
};

ReactDOM.render(<DemoPie />, document.getElementById('container'));

`

**Comment by Richt20** [comment]
谢谢您的解答，这解决了我的问题
