### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by Cherry860** [ant-design/ant-design-charts#1401]
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]   https://codesandbox.io/s/0yr0cs

- ant-design-charts 版本: [e.g. 0.9.0]  latest
- 浏览器环境 
Chrome 103.0.5060.114（正式版本） （64 位）
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/37651304/177956477-fc000542-7476-4109-9478-3fa091e063af.png)

**Comment by lxfu1** [comment]
`limitInPlot: true`
