### ISSUE TITLE
🧐[问题] Is there a way to obtain the coordinate accuracy of the y-axis of a bar chart?

### ISSUE THREAD

**Issue by Cherry860** [ant-design/ant-design-charts#1402]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]  
 Is there a way to obtain the coordinate accuracy of the y-axis of a bar chart?
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
For example, in this figure, I want to obtain a value ranging from 50000 to 25000. In fact, the value of the Y axis is dynamically generated. How can I determine the distance of each coordinate?
![image](![image](![image](https://user-images.githubusercontent.com/37651304/178173905-11662a1a-6b74-4846-bc4d-39deb7ea892c.png)

**Comment by lxfu1** [comment]
https://charts.ant.design/zh/docs/manual/faq#4%E6%80%8E%E4%B9%88%E8%AE%BE%E7%BD%AE%E6%A8%AA%E8%BD%B4%E4%BB%8E-0-%E5%BC%80%E5%A7%8B

**Comment by Cherry860** [comment]
@lxfu1 
Thank you, but my question is not how the coordinates start from 0, but how to get the difference between the two coordinates.

**Comment by lxfu1** [comment]
```ts
yAxis: {
 tickInterval: 5000
}
```
