### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by 17671881483** [ant-design/ant-design-charts#1403]
### 🐛 扇形图 label 的 type 类型过于草率吧
![image](https://user-images.githubusercontent.com/61647474/178174391-273c4a17-6892-4087-a09b-279c7c66f534.png)
![image](https://user-images.githubusercontent.com/61647474/178174408-62e2a50f-865e-4c57-936f-288da64e3780.png)

**Comment by visiky** [comment]
对于不同图表的 `type` 类型是不一样的，所以使用泛化的类型定义
