### ISSUE TITLE
饼图样式

### ISSUE THREAD

**Issue by 17671881483** [ant-design/ant-design-charts#1404]
请问一下这种样式 label 应该给什么配置
![image](https://user-images.githubusercontent.com/61647474/178180768-8c595893-fc9c-479e-8904-ae6706279aef.png)

**Comment by 17671881483** [comment]
用的 Ant Design Charts

**Comment by lxfu1** [comment]
参考这个和下面一个示例
https://charts.ant.design/zh/examples/pie/basic#spider-label
