### ISSUE TITLE
🧐[问题] max width of y axis

### ISSUE THREAD

**Issue by donghoon-song** [ant-design/ant-design-charts#1407]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Can I set the max width of this part? I get the items on the y axis from the server so they are not fixed. When the length of the item is too long, the chart part get short so it causes poor readability.
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/32301380/178395761-e8489a1c-7eb7-4ee6-ae92-7c53abf06b09.png)

**Comment by lxfu1** [comment]
```ts
    yAxis: {
      label: {
        formatter: (label)=> label.substr(0,6)
      }
    },
```

**Comment by donghoon-song** [comment]
@lxfu1 Thank you but your solution slice the label. I just want to keep the label and add a new line

**Comment by donghoon-song** [comment]
@lxfu1 Is there another way something working like css 'wrap'?
