### ISSUE TITLE
🐛[BUG] 图例点击事件无法禁用

### ISSUE THREAD

**Issue by LzhH5** [ant-design/ant-design-charts#1408]
设置selectedMode: false 或者mode： false无法禁用图例点击事件

**Comment by lxfu1** [comment]
能提供个链接或者帖一下相关代码吗？如果不想要关闭事件的话，可以用items自定义

**Comment by LzhH5** [comment]
![20220712162741](https://user-images.githubusercontent.com/60648379/178450371-51fdbfdd-7a57-441d-acd0-01a61cbf681d.png)
![20220712161657](https://user-images.githubusercontent.com/60648379/178450410-481797c1-932e-4f58-8dc2-4f32f4e9e966.png)
因为图例的点击的事件 会有第一个问题 所以期望通过禁用图例点击事件 解决掉第一个问题 但是通过legend 属性的 selectedMode: false 无法禁用掉图例的点击事件 稍后这边会发送一个codesandbox 想请教下 如果再antd echarts禁用掉图例的点击事件
