### ISSUE TITLE
🧐[问题] 指标拆解图视角丢失问题

### ISSUE THREAD

**Issue by jianzhicangqiong** [ant-design/ant-design-charts#1409]
### 🧐 问题描述

指标拆解图，节点个数较多，并且使用懒加载。在节点展开的过程中，视角会自动调整到某一位置，导致展开的节点丢失视野，请问如何使视角调整到点击的节点呢？

**Comment by lxfu1** [comment]
好问题，近期支持

**Comment by lxfu1** [comment]
参考这个 https://charts.ant.design/zh/examples/relation-graph/decomposition-tree-graph#async-load
