### ISSUE TITLE
设置nodeStateStyles，样式不改变

### ISSUE THREAD

**Issue by JiangMengLei** [ant-design/ant-design-charts#141]

**Comment by lxfu1** [comment]
最好提供一下在线地址 ，方便排查。

**Comment by baizn** [comment]
@JiangMengLei 具体怎么使用的呢 ，nodeStateStyles 是交互状态，设置了以后需要交互后才能看到样式改变，具体可以参考 https://g6.antv.vision/zh/docs/manual/middle/states/state-new
