### ISSUE TITLE
Column chart with scroll bar🧐[问题]

### ISSUE THREAD

**Issue by Anjula1996** [ant-design/ant-design-charts#1410]
What is the proper way to apply a scroll bar to the column chart?
when i applied the props of the document like `scrollBar: {type: "horizontal"}` is display the horizontal scroll bar  but  scrolling into top bottom. 
when i applied the prop `scrollBar: { type: "vertical"}` is display the vertical scroll bar but scrolling into right to left from the graphs
is there a proper way to apply a scroll bar and overflow limit for the column chart in  the antV

**Comment by lxfu1** [comment]
slider ?

**Comment by Anjula1996** [comment]
> slider ?

yes slider can be used but is there a way to fix the length of the slider scroll, slider length is changing according to the number of columns
