### ISSUE TITLE
🐛[BUG] Image annotations do not respect `top` when using regionFilter annotations

### ISSUE THREAD

**Issue by andronikosnedos-temboo** [ant-design/ant-design-charts#1416]
### 🐛 bug 
On a Line chart with an `Image` annotation overlaid on a `regionFilter` annotation, the `top` property of the `image` annotation is not being respected.

In the image below, the image annotation should be on top of the green segment, similar to the blue segment.
<img width="664" alt="image" src="https://user-images.githubusercontent.com/80974677/178540232-42248924-e9db-434c-b3fb-665430f82ba3.png">

I made a small example snippet to aid debugging: https://codesandbox.io/s/sleepy-pond-5lz1d6?file=/index.js

**Comment by andronikosnedos-temboo** [comment]
I wonder if there's additional help that I can provide to diagnose this issue. I would like to know if there are any workarounds or it's a known issue. Any feedback on this is appreciated.

**Comment by lxfu1** [comment]
So let's go around it.
```ts
annotations.push({
  type: "html",
  html: '<img src="https://cdn-icons-png.flaticon.com/512/7958/7958422.png" width="24" height="24" />',
  style: {
    width: noteAnnotationImageWidth,
    height: noteAnnotationImageHeight,
  },
  position: [d.Date, d.scales],
  offsetY: -12,
  offsetX: -12,
  top: true
})
```

**Comment by andronikosnedos-temboo** [comment]
I've realised a snag with annotations of type `html`, interactions of type `annotation:mouseenter` and `annotation:mouseleave` don't seem to work. I've updated the code above https://codesandbox.io/embed/sleepy-pond-5lz1d6?fontsize=14&hidenavigation=1&theme=dark to illustrate the issue, hovering above 
<img width="46" alt="image" src="https://user-images.githubusercontent.com/80974677/180148566-369601f3-ebec-4c5e-9a7a-f77a5b5d2a73.png"> changes the mouse cursor but it doesn't change when hovering on top of `html` annotations.

**Comment by lxfu1** [comment]
type: 'html'， style="cursor: pointer"   @pearmini

**Comment by andronikosnedos-temboo** [comment]
> 

Thanks for the suggestion, unfortunately it doesn't seem like `style` is a supported attributed for annotations of type `html` https://charts.ant.design/en/docs/api/components/annotations#-html-annotation. 

Updating the snippet to this doesn't have any effect:
```
            type: 'html',
            style: {
                cursor: "pointer"
            },
```

**Comment by andronikosnedos-temboo** [comment]
Another issue with annotation of type `html` is that `annotation:click` events don't work. I've updated the snippet above and you can see that console statements get issued when clicking on an annotation of type `image`, while nothing happens when clicking on an annotation of type `html`.

**Comment by andronikosnedos-temboo** [comment]
I've created another bug to capture some additional bugs regarding annotations of type `html` that I've found as I've worked through some of the suggestions in this ticket.

**Comment by blackcid** [comment]
Why is this closed if the bug is still happening?
