### ISSUE TITLE
👑 [需求] Add Suffix "%" to label

### ISSUE THREAD

**Issue by yuenzp** [ant-design/ant-design-charts#1417]
Could ant design's Grouped bullet progress plot chart support suffix to add % to the label. I had tried to add '{percentage}' at the content, but it is not working.

**Comment by lxfu1** [comment]
label: { formatter: (value)=> 'xxx' }

**Comment by yuenzp** [comment]
import { Bullet } from '@ant-design/plots';

const DemoBullet = () => {
  const data = [
    {
      title: 'Availability',
      ranges: [60, 90, 100],
      measures: [65],
      target: null,
    },
    {
      title: 'Performance',
      ranges: [60, 90, 100],
      measures: [50],
      target: null,
    },
    {
      title: 'Quality',
      ranges: [60, 90, 100],
      measures: [100],
      target: null,
    }
  ];

  const config = {
    data,
    measureField: 'measures',
    rangeField: 'ranges',
    targetField: 'target',
    xField: 'title',
    color: {
      range: ['#FFbcb8', '#FFe0b0', '#bfeec8'],
      measure: '#5B8FF9',
      target: '#39a3f4',
    },
    label: {
      measure: {
        position: 'middle',
        style: {
          fill: '#fff',
        },
        formatter:  (text: any) => text.measures + " %"
      }
    },
    xAxis: {
      line: null,
    },
    yAxis: false,
    // 自定义 legend
    legend: {
      custom: true,
      position: 'bottom',
      items: [
        {
          value: '差',
          name: '差',
          marker: {
            symbol: 'square',
            style: {
              fill: '#FFbcb8',
              r: 5,
            },
          },
        },
        {
          value: '良',
          name: '良',
          marker: {
            symbol: 'square',
            style: {
              fill: '#FFe0b0',
              r: 5,
            },
          },
        },
        {
          value: '优',
          name: '优',
          marker: {
            symbol: 'square',
            style: {
              fill: '#bfeec8',
              r: 5,
            },
          },
        },
        {
          value: '实际值',
          name: '实际值',
          marker: {
            symbol: 'square',
            style: {
              fill: '#5B8FF9',
              r: 5,
            },
          },
        },
        {
          value: '目标值',
          name: '目标值',
          marker: {
            symbol: 'line',
            style: {
              stroke: '#39a3f4',
              r: 5,
            },
          },
        },
      ],
    },
  };
  return <Bullet {...config} />;
};

export default DemoBullet;
