### ISSUE TITLE
🐛[BUG] 1.4.0版本的chart.min.js没有导出内容

### ISSUE THREAD

**Issue by mslmsl66** [ant-design/ant-design-charts#1419]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
1.4.0版本打包完的 charts.min.js，导入组件后是 undefined

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
`import { Line } from '@ant-design/charts/dist/charts.min.js';

console.log(Line, 11111111);`
### 🏞 期望结果 [描述你原本期望看到的结果]
能够正常使用
### © 版本信息

- ant-design-charts 版本: 1.4.0
- 浏览器环境: Chrome  v103.0.5060.114
- 开发环境: mac OS

**Comment by lxfu1** [comment]
1.4.1
