### ISSUE TITLE
legend如何显示完整文本内容不要限制宽度

### ISSUE THREAD

**Issue by yanglibai** [ant-design/ant-design-charts#142]
现在图例文本超过一定长度就会变成省略号看不到完整内容

**Comment by Rencs** [comment]
> 现在图例文本超过一定长度就会变成省略号看不到完整内容

遇到同样的问题

**Comment by lxfu1** [comment]
内部做了判断 legend 占比是有限制的 我们考虑下要不要去掉

**Comment by A0150315** [comment]
> 内部做了判断 legend 占比是有限制的 我们考虑下要不要去掉

请问现在更新之后有相关属性控制不显示省略号自动撑开吗，原来的版本不会有这个问题

**Comment by ClenLu** [comment]
> 内部做好判断legend占比是有限制的我们考虑下要不要去掉

同样的问题  @lxfu1

**Comment by juxiaowei** [comment]
同样的问题 @lxfu1  什么时候解决

**Comment by bizhigang** [comment]
@lxfu1 还没去掉吗？？？

**Comment by lxfu1** [comment]
升级 1.0 。
```ts
 legend: {
      maxItemWidth: 1000
  },
```
