### ISSUE TITLE
👑 关系图的来源去向图edge支持虚线吗？

### ISSUE THREAD

**Issue by 480131785** [ant-design/ant-design-charts#1421]
### 🥰 需求描述
关系图中的来源去向图，edge是否能支持虚线线条。我看光放API关于edge的配置只有下面这些
![image](https://user-images.githubusercontent.com/72115444/178885373-637fe9ab-497d-4a72-a159-25c9db69f13d.png)

**Comment by lxfu1** [comment]
edgeCfg.style.lineDash: [2, 6]

**Comment by 480131785** [comment]
配置以后，边就不支持 cubic-horizontal 了，有办法解决吗
