### ISSUE TITLE
🧐Why aren't charts rendered in production @Next.JS

### ISSUE THREAD

**Issue by ItsCoding** [ant-design/ant-design-charts#1426]
### 🚑 Its not due to SSR, I disabled SSR completely in my tests and it didn't change anything. When you try it in Development everything works as Expected!

To simplify this: 

This is how it looks in dev `yarn dev` 
<img width="939" alt="image" src="https://user-images.githubusercontent.com/10713197/179406130-8cb1f649-c6d7-43ca-866c-12ca29a9e0de.png">

And that's how it looks in Production `yarn build && yarn start`

<img width="640" alt="image" src="https://user-images.githubusercontent.com/10713197/179406174-91e8b185-2143-47de-a907-4bac3b84f40f.png">

**Comment by nandubatchu** [comment]
This is happening to me too! 🙈

**Comment by lxfu1** [comment]
`swcMinify: false`
