### ISSUE TITLE
Standalone Slider

### ISSUE THREAD

**Issue by John0x** [ant-design/ant-design-charts#1427]
Hey, is it possible to use the Slider as a standalone component?
Couldn't find anything on it in the docs.

Basically the slider without the line chart, so that I can use it to select a timeframe for other charts, globally.

**Comment by lxfu1** [comment]
@pearmini  @visiky  `@antv/components` ?

**Comment by John0x** [comment]
To elaborate on the use case:
Imagine an admin dashboard with a lot of charts that refer to the same timeframe. Grafana dashboards do this a lot, for example. Instead of having to set the time frame for each chart individually (by having a Slider on each of them), it would be way more ergonomic to just have on Slider on the top of the page which controls the time frame globally for that page.

**Comment by enriqueqs** [comment]
hi @John0x how did you solve your issue? I'm trying to achieve something similar to what you're trying to achieve :)

**Comment by John0x** [comment]
> hi @John0x how did you solve your issue? I'm trying to achieve something similar to what you're trying to achieve :)

Had to switch to a typical date-range selector

**Comment by lxfu1** [comment]
`@antv/gui`
