### ISSUE TITLE
🧐[问题] 下面这两段代码  这样编写右键菜单还是出不来，默认的右键删除功能 倒是可以通过show ： false 去掉，新功能出不来

### ISSUE THREAD

**Issue by 9527jfLi** [ant-design/ant-design-charts#1431]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

interface.d.ts 下 ：

export interface ToolbarPanelProps extends BaseProps {
    commands?: CommandItem[];
    layout?: IToolbarLayout;
    readonly flowchartId?: string;
}
export interface ScaleToolbarPanelProps extends BaseProps {
    layout?: IToolbarLayout;
}
// export declare type ContextMenuPanelProps = Pick<BaseProps, 'show'>;
export  type ContextMenuPanelProps = Pick<BaseProps, 'show'> & {
    /** 是否展示内置功能 */
    showOfficial?: boolean;
    /** 自定义menu */
    submenu?: (cfg: { menuType: MenuType }) => MenuItem[];
  };

----------------------------------------------------------------------------
js文件下：
        contextMenuPanelProps={{
          // menuType === 'node'
          show: false,
          submenu: (cfg) => {
            const { menuType } = cfg;
            if (true) {
              return [{
                id: 'LINK',
                label: 'LINK',
                render: () => {
                  return (
                    <a target="_blank" href="https://charts.ant.design/" style={{ padding: '0 16px' }}>
                      自定义渲染
                    </a>
                  );
                },
              }];
            }
            // return [];
          },
        }}

**Comment by lxfu1** [comment]
确认下版本 @ant-design/flowchart  1.1.7

**Comment by 9527jfLi** [comment]
问题解决了 谢谢您
