### ISSUE TITLE
🧐[问题] How to set the Grouped Bullet Plot Chart's xAxis label font size as a responsive font size?

### ISSUE THREAD

**Issue by yuenzp** [ant-design/ant-design-charts#1432]
How to set the Grouped Bullet Plot Chart's xAxis label font size as a responsive font size?

Currently is a fixed font size.

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
`xAxis: {
    line: null,
    label:{
      style:{
        fill:'black',
        fontWeight: 500,
        fontSize: 15
      }
    },
  },`

**Comment by lxfu1** [comment]
const [fontSize, setFontSize]  = useState(15);

setFontSize(xx);

**Comment by yuenzp** [comment]
`const [fontSize, setFontSize] = useState(15);

window.onresize = ()=> setFontSize(document.body.clientWidth > 550? 15 : document.body.clientWidth * 0.03)

xAxis: { line: null, label:{ style:{ fill:'black', fontWeight: 500, fontSize: fontSize } }, },`

**Comment by yuenzp** [comment]
`const [fontSize, setFontSize] = useState(15);

window.onresize = ()=> setFontSize(document.body.clientWidth > 550? 15 : document.body.clientWidth * 0.03)

xAxis: { line: null, label:{ style:{ fill:'black', fontWeight: 500, fontSize: fontSize } }, },`

**Comment by yuenzp** [comment]
const [fontSize, setFontSize] = useState(15);

window.onresize = ()=> setFontSize(document.body.clientWidth > 550? 15 : document.body.clientWidth * 0.03)

xAxis: { line: null, label:{ style:{ fill:'black', fontWeight: 500, fontSize: fontSize } }, },
