### ISSUE TITLE
👑 [需求]移除图例点击效果

### ISSUE THREAD

**Issue by Pancake-Q** [ant-design/ant-design-charts#1435]
如何禁用图例点击呢？自定义图例点击后灰暗，想要移除点击效果

**Comment by ai-qing-hai** [comment]
interactions: [{ type: 'legend-filter', enable: false }, 
{ type: 'legend-active', enable: false }]
看一下

**Comment by ai-qing-hai** [comment]
@Pancake-Q 
![image](https://user-images.githubusercontent.com/65594180/179707852-1b0783f1-047d-43e3-b615-93a551f3db3c.png)

**Comment by Pancake-Q** [comment]
[https://codesandbox.io/s/nifty-merkle-yeictu?file=/index.js](url) 看一下是这种写发吗？感觉并没有起到作用 @ai-qing-hai

**Comment by Pancake-Q** [comment]
![image](https://user-images.githubusercontent.com/81684567/180125515-8f17418b-218d-4abb-8511-f2c99fb98b9b.png)
不起作用

**Comment by visiky** [comment]
@ai-qing-hai 看下是不是双轴图的问题

**Comment by ai-qing-hai** [comment]
@Pancake-Q  双轴图比较特殊， 是内部自定义的筛选时间， 得去除内部的事件
![image](https://user-images.githubusercontent.com/65594180/180155442-5b0e8c98-5bfe-45e1-b3b3-6b39cad6a203.png)

**Comment by visiky** [comment]
> @Pancake-Q 双轴图比较特殊， 是内部自定义的筛选时间， 得去除内部的事件 ![image](https://user-images.githubusercontent.com/65594180/180155442-5b0e8c98-5bfe-45e1-b3b3-6b39cad6a203.png)

这个处理，在 G2Plot 内部兼容下吧

**Comment by Pancake-Q** [comment]
这个方案有一个小问题是可点击的小手依然存在 @ai-qing-hai

**Comment by ai-qing-hai** [comment]
@Pancake-Q 
![image](https://user-images.githubusercontent.com/65594180/180178078-8fa4d4b8-a104-413a-a5c9-7e8efefd1fb3.png)
