### ISSUE TITLE
👑 [需求] 来源去向图 能不能和指标拆解图一样新增一个异步加载 

### ISSUE THREAD

**Issue by daidaic** [ant-design/ant-design-charts#1437]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
来源去向图 能不能和指标拆解图一样新增一个异步加载 暴露一个getChildren方法

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
指标拆解图的异步示例
https://charts.ant.design/zh/examples/relation-graph/decomposition-tree-graph#async-load

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/pull/1443/files#diff-f33491cf4e435aeb63d833839e32e729d406abfb670ac41ccc21456fd1d9d10c
