### ISSUE TITLE
🐛[BUG] 指标拆解图 fitCenter设置为false 时， 树从头节点重新展开

### ISSUE THREAD

**Issue by oumingliang** [ant-design/ant-design-charts#1441]
### 🐛 bug 描述 

标拆解图 fitCenter设置为false ，异步加载子树时， 整棵树从头节点重新展开

### © 版本信息

-  @ant-design/graphs: "^1.2.1",
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
`@ant-design/graphs` V: 1.2.3

**Comment by oumingliang** [comment]
👍🏻 谢谢
