### ISSUE TITLE
🐛[BUG]yAxis nice 对最小值没有优化

### ISSUE THREAD

**Issue by Dawnwangzi** [ant-design/ant-design-charts#1445]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
yAxis: {
      nice: true
    }
最对最大值有nice效果，最最小值没有作用。

而G2中
plot.chart.scale('value', {
        nice: true,
      });
可以对最小值也有优化，坐标轴不是从0开始

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/20938424/180349009-32c0327d-c68f-46cb-9a65-239a9e67a2bf.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
期望 yAxis: {
      nice: true
    }
对最小值也有优化，坐标轴不是一直是从0开始

### © 版本信息

- ant-design-charts 版本: [1.4.0]
- 浏览器环境 chrome
- 开发环境 [mac OS]

**Comment by lxfu1** [comment]
```ts
yAxis: {
  min: null
},
```
