### ISSUE TITLE
🧐[问题] 分组柱状图的seriesField 去动态更新不会触发视图更新

### ISSUE THREAD

**Issue by Wxw-Gu** [ant-design/ant-design-charts#1451]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

我第一次的data值 没有legend字段，seriesField为空，
更新data值 有legend字段
会更新视图，但不会出现分组的选项，

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

https://codesandbox.io/s/ecstatic-pond-55pil2?file=/index.js

    <>
      {
        useMemo(() => <Column data={data} {...config} seriesField={flag ? 'legend' : ''} />, [data])
      }
    </>

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![bug1](https://user-images.githubusercontent.com/84499436/180694419-e4bc0d8b-3d22-4f79-a226-f47d272c7bbe.png)
![bug2](https://user-images.githubusercontent.com/84499436/180694740-1aaa2e4a-d946-4e33-97ff-16823b2143ab.png)
![bug3](https://user-images.githubusercontent.com/84499436/180694748-65a8ecda-3ffa-43eb-b81e-bdf8ec9efcc0.png)

**Comment by qq969409112** [comment]
第一次的data值为
`[
    {
        "axis": "厨房小电",
        "value": 6998
    },
    {
        "axis": "大家电",
        "value": 69995
    }
]`

第二次的data值为
`[
    {
        "axis": "厨房小电",
        "value": 6998,
        "legend": "204911303113"
    },
    {
        "axis": "大家电",
        "value": 69995,
        "legend": "1172134052236"
    }
]`
> 

分组柱状图 去setData的时候分组不会显示出来 @[lxfu1](https://github.com/lxfu1)

**Comment by lxfu1** [comment]
axis 相同才会分组啊，你数据是 `厨房小电` 和 `大家电` 没法分。

**Comment by qq969409112** [comment]
> 轴是不同的分组啊，你的数据是`厨房小电`和`大家电`不同的。

可能是我描述的不清楚,这个是demo 您方便点下看demo 

https://codesandbox.io/s/ecstatic-pond-55pil2?file=/index.js

**Comment by qq969409112** [comment]
@lxfu1  这个是demo 链接   我刚刚更新了一下
config里的seriesField如果有name则为name 没有则为空，
去setData的时候 上面的分组并不会更新,
https://codesandbox.io/s/ecstatic-pond-55pil2?file=/index.js

**Comment by qq969409112** [comment]
我把代码稍微改了一下, 把Column写了一个key, 每次更新data的时候 就把key+1  现在问题解决了
