### ISSUE TITLE
自定义 Tooltip 触发 React 18  warning 警告

### ISSUE THREAD

**Issue by zeusyaoyao** [ant-design/ant-design-charts#1452]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

react 18 使用 line 组件，自定义 Tooltip 组件，触发 warning

![Screenshot 2022-07-25 at 5 42 25 PM](https://user-images.githubusercontent.com/109730486/180747903-4c18988c-0123-4f88-986d-0b9c7ee26a92.png)
![Screenshot 2022-07-25 at 5 42 11 PM](https://user-images.githubusercontent.com/109730486/180747915-7be2b6d6-1d9d-4638-8b4b-5bfdbe11a0b1.png)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
    "@ant-design/charts": "^1.4.2",

**Comment by lxfu1** [comment]
目前确实有点问题，近期支持下。

**Comment by lxfu1** [comment]
`@ant-design/plots 1.2.0`
