### ISSUE TITLE
🧐[问题]Line的onReady启用时能否关闭Line的重复渲染？

### ISSUE THREAD

**Issue by manstein-lzn** [ant-design/ant-design-charts#1454]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
使用Line的onReady功能时，只要页面中（包括其他组件）有任何改变都会导致Line重新渲染，实际上这些动作没有改变Line的任何内容。有什么办法禁止Line重新渲染吗？

**Comment by lxfu1** [comment]
onReady 属于 Function，底层没法检测配置是否变化，每次都会执行 update ，建议用 memo 控制一下， 参考这个示例  https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx

**Comment by manstein-lzn** [comment]
> onReady 属于 Function，底层没法检测配置是否变化，每次都会执行 update ，建议用 memo 控制一下， 参考这个示例 https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx

好的，谢谢。

**Comment by monologue-web** [comment]
> onReady 属于 Function，底层没法检测配置是否变化，每次都会执行 update ，建议用 memo 控制一下， 参考这个示例 https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx

memo 并没有限制由于onReady所带来的多余的渲染啊

**Comment by lxfu1** [comment]
可以的啊，你试一下那2个按钮的区别

**Comment by monologue-web** [comment]
> 可以的啊，你试一下那2个按钮的区别
确实可以的😂,搭配useCallBack 缓存一下函数引用
