### ISSUE TITLE
flowchart可以自定义边的表单吗

### ISSUE THREAD

**Issue by changyouyi** [ant-design/ant-design-charts#1458]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

自定义边的表单，赋不了值，config为空

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
``
import { EditorPanels, FormWrapper } from '@ant-design/flowchart';
import React from 'react';
import { useEffect, useState } from 'react';
const PREFIX = 'flowchart-editor';
const { InputFiled } = EditorPanels;

const EdgeComponent = (props: any) => {
  const { config, plugin = {} } = props;
  //config 为 {}
  console.log(config);
  const { updateEdge } = plugin;
  const [edgeConfig, setEdgeConfig] = useState({
    ...config,
  });
  const onEdgeConfigChange = (key: string, value: any) => {
    setEdgeConfig({
      ...edgeConfig,
      [key]: value,
    });
    updateEdge({
      [key]: value,
    });
  };
  useEffect(() => {
    setEdgeConfig({
      ...config,
    });
  }, [config]);
  return (
    <div className={`${PREFIX}-panel-body`}>
      <div className={`${PREFIX}-panel-group`}>
        <h5>内容</h5>
        <InputFiled
          label="标题"
          value={edgeConfig.label}
          onChange={(value) => {
            onEdgeConfigChange('label', value);
          }}
        />
      </div>
    </div>
  );
};

const CustomEdgeService = (props: any) => {
  console.log(props);
  return (
    <FormWrapper {...props}>
      {(config, plugin) => <EdgeComponent {...props} plugin={plugin} config={config} />}
    </FormWrapper>
  );
};

export default CustomEdgeService;

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/32160912/180967068-bd4d2c69-d087-401a-8b31-927500fa944c.png)

**Comment by lxfu1** [comment]
可以  参考下这个 https://charts.ant.design/zh/examples/flowchart/basic#custom-form

**Comment by changyouyi** [comment]
需要对FormWrapper 加上 type="edge"

    <FormWrapper {...props} type="edge">
      {(config, plugin) => <EdgeComponent {...props} plugin={plugin} config={config} />}
    </FormWrapper>
