### ISSUE TITLE
🐛[BUG] Fix GeoJSON adapter

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design-charts#1462]
Hi, could you provide an example of using ChoroplethMap component with other countries?
I tried to use the object structure as described [here](https://charts.ant.design/en/docs/map-api/source) and got errors

https://codesandbox.io/s/competent-matsumoto-jspv11?file=/index.js

**Comment by lvisei** [comment]
Please use [Area](https://charts.ant.design/en/docs/map-api/plots/area) plot, ChoroplethMap [source data](https://charts.ant.design/en/docs/map-api/plots/choropleth#code-classlanguage-textoptionscodesource) structure only `json` 

@monolithed

**Comment by monolithed** [comment]
@lvisei, thanks for the answer, but [Area](https://charts.ant.design/en/docs/map-api/plots/area) is completely different type of plot. I need a geo map like https://charts.ant.design/en/examples/map-choropleth/administrative#china-map

I've already tried to use json and also without success:

```js
  const config = {
    parser: { 
      type: "geojson"
    },
    source: {
      data: JSON.stringify(data)
    }
  };
```

It'd be nice if you provided a working example to render a map of Italy using my [example](https://codesandbox.io/s/competent-matsumoto-jspv11?file=/index.js)

**Comment by lvisei** [comment]
Geographic data is integrated ChoroplethMap plot, so just need business data like

```
{
  source: {
    data: [{ countryName: 'china',  value: 200 }],
    joinBy: {
      sourceField: 'countryName',
      geoField: 'name',
    },
  },
}
```

But Choropleth plot no integration of geographic data outside of China, you May need  AreaMap [demo](https://charts.ant.design/en/examples/map-area/division#chinese-provinces)

**Comment by monolithed** [comment]
@lvisei, I have [already tried](https://codesandbox.io/s/intelligent-solomon-iw5jhz?file=/index.js) to use AreaMap and got the same result — I see a map of China (

Anyway thanks for pointing out AreaMap, I didn't know it needed an internet connection to amap.com to display the map. It's pitty, I didn't want to use D3.js again (
I think it's necessary to add a note to the library description about such restrictions.

**Comment by lvisei** [comment]
Choose map type mapbox or map

```jsx
onst Map = () => {
  const config = {
    autoFit: true,
    map: {
      type: "mapbox",
	  // type: "map",
	  // style: 'blank',
      // center: [120.19382669582967, 30.258134],
      // zoom: 3,
    },
    source: {
      parser: {
        type: "geojson"
      },
      data: data
    },
    style: {
      opacity: 1,
      stroke: "rgb(93,112,146)",
      lineWidth: 2,
      lineOpacity: 1
    },
    state: {
      active: true
    }
  };

  return (
    <div style={{ height: 300 }}>
      <AreaMap {...config} />
    </div>
  );
};
```
