### ISSUE TITLE
🧐[项目中使用的antd v3, 但是antd design charts中peerdependencies依赖的v4，只能使用1.2之前的版本吗？]

### ISSUE THREAD

**Issue by bbhu-y** [ant-design/ant-design-charts#1464]
问题如上。
但是项目升级挺麻烦的，还依赖了项目组件库，也是v3。为什么这个要用到peerdependencies中，不自行安装呢

**Comment by zeus-maker** [comment]
npm install @ant-design/plots安装包错：npm ERR! Maximum call stack size exceeded
