### ISSUE TITLE
I need to sort on the Y axis

### ISSUE THREAD

**Issue by shanematte** [ant-design/ant-design-charts#1466]
Hi, I have a lot of data that I want to show as multi-lines. But I need sorting on the y-axis from 0 to max. 

It is not possible to sort the array this way. How can this be done? Thanks

![Снимок экрана 2022-07-28 005819](https://user-images.githubusercontent.com/3002401/181351968-fd33e5ab-96f1-4602-ac92-e0f4e5b9b74d.png)

DATA

`[
  {
    "category": "Клики: instagram",
    "year": "2022-25-07",
    "value": "2"
  },
  {
    "category": "Клики: whatsapp",
    "year": "2022-25-07",
    "value": "3"
  },
  {
    "category": "Просмотры в день",
    "year": "2022-25-07",
    "value": "34"
  },
  {
    "category": "Клики: звонки",
    "year": "2022-25-07",
    "value": "40"
  },
  {
    "category": "Показы в день",
    "year": "2022-25-07",
    "value": "293"
  },
  {
    "category": "Клики: instagram",
    "year": "2022-26-07",
    "value": "3"
  },
  {
    "category": "Клики: whatsapp",
    "year": "2022-26-07",
    "value": "5"
  },
  {
    "category": "Клики: звонки",
    "year": "2022-26-07",
    "value": "22"
  },
  {
    "category": "Показы в день",
    "year": "2022-26-07",
    "value": "90"
  },
  {
    "category": "Просмотры в день",
    "year": "2022-26-07",
    "value": "112"
  },
  {
    "category": "Клики: instagram",
    "year": "2022-27-07",
    "value": "1"
  },
  {
    "category": "Клики: whatsapp",
    "year": "2022-27-07",
    "value": "2"
  },
  {
    "category": "Показы в день",
    "year": "2022-27-07",
    "value": "16"
  },
  {
    "category": "Просмотры в день",
    "year": "2022-27-07",
    "value": "17"
  },
  {
    "category": "Клики: звонки",
    "year": "2022-27-07",
    "value": "24"
  }
]`

**Comment by lxfu1** [comment]
`value` need to be number, ex: `{ "category": "Клики: instagram", "year": "2022-25-07", "value": 2 }`
