### ISSUE TITLE
运行报错🧐[问题]

### ISSUE THREAD

**Issue by hj12hj** [ant-design/ant-design-charts#1467]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
ERROR in ./node_modules/@antv/x6-react-components/es/color-picker/index.js 18:0-41
Module not found: Error: Can't resolve 'antd/es/popover/style/index.css' in '/Users/hejie/WebstormProjects/untitled1/node_modules/@antv/x6-react-components/es/color-picker'

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/52463603/181408716-67aa344a-fa3f-4041-bf28-583ee088cd18.png)

**Comment by hj12hj** [comment]
![image](https://user-images.githubusercontent.com/52463603/181408836-3c4287fa-339b-49a3-99e6-df1ee9050b94.png)
已经install了

**Comment by lxfu1** [comment]
用子包试一下，最后提供个复现。
