### ISSUE TITLE
🐛[BUG] interactions and events don't seem to work with annotations of type `html`

### ISSUE THREAD

**Issue by andronikosnedos-temboo** [ant-design/ant-design-charts#1470]
I've decided to create a separate issue to capture some of the workarounds and suggestions from https://github.com/ant-design/ant-design-charts/issues/1416

As you can see from https://codesandbox.io/embed/sleepy-pond-5lz1d6?fontsize=14&hidenavigation=1&theme=dark, the issue that with annotations of type `html`,
- interactions of type `mouseenter` don't seem to work, in the example above, you can see the cursor **not** changing
- events of type `annotation:click` don't work either, in the example above, no `console.log` is issued 

This is with the latest `@ant-design/charts` 1.4.0

**Comment by ai-qing-hai** [comment]
Image is fine. Mainly of HTML type. HTML is special, and chart events that no longer belong to canvas cannot be monitored. You can add a subset of events by wrapping a

layer.
@andronikosnedos-temboo

**Comment by andronikosnedos-temboo** [comment]
Thanks, your suggested approach makes sense, it would be nice to fix the original issue with the image annotations though.
