### ISSUE TITLE
👑 [需求]地图中把所有的缩放禁用了鼠标样式还是手型，有配置设置吗？或者应该这时候是默认样式？

### ISSUE THREAD

**Issue by bbhu-y** [ant-design/ant-design-charts#1471]
![image](https://user-images.githubusercontent.com/38289190/181719047-cdd47012-ca48-4249-84e1-888c26bb3314.png)

缩放配置都禁用了。
地图上的手型截图不出来，可以看下。

**Comment by bbhu-y** [comment]
地图不支持缩放，但是鼠标样式是grab手型，真的非常奇怪

**Comment by lvisei** [comment]
@bbhu-y 手型是 dom 容器上面设置都，默认都是手形，修改 dom 上的 CSS 属性

**Comment by bbhu-y** [comment]
![image](https://user-images.githubusercontent.com/38289190/181748318-6dde0a9b-38b3-4cba-b593-72fd58b2c979.png)


并不生效~我试过了

**Comment by lvisei** [comment]
@bbhu-y 容器设置错误，看 css 权重在上一层容器上
