### ISSUE TITLE
🐛[BUG]地图加上tooltip配置后，偶尔会导致页面卡死崩溃

### ISSUE THREAD

**Issue by bbhu-y** [ant-design/ant-design-charts#1472]
bug如题中描述，非必现，刷10次页面大概有1-2次重现，其他情况正常。

配置如下：
![image](https://user-images.githubusercontent.com/38289190/181732091-7f948d09-7bea-4062-993a-4eb7829ce1be.png)

其他信息如下：
![image](https://user-images.githubusercontent.com/38289190/181731968-91973dc5-fbb6-4911-9fb7-aef6ad938c00.png)

![image](https://user-images.githubusercontent.com/38289190/181732156-da9b76fd-5a41-46b7-a9dd-31b95f557122.png)

![image](https://user-images.githubusercontent.com/38289190/181732208-78b08fe3-f17c-49cc-9247-e4a0022b7196.png)

**Comment by bbhu-y** [comment]
去除掉customTitle的配置就好了。但是因为没有customTitle,导致需要使用customContent, 但是也不生效？？？？
这地图不知道是我不会用还是什么的，发现好多问题啊！




![image](https://user-images.githubusercontent.com/38289190/181745924-a7273e6c-3c4d-412e-b177-daed0d96cde5.png)

**Comment by bbhu-y** [comment]
![image](https://user-images.githubusercontent.com/38289190/181747657-48b0d6f4-49fc-4c4b-9b78-4f7e1301db94.png)


customValue也会导致上面的崩溃问题！不加这个就正常显示和使用

**Comment by bbhu-y** [comment]
![image](https://user-images.githubusercontent.com/38289190/181747765-7505b982-5985-428e-af3b-29f71c78d1f4.png)

**Comment by lvisei** [comment]
使用方式有误 [API 文档](https://l7plot.antv.vision/zh/docs/api/components/tooltip#code-classlanguage-texttooltipcodecustomcontent)

![image](https://user-images.githubusercontent.com/26923747/181748327-b1f6b86b-8e07-48a6-bc2f-dc754cde5349.png)
