### ISSUE TITLE
🐛[BUG]地图的legend自定义customContent没用？

### ISSUE THREAD

**Issue by bbhu-y** [ant-design/ant-design-charts#1473]
未配置customContent之前，图例正常显示：
![image](https://user-images.githubusercontent.com/38289190/181735396-fff8eea6-eb9a-46a9-b134-bed97914ca4a.png)

配置customContent之后，图例不见了：
![image](https://user-images.githubusercontent.com/38289190/181735576-f173a0d3-3230-4b93-aac1-f5f681c28b57.png)

**Comment by lvisei** [comment]
使用方式错误，需要返回 html

![image](https://user-images.githubusercontent.com/26923747/181747922-4c6d4409-74f3-4405-85d9-9279134cb133.png)

**Comment by bbhu-y** [comment]
![image](https://user-images.githubusercontent.com/38289190/181748710-61415049-3867-4f14-b109-b76663728feb.png)


返回html也是一样的！~我之前就试过了，贴错图了

**Comment by bbhu-y** [comment]
哦哦，我知道了，要用字符串，不能reactNode, 不好意思。
`<div>aa</div>`就可以了

**Comment by lvisei** [comment]
[Tooltip 怎么使用 JSX ?](https://l7plot.antv.vision/zh/docs/manual/faq#%E5%9C%B0%E5%9B%BE%E7%9B%B8%E5%85%B3)
