### ISSUE TITLE
🐛[BUG] Typing error for Tooltip

### ISSUE THREAD

**Issue by xinghul** [ant-design/ant-design-charts#1474]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
安装了`@ant-design/charts@1.4.2`之后tooltip formatter报错

<img width="1395" alt="Screen Shot 2022-07-29 at 7 02 38 PM" src="https://user-images.githubusercontent.com/6555861/181866171-12d68a71-9875-4d44-b8e0-6e853210f8da.png">

看了下代码之后发现`@antv/g2plot/lib/types/tooltip.d.ts`这一行有问题：
`export declare type Tooltip = false | TooltipOptions;`

应该去掉`false | ` 吧？

### © 版本信息
1.4.2

**Comment by lxfu1** [comment]
Use latest version.
