### ISSUE TITLE
🐛[BUG] color cannot be changed based on value of Column bar

### ISSUE THREAD

**Issue by cfontes** [ant-design/ant-design-charts#1475]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

```
// Function
  const config = {
    data,
    xField: 'type',
    yField: 'value',
    colorField: 'value', 
   color: ({ value }) => {
    if(type === '1'){
      return 'red';
    }
    return 'yellow';
  }
return <Column {...config} />;
}
```

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
Doesn't work with values, only with type (xField)

### © 版本信息

- ant-design-charts 版本: [e.g. 1.4.0]
- Chrome
- Windows

**Comment by ai-qing-hai** [comment]
color 分组， 更何况是按照 数值分组， 你要实现 部分颜色的改变， 可以使用 columnStyle 回调

**Comment by ai-qing-hai** [comment]
@cfontes  看一下 
![image](https://user-images.githubusercontent.com/65594180/182277386-70c0a37a-c474-4a48-a961-feef6c80e824.png)

**Comment by cfontes** [comment]
That is great, thanks.
Couldn't find this in the documentation but will try it out!
