### ISSUE TITLE
自定义主题里可以设置字体颜色吗，只看到fontFamily🧐[问题]

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#1476]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

如题，不知道有没有比较方便的方法可以统一设置图表中各个字体的颜色，`dark`主题下字体还是以前的灰色看起来不明显

**Comment by ai-qing-hai** [comment]
https://juejin.cn/post/7122704459578212382 可以看一下这个 theme 的配置

**Comment by ai-qing-hai** [comment]
@CNFeffery  字体颜色 是 fill 没有统一的配置 https://juejin.cn/post/7122704459578212382 可以看一下这个 theme 的配置
