### ISSUE TITLE
🧐[问题] Can we get an event for slider filter on the bar and line charts?

### ISSUE THREAD

**Issue by cfontes** [ant-design/ant-design-charts#1477]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

Would it be possible to receive an event with the data of the slider when that slider is moved? so we can use it to change other Ant Design components like a table based on it?

**Comment by ai-qing-hai** [comment]
return <Column {...config}
   ref={(e) => {
    setTimeout(() => {
      // 通过 chart.getController('slider') 获取其他图 slider 对象
      // const slider2 = view2.getController('slider');
      // const slider1 = view1.getController('slider');
      e?.getChart().chart.on('slider:valuechanged', (ev) => {
        const { start, end } = ev.gEvent.delegateObject.slider.cfg;
        // slider1.onValueChange([start, end])
        // slider2.onValueChange([start, end])
      })
    })
  }} />; 参考一下哈

**Comment by lxfu1** [comment]
onReady: (plot) => plot.on('slider:valuechanged', callback)

**Comment by lakshmi-udaan** [comment]
> ```ts
> onReady: (plot) => plot.on('slider:valuechanged', callback)
> ```

Follow up question to the above step : https://github.com/ant-design/ant-design-charts/issues/1867
