### ISSUE TITLE
🐛[BUG]自定义Tooltip会频繁闪烁

### ISSUE THREAD

**Issue by zeusyaoyao** [ant-design/ant-design-charts#1478]
### 🐛 自定义Tooltip会频繁闪烁

自定义 tooltip 鼠标放上去一直抖动闪烁，打 log 看一直在重新渲染。

react 18，ant-design-charts 版本: 1.4.2。

![Screenshot 2022-08-02 at 10 29 11 AM](https://user-images.githubusercontent.com/109730486/182278761-41c60cd5-e94b-4a40-9b13-d76c506d4846.png)

![Screenshot 2022-08-02 at 10 29 32 AM](https://user-images.githubusercontent.com/109730486/182278800-cadd6fc0-0209-4bdd-95f6-b99e12299ddc.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

按照使用方式配置，就能复现

### © 版本信息

- ant-design-charts 版本: 1.4.2
- react 版本：18
- 浏览器环境 chrome
- 开发环境 mac Os

**Comment by lxfu1** [comment]
配置 showDelay: 300  试试

**Comment by zeusyaoyao** [comment]
配置 showDelay 会有些卡顿，就不流畅了

**Comment by lxfu1** [comment]
> 配置 showDelay 会有些卡顿，就不流畅了

底层问题，近期发布新版本 @visiky

**Comment by lxfu1** [comment]
删除node_modules重新安装一下。

**Comment by yxiangTang** [comment]
1.4.2还有相同问题啊，8月份提的issue，现在还没修复吗
