### ISSUE TITLE
🧐[问题] Brush 刷选 不支持折线图么

### ISSUE THREAD

**Issue by xuoutput** [ant-design/ant-design-charts#1479]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Brush 刷选 不支持折线图么, 目前只看到 4 种
<img width="163" alt="image" src="https://user-images.githubusercontent.com/16385443/182299608-4d8f5270-55c7-4abe-a43d-187f74dc2763.png">

**Comment by HongwuQz** [comment]
添加如下配置即可
`// 开启 brush 刷选交互
     interactions:[{ type:'brush' }],
    
     // 设置刷选范围的样式
     brushStyle:{
       fill:'#ccc',
       fillOpacity:'0.3'
     }`

**Comment by lxfu1** [comment]
V2, `interaction: { brushFilter: true}`, Double click to reset.
