### ISSUE TITLE
🧐[问题]如何在事件中修改样式

### ISSUE THREAD

**Issue by ybzjsxh** [ant-design/ant-design-charts#148]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
比如我想在donut图里通过events的onRingMouseenter,leave等事件让当前的图形偏移该如何实现呢，类似echarts的环图hover时的那种效果，现在通过onRingMoseenter: v => console.log(v)打印出来的属性不知该修改哪里，还请指导下谢谢🙏

**Comment by lxfu1** [comment]
interactions:[
   {type:'element-single-selected' }
 ],

**Comment by lxfu1** [comment]
修改样式
```ts
plot.setActive(
      (obj) => {
        return obj.type === '分类五';
      },
      {
        fillStyle: 'green',
      }
    );
```
