### ISSUE TITLE
🧐[问题] 环图  type为spider   formatter return null  导致所有的label不展示；

### ISSUE THREAD

**Issue by a1352723557** [ant-design/ant-design-charts#1483]
环图中， label.type = 'spider';  formatter 某一条数据 return null； 导致整个label都不展示

``label: {
      type: 'spider',
      formatter: (data) => {
        if (data.value == 0) return;
        return `${data.percent}%`;
      },
   }``

<img width="239" alt="image" src="https://user-images.githubusercontent.com/41726893/182999210-a50d9b03-8286-4cb4-91dd-c96c73bb6f86.png">
<img width="284" alt="image" src="https://user-images.githubusercontent.com/41726893/182999325-c8b748fc-b7f8-4e3f-a92a-852976bfe8d7.png">

<img width="766" alt="image" src="https://user-images.githubusercontent.com/41726893/182999289-154515cd-e798-4f2d-a983-a621a4ae29cb.png">

**Comment by a1352723557** [comment]
复现地址： https://codesandbox.io/s/kkyqlb

**Comment by lxfu1** [comment]
@visiky

**Comment by yanzi123** [comment]
你试试不设置formater，改成设置label对象的content 呢
const config = {
    label: {
      type: 'spider',
      content: ({ percent }) => `${(percent * 100).toFixed(2)}%`,
    }
}

**Comment by vipin-msec** [comment]
> 你试试不设置formater，改成设置label对象的content 呢 const config = { label: { type: 'spider', content: ({ percent }) => `${(percent * 100).toFixed(2)}%`, } }

hey do you know how to reduse the size of label link line???

**Comment by lxfu1** [comment]
可以返回空` ' '`,
