### ISSUE TITLE
🐛[BUG]双轴图设置slider的start为非0值，折线及tooltip显示异常

### ISSUE THREAD

**Issue by joshchiucn** [ant-design/ant-design-charts#1486]
### 🐛 bug 描述 
使用双轴图时，当设置了slider，并且slider的start 不为0时，折线图没有填满空间，并且当光标悬浮在某个数据点的位置时，tooltip未正常显示。
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
使用官方文档上的双轴线示例 https://charts.ant.design/zh/examples/dual-axes/dual-line#dual-line， 或者下方复现代码。 config 中增加 slider, start设置为 0.7或其他值。
### 🏞 期望结果 [描述你原本期望看到的结果]
折线根据slider start 设置的范围数据，填充图表空间，tooltip跟随光标位置。
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/g50jrj
### © 版本信息

- ant-design-charts 版本: @ant-design/plots 1.2.1
- 浏览器环境 chrome
- 开发环境 mac OS

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/20282988/183287385-3861a27b-24ec-4688-9fc6-ba2c4e881659.png)

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/489
