### ISSUE TITLE
👑 [需求] flowcharts 节点选中时允许直接连线，不需要额外点击空白处

### ISSUE THREAD

**Issue by jx-zyf** [ant-design/ant-design-charts#1487]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

自定义表单节点选中时(图1)可以配置成可连线状态(图二)

<img width="1920" alt="lQLPJxaSGkKKedjNB5rNDwCwjoPxC3E4CY8C8HDV3UAGAA_3840_1946" src="https://user-images.githubusercontent.com/26456842/183327366-a4662ebf-b0d2-40b0-8ae0-316f98f9be47.png">

<img width="1920" alt="lQLPJxaSGkKKefvNB5rNDwCwbFoR66fm-GcC8HDV4AAnAA_3840_1946" src="https://user-images.githubusercontent.com/26456842/183327388-3eb59132-5bb1-41bb-9f2a-187bf8405c42.png">

**Comment by lxfu1** [comment]
删除依赖重新安装一下， canvasProps = {showPortsOnNodeSelected: true}
