### ISSUE TITLE
👑 [需求]辐射树希望能自定义节点icon

### ISSUE THREAD

**Issue by weiman-133** [ant-design/ant-design-charts#1489]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

RadialTreeGraph 辐射树想要自定义节点图片；目前设置nodeCfg发现图片显示不完整

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
自定义之后发现如图所示
![image](https://user-images.githubusercontent.com/86717611/183850189-e981a8cb-f445-4913-8ae7-b0a5770c24c2.png)

**Comment by lxfu1** [comment]
```ts
  const data = {
    id: 'Modeling Methods',
    type: 'image',
    img: 'https://gw.alipayobjects.com/mdn/rms_f8c6a0/afts/img/A*w5uESbSe430AAAAAAAAAAABkARQnAQ',
    children: [],
    value: 'Modeling Methods',
  };
```
