### ISSUE TITLE
🧐[问题]legend的marker symbol返回自定义图片不好用

### ISSUE THREAD

**Issue by deviluncle** [ant-design/ant-design-charts#1492]
**### 🧐 问题描述 [详细地描述问题，让大家都能理解]
**尝试了好几种写法都无法展示图片** 请帮忙看看

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
`marker: {
        symbol:() =>  'https://www.highcharts.com/samples/graphics/sun.png'
      },`

`marker: {
        symbol:() =>  '<img src = "https://www.highcharts.com/samples/graphics/sun.png" width="14px" height="14px">'
      },`

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![laq71vEQUi](https://user-images.githubusercontent.com/29850196/184073494-8181f8bb-8b1e-426c-b257-8a9f0bbbf042.jpg)

**Comment by lxfu1** [comment]
不支持这种用法的，可以在外层用div模拟实现
