### ISSUE TITLE
[问题]可以设置Y坐标标签的宽度吗？

### ISSUE THREAD

**Issue by shaoyh** [ant-design/ant-design-charts#1493]
<img width="596" alt="image" src="https://user-images.githubusercontent.com/1124542/184108930-bdb4df31-930b-48c2-b55c-ff39a2f033e1.png">

目前问题，两个折线竖着排列，时间范围相同，因为y轴标签宽度不一致，导致两个折线的x轴刻度不一样，对比起来不友好，请问有没有办法避免或者解决这个问题？

**Comment by lxfu1** [comment]
设置 padding: [40, 80] 试试
