### ISSUE TITLE
🧐[问题]如何实现多度量的柱状或者条形堆叠图？

### ISSUE THREAD

**Issue by xiazzhNew** [ant-design/ant-design-charts#1497]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
参照文档上没有找到类似的说明。一番搜索后也没有找到类似的例子。
图形的isStack为true，尝试了让yfield设置为数组和设置series为数组都没有看到效果。

**Comment by lxfu1** [comment]
https://charts.ant.design/zh/examples/dual-axes/grouped-stacked-line#stacked-grouped-column-line

**Comment by xiazzhNew** [comment]
> https://charts.ant.design/zh/examples/dual-axes/grouped-stacked-line#stacked-grouped-column-line

感谢快速回复和支持！似乎这个配置还是不能解决问题的，您辛苦看一下附件图片内的PowerBI数据和效果图，如果是这样的多个度量维度，我尝试了一下还是无法实现堆叠，而PowerBI和Tableau都可以实现这样的堆叠。
<img width="956" alt="PowerBI多度量堆叠图" src="https://user-images.githubusercontent.com/81508976/184798065-bda02152-8100-4c9d-b181-5c0b05536c24.png">

**Comment by xiazzhNew** [comment]
大神们有什么解决方案吗？

**Comment by lxfu1** [comment]
需要转换一下数据，类似 type:  '固定工资' ||  'xx' ,然后配置 seriesField: 'type'
