### ISSUE TITLE
🧐[问题] Can you fill a certain box in a box plot with a color?

### ISSUE THREAD

**Issue by alexroginski1** [ant-design/ant-design-charts#1498]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

Is it possible to fill a certain box in a box plot with a color depending on its xField value? 
I can do this with "color", which changes the border color, but not with "fill" in "boxStyle". 

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

Is it possible to fill certain boxes, like the screenshot below, with blue and red?
<img width="541" alt="Screen Shot 2022-08-15 at 10 50 41 AM" src="https://user-images.githubusercontent.com/73569378/184688556-802f8bf4-9ed8-4fde-b346-05db2f84ee71.png">

**Comment by lxfu1** [comment]
```ts
 boxStyle: (arg)=>{
      return {
        stroke: '#545454',
        fill: 'red',
        fillOpacity: 0.3,
      }
    }
```

**Comment by AlexRoginskiLightup** [comment]
Thank you, this worked.
