### ISSUE TITLE
🧐[问题]多层 circle packing示例与参数说明不一致

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#1499]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

在官网[多层 circle packing](https://charts.ant.design/zh/examples/more-plots/circle-packing#nest)的例子中，`colorField`跟`sizeField`所设置的值没在`data`中的字段里出现过，且`color`参数的设置格式也没在参数说明里介绍过

![image](https://user-images.githubusercontent.com/49147660/184820879-32226710-da0b-445c-a323-40715f32ed86.png)

**Comment by lxfu1** [comment]
底层有数据转换，但这种配置确实不应该在上层体现。

**Comment by lxfu1** [comment]
最新版本已经优化
