### ISSUE TITLE
🐛[BUG]chart随父容器进入局部全屏状态再退出后，chart的canvas高度不准了，溢出了父容器一小块

### ISSUE THREAD

**Issue by wangwufan** [ant-design/ant-design-charts#1500]
### 💻 复现代码
`
    import React from 'react';
    import ProCard from '@ant-design/pro-card';
    import FullScreenButton from '../AnalysisElementDesign/components/FullScreenButton';
    import { Area } from '@ant-design/charts';
    
    const TestPage = () => {
      const data = [
        {
          "timePeriod": "2006 Q3",
          "value": 1
        },
        {
          "timePeriod": "2006 Q4",
          "value": 1.08
        },
        {
          "timePeriod": "2007 Q1",
          "value": 1.17
        },
        {
          "timePeriod": "2007 Q2",
          "value": 1.26
        },
        {
          "timePeriod": "2007 Q3",
          "value": 1.34
        }
      ]
      const config = {
        pixelRatio:2,
        xField: 'timePeriod',
        yField: 'value',
        xAxis: {
          range: [0, 1],
        }
      }
      return (
    
        <div style={{ height: 600 ,boxSizing:"border-box"}}>
          <ProCard
            id={"测试"}
            title="标题"
            // headStyle={{flex:"auto"}}
            bodyStyle={{flexGrow:"auto"}}
            style={{ height: "100%", }}
            extra={
              <div>
                <FullScreenButton domId={"测试"} />
              </div>
            }
          >
            {<div style={{ height: "100%" }}><Area data={data} {...config} /></div>}
          </ProCard>
        </div>
      );
    };
    export default TestPage;
`
全屏按钮组件的代码：
`
    import { FullscreenExitOutlined, FullscreenOutlined } from '@ant-design/icons';
    import React from 'react';
    import screenfull from 'screenfull';
    
    function FullScreenButton(props:any) {
      const {domId}=props;
      return (
        <span style={{ marginRight: 10 }} 
          onClick={()=>{
            if(screenfull.isEnabled && domId!==null) {
                const dom = document.getElementById(domId);
                if(dom!==null){
                  screenfull.toggle(dom);
                }
              }
            }// handle.enter
          }>{screenfull.isFullscreen ? <FullscreenExitOutlined /> : <FullscreenOutlined />}
        </span>
      );
    }
    
    export default FullScreenButton;
`

### © 版本信息

- ant-design-charts 版本: [1.4.2]
- 浏览器环境 [chrome 104.0.5112.81,edge最新]
- 开发环境 [Windows 11]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
刚载入页面，全屏前：
![image](https://user-images.githubusercontent.com/12657738/184830965-e2c79a44-d1d7-41a3-9897-c5076bd3d2d9.png)

点击全屏再退出后：
![后](https://user-images.githubusercontent.com/12657738/184831278-2eb1f7ac-cb3f-4c10-8a16-82423fca43b9.png)

**Comment by lxfu1** [comment]
提供一个sandcodebox 在线复现

**Comment by wangwufan** [comment]
这是在线地址：
https://codesandbox.io/s/ji-chu-qia-pian-forked-07zh33



***@***.***
 
发件人： Joel Alan
发送时间： 2022-08-16 19:10
收件人： ant-design/ant-design-charts
抄送： wangwufan; Author
主题： Re: [ant-design/ant-design-charts] [BUG]chart随父容器进入局部全屏状态再退出后，chart的canvas高度不准了，溢出了父容器一小块 (Issue #1500)
提供一个sandcodebox 在线复现

**Comment by wangwufan** [comment]
> 提供一个codesandbox 在线复现

这是在线地址：
https://codesandbox.io/s/ji-chu-qia-pian-forked-07zh33

**Comment by lxfu1** [comment]
flex 引起的，样式覆盖一下。

![image](https://user-images.githubusercontent.com/31396322/185027830-78197bd3-8af2-47bd-ab76-6fe71f3be6c4.png)

![image](https://user-images.githubusercontent.com/31396322/185027858-ef6ea6b2-9fcf-4c2d-ad6f-4e2dd6d7ab79.png)
