### ISSUE TITLE
🧐[问题] 折线图组件引入2.13MB包体积增长

### ISSUE THREAD

**Issue by AlisaBen** [ant-design/ant-design-charts#1503]
### 🧐 问题描述
@antv包可以按需引入吗？

仅引入了Mix组件，但是引入的@antv包体积有2.13MB，这个包体积如何优化呢？

### 💻 示例代码
```
import Mix from '@ant-design/plots/es/components/mix';
```
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/35186333/184885923-c74820c5-0a44-458a-90af-4be68905bd11.png)

**Comment by lxfu1** [comment]
目前因为底层一些依赖不支持按需，体积会大一点，短时间内无法解决，可以试试 CDN 的方式。

**Comment by lxfu1** [comment]
[最新版本已解](https://ant-design-charts-next.antgroup.com)
