### ISSUE TITLE
tooltip,使用formatter不展示内容

### ISSUE THREAD

**Issue by LMLGM** [ant-design/ant-design-charts#1513]
问题1: tooltip,使用formatter不展示内容
![image](https://user-images.githubusercontent.com/58587791/185339822-5243e5ad-6e77-4dfd-9317-e3ad48bfb9e5.png)
![image](https://user-images.githubusercontent.com/58587791/185339849-6cfede27-722d-4713-92bc-bad7fb667c41.png)
![image](https://user-images.githubusercontent.com/58587791/185339967-07582209-eb3a-46a5-99e9-f38317876d07.png)

问题2: 如果data中某条数据value为null，怎么能够默认展示为0

**Comment by lxfu1** [comment]
formatter 用法不对，应该上 {name: xx,value: xxx}，建议使用[自定义 tooltip ](https://charts.ant.design/zh/docs/api/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip)
