### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by Novante** [ant-design/ant-design-charts#1514]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
https://charts.ant.design/zh/examples/relation-graph/radial-tree-graph#layout
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
    nodeCfg: {
      type: 'diamond',
    },
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
Is it possible to change the type or color of different nodes in the same tree?

**Comment by lxfu1** [comment]
Put it in data, and then I'll support callback.

![image](https://user-images.githubusercontent.com/31396322/185530438-850d76fe-85cc-48be-8b87-4d46059c43d4.png)
