### ISSUE TITLE
🧐[问题]怎么让自定义legend的颜色和实际的颜色一致

### ISSUE THREAD

**Issue by newcaptain** [ant-design/ant-design-charts#1516]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我想让条形图的legend的颜色和实际显示的一致，具体需要怎么配置。
目前是可以鼠标移进去，图形会自动高亮，说明应该识别到了（应该？）
但是现在颜色都是蓝色，怎么变成和实际的颜色是一致的？

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
比如官网的示例：
![impicture_20220819_092054](https://user-images.githubusercontent.com/33460651/185522411-20f02998-e6ac-4565-a0bf-b23a18f7b8ef.png)

**Comment by lxfu1** [comment]
marker 可以配置颜色的， `legend.items[xx].marker: {symbol: 'circle', style: {fill: 'red'}}`
