### ISSUE TITLE
🐛[BUG] charts 和 requirejs 冲突

### ISSUE THREAD

**Issue by wangcheng007** [ant-design/ant-design-charts#1517]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
charts 和 requirejs 一起使用 出错，错误原因 @dagrejs/graphlib@2.1.4 导致。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
在入口 html 中加入 requirejs cdn 地址。
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/24378829/185593035-0b735b57-0c26-45d1-b6b8-8fbbaac54589.png">

项目中正常使用，控制台报错
<img width="987" alt="image" src="https://user-images.githubusercontent.com/24378829/185593401-a0f4103e-e223-458c-b392-b6d3a25acf64.png">

### 🏞 期望结果 [描述你原本期望看到的结果]
将 @dagrejs/graphlib@2.1.4 升级至 graphlib@2.1.8。
依赖层级
@ant-design/charts@1.4.2 -> @ant-design/flowchart@1.2.0 -> @antv/layout@0.1.31 -> @dagrejs/graphlib@2.1.4

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
推荐使用子包`@ant-design/plots`,或者在package.json里面配置 resolutions  解决一下
```ts
"resolutions": {
    "@dagrejs/graphlib": "2.1.8",
  }
```
