### ISSUE TITLE
🧐[问题]ChoroplethMap 开启drill时，刷新页面的时候一直又个定时器，直至浏览器奔溃、如何解决呢？

### ISSUE THREAD

**Issue by lyn7568** [ant-design/ant-design-charts#1522]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
ChoroplethMap 开启drill时，刷新页面的时候一直又个定时器，直至浏览器奔溃；去掉dirll就没问题

我想要的效果，点击地图区域获取到所点的code信息，有其他用处；查看文档，均没有试出有效方法，才说使用dirll下钻，拿到需要的数据，需要下钻拦截(实际不需要真正的下钻)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/20807788/185883637-0554f566-3efd-4d62-866d-2d0b3735bea2.png">

**Comment by lvisei** [comment]
不需要下钻就不用开启，获取数据，绑定点击事件

https://l7plot.antv.vision/zh/docs/api/plots/choropleth#%E5%9B%BE%E5%B1%82%E4%BA%8B%E4%BB%B6

**Comment by YahuiAn** [comment]
@lyn7568 这样应该可以

```javascript
const config = {
  onReady: (c) => {
      c.on('fillAreaLayer:click', (event) => {
        const name = event.feature.properties.name
        const level = event.feature.properties.level
        console.log(name, level);
      });
    }
}
```
