### ISSUE TITLE
🧐[问题]行政区域里面中国地图

### ISSUE THREAD

**Issue by UvDream** [ant-design/ant-design-charts#1523]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
行政区域中国地图里面请求了两个json数据
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/33121872/185889229-0aa5b1d0-7483-4b14-b289-4e86ccf36aa8.png">
我现在需要内网部署,这两个数据能弄下来吗,内网不允许请求外部资源

**Comment by YahuiAn** [comment]
@UvDream 请问你最后怎么解决这个问题的？ 🙏

**Comment by UvDream** [comment]
> @UvDream 请问你最后怎么解决这个问题的？ 🙏

https://l7plot.antv.vision/zh/docs/api/plots/choropleth#code-classlanguage-textoptionscodegeoarea
<img width="207" alt="image" src="https://user-images.githubusercontent.com/33121872/186376969-e2e5b4b5-8717-4c9f-b9a8-95b789a9fa4b.png">
这个文件夹下下来放在服务器上,然后配置
```
geoArea: {
    url: '/geo-data/xxxx',
    type: 'topojson',
  },
```
千万注意url是文件夹地址,因为他内部是拼接这个去找这个文件的
