### ISSUE TITLE
未做任何改动，但是编译失败🐛[BUG]

### ISSUE THREAD

**Issue by w22ee** [ant-design/ant-design-charts#1528]
### 💻 复现代码 [
TS2322: Type '{ customItems: (items: any) => any; }' is not assignable to type 'Tooltip'.

 Type '{ showTitle: true; customContent: (title: string, items: any[]) => string; }' is not assignable to type 'Tooltip'.

Type '{ domStyles: { 'g2-tooltip': { width: string; }; }; showTitle: true; enterable: true; showCrosshairs: false; fields: string[]; showMarkers: true; marker: { r: number; fill: string; fillOpacity: number; stroke: string; lineWidth: number; shadowColor: string; shadowBlur: number; }; customContent: (title: string, items...' is not assignable to type 'Tooltip'.

 TS2322: Type '{ customItems: (items: any) => any; }' is not assignable to type 'Tooltip'.
]

### © 版本信息
ant-design/charts 1.4.2
- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
配置提供一下，最近有更新 tooltip 类型， `const config  ={xx} as any` 可以临时跳过。
