### ISSUE TITLE
🧐[问题] Tooltip on line hover

### ISSUE THREAD

**Issue by lajosVlasics** [ant-design/ant-design-charts#1531]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
If I use a Line chart with different time intervals (x axis), the tooltip is not showing in the middle of a long line (see the example, between 4-5 points).

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://codesandbox.io/s/ant-chart-tooltip-bug-mtnovm?file=/App.tsx

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
Is there a way to force the ant chart to show the tooltips on line hovers, and not to points?

**Comment by lxfu1** [comment]
xField must be of type string.
