### ISSUE TITLE
🐛[BUG] Tooltip customItems not changes title

### ISSUE THREAD

**Issue by lajosVlasics** [ant-design/ant-design-charts#1532]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
The tooltip customItems callback does not changes the 'title' (it works for 'name', or the 'value' field).

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
With the customItems callback, map the original tooltip items and change the 'title' field.

### 🏞 期望结果 [描述你原本期望看到的结果]
The title is actually modified in the tooltip.

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/ant-chart-customitems-not-changes-tooltip-title-fqnd0n?file=/App.tsx

### © 版本信息

- ant-design-charts 版本: [1.3.5, 1.4.2]

**Comment by lxfu1** [comment]
https://charts.ant.design/en/docs/api/case#custom-tooltip

**Comment by lxfu1** [comment]
No title!

![image](https://user-images.githubusercontent.com/31396322/186423735-9e4b7168-18c1-4ec5-8e1b-faf9a95b94df.png)
![image](https://user-images.githubusercontent.com/31396322/186423778-b718ee81-6fc5-42e9-a597-d5c4ff709826.png)

**Comment by Tiepbm** [comment]
@lxfu1 I used to **customItems** to filter tooltip. But it not effect
<img width="518" alt="image" src="https://user-images.githubusercontent.com/3059239/191659213-4d5399b1-ec81-41ff-9813-54b14ec79466.png">

<img width="464" alt="image" src="https://user-images.githubusercontent.com/3059239/191659269-747c7e13-b89d-4d9f-8dcd-3b4a93962ebd.png">

result:
![image](https://user-images.githubusercontent.com/3059239/191659320-818d64de-2351-4bdb-8464-4d81e745fc9e.png)

ant-design-charts v1.4.2
