### ISSUE TITLE
🧐[问题]如何绘制2.5D柱状图，饼状图

### ISSUE THREAD

**Issue by liukefu2050** [ant-design/ant-design-charts#1534]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
能否提供2.5D,3D柱状图，饼状图实例
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![微信图片_20220825102000](https://user-images.githubusercontent.com/21030225/186559284-b34a394c-4c90-4410-8b10-a2ad0f9b7a0c.png)

**Comment by lxfu1** [comment]
暂时不支持这种，G2 5.0 发布后会有相关能力@pearmini

**Comment by SongJuXin** [comment]
> 暂时不支持这种，G2 5.0 发布后会有相关能力@pearmini

现在g2版本到 v5.1.3 了，`2.5d饼图`相关能力可以用了吗？

**Comment by A-ANing** [comment]
+1

**Comment by hustcc** [comment]
https://g2.antv.antgroup.com/examples/interesting/interesting/#25d-column 

看看这个 DEMO~

**Comment by lxfu1** [comment]
https://ant-design-charts-next.antgroup.com/examples/statistics/column/#25d
