### ISSUE TITLE
🐛[BUG] The `shape` should be specified when creating a node/edge instance

### ISSUE THREAD

**Issue by hexu107** [ant-design/ant-design-charts#1537]
![image](https://user-images.githubusercontent.com/81137471/186656414-1398a269-7a3b-410e-86d3-07b17a1afe5b.png)
![image](https://user-images.githubusercontent.com/81137471/186656460-6a27e34d-f9f8-4643-aac0-344ccc1dadc0.png)
![image](https://user-images.githubusercontent.com/81137471/186656516-1c88940c-086b-42d7-bfae-f509abc7ac17.png)
官网复制流程图的案列报错，复制到沙盒上没问题包版本也复制了，就本地不行。

**Comment by lxfu1** [comment]
更新到最新版本试一下，这个问题很久之前就修复了
