### ISSUE TITLE
🐛[BUG] The `shape` should be specified when creating a node/edge instance

### ISSUE THREAD

**Issue by hexu107** [ant-design/ant-design-charts#1538]
![image](https://user-images.githubusercontent.com/81137471/186799853-51844bc5-9817-403f-86cd-a771594a6e77.png)
![image](https://user-images.githubusercontent.com/81137471/186657275-89d5e050-e6ba-45dd-854a-9f6f51d101eb.png)
![image](https://user-images.githubusercontent.com/81137471/186799543-c6058689-f48f-4234-8f01-53c342b31a1e.png)
![image](https://user-images.githubusercontent.com/81137471/186802271-4a1b789a-0d12-4dd2-a875-f41434c9caa4.png)
 The `shape` should be specified when creating a node/edge instance

**Comment by lxfu1** [comment]
看下 @ant-design/flowchart 的版本是否是 1.2.1

**Comment by hexu107** [comment]
> 看下@ant-design/flowchart的版本是否是1.2.1
是呀，我更新了一下麻烦大佬看一下我本地的包版本，是包版本的问题嘛

**Comment by lxfu1** [comment]
要看你 node_modules 里面安装的版本 ，你提供的这个配置截图无法复现问题。

**Comment by hexu107** [comment]
> 你的 node_modules 里面的安装版本，你提供的这个配置截图不能复现问题。
node包里面是，我更新了上面的图片。

**Comment by lxfu1** [comment]
给个复现链接，可以把代码脱敏上传到github

**Comment by hexu107** [comment]
> 你的 node_modules 里面的安装版本，你提供的这个配置截图不能复现问题。



> 你的 node_modules 里面的安装版本，你提供的这个配置截图不能复现问题。

就本地有这个问题，放在沙盒里就没有这个问题了，我把本地的版本复制过去也没有

**Comment by lxfu1** [comment]
那就是你本地版本导致的，charts 里面已经包含了 flowchart，你删除依赖里面的@ant-design/flowchart和node_modules重新依赖看看。

**Comment by hexu107** [comment]
> 给个复现链接，可以把代码脱敏上传到github

我发到测网就没有这个问题了，但是布局乱了。
![image](https://user-images.githubusercontent.com/81137471/186803317-de26ff47-f55a-45c5-961d-d8218f98fd96.png)
![image](https://user-images.githubusercontent.com/81137471/186803336-d37f3f15-7371-4426-8962-bb137c1cbc26.png)

**Comment by lxfu1** [comment]
你没有引入antd样式啊

**Comment by hexu107** [comment]
> 那就是你本地版本导致的，charts 里面已经包含了 flowchart，你删除依赖里面的@ant-design/flowchart和node_modules重新依赖看看。

删除了@ant-design/flowchart ，用的charts，重新安装了node包还是不行
