### ISSUE TITLE
🐛[BUG] legend自定义items部分symbol失效

### ISSUE THREAD

**Issue by deviluncle** [ant-design/ant-design-charts#1540]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
使用legend的items自定义时，部分symbol样式失效

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
已通过官方例子复现

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
`import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Line } from '@ant-design/plots';

const DemoLine = () => {
  const [data, setData] = useState([]);

  useEffect(() => {
    asyncFetch();
  }, []);

  const asyncFetch = () => {
    fetch('https://gw.alipayobjects.com/os/bmw-prod/55424a73-7cb8-4f79-b60d-3ab627ac5698.json')
      .then((response) => response.json())
      .then((json) => setData(json))
      .catch((error) => {
        console.log('fetch data failed', error);
      });
  };
  const config = {
    data,
    xField: 'year',
    yField: 'value',
    seriesField: 'category',
    legend: {
      items: [
        {
          id: 1,
          name: 1,
          marker: {
            symbol: 'diamond',
            style: {
              lineDash: [4, 4],
              fill: '#995200'
            }
          }
        },
        {
          id: 2,
          name: 2,
          marker: {
            symbol: 'hyphen',
            style: {
              lineDash: [4, 4],
              fill: '#995200'
            }
          }
        }
      ]
    },
    xAxis: {
      type: 'time',
    },
    yAxis: {
      label: {
        // 数值格式化为千分位
        formatter: (v) => `${v}`.replace(/\d{1,3}(?=(\d{3})+$)/g, (s) => `${s},`),
      },
    },
  };

  return <Line {...config} />;
};

ReactDOM.render(<DemoLine />, document.getElementById('container'));
`

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![WFamfdIO4w](https://user-images.githubusercontent.com/29850196/187130206-720eda67-183d-485f-a77c-5fb0c30bf0cc.jpg)

**Comment by lxfu1** [comment]
你这不是正常的吗？

**Comment by ai-qing-hai** [comment]
@deviluncle  加上   custom: true,
