### ISSUE TITLE
🐛[BUG] 依赖 @ant-design/graphs 1.2.7 导致自定义 Tooltip 消失

### ISSUE THREAD

**Issue by calimanco** [ant-design/ant-design-charts#1541]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

今天重装了一下，就发现原来自定义的Tooltip不见了，看了一下html，发现渲染的结果是g2-tooltip里多套了一个g2-tooltip，而且里面那个一直都是隐藏的，这才导致Tooltip消失。
进一步研究发现是 @ant-design/graphs 更新到 1.2.7 导致的，回退到 1.2.6 就正常了。
PS：顺便一提，customContent的ts描述有问题。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

只贴 tooltip 配置部分
```typescript
<Column
    tooltip={{
    domStyles: {
        'g2-tooltip': {
        color: '#fff',
        backgroundColor: '#4d4d4d'
    }},
    // @ts-ignore
   customContent(title, item) {
        return (
              <><div className='g2-tooltip-title'>{title}</div><ul className='g2-tooltip-list'>...</ul></>
        )
    }}} />

```

### © 版本信息

- ant-design-charts 版本: 1.4.2
- 浏览器环境: Chrome104
- 开发环境: mac OS

**Comment by lxfu1** [comment]
这个问题是底层升级导致的，和 `@ant-design/graphs` 无关，时间点巧合。

**Comment by zhenjs** [comment]
@lxfu1 老板，所以这个问题怎么解决呢
