### ISSUE TITLE
🐛[BUG] 柱形图数据接近y轴最大数据时，柱形顶部数字会超出

### ISSUE THREAD

**Issue by wang-zhixiang** [ant-design/ant-design-charts#1543]
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Column } from '@ant-design/plots';

import { each, groupBy } from '@antv/util';

const DemoColumn = () => {
  const [data, setData] = useState([
    {
        "orderTime": "08-01",
        "value": 1,
        "type": "已回存"
    },
    {
        "orderTime": "08-01",
        "value": 598,
        "type": "待回存"
    },
    {
        "orderTime": "08-02",
        "value": 0,
        "type": "已回存"
    },
    {
        "orderTime": "08-02",
        "value": 575,
        "type": "待回存"
    },
    {
        "orderTime": "08-03",
        "value": 0,
        "type": "已回存"
    },
    {
        "orderTime": "08-03",
        "value": 237,
        "type": "待回存"
    },
    {
        "orderTime": "08-04",
        "value": 0,
        "type": "已回存"
    },
    {
        "orderTime": "08-04",
        "value": 550,
        "type": "待回存"
    },
    {
        "orderTime": "08-05",
        "value": 1,
        "type": "已回存"
    },
    {
        "orderTime": "08-05",
        "value": 576,
        "type": "待回存"
    },
    {
        "orderTime": "08-06",
        "value": 0,
        "type": "已回存"
    },
    {
        "orderTime": "08-06",
        "value": 581,
        "type": "待回存"
    },
    {
        "orderTime": "08-07",
        "value": 0,
        "type": "已回存"
    },
    {
        "orderTime": "08-07",
        "value": 575,
        "type": "待回存"
    },
    {
        "orderTime": "08-08",
        "value": 2,
        "type": "已回存"
    },
    {
        "orderTime": "08-08",
        "value": 569,
        "type": "待回存"
    },
    {
        "orderTime": "08-09",
        "value": 0,
        "type": "已回存"
    },
    {
        "orderTime": "08-09",
        "value": 558,
        "type": "待回存"
    },
    {
        "orderTime": "08-10",
        "value": 0,
        "type": "已回存"
    },
    {
        "orderTime": "08-10",
        "value": 594,
        "type": "待回存"
    },
    {
        "orderTime": "08-11",
        "value": 0,
        "type": "已回存"
    },
    {
        "orderTime": "08-11",
        "value": 261,
        "type": "待回存"
    },
]);

 
  // 也可以在项目中直接使用 lodash
  const annotations = [];
  each(groupBy(data, 'orderTime'), (values, k) => {
    const value = values.reduce((a, b) => a + b.value, 0);
    annotations.push({
      type: 'text',
      position: [k, value],
      content: `${value}`,
      style: {
        textAlign: 'center',
        fontSize: 14,
        fill: 'rgba(0,0,0,0.85)',
      },
      offsetY: -10,
    });
  });
  const config = {
    data,
    isStack: true,
    xField: 'orderTime',
    yField: 'value',
    seriesField: 'type',
    color: ['#52c41a', '#cf0030',],
      isStack: true,
      legend: {
        layout: 'vertical',
        position: 'left'
      },
    // 使用 annotation （图形标注）来展示：总数的 label
    annotations,
    yAxis: {
      verticalLimitLength: 700,
    },
  };

  return <Column {...config} />;
};

ReactDOM.render(<DemoColumn />, document.getElementById('container'));

### © 版本信息

- ant-design-charts 版本: 1.4.2
- 浏览器环境 edge 104.0.1293.70
- 开发环境 windows

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![1661846872755](https://user-images.githubusercontent.com/110386078/187384565-dd6f6005-4ac3-4682-a645-71143ec8c44e.png)

**Comment by lxfu1** [comment]
limitInPlot: true

**Comment by wang-zhixiang** [comment]
limitInPlot: true 并不能起到作用 @lxfu1 

![1662011062151](https://user-images.githubusercontent.com/110386078/187840319-4d44bfaa-8c6b-4e41-9853-0cd012f85299.png)

**Comment by wang-zhixiang** [comment]
> limitInPlot: true

无效

https://user-images.githubusercontent.com/110386078/187840319-4d44bfaa-8c6b-4e41-9853-0cd012f85299.png

**Comment by lxfu1** [comment]
```ts
 label: {
      layout: [{type: 'limit-in-plot'}]
    },
```

**Comment by wang-zhixiang** [comment]
> limitInPlot: true

使用这个api也无效
![1662011879993](https://user-images.githubusercontent.com/110386078/187842167-93e019a0-2446-42d8-964f-378375cbb635.png)

**Comment by wang-zhixiang** [comment]
> ```ts
>  label: {
>       layout: [{type: 'limit-in-plot'}]
>     },
> ```

@lxfu1 
![1662012119198](https://user-images.githubusercontent.com/110386078/187842772-5d9c6390-fe7b-4b93-b163-c5422f54ac97.png)

**Comment by eternallycyf** [comment]
appendPadding || padding 进行调整

**Comment by Martvey** [comment]
limitInPlot: false
