### ISSUE TITLE
下一个版本什么时候迭代

### ISSUE THREAD

**Issue by jck9** [ant-design/ant-design-charts#1544]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
下一个版本什么时候迭代！！！！

**Comment by lxfu1** [comment]
G2 5.0 发布后会升级到2.0，graphs\plots\flowchart也会有大版本的升级，有没有兴趣一起？

**Comment by lxfu1** [comment]
https://ant-design-charts-next.antgroup.com/
