### ISSUE TITLE
🐛[BUG] Chart displays data inappropriately

### ISSUE THREAD

**Issue by leventebg93** [ant-design/ant-design-charts#1545]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
React - Antd chart displays data inappropriately (it puts a weird horizontal line to certain places)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
use this as data source
[data](https://jsonkeeper.com/b/KEFQ)

And the component code:
```
  import { Line } from '@ant-design/plots';  

  ....
  ....

  const config = {
        data,
        xField: 'md',
        yField: 'tvd',
    };

    return <Line {...config}/>;
```
The result:
![image](https://user-images.githubusercontent.com/97885059/188096854-bd7cf31a-52a6-4f5c-9946-a79c83e7b7b1.png)

And this horizontal line is repeated if the data is larger 

### 🏞 期望结果 [描述你原本期望看到的结果]

This is how it should look like 
![image](https://user-images.githubusercontent.com/97885059/188097543-da0f38cb-1f5c-4db8-9c4e-af0c1b79464f.png)

(I had to remove the 1st data object (tvd:30,md:30) to get it to work, which shouldnt even be related 

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
Described in Step 2

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by leventebg93** [comment]
To demonstrate the problem with a more extreme example you can use this data
https://jsonkeeper.com/b/ABAH

Now the result instead of a single diagonal line is a zig-zag
![image](https://user-images.githubusercontent.com/97885059/188113220-6d3b9fc7-6e73-4b4d-8833-3f6273d9088b.png)

**Comment by lxfu1** [comment]
`xFiled` type must be string and no repeat.

**Comment by leventebg93** [comment]
> `xFiled` type must be string and no repeat.

Xfield is actually a string
xField: 'md' => 'md' is a string

What do you mean by no repeat? Should I add it somewhere

**Comment by lxfu1** [comment]
"md":60,  => "md": '60',
