### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by wangjingithub** [ant-design/ant-design-charts#1546]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
组织架构图nodeCfg 配置中，如果文字过长，则超出范围，如果设置 autoWidth：auto 标签会变得很长。
是否可以在固定宽度的情况下，设置省略号并且hover的时候可以有类似title显示全部文字，请问有什么配置或者其他解决方案

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
无
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/32031683/188102118-c4943b0e-d4b3-4f8e-b77b-5d5592001bfd.png)

**Comment by lxfu1** [comment]
hover 可以通过 tooltip 配置，自动隐藏这个后续支持下，可以先处理下数据，如图：

![image](https://user-images.githubusercontent.com/31396322/188115931-e4d104f6-5f6a-46d5-b24a-4b515e633b48.png)

**Comment by wangjingithub** [comment]
> hover 可以通过 tooltip 配置，自动隐藏这个后续支持下，可以先处理下数据，如图：
> 
> ![image](https://user-images.githubusercontent.com/31396322/188115931-e4d104f6-5f6a-46d5-b24a-4b515e633b48.png)
感谢回复

**Comment by hhbusui** [comment]
组织架构图可以自定义item去解决这个问题（文字过长，超出范围）么？ @lxfu1

**Comment by lxfu1** [comment]
支持， 看下这个示例的 [customContent](https://charts.ant.design/zh/examples/relation-graph/flow-analysis-graph#custom)

**Comment by hhbusui** [comment]
> 支持， 看下这个示例的 [customContent](https://charts.ant.design/zh/examples/relation-graph/flow-analysis-graph#custom)

好的  谢谢您
