### ISSUE TITLE
🐛[BUG] 用mix组件 渲染四个相同配置的饼图，选择分类发现 渲染颜色会出现不一样的颜色

### ISSUE THREAD

**Issue by Jeffreymmm** [ant-design/ant-design-charts#1547]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/52057193/188357788-f600b28e-b611-4326-b04c-9c48a6221053.png)
渲染pie mix 为什么 还可以颜色不一样

**Comment by lxfu1** [comment]
手动指定 color

**Comment by Jeffreymmm** [comment]
能解决，谢谢
