### ISSUE TITLE
🧐 X-axis label positions to be based on a defined interval

### ISSUE THREAD

**Issue by leventebg93** [ant-design/ant-design-charts#1549]
### 🧐 X-axis labels position to be based on defined intervals ..instead of the data
![image](https://user-images.githubusercontent.com/97885059/188396681-935127d3-cf12-4814-adec-bb926e326adc.png)
I have this graph where both axes are numbers - which in order to make it work the x axis had to be converted to string to avoid a bug 

I want to have have the **x-axis to have numbers like 500-1000-1500** etc.. instead of the chart defining them from the data
Is that possible?

**This is how I want it to look**
![image](https://user-images.githubusercontent.com/97885059/188400282-a5f821aa-f5da-4e2a-965b-1d38616e5462.png)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
data: https://jsonkeeper.com/b/2PIJ

 ```
const config = {
        data,
        xField: 'tvd',
        yField: 'md',
       //...styling
}

 return <Line {...config}  />;
```

**Comment by lxfu1** [comment]
```ts
    meta: {
      tvd:{
        type: 'log'
      }
    },
```
![image](https://user-images.githubusercontent.com/31396322/188529777-22e36d29-9464-4fb2-a07a-806b736fa286.png)

**Comment by leventebg93** [comment]
> ```ts
>     meta: {
>       tvd:{
>         type: 'log'
>       }
>     },
> ```
> 
> ![image](https://user-images.githubusercontent.com/31396322/188529777-22e36d29-9464-4fb2-a07a-806b736fa286.png)

It was meta.type: "linear" actually. Thanks anyway
