### ISSUE TITLE
🧐[问题]canvas模式下，环图的中央文字如何能留在导出的图片中？目前导出的环图中央是空的

### ISSUE THREAD

**Issue by wangwufan** [ant-design/ant-design-charts#1551]
### 🚑 ![image](https://user-images.githubusercontent.com/12657738/188574234-4c4ccf92-34bc-46b2-b1ae-e4243cc8db77.png)
![image](https://user-images.githubusercontent.com/12657738/188575197-0fde2f96-c3e2-4ea0-8517-21c2da7f00c6.png)

**Comment by lxfu1** [comment]
试试 [html2canvas](https://www.npmjs.com/package/html2canvas)

**Comment by wangwufan** [comment]
> 试试 [html2canvas](https://www.npmjs.com/package/html2canvas)

html2canvas是根据Dom生成图片，在和antdesignchart结合使用时体验太差了，png图片也不透明，你们能不能原生支持一下，就像对label格式化的formatter一样可以用G2引擎绘制图形?

**Comment by wangwufan** [comment]
> 试试 [html2canvas](https://www.npmjs.com/package/html2canvas)

html2canvas是根据Dom生成图片，在和antdesignchart结合使用时体验太差了，png图片也不透明，你们能不能原生支持一下，就像对label格式化的formatter一样可以用G2引擎绘制图形?
