### ISSUE TITLE
地图鼠标移入时，支持显示阴影吗？

### ISSUE THREAD

**Issue by yjslv** [ant-design/ant-design-charts#1553]
当前 鼠标放到地图上，支持的样式好像很有限，只有stoke和color ，怎么能让其支持shadow，从而达到立体的效果 ？
![image](https://user-images.githubusercontent.com/29451780/188604094-3cd307a7-c833-40d9-a6ee-43ed98c644ae.png)

**Comment by lvisei** [comment]
@yjslv 不支持，可参考 L7 的 [3D 填充图](https://l7.antv.antgroup.com/examples/polygon/3d/#floatmap)
