### ISSUE TITLE
🧐[问题] react18渲染组织架构图问题（重复渲染/第二次渲染key不唯一）

### ISSUE THREAD

**Issue by hhbusui** [ant-design/ant-design-charts#1554]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
组织架构图在react18中渲染两次，此问题暂时删除StrictMode解决了，不知道有没有其他方式呢？

第二次重复渲染描述
我通过getTopoInitData获取拓扑图数据（拓扑图数据存储在redux中）。第一次渲染没有问题，第二次渲染或者更改代码中的数据就会渲染失败，失败的原因说我key不唯一。

```
useEffect(() => {
   getTopoInitData();

    // return () => {
    // 	dispatch(setTopoData({}));
    // };
}, []);
```

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

package.json信息

"react": "^18.2.0",
"@ant-design/flowchart": "^1.1.3",
"@ant-design/graphs": "^1.1.3",
"@ant-design/icons": "^4.7.0",
"@ant-design/plots": "^1.0.9",

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/43135111/188848104-6640a83c-0e31-4ee4-8346-fe65789364ab.png)

![image](https://user-images.githubusercontent.com/43135111/188847002-4770fc60-0445-4a8b-9002-2d743e8dc238.png)

**Comment by lxfu1** [comment]
近期修复，能提供一下复现代码吗？

**Comment by lxfu1** [comment]
这是 React18 的新特性，StrictMode 在 dev 环境会渲染 2 次（will only happen in dev），主要用于检测代码是否存在过时写法或副作用，https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode ，可以先去掉。

**Comment by hhbusui** [comment]
第二个问题我自己的问题，抱歉了。
