### ISSUE TITLE
使用seriesField 中各个字段（field）展示图例🧐[问题]

### ISSUE THREAD

**Issue by Tomlili43** [ant-design/ant-design-charts#1562]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
目前的展示情况
![image](https://user-images.githubusercontent.com/58140546/189792183-1b7ffbdd-9078-4190-946d-d29913f7fdd7.png)
预期目标：修改 a b c 显示为aaaa bbbb cccc
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
目前代码 可用meta修改 value 为温度 但 count为seriesField  涉及多个字段 如何修改呢？
[柱多线混合图：](https://charts.ant.design/zh/examples/dual-axes/column-line#column-multi-line)
`import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { DualAxes } from '@ant-design/plots';

const DemoDualAxes = () => {
  const uvData = [
    {
      time: '2019-03',
      value: 35,
    },
    {
      time: '2019-04',
      value: 90,
    },
    {
      time: '2019-05',
      value: 30,
    },
    {
      time: '2019-06',
      value: 45,
    },
    {
      time: '2019-07',
      value: 47,
    },
  ];
  const transformData = [
    {
      time: '2019-03',
      count: 800,
      name: 'a',
    },
    {
      time: '2019-04',
      count: 600,
      name: 'a',
    },
    {
      time: '2019-05',
      count: 400,
      name: 'a',
    },
    {
      time: '2019-06',
      count: 380,
      name: 'a',
    },
    {
      time: '2019-07',
      count: 220,
      name: 'a',
    },
    {
      time: '2019-03',
      count: 750,
      name: 'b',
    },
    {
      time: '2019-04',
      count: 650,
      name: 'b',
    },
    {
      time: '2019-05',
      count: 450,
      name: 'b',
    },
    {
      time: '2019-06',
      count: 400,
      name: 'b',
    },
    {
      time: '2019-07',
      count: 320,
      name: 'b',
    },
    {
      time: '2019-03',
      count: 900,
      name: 'c',
    },
    {
      time: '2019-04',
      count: 600,
      name: 'c',
    },
    {
      time: '2019-05',
      count: 450,
      name: 'c',
    },
    {
      time: '2019-06',
      count: 300,
      name: 'c',
    },
    {
      time: '2019-07',
      count: 200,
      name: 'c',
    },
  ];
  const config = {
    data: [uvData, transformData],
    xField: 'time',
    yField: ['value', 'count'],
    meta: {
    value: {
      alias: '温度',
    },
    count: {
      alias: '海拔'
    }
  },
    geometryOptions: [
      {
        geometry: 'column',
        columnWidthRatio: 0.4,
      },
      {
        geometry: 'line',
        seriesField: 'name',
      },
    ],
  };
  return <DualAxes {...config} />;
};

ReactDOM.render(<DemoDualAxes />, document.getElementById('container'));`

**Comment by lxfu1** [comment]
```ts
    meta: {
      name:{
        formatter:(arg)=> {
        return 'name'
       }
      }
    },
```

**Comment by Tomlili43** [comment]
![image](https://user-images.githubusercontent.com/58140546/189843170-b59e99c8-1920-43d9-b8cf-7f223f4286fd.png)

**Comment by Tomlili43** [comment]
Example to the solution, the below image is my code solution.[https://charts.ant.design/zh/examples/component/legend#legend-item-cfg](url).
**change the config of legend**
![image](https://user-images.githubusercontent.com/58140546/189843954-84038d79-8d53-479d-9b92-a95551a205d1.png)
