### ISSUE TITLE
🐛[BUG]多折线图配置label后，如果数据相同，点击legend关闭其中一项，相同数据的label文字也会消失

### ISSUE THREAD

**Issue by Nangras** [ant-design/ant-design-charts#1566]
### 🐛 bug 描述
多折线图配置label后，如果数据相同，点击legend关闭其中一项，相同数据的label文字也会消失

### 📷 复现步骤
代码中可看到【7日回报率】和【14日回报率】的数据是相等的，当我们点击legend隐藏【7日回报率】，会发现【14日回报率】的文案也消失了

### 🏞 期望结果
即使存在相同的数据，在点击legend关闭其中某一项时，剩余数据也应保留label文案

### 💻 复现代码
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Line } from '@ant-design/plots';

const DemoLine = () => {
  const [data, setData] = useState([
    {
        "date": "2022-07-01",
        "value": 3.8,
        "category": "首日回报率"
    },
    {
        "date": "2022-07-01",
        "value": 10.9,
        "category": "3日回报率"
    },
    {
        "date": "2022-07-01",
        "value": 16.9,
        "category": "7日回报率"
    },
    {
        "date": "2022-07-01",
        "value": 16.9,
        "category": "14日回报率"
    },
    {
        "date": "2022-07-01",
        "value": 46.7,
        "category": "30日回报率"
    },
    {
        "date": "2022-07-01",
        "value": 73,
        "category": "60日回报率"
    },
    {
        "date": "2022-07-01",
        "value": 76.2,
        "category": "90日回报率"
    }
]);

  const config = {
data,
        xField: 'date',
        yField: 'value',
        seriesField: 'category',
        yAxis: {
          label: { formatter: (v) => `${v}%` },
        },
        label: { formatter: (item) => `${item.value}%` },
        legend: {
          position: 'right',
          itemName: { formatter: (name) => `${name}` },
        },
        tooltip: {
          fields: ['value', 'category'],
          formatter: (datum) => {
            return { name: datum.category, value: datum.value + '%' };
          },
        },
  };

  return <Line {...config} />;
};

ReactDOM.render(<DemoLine />, document.getElementById('container'));

### © 版本信息

- ant-design-charts 版本: [ 1.4.2]
- 浏览器环境[谷歌浏览器]
- 开发环境 [ win10]
![image](https://user-images.githubusercontent.com/30164340/190049360-d7f3cbfc-22e8-4865-a8ce-f11c688474f8.png)
![image](https://user-images.githubusercontent.com/30164340/190049387-5cae2c83-5552-4e91-b7ac-e43371ea1395.png)

**Comment by lxfu1** [comment]
这是因为底层做了 label 防重叠处理，如果要展示全量 label 的话，可以做如下配置。
```ts
 label: {
    layout: []
  },
```
