### ISSUE TITLE
官方基础饼图content变量引入报类型错误

### ISSUE THREAD

**Issue by zhengesther0825** [ant-design/ant-design-charts#1567]
### 🧐 问题描述
使用官方基础饼图示例，TS报如下错误，主要是content类型不对，请问大佬们这个怎么修改
Type '{ appendPadding: number; data: { type: string; value: number; }[]; angleField: string; colorField: string; radius: number; label: { type: string; offset: string; content: ({ percent }: { percent: any; }) => string; style: { ...; }; }; interactions: { ...; }[]; }' is not assignable to type 'PieConfig'.
  Types of property 'label' are incompatible.
    Type '{ type: string; offset: string; content: ({ percent }: { percent: any; }) => string; style: { fontSize: number; textAlign: string; }; }' is not assignable to type 'Label | undefined'.
      Type '{ type: string; offset: string; content: ({ percent }: { percent: any; }) => string; style: { fontSize: number; textAlign: string; }; }' is not assignable to type '{ readonly fields?: string[] | undefined; readonly callback?: LabelCallback | undefined; readonly formatter?: string | IGroup | IShape | GeometryLabelContentCallback | undefined; } & GeometryLabelCfg'.
        Type '{ type: string; offset: string; content: ({ percent }: { percent: any; }) => string; style: { fontSize: number; textAlign: string; }; }' is not assignable to type 'GeometryLabelCfg'.
          Types of property 'content' are incompatible.
            Type '({ percent }: { percent: any; }) => string' is not assignable to type 'string | IGroup | IShape | GeometryLabelContentCallback | undefined'.
              Type '({ percent }: { percent: any; }) => string' is not assignable to type 'GeometryLabelContentCallback'.
                Types of parameters '__0' and 'data' are incompatible.
                  Property 'percent' is missing in type 'Datum' but required in type '{ percent: any; }'.

### 💻 示例代码
链接如下 https://charts.ant.design/zh/examples/pie/basic#basic
const config = {
    appendPadding: 10,
    data,
    angleField: 'value',
    colorField: 'type',
    radius: 0.9,
    label: {
      type: 'inner',
      offset: '-30%',
      content: ({ percent }) => `${(percent * 100).toFixed(0)}%`,
      style: {
        fontSize: 14,
        textAlign: 'center',
      },
    },
    interactions: [
      {
        type: 'element-active',
      },
    ],
  };

**Comment by lxfu1** [comment]
const config = {} as any; 先临时解决一下，后续看看。
