### ISSUE TITLE
🐛[BUG]mapbox的401报错

### ISSUE THREAD

**Issue by symnetry** [ant-design/ant-design-charts#1568]
[官网示例](https://charts.ant.design/zh/examples/map-dot/map-scatter#classified-scatter)

官网示例中的散点图@ant-design/maps
只要引用了上面的map 就会有mapbox的401报错

`import { DotMap } from '@ant-design/maps';`
mapbox指向了这个 [链接](https://api.mapbox.com/styles/v1/zcxduo/ck241p6413s0b1cpayzldv7x7?access_token=pk.eyJ1IjoiMTg5Njk5NDg2MTkiLCJhIjoiY2s5OXVzdHlzMDVneDNscDVjdzVmeXl0dyJ9.81SQ5qaJS0xExYLbDZAGpQ)

**Comment by meiguiyisenluo** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/52649954/8cc5d4ee-4546-4c3c-a3cf-bfcc621df908)
