### ISSUE TITLE
🧐[问题] 折線圖的鄰近元素如果設置了`float: left/right`css屬性，圖表`canvas`高度會無限增長

### ISSUE THREAD

**Issue by BensonLiao** [ant-design/ant-design-charts#1569]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
折線圖的鄰近元素如果設置了 `float: left/right` css屬性，
圖表`canvas`高度會無限增長，
有大大知道這是為啥嗎？
感謝

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://codesandbox.io/s/antd-chart-sibling-float-element-issue-q5m9yd?file=/index.js

**Comment by lxfu1** [comment]
`autoFit: false` OR
```tsx
 <div style={{height: 500}}>
    <Line {...config} />
  </div>
```
