### ISSUE TITLE
🧐[问题]如何给Column柱子加一个选中状态

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design-charts#157]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
RT.
需求是通过点击柱子联动Table的数据显示，所以想给选中的柱子加一个类似hover的样式
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
无
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/20501316/91023843-a684f380-e629-11ea-9456-225f00d69f8f.png)

**Comment by lxfu1** [comment]
```js
columnPlot.setActive({
  name: 'type',
  exp: (value) => {
    return value === '10月';
  }
}, {
  fill: 'red'
});
```

**Comment by lxfu1** [comment]
> ```js
> columnPlot.setActive({
>   name: 'type',
>   exp: (value) => {
>     return value === '10月';
>   }
> }, {
>   fill: 'red'
> });
> ```

https://charts.ant.design/guide/case#%E8%8E%B7%E5%8F%96-chart-%E5%AE%9E%E4%BE%8B

**Comment by afc163** [comment]
exp 是啥意思？搞一个比较容易看懂的 API 吧。

**Comment by lxfu1** [comment]
> exp 是啥意思？搞一个比较容易看懂的 API 吧。

嗯嗯 2.0 我们规划哈。
