### ISSUE TITLE
🐛[BUG] 有中位线的折线图添加了slider以后 出现异常

### ISSUE THREAD

**Issue by A9074o** [ant-design/ant-design-charts#1570]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/45235142/190123833-313c5f02-d559-4278-bf2e-74e75b360fa5.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
和折线图一样实时变化
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
`import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Line } from '@ant-design/plots';

const DemoLine = () => {
  const [data, setData] = useState([]);

  useEffect(() => {
    asyncFetch();
  }, []);

  const asyncFetch = () => {
    fetch('https://gw.alipayobjects.com/os/bmw-prod/1d565782-dde4-4bb6-8946-ea6a38ccf184.json')
      .then((response) => response.json())
      .then((json) => setData(json))
      .catch((error) => {
        console.log('fetch data failed', error);
      });
  };
  const config = {
    data,
    padding: 'auto',
    xField: 'Date',
    yField: 'scales',
    annotations: [
      // 低于中位数颜色变化
      {
        type: 'regionFilter',
        start: ['min', 'median'],
        end: ['max', '0'],
        color: '#F4664A',
      },
      {
        type: 'text',
        position: ['min', 'median'],
        content: '中位数',
        offsetY: -4,
        style: {
          textBaseline: 'bottom',
        },
      },
      {
        type: 'line',
        start: ['min', 'median'],
        end: ['max', 'median'],
        style: {
          stroke: '#F4664A',
          lineDash: [2, 2],
        },
      },
    ],
      slider: {
        start: 0,
        end: 1,
        height: 26,
      },
  };

  return <Line {...config} />;
};

ReactDOM.render(<DemoLine />, document.getElementById('container'));
`
### © 版本信息

- ant-design-charts 版本: 1.42
- 浏览器环境 谷歌
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
V2 `slider: {x: {}}`

**Comment by maxeth** [comment]
> V2 `slider: {x: {}}`

@lxfu1  You mean we should upgrade to the v2 version of the package and `slider: {x: {}}` will fix it? When I update to the latest v2 version, I get: `Error: Unknown mark: regionFilter.`, so I can't even use the `regionFilter` annotation 🤔 (I just tried to use the code from the [example](https://ant-design-charts.antgroup.com/en/examples/line/basic/#line-annotation)).

![Screenshot 2024-01-23 at 16 13 18](https://github.com/ant-design/ant-design-charts/assets/48837036/a6af2bd2-ab93-44aa-a972-02dc0920fa5e)

**Comment by lxfu1** [comment]
Refer to [Option](https://ant-design-charts-next.antgroup.com/options/plots/annotation/range)
