### ISSUE TITLE
🧐[问题] 组织架构图数据改变界面刷新问题

### ISSUE THREAD

**Issue by hhbusui** [ant-design/ant-design-charts#1574]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
const topoData = useSelector(state => state.homeResData.topoData);
topoData 是我的组织结构图数据。
问题：
1、当我在界面中动态修改数据后，界面会整体刷新一次，如果我的数据是定时变化的话是否界面就会一直刷新呢
2、可以有局部刷新的方式么？

ps: 代码中我是自定义item (customContent)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
无

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
无

**Comment by lxfu1** [comment]
因为局部刷新底层存在一些问题，在 charts 层选择了关闭，不过针对特定场景，我们也有一些解决方案，可参考  https://charts.ant.design/zh/examples/relation-graph/decomposition-tree-graph#async-load
