### ISSUE TITLE
针对label可以提供html字符串渲染的功能吗👑 [需求]

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#1575]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

想实现类似下图的条件样式，但是查了下资料目前`antd charts`不支持直接渲染html字符串：
![预期效果](https://user-images.githubusercontent.com/49147660/190414667-8cc99585-e6e0-4199-810f-fecd502d7b94.JPG)

**Comment by lxfu1** [comment]
目前不支持，可以用annotations: [{type: 'html'}]
