### ISSUE TITLE
🧐[问题]折线图纵坐标轴标题位置问题

### ISSUE THREAD

**Issue by Vkashuu** [ant-design/ant-design-charts#1576]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
折线图的纵坐标轴标题能否旋转之后放到纵坐标轴上方，如图所示。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/34912470/190542877-e302ed6f-eca3-4b3e-a42a-41bb37f485e4.png)

**Comment by lxfu1** [comment]
```ts
 yAxis: {
      title: {
        text: 'title',
        position: 'end'
      }
    },
```

**Comment by xuoutput** [comment]
@lxfu1 这里只是把 个数放到了上面, 个数两个字是垂直, 而不是水平的

**Comment by Ich-liebe-dich** [comment]
> @lxfu1 这里只是把 个数放到了上面, 个数两个字是垂直, 而不是水平的 例如 <img alt="image" width="776" src="https://user-images.githubusercontent.com/16385443/192685934-2545c16f-95ba-411f-b20a-0e4fe87ba0ec.png"> 来自官网 demo https://charts.ant.design/zh/examples/line/multiple#line-grid
> 
> 期望的是 <img alt="image" width="408" src="https://user-images.githubusercontent.com/16385443/192686022-bfde279e-6691-4379-af14-5518c7b0eef6.png">

同遇到这个问题，想了好久，annotations或许是一种解决思路，同时设置 appendPadding，避免因自定义的文本超出折线图而不显示。https://charts.ant.design/zh/docs/api/graphic-style
``` 
const config = {
    data,
    padding: 'auto',
    appendPadding: 32,
    xField: 'Date',
    yField: 'scales',
    xAxis: {
      // type: 'timeCat',
      tickCount: 5,
    },
    annotations: [
       {
        type: 'text',
        position: ['0%', '0%'],
        offsetX: -48,
        offsetY: -24,
        content: '辅助文本',
      },
    ]
  };
```

**Comment by sdhushu** [comment]
同遇到问题，以下或许是解决方案
```typescript
title: {
  // 轴线标题
  text: 'kWh',
  // 禁止旋转
  autoRotate: false,
  // 位置
  position: 'end',
  // 间距 单位与轴线对齐
  spacing: -15,
  style: {
     // 位置 y轴方向
      y: 25,
      fill: '#7A8297'
    },
},
``` 
![image](https://github.com/ant-design/ant-design-charts/assets/54340686/24cad9f9-74be-4789-9db2-f9871432088d)
