### ISSUE TITLE
🐛[BUG]示例中心来源去向图打开报错

### ISSUE THREAD

**Issue by a758801405** [ant-design/ant-design-charts#1577]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/13042895/190551445-f4fcdbed-d4c3-4e5f-b0c6-de38df3d9038.png)

### © 版本信息

- ant-design-charts 版本: [e.g. 1.4.2]
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
官网示例问题，可以正常使用，随后修复。
