### ISSUE TITLE
👑 [需求]迷你图表也需要onlyChangeData功能

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design-charts#158]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
RT
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
无
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
无

**Comment by lxfu1** [comment]
目前就支持的啊

**Comment by WangJM001** [comment]
RingProgress没看到这个属性
![image](https://user-images.githubusercontent.com/20501316/91115913-d382e600-e6bd-11ea-89b2-62244c194ec5.png)

**Comment by lxfu1** [comment]
额 这是类型问题，先ignore一下，改动点比较大，v2 会去掉 onlyChangeData ， 内部进行判断。

**Comment by WangJM001** [comment]
ok

**Comment by WangJM001** [comment]
有bug 加了后percent变化了没瓜的，图形没变化

**Comment by lxfu1** [comment]
1.0  内部已经做了优化。
