### ISSUE TITLE
🐛[BUG]雷达图lineStyle和area配置项使用回调函数，不符合预期

### ISSUE THREAD

**Issue by realzbc** [ant-design/ant-design-charts#1581]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
雷达图**lineStyle**和**area**配置项使用回调函数，不符合预期（series一直是undefined）
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
在https://charts.ant.design/zh/examples/more-plots/radar#line-grid 中增加如下配置项
```javascript
lineStyle: (x, y, series) => {
      return {
        stroke: series === "a" ? "red" : "yellow",
        lineWidth: 3
      };
    },
    area: {
      style: (x, y, series) => {
        return {
          fill: series === "a" ? "red" : "yellow"
        };
      }
    }
```
### 🏞 期望结果 [描述你原本期望看到的结果]
a组使用红色，b组使用黄色
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
[线上demo](https://codesandbox.io/s/still-smoke-wwcgiw?file=/index.js:1119-1389)
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境 chrome@latest
- 开发环境 macos

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1346" alt="截屏2022-09-18 下午7 20 15" src="https://user-images.githubusercontent.com/3351124/190899494-8dccd808-f18f-43bd-bcde-558a4fdc59eb.png">

**Comment by lxfu1** [comment]
```ts
    lineStyle: ({user}) => {
      return {
        stroke: user === "a" ? "red" : "yellow",
        lineWidth: 3
      };
    },
```
