### ISSUE TITLE
流程图和procards使用、切换点击和收起左边时直接卡死了，不清楚什么状况🧐[问题]

### ISSUE THREAD

**Issue by tzsb3** [ant-design/ant-design-charts#1582]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/41953568/190916440-af198f48-a9c9-4141-9551-5ab53802bba4.png)
![image](https://user-images.githubusercontent.com/41953568/190916490-08f1a967-9dfd-411f-839d-4b8b0e3274a2.png)

**Comment by tzsb3** [comment]
![image](https://user-images.githubusercontent.com/41953568/190916543-805bccd9-c339-4ff0-b8b9-a2ad7fa0d48b.png)
这里使用

**Comment by lxfu1** [comment]
光看代码不知道什么问题，尽可能提供复现。
