### ISSUE TITLE
【BUG】slider 添加在双轴图后，改变缩略轴的长度及位置 双折线图未被刷新

### ISSUE THREAD

**Issue by YiYimm811** [ant-design/ant-design-charts#1585]
slider 添加在双轴图后，改变缩略轴的长度及位置 双折线图未被刷新，折线图及tooltip显示异常
![image](https://user-images.githubusercontent.com/48373509/191230231-3f119ea2-ded7-44a1-bb3e-8bea172b4a27.png)
![image](https://user-images.githubusercontent.com/48373509/191230345-d763542f-4f1e-4a0e-82b5-34d45c3212a5.png)
![image](https://user-images.githubusercontent.com/48373509/191230434-ca66fbda-7843-4f3d-8bbc-83033a8a4f56.png)

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/489
