### ISSUE TITLE
官网“关系图”下多个示例渲染失败🐛[BUG]

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#1587]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

官网“关系图”下多个示例失效，具体有**指标拆解图-节点占比**，以及**来源去向图**下所有示例

![image](https://user-images.githubusercontent.com/49147660/192097330-8970127d-dd0e-491a-b0d8-5954174cbc20.png)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
强制刷新一下
