### ISSUE TITLE
🐛[BUG] 对双折线图 - 多折线进行 bursh-x 后, 双击恢复发现折现到图外去了

### ISSUE THREAD

**Issue by xuoutput** [ant-design/ant-design-charts#1592]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
对双折线图 - 多折线进行 bursh-x 后, 双击恢复发现折现到图外去了
<img width="969" alt="image" src="https://user-images.githubusercontent.com/16385443/192516832-d7cc1a34-beaf-4c55-958a-9967b50f0d1a.png">

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

在 demo 示例这里 https://charts.ant.design/zh/examples/dual-axes/dual-line#dual-multi-line
配置增加一行代码
<img width="454" alt="image" src="https://user-images.githubusercontent.com/16385443/192517003-cc717e09-343c-42b4-876d-9f27d8147b68.png">
`interactions: [{ type: 'brush-x' }],`

原图形
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/16385443/192517115-ca064de2-9e2e-408d-894b-90d365300441.png">
鼠标对图形进行一个 x 轴的刷选
之后 双击恢复
<img width="980" alt="image" src="https://user-images.githubusercontent.com/16385443/192517216-593a7654-6d39-4adb-b6ec-28eda8cad10c.png">

### © 版本信息

- ant-design-charts 版本: [1.4.2]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xuoutput** [comment]
=_=

**Comment by lxfu1** [comment]
加个`padding: 20,` 试试
