### ISSUE TITLE
@ant-design/charts 1.4.2中graphs打包错误🐛[BUG]

### ISSUE THREAD

**Issue by Gin-X** [ant-design/ant-design-charts#1593]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/16318542/192521621-c7ec8542-e34e-4a02-bd88-9e90455c4e03.png">

### © 版本信息

- ant-design-charts 版本: 1.4.2[e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
看下 @ant-design/graphs 是那个版本？ 或者先用子包临时解决一下 `@ant-design/plots`

**Comment by lxfu1** [comment]
最新的 graphs 是 1.3.1， 1.3.0 有 bug！

**Comment by Gin-X** [comment]
> 最新的 graphs 是 1.3.1， 1.3.0 有 bug！

嗯嗯。graphs1.3.1试过，可以了。3Q。
