### ISSUE TITLE
🐛[BUG]指标拆解图未做适配

### ISSUE THREAD

**Issue by Js-Man-H5** [ant-design/ant-design-charts#1594]
### © 版本信息

- ant-design-charts 版本: [1.4.2]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
屏幕先大后小
![image](https://user-images.githubusercontent.com/62057975/192707305-b1f579dd-d8ef-4ba0-8af7-f44529ec527f.png)
屏幕先小后大
![image](https://user-images.githubusercontent.com/62057975/192707467-1314fcd2-20a7-407d-9784-9778888ee517.png)
官网案例同样有问题 只是增加了滚动条、
![image](https://user-images.githubusercontent.com/62057975/192707638-462d2865-5580-4596-868f-f32de6dbf52b.png)

**Comment by Js-Man-H5** [comment]
![image](https://user-images.githubusercontent.com/62057975/192708610-766d082f-2109-46cb-85d6-a69501774a40.png)

**Comment by lxfu1** [comment]
这个先上层实现一下：
```tsx
import useResizeAware from 'react-resize-aware';

export const demo = () => {
  const [resizeListener] = useResizeAware();
  
  return  <div >
              {resizeListener}
              <DecompositionTreeGraph {...config} />
            </div>
}

```
