### ISSUE TITLE
🐛[BUG] 折线图 point与animation有冲突

### ISSUE THREAD

**Issue by Rarchers** [ant-design/ant-design-charts#1595]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
使用折线图，在configLine中如果有animation，再添加point会出现element.getTotalLenght的报错
### 🏞 期望结果 [描述你原本期望看到的结果]
解决冲突，可以标注点的同时，也有动画

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
没有复现，提供复现后再打开
```ts
    point: {},
    animation: {
        appear: {
        animation: 'wave-in', // 动画效果
        duration: 5000,  // 动画执行时间
      },
    },
```
