### ISSUE TITLE
🧐[DualAxe Chart Control from EXTERNAL slider]

### ISSUE THREAD

**Issue by leventebg93** [ant-design/ant-design-charts#1596]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

Right now the Chart provides a built in slider option, the problem is that changing the start and end value will yield a buggy result
```
const config = {
    data,
    ....
   //changing the start and end values to a STATE will be buggy
    slider: {
      start: 0.1 ==> startNumber / 100,
      end: 0.5 ==> endNumber / 100,
    },
  };

  return <DualAxes {...config} />;
```

And it behaves like this **(the upper slider is the external one)**
**Problem: the chart doesnt fill out its container horizontally if I use the EXTERNAL SLIDE only if I use the INTERNAL one**
![2_gif](https://user-images.githubusercontent.com/97885059/193232583-8169df59-79bd-4e18-961d-14581e37f70b.gif)

**Question: Is it possible to dynamically control the slider from an external state without bugs? If so How?**
**Alternative question: Can I control multiple graphs with one slider (that use the same horizontal values )**

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
The code shown more elaborately

 ```
const [endNumber, setEndNumber] = useState(100);
const [startNumber, setStartNumber] = useState(0);
```

```
const config = {
    data,
    ....
    slider: {
      start: startNumber / 100,
      end: endNumber / 100,
    },
  };
```

```
<Slider
     range
     defaultValue={[startNumber, endNumber]}
     onChange={(item) => {
       setStartNumber(item[0]);
       setEndNumber(item[1]);
      }}
/>
<DualAxes {...config} className={'chart-view'} />
```

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/489
