### ISSUE TITLE
d3-color vulnerability

### ISSUE THREAD

**Issue by aorioir** [ant-design/ant-design-charts#1597]
Today yarn audit inform that there are a new vulnerability with d3-color library.

![image](https://user-images.githubusercontent.com/114917200/193555988-4ff3c7d6-b32a-4b01-b3d9-586e083cdef3.png)

Could be possible an upgrade ant-design to fix this "high-vulnerability"?

Link to the vulnerability: https://github.com/advisories/GHSA-36jr-mh4h-2g58

**Comment by lilongllong** [comment]
同样遇到这个问题，想询问该如何修复，目前d3-color是被锁死到1版本，希望官方支持下更新。

**Comment by aorioir** [comment]
At the end, I fix it, adding d3-color": "^3.1.0" to package.json resolutions, and adding d3-color to transformIgnorePatterns on jest.config.js
