### ISSUE TITLE
👑 [需求] Worker type module

### ISSUE THREAD

**Issue by lilbumblebear** [ant-design/ant-design-charts#1598]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
As a developer, I would like to be able to use ant charts with edge deployments like Deno. However, Deno does not support "classic" webworkers.  

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
Can the workers be changed to type: module? 

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
https://deno.land/
https://deno.land/manual@v1.26.0/runtime/workers#workers

**Comment by lxfu1** [comment]
V2
