### ISSUE TITLE
🧐How to make the legend not clickable?

### ISSUE THREAD

**Issue by flekpy** [ant-design/ant-design-charts#1599]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

When you click the legend, the graph data is hidden. I need to make it so that when you click on the legend nothing happens, the data does not disappear

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

I expect something similar
  legend: {
    onClick:  false
  }

thank

**Comment by lxfu1** [comment]
```ts
    legend: {
      capture: false
    },
```
