### ISSUE TITLE
👑 [需求]ER模型图

### ISSUE THREAD

**Issue by laosandegudai** [ant-design/ant-design-charts#1603]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
G6的ER模型图

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
我暂时用FlowAnalysisGraph 实现了简单UI展示，但是模型内的item点击事件未能找到获取点击目标item的办法。
![image](https://user-images.githubusercontent.com/17979159/194835250-d175d0c1-3a4f-4fc5-8ff4-48acfead0f34.png)

**Comment by lxfu1** [comment]
```ts
onReady: (graph) => {
  graph.on('node:click', (evt) => {
    console.log(evt, evt.target.get('name'))
  })
}
```

**Comment by laosandegudai** [comment]
> ```ts
> onReady: (graph) => {
>   graph.on('node:click', (evt) => {
>     console.log(evt, evt.target.get('name'))
>   })
> }
> ```

name我能拿到，但是name如何自定义值呢？
`const data = {
    id: 'A0',
    value: {
      title: '订单金额',
      items: [
        {
          text: '3031万',
        },
      ],
    },
    children: [
      {
        id: 'A1',
        value: {
          title: '华南',
          items: [
            {
              text: '1152万',
            },
            {
              text: '占比',
              value: '30%',
            },
          ],
        },
        children: [
          {
            id: 'A11',
            value: {
              title: '广东',
              items: [
                {
                  text: '1152万',
                },
                {
                  text: '占比',
                  value: '30%',
                },
              ],
            },
          },
          {
            id: 'A12',
            value: {
              title: '广西',
              items: [
                {
                  text: '1152万',
                },
                {
                  text: '占比',
                  value: '30%',
                },
              ],
            },
          },
          {
            id: 'A13',
            value: {
              title: '海南',
              items: [
                {
                  text: '1152万',
                },
                {
                  text: '占比',
                  value: '30%',
                },
              ],
            },
          },
        ],
      },
      {
        id: 'A2',
        value: {
          title: '华北',
          items: [
            {
              text: '595万',
            },
            {
              text: '占比',
              value: '30%',
              icon: 'https://gw.alipayobjects.com/zos/antfincdn/iFh9X011qd/7797962c-04b6-4d67-9143-e9d05f9778bf.png',
            },
          ],
        },
      },
    ],
  };`

**Comment by lxfu1** [comment]
text-1-0,  `1-0` 代表 items 的行列

**Comment by laosandegudai** [comment]
> text-1-0, `1-0` 代表 items 的行列

这个我想到用索引了，还以为是歪门邪道用法，还真是正解。多谢了。
