### ISSUE TITLE
🐛[BUG] 辐射树图无法更改文字样式( 参考辐射树图-调整布局)

### ISSUE THREAD

**Issue by hhbusui** [ant-design/ant-design-charts#1604]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
我是使用的官方demo(参考辐射树图-调整布局)，想更改默认的Item文字颜色，通过配置labelCfg不生效

![image](https://user-images.githubusercontent.com/43135111/194834602-c7441474-53d6-4f10-844b-04713e92f1e5.png)

在nodeCfg中配置如下
```
nodeCfg: {
	type: "rect",
	style: {
		stroke: "red"
	},
	labelCfg: () => {
		const style = {
			fontSize: 16,
			fontWeight: 300,
			fill: "red",
			stroke: "red",
			textAlign: "center",
			textBaseline: "middle",
			shadowColor: "white",
			shadowBlur: 10
		};
		return style;
	}
},
```

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
官方demo中修改labelCfg配置
```
nodeCfg: {
	type: "rect",
	style: {
		stroke: "red"
	},
	labelCfg: () => {
		const style = {
			fontSize: 16,
			fontWeight: 300,
			fill: "red",
			stroke: "red",
			textAlign: "center",
			textBaseline: "middle",
			shadowColor: "white",
			shadowBlur: 10
		};
		return style;
	}
},
```

### 🏞 期望结果 [描述你原本期望看到的结果]
文字颜色为红色

### © 版本信息

- ant-design-charts 版本: 最新版
- 浏览器环境  chrome 103
- 开发环境 react18, "@ant-design/graphs": "^1.1.3",

**Comment by lxfu1** [comment]
```ts
labelCfg: {
    style: {
      fill: 'red'
    }
  }
```

**Comment by hhbusui** [comment]
升级"@ant-design/graphs": "^1.1.3"为最新1.3x版本

**Comment by zoro-r** [comment]
1.4的不行啊

**Comment by dayexiaofan** [comment]
这玩意不支持回调吧？ 回调啥也没调出来。官网有写着支持回调
