### ISSUE TITLE
Add title prop for axis in axis based charts

### ISSUE THREAD

**Issue by vipin-msec** [ant-design/ant-design-charts#1605]
Currently only able to add label to axis, I'm using column chart but don't know which data is on which axis by looking only on chart
a title prop should be there to add title of both axis like:
`title:{
xAxis: '',
yAxis:''
}`

**Comment by lxfu1** [comment]
```ts
    xAxis: {
      title: {
        text: '123'
      }
    },
    yAxis: {
      title: {
        text: '123'
      }
    }
```
