### ISSUE TITLE
🧐[问题]针对数据集的回归趋势线支持

### ISSUE THREAD

**Issue by antstudio-git** [ant-design/ant-design-charts#1607]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

针对一组数据，能否绘制多种回归线，反应拟合后的曲线

**Comment by lxfu1** [comment]
https://charts.ant.design/zh/examples/scatter/scatter#line  参考下这个？

**Comment by antstudio-git** [comment]
> https://charts.ant.design/zh/examples/scatter/scatter#line 参考下这个？

嗯，这个的确是趋势线。

我的需求是在一个双轴图中，对柱状数据拟合一个曲线出来，这个用DualAxes能解决么？

**Comment by lxfu1** [comment]
双轴图目前不支持

**Comment by lxfu1** [comment]
[2.0 可以随意添加](https://ant-design-charts-next.antgroup.com/zh/examples/statistics/dual-axes/#dual-multi-line)
