### ISSUE TITLE
柱状折线图图 数据存在连个相同名字的对象展示会乱掉

### ISSUE THREAD

**Issue by goodboygg69** [ant-design/ant-design-charts#1608]
柱状折线混合图 如果存在两个相同名字的数据  柱状图只会展示一个，折线图会乱掉
![WX20221011-165029](https://user-images.githubusercontent.com/110594071/195044369-47cbb9d7-c97c-4701-a808-fc8460351948.png)

**Comment by lxfu1** [comment]
过滤下重复数据或者聚合一下。

**Comment by goodboygg69** [comment]
> 

两个对象是不同的 只是名字相同而已
