### ISSUE TITLE
🧐[问题] 辐射图如何自定义节点 组织架构图中的: customContent

### ISSUE THREAD

**Issue by hhbusui** [ant-design/ant-design-charts#1609]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
辐射图是否支持类似组织架构图中的自定义节点的功能

#### 组织架构图
![image](https://user-images.githubusercontent.com/43135111/195047066-82d6d156-bbbd-4aee-be95-20c55fa6810d.png)

#### 辐射图
![image](https://user-images.githubusercontent.com/43135111/195047316-a292eaa9-4caf-48d4-bc81-553b63ababb7.png)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
无

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
无

**Comment by lxfu1** [comment]
这个对布局影响比较大，暂不支持自定义。

**Comment by hhbusui** [comment]
> 这个对布局影响比较大，暂不支持自定义。

好的，谢谢啦。

**Comment by hhbusui** [comment]
辐射图nodeCfg - type 设置为： modelRect
可以更改前后的图标么？

![image](https://user-images.githubusercontent.com/43135111/195069876-d1c48d2f-7cac-4610-b76e-6911fe8f6093.png)

@lxfu1

**Comment by lxfu1** [comment]
在data里面修改，配置可以参考[G6](https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/built-in/modelRect/#%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E)
```ts
  {
        id: '0',
        label: '0',
        logoIcon: {
          // 是否显示 icon，值为 false 则不渲染 icon
          show: true,
          x: 0,
          y: 0,
          // icon 的地址，字符串类型
          img: 'https://gw.alipayobjects.com/zos/basement_prod/4f81893c-1806-4de4-aff3-9a6b266bc8a2.svg',
          width: 16,
          height: 16,
          // 用于调整图标的左右位置
          offset: 0
        },
        // 节点中表示状态的 icon 配置
        stateIcon: {
          // 是否显示 icon，值为 false 则不渲染 icon
          show: true,
          x: 0,
          y: 0,
          // icon 的地址，字符串类型
          img: 'https://gw.alipayobjects.com/zos/basement_prod/300a2523-67e0-4cbf-9d4a-67c077b40395.svg',
          width: 16,
          height: 16,
          // 用于调整图标的左右位置
          offset: -5
        }
      },
```
