### ISSUE TITLE
tooltip配置问题

### ISSUE THREAD

**Issue by sdhushu** [ant-design/ant-design-charts#1611]
### 💻 复现代码 
            isPercent: true,
            isStack: true,
            tooltip: false

### © 版本信息

- ant-design-charts 版本: [ "@ant-design/charts": "^1.4.2"]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
```ts
tooltip: {
  shared: false,
  customContent: (x, xx) => <div>xxx</div> 
}
```
