### ISSUE TITLE
🐛[BUG]DecompositionTreeGraph 配置 tooltipCfg 时，显示 ReactDOM.render is no longer supported in React 18

### ISSUE THREAD

**Issue by wanghui94** [ant-design/ant-design-charts#1614]
### © 版本信息
"react": "^18.2.0"
- ant-design-charts 版本: [e.g. 0.9.0] "@ant-design/graphs": "^1.3.1"
- 浏览器环境 chrome 106.0.5249.103 
- 开发环境 [e.g. mac OS] mac OS 12.6

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/37385554/195758372-f20dcfa5-dea2-4e54-9330-bacf935d98ef.png">

**Comment by lxfu1** [comment]
这个不影响使用，随后修复。

**Comment by lxfu1** [comment]
1.3.2
