### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by yadprab** [ant-design/ant-design-charts#1616]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

1. is there a way to create a custom legend? 

2. is there a way to control gap between columns? i want to acheive like this

1. 有没有办法创建自定义图例？

2. 有没有办法控制列之间的差距？我想像这样实现

![Screenshot 2022-10-15 at 12-34-26 React Charts Gallery - Simple Histogram](https://user-images.githubusercontent.com/68110471/195974035-5d61266d-9340-4088-8394-ff71da9eaea2.png)

**Comment by lxfu1** [comment]
1. Query issues related to `custom legend`  by keyword
2. Configuration `marginRatio` (suitable for grouped Column)

**Comment by yadprab** [comment]
> 1. Query issues related to `custom legend`  by keyword
> 
>     2. Configuration `marginRatio` (suitable for grouped Column)

thanks
