### ISSUE TITLE
👑 DualAxes 双轴图 右轴刻度显示为百分比，上限100%，下限-100%，如何配置

### ISSUE THREAD

**Issue by Fengfa101126** [ant-design/ant-design-charts#1621]
![image](https://user-images.githubusercontent.com/65803424/196117886-ef9523c8-82a7-454e-b8c3-0c58a543292f.png)

**Comment by lxfu1** [comment]
```ts
 yAxis: {
   [yField]: {
      label: {
        formatter: ()=>{
          return '123'
        }
      }
    },
  },
```

**Comment by Fengfa101126** [comment]
可以啦，谢谢，max min 就可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月17日(星期一) 下午4:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-charts] 👑 DualAxes 双轴图 右轴刻度显示为百分比，上限100%，下限-100%，如何配置 (Issue #1621)





  yAxis: {    [yField]: {       label: {         formatter: ()=&gt;{           return '123'         }       }     },   },
