### ISSUE TITLE
🧐 pie chart slice label not visible 

### ISSUE THREAD

**Issue by vipin-msec** [ant-design/ant-design-charts#1624]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

I'm using Ant Design Donut Chart but if screen size is small the labels shows only ellipsis (like in screenshot) and link size remains same
how should i reduce the size of link in order to show full label.

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
this is when my screen size is between 1400px and 1500px
![image](https://user-images.githubusercontent.com/111870936/196190693-fb7b8c34-8c5c-4076-b3ae-6d4792844243.png)

**Comment by lxfu1** [comment]
Configuration inner and innerRadius .
