### ISSUE TITLE
antd charts graphs

### ISSUE THREAD

**Issue by fangqihao** [ant-design/ant-design-charts#1629]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
关系图中一级节点下有上百个同级子节点，canvas在chrome上渲染时间过长，如何解决

**Comment by lxfu1** [comment]
共计多少个节点？

**Comment by lxfu1** [comment]
log看下是不是重复渲染了，我测试了3000节点，还算流畅，如果还有问题，建议提供个复现demo。

**Comment by fangqihao** [comment]
不是重复渲染，同一级的数量多于200条，导致canvas渲染宽度很长才变得卡顿，会不会这个原因呢
