### ISSUE TITLE
🧐[问题] 双折线 多折现如何配置不同折现的 tooltip formatter 格式呢

### ISSUE THREAD

**Issue by xuoutput** [ant-design/ant-design-charts#1631]
直接写 formatter 不好控制收到的值, 会收到 2 个
<img width="683" alt="image" src="https://user-images.githubusercontent.com/16385443/196390208-a1cb9465-f8e0-4f00-8495-5f7ccb281323.png">
如果按照 yAxis 这样配置, 好像在 tooltip 这里不支持
<img width="565" alt="image" src="https://user-images.githubusercontent.com/16385443/196390341-cdd692d1-4b0e-41c3-8893-828d8affe6ec.png">

**Comment by xuoutput** [comment]
看起来得用 customContent 自定义的亚子

**Comment by lxfu1** [comment]
推荐 customContent ，也可以试试配置 fields ， 在 formatter 里面根据参数返回不同的值。
