### ISSUE TITLE
这个如何配合一起使用

### ISSUE THREAD

**Issue by Fengfa101126** [ant-design/ant-design-charts#1632]
![image](https://user-images.githubusercontent.com/65803424/196648152-b36b939a-b868-474a-8893-65672889e7e5.png)

**Comment by lxfu1** [comment]
`fields` 里面设置的字段，会在 formatter、 customContent 等回调中作为参数出入。

**Comment by Fengfa101126** [comment]
必须是回调的方式么？看了下formatter不支持多字段，customContent 接收的参数有那几个呢？
