### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by 9527jfLi** [ant-design/ant-design-charts#1634]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
Ant Design 里面的Table组件中那个虚拟列表功能能不能优化一下，目前用起来太麻烦对于自定义功能表格似乎不能用

**Comment by 9527jfLi** [comment]
表格中有 输入框 下拉框 多选框 且不能有分页，数据多是情况下会很卡

**Comment by lxfu1** [comment]
这里 https://github.com/ant-design/ant-design/issues
