### ISSUE TITLE
How to customize column colors and column strokes from component data? 🧐[问题]

### ISSUE THREAD

**Issue by vovajr11** [ant-design/ant-design-charts#1636]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
I get the column and border color from the data. I need to custom style each column
How do I configure this?

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
I did only for the color of the column
https://codesandbox.io/s/busy-resonance-c0xhy2?file=/index.js

**Comment by lxfu1** [comment]
```ts
 columnStyle: (arg)=> {
      return {
        stroke: 'red',
        fill: 'yellow'
      }
    },
```

**Comment by vovajr11** [comment]
@lxfu1 Hi) thanks for the answer but I don't need a static color.
I want to take the column and border color from the data

```js
 columnStyle: (arg)=> {
      return {
        stroke: arg.stroke,
        fill: arg.bgColor
      }
    },
```
How do i make this configuration?

**Comment by lxfu1** [comment]
```ts
rawFields: ['xxx','stroke', 'bgColor']
```
