### ISSUE TITLE
🐛[BUG]  柱线混合图里，以时间为横轴，中间某些类型某个时间没有数据，就会错乱

### ISSUE THREAD

**Issue by Fengfa101126** [ant-design/ant-design-charts#1637]
![image](https://user-images.githubusercontent.com/65803424/197986189-ad9d00d0-6c5c-4b46-be23-b4a86dc641c7.png)
数据格式 必须严格按照时间 1-12月这样排么

**Comment by lxfu1** [comment]
你数据有问题吧？ 或者设置 xAxis[filed].type 看看

**Comment by Fengfa101126** [comment]
我在 AntV 给的例子里试了下，如果本来数据 是连贯的 从1月到12月，把其中一个 类型的数据 删掉一个月， 就会出现排列乱掉的情况，有个疑问:   是不是 数据就应该是 连贯的，不能断？

**Comment by Fengfa101126** [comment]
![Uploading image.png…]()
 const uvBillData = [
    {
      time: '2019-03',
      value: 350,
      type: 'uv',
    },
    // {
    //   time: '2019-04',
    //   value: 900,
    //   type: 'uv',
    // },
    {
      time: '2019-05',
      value: 300,
      type: 'uv',
    },
    {
      time: '2019-06',
      value: 450,
      type: 'uv',
    },
    {
      time: '2019-07',
      value: 470,
      type: 'uv',
    },
    {
      time: '2019-03',
      value: 220,
      type: 'bill',
    },
    {
      time: '2019-04',
      value: 300,
      type: 'bill',
    },
    {
      time: '2019-05',
      value: 250,
      type: 'bill',
    },
    {
      time: '2019-06',
      value: 220,
      type: 'bill',
    },
    {
      time: '2019-07',
      value: 362,
      type: 'bill',
    },
  ];
  const transformData = [
    {
      time: '2019-03',
      count: 800,
    },
    {
      time: '2019-04',
      count: 600,
    },
    {
      time: '2019-05',
      count: 400,
    },
    {
      time: '2019-06',
      count: 380,
    },
    {
      time: '2019-07',
      count: 220,
    },
  ];

**Comment by Fengfa101126** [comment]
![image](https://user-images.githubusercontent.com/65803424/198173307-5ac8659a-1817-48df-b610-2ccfef03363b.png)

**Comment by lxfu1** [comment]
提供一下整体配置，大概率是xAxis.type配置导致的

**Comment by lxfu1** [comment]
双轴图的 xAxis 取决于第一份数据，需要补充一下。
