### ISSUE TITLE
🐛[BUG] onAddEdge和onAddNode无法更新useState定义的变量，只能获取初始赋予的值

### ISSUE THREAD

**Issue by Choi-Keith** [ant-design/ant-design-charts#1638]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
使用flowchart@1.2.1版本，onAddEdge和onAddNode无法更新useState定义的变量，只能获取初始赋予的值

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

<img width="968" alt="企业微信截图_16669512085176" src="https://user-images.githubusercontent.com/39899400/198561656-4719b8bf-b818-4a2f-89f9-3f27c38bef17.png">

<img width="960" alt="企业微信截图_16669513209436" src="https://user-images.githubusercontent.com/39899400/198561687-965895d3-ad6c-4752-b530-a140d931cc20.png">

### 🏞 期望结果 [描述你原本期望看到的结果]

希望可以更新useState的值，并且同步useState的值

### © 版本信息

- ant-design-charts 版本: 1.2.1
- 浏览器环境: https://charts.ant.design/en/examples/flowchart/basic#basic
- 开发环境 : windows

**Comment by lxfu1** [comment]
```ts
const countRef = React.useRef(null);
countRef.current = count;

onAddEdge: () => countRef.current 
```
