### ISSUE TITLE
👑 [需求]来源去向图中怎么显示tooltip？

### ISSUE THREAD

**Issue by smancang** [ant-design/ant-design-charts#1639]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
https://charts.ant.design/zh/examples/relation-graph/flow-analysis-graph#custom
这里来源去向图中，有些文字太长，需要省略号裁剪，但是需要鼠标移动上去后显示完整详细信息。

请问该怎么做？

**Comment by lxfu1** [comment]
```td
    tooltipCfg: {
      show: true,
      customContent: () => <div>123</div>
    },
```
