### ISSUE TITLE
🧐How add multi yAxis on Line chart?

### ISSUE THREAD

**Issue by Aspedm** [ant-design/ant-design-charts#164]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

In chart.js we can add n yAxis on left or right side. But how make it with antd charts?
I finded DualLine component in documentations, but google translate is poor or this component can't render yAxis on one side.

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
no

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
Chart.js: http://www.nsfpic.com/data/qf/qfmj7q/chart-js.png
Ant-design chart: http://www.nsfpic.com/data/qf/qfmj6r/antd-chart.png

**Comment by lxfu1** [comment]
暂时不支持。

**Comment by Aspedm** [comment]
Thx. it's sadly.
