### ISSUE TITLE
🐛[BUG] legend item tooltip does'nt hides after mouse leave  图例项目工具提示在鼠标离开后不会隐藏

### ISSUE THREAD

**Issue by yadprab** [ant-design/ant-design-charts#1640]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![Screenshot 2022-11-01 at 15-38-13 React App](https://user-images.githubusercontent.com/68110471/199211888-38d92220-88f2-4c3b-864e-6198d4f0a358.png)

Problem:

when I give width to the legend item it truncates an ellipsis and shows the tooltip. this tooltip is never set to visibility hidden after the mouse leaves it happens only in the renderer **SVG**.  And has the same class name as the chart tooltip 

 suggestions
1. either show the chart tooltip while hovering over the legend item 
2. or provide customization for the legend tooltip with different class name

问题：

当我为图例项指定宽度时，它会截断省略号并显示工具提示。此工具提示永远不会设置为鼠标离开后隐藏的可见性，它仅在渲染器**SVG**中发生。并且具有与图表工具提示相同的类名

 建议
1. 将鼠标悬停在图例项上时显示图表工具提示
2.或为不同类名的图例工具提示提供自定义

code: [url](https://github.com/yadprab/my-app/tree/master/src/Chart)
live site: [live](https://my-app-nine-bay.vercel.app/)

https://user-images.githubusercontent.com/68110471/199215322-414984f1-42d8-437e-ae70-f04b515f74f9.mp4

**Comment by lxfu1** [comment]
`renderer: 'canvas'` ?

**Comment by yadprab** [comment]
> `renderer: 'canvas'` ?
> 
> There should be some problems with svg mode.


when I give canvas mode chart color is only black it doesn't takes the value form the color array i gave
