### ISSUE TITLE
分组堆叠柱状图的tooptip.customItems失效🐛[BUG]

### ISSUE THREAD

**Issue by zhangmingzhen2netease** [ant-design/ant-design-charts#1642]
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://codesandbox.io/embed/zen-resonance-i8keuc?fontsize=14&hidenavigation=1&theme=dark

### 🏞 期望结果 [描述你原本期望看到的结果]
应该要能执行customItems，打印内容

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/embed/zen-resonance-i8keuc?fontsize=14&hidenavigation=1&theme=dark
### © 版本信息

- ant-design-charts 版本: [e.g. 1.4.2]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/109211399/199676105-20e0cdc1-af15-49ab-b895-e5d298017ba5.png)

**Comment by lxfu1** [comment]
[底层](https://github.com/antvis/G2Plot/blob/master/src/plots/column/adaptor.ts#L253)有覆盖，先用 customContent 吧！

**Comment by zhangmingzhen2netease** [comment]
好的 感谢
