### ISSUE TITLE
🐛[BUG]柱线混合图纵轴最大值最小值不准确

### ISSUE THREAD

**Issue by hang1017** [ant-design/ant-design-charts#1655]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

 "@ant-design/charts": "^1.4.2",

使用【antdesign - charts】DualAxes 柱线混合图的组件。
给y 左轴配置最大值时，没有在y轴上增加最大值的刻度线。

举例说明：
 max:11, min:1, tickInterval:2  最大值为11，最小值为1，间隔2。
是否要从1 开始然后3，5，7，9，11 的展示纵轴的刻度线

![image](https://user-images.githubusercontent.com/48704410/200526582-9f9747ac-2ac4-4938-992f-2e1ef61e2481.png)

复现demo 如下：

pnpm i 
pnpm start

访问：http://localhost:8000/#/hisLine

[maps.zip](https://github.com/ant-design/ant-design-charts/files/9959617/maps.zip)

**Comment by lxfu1** [comment]
刻度有一定的计算规则，最大值不一定会绘制刻度，可以通过 type指定， eg: `yAxis[yField].type: 'pow' | 'log'`
