### ISSUE TITLE
🧐How do you show an empty chart if you have no data?

### ISSUE THREAD

**Issue by leventebg93** [ant-design/ant-design-charts#1656]
### 🧐 If you have no data you theres no way to show the chart

How can you do that with eg.: a dual axe dual line chart?
It shouldnt show any lines but just the chart with the yAxis showing the units on both sides

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
Here I provide sample data so the chart doesnt error out
https://stackblitz.com/edit/react-pvog1z?file=index.js

But how can you do it without data?

**Comment by lxfu1** [comment]
```tsx
  if(!data.length){
    return 'No data'
  }
 return <DualAxes {...config} />;
```

**Comment by leventebg93** [comment]
@lxfu1 
Youre not showing an empty chart 
You're just showing a text saying "No Data"

Which is not the same at all
