### ISSUE TITLE
辅助线设置超过y轴最大值不展示，如果能让辅助线展示出来

### ISSUE THREAD

**Issue by white-Hang** [ant-design/ant-design-charts#1657]
![image](https://user-images.githubusercontent.com/54161396/200711023-ad3ece13-8866-443f-88f6-246f3b27bd97.png)
设置的辅助线超过了最大值，就不在图上展示了，有没有大佬有解决办法啊

**Comment by lxfu1** [comment]
可以设置下`yAxis.max: 3000`
