### ISSUE TITLE
 带有滚动条的图形，点击导出图片，导出的图片数据不完整，只有可视区域的，如果将所有的数据都导出到图片上🧐[问题]

### ISSUE THREAD

**Issue by white-Hang** [ant-design/ant-design-charts#1658]
![image](https://user-images.githubusercontent.com/54161396/200714708-00a9943d-6e03-4388-a6a7-f09ad7e993ef.png)
希望能将所有的数据都导出，有大佬知道吗？

**Comment by lxfu1** [comment]
导出是导出当前画布，滚动条会过滤数据，导出前去掉滚动条或者调整滚动条的range
