### ISSUE TITLE
Sankey Chart: Disable Nodes onClick

### ISSUE THREAD

**Issue by CarmineBruno** [ant-design/ant-design-charts#1660]
Hi everyone,
I was wondering if there was an option to disable nodes on click in a Sankey Chart (see image below).

![image](https://user-images.githubusercontent.com/70442479/200863514-b35d9bbe-1608-4904-a831-d99b2ef8d8be.png)

Is this feature available?

I was looking at this field, but it doesn't seem to work 
![image](https://user-images.githubusercontent.com/70442479/200864431-a16c8b09-7bd2-4429-a6b9-8ba159673c4e.png)

**Comment by lxfu1** [comment]
No, you just don't need to bind the click event.
