### ISSUE TITLE
堆叠条形图加了鼠标滚动滚动以后图表消失

### ISSUE THREAD

**Issue by sdhushu** [ant-design/ant-design-charts#1664]
### 🧐 
堆叠条形图加了鼠标滚动滚动以后图表消失，上下左右都会触发内部事件

### 💻 
(https://codesandbox.io/s/frosty-nash-75onoi?file=/index.js)

### 
滚动前：
![image](https://user-images.githubusercontent.com/54340686/201027394-1e60fb16-572e-41ff-8bbb-c3d1cd728e6c.png)
滚动后：
![image](https://user-images.githubusercontent.com/54340686/201027506-4156a537-99af-40f6-9ea9-de3f0fc8a114.png)

**Comment by lxfu1** [comment]
V2 `scrollbar: {y: {}}`
