### ISSUE TITLE
🧐[问题]显示问题

### ISSUE THREAD

**Issue by 2020mythww** [ant-design/ant-design-charts#1665]
下图是我在扩展屏上的截图，可以正常显示1.
![image](https://user-images.githubusercontent.com/67315275/201040225-0e41cf1c-2696-466d-8671-9f6c971b168a.png)
这张图是我在笔记本上的截图，屏幕变小，1就显示不出来了
![image](https://user-images.githubusercontent.com/67315275/201040537-d22d194c-6243-4d08-9218-33a35ddd2951.png)

然后我考虑到自己电脑屏幕有125%的缩放，换成100%又可以显示了，那么怎么样解决这个问题，让他显示呢

**Comment by lxfu1** [comment]
`label.layout: []`

**Comment by 2020mythww** [comment]
这是我的配置，图表类型是柱状图。
![image](https://user-images.githubusercontent.com/67315275/201042542-4774b9c2-9e1e-4d67-8cd2-90d8560b0e7e.png)
然后加上你的配置后，页面是这个效果了
![image](https://user-images.githubusercontent.com/67315275/201042889-6d91d8d4-5d49-48df-be23-30680650692a.png)

**Comment by lxfu1** [comment]
默认情况下，放不下的label会被自动隐藏，可以仔细看下 label.layout.
```ts
label: {
  position: 'middle',
  layout: []
}
```

**Comment by 2020mythww** [comment]
好的，谢谢大哥
