### ISSUE TITLE
使用了customContent自定义的tooltip,，并设置enterable为true，鼠标移入tooltip再快速移出，tooltip不消失🧐[问题]

### ISSUE THREAD

**Issue by white-Hang** [ant-design/ant-design-charts#1666]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/54161396/201085364-d8588836-8673-4b81-b30b-491eec83e6be.png)

**Comment by lxfu1** [comment]
太快可能有点反应不过来，建议在 customContent 绑定一个鼠标移除事件，鼠标移除的时候调用 plot 的 hideTooltip({x,y})

**Comment by bbhu-y** [comment]
![image](https://user-images.githubusercontent.com/38289190/210776686-6fdd8d38-0937-4455-9a8d-08de3acd39c4.png)
![image](https://user-images.githubusercontent.com/38289190/210776703-ba214a3e-0a0f-43ed-9104-74d31a01d8b1.png)
这样就可以解决

**Comment by bbhu-y** [comment]
![image](https://user-images.githubusercontent.com/38289190/210782171-f36e19f2-e655-4102-87c9-77e9add2a50a.png)
确实可以解决
