### ISSUE TITLE
🧐[问题] How to control legend filter using a button outside of ant design chart?

### ISSUE THREAD

**Issue by tacmoktan** [ant-design/ant-design-charts#1667]
For e.g: trigger the **Liquid fuel** legend filter from a button outside of chart.
![image](https://user-images.githubusercontent.com/36654683/201155505-d601001f-df73-4c4a-8a48-ee67988388e9.png)

**Comment by lxfu1** [comment]
`legend: false` and find `custom legend` in issues.
