### ISSUE TITLE
🧐[问题]如何联动两个Pie图进行selected联动

### ISSUE THREAD

**Issue by MuYuCat** [ant-design/ant-design-charts#1668]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
现有需求需要两个Pie图共用一个Legend，所以使用Mix进行View联动，现在有两个问题在文档中没有查阅到
1. 如何在初始onReady时对两个pie图进行setState('selected',)赋值？
如示例代码，但是运行无效
2. 如何点击一个Pie图之后，两个Pie图同时达到selected的状态？

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
import React, { useState } from 'react';
import { Mix, G2 } from '@ant-design/charts';
import { mockData } from '../mixEcharts/config';

const Index: React.FC = () => {
  const [data] = useState(mockData);
  const config = {
    // 关闭 chart 上的 tooltip，子 view 开启 tooltip
    tooltip: false,
    legend: {
      layout: 'horizontal',
      position: 'bottom',
    },
    plots: [
      {
        type: 'pie',
        region: {
          start: {
            x: 0,
            y: 0,
          },
          end: {
            x: 0.45,
            y: 1,
          },
        },
        options: {
          data: data.pie1,
          angleField: 'bill',
          colorField: 'area',
          radius: 1,
          innerRadius: 0.6,
          tooltip: {
            showMarkers: false,
          },
          label: {
            type: 'inner',
            content: '',
          },
          interactions: [
            {
              type: 'element-single-selected',
            },
            {
              type: 'element-single-active',
            },
            {
              type: 'element-single-highlight',
            },
            {
              type: 'association-try-select',
            },
          ],
        },
      },
      {
        type: 'pie',
        region: {
          start: {
            x: 0.55,
            y: 0,
          },
          end: {
            x: 1,
            y: 1,
          },
        },
        options: {
          data: data.pie2,
          radius: 1,
          innerRadius: 0.6,
          angleField: 'value',
          colorField: 'area',
          label: {
            type: 'inner',
            content: '',
          },
          tooltip: {
            showMarkers: false,
          },
          interactions: [
            {
              type: 'element-single-selected',
            },
            {
              type: 'element-single-active',
            },
            {
              type: 'element-single-highlight',
            },
            {
              type: 'association-try-select',
            },
          ],
        },
      },
    ],
    // 初始selected第一个类目
    onReady: (piePlot: any) => {
      //  动态调整即可
      console.log('piePlot', piePlot);
      piePlot.setState('selected', (item: any) => {
        console.log('item：any', item);
        return item.type === '分类一';
      });
    },
  };
  return <Mix {...(config as any)} />;
};
export default Index;

**Comment by lxfu1** [comment]
绑定hover事件，同时设置2个plot的state，伪代码：
```ts
onReady: (plot) => {
  plot.on('element:hover', (e) => {
    const  {data} = e.data;
    view1.setState('selected', () => true | false)
    view2.setState('selected', () => true | false)
  })
}
```
