### ISSUE TITLE
🐛funnel控制台报错Cannot read properties of undefined (reading 'length')    

### ISSUE THREAD

**Issue by xiaoCue** [ant-design/ant-design-charts#1669]
### 🐛 bug 描述
container.js:373 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at ./node_modules/_@antv_g-base@0.5.11@@antv/g-base/esm/abstract/container.js.Container.getCount
### 📷 复现步骤 
漏斗图funnel ，uselayoutEffect中使用chart.changeSize
### 🏞 期望结果
控制台无报错
### © 版本信息
@ant-design/charts@1.3.5
@ant-design/plots@1.2.2

**Comment by AllenWUu** [comment]
+1

**Comment by FuncWei** [comment]
去掉renderer="svg"不会报这个错

**Comment by lxfu1** [comment]
建议不要使用`renderer: "svg"`

**Comment by xiaoCue** [comment]
没有使用renderer: "svg"
