### ISSUE TITLE
🧐[问题]像疫情这种每日累加的折线图,目前该怎么实现呢?

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-charts#167]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/15940920/91382257-ea5f3f00-e85b-11ea-889e-0412399c0359.png)

后端返回的数据,是每日新增的.

要实现这种递增的折线图,该怎么做呢,求思路~~

**Comment by lxfu1** [comment]
让后端按日期期间返回全量数据呗。

**Comment by l745230** [comment]
@lxfu1 后端不给,说这个是前端做的...

**Comment by lxfu1** [comment]
@l745230 怼他啊

**Comment by afc163** [comment]
非图表 bug 或 feature request 不要这里询问。
