### ISSUE TITLE
Elements small height problem, impossible interaction "element-selected"

### ISSUE THREAD

**Issue by Valtas** [ant-design/ant-design-charts#1671]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Interaction "element-selected". I can't select an element on a diagram of type "Column". In the diagram, many elements are too small in height, or completely invisible.

I've read the documentation and googled it many times, however, I couldn't set the element's minimum height (:

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
CodeSanbox example - https://codesandbox.io/s/interaction-element-selected-elements-small-height-problem-ihkszt

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
"@ant-design/charts": "1.2.14",
"@ant-design/plots": "1.2.2"

![Shot 2022-11-13 at 23 39 15](https://user-images.githubusercontent.com/14878109/201543604-f3dba5e0-e71e-4526-8dfd-ef58c3c374e8.png)

**Comment by lxfu1** [comment]
Min height is not supported，like this.
```ts
      // interactions: [{ type: "element-selected" }],
      state: {
        selected: {
          style: { fill: "#258c60" }
        }
      },
      onReady: (plot) => {
        plot.on("axis-label:click", (e) => {
          const text = e.target.attr('text');
          plot.setState('selected', (item) => item['城市'] === text)
        });
        plot.on("element:click", (e) => {
          const {data} = e.data;
          plot.setState('selected', (item) => item === data)
        });
      }
```

**Comment by Valtas** [comment]
thanks 👍, select element works, tell me please how to do deselect element?

**Comment by lxfu1** [comment]
> ### 🧐 问题描述 [详细地描述问题，让大家都能理解]
> Interaction "element-selected". I can't select an element on a diagram of type "Column". In the diagram, many elements are too small in height, or completely invisible.
> 
> I've read the documentation and googled it many times, however, I couldn't set the element's minimum height (:
> 
> ### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
> CodeSanbox example - https://codesandbox.io/s/interaction-element-selected-elements-small-height-problem-ihkszt
> 
> ### 🚑 其他信息 [如截图等其他信息可以贴在这里]
> "@ant-design/charts": "1.2.14", "@ant-design/plots": "1.2.2"
> 
> ![Shot 2022-11-13 at 23 39 15](https://user-images.githubusercontent.com/14878109/201543604-f3dba5e0-e71e-4526-8dfd-ef58c3c374e8.png)

plot.setState('selected', (item) => true, false)

**Comment by lxfu1** [comment]
> thanks 👍, select element works, tell me please how to do deselect element?

plot.setState('selected', (item) => true, false)

**Comment by Valtas** [comment]
> plot.setState('selected', (item) => true, false)
unfortunately that didn't fix the problem (:

CodeSanbox example - https://codesandbox.io/s/interaction-element-selected-elements-small-height-problem-ihkszt

![Shot 2022-11-14 at 14 15 16](https://user-images.githubusercontent.com/14878109/201647360-a4dba6ec-bf31-4fc0-84e1-a582dfbbcdf5.png)

**Comment by lxfu1** [comment]
```ts
      onReady: (plot) => {
        const setState = (text) => {
          // reset
          plot.setState("selected", (item) => true, false);
          plot.setState("selected", (item) => item["城市"] === text);
        }
        plot.on("axis-label:click", (e) => {
          setState(e.target.attr("text"));
        });
        plot.on("element:click", (e) => {
          const { data } = e.data;
          setState(data['城市']);
        });
      }
```

**Comment by Valtas** [comment]
thanks 👍, but this solution does not allow multiple selections, nor does it completely remove the selection.

I managed to overcome these moments:
```
onReady: (plot) => {
  const toggleElementState = (text) => {
    const selectedElements = plot.getStates();
    // reset states
    plot.setState("selected", () => true, false);
    // set new states
    plot.setState("selected", (item) => {
      const prevState = selectedElements
        .filter((el) => el.state === "selected")
        .some((el) => el.data["城市"] === item["城市"]);
      return item["城市"] === text ? !prevState : prevState;
    });
  };
  plot.on("axis-label:click", (e) => {
    toggleElementState(e.target.attr("text"));
  });
  plot.on("element:click", (e) => {
    const { data } = e.data;
    toggleElementState(data["城市"]);
  });
}
```

CodeSanbox example - https://codesandbox.io/s/interaction-element-selected-elements-small-height-problem-ihkszt

However, there is one undesirable moment:
```
// reset states
plot.setState("selected", () => true, false);
```

because of this line of code, it visually removes the selection completely and then installs it. This can probably be improved by turning off the animation.
