### ISSUE TITLE
🐛[BUG] onEvent回调状态会被缓存

### ISSUE THREAD

**Issue by xlz-cloud** [ant-design/ant-design-charts#1672]
### © 版本信息

- ant-design-charts 版本: 1.4.2
- 浏览器环境
- 开发环境 [windows]

**Comment by lxfu1** [comment]
用 useRef 解决一下 。

**Comment by lxfu1** [comment]
const state = React.useRef();
state.current = data;

onEvent((), ()=> state.current)
