### ISSUE TITLE
🧐[问题] legend有没有类似selectedMode: false的属性？

### ISSUE THREAD

**Issue by deviluncle** [ant-design/ant-design-charts#1673]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
目前遇到的需求是legend不允许点击  请问有没有类似echarts的selectedMode: false的属性？

**Comment by lxfu1** [comment]
目前没有，可以用`legend.items: [{id, name}]` 去模拟实现，只有id和原始数据不一致，就没有关闭功能。

**Comment by surongm** [comment]
> 目前没有，可以用`legend.items: [{id, name}]` 去模拟实现，只有id和原始数据不一致，就没有关闭功能。

用items也不行 如何实现图例关闭功能呢
  selectedMode:false,
 selected: { '分类一': true}
都不行
![image](https://github.com/ant-design/ant-design-charts/assets/41141486/97513dd3-0020-4bbf-ab61-72a1542d3f46)

在线案例
https://codesandbox.io/s/great-dust-4hmdiv
