### ISSUE TITLE
🐛[BUG] DataMarker Annotation - line marker style attribute not working

### ISSUE THREAD

**Issue by hiepnc-ghub** [ant-design/ant-design-charts#1674]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
I try to style the line marker, follow as the document. But the style attribute not working 
![image](https://user-images.githubusercontent.com/70257033/201615119-d3f1ac3f-4e3a-4e70-bf74-8ccf7cfa0c9d.png)

I try to style for point, it worked. 
but the line style isn't.

### 🏞 期望结果 [描述你原本期望看到的结果]
I expect the line can be config width and color like this 
![image](https://user-images.githubusercontent.com/70257033/201617140-dbea8278-d928-4516-b629-966c9349d544.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
Im config the annotation with type "dataMarker" as document. the line show up but cant styling it. 

`  let annotations: any = [
    {
      type: "dataMarker",
      position: [8.75, 1000],
      point: null,
      line: {
        length: 351,
        style: {
          fill: "#FD2D01",
          color: "#FD2D01",
          background: "#FD2D01",
          width: '2px'
        },
      },
    },
  ]; `
  
  `  
  const config = {
    data: currentData,
    xField: "days",
    yField: "value",
    xAxis: {
      range: [0, 1],
      title: {
        text: "Time,
        style: {
          fontSize: 12,
          fill: "#74788D",
        },
      },
    },
    yAxis: {
      title: {
        text: "No.",
        style: {
          fontSize: 12,
          fill: "#74788D",
        },
      },
    },
    smooth: true,
    annotations,
  };
  `

### © 版本信息

- ant-design-charts 版本: ^1.4.2
- 浏览器环境: chrome, etc
- 开发环境 [e.g. mac OS]: ubuntu, window, etc

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
Actual: 
![image](https://user-images.githubusercontent.com/70257033/201617467-86ca7db6-4b35-44fe-9022-4d3824121e2c.png)

**Comment by lxfu1** [comment]
```ts
  style: {
    stroke: 'red'
 },
```

**Comment by hiepnc-ghub** [comment]
> 

thank you, that worked
