### ISSUE TITLE
🧐[问题] 柱状图想要stroke的颜色和fill的颜色保持一致应该怎么设置

### ISSUE THREAD

**Issue by Dawnwangzi** [ant-design/ant-design-charts#1675]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
柱状图，我在config里设置了selected，active，inactive状态的样式。
想要stroke的颜色和fill的颜色保持一致应该怎么设置。fill的颜色就是主题中的颜色，是不固定的。
需要有stroke 不想把stoke设成null

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

state: {
          selected: {
            style: {
              fill: '#0FE980',
              // stroke: null,
              opacity: 1,
              stokeOpacity: 0.1,
              fillOpacity: 1,
            },
          },
          active: {
            style: {
              // stroke: null,
              opacity: 1,
              stokeOpacity: 0.1,
              fillOpacity: 1,
            },
          },
          inactive: {
            style: {
              // stroke: null,
              opacity: 1,
              stokeOpacity: 0.1,
              fillOpacity: 0.2,
            },
          },
        },

**Comment by lxfu1** [comment]
目前 state 不支持动态配置。

**Comment by josecao** [comment]
Hi @lxfu1 ,  is it supported in v2? Thank you!
