### ISSUE TITLE
ant-design-charts能用在移动端吗？有没有什么兼容问题？🧐[问题]

### ISSUE THREAD

**Issue by white-Hang** [ant-design/ant-design-charts#1677]

**Comment by lxfu1** [comment]
移动端没有做个特殊处理，推荐使用 @atnv/f2 噢

**Comment by white-Hang** [comment]
f2很多功能不完善，产品又要求web端和移动端必须一样，antdCharts用在移动端应该也能用吧

**Comment by white-Hang** [comment]
> 移动端没有做个特殊处理，推荐使用 @atnv/f2 噢

f2的问题挺多了，产品又要求web端和移动端必须一样，antdCharts如果用在移动端会有什么大的兼容问题吗？

**Comment by wozien** [comment]
f2 这东西能用？
