### ISSUE TITLE
柱状图的y轴坐标最大值过大，柱子值太小，设置了shared:false,鼠标放上去就没法展示出tooltip了，这怎么解决？🧐[问题]

### ISSUE THREAD

**Issue by white-Hang** [ant-design/ant-design-charts#1678]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/54161396/201875824-668e2c52-8c58-40a3-be39-4a7c523f2908.png)

**Comment by lxfu1** [comment]
[2.0 支持配置最小值](https://ant-design-charts-next.antgroup.com/examples/statistics/column/#column)

style: {minHeight: 10}
