### ISSUE TITLE
在antd的tabs组件中使用两个折线图，其中一个折线图的横线会消失🐛[BUG]

### ISSUE THREAD

**Issue by xiaozheqiu** [ant-design/ant-design-charts#1679]
如题 
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/49509790/201884521-ee08a9f1-985b-4bd2-a15d-4c402f6296b3.png)
![image](https://user-images.githubusercontent.com/49509790/201884561-df52e2fa-3e6d-49f9-805a-845fe2a05693.png)

**Comment by lxfu1** [comment]
数据类型不对吧，yField 必须是 number 类型

**Comment by xiaozheqiu** [comment]
> 

已解决 感谢
