### ISSUE TITLE
🐛[BUG]图表示例点热力图打开报错

### ISSUE THREAD

**Issue by IceLeach** [ant-design/ant-design-charts#1681]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/75960208/202058257-1ebbd76c-9e79-491d-9b3d-3e6c6c5068de.png)
包括杭州房屋交易量、全国交通事故增长率、全球热力、全球热力 3D

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lvisei** [comment]
@lxfu1  是不是改名称 [GeographicHeatmap](https://github.com/ant-design/ant-design-charts/blob/44faebea1a48481b98df56c0f7c80792c358f983/packages/maps/src/components/geographic-heatmap/index.tsx) 了？文档没有同步
