### ISSUE TITLE
🧐[问题] 为什么双折线图不支持向多折线图那样，点击图例，只展示对应的线

### ISSUE THREAD

**Issue by lynnelyin** [ant-design/ant-design-charts#1682]
![image](https://user-images.githubusercontent.com/43037427/202066448-9223524c-0a0f-43d4-84ff-2a081ba44eec.png)
![image](https://user-images.githubusercontent.com/43037427/202066521-c91d85f7-58f2-48b4-890e-d7714fbbc3b5.png)

**Comment by lxfu1** [comment]
双轴图是多个View，目前没有这个功能
