### ISSUE TITLE
Range on every Y axis point.

### ISSUE THREAD

**Issue by kzatin** [ant-design/ant-design-charts#1684]
![WhatsApp Image 2022-11-16 at 11 40 32 AM](https://user-images.githubusercontent.com/65963985/202098507-2b116192-024a-4c59-a38b-0e225711de52.jpeg)
Hi,
I want to get y axis range like the way in image. 
I am not able to find any particular solution in docs. 
Please help

**Comment by lxfu1** [comment]
`yAxis.label.formatter: () => xx` or [Range](https://charts.ant.design/zh/examples/bar/range#basic) ?

**Comment by kzatin** [comment]
> `yAxis.label.formatter: () => xx` or [Range](https://charts.ant.design/zh/examples/bar/range#basic) ?

Hi,
need label same as range shown in image. 
Please elaborate as formatter not working as expected.
