### ISSUE TITLE
分组柱状图设置两条相同的xField和seriesField值相同的数据，柱子和合并在一起，怎么让柱子分开？，如下图所示🧐[问题]

### ISSUE THREAD

**Issue by white-Hang** [ant-design/ant-design-charts#1685]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/54161396/202130274-a41948c2-9ba4-4faf-b4d6-a46b455ef0d0.png)

**Comment by lxfu1** [comment]
数据问题，纠正一下数据。

**Comment by white-Hang** [comment]
> 数据问题，纠正一下数据。

![image](https://user-images.githubusercontent.com/54161396/202370605-0cc85107-cbf3-42d6-bb7e-6250448f17b0.png)
就跟echarts这样，能渲染出完整的不同柱子，而不是合并在一起。
