### ISSUE TITLE
🐛[BUG] 旭日图内圈有时候不显示

### ISSUE THREAD

**Issue by 635936876** [ant-design/ant-design-charts#1688]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
当旭日图value值保留三位小数时,有时候图表内侧会不显示

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
在https://codesandbox.io/s/081r2x?file=/index.js 这个链接, 把内容替换为
`import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Sunburst } from '@ant-design/plots';

const DemoSunburst = () => {
  const config = {
    data: {
      "name": "咖啡产地",
      "children": [
        {
          "name": "非洲",
          "value": 2133,
          "children": [
            {
              "name": "埃塞俄比亚",
              "value": 71.229
            },
            {
              "name": "肯尼亚",
              "value": 2061.771
            },
          ]
        }
      ]
    },
    innerRadius: 0.3,
    interactions: [
      {
        type: 'element-active',
      },
    ],
  };

  return <Sunburst {...config} />;
};

ReactDOM.render(<DemoSunburst />, document.getElementById('container'));
`

**Comment by ai-qing-hai** [comment]
@635936876  不显示是什么意思？ 试试这个？
```
import { Sunburst } from '@ant-design/plots';
import React from 'react';
import ReactDOM from 'react-dom';

const DemoSunburst = () => {
  const config = {
    data: {
      value: {
        "name": "咖啡产地",
        "children": [
          {
            "name": "非洲",
            "value": 2133,
            "children": [
              {
                "name": "埃塞俄比亚",
                "value": 71.229
              },
              {
                "name": "肯尼亚",
                "value": 2061.771
              },
            ]
          }
        ]
      }
    },
    innerRadius: 0.3,
  };
  return <Sunburst {...config} />;
};

ReactDOM.render(<DemoSunburst />, document.getElementById('container'));

```
