### ISSUE TITLE
🐛双轴图的yaxis 不能正常展示

### ISSUE THREAD

**Issue by 980792492** [ant-design/ant-design-charts#1690]
### 🐛 bug 描述
     双轴图的yAxis的刻度 不能 完全 大于渲染的数据，

### 
![image](https://user-images.githubusercontent.com/22511204/202986642-7785816f-7a66-48b3-bfd7-d4f03c09a701.png)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
     期望能够实现 yAxis 和 柱图 一样

**Comment by lxfu1** [comment]
```ts
   yField: ['value', 'value'],
   yAxis: {
     // eg: value
     [yField]: {
        nice: true
      }
    },
```
