### ISSUE TITLE
customHtml属性写html时，气泡提示功能无法显示，能否加一个气泡功能👑 [需求]

### ISSUE THREAD

**Issue by coder-txh** [ant-design/ant-design-charts#1696]

**Comment by beMySun** [comment]
同需要气泡功能， 急 ！

**Comment by lxfu1** [comment]
把`pointer-events: none`覆盖掉，改为 auto。

![image](https://user-images.githubusercontent.com/31396322/204745055-9bcdf635-0c45-4955-baae-db8fc4c7e71d.png)
