### ISSUE TITLE
🧐 Combine multiple maps

### ISSUE THREAD

**Issue by Lc0rE** [ant-design/ant-design-charts#1697]
I noticed that in the latest versions of AntV, we have the option to combine multiple traces through a `Mix` component that takes in input a config object like the following:

```js
config: {
  plots: [...]
}
```

A working example on your documentation: https://codesandbox.io/s/k7jmfu?file=/index.js
![image](https://user-images.githubusercontent.com/7023628/203759692-56100c04-934c-4e88-a205-526d9a428814.png)

I'm trying to achieve the same result through a combination of different map types like I'm doing by using a library like Plot.ly JS (trace1: countries colors, trace2: bubbles):

![image](https://user-images.githubusercontent.com/7023628/203759203-db3639c0-fadc-42bc-9d12-be8500fa819f.png)

Can you please give me some hints if this is possible?

**Comment by Lc0rE** [comment]
I found out that by using L7Plot instead of ant-charts for React, I can use Multiple Layers documented in the library Examples.

**Comment by liho00** [comment]
how can provide example? thank you ser @Lc0rE
