### ISSUE TITLE
可以在柱子顶部自定义显示柱子值的和吗

### ISSUE THREAD

**Issue by 2020mythww** [ant-design/ant-design-charts#1698]
![image](https://user-images.githubusercontent.com/67315275/203922727-eeb2efcd-68d4-4978-bbc2-4cabc57bb404.png)
不如样件准备是是3，1就在顶部显示4。3，1依旧显示

**Comment by lxfu1** [comment]
用 annotations 实现， https://charts.ant.design/zh/examples/component/annotation#text-annotation1
