### ISSUE TITLE
👑 [需求] 双Y轴面积图

### ISSUE THREAD

**Issue by Morphone0429** [ant-design/ant-design-charts#1699]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
如下图 面积图可以支持双Y轴吗? 功能上如双Y轴DualAxes
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
DualAxes
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![20221125-160254](https://user-images.githubusercontent.com/30744484/203931269-bfdd293b-169e-4b5b-82a6-311a207e81f9.jpeg)

**Comment by hx-sea** [comment]
解决了嘛，同样的需求

**Comment by MonsterXue** [comment]
您好，请问如何实现双Y轴柱状图

**Comment by lxfu1** [comment]
2.0 版本支持任意组合， `type: 'area'` 

https://ant-design-charts-next.antgroup.com/zh/examples/statistics/dual-axes/#dual-line
