### ISSUE TITLE
🧐[问题] 如何在迷你环形进度条中间放“65 %”

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design-charts#170]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
 如何在环形进度条中间放“65 %”
如果做不了。怎么在饼状图环形中改成  迷你环形进度条 的样子
Thanks♪(･ω･)ﾉ

**Comment by lxfu1** [comment]
不可，需要的话可以使用 Bar 
```js
 {
  yAxis: {
    visible: false
  },
  xAxis: {
    visible: false
  }, 
  barSize: 15,
  label: {
    visible: true,
    position: 'center',
    formatter: (v) =>'64%',
  }
}
```

**Comment by lxfu1** [comment]
不可以
1、业务层定位一个上去 
2、使用 Donut 模拟一下

**Comment by lxfu1** [comment]
Donut 模拟
```js
const data = [
  {
    type: '分类一',
    value: 27,
  },
  {
    type: '分类二',
    value: 25,
  },
];

config = {
  ...,
  label: {
    visible: false
  },
  color: ['red', '#ccc'],
  legend: {
    visible: false
  },
}

```

**Comment by k983551019** [comment]
> Donut 模拟
> 
> ```js
> const data = [
>   {
>     type: '分类一',
>     value: 27,
>   },
>   {
>     type: '分类二',
>     value: 25,
>   },
> ];
> 
> config = {
>   ...,
>   label: {
>     visible: false
>   },
>   color: ['red', '#ccc'],
>   legend: {
>     visible: false
>   },
> }
> ```

**Comment by lxfu1** [comment]
htmlContent: () =>  '123
