### ISSUE TITLE
🐛[BUG]  双轴折线图，左侧数据为空，右侧数据图表没有显示刻度线。

### ISSUE THREAD

**Issue by 21haoxingxiu** [ant-design/ant-design-charts#1702]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
如题
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
线上demo：  https://charts.ant.design/zh/examples/dual-axes/dual-line#dual-line
如图； 
![image](https://user-images.githubusercontent.com/20453074/204205214-084fa05f-540e-4bb8-873a-3201d0d79c52.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
都有刻度线
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
双轴图的刻度以及axis是依赖左侧数据的

**Comment by 21haoxingxiu** [comment]
> 

现在有什么解决方案吗，我目前的需求是切换只看百分比的数据， 这个需求还是比较常见的。

**Comment by lxfu1** [comment]
> > 
> 
> 现在有什么解决方案吗，我目前的需求是切换只看百分比的数据， 这个需求还是比较常见的。

先做个检测，左侧数据为空时把右侧数据放到左侧？

**Comment by 21haoxingxiu** [comment]
> > > 
> > 
> > 
> > 现在有什么解决方案吗，我目前的需求是切换只看百分比的数据， 这个需求还是比较常见的。
> 
> 先做个检测，左侧数据为空时把右侧数据放到左侧？

我目前也只能想到这样，希望能说服产品 0-0

**Comment by lxfu1** [comment]
这个 2.0 会支持
