### ISSUE TITLE
🐛[BUG] 饼图和环图设置 `width` 后初始渲染有异常

### ISSUE THREAD

**Issue by JackLiR8** [ant-design/ant-design-charts#1704]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
饼图设置了 `width` 后初始渲染异常

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
设置 `width`, 或者同时设置 `width` 和 `height`。(只设置 `height` 渲染正常)

### 🏞 期望结果 [描述你原本期望看到的结果]
配置 `width` 后渲染正常

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://stackblitz.com/edit/react-5mpvju?file=index.js
### © 版本信息

- ant-design-charts 版本: [@ant-design/plots 1.2.2]
- 浏览器环境 [Chrome]
- 开发环境 [mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![pie-error](https://user-images.githubusercontent.com/45257542/204422383-27a4b70c-af81-4e42-b132-57a6fd81c5c5.png)

**Comment by lxfu1** [comment]
需要同时设置，或者使用默认高度，如下。
```ts
   autoFit: false,
```

**Comment by JackLiR8** [comment]
同时设置 `width` 和 `height` 也会出现

**Comment by JackLiR8** [comment]
> 需要同时设置，或者使用默认高度，如下。
> 
> ```ts
>    autoFit: false,
> ```

同时设置 width 和 height 也会出现

**Comment by JackLiR8** [comment]
刚理解错了。设置 `width` 和 `height` 时需要同时设置 `autoFit` 为 `false`
