### ISSUE TITLE
🧐[问题] 打包后太大了，是否是使用方式有问题

### ISSUE THREAD

**Issue by gefeiyanga** [ant-design/ant-design-charts#1707]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
已使用下方推荐方式引入，包大小如下图，有没有优化空间了
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```
import Bar from '@ant-design/plots/es/components/bar';
import Area from '@ant-design/plots/es/components/area';
```
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/30728843/204493199-97f1c75b-cce2-40df-8d5c-01200d44aec9.png)

**Comment by lxfu1** [comment]
external掉，用CDN ?
