### ISSUE TITLE
混合图的图例无法点击🐛[BUG]

### ISSUE THREAD

**Issue by CHEN-DONG** [ant-design/ant-design-charts#171]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
不能点还是不支持点击事件？

**Comment by CHEN-DONG** [comment]
> 不能点还是不支持点击事件？

https://charts.ant.design/demos/combo#groupedcolumnline
这个例子下的图例都无法点击

**Comment by lxfu1** [comment]
这是官网的问题。

**Comment by CHEN-DONG** [comment]
> 这是官网的问题。

https://antv-g2plot.gitee.io/zh/examples/combo/column-line
g2官网是可以点击的@lxfu1

**Comment by lxfu1** [comment]
1.0 已经发布， 欢迎使用。 https://charts.ant.design/guide/case#%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A
```ts
  ref.current.on('legend', (...args) => {
        console.log(...args);
      });
```
