### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by TallNutAlarak** [ant-design/ant-design-charts#1712]
### 🐛 bug 描述 
AreaMap map.rotation 初始不生效

### 📷 复现步骤
见sandbox

### 🏞 期望结果
初始生效

### 💻 复现代码 
https://codesandbox.io/s/laughing-julien-i03rg4?file=/src/App.js

### © 版本信息

- ant-design-charts 版本: 
 1.0.6
- 浏览器环境
 chrome
- 开发环境
 mac OS

**Comment by lvisei** [comment]
type 修改为 amap
```
map: {
      type: "amap",
}
```
