### ISSUE TITLE
🧐[问题] How to modify the "hot-zone" that will render the tooltip?

### ISSUE THREAD

**Issue by roger-sony** [ant-design/ant-design-charts#1714]
Hi! So I wasn't able to find the solution in the docs and figured I should probably ask here. 

Is there a way to expand the zone of the bar that detects whether the cursor is on the element?

Example:
![CleanShot 2022-12-02 at 13 44 00](https://user-images.githubusercontent.com/104792949/205364332-2efff840-d461-4401-84d8-971393b3db22.gif)

Ideally, I'd like the tooltip to appear as soon as the cursor overlaps with the bar.

Thanks!

**Comment by roger-sony** [comment]
After doing some experimentation, it seems like this bug only happens when there is only one item within the data array. 

For example:
[codesandbox](https://codesandbox.io/s/brave-rgb-n7wsms?file=/index.js)
![CleanShot 2022-12-05 at 05 26 34](https://user-images.githubusercontent.com/104792949/205614900-3d699bec-b239-44eb-86cc-c83787ad8386.gif)

**Comment by lxfu1** [comment]
tooltip: { shared: false } ??

**Comment by roger-sony** [comment]
Wow, yup that fixes it. Thanks @lxfu1!

**Comment by roger-sony** [comment]
Sorry, I'm still having this issue. Would love to get some help if possible!
