### ISSUE TITLE
antd v5 不支持吗？使用官网的示例 起不来🧐[问题]

### ISSUE THREAD

**Issue by echoyl** [ant-design/ant-design-charts#1716]
Error: Cannot find module 'antd/es/tooltip/style/index.css'

**Comment by echoyl** [comment]
> 运行一下这个：
> 
> npm i @antv/x6-react-components

没用 本来就已经安装了这个的。只能等了

**Comment by mashirozx** [comment]
> 

要更新这个版本，2.0.4以上

**Comment by mashirozx** [comment]
> > 运行一下这个：
> > npm i @antv/x6-react-components
> 
> 没用 本来就已经安装了这个的。只能等了

要更新这个版本，2.0.4以上

**Comment by echoyl** [comment]
> > > 运行一下这个：
> > > npm i @antv/x6-react-components
> > 
> > 
> > 没用 本来就已经安装了这个的。只能等了
> 
> 要更新这个版本，2.0.4以上

还需要升级下react到18 现在可以了
