### ISSUE TITLE
🐛[BUG]柱线混合图例展示不全

### ISSUE THREAD

**Issue by geekhac** [ant-design/ant-design-charts#1717]
### 🐛 柱线混合图，图例字段长，屏幕小，不能完全展示时，文字会被截断

<img width="444" alt="image" src="https://user-images.githubusercontent.com/13954860/205612405-a0921c82-67ab-4f9d-901b-a028870fc3d0.png">

### © 版本信息

- ant-design-charts 版本: [e.g. 1.2.2]
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
`legend.itemHeight: 24`
