### ISSUE TITLE
🐛[BUG] - Tooltips going outside the area of the chart

### ISSUE THREAD

**Issue by evybauer** [ant-design/ant-design-charts#1718]
### 🐛 Bug Description [Describe the bug in detail so that everyone can understand]:
After a recent update of ant-design-charts the tooltips have started going outside the area of the chart.

### 📷 Reproduction Steps [Clearly describe the reproduction steps so that others can see the problem]
Hovering over a chart and custom tooltips won't behave as before, they get outside the area of the chart and are not as responsive as they were before. When hovering from left to right, the custom tooltip is used to remain on the right side. The more right you'd hover the custom tooltip would jump to the left side, not blocking the chart view users are hovering. 

### 🏞 Desired Result [Describe the result you expected to see]
The custom tooltip should behave as before, not going outside the chart area and following the mouse hovering to avoid blocking the chart's view

### 💻 Reproduce code [provide reproducible code, repository, or online examples]
Custom tooltip using ant design and styled components:

`tooltip: {
      customContent: (title: string, items: any[]) => {
        const item = items[0] || {}

        return (
          <TooltipContainer>
            <Text>{dayjs(title).format('DD/MM/YYYY  HH:mm')}</Text>
            <ValueText
              css={{
                '&&': {
                  color,
                },
              }}
            >
              {item.value}
              {suffix}
            </ValueText>
          </TooltipContainer>
        )
      },
    },`

### © Version information

- ant-design-charts version: 1.4.2
- Browser environment: Chrome
- Development environment: mac OS

### 🚑 Other information [Other information such as screenshots can be posted here]

<img width="471" alt="Screen Shot 2022-12-06 at 10 58 55 AM" src="https://user-images.githubusercontent.com/48938870/205998475-7475ab5d-924c-4d70-be14-c370e092b88c.png">

**Comment by cecil-su** [comment]
try this way
```
customContent: (title: string, data: any) => {
    return `<div class="g2-tooltip-title">${dayjs(title).format('DD/MM/YYYY  HH:mm')}</div>`
}
```

**Comment by evybauer** [comment]
Currently, we customize the tooltips with `ant design` components so there's no way to transform everything into a string. 
The only alternative found was to downgrade the ant-design-charts version to avoid the issue.

**Comment by lxfu1** [comment]
The latest version will automatically adjust the position.

**Comment by wzz5304** [comment]
![image](https://github.com/user-attachments/assets/95afa1eb-cbdb-40b4-9fbc-b5a60b5a9404)
@ant-design/plots 2.3.2版本 还是存在这个问题

**Comment by wzz5304** [comment]
tooltip: {
      title: false,
      items: [
        (d: IObj) => {
          return { name: d.label, value: d.desc };
        },
      ],
    }, 怎么解决
