### ISSUE TITLE
help with onClick

### ISSUE THREAD

**Issue by vah13** [ant-design/ant-design-charts#1721]
Hello, 
I'm sorry, I'd like to use one of those graphs, but I can't add onClick properties. 
```
FundFlowGraph 
RadialTreeGraph
FlowAnalysisGraph
```
How can I use `onClick` on graph elements?
Thank you

**Comment by lxfu1** [comment]
```ts
onReady: (graph) => {
  graph.on('node:click', ()=> {xx})
}
```

**Comment by vah13** [comment]
Thank you so much!
