### ISSUE TITLE
legend挡住了刻度线

### ISSUE THREAD

**Issue by 2020mythww** [ant-design/ant-design-charts#1724]
这个地方legend挡住了线，可以通过什么属性配置吗
![image](https://user-images.githubusercontent.com/67315275/206978212-6cd043ec-398c-4780-8fd0-096372dec31b.png)
理想效果如下
![image](https://user-images.githubusercontent.com/67315275/206978317-5caa70d3-b7ab-438b-ae41-6da188709391.png)

**Comment by lxfu1** [comment]
padding: [30, 100]
