### ISSUE TITLE
🧐[迷你折线图要怎么定义meta里面的formatter？]

### ISSUE THREAD

**Issue by zyk2891** [ant-design/ant-design-charts#1727]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
迷你折线图传入的data为[264, 417, 438]如此类型，想要重新给数值格式化，由于meta传入一个Record<string, Meta>，纯数字数组无法满足{字段名: MetaOption} 格式，如何在meta中配置？
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
meta: {
    [field: string]: MetaOption
  }

**Comment by lxfu1** [comment]
field 底层默认为 `x\y` 了
```ts
export const X_FIELD = 'x';
export const Y_FIELD = 'y';
```

**Comment by zyk2891** [comment]
但是设置

**Comment by zyk2891** [comment]
![image](https://user-images.githubusercontent.com/43950678/207237534-7d1a8892-d0f5-4521-9873-17b0ed8cd020.png)
但是设置y也无效

**Comment by zyk2891** [comment]
tooltip: {
      customItems: (originalItems) => {
        // process originalItems, 
        originalItems[0].data = Object.assign({}, originalItems[0].data, { y: '#'})
        console.log(originalItems)
        return originalItems;
      }
    }

**Comment by lxfu1** [comment]
```ts
tooltip:{
      customContent:(value)=> {
        return <p>{value}</p>
      }
    }
```

**Comment by zyk2891** [comment]
是否可以直接通过
![image](https://user-images.githubusercontent.com/43950678/207238374-01869140-ec85-4ab1-a7c2-49cb5923a715.png)
替换originalItems.data实现？替换originalItems.value貌似没有效果
originalItems似乎一直是一个[{}]的数据格式
tooltip: {
      customItems: (originalItems) => {
        originalItems[0].data = Object.assign({}, originalItems[0].data, { x: originalItems[0].data.x, y:  originalItems[0].data.y+'#'})
        return originalItems;
      }
    }

**Comment by zyk2891** [comment]
> ```ts
> tooltip:{
>       customContent:(value)=> {
>         return <p>{value}</p>
>       }
>     }
> ```
哦哦 明白了 我之前那个回答多此一举了
