### ISSUE TITLE
🐛[BUG]Unhandled Rejection (TypeError): src.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by YYL1999** [ant-design/ant-design-charts#1731]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
使用官网柱形图demo出现这个问题

### 🏞 期望结果 [描述你原本期望看到的结果]
没有报错
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
官网demo
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
提供个链接

**Comment by YYL1999** [comment]
用codesandbox复现不了 发现可能根数据有关系，把数据json转换一下就好了
