### ISSUE TITLE
Line在x轴为连续型数值时，slider范围显示异常🐛[BUG]

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#1732]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
当在Line中传入连续型数值的x轴数据时使用slider，会出现slider标注的范围文字信息与实际坐标轴不符合的情况
![image](https://user-images.githubusercontent.com/49147660/208006417-1703ce5c-bd0e-4098-b27d-728c03ae7e30.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
见复现地址
### 🏞 期望结果 [描述你原本期望看到的结果]
slider范围文字与实际缩放到的坐标轴范围一致
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
复现地址：https://codesandbox.io/s/rough-dew-mpwtq9?file=/index.js
@lxfu1

**Comment by lxfu1** [comment]
xField 需要是 string 类型，不支持连续类型的。

**Comment by Zavins** [comment]
那为何将xAxis的type改为pow的时候, slider 又显示正常呢？
