### ISSUE TITLE
🐛[BUG] "dodgePadding" not working when data have one record

### ISSUE THREAD

**Issue by dongnvinfoplus** [ant-design/ant-design-charts#1738]
```
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Column } from '@ant-design/plots';

const DemoColumn = () => {
  const data = [
    {
      "groupCd":"G1",
      "groupValue":44500,
      "month":"11/2022"
    },
    {
      "groupCd":"G1",
      "groupValue":516789,
      "month":"12/2022"
    }
  ];
  const config = {
    data,
    isGroup: true,
    xField: 'groupCd',
    yField: 'groupValue',
    seriesField: 'month',
     color:['#1E4485', '#F9C718'],
     maxColumnWidth:40,
     dodgePadding:15,
  };
  return <Column {...config} />;
};

ReactDOM.render(<DemoColumn />, document.getElementById('container'));
```

It's not show chart
![image](https://user-images.githubusercontent.com/105279269/208820570-38691aac-4249-4bbb-aa8d-4302a90d6e2e.png)

and remove "dodgePadding"
![image](https://user-images.githubusercontent.com/105279269/208820867-88901960-aa80-4b11-8bf6-feedfdf4c6db.png)

**Comment by sparrowek** [comment]
The same problem for me - when dodgePadding is set the chart is empty

`import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Column } from '@ant-design/plots';

const DemoColumn = () => {

  const data = [
  {
    count: 5,
factory: "MOB",
processStep: "MOB - Zakładanie lokalizacji",
processType: "ZLS",
  },
  ];

  const config = {
    data,
    xField: 'processType',
    yField: 'count',
    isGroup: true,
    isStack: true,
    seriesField: 'processStep',
    groupField: 'factory',
    dodgePadding: 2,
  };

  return <Column {...config} />;
};

ReactDOM.render(<DemoColumn />, document.getElementById('container'));
`

**Comment by lxfu1** [comment]
你这个2个配置在一定条件下是互斥的啊~

```ts
 maxColumnWidth:40,
 dodgePadding:15,
```

**Comment by sparrowek** [comment]
My example (which is copied from the official one) does not have maxColumnWidth and dodgePadding still causes a problem.

**Comment by ClickEsc** [comment]
With one record of type dodgePadding prevents columns from being shown:

`
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { DualAxes } from '@ant-design/plots';

const DemoDualAxes = () => {
  const uvBillData = [
    {
      time: '2019-03',
      value: 350,
      type: 'uv',
    },
    // {
    //   time: '2019-04',
    //   value: 900,
    //   type: 'uv',
    // },
    // {
    //   time: '2019-05',
    //   value: 300,
    //   type: 'uv',
    // },
    // {
    //   time: '2019-06',
    //   value: 450,
    //   type: 'uv',
    // },
    // {
    //   time: '2019-07',
    //   value: 470,
    //   type: 'uv',
    // },
    {
      time: '2019-03',
      value: 220,
      type: 'bill',
    },
    // {
    //   time: '2019-04',
    //   value: 300,
    //   type: 'bill',
    // },
    // {
    //   time: '2019-05',
    //   value: 250,
    //   type: 'bill',
    // },
    // {
    //   time: '2019-06',
    //   value: 220,
    //   type: 'bill',
    // },
    // {
    //   time: '2019-07',
    //   value: 362,
    //   type: 'bill',
    // },
  ];
  const transformData = [
    {
      time: '2019-03',
      count: 800,
    },
    {
      time: '2019-04',
      count: 600,
    },
    {
      time: '2019-05',
      count: 400,
    },
    {
      time: '2019-06',
      count: 380,
    },
    {
      time: '2019-07',
      count: 220,
    },
  ];
  const config = {
    data: [uvBillData, transformData],
    xField: 'time',
    yField: ['value', 'count'],
    geometryOptions: [
      {
        geometry: 'column',
        isGroup: true,
        dodgePadding: 0,
        seriesField: 'type',
      },
      {
        geometry: 'line',
        lineStyle: {
          lineWidth: 2,
        },
      },
    ],
  };
  return <DualAxes {...config} />;
};

ReactDOM.render(<DemoDualAxes />, document.getElementById('container'));
`

With two or more records of the same type dodgePadding is applied ok and columns are shown:

`
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { DualAxes } from '@ant-design/plots';

const DemoDualAxes = () => {
  const uvBillData = [
    {
      time: '2019-03',
      value: 350,
      type: 'uv',
    },
    {
      time: '2019-04',
      value: 900,
      type: 'uv',
    },
    // {
    //   time: '2019-05',
    //   value: 300,
    //   type: 'uv',
    // },
    // {
    //   time: '2019-06',
    //   value: 450,
    //   type: 'uv',
    // },
    // {
    //   time: '2019-07',
    //   value: 470,
    //   type: 'uv',
    // },
    {
      time: '2019-03',
      value: 220,
      type: 'bill',
    },
    {
      time: '2019-04',
      value: 300,
      type: 'bill',
    },
    // {
    //   time: '2019-05',
    //   value: 250,
    //   type: 'bill',
    // },
    // {
    //   time: '2019-06',
    //   value: 220,
    //   type: 'bill',
    // },
    // {
    //   time: '2019-07',
    //   value: 362,
    //   type: 'bill',
    // },
  ];
  const transformData = [
    {
      time: '2019-03',
      count: 800,
    },
    {
      time: '2019-04',
      count: 600,
    },
    {
      time: '2019-05',
      count: 400,
    },
    {
      time: '2019-06',
      count: 380,
    },
    {
      time: '2019-07',
      count: 220,
    },
  ];
  const config = {
    data: [uvBillData, transformData],
    xField: 'time',
    yField: ['value', 'count'],
    geometryOptions: [
      {
        geometry: 'column',
        isGroup: true,
        dodgePadding: 0,
        seriesField: 'type',
      },
      {
        geometry: 'line',
        lineStyle: {
          lineWidth: 2,
        },
      },
    ],
  };
  return <DualAxes {...config} />;
};

ReactDOM.render(<DemoDualAxes />, document.getElementById('container'));
`
https://ant-design-charts.antgroup.com/en/examples/dual-axes/grouped-column-line/#grouped-column-line

**Comment by ClickEsc** [comment]
I guess **marginRatio** can be used to substitute dodgePadding here. Though in my project it takes marginRatio: 0 to substitute dodgePadding: 0, whereas in the sandbox it takes marginRatio: uvBillData?.length <= 2 ? -0.5 : 0, to do the same

![image](https://github.com/ant-design/ant-design-charts/assets/66803943/7aea6944-52a0-4a20-99e0-9417fae5d730)

![image](https://github.com/ant-design/ant-design-charts/assets/66803943/6cd56834-bfa2-4e74-b54d-98e86ceed928)


```
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { DualAxes } from '@ant-design/plots';

const DemoDualAxes = () => {
  const uvBillData = [
    {
      time: '2019-03',
      value: 350,
      type: 'uv',
    },
    // {
    //   time: '2019-04',
    //   value: 900,
    //   type: 'uv',
    // },
    // {
    //   time: '2019-05',
    //   value: 300,
    //   type: 'uv',
    // },
    // {
    //   time: '2019-06',
    //   value: 450,
    //   type: 'uv',
    // },
    // {
    //   time: '2019-07',
    //   value: 470,
    //   type: 'uv',
    // },
    {
      time: '2019-03',
      value: 220,
      type: 'bill',
    },
    // {
    //   time: '2019-04',
    //   value: 300,
    //   type: 'bill',
    // },
    // {
    //   time: '2019-05',
    //   value: 250,
    //   type: 'bill',
    // },
    // {
    //   time: '2019-06',
    //   value: 220,
    //   type: 'bill',
    // },
    // {
    //   time: '2019-07',
    //   value: 362,
    //   type: 'bill',
    // },
  ];
  const transformData = [
    {
      time: '2019-03',
      count: 800,
    },
    {
      time: '2019-04',
      count: 600,
    },
    {
      time: '2019-05',
      count: 400,
    },
    {
      time: '2019-06',
      count: 380,
    },
    {
      time: '2019-07',
      count: 220,
    },
  ];
  const config = {
    data: [uvBillData, transformData],
    xField: 'time',
    yField: ['value', 'count'],
    geometryOptions: [
      {
        geometry: 'column',
        isGroup: true,
        // dodgePadding: 0,
        marginRatio: uvBillData?.length <= 2 ? -0.5 : 0,
        seriesField: 'type',
      },
      {
        geometry: 'line',
        // marginRatio: 0,
        lineStyle: {
          lineWidth: 2,
        },
      },
    ],
  };
  return <DualAxes {...config} />;
};

ReactDOM.render(<DemoDualAxes />, document.getElementById('container'));
```

Example based on: [https://ant-design-charts.antgroup.com/en/examples/dual-axes/grouped-column-line/#grouped-column-line](https://ant-design-charts.antgroup.com/en/examples/dual-axes/grouped-column-line/#grouped-column-line)
