### ISSUE TITLE
Is it possible to only have one area in a Stacked Area chart?

### ISSUE THREAD

**Issue by DWboutin** [ant-design/ant-design-charts#1739]
![Screenshot 2022-12-22 at 12 47 57 PM](https://user-images.githubusercontent.com/1322006/209196515-6b8411c9-a61e-45ed-aa72-c7cbc114f053.png)

I want to have my charts like this. Is it possible? Is using Stacked Area is correct or should I use another one?

**Comment by lxfu1** [comment]
https://charts.ant.design/zh/examples/area/stacked#area-large-data
```ts
    areaStyle: ()=>{
      return {fill: '#fff'}
    },
``
