### ISSUE TITLE
Is it possible to have border-radius for the highest column only in a Stacked Column Chart?

### ISSUE THREAD

**Issue by DWboutin** [ant-design/ant-design-charts#1740]
I would like to create this layout, is it possible?

![Screenshot 2022-12-22 at 2 56 08 PM](https://user-images.githubusercontent.com/1322006/209216068-33958a33-29aa-4e8c-a97b-879ebedcb07a.png)

**Comment by nate-kelley-buster** [comment]
Requesting this feature as well!

**Comment by hustcc** [comment]
本质上，这个是一个非堆积的柱形图。

```ts
const stackedColumnPlot = new Column('container', {
  data,
  isStack: false,
  xField: 'year',
  yField: 'value',
  seriesField: 'type',
});

stackedColumnPlot.render();
```
