### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by LzhH5** [ant-design/ant-design-charts#1744]
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
设置柱状图为数值

### 🏞 期望结果 [描述你原本期望看到的结果]
![2722c23df0abe1b2f928310b8980d1a](https://user-images.githubusercontent.com/60648379/209802890-17d7a125-aa2f-4356-ad3d-486a59c8fb41.png)
如果不以0为基准线，从最小值开始
类似帖子
https://segmentfault.com/q/1010000015342610
尝试使用这个 axisLine: {
          onZero: false
        }
也没有生效

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/summer-pine-rl3cwt?file=/index.js

### © 版本信息

- ant-design-charts 版本: [e.g. 1.2.11]
- 浏览器环境
- 开发环境 [e.g. windows]

**Comment by lxfu1** [comment]
这个是合理操作吧

**Comment by wooxyz** [comment]
> 这个是合理操作吧

x轴从负值（不是从0开始的），那也是合理的需求吧！
