### ISSUE TITLE
Chord和弦图如何设置节点文本大小🧐[问题]

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#1746]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
请问如何针对和弦图节点的文本样式进行自定义：
![image](https://user-images.githubusercontent.com/49147660/210039336-63f0c98a-1685-44b0-b774-bb0834cd9165.png)

**Comment by lxfu1** [comment]
@visiky 底层写死了

**Comment by lxfu1** [comment]
已经修复，重新安装下依赖
```ts
label: {
  style: {
    fontSize: 20
  }
}
```
