### ISSUE TITLE
鼠标右键->将图像另存为？

### ISSUE THREAD

**Issue by 2020mythww** [ant-design/ant-design-charts#1747]
![image](https://user-images.githubusercontent.com/67315275/210044672-add0244e-a3ed-4546-b365-0a629b2a0949.png)
这个将图像另存为好像是antv的功能，可以拿掉吗？

**Comment by lxfu1** [comment]
这个应该是浏览器的功能！

**Comment by 2020mythww** [comment]
请问你知道怎么在代码层面，将这个功能禁用吗

**Comment by CNFeffery** [comment]
@2020mythww 将参数`renderer`设置为`'svg'`即可
![image](https://user-images.githubusercontent.com/49147660/210082483-33c370d8-afdb-46e2-b61c-776923d17230.png)
