### ISSUE TITLE
🐛[BUG] Unable to apply animation on gauge

### ISSUE THREAD

**Issue by AmrAhmedA** [ant-design/ant-design-charts#1748]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
following tour [animation guide](https://charts.ant.design/en/docs/api/options/animation), gauge component docs, none of the animation work for the gauge component.
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://codesandbox.io/s/vigorous-johnson-5re0dv?file=/index.js
### 🏞 期望结果 [描述你原本期望看到的结果]
should show grow in xy animation for gauge chart.
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/vigorous-johnson-5re0dv?file=/index.js

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0] : Antd charts: ^1.4.2
- 浏览器环境 : Google Chrome - Version 108.0.5359.124 (Official Build) (arm64)
- 开发环境 [e.g. mac OS] : MAC OS

**Comment by lxfu1** [comment]
试试2.0 https://ant-design-charts-next.antgroup.com/en/examples/statistics/gauge/#gauge
```ts
  animate: {
      arcenter: {
        type: 'growInX'
      },
    }
```
