### ISSUE TITLE
🧐[问题] 手机端使用时，报 unexpected token [

### ISSUE THREAD

**Issue by sdls10qq** [ant-design/ant-design-charts#175]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
   手机端打开时，报 unexpected token [  错误。
      目前发现 打包 压缩的js里面出现了  
                 let[d,h]=Hp(a,o,s,c);d=Math.exp(d);  
                const[f,d]=Hp(a,o,s,c),h=e=>d*e+f,p=[[l,h(l)],[u,h(u)]];
         
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
    环境  基于umi 2.13.12， 移动端  android 5.1 , 浏览器内核为 chrome 44 mobile

**Comment by lxfu1** [comment]
这个看上去不像是图表的问题。

**Comment by sdls10qq** [comment]
是umi的 uglify 压缩报错问题及 es5-imcompatible-versions。目前已经解决
详见 https://github.com/sorrycc/blog/issues/68
