### ISSUE TITLE
🧐[问题] type: 'time' 的时候 时间的格式可以输入的类型都有哪些？怎么获得时分秒信息？

### ISSUE THREAD

**Issue by Dawnwangzi** [ant-design/ant-design-charts#1753]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://user-images.githubusercontent.com/20938424/211233484-c58acc1c-99dd-4591-ba7a-2853dbca5def.png)

怎么获得时分秒信息？
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://codesandbox.io/s/xh1u8x?file=/index.js:1591-1603

**Comment by lxfu1** [comment]
目前不支持，建议自己处理数据，使用cat类型，或者试试 formatter 的第二个参数`formatter: (v, arg)=> 'xx'`
