### ISSUE TITLE
d3-color vulnerable to ReDoS

### ISSUE THREAD

**Issue by nonam4** [ant-design/ant-design-charts#1759]
i don't think this is an issue with the project but in my app using `"@ant-design/charts": "^1.4.2"` I'm getting a dependabot warning with `high` severity about this

```
Dependabot cannot update d3-color to a non-vulnerable version
The latest possible version that can be installed is 1.4.1 because of the following conflicting dependencies:

@ant-design/charts@1.4.2 requires d3-color@^1.4.0 via a transitive dependency on @antv/l7-utils@2.13.1
@ant-design/charts@1.4.2 requires d3-color@^1.4.0 via a transitive dependency on @antv/l7-layers@2.13.1
@ant-design/charts@1.4.2 requires d3-color@1 via a transitive dependency on d3-interpolate@1.4.0
The earliest fixed version is 3.1.0.
``` 

Can you please bump deps to earliest fixed version to fix this warning?

**Comment by lzxue** [comment]
sorry，because  L7 IE11  compatibility,  can’t update d3-color to 3.10 。

**Comment by nonam4** [comment]
@lzxue I think you should leave IE11 behind because it's an old and outdated browser.. 
I think nobody uses it this days when we have Google Chrome, Microsoft Edge, Opera, Firefox, Safari and tons of better, modern and beautifull browsers options to use

**Comment by lxfu1** [comment]
If you are not using maps, you can use sub packages such as `@ant-design/plots` .

**Comment by nonam4** [comment]
> If you are not using maps, you can use sub packages such as `@ant-design/plots` .

this works, I've already moved to `@ant-design/plots` sometime after opening this issue.
