### ISSUE TITLE
🐛[BUG] 在 grid 布局中图表 autofit 缩小宽度时不生效

### ISSUE THREAD

**Issue by zhangminggeek** [ant-design/ant-design-charts#1761]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
设置容器 display: grid ，图表设置 autoFit: true，在容器放大时图表能自适应放大，容器缩小时图表宽度不变化

### 🏞 期望结果 [描述你原本期望看到的结果]
容器放大缩小都能自适应

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/hidden-violet-b2ft42?file=/index.js

### © 版本信息

- ant-design-charts 版本: 1.4.2
- 浏览器环境
- 开发环境 mac OS

**Comment by lxfu1** [comment]
如图：
![image](https://user-images.githubusercontent.com/31396322/212837917-084a173a-d8ed-47e9-a935-8d582f1046cd.png)

**Comment by sjinpark0502** [comment]
@lxfu1  @ant-design/plots Are there any plans to publish a corresponding patch?

**Comment by Qiuhang817385** [comment]
> ```ts
> config.style = {
>   overflow: "hidden"
> }
> ```

https://github.com/ant-design/ant-design-charts/issues/1785 引入了新的问题？
