### ISSUE TITLE
marker的回调形式返回的PathCommand是个什么类型？

### ISSUE THREAD

**Issue by 2020mythww** [ant-design/ant-design-charts#1769]
![image](https://user-images.githubusercontent.com/67315275/212914387-57e1c942-d010-47da-889f-7eaf654ed02c.png)

**Comment by lxfu1** [comment]
![image](https://user-images.githubusercontent.com/31396322/215326736-9a2b9d63-b6e1-49f0-8de0-546a6b5e5da0.png)

**Comment by 2020mythww** [comment]
![image](https://user-images.githubusercontent.com/67315275/215392184-773eeacb-af9b-4d5a-99c3-083ea94e8dba.png)
好像页面上没有反应
