### ISSUE TITLE
版本1.0.0-beta.1，设置属性title,description,height...属性都没有效果,降低版本就好了🐛[BUG]

### ISSUE THREAD

**Issue by qing-zhi** [ant-design/ant-design-charts#177]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
发布问题， 最新版本已经更正到 0.9.13 版本， 1.0.0-beta.1 图表类型还不完善。
