### ISSUE TITLE
🐛[BUG] When wrapping a chart in a grid layout with a div tags, chart auto-fit is not applied

### ISSUE THREAD

**Issue by cosycoder** [ant-design/ant-design-charts#1770]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

When wrapping a column chart in a grid layout with a div tags, chart auto-fit is not applied..

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

https://user-images.githubusercontent.com/75600055/213131339-aa0fc07a-3073-4406-9073-444be69813a1.mov

### 🏞 期望结果 [描述你原本期望看到的结果]

i saw https://github.com/ant-design/ant-design-charts/issues/1761. but, when I wrap the chart in a div, the issue reproduces. can you solve the problem?

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://codesandbox.io/s/jovial-cray-266iwq

### © 版本信息

- @ant-design/plots : 1.2.4
- in chrome browser
- mac os

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

🐛[BUG] When wrapping a chart in a grid layout with a div tags, chart auto-fit is not applied

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/1761

**Comment by sjinpark0502** [comment]
> #1761

i saw https://github.com/ant-design/ant-design-charts/issues/1761. but, when I wrap the chart in a div, the issue reproduces. can you solve the problem?

**Comment by cosycoder** [comment]
> #1761

@lxfu1 i saw https://github.com/ant-design/ant-design-charts/issues/1761. but, when I wrap the chart in a div, the issue reproduces. can you solve the problem?

https://codesandbox.io/s/jovial-cray-266iwq

**Comment by lxfu1** [comment]
```tsx
 <div className="chart-wrapper" style={{overflow: 'hidden'}}>
    <Column {...config} />
  </div>
```
