### ISSUE TITLE
[问题] - Is there any guidance on using a custom legend?

### ISSUE THREAD

**Issue by matt-gribben** [ant-design/ant-design-charts#1772]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

As per the title, I would like to customise the legend, or possibly replace it with a html version elsewhere.

Is there a callback or something I can hook into to get the graph data and render my own legend? Or just general guidance in documentation?

**Comment by lxfu1** [comment]
https://codesandbox.io/s/funny-kowalevski-z2kymb?file=/index.js
