### ISSUE TITLE
👑 [需求] Please add position to title in legend in plots

### ISSUE THREAD

**Issue by newbeelearn** [ant-design/ant-design-charts#1774]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

I want to adjust position of title in legend but there is no option available.
It is possible to adjust position in case of G2 with "position" parameter
https://g2plot.antv.antgroup.com/en/api/plots/bar

In general it would be good if there could be parity with g2 options as antd chart is using g2.

**Comment by lxfu1** [comment]
I don't understand what you are going to do, `legend: { position: 'top' }` ?

**Comment by newbeelearn** [comment]
legend: {
		       position: 'top',
		       title: {
		       text: cdata.title,
		       **position: 'center',**
}
i want to adjust position of title in legend right now it is fixed to left.

**Comment by lxfu1** [comment]
Not supported, only `textAlign` can be configured
```ts
title: {
  text: 'cdata.title',
  style: {
    textAlign: 'right',
    fill: 'red',
  }
},
```
