### ISSUE TITLE
🧐[问题]wordCloud-词云图，数据超长不展示

### ISSUE THREAD

**Issue by 54955901** [ant-design/ant-design-charts#1783]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在中文字符达到16字符时，或屏幕宽度不够展示该条内容的情况下，超长的文字会被隐藏掉。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
我想使用词云图中的api，
 ### 
 const config = {
    data: dataSource,
    wordField: 'hotsName',
    weightField: 'hotsCount',
    color: '#1677FF',
    wordStyle: { fontSize: [12, 12], rotation: 0 },
    label: {
      autoHide: true,
      formatter(text: any) {
        // 字符太长添加省略号
        return text.length > 10 ? `${text.slice(0, 15)}...` : text;
      },
    },
    interactions: [
      {
        type: 'element-active',
      },
    ],
    random: () => 0.5,
  };
  return <WordCloud {...config} />;

**Comment by 54955901** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/79985360/215637191-4fbede15-cc16-4eb1-82a5-bfc74aab0a91.png">
我想使用截图内圈出来的代码，但是发现怎么处理都不成功。

**Comment by lxfu1** [comment]
直接处理dataSource ?

**Comment by lxfu1** [comment]
底层设计如此
