### ISSUE TITLE
🧐[问题] tooltip 不能超出图表范围

### ISSUE THREAD

**Issue by Qiuhang817385** [ant-design/ant-design-charts#1785]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://user-images.githubusercontent.com/38211706/215980785-c373dce7-0a32-4435-8b4d-0bcd85038fb5.png)

展示上  tooltip 不能超出图表范围，是底层的库更新了吗？

**Comment by Qiuhang817385** [comment]
应该是这个 PR 导致的问题？https://github.com/ant-design/ant-design-charts/pull/1766/files

**Comment by Qiuhang817385** [comment]
@lxfu1 
想确认下有更好的解决办法吗

**Comment by lxfu1** [comment]
> @lxfu1 想确认下有更好的解决办法吗

配置下 style: {overflow: 'auto'}

**Comment by Qiuhang817385** [comment]
> 

OK，那先临时这样解决。

**Comment by Qiuhang817385** [comment]
> > @lxfu1 想确认下有更好的解决办法吗
> 
> 配置下 style: {overflow: 'auto'}

OK。那先这样临时解决下，作为通用配置，蹲下后续有没有其他适配方案

**Comment by lxfu1** [comment]
> > > @lxfu1 想确认下有更好的解决办法吗
> > 
> > 
> > 配置下 style: {overflow: 'auto'}
> 
> OK。那先这样临时解决下，作为通用配置，蹲下后续有没有其他适配方案

这里有个兼容问题：如果去掉 hidden，在 grid布局下，容器缩小时无法自适应，加上的话，在tooltip过多时，会出现遮挡。

**Comment by Qiuhang817385** [comment]
设置成 auto 的展示也存在问题。。
![image](https://user-images.githubusercontent.com/38211706/216250031-7c145e73-f7ab-47b2-83c3-d4741224a13a.png)
本地项目先设置回默认值 visible 了

**Comment by dengfuping** [comment]
> 应该是这个 PR 导致的问题？https://github.com/ant-design/ant-design-charts/pull/1766/files

相比要解决的问题，这个 PR 引入的问题更严重些，建议优先回滚掉。

**Comment by lxfu1** [comment]
> > 应该是这个 PR 导致的问题？https://github.com/ant-design/ant-design-charts/pull/1766/files
> 
> 相比要解决的问题，这个 PR 引入的问题更严重些，建议优先回滚掉。

+1
