### ISSUE TITLE
🧐[问题] 饼图提供字段显示标题吗

### ISSUE THREAD

**Issue by zyk2891** [ant-design/ant-design-charts#1787]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
柱状图axis有title属性，但饼图没有axis，那只能自建div显示标题吗？在图例(legend)左右分布的时候，就不能简单通过text-align: center控制居中，有什么好的解决办法吗
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/43950678/216259991-e2f76fa6-ec9a-4dd8-8547-5bcba3840b6a.png)

**Comment by zyk2891** [comment]
自建div容易无法与饼图中心点对其

**Comment by zyk2891** [comment]
@lxfu1

**Comment by zyk2891** [comment]
牛的牛的 发自我的手机-------- 原始邮件 --------发件人： Joel Alan ***@***.***>日期： 2023年2月6日周一 上午10:17收件人： ant-design/ant-design-charts ***@***.***>抄送： zyk2891 ***@***.***>, Author ***@***.***>主    题： Re: [ant-design/ant-design-charts] 🧐[问题] 饼图提供字段显示标题吗 (Issue #1787)

配置一下 legend 的最大值，同时设置 paddingRight

legend: {

  maxWidth: 120,

},



<p style={{ paddingRight: 120}}>我是标题</p>

**Comment by lxfu1** [comment]
`onReady: (plot) => plot.chart.getComponents().find(item => item.type === "legend").component.getBBox()` 也可以获取legend 的属性，需要配合 React.memo 使用，避免二次渲染。

**Comment by zyk2891** [comment]
`	const onReady = (plot) => {
		let legend = plot.chart.getComponents()
		console.log(plot.chart, legend)
	}
`
`const equityCltCountPieConfig = useMemo(() => {
		const sum = equityCltCountData.reduce((prev,cur) => {
			return prev + cur.value
		}, 0)
		return {
			height: 350,
			appendPadding: 10,
			data: equityCltCountData,
			angleField: 'value',
			colorField: 'type',
			color: ['#7294d4', '#5ec9db', '#7ae677', '#fdc765', '#f27d51'],
			radius: 0.75,
			label: {
				type: 'spider',
				content: (props) => `${(props.percent * 100).toFixed(2)}%`,
				style: {
					fontSize: 14,
					textAlign: 'center',
				},
				layout: []
			},
			tooltip: {
				formatter: (datum) => {
					return { name: datum.type, value: thousands(datum.value, 0) + `(${((datum.value / sum) * 100 || 0).toFixed(2)}%)` };
				},
			},
			interactions: [
				{
					type: 'element-active',
				},
			],
		}
	}, [equityCltCountData])
<Pie {...equityCltCountPieConfig} onReady={onReady}/>`
plot.chart.getComponents()为空数组

**Comment by zyk2891** [comment]
应该是由于equityCltCountData是异步获取的问题导致onReady的时候图表中的data还是[]

**Comment by lxfu1** [comment]
> 应该是由于equityCltCountData是异步获取的问题导致onReady的时候图表中的data还是[]

https://juejin.cn/post/7196652592372662331#heading-2
