### ISSUE TITLE
🐛[BUG]地图组件设置了英语，没有切换成功。

### ISSUE THREAD

**Issue by abuyao** [ant-design/ant-design-charts#1788]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

DotMap 组件 设置了高德的配置，然后设置了语言为英文，组件无效果。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
代码如下：

  const config = {
    map: {
      type: 'amap',
      style: 'dark',
      center: [lon - 0, lat - 0],
      zoom: 5,
      pitch: 0,
      token: '58cca049bc64d56ee2ddd59bcbf3942e',
      lang: 'en',
    },
  source: {},
  color: { field: 'c' },
    shape: 'circle',
    size: 10,
    tooltip: {
      items: ['name', 'city'],
    },
}
<DotMap {...config} />
显示的结果还是中文：
![image](https://user-images.githubusercontent.com/31335677/216285615-69329474-ef37-41b5-9b2f-fda026c6486e.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
希望地图展示为英文。

### © 版本信息

- @ant-design/maps 版本: [1.0.6]
- 浏览器环境
- 开发环境 [mac OS]

**Comment by lvisei** [comment]
![image](https://user-images.githubusercontent.com/26923747/216540659-8524783b-a60b-426a-99a4-e64c2cbf52a6.png)
