### ISSUE TITLE
🧐[问题]什么时候可以支持g2的地图

### ISSUE THREAD

**Issue by malusama** [ant-design/ant-design-charts#179]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
https://g2.antv.vision/zh/examples/map/map#choropleth-map

**Comment by lxfu1** [comment]
这个会在国庆之后进行排期。

**Comment by smarkoo** [comment]
你好，怎么和你联系？请教一些问题，谢谢！

**Comment by KellenHe** [comment]
@lxfu1 等到花儿都谢了。请问是哪一年的国庆~~

**Comment by lxfu1** [comment]
> @lxfu1 等到花儿都谢了。请问是哪一年的国庆~~

可以看下beta版本， https://lxfu1.github.io/charts-beta/zh-CN/demos/district-map-fill 。

**Comment by lxfu1** [comment]
> @lxfu1 等到花儿都谢了。请问是哪一年的国庆~~

建议先使用 L7 或者高德啊，也可以关注下 [L7Plot](https://github.com/antvis/L7Plot) 的进度

**Comment by KellenHe** [comment]
好的，谢谢

**Comment by lxfu1** [comment]
1.3.x 已经支持
