### ISSUE TITLE
🐛[BUG] 组织架构图，层级过多，数据过多导致样式错乱

### ISSUE THREAD

**Issue by hhbusui** [ant-design/ant-design-charts#1790]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
多层级样式错乱
![image](https://user-images.githubusercontent.com/43135111/216503658-d27ce26e-aa88-4260-862a-1234d2d73771.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
直接运行demo就可以看到了

### 🏞 期望结果 [描述你原本期望看到的结果]
样式正常

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
```
import React from 'react';
import ReactDOM from 'react-dom';
import { OrganizationGraph } from '@ant-design/graphs';

const DemoOrganizationGraph = () => {
  const data = {
    "id": "root",
    "value": {
        "title": "所有资源",
        "resType": 2001
    },
    "children": [
        {
            "id": "0",
            "value": {
                "title": "所有计算机",
                "resType": 2002
            },
            "children": [
                {
                    "id": "0-0",
                    "uuid": "0CB23F8FE0D7E23E3A454E37DD8240B4",
                    "value": {
                        "title": "hy",
                        "titleTips": "hy",
                        "resType": 1,
                        "state": 1
                    }
                },
                {
                    "id": "0-1",
                    "uuid": "14ED2531B81F6B35B5C9399BE076B2BF",
                    "value": {
                        "title": "66AFDAB...",
                        "titleTips": "66AFDABA4FAFFA78D095D0764FBDC3C8",
                        "resType": 1
                    },
                    "children": [
                        {
                            "id": "0-1-0",
                            "uuid": "A82D90AB8D6C499F6AC8537F6011CA28",
                            "value": {
                                "title": "9999",
                                "titleTips": "9999",
                                "resType": 4,
                                "state": 1
                            }
                        }
                    ]
                },
                {
                    "id": "0-3",
                    "uuid": "59F7C7BEBCDC94135FD295C6D329E51F",
                    "value": {
                        "title": "合法化...",
                        "titleTips": "合法化的撒发撒打发发达发射点发生发撒法_PC",
                        "resType": 1,
                        "state": 2
                    },
                    "children": [
                        {
                            "id": "0-3-0",
                            "uuid": "3570262D8F46A640A1797651BDC740DC",
                            "value": {
                                "title": "fda",
                                "titleTips": "fda",
                                "resType": 4,
                                "state": 1
                            }
                        },
                        {
                            "id": "0-3-1",
                            "uuid": "47D1F1AD0B29542D926590391F4EC500",
                            "value": {
                                "title": "dD_wrp",
                                "titleTips": "ddd_wrp",
                                "resType": 4,
                                "state": 2
                            }
                        },
                        {
                            "id": "0-3-2",
                            "uuid": "B8FDDFBF8A4D4A305490FF9CBE046930",
                            "value": {
                                "title": "ddd_wrp",
                                "titleTips": "ddd_wrp",
                                "resType": 4,
                                "state": 1
                            }
                        },
                        {
                            "id": "0-3-3",
                            "uuid": "6A79749AAB8DC61328D25C907C8F17D9",
                            "value": {
                                "title": "Qt1111...",
                                "titleTips": "Qt111 Demo 软件服务示例",
                                "resType": 4,
                                "state": 1
                            }
                        }
                    ]
                },
                {
                    "id": "0-5",
                    "uuid": "5F58964EE199D180C64623B2B5FF7C0F",
                    "value": {
                        "title": "zzw",
                        "titleTips": "zzw",
                        "resType": 1,
                        "state": 1
                    }
                },
                {
                    "id": "0-6",
                    "uuid": "70AB114A6323081601DB08AF1D1FAC06",
                    "value": {
                        "title": "11111",
                        "titleTips": "11111",
                        "resType": 1,
                        "state": 1
                    }
                },
                {
                    "id": "0-7",
                    "uuid": "87E1512EEFFE0F9E2044249F9AF02C53",
                    "value": {
                        "title": "2222",
                        "titleTips": "2222",
                        "resType": 1,
                        "state": 1
                    }
                },
                {
                    "id": "0-8",
                    "uuid": "8EF3AFF5B5FE5E35E2F1F177B9D0E4E1",
                    "value": {
                        "title": "test2",
                        "titleTips": "test2",
                        "resType": 1,
                        "state": 1
                    },
                    "children": [
                        {
                            "id": "0-8-0",
                            "uuid": "8E3CBF5DF318CA9FB3D4A4A46F1DD7C1",
                            "value": {
                                "title": "fda",
                                "titleTips": "fda",
                                "resType": 4,
                                "state": 1
                            }
                        },
                        {
                            "id": "0-8-1",
                            "uuid": "D662CA095C90C507F6B4586E9A7EA2CE",
                            "value": {
                                "title": "66666",
                                "titleTips": "66666",
                                "resType": 4,
                                "state": 1
                            }
                        }
                    ]
                },
                {
                    "id": "0-9",
                    "uuid": "9402931E4D91050304641419194EC0C5",
                    "value": {
                        "title": "66AFDAB...",
                        "titleTips": "66AFDABA4FAFFA78D095D0764FBDC3C7",
                        "resType": 1,
                        "state": 1
                    }
                },
                {
                    "id": "0-14",
                    "uuid": "DF0437770A37740EDC077641D8A9E6D3",
                    "value": {
                        "title": "linux计算...",
                        "titleTips": "linux计算机",
                        "resType": 1,
                        "state": 1
                    }
                },
                {
                    "id": "0-15",
                    "uuid": "E67A4563CEAEC5E4A6BD446C71119089",
                    "value": {
                        "title": "fdafadf...",
                        "titleTips": "xunijefefdafdi111",
                        "resType": 1,
                        "state": 1
                    }
                },
                {
                    "id": "0-16",
                    "uuid": "FFB2C280C4CF13526B7A8080F959912D",
                    "value": {
                        "title": "19A24B7...",
                        "titleTips": "19A24B7AF18E34A393759579F23B0C05",
                        "resType": 1,
                        "state": 1
                    }
                }
            ]
        },
        {
            "id": "1",
            "value": {
                "title": "所有PDU",
                "resType": 2003
            },
            "children": [
                {
                    "id": "1-0",
                    "uuid": "972b4160130811ed902818c04dcaf02d",
                    "value": {
                        "title": "NKPfdaf-DY-...",
                        "titleTips": "NKPfda-DY-TU123",
                        "resType": 2,
                        "state": 1
                    }
                },
                {
                    "id": "1-1",
                    "uuid": "9d4fa07312d011ed868f18c04dcaf02d",
                    "value": {
                        "title": "8888888...",
                        "titleTips": "888888888888888888",
                        "resType": 2,
                        "state": 1
                    }
                }
            ]
        },
        {
            "id": "2",
            "value": {
                "title": "所有其他资源",
                "resType": 2004
            },
            "children": [
                {
                    "id": "2-0",
                    "uuid": "1aa75bb113cf11edae6918c04dcaf02d",
                    "value": {
                        "title": "其它资源_m...",
                        "titleTips": "其它资源_myComputers1",
                        "resType": 12
                    }
                },
                {
                    "id": "2-1",
                    "uuid": "1aa7828113cf11edae6a18c04dcaf02d",
                    "value": {
                        "title": "其它资源_其...",
                        "titleTips": "其它资源_其他资源_myComputers()",
                        "resType": 11
                    }
                },
                {
                    "id": "2-2",
                    "uuid": "1aa795dc13cf11edae6a18c04dcaf02d",
                    "value": {
                        "title": "其它资源_5...",
                        "titleTips": "其它资源_5678",
                        "resType": 11
                    }
                },
                {
                    "id": "2-3",
                    "uuid": "2bafe00f13cf11edae6c18c04dcaf02d",
                    "value": {
                        "title": "其它资源_其...",
                        "titleTips": "其它资源_其它资源_其他资源_myComputers()",
                        "resType": 11
                    }
                },
                {
                    "id": "2-4",
                    "uuid": "2bb006d313cf11edae6c18c04dcaf02d",
                    "value": {
                        "title": "其它资源_其...",
                        "titleTips": "其它资源_其他资源_其他资源_myComputers()",
                        "resType": 11
                    }
                },
                {
                    "id": "2-5",
                    "uuid": "3f84068d145f11ed8d6e18c04dcaf02d",
                    "value": {
                        "title": "其它资源_m...",
                        "titleTips": "其它资源_myComputers12",
                        "resType": 11
                    }
                },
                {
                    "id": "2-6",
                    "uuid": "430ecc2713d211edae7a18c04dcaf02d",
                    "value": {
                        "title": "其它资源_其...",
                        "titleTips": "其它资源_其它资源_myComputers1",
                        "resType": 11
                    }
                },
                {
                    "id": "2-7",
                    "uuid": "430edcaa13d211edae7a18c04dcaf02d",
                    "value": {
                        "title": "其它资源_1...",
                        "titleTips": "其它资源_12346",
                        "resType": 11
                    }
                },
                {
                    "id": "2-8",
                    "uuid": "ADE462370E5CB672A8004821C7FA83FD",
                    "value": {
                        "title": "she...",
                        "titleTips": "shebei",
                        "resType": 11,
                        "state": 2
                    }
                },
                {
                    "id": "2-9",
                    "uuid": "D4B37C90E5AC73D58BA03EEDE6F337F5",
                    "value": {
                        "title": "其他资源设备...",
                        "titleTips": "其他资源设备shebei",
                        "resType": 11,
                        "state": 2
                    }
                }
            ]
        }
    ]
};

  return (
    <OrganizationGraph
      data={data}
      nodeCfg={{
        style: (node) => {
          return node.id === 'joel'
            ? {
                fill: '#91d5ff',
                stroke: '#91d5ff',
              }
            : {};
        },
        label: {
          style: (node, group, type) => {
            const styles = {
              icon: {
                width: 32,
                height: 32,
              },
              title: {
                fill: '#fff',
              },
              name: {
                fill: '#fff',
              },
            };
            return node.id === 'joel' ? styles[type] : {};
          },
        },
      }}
    />
  );
};

ReactDOM.render(<DemoOrganizationGraph />, document.getElementById('container'));

```

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0] 最新的
- 浏览器环境 最新的
- 开发环境 [e.g. mac OS] windows

**Comment by lxfu1** [comment]
调整 layout 试试： 
```ts
const layout = {
  getHeight: () => 16,
  getWidth: () => 16,
  getVGap:  () => 40,
  getHGap: () => 60,
}
```

**Comment by hhbusui** [comment]
> 调整 layout 试试：
> 
> ```ts
> const layout = {
>   getHeight: () => 16,
>   getWidth: () => 16,
>   getVGap:  () => 40,
>   getHGap: () => 60,
> }
> ```

感谢回复，我试了下，似乎也不可以呢。

我用这个组件的customContent方法后，接近100多个节点、4层的时候还会出现性能问题呢。

**Comment by lxfu1** [comment]
提供一个在线示例
![image](https://user-images.githubusercontent.com/31396322/216868186-3e79a2e3-b7e2-4a29-bfba-bb6d3f7d0f2f.png)

**Comment by hhbusui** [comment]
> import { OrganizationGraph } from '@ant-design/graphs';
> 
> const DemoOrganizationGraph = () => {
>   const data = {
>     "id": "root",
>     "value": {
>         "title": "所有资源",
>         "resType": 2001
>     },
>     "children": [
>         {
>             "id": "0",
>             "value": {
>                 "title": "所有计算机",
>                 "resType": 2002
>             },
>             "children": [
>                 {
>                     "id": "0-0",
>                     "uuid": "0CB23F8FE0D7E23E3A454E37DD8240B4",
>                     "value": {
>                         "title": "hy",
>                         "titleTips": "hy",
>                         "resType": 1,
>                         "state": 1
>                     }
>                 },
>                 {
>                     "id": "0-1",
>                     "uuid": "14ED2531B81F6B35B5C9399BE076B2BF",
>                     "value": {
>                         "title": "66AFDAB...",
>                         "titleTips": "66AFDABA4FAFFA78D095D0764FBDC3C8",
>                         "resType": 1
>                     },
>                     "children": [
>                         {
>                             "id": "0-1-0",
>                             "uuid": "A82D90AB8D6C499F6AC8537F6011CA28",
>                             "value": {
>                                 "title": "9999",
>                                 "titleTips": "9999",
>                                 "resType": 4,
>                                 "state": 1
>                             }
>                         }
>                     ]
>                 },
>                 {
>                     "id": "0-3",
>                     "uuid": "59F7C7BEBCDC94135FD295C6D329E51F",
>                     "value": {
>                         "title": "合法化...",
>                         "titleTips": "合法化的撒发撒打发发达发射点发生发撒法_PC",
>                         "resType": 1,
>                         "state": 2
>                     },
>                     "children": [
>                         {
>                             "id": "0-3-0",
>                             "uuid": "3570262D8F46A640A1797651BDC740DC",
>                             "value": {
>                                 "title": "fda",
>                                 "titleTips": "fda",
>                                 "resType": 4,
>                                 "state": 1
>                             }
>                         },
>                         {
>                             "id": "0-3-1",
>                             "uuid": "47D1F1AD0B29542D926590391F4EC500",
>                             "value": {
>                                 "title": "dD_wrp",
>                                 "titleTips": "ddd_wrp",
>                                 "resType": 4,
>                                 "state": 2
>                             }
>                         },
>                         {
>                             "id": "0-3-2",
>                             "uuid": "B8FDDFBF8A4D4A305490FF9CBE046930",
>                             "value": {
>                                 "title": "ddd_wrp",
>                                 "titleTips": "ddd_wrp",
>                                 "resType": 4,
>                                 "state": 1
>                             }
>                         },
>                         {
>                             "id": "0-3-3",
>                             "uuid": "6A79749AAB8DC61328D25C907C8F17D9",
>                             "value": {
>                                 "title": "Qt1111...",
>                                 "titleTips": "Qt111 Demo 软件服务示例",
>                                 "resType": 4,
>                                 "state": 1
>                             }
>                         }
>                     ]
>                 },
>                 {
>                     "id": "0-5",
>                     "uuid": "5F58964EE199D180C64623B2B5FF7C0F",
>                     "value": {
>                         "title": "zzw",
>                         "titleTips": "zzw",
>                         "resType": 1,
>                         "state": 1
>                     }
>                 },
>                 {
>                     "id": "0-6",
>                     "uuid": "70AB114A6323081601DB08AF1D1FAC06",
>                     "value": {
>                         "title": "11111",
>                         "titleTips": "11111",
>                         "resType": 1,
>                         "state": 1
>                     }
>                 },
>                 {
>                     "id": "0-7",
>                     "uuid": "87E1512EEFFE0F9E2044249F9AF02C53",
>                     "value": {
>                         "title": "2222",
>                         "titleTips": "2222",
>                         "resType": 1,
>                         "state": 1
>                     }
>                 },
>                 {
>                     "id": "0-8",
>                     "uuid": "8EF3AFF5B5FE5E35E2F1F177B9D0E4E1",
>                     "value": {
>                         "title": "test2",
>                         "titleTips": "test2",
>                         "resType": 1,
>                         "state": 1
>                     },
>                     "children": [
>                         {
>                             "id": "0-8-0",
>                             "uuid": "8E3CBF5DF318CA9FB3D4A4A46F1DD7C1",
>                             "value": {
>                                 "title": "fda",
>                                 "titleTips": "fda",
>                                 "resType": 4,
>                                 "state": 1
>                             }
>                         },
>                         {
>                             "id": "0-8-1",
>                             "uuid": "D662CA095C90C507F6B4586E9A7EA2CE",
>                             "value": {
>                                 "title": "66666",
>                                 "titleTips": "66666",
>                                 "resType": 4,
>                                 "state": 1
>                             }
>                         }
>                     ]
>                 },
>                 {
>                     "id": "0-9",
>                     "uuid": "9402931E4D91050304641419194EC0C5",
>                     "value": {
>                         "title": "66AFDAB...",
>                         "titleTips": "66AFDABA4FAFFA78D095D0764FBDC3C7",
>                         "resType": 1,
>                         "state": 1
>                     }
>                 },
>                 {
>                     "id": "0-14",
>                     "uuid": "DF0437770A37740EDC077641D8A9E6D3",
>                     "value": {
>                         "title": "linux计算...",
>                         "titleTips": "linux计算机",
>                         "resType": 1,
>                         "state": 1
>                     }
>                 },
>                 {
>                     "id": "0-15",
>                     "uuid": "E67A4563CEAEC5E4A6BD446C71119089",
>                     "value": {
>                         "title": "fdafadf...",
>                         "titleTips": "xunijefefdafdi111",
>                         "resType": 1,
>                         "state": 1
>                     }
>                 },
>                 {
>                     "id": "0-16",
>                     "uuid": "FFB2C280C4CF13526B7A8080F959912D",
>                     "value": {
>                         "title": "19A24B7...",
>                         "titleTips": "19A24B7AF18E34A393759579F23B0C05",
>                         "resType": 1,
>                         "state": 1
>                     }
>                 }
>             ]
>         },
>         {
>             "id": "1",
>             "value": {
>                 "title": "所有PDU",
>                 "resType": 2003
>             },
>             "children": [
>                 {
>                     "id": "1-0",
>                     "uuid": "972b4160130811ed902818c04dcaf02d",
>                     "value": {
>                         "title": "NKPfdaf-DY-...",
>                         "titleTips": "NKPfda-DY-TU123",
>                         "resType": 2,
>                         "state": 1
>                     }
>                 },
>                 {
>                     "id": "1-1",
>                     "uuid": "9d4fa07312d011ed868f18c04dcaf02d",
>                     "value": {
>                         "title": "8888888...",
>                         "titleTips": "888888888888888888",
>                         "resType": 2,
>                         "state": 1
>                     }
>                 }
>             ]
>         },
>         {
>             "id": "2",
>             "value": {
>                 "title": "所有其他资源",
>                 "resType": 2004
>             },
>             "children": [
>                 {
>                     "id": "2-0",
>                     "uuid": "1aa75bb113cf11edae6918c04dcaf02d",
>                     "value": {
>                         "title": "其它资源_m...",
>                         "titleTips": "其它资源_myComputers1",
>                         "resType": 12
>                     }
>                 },
>                 {
>                     "id": "2-1",
>                     "uuid": "1aa7828113cf11edae6a18c04dcaf02d",
>                     "value": {
>                         "title": "其它资源_其...",
>                         "titleTips": "其它资源_其他资源_myComputers()",
>                         "resType": 11
>                     }
>                 },
>                 {
>                     "id": "2-2",
>                     "uuid": "1aa795dc13cf11edae6a18c04dcaf02d",
>                     "value": {
>                         "title": "其它资源_5...",
>                         "titleTips": "其它资源_5678",
>                         "resType": 11
>                     }
>                 },
>                 {
>                     "id": "2-3",
>                     "uuid": "2bafe00f13cf11edae6c18c04dcaf02d",
>                     "value": {
>                         "title": "其它资源_其...",
>                         "titleTips": "其它资源_其它资源_其他资源_myComputers()",
>                         "resType": 11
>                     }
>                 },
>                 {
>                     "id": "2-4",
>                     "uuid": "2bb006d313cf11edae6c18c04dcaf02d",
>                     "value": {
>                         "title": "其它资源_其...",
>                         "titleTips": "其它资源_其他资源_其他资源_myComputers()",
>                         "resType": 11
>                     }
>                 },
>                 {
>                     "id": "2-5",
>                     "uuid": "3f84068d145f11ed8d6e18c04dcaf02d",
>                     "value": {
>                         "title": "其它资源_m...",
>                         "titleTips": "其它资源_myComputers12",
>                         "resType": 11
>                     }
>                 },
>                 {
>                     "id": "2-6",
>                     "uuid": "430ecc2713d211edae7a18c04dcaf02d",
>                     "value": {
>                         "title": "其它资源_其...",
>                         "titleTips": "其它资源_其它资源_myComputers1",
>                         "resType": 11
>                     }
>                 },
>                 {
>                     "id": "2-7",
>                     "uuid": "430edcaa13d211edae7a18c04dcaf02d",
>                     "value": {
>                         "title": "其它资源_1...",
>                         "titleTips": "其它资源_12346",
>                         "resType": 11
>                     }
>                 },
>                 {
>                     "id": "2-8",
>                     "uuid": "ADE462370E5CB672A8004821C7FA83FD",
>                     "value": {
>                         "title": "she...",
>                         "titleTips": "shebei",
>                         "resType": 11,
>                         "state": 2
>                     }
>                 },
>                 {
>                     "id": "2-9",
>                     "uuid": "D4B37C90E5AC73D58BA03EEDE6F337F5",
>                     "value": {
>                         "title": "其他资源设备...",
>                         "titleTips": "其他资源设备shebei",
>                         "resType": 11,
>                         "state": 2
>                     }
>                 }
>             ]
>         }
>     ]
> };
> 
>   return (
>     <OrganizationGraph
>       data={data}
>       nodeCfg={{
>         style: (node) => {
>           return node.id === 'joel'
>             ? {
>                 fill: '#91d5ff',
>                 stroke: '#91d5ff',
>               }
>             : {};
>         },
>         label: {
>           style: (node, group, type) => {
>             const styles = {
>               icon: {
>                 width: 32,
>                 height: 32,
>               },
>               title: {
>                 fill: '#fff',
>               },
>               name: {
>                 fill: '#fff',
>               },
>             };
>             return node.id === 'joel' ? styles[type] : {};
>           },
>         },
>       }}
>     />
>   );
> };

提交了一个demo。此demo存在两个问题
1. 连线交叉渲染
2. 首页渲染比较耗时
https://codesandbox.io/s/inspiring-dan-gnyw65

**Comment by hhbusui** [comment]
@lxfu1  大佬请问题这个问题能解决么？

**Comment by lxfu1** [comment]
看中这个，直接使用最新的 `@ant-design/graphs`  https://codesandbox.io/s/floral-leftpad-6k46vq?file=/src/App.js

**Comment by hhbusui** [comment]
@lxfu1  多谢大佬
