### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by jipengwei** [ant-design/ant-design-charts#1794]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在umijs框架中,  直接复制demo中的示例无其它额外附加  纯demo代码,  只要点击组件折叠整个页面假死，必须关掉重新打开页面.
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![30203223530](https://user-images.githubusercontent.com/12807371/216631185-43da59c5-37a7-431c-a25f-043289854476.png)

**Comment by lxfu1** [comment]
重新安装下依赖，已经修复过了 https://github.com/ant-design/ant-design-charts/pull/1760
