### ISSUE TITLE
指标拆解图中有没有方法或者事件，每一次图标在load后可以执行👑 [需求]

### ISSUE THREAD

**Issue by dawnsongpeng** [ant-design/ant-design-charts#1798]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
指标拆解图中有没有方法或者事件，每一次图标在load后可以执行，我通过放大缩小下拉框选择相应的比例，可以缩小放大指标拆解图，但是onReady只有在第一次加载后会执行，切换下一次的时候就不执行了。

**Comment by lxfu1** [comment]
onReady 没必要多次执行吧，你的目的是啥？

**Comment by dawnsongpeng** [comment]
您好，我的目的是每次切换缩小放大比例的时候可以做到将指标拆解图放大缩小相应的比例。谢谢！

**Comment by lxfu1** [comment]
用 useRef 把graph实例存起来， onReady: (graph) => ref.current = graph；直接调用 ref.current.zoomxx()即可
