### ISSUE TITLE
🐛[BUG]图表 Line  annotations 缺少x,y类型

### ISSUE THREAD

**Issue by VincentChris** [ant-design/ant-design-charts#1799]
### 💻 复现代码
![image](https://user-images.githubusercontent.com/34203619/216936957-56f3a1b0-3772-4fa2-9107-c725d5b7b0ac.png)
![image](https://user-images.githubusercontent.com/34203619/216937024-6dfc6593-624f-4358-a1a4-18e160356532.png)

### © 版本信息

- "@ant-design/plots": "^1.2.3",
- chrome 108.0.5359.125
- 开发环境 win11

**Comment by lxfu1** [comment]
position: [100, 200]
