### ISSUE TITLE
Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by FuncWei** [ant-design/ant-design-charts#1800]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Uncaught TypeError: Cannot read properties of null (reading '0')
    at Module.fillPathByDiff (path.js?b6fb:1136:1)
    at _update (timeline.js?59c9:30:1)
    at update (timeline.js?59c9:127:1)
    at eval (timeline.js?59c9:177:1)
    at timerFlush (timer.js?74f4:61:1)
    at wake (timer.js?74f4:71:1)
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
Area组件，动态更改data数据
### © 版本信息

- ant-design-charts 版本: [1.4.2]
- 浏览器环境 [chrome 104.0.51121.101 arm64]
- 开发环境 [emac OS]

**Comment by FuncWei** [comment]
TypeError
Cannot read properties of null (reading '0')
Call Stack
 Module.fillPathByDiff
  node_modules/@antv/g-base/esm/util/path.js:1150:19
 _update
  node_modules/@antv/g-base/esm/animate/timeline.js:41:72
 update
  node_modules/@antv/g-base/esm/animate/timeline.js:138:9
 eval
  node_modules/@antv/g-base/esm/animate/timeline.js:188:42
 timerFlush
  node_modules/d3-timer/src/timer.js:68:48
 wake
  node_modules/d3-timer/src/timer.js:78:5

**Comment by FuncWei** [comment]
去掉 renderer="svg" 不报这个错

**Comment by lxfu1** [comment]
提供个复现，在折线图试了一下，没发现问题。

**Comment by lxfu1** [comment]
用 canvas 吧，或者提供复现之后再打开。
