### ISSUE TITLE
🐛[BUG]render-graph setFlowTag 会导致nodes和edges异常

### ISSUE THREAD

**Issue by 11010cy** [ant-design/ant-design-charts#1801]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/18585614/217422271-2969c043-c055-4d33-8f6a-b1842d0d8197.png)
setFlowTag 会导致nodes和edges异常，进而影响图的正常渲染：

1. 节点重复
  ![image](https://user-images.githubusercontent.com/18585614/217422789-31249112-ad77-4ddb-ae49-930f2eeecc66.png)
2. 边减少

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
@ant-design/graphs/es/utils/render-graph.js
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
提供个复现示例

**Comment by 11010cy** [comment]
@lxfu1 示例：
1.3.6
https://codesandbox.io/s/exciting-bird-u781p6?file=/index.js
1.3.4
https://codesandbox.io/s/dazzling-black-7jhw69?file=/index.js
同样的配置下，1.3.6控制台报错，且边的数量减少
![image](https://user-images.githubusercontent.com/18585614/217452509-7787a917-f342-4987-8ab0-28998ac32b95.png)
