### ISSUE TITLE
🐛[BUG] Error [ERR_REQUIRE_ESM]: require() of ES Module nextjs typescript (timeline.js to a dynamic import() which is available in all CommonJS modules.)

### ISSUE THREAD

**Issue by radrianhp** [ant-design/ant-design-charts#1802]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
I'm using Next.js with TypeScript and I tried to use "Pie chart " from Ant Design Charts https://charts.ant.design/en/examples/pie/basic#basic. But I have error node_modules because have to dynamic import, How to solve this

### 🏞 期望结果 [描述你原本期望看到的结果]
this my sourcode: 
import { Pie } from "@ant-design/plots";

interface testTypes {
  dataProyek: string;
}

const test: React.FC<testTypes> = () => {

  const data: any = [
    {
      type: '分类一',
      value: 27,
    },
    {
      type: '分类二',
      value: 25,
    },
    {
      type: '分类三',
      value: 18,
    },
    {
      type: '分类四',
      value: 15,
    },
    {
      type: '分类五',
      value: 10,
    },
    {
      type: '其他',
      value: 5,
    },
  ];

  const config = {
    appendPadding: 10,
    data,
    angleField: 'value',
    colorField: 'type',
    radius: 0.9,
    label: {
      type: 'inner',
      offset: '-30%',
      content: ({ percent }: any) => `${(percent * 100).toFixed(0)}%`,
      style: {
        fontSize: 14,
        textAlign: 'center',
      },
    },
    interactions: [
      {
        type: 'element-active',
      },
    ],
  };

  return (
    <>
      <Pie {...config} />
    </>
  );
};

### © 版本信息

- @ant-design/plots: [1.0.9]
- next: [12.0.10]
- @ant-design/charts: [1.3.6]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/15336755/217432736-76308d59-201d-4fb6-9a69-587da5099bba.png)
![image](https://user-images.githubusercontent.com/15336755/217432934-16bd4617-d36b-4881-a57c-ff7966cbd277.png)

**Comment by edikurniawan-dev** [comment]
Try this:

Remove
 `import { Pie } from "@ant-design/plots";`

And import like this 
`
const Pie = dynamic(() => import('@ant-design/plots').then(({ Pie }) => Pie), {
    ssr: false,
});
`

**Comment by radrianhp** [comment]
it's still not work

**Comment by edikurniawan-dev** [comment]
have you imported this?
`import dynamic from 'next/dynamic';`

**Comment by radrianhp** [comment]
yah, I got same error

**Comment by edikurniawan-dev** [comment]
hmm, i have been trying in nextjs and it's work
```
import dynamic from 'next/dynamic';
const Pie = dynamic(() => import('@ant-design/plots').then(({ Pie }) => Pie), { ssr: false });

interface testTypes {
    dataProyek: string;
}

const Test: React.FC = () => {
    const data: any = [
        {
            type: '分类一',
            value: 27,
        },
        {
            type: '分类二',
            value: 25,
        },
        {
            type: '分类三',
            value: 18,
        },
        {
            type: '分类四',
            value: 15,
        },
        {
            type: '分类五',
            value: 10,
        },
        {
            type: '其他',
            value: 5,
        },
    ];

    const config = {
        appendPadding: 10,
        data,
        angleField: 'value',
        colorField: 'type',
        radius: 0.9,
        label: {
            type: 'inner',
            offset: '-30%',
            // content: ({ percent }: any) => ${(percent * 100).toFixed(0)%},
            style: {
                fontSize: 14,
                textAlign: 'center',
            },
        },
        interactions: [
            {
                type: 'element-active',
            },
        ],
    };

    return (
        <>
            <Pie {...config} />
        </>
    );
};

export default Test;

```

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design/issues/40644#issuecomment-1423803785

**Comment by Henry59210** [comment]
> dynamic

大佬牛逼
