### ISSUE TITLE
FlowCharts 的节点怎么添加双击事件🧐[问题]

### ISSUE THREAD

**Issue by hello-yajing** [ant-design/ant-design-charts#1805]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
现在有个需求需要给节点加双击事件，但是看文档里有双击事件，不知道怎么用，烦请指教，//抱拳感谢！

![image](https://user-images.githubusercontent.com/39940799/218058169-7d59a1e5-f4b7-420d-b8d0-4ed0e4381e27.png)

**Comment by lxfu1** [comment]
```tsx
 onReady={(graph) => {
    graph.on('node:dblclick', (e) => {
        console.log(e, e.node.data)
      })
    }}
```
