### ISSUE TITLE
Display null value on chart

### ISSUE THREAD

**Issue by quanbui1997** [ant-design/ant-design-charts#1808]
Is there a way that i can display null value on line chart (or orthers) with specific color with connectNulls = true. Thanks
![image](https://user-images.githubusercontent.com/125259954/218423643-bf6aa719-882b-4f48-b91f-a3cd2c946cd6.png)

**Comment by lxfu1** [comment]
`connectNulls: true,`

**Comment by quanbui1997** [comment]
> `connectNulls: true,`

sorry but can you read the question carefully, i know we have connectNulls but i want specify color for this edge

**Comment by lxfu1** [comment]
Not supported.
