### ISSUE TITLE
🐛[BUG]Label遮挡问题

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design-charts#181]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
雷达图
forceFit状态下label显示不完整
### 🏞 期望结果 [描述你原本期望看到的结果]
正常显示
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/20501316/91943992-ff424380-ed2f-11ea-9c86-52f2df4d4793.png)

**Comment by lxfu1** [comment]
设置下padding: [100]，1.0 做了优化，欢迎更新。

**Comment by slodManF** [comment]
padding: [100]不能这样子改吧，如果这样改哪宽度过小的时候不就什么都看不到了吗

**Comment by slodManF** [comment]
> 设置下padding: [100]，1.0已优化，欢迎更新。
padding: [100]不能这样子改吧，如果这样改哪宽度过小时候不就什么都看不到了吗
