### ISSUE TITLE
🧐[问题] 含有坐标轴的图表如何沿着x轴或者y轴上下拖动

### ISSUE THREAD

**Issue by hhbusui** [ant-design/ant-design-charts#1814]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
如下图表，当我x轴或者y轴有100+数据时，想着可以拖动图表上下滑动。
![image](https://user-images.githubusercontent.com/43135111/219261518-dc140d2b-8dba-4414-b6ef-ac009c47b25e.png)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

类似案例。下图这种是沿着滚动条拖动。我的想法是拖动画布，x/y轴跟随移动
![Uploading image.png…]()

https://charts.ant.design/zh/examples/column/basic#scrollbar

**Comment by lxfu1** [comment]
目前只能用 slider  或 scrollbar
