### ISSUE TITLE
🧐[问题]官网设计指引样例实现：饼图内部展示占比，同时外围拉线显示名称和具体数值？

### ISSUE THREAD

**Issue by ScotchPie** [ant-design/ant-design-charts#1821]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
希望能提供下图中左测饼图效果的示例代码
![image](https://user-images.githubusercontent.com/109577566/219359422-00319f5c-76a8-489b-b6a6-fc2783e2e5c2.png)

**Comment by lxfu1** [comment]
https://charts.ant.design/zh/examples/pie/basic#spider-label
