### ISSUE TITLE
🐛[BUG]AreaMap报错，你们的样例都报错

### ISSUE THREAD

**Issue by Mzhang1994** [ant-design/ant-design-charts#1822]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
AreaMap报错，你们的样例都报错。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/69185609/219594509-9cda3666-8038-4770-825d-9cfe007c37e7.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
此组件可以使用

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lvisei** [comment]
已修复，删掉依赖重新安装最新版 @Mzhang1994
