### ISSUE TITLE
🧐[问题]使用Mix，里面有多种类型的图，能否共用一个显示时分秒的X轴，然后共用一个slider

### ISSUE THREAD

**Issue by NARUTOyuyang** [ant-design/ant-design-charts#1824]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
用Mix，里面有多种类型的图，能否共用一个显示时分秒的X轴，然后共用一个slider，我尝试了在其中一个里面加，发现只能作用在当前的图表，不能作用到其他图表
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://codesandbox.io/s/k7jmfu?file=/index.js

**Comment by lxfu1** [comment]
目前是分开的，只能单一生效

**Comment by NARUTOyuyang** [comment]
> 

那我每个图表设置一个 slider ，会重叠在一起，而且只能移动最上层那个

**Comment by lxfu1** [comment]
```ts
xAxis: {
    mask: "YYYYMMDD hh:mm:ss"
},
```
