### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by xinjiahuan** [ant-design/ant-design-charts#1827]
折线图设置了minInterval无效

![image](https://user-images.githubusercontent.com/110023514/220057085-ab40bf46-7014-45e6-8023-00ec74d2cba7.png)
![image](https://user-images.githubusercontent.com/110023514/220057152-5f21cd97-a9c4-410c-9473-0f10101e7d46.png)

**Comment by lxfu1** [comment]
tickInterval
