### ISSUE TITLE
🐛[BUG]基础环图的 pieStyle lineCap设置 ‘round’后，点击 Legend 图例切换动画有问题。

### ISSUE THREAD

**Issue by dingminghui** [ant-design/ant-design-charts#1832]
### 🐛 bug 描述 

基础环图的 pieStyle lineCap设置 ‘round’后，点击 Legend 图例切换动画有问题。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

https://user-images.githubusercontent.com/49083552/221105658-fcd5ec56-dcb3-43e8-b929-6f7f70bf31a6.mov

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

const config = {
    appendPadding: 10,
    data,
    angleField: 'value',
    colorField: 'type',
    radius: 1,
    innerRadius: 0.6,
    label: {
      type: 'inner',
      offset: '-50%',
      content: '{value}',
      style: {
        textAlign: 'center',
        fontSize: 14,
      },
    },
     pieStyle: {
        strokeOpacity: 0,
        lineCap: 'round',
      },
    interactions: [
      {
        type: 'element-selected',
      },
      {
        type: 'element-active',
      },
    ],
    statistic: {
      title: false,
      content: {
        style: {
          whiteSpace: 'pre-wrap',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
        },
        content: 'AntV\nG2Plot',
      },
    },
  }

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
https://ant-design-charts-next.antgroup.com/zh/examples/statistics/pie/#doughnut
