### ISSUE TITLE
🧐[问题]xAxis轴label的formatter不能返回DOM吗？怎么把x轴标签自定义为a标签

### ISSUE THREAD

**Issue by stoiCasey** [ant-design/ant-design-charts#1833]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
xAxis的label貌似不支持返回DOM？我需要怎么做X轴的点击事件

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```
const config = {
    data,
    columnWidthRatio: 0.2,
    isStack: true,
    xField,
    yField,
    xAxis: {
      label: {
        autoRotate: true,
        autoHide: false,
        autoEllipsis: false,
        formatter: (text, item, index) => {
          return <a>text</a>
        }
      },
    }
}
```

**Comment by lxfu1** [comment]
```ts
onReady: (plot) =>{
  plot.on('axis:click', (evt) => {
    console.log(evt.target)
  })
}
```

**Comment by stoiCasey** [comment]
> ```ts
> onReady: (plot) =>{
>   plot.on('axis:click', (evt) => {
>     console.log(evt.target)
>   })
> }
> ```

谢谢你，这样使用可以达到跳转穿透的需求了，如果能像Tooltip组件customContent属性一样接收模板语法就好了

**Comment by stoiCasey** [comment]
> ```ts
> onReady: (plot) =>{
>   plot.on('axis:click', (evt) => {
>     console.log(evt.target)
>   })
> }
> ```

请问，如果我在柱线双轴图中设置了右侧yAxis轴的min为0，max为100，formatter label加了%，为了达到百分比的显示效果。此时接口数据值超过100或者低于0，无法显示出这个值的折线了，有配置可以让他们默认显示在最小值或最大值吗？
