### ISSUE TITLE
Tooltop not getting all data if multiple same value 🧐[问题]

### ISSUE THREAD

**Issue by aseph8083** [ant-design/ant-design-charts#1834]
if json like this 
 const data = [
    {
      "quarter": "Q1 2021",
      "periode": "2021-01",
      "nominal": 0
    },
    {
      "quarter": "Q1 2021",
      "periode": "2021-02",
      "nominal": 0
    },
    {
      "quarter": "Q1 2021",
      "periode": "2021-03",
      "nominal": 0
    },
    {
      "quarter": "Q2 2021",
      "periode": "2021-04",
      "nominal": 0
    },
    {
      "quarter": "Q2 2021",
      "periode": "2021-05",
      "nominal": 0
    },
    {
      "quarter": "Q2 2021",
      "periode": "2021-06",
      "nominal": 0
    },
    {
      "quarter": "Q3 2021",
      "periode": "2021-07",
      "nominal": 0
    },
    {
      "quarter": "Q3 2021",
      "periode": "2021-08",
      "nominal": 0
    },
    {
      "quarter": "Q3 2021",
      "periode": "2021-09",
      "nominal": 0
    },
    {
      "quarter": "Q4 2021",
      "periode": "2021-10",
      "nominal": 0
    },
    {
      "quarter": "Q4 2021",
      "periode": "2021-11",
      "nominal": 0
    },
    {
      "quarter": "Q4 2021",
      "periode": "2021-12",
      "nominal": 13620388408
    }
  ];

data quarter Q4 2021 on last index in tooltip not getting, but show 0, only show on chart

[[](url)](https://codesandbox.io/s/happy-snyder-hee41n)

**Comment by lxfu1** [comment]
```ts
seriesField: 'periode',
isStack: true,
```
