### ISSUE TITLE
🧐[问题]请问如何实现双Y轴柱图

### ISSUE THREAD

**Issue by MonsterXue** [ant-design/ant-design-charts#1835]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
类似于这样
![image](https://user-images.githubusercontent.com/54263194/221735181-9fe2f8b5-0f15-4cda-8b4d-e0a18255533f.png)
我尝试使用DualAxes，但似乎是以堆叠的形式展示的

**Comment by lxfu1** [comment]
https://charts.ant.design/zh/examples/dual-axes/grouped-column-line#grouped-column-line

**Comment by edikurniawan-dev** [comment]
how if want to usage column in chart? not line

**Comment by lxfu1** [comment]
```ts
    axis: {
      y: [
          {
          position: 'left'
        },
        {
          position: 'right',
          labelFormatter: t => `${t} ℃`
        }
      ] 
    },
```
