### ISSUE TITLE
多余的手动调用render方法，影响性能

### ISSUE THREAD

**Issue by inceptiongt** [ant-design/ant-design-charts#1836]
https://github.com/ant-design/ant-design-charts/blob/44faebea1a48481b98df56c0f7c80792c358f983/packages/plots/src/hooks/useChart.ts#L107-L108
如上代码，当config的data改变时，会执行changeData，再执行render。这里changeData、render就是G2Plot的方法。可是G2Plot里执行了changeData就会自动重新渲染，不需要再手动调用render。

所以代码L108是否多余，影响性能？

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/20478779/221768201-24430d59-8ed6-4a1b-b5a2-fa504ed433c7.png">

**Comment by inceptiongt** [comment]
重新编辑后，新开了另外一个。

**Comment by wozien** [comment]
我觉得有点多余
