### ISSUE TITLE
🐛[BUG]源码中调用changeData方法后面，多余的手动调用render方法，影响性能

### ISSUE THREAD

**Issue by inceptiongt** [ant-design/ant-design-charts#1837]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
https://github.com/ant-design/ant-design-charts/blob/44faebea1a48481b98df56c0f7c80792c358f983/packages/plots/src/hooks/useChart.ts#L107-L108
如上代码，当config的data改变时，会执行changeData，再执行render。
这里changeData、render就是G2Plot的方法。
可是G2Plot里执行了changeData就会自动重新渲染，不需要再手动调用render。

所以代码L108是否多余，影响性能？

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/20478779/221768201-24430d59-8ed6-4a1b-b5a2-fa504ed433c7.png">
如上图，changeData及render都调用了View.print。

### © 版本信息

- ant-design-charts 版本: 1.4.2
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
不重新 render 会存在 axis 不清空的问题，这个其实是底层bug导致的~！

**Comment by inceptiongt** [comment]
> 

是G2Plot的changeData的bug导致的吗，还是更底层G2的bug？

**Comment by inceptiongt** [comment]
> 不重新 render 会存在 axis 不清空的问题，这个其实是底层bug导致的~！

是G2Plot的changeData的bug导致的吗，还是更底层G2的bug？

**Comment by lxfu1** [comment]
> > 不重新 render 会存在 axis 不清空的问题，这个其实是底层bug导致的~！
> 
> 是G2Plot的changeData的bug导致的吗，还是更底层G2的bug？

G2

**Comment by inceptiongt** [comment]
> 不重新 render 会存在 axis 不清空的问题，这个其实是底层bug导致的~！

重新render是不是把changeData里面做的render工作又重新做了一遍？

**Comment by inceptiongt** [comment]
> 不重新 render 会存在 axis 不清空的问题，这个其实是底层bug导致的~！

这个bug麻烦给个复现的例子。
G2Plot网站上的例子：https://codesandbox.io/s/cq9s3f，axis是没问题的。

**Comment by lxfu1** [comment]
> > 不重新 render 会存在 axis 不清空的问题，这个其实是底层bug导致的~！
> 
> 这个bug麻烦给个复现的例子。 G2Plot网站上的例子：https://codesandbox.io/s/cq9s3f ，axis是没问题的。

https://github.com/ant-design/ant-design-charts/pull/1600

**Comment by inceptiongt** [comment]
> > > 不重新 render 会存在 axis 不清空的问题，这个其实是底层bug导致的~！
> > 
> > 
> > 这个bug麻烦给个复现的例子。 G2Plot网站上的例子：https://codesandbox.io/s/cq9s3f ，axis是没问题的。
> 
> #1600

我看G2Plot里render的时候好像把axis和legend 都清空了，咋还有呢https://github.com/antvis/G2Plot/blob/1b0a0a966a1d50102197b53463907f0b6a48df1a/src/core/plot.ts#L147-L168
所以说这是G2的bug了？
changeData里render一次，又再次render，从Chrome Performance面板看这两次耗时差不多，导致两倍耗性能。
我现在业务是Drawer组件里面好几个chart，页面卡顿严重，得想想办法了。

**Comment by lxfu1** [comment]
> > > > 不重新 render 会存在 axis 不清空的问题，这个其实是底层bug导致的~！
> > > 
> > > 
> > > 这个bug麻烦给个复现的例子。 G2Plot网站上的例子：https://codesandbox.io/s/cq9s3f ，axis是没问题的。
> > 
> > 
> > #1600
> 
> 我看G2Plot里render的时候好像把axis和legend 都清空了，咋还有呢https://github.com/antvis/G2Plot/blob/1b0a0a966a1d50102197b53463907f0b6a48df1a/src/core/plot.ts#L147-L168 所以说这是G2的bug了？ changeData里render一次，又再次render，从Chrome Performance面板看这两次耗时差不多，导致两倍耗性能。 我现在业务是Drawer组件里面好几个chart，页面卡顿严重，得想想办法了。

你锁定一下版本试试 @ant-design/plots@1.2.2

**Comment by wozien** [comment]
所以要用旧版本，就是这个render每次数据更新都要重新执行一遍初始动画，闪一下，很不友好
