### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')  at Container.getCount 🧐[问题]

### ISSUE THREAD

**Issue by aseph8083** [ant-design/ant-design-charts#1838]
i'm using nextjs 12 typescript, when I use the Funnel plot chart, when the label property is used an error occurs Cannot read properties of undefined (reading 'length') at Container.getCount, but when my label is set to false no error occurs
![image](https://user-images.githubusercontent.com/87680962/221772189-8e6df85d-3bb5-4489-b465-28194041ec28.png)

![image](https://user-images.githubusercontent.com/87680962/221772043-f6e5a93a-595e-4321-b0f6-e761541a17cf.png)

Call Stack
Container.getCount
node_modules\@antv\g-base\esm\abstract\container.js (373:0)
eval
node_modules\@antv\g2\esm\component\update-label.js (50:0)
each
node_modules\@antv\util\esm\each.js (10:0)
updateLabel
node_modules\@antv\g2\esm\component\update-label.js (49:8)
eval
node_modules\@antv\g2\esm\component\labels.js (82:47)
each
node_modules\@antv\util\esm\each.js (19:0)
Labels.eval
node_modules\@antv\g2\esm\component\labels.js (69:28)
step
node_modules\tslib\tslib.es6.js (102:0)
Object.eval [as next]
node_modules\tslib\tslib.es6.js (83:45)
fulfilled
node_modules\tslib\tslib.es6.js (73:42)

**Comment by lxfu1** [comment]
提供个复现参考： https://codesandbox.io/s/youthful-cherry-083bjy?file=/index.js

**Comment by aseph8083** [comment]
> 提供个复现参考： https://codesandbox.io/s/youthful-cherry-083bjy?file=/index.js

if using codesandbox there is no problem, but when using nextjs typescript live project there is error like that, but I solved it temporarily using renderer: "canvas",

**Comment by lxfu1** [comment]
> > 提供个复现参考： https://codesandbox.io/s/youthful-cherry-083bjy?file=/index.js
> 
> if using codesandbox there is no problem, but when using nextjs typescript live project there is error like that.

https://github.com/ant-design/ant-design-charts/pull/1600

**Comment by kemisstep** [comment]
+1 同样的问题

**Comment by kemisstep** [comment]
> 提供个复现参考： https://codesandbox.io/s/youthful-cherry-083bjy?file=/index.js

请问后面怎么解决的？

**Comment by kemisstep** [comment]
> > 提供个复现参考： https://codesandbox.io/s/youthful-cherry-083bjy?file=/index.js
> 
> if using codesandbox there is no problem, but when using nextjs typescript live project there is error like that.

请问后面怎么解决的？

**Comment by hibluesea** [comment]
i have got the same issue when using DualAxes component in next.js. is there any one deal with the problem since the issue has been open for ten month.

**Comment by hraj6056** [comment]
Any update on this issue, i am using funnel chart in reactjs, and it's popping up.

**Comment by lxfu1** [comment]
Unable to reproduce, please provide a reproduction address, refer to https://github.com/Rujuu-prog/next13-antd-error

**Comment by pangjiancongl** [comment]
这个问题官方有修复吗
