### ISSUE TITLE
is there a special property to create an ellipsis if the label is too long on the yAxis? 🧐[问题]

### ISSUE THREAD

**Issue by aseph8083** [ant-design/ant-design-charts#1840]
when there is a long label like the picture
![image](https://user-images.githubusercontent.com/87680962/222034011-291cd8dc-3e38-4db6-aff6-003fd4503968.png)

can it be formatted like this?
![image](https://user-images.githubusercontent.com/87680962/222034103-cceb3b4f-7e33-463c-8287-be5d0dce64e0.png)

Or does it have to be formatted manually?

if i try to use following property its not working
`yAxis: {
      label: {
        autoEllipsis: true,
        autoHide: true,
      }
    },`

**Comment by lxfu1** [comment]
`yAxis.label.formatter: (label) => label.substr()`
