### ISSUE TITLE
👑 Is there any way to change the Type of node graph dynamically using fetched data?

### ISSUE THREAD

**Issue by eisa-rezaei** [ant-design/ant-design-charts#1841]
![image](https://user-images.githubusercontent.com/78264204/222068818-38678bfe-278d-47eb-a271-a3219f2de2d5.png)
is there any way to do this ?

**Comment by lxfu1** [comment]
![image](https://user-images.githubusercontent.com/31396322/222076710-6794f2b9-432d-46a7-8ac3-58cd617527e7.png)

**Comment by eisa-rezaei** [comment]
@lxfu1  Thanks for your answer. I have tasted this before but it wasn't working the issue was style disappears when a state changes like loading.

**Comment by lxfu1** [comment]
Could'y provider an online demo?

**Comment by eisa-rezaei** [comment]
@lxfu1 https://codesandbox.io/s/eloquent-roman-2quh3e?file=/index.js
the state changes ofter 2s and styles gone.

**Comment by lxfu1** [comment]
https://codesandbox.io/s/eloquent-moser-9wy0eh?file=/index.js
