### ISSUE TITLE
🐛[BUG] 官网来源去向图-节点类型的图标与内容不一致

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design-charts#1845]
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/37385554/222302550-c8bac352-22bf-4cbc-9c54-dca6052e9ee5.png">

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
后续更新一下
