### ISSUE TITLE
👑 [需求]交换瀑布图的X轴和Y轴

### ISSUE THREAD

**Issue by zhanghx0905** [ant-design/ant-design-charts#1847]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
你好，我希望能交换瀑布图的X轴和Y轴。举例而言，现在我在前端的图像是：

![image](https://user-images.githubusercontent.com/50790281/222328519-d7ffc256-176f-4f52-8580-5cc23f3ed432.png)

我希望交换图像的X轴和Y轴，交换之后的效果类似于（用Matplotlib绘制）

![666_lgbm_waterfall_plot](https://user-images.githubusercontent.com/50790281/222328601-f9e3ff8c-b799-4469-a1fc-d362b256ea63.png)

Antd目前似乎没有提供这种功能？能给我一些指引吗？

**Comment by lxfu1** [comment]
目前不支持
