### ISSUE TITLE
🐛[BUG]1.4.2官网示例：脑图报错

### ISSUE THREAD

**Issue by ted-1ted** [ant-design/ant-design-charts#1848]
地址：https://charts.ant.design/zh/examples/relation-graph/mind-map-graph#basic
![image](https://user-images.githubusercontent.com/126846279/222657946-47b28af8-a44f-42cb-9a41-602083e3d63d.png)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
getChildren 的配置先删除一下
