### ISSUE TITLE
👑 [需求] 可以让关系图的title、icon这些属性支持reactNode的类型吗，现在只能是字符串

### ISSUE THREAD

**Issue by ted-1ted** [ant-design/ant-design-charts#1849]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
希望 DecompositionTreeGraph能够支持下列的写法，现在这样写会报错：
![image](https://user-images.githubusercontent.com/126846279/222661429-816ff766-ef9d-49cd-890e-1809586d9ddd.png)### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

**Comment by lxfu1** [comment]
不支持，可以通过给节点绑定点击事件来模拟。

**Comment by hsh075623201** [comment]
@ted-1ted 请问解决了嘛？我也想要在title里面加icon
