### ISSUE TITLE
🐛[BUG] Crimea is Ukraine!

### ISSUE THREAD

**Issue by BrVolodymyr** [ant-design/ant-design-charts#1853]
**Crimea is Ukraine!**

**Оn this map _[Division Fill -> 2019 Europe pop-est](https://charts.ant.design/en/examples/map-area/division#europe-pop-est)_, the territory of the Crimean peninsula is marked as Russia, this is incorrect.**
Please see here [Wiki](https://en.wikipedia.org/wiki/Crimea)!

**Comment by valerii-sovytskyi** [comment]
Totally, this is major bug, how it possible to make such mistake, please resolve it ASAP, thanks!

**Comment by lzxue** [comment]
Sorry, we got the mistake data. Today we will fix this mistake.

**Comment by macaframaretard** [comment]
Crimea is Russia, it's not bug, it's feature

**Comment by BrVolodymyr** [comment]
> Sorry, we got the mistake data. Today we will fix this mistake.

**Comment by BrVolodymyr** [comment]
> Sorry, we got the mistake data. Today we will fix this mistake.

Sorry, but I don't see any changes!
