### ISSUE TITLE
🧐[问题]折线图和散点图复合图出现x轴对不上，x轴为时间

### ISSUE THREAD

**Issue by Merely-chao** [ant-design/ant-design-charts#1856]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
折线图和散点图复合图出现x轴对不上，x轴为时间，

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
[https://codesandbox.io/s/fast-butterfly-z8n14x?file=/index.js](https://codesandbox.io/s/fast-butterfly-z8n14x?file=/index.js)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![屏幕截图_20230311_115538](https://user-images.githubusercontent.com/39617057/224463561-d699d262-1f8a-4521-a5f4-be83341f730f.png)

**Comment by lxfu1** [comment]
meta.type 不要使用 time，可以用 xAxis.label.formatter 处理
