### ISSUE TITLE
👑 [需求] 可否支持环图的圆角可配置呢

### ISSUE THREAD

**Issue by libaofeng** [ant-design/ant-design-charts#1857]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
 G2是支持圆角配置的，但是antd chart 和 G2plot 目前都不支持

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
开放环图圆角的配置项

**Comment by lxfu1** [comment]
2.0  https://ant-design-charts-next.antgroup.com/examples/statistics/tiny/#ring
```ts
style: {
  radius: 5
}
```
