### ISSUE TITLE
🧐[问题] 分组柱状图设置滚动条，但是滚动条无法拖动，滚动条的宽度直接沾满整一个容器

### ISSUE THREAD

**Issue by zzq1101921989** [ant-design/ant-design-charts#1859]
### 🧐 问题描述
分组柱状图设置滚动条，但是滚动条无法拖动，滚动条的宽度等于容器宽度，这是什么问题？（数据量并没有官方案例这么多）

### 💻 示例代码
  const handlerData = () => {
    const data = [];
    for (let i = 0; i < 10; i++) {
      for (let j = 0; j < 12; j++) {
        data.push({
          month: `${j}月`,
          company: `分公司${i}`,
          value: parseInt(Math.random() * (1000 - 10) + 10),
        });
      }
    }
    return data;
  };

  const config: ColumnConfig = {
    data: handlerData(),
    isGroup: true,
    xField: 'company',
    yField: 'value',
    seriesField: 'month',
    dodgePadding: 2,
    xAxis: {
      label: {
        autoRotate: false,
      },
    },
    scrollbar: {
        type: 'horizontal'
    }
  };

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/48540122/224686265-8043c0c6-17c5-4572-9eca-23319d2c04eb.png)

**Comment by lxfu1** [comment]
用 slider
