### ISSUE TITLE
🧐[问题]GroupedColumnLine使用setData之后没有刷新图表

### ISSUE THREAD

**Issue by 495640129** [ant-design/ant-design-charts#186]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
GroupedColumnLine使用setData之后没有刷新图表
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
const [data, setData] = useState([[
    {time: '2019-03', value: 350, type: '计划'},
    {time: '2019-04', value: 900, type: '计划'},
    {time: '2019-05', value: 300, type: '计划'},
    {time: '2019-06', value: 450, type: '计划'},
    {time: '2019-07', value: 470, type: '计划'},
    {time: '2019-03', value: 220, type: '实际'},
    {time: '2019-04', value: 300, type: '实际'},
    {time: '2019-05', value: 250, type: '实际'},
    {time: '2019-06', value: 220, type: '实际'},
    {time: '2019-07', value: 362, type: '实际'},
  ], [
    {time: '2019-03', 达成率: 20, type: '实际1'},
    {time: '2019-04', 达成率: 40, type: '实际1'},
    {time: '2019-05', 达成率: 60, type: '实际1'},
    {time: '2019-06', 达成率: 70, type: '实际1'},
    {time: '2019-07', 达成率: 90, type: '实际1'},
  ]]);

const config = {
    title: {
      visible: true,
      text: '消耗额',
    },
    description: {
      visible: true,
      text: '消耗额情况',
    },
    meta: {
      达成率: {
        formatter: (v) => {
          return `${v}%`
        }
      },
    },
    data,
    xField: 'time',
    yField: ['value', '达成率'],
    xAxis: {
      title: {
        visible: false,
      },
    },
    lineSize: 1,
    legend: {
      visible: true,
      text: {
        // formatter: (text, aa, bb) => {
        //   console.log(text, aa, bb);
        // }
      }
    },
    tooltip: {
      visible: true,
      shared: true,
      showCrosshairs: true,
      crosshairs: {
        type: 'y'
      },
      offset: 20,
      // fields: ['time', 'type', 'value', 'proportion'],
      // formatter: (xField, yField, seriesField, seriesField2) => {
      //   console.log(xField, yField, seriesField, seriesField2);
      //   return {name:seriesField,value:yField};
      // }
    },
    columnGroupField: 'type',
  };

//执行setData...
...........
<GroupedColumnLine {...config} memoData={data.length}/>
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/21274569/92232478-2ee47d80-eee1-11ea-94e0-d18abf3e2ae2.png)

**Comment by lxfu1** [comment]
设置了 memoData  之后， 只有 data.length 发生改变才会更新，length 一直为 2 所以不会更新。

**Comment by 495640129** [comment]
还有个问题，就是data的value都为0的时候，图表就不显示了，是不是个bug
const [data, setData] = useState([[
    {time: '2019-03', value: 0, type: '计划'},
    {time: '2019-04', value: 0, type: '计划'},
    {time: '2019-05', value: 0, type: '计划'},
    {time: '2019-06', value: 0, type: '计划'},
    {time: '2019-07', value: 0, type: '计划'},
    {time: '2019-03', value: 0, type: '实际'},
    {time: '2019-04', value: 0, type: '实际'},
    {time: '2019-05', value: 0, type: '实际'},
    {time: '2019-06', value: 0, type: '实际'},
    {time: '2019-07', value: 0, type: '实际'},
  ], [
    {time: '2019-03', 达成率: 20, type: '实际1'},
    {time: '2019-04', 达成率: 40, type: '实际1'},
    {time: '2019-05', 达成率: 60, type: '实际1'},
    {time: '2019-06', 达成率: 70, type: '实际1'},
    {time: '2019-07', 达成率: 90, type: '实际1'},
  ]]);
![image](https://user-images.githubusercontent.com/21274569/92317511-f4d7c080-f033-11ea-95e3-1ae0ead7ec01.png)

**Comment by 495640129** [comment]
![image](https://user-images.githubusercontent.com/21274569/92343907-996f0680-f0f7-11ea-84ec-d7824a55f155.png)

**Comment by lxfu1** [comment]
# 187
