### ISSUE TITLE
🐛[BUG]组织架构图，使用nodecfg的customContent自定义item时，出现意外效果

### ISSUE THREAD

**Issue by rocketsbigfan** [ant-design/ant-design-charts#1860]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
点击tree组件，动态加载数据，使用OrganizationGraph组件来展示对应的组织架构，为了实现ui效果
<img width="401" alt="image" src="https://user-images.githubusercontent.com/20547894/224727890-5019c412-4549-484d-8c27-307aec61ef9e.png">
用了customContent来写相关text，结果鼠标hover上去之后，背景色变了，且背景色无法复原（这不是我要的效果，我想的是鼠标hover上去，仅改变边框颜色，不改变背景色

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1.点击树组件
2.鼠标hover到item
3.bug就出现了。。

### 🏞 期望结果 [描述你原本期望看到的结果]
自定义item的相关样式能正确展示，鼠标hover事件正常出现

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

[线上示例](https://stackblitz.com/edit/react-szyrfc?file=index.js)

### © 版本信息

- ant-design-charts 版本: [1.4.0]
- 浏览器环境
- 开发环境 [ mac OS]

**Comment by rocketsbigfan** [comment]
破案了，addShape得加上name，有没有大佬能帮忙解释下为啥

**Comment by rocketsbigfan** [comment]
想问下，自定义的content，如何去水平垂直居中呀，
![image](https://user-images.githubusercontent.com/20547894/224918716-30ff4b20-ac03-4127-b97c-8dda3b148064.png)

**Comment by lxfu1** [comment]
可以调整 x、y的值，并设置文本对齐方式
![image](https://user-images.githubusercontent.com/31396322/225205654-8cda2614-8470-413b-9113-b849c3f70c77.png)
