### ISSUE TITLE
🐛[BUG] 水波图在Firefox浏览器上显示异常

### ISSUE THREAD

**Issue by IceLeach** [ant-design/ant-design-charts#1861]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/75960208/224863795-5bacd319-1098-4f50-9e27-0e739f480bc0.png)
设置percent: 0.25，实际显示占满

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://charts.ant.design/zh/examples/progress-plots/liquid#basic
设置renderer: 'svg'即可复现

### 🏞 期望结果 [描述你原本期望看到的结果]
水波图显示比例与设置的percent一致

### © 版本信息

- ant-design-charts 版本: 1.4.2
- 浏览器环境 Firefox 110.0.1
- 开发环境 Windows 10

**Comment by lxfu1** [comment]
`svg`  1.x 版本不稳定，先用 canvas
