### ISSUE TITLE
🐛[BUG] 配置蜘蛛布局展示标签没有正常展示

### ISSUE THREAD

**Issue by made-02** [ant-design/ant-design-charts#1864]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在饼图蜘蛛布局标签时，我想配置label只有第一项展示，配置不起来
![image](https://user-images.githubusercontent.com/56807957/225507959-1551fd75-cd7c-41e6-bcfc-b6e9abab01e3.png)
必须其他项也得给返回值才可以展示
但是在type = outer的时候是可以的
![image](https://user-images.githubusercontent.com/56807957/225508004-eefe5b45-e3ef-48f3-bb25-ea9c360cd8d4.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
官方示例
https://charts.ant.design/zh/examples/pie/basic#spider-label
![image](https://user-images.githubusercontent.com/56807957/225508170-4bb7e3ab-03d6-48a9-a843-000aeab4d234.png)
label.content配置 (data, c, index) => {
        if (index !== 0) {
          return ''
        }
        return (data.percent * 100).toFixed(2) + '%'
      },
    }
### 🏞 期望结果 [描述你原本期望看到的结果]
蜘蛛布局时也可以只展示前三个
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://charts.ant.design/zh/examples/pie/basic#spider-label
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lanqingYang** [comment]
遇到了相同的问题 有解决方式吗？

**Comment by jiangyh1024** [comment]
。。。我也有这种需求，值为0的 不显示。。 只能用outer了。。目前

**Comment by jiangyh1024** [comment]
@made-02  楼主有解决办法吗？

**Comment by lxfu1** [comment]
V2 https://ant-design-charts-next.antgroup.com/examples/statistics/pie/#spider-label
```ts
    label: {
      text: (d) => {
        if(d.type === '其他') {
          return `${d.type}\n ${d.value}`
        }
        return ''
      },
      connector: false, // conditional
      position: 'spider',
    },
```
