### ISSUE TITLE
🧐[问题]DualAxes 在使用slider配置时，line的样式混乱

### ISSUE THREAD

**Issue by luminous6** [ant-design/ant-design-charts#1866]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
已查看issus https://github.com/ant-design/ant-design-charts/issues/489, 还是不能解决
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/38565751/225657411-1adce53a-0ddf-41e4-9cee-a623f4e6aa9c.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/38565751/225657488-9a5f0c0c-11d8-4246-a16e-c7af775aa3a0.png">

**Comment by lxfu1** [comment]
感觉你数据有重复，先检测下数据或者提供个复现链接

**Comment by luminous6** [comment]
> 感觉你数据有重复，先检测下数据或者提供个复现链接

感谢回复🙏，确实是数据有重复情况所导致。

**Comment by jypblue** [comment]
问一下如何设置line的Y轴刻度因为跟着数据变化下串到slider滑轨上面，目前滚动一下line的线直接下串到底部去了
