### ISSUE TITLE
flowchart左侧节点

### ISSUE THREAD

**Issue by imaryan** [ant-design/ant-design-charts#1868]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
左侧自定义节点时，我需要多个节点，现在通过数组配置发现每个自定义节点下的组件会汇总在一起

**Comment by lxfu1** [comment]
```ts
registerNode: []
```

**Comment by kisslove** [comment]
@imaryan 通过此处源码可以认为是通过key作为分组，不传默认为空，导致组件重复汇总
https://github.com/antvis/XFlow/blob/9221e29e91dc82a055fc7d17b6c44945af633821/packages/xflow-extension/src/flowchart-node-panel/utils.tsx#LL101C25-L101C25

传入key就没问题了。
