### ISSUE TITLE
🐛[BUG]GroupedColumnLine图表，data[0]的value为0的时候，图表不显示

### ISSUE THREAD

**Issue by 495640129** [ant-design/ant-design-charts#187]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
GroupedColumnLine图表，data的value都为0的时候，图表就不显示了，是不是个bug
...
const [data, setData] = useState([[
{time: '2019-03', value: 0, type: '计划'},
{time: '2019-04', value: 0, type: '计划'},
{time: '2019-05', value: 0, type: '计划'},
{time: '2019-06', value: 0, type: '计划'},
{time: '2019-07', value: 0, type: '计划'},
{time: '2019-03', value: 0, type: '实际'},
{time: '2019-04', value: 0, type: '实际'},
{time: '2019-05', value: 0, type: '实际'},
{time: '2019-06', value: 0, type: '实际'},
{time: '2019-07', value: 0, type: '实际'},
], [
{time: '2019-03', 达成率: 20, type: '实际1'},
{time: '2019-04', 达成率: 40, type: '实际1'},
{time: '2019-05', 达成率: 60, type: '实际1'},
{time: '2019-06', 达成率: 70, type: '实际1'},
{time: '2019-07', 达成率: 90, type: '实际1'},
]]);
...
const config = {
title: {
visible: true,
text: '消耗额',
},
description: {
visible: true,
text: '消耗额情况',
},
meta: {
达成率: {
formatter: (v) => {
return ${v}%
}
},
},
data,
xField: 'time',
yField: ['value', '达成率'],
xAxis: {
title: {
visible: false,
},
},
lineSize: 1,
legend: {
visible: true,
text: {
// formatter: (text, aa, bb) => {
// console.log(text, aa, bb);
// }
}
},
tooltip: {
visible: true,
shared: true,
showCrosshairs: true,
crosshairs: {
type: 'y'
},
offset: 20,
// fields: ['time', 'type', 'value', 'proportion'],
// formatter: (xField, yField, seriesField, seriesField2) => {
// console.log(xField, yField, seriesField, seriesField2);
// return {name:seriesField,value:yField};
// }
},
columnGroupField: 'type',
};

....
dom:
<GroupedColumnLine {...config} memoData={JSON.stringify(data)}/>

### 🏞 期望结果 [描述你原本期望看到的结果]
value为0的时候也渲染出图表
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
 "@ant-design/charts": "^0.9.13",
- 浏览器环境
Google Chrome 版本 84.0.4147.135（正式版本） （64 位）
- 开发环境 [e.g. mac OS]
windows10 

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/21274569/92317541-60219280-f034-11ea-9b45-aeffb4af984a.png)

**Comment by 495640129** [comment]
![image](https://user-images.githubusercontent.com/21274569/92343897-96741600-f0f7-11ea-834e-483b49aafb2a.png)

**Comment by lxfu1** [comment]
删除 package-lock.json 重新 install 一下， 我测试了一下貌似没发现问题。

**Comment by lxfu1** [comment]
V 1.0: https://charts.ant.design/demos/dual-axes#%E5%A0%86%E5%8F%A0%E6%9F%B1%E7%BA%BF%E5%9B%BE%E8%A1%A8
