### ISSUE TITLE
资金流向图节点字体大小设置无效🐛[BUG]

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#1870]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

基于`nodeCfg`设置相关参数，对节点内文字无效：

![image](https://user-images.githubusercontent.com/49147660/226236133-c52ddcf7-3ad1-4bd4-9fa2-ff8679a04975.png)

### 🏞 期望结果 [描述你原本期望看到的结果]

可以对资金流向图中节点的字体相关参数作有效设置

**Comment by lxfu1** [comment]
这个还没升级， 先临时解决一下
```ts
nodeCfg: {
  label: {
    style: {
      fontSize: 32
    }
  },
}
```
