### ISSUE TITLE
Global heat map error

### ISSUE THREAD

**Issue by vgs18** [ant-design/ant-design-charts#1872]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
The example global heat map is not loading in https://charts.ant.design/en/examples/map-heat/heatmap#global-2d

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/95902397/226513513-8a4825bc-a25b-467a-8af0-a7fa0eef23ca.png">

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/1681
