### ISSUE TITLE
请问，目前 ant-design-charts  支持鼠标右键功能吗？

### ISSUE THREAD

**Issue by 2020mythww** [ant-design/ant-design-charts#1873]
我是用的版本是ant-design-charts@1.4.2.js。
需求是这样，鼠标右键后，会在右键菜单中，多一个我自定义的功能。目前支持吗？

**Comment by 2020mythww** [comment]
![image](https://user-images.githubusercontent.com/67315275/226850284-42090ca9-0646-4c5b-8114-d1c2c6175851.png)
这种

**Comment by lxfu1** [comment]
```ts
    onReady: (plot) => {
      plot.on('contextmenu', ()=>{alert('123')})
    },
```
