### ISSUE TITLE
🧐[How to] How to add value and value in percentage in legend of donut chart

### ISSUE THREAD

**Issue by kennylelfw** [ant-design/ant-design-charts#1879]
Hi all, 

I would to add value and value in percentage in legend of donut chart as of in picture below. Please share the code if possible.

Thanks a lot!

![image](https://user-images.githubusercontent.com/108479342/227438684-6555e4df-5ec9-489f-b3f4-14f51b0a4559.png)

**Comment by lxfu1** [comment]
[Custom Legend](https://github.com/ant-design/ant-design-charts/issues/1169)

**Comment by 7NZ** [comment]
> [Custom Legend](https://github.com/ant-design/ant-design-charts/issues/1169)

有没有2.0版本的这个图例的自定义案例，这个2.0用不了？2.0好像没有formatter了，文档里面也没看到。
