### ISSUE TITLE
👑 [需求] Can I have the example code of Bullet

### ISSUE THREAD

**Issue by ngminhthanh12a3** [ant-design/ant-design-charts#1887]
I need the code of this Bullet Example. Thank you!

![image](https://user-images.githubusercontent.com/93377382/229264054-c340c00a-00fe-47c6-9aed-b1c1ccfe13cb.png)

[Example link](https://antv.antfin.com/zh-cn/vis/chart/bullet.html)

**Comment by PhoenixRiseA** [comment]
On first look, seems like they are formatting the y axis label. Although I tried with single bullet chart, It shows grid lines over the whole chart.

**Comment by PhoenixRiseA** [comment]
Did you achieve what you wanted to do? @ngminhthanh12a3

**Comment by ngminhthanh12a3** [comment]
> Did you achieve what you wanted to do? @ngminhthanh12a3

I want to use this sort of bullet plot to display values of environmental monitoring (CO2, CH20, temperature, humidity...).
I've tried to plot these values in multiple bullets in the same graph.
Currently, I can't do this. I manually draw the values in multiple graphs instead.

**Comment by ngminhthanh12a3** [comment]
Here is my chart for displaying values of environmental monitoring.
![image](https://github.com/ant-design/ant-design-charts/assets/93377382/65621fea-8349-4c38-a148-3388ae4d2112)

**Comment by PhoenixRiseA** [comment]
Actually you don't have to use multiple canvases, there is a way to do this with example, https://codesandbox.io/s/jovial-banzai-htsl4n . 
https://charts.ant.design/zh/examples/progress-plots/bullet/#grouped

**Comment by PhoenixRiseA** [comment]
I thought you were trying to achieve that bullet chart with axis labels, but grouped bullet chart is doable.

**Comment by ngminhthanh12a3** [comment]
Yes, these examples can group the bullets on the same canvas.
But these values are in the same range (from 0 to 120).
My displayed figures are in completely different ranges. It is like this.
![image](https://github.com/ant-design/ant-design-charts/assets/93377382/768aad2c-5c25-4a13-8c84-70e6be9634e7)

**Comment by lxfu1** [comment]
Implement using multiple individual bullets combined.
