### ISSUE TITLE
🐛[BUG] (legend -> selected) api not working on funnel chart 

### ISSUE THREAD

**Issue by ghost** [ant-design/ant-design-charts#1889]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
The api to configure which legend field to be selected is not working. 

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![Screenshot 2023-04-03 at 10 47 23 AM](https://user-images.githubusercontent.com/119552133/229400722-7dfab058-ddab-4c90-bebd-e0b797b1a8bd.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
![Screenshot 2023-04-03 at 10 47 35 AM](https://user-images.githubusercontent.com/119552133/229400750-253d0afa-882f-4eec-b680-b5aa3b784ea2.png)
Expected result is to only show '简历筛选', '初试人数', '复试人数' & '录取人数' while hiding "入职人数".

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://charts.ant.design/en/examples/more-plots/funnel#basic

### © 版本信息

- ant-design-charts 版本: 1.4.2
- 浏览器环境 : Version 111.0.5563.146 Chrome
- 开发环境 mac OS

**Comment by lxfu1** [comment]
V1 Funnel 不支持这个配置的，可以试试 V2 的自定义 [legend filter](https://codesandbox.io/p/sandbox/sleepy-hamilton-cfxyqw)
