### ISSUE TITLE
Title of Bubble Chart does not wrap properly

### ISSUE THREAD

**Issue by jonborchardt** [ant-design/ant-design-charts#189]
![image](https://user-images.githubusercontent.com/8194065/92629600-69546e80-f283-11ea-98cd-19179f9351ba.png)

is there a way to style the title's wrapping component so that it wraps properly?
```
const config = {
        title:  {
                  visible: true,
                  text: props.title  // <-- proposal is to make this an element instead of a string... and/or wrap the text properly
              },
       ...}
```

**Comment by lxfu1** [comment]
Proposal is use custom ReactNode, we will remove title  config at v2。

**Comment by jonborchardt** [comment]
Can you provide an example of how to use a ReactNode?
