### ISSUE TITLE
🐛[BUG]面积图中的百分比isPercent如何设置，示例好像并不正确

### ISSUE THREAD

**Issue by hui-huo** [ant-design/ant-design-charts#1892]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

<img width="861" alt="image" src="https://user-images.githubusercontent.com/55521126/229777785-8bdd1b49-7115-4a79-86c6-d6636d1553b5.png">

**Comment by lxfu1** [comment]
你这个是堆叠的，isStack: false 试试
