### ISSUE TITLE
🐛[BUG] - Unable to see docs for a graph in updated website

### ISSUE THREAD

**Issue by akshatjoshihbd** [ant-design/ant-design-charts#1900]
**Issue**: After a recent change in the website, it seems the docs are not visible for a graph.

**Description**: Earlier, under examples, when an example graph was clicked, the playground used to be at the bottom and the docs for that graph on the right side. But now, the playground has been moved to the right side and the the docs are not visible anywhere. Is this a known change and have the docs been moved to some other location in the website?

**Comment by lxfu1** [comment]
Take a look at the [API](https://ant-design-charts.antgroup.com/api/graphic-style) temporarily, we will update it later

**Comment by akshatjoshihbd** [comment]
Sure @lxfu1 
Request you to pls fix this on priority since the docs are required to work with the charts properly.

**Comment by ChristopherTeague** [comment]
I agree, please make this a priority.

**Comment by lxfu1** [comment]
V2

![image](https://github.com/ant-design/ant-design-charts/assets/31396322/1d6c0bb1-2813-4b97-b444-921d53cf0839)
