### ISSUE TITLE
🐛[BUG]和antdesign5.0版本冲突

### ISSUE THREAD

**Issue by fangj** [ant-design/ant-design-charts#1901]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
安装antdesign5.0后，安装ant-design-charts报错

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
安装 "antd": "^5.4.0",
安装 "@ant-design/icons": "^5.0.1",
再安装 npm install @ant-design/charts --save
收到错误
warning " > @ant-design/charts@1.4.2" has incorrect peer dependency "@ant-design/icons@^4.6.0".
warning " > @ant-design/charts@1.4.2" has incorrect peer dependency "antd@^4.6.3".
warning " > @ant-design/charts@1.4.2" has unmet peer dependency "lodash@^4.17.20".

### 🏞 期望结果 [描述你原本期望看到的结果]
ant-design-charts 能和antdesign5.0共同安装

### © 版本信息

- ant-design-charts 版本: [1.4.2]
- ant-design/icons 版本:  [5.0.1]
- ant-design 版本:  [5.4.1]
- 浏览器 chrome
- 开发环境 [windows]

**Comment by xu756** [comment]
我昨天也遇到了这个问题  
删除  node_modules（package.json的dependencies antd行也删掉）
先安装 ant-design/charts 然后再安装 antd
再 npm i就好了

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/1689
