### ISSUE TITLE
🧐[问题]请问迷你进度条图如何添加tooltip

### ISSUE THREAD

**Issue by hewitt99** [ant-design/ant-design-charts#1904]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
已经给其他的迷你图(迷你柱图、迷你面积图 )通过toooltip:{  customContent:   }，显示了想要的展示的“key”： “value”。
但是进度条图无法通过该属性展示

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://ant-design-charts.antgroup.com/examples/tiny/progress/#progress

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
提前感谢解答

**Comment by lxfu1** [comment]
https://codesandbox.io/s/intelligent-goodall-km7jkr
