### ISSUE TITLE
🧐[问题]柱状图的坐标参考线可以改成虚线吗？

### ISSUE THREAD

**Issue by ggclearlove** [ant-design/ant-design-charts#1906]
![R4~GX@J)3U605CE2`JQD0@9](https://user-images.githubusercontent.com/44995694/231414343-d0077607-eba0-4b59-9a13-8815bc737fb2.png)

**Comment by lxfu1** [comment]
```ts
 yAxis: {
      grid: {
        line: {
          style: {
            lineDash: [2, 4]
          }
        }
      }
    },
```

**Comment by ggclearlove** [comment]
请问在哪里看呀，api没找到这个

**Comment by ggclearlove** [comment]
> ```ts
>  yAxis: {
>       grid: {
>         line: {
>           style: {
>             lineDash: [2, 4]
>           }
>         }
>       }
>     },
> ```

请问在哪里看呀？api没找到这个
