### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by MariyamMaj** [ant-design/ant-design-charts#1907]
<img width="1420" alt="Screenshot 2023-04-12 at 3 20 25 PM" src="https://user-images.githubusercontent.com/125335225/231444136-f75382dc-9b3e-4844-8078-6a06c7ffda16.png">

-I introduced my own custom legend in to the canvas
- And gave a style to the pie config. In styling when I give a width property and decreased the size of the pie chart, the tooltip flickers and doesn't appear properly. 
- The tooltip that has to appear when hovered on top of the pie chart- is not appearing when width style is applied in the pie config.
- Tooltip appears in all parts of the pie chart except the top part of the pie chart..it flickers and shows a text-cursor on top of the pie chart.

**Comment by vipin-msec** [comment]
Can you please share Codesendbox link

**Comment by lxfu1** [comment]
Invalid issue, provide `Codesendbox link`  and reopen
