### ISSUE TITLE
🧐[问题]如何在ant design pro v6.0.0上使用

### ISSUE THREAD

**Issue by kindlejiang** [ant-design/ant-design-charts#1910]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

如何在ant design pro v6.0.0上使用

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
强制安装后运行，提示如下：
Module "./@ant-design/charts" does not exist in container. while loading "./@ant-design/charts" from webpack/container/reference/mf

**Comment by unStarCN** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/78009357/57e7b0cd-f8f3-49dc-9796-dc1e1c9bca8e)
一装上就报错....不知道什么原因

**Comment by unStarCN** [comment]
感觉是他内部代码有点问题

**Comment by lxfu1** [comment]
复现能提供一下吗？或者删除整个node_modules重新安装试试，把@ant-design/charts换成@ant-design/plots

**Comment by grisbyedginid** [comment]
我的项目报错是@ant-design/plots，我在 package.json dependencies 固定版本 "@ant-design/plots": "1.0.2" 就解决了

**Comment by lxfu1** [comment]
[试试2.0，有问题跪求提供复现地址](https://ant-design-charts-next.antgroup.com/)
