### ISSUE TITLE
🧐[问题] 每次import复杂图组件都会出现no exported member错误，如何解决？

### ISSUE THREAD

**Issue by jazwu** [ant-design/ant-design-charts#1915]
### 🧐 问题描述 

我在引入 折现柱状堆叠混合图StackedColumnLine组件 时，出现报错：Module '"@ant-design/charts"' has no exported member 'StackedColumnLine'，但引入基础图Line, Column就没有问题，请问如何解决？

另外想问问大家，如果我想要自己实现两张图显示在一张图上这个功能，要怎么做呢？

### 💻 示例代码

![image](https://user-images.githubusercontent.com/113967503/232373428-0de3195b-f532-4214-8fa7-7f0231364bbb.png)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

 @ant-design/charts 版本 1.4.2

**Comment by lxfu1** [comment]
版本不对，你这个是 0.x 版本的组件

**Comment by thugbobby** [comment]
解决了么这个问题
