### ISSUE TITLE
🧐[问题]折线图x轴坐标左侧间距如何设置为0

### ISSUE THREAD

**Issue by sawafish** [ant-design/ant-design-charts#1917]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
折线图x轴坐标左侧和y轴总是有个间距，这个间距可以设置为0吗
![image](https://user-images.githubusercontent.com/27727043/232657407-c5dcdedb-78a0-4cd1-b901-4aaf6759717c.png)

**Comment by lxfu1** [comment]
https://ant-design-charts.antgroup.com/manual/faq#4%E6%80%8E%E4%B9%88%E8%AE%BE%E7%BD%AE%E6%A8%AA%E8%BD%B4%E4%BB%8E-0-%E5%BC%80%E5%A7%8B

**Comment by sawafish** [comment]
> https://ant-design-charts.antgroup.com/manual/faq#4%E6%80%8E%E4%B9%88%E8%AE%BE%E7%BD%AE%E6%A8%AA%E8%BD%B4%E4%BB%8E-0-%E5%BC%80%E5%A7%8B

感谢
