### ISSUE TITLE
🐛[BUG] 文档错误

### ISSUE THREAD

**Issue by txp1035** [ant-design/ant-design-charts#1919]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

![image](https://user-images.githubusercontent.com/9554297/233048527-b7f5e5f0-f454-46aa-9de6-f6f324e755c5.png)

链接：https://charts.ant.design/examples/column/stacked/#basic
引用错误

### 🏞 期望结果 [描述你原本期望看到的结果]

应该是`import { Column } from '@ant-design/charts';`

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
@ant-design/plots 是 @ant-deign/charts 的一个子包，也是推荐用法噢

**Comment by txp1035** [comment]
> @ant-design/plots 是 @ant-deign/charts 的一个子包，也是推荐用法噢

![image](https://user-images.githubusercontent.com/9554297/233071617-1ec36d00-d34d-4314-a7cb-23166e4833d1.png)

![image](https://user-images.githubusercontent.com/9554297/233071712-fc0d7f63-4010-4273-8e3c-d3366eb58396.png)
那说明有冲突，推荐用法不一样

**Comment by txp1035** [comment]
大致拆包作用我是理解了，看使用情况如果多子包用就用chart？话说这个东西不能treesharking吗？拆包作用是减少大小？
