### ISSUE TITLE
🧐[问题] 图表示例中的图表和代码还有api的布局调整控制功能怎么不见了啊

### ISSUE THREAD

**Issue by monologue-web** [ant-design/ant-design-charts#1920]
### 🧐 问题描述 
希望可以复原这个功能啊,感觉非常方便对照api调试图表📈的;或者加个开关自主去控制这个功能?

**Comment by lxfu1** [comment]
试一下V2版本哈

![image](https://github.com/ant-design/ant-design-charts/assets/31396322/e12a8d9a-cba1-41f1-ad7a-304badbd8891)
