### ISSUE TITLE
🐛[BUG] 链接无法打开

### ISSUE THREAD

**Issue by monologue-web** [ant-design/ant-design-charts#1921]
### 🐛 bug 描述
链接无法打开

### © 版本信息

- ant-design-charts 版本: [1.4.2]
- 浏览器环境
- 开发环境 [ mac OS]

### 🚑 其他信息 
customContent
可选 Function

支持自定义模板。[在线示例](https://charts.ant.design/zh/examples/case/customize#customize-tooltip)

![image](https://user-images.githubusercontent.com/52210420/233552477-fcafa430-0640-4307-9526-155787fa225b.png)

**Comment by lxfu1** [comment]
参考下这个，https://ant-design-charts.antgroup.com/examples/component/tooltip/#html-tooltip
