### ISSUE TITLE
🐛[BUG] Unexpected token 'export'  when running jest

### ISSUE THREAD

**Issue by matiasfacio** [ant-design/ant-design-charts#1922]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]  
Jest detects an expected token and test will fail

I have installed  "@ant-design/plots": "^1.2.5",
I already removed  "@ant-design/charts", but the problem did not go away

### © 版本信息

  Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/matias/Documents/GitHub/work-dashboard/node_modules/@antv/g-base/node_modules/d3-interpolate/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export {default as interpolate} from "./value.js";
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/@antv/g-base/src/animate/timeline.ts:3:1)

Could anyone help me here, please?

**Comment by ashishshukla7** [comment]
Do we have any update to fix this issue?

**Comment by matiasfacio** [comment]
> Do we have any update to fix this issue?

hey @ashishshukla7 what helped me was to mock the imports in my test. Like this:

`jest.mock('@ant-design/plots', () => ({
	Column: () => null,
	ColumnConfig: () => null,
}));`
