### ISSUE TITLE
🧐[问题] ant-design-chart 从2022-07-19 到现在都没有更新过，是有什么变动吗？后续的更新维护计划可以透露一下吗？

### ISSUE THREAD

**Issue by Gzbox** [ant-design/ant-design-charts#1934]

**Comment by YuZongYangHi** [comment]
一堆问题。

**Comment by Gzbox** [comment]
> 一堆问题。

嗯 和 antd5 跟进还不及时  希望能公布一些后续的计划    想切回Echart 又不太甘心  哈哈  想用 antd 全家桶 😄

**Comment by lxfu1** [comment]
目前底层依赖在做升级，预计8月会推出2.0版本，Ant Design Charts 本身只是一个壳，子包是有在更新的。

**Comment by Gzbox** [comment]
> 目前底层依赖在做升级，预计8月会推出2.0版本，Ant Design Charts 本身只是一个壳，子包是有在更新的。

好的  静待新版本发布。希望能超预期时间发布 😄 辛苦了

**Comment by zhengmenghuang** [comment]
> > 目前底层依赖在做升级，预计8月会推出2.0版本，Ant Design Charts 本身只是一个壳，子包是有在更新的。
> 
> 好的 静待新版本发布。希望能超预期时间发布 😄 辛苦了 能订一个issues 说明一下就更好了

已经11月份了

**Comment by Gzbox** [comment]
> > > 目前底层依赖在做升级，预计8月会推出2.0版本，Ant Design Charts 本身只是一个壳，子包是有在更新的。
> > 
> > 
> > 好的 静待新版本发布。希望能超预期时间发布 😄 辛苦了 能订一个issues 说明一下就更好了
> 
> 已经11月份了

还好在我项目上线之前我下决心换回 EChart 啦  😄

**Comment by zhengmenghuang** [comment]
> > > > 目前底层依赖在做升级，预计8月会推出2.0版本，Ant Design Charts 本身只是一个壳，子包是有在更新的。
> > > 
> > > 
> > > 好的 静待新版本发布。希望能超预期时间发布 😄 辛苦了 能订一个issues 说明一下就更好了
> > 
> > 
> > 已经11月份了
> 
> 还好在我项目上线之前我下决心换回 EChart 啦 😄

是真的不好用 一堆坑要踩 我也换EChart算了 何必为难自己？

**Comment by Kevin9703** [comment]
已经2月份了

**Comment by lxfu1** [comment]
> 已经2月份了

V2 去年就发布了~  https://ant-design-charts-next.antgroup.com/
