### ISSUE TITLE
🐛[BUG] 关系图右键菜单异常

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design-charts#1936]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
关系图node右键，弹窗的菜单异常
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
官网示例 https://charts.ant.design/zh/examples/relation-graph/organization-graph/#basic 
![Screenshot 2023-05-09 151549](https://user-images.githubusercontent.com/6482819/237033854-0b115d3b-c292-4123-86e2-5cee8d6a786e.png)

### © 版本信息

- ant-design-charts 版本: [1.4.2]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by sawanoutsu** [comment]
现在还没更新这个bug吗？我看官网右键点击还是会有

**Comment by hhbusui** [comment]
> 现在还没更新这个bug吗？我看官网右键点击还是会有

可以直接找到dom然后 displayer: none隐藏

**Comment by Jackson-wjx** [comment]
如何配置菜单呢，看样子只是样式没绑上去
