### ISSUE TITLE
🐛[BUG] 关系图设置tooltip 频繁闪烁

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design-charts#1937]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
鼠标移动过程中，tooltip会闪烁

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
鼠标移动到node上显示tooltip，然后任意移动鼠标
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://stackblitz.com/edit/react-j7lwhc
### © 版本信息

- ant-design-charts 版本: [1.4.2]
- 浏览器环境 chrome 112
- 开发环境 [win 11]

**Comment by ChenKun1997** [comment]
@lxfu1 我看官网的例子不会闪，跑charts的源码也不会闪，官网是1.4.2版本的，npm上还是1.4.0，npm发一下包应该就没事了
![image](https://github.com/ant-design/ant-design-charts/assets/24249578/a852d672-a52d-4762-8be5-37b5fec60c55)
