### ISSUE TITLE
🐛[BUG] 增加slider模块导致tooltip.customContent获取到错误的数据

### ISSUE THREAD

**Issue by moon-xt** [ant-design/ant-design-charts#1938]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
增加slider模块导致tooltip.customContent获取到错误的数据
![image](https://github.com/ant-design/ant-design-charts/assets/47058891/f2173776-6661-44f9-8783-ac916da0a058)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
滑动slider，鼠标悬浮在柱状图上，获取的tooltip.customContent的items数据错误

### 🏞 期望结果 [描述你原本期望看到的结果]
数据无误

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/confident-snowflake-g6wtye?file=/index.js

### © 版本信息

- ant-design-charts 版本: 1.4.2
- 浏览器环境 chrome 113.0.5672.92
- 开发环境 mac OS

**Comment by lxfu1** [comment]
升级到[V2](https://ant-design-charts-next.antgroup.com/examples/statistics/column/#tooltip)吧

`slider: {x: {}}`
