### ISSUE TITLE
🧐[问题] ant-design -charts 中怎么使用 antv-g2plot 的 stateManager (状态管理机)？

### ISSUE THREAD

**Issue by glk-hll** [ant-design/ant-design-charts#194]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
不是说 ant-design -charts 基于 antv-g2plot 开发的吗？那么如何在 ant-design -charts 中怎么使用 antv-g2plot 的 stateManager (状态管理机)？文档上面只有一个有一个 通用配置/高级 的链接，跳的还是 antv-g2plot ？难道需要在项目中引入这两个库才能实现图表联动吗？

**Comment by lxfu1** [comment]
可以获取 chart 实例， https://charts.ant.design/guide/case#%E8%8E%B7%E5%8F%96-chart-%E5%AE%9E%E4%BE%8B
