### ISSUE TITLE
🧐[问题]神仙文档

### ISSUE THREAD

**Issue by jokeryZz** [ant-design/ant-design-charts#1940]
文档能不能描述的清楚一点，也太难懂了。
api找半天找不到。

**Comment by wozien** [comment]
+1

**Comment by xams-creator** [comment]
感觉都没人更新了一样

**Comment by woshiji1987** [comment]
文档直接去看g2 或者 g2plot, 都是从G一层一层包装上来的

**Comment by lanyaping** [comment]
找东西好难

**Comment by lxfu1** [comment]
可以试试最上层的[查询功能](https://ant-design-charts-next.antgroup.com/)，遇到问题欢迎加钉群讨论 44788198
