### ISSUE TITLE
Bar图表的刻度线配置变更，在React项目中，无法及时触发Bar图表的重新渲染🐛[BUG]

### ISSUE THREAD

**Issue by xiaopujun** [ant-design/ant-design-charts#1945]
### © 版本信息 :"@ant-design/charts": "^1.4.2",

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. win11]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/38376350/8e3b92b7-e6b0-4065-910b-9e6414f0dce5)

**Comment by lxfu1** [comment]
这个是底层BUG，建议升级到[ 2.0 版本](https://ant-design-charts-next.antgroup.com)
