### ISSUE TITLE
🧐[问题]使用堆积面积图时候，当第一个数据集为负数时候，无法正常堆叠

### ISSUE THREAD

**Issue by coder-sunrise** [ant-design/ant-design-charts#1947]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
使用堆积面积图时候，当第一个数据集为负数时候，无法正常堆叠
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Area } from '@ant-design/plots';

const DemoArea = () => {
  const [data, setData] = useState([]);

  useEffect(() => {
    asyncFetch();
  }, []);

  const asyncFetch = () => {
    setData([
      { "type": "probingDepth", "date": 0, "value": 0 },
      { "type": "probingDepth", "date": 1, "value": 0 },
      { "type": "probingDepth", "date": 2.7, "value": -2 },
      { "type": "probingDepth", "date": 3, "value": 0 },
      { "type": "probingDepth", "date": 4, "value": 0 },

      { "type": "gingivalDepth", "date": 0, "value": 0 },
      { "type": "gingivalDepth", "date": 1, "value": 0 },
      { "type": "gingivalDepth", "date": 2.7, "value": 1 },
      { "type": "gingivalDepth", "date": 3, "value": 0 },
      { "type": "gingivalDepth", "date": 4, "value": 0 },
    ])
  };
  const config = {
    data,
    xField: 'date',
    yField: 'value',
    tickLine: null,
    subTickLine: null,
    animate: false,
    tickCount: 0,
    legend: false,
    grid: null,
    color: ['#0000FF', '#FFFFFF'],
    seriesField: 'type', autoFit: false,
    
    height: 150,
    tooltip: false,
    xAxis: {
      line: false,
     type: 'quantize',
      tickInterval: 0.1,
      grid: {
        labels: null,
        line: false
      },
 
    },
    line:{
      color:['blue','red']
    },
    yAxis: {
      line: false,
      grid: {
        line: false
      },
      tickLine: false,
      min: -20,
      max: 20,
      visible: false,
    },
    areaStyle:{ 
      fill:'blue',
      fillOpacity:'0.5'
    },
    pattern :{
      fill:'orange'
    }
  };

  return <Area {...config} />;
};

ReactDOM.render(<DemoArea />, document.getElementById('container'));

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
ECharts有数据堆叠策略，不知道antd charts 有没有
以下是Echarts自定义堆叠策略的代码：
[series-line.](https://echarts.apache.org/zh/option.html#series-line) [stackStrategy](https://echarts.apache.org/zh/option.html#series-line.stackStrategy)  = 'samesign'string
从 v5.3.3 开始支持

堆积数值的策略，前提是[stack](https://echarts.apache.org/zh/option.html#series-line.stack)属性已被设置。其值可以是：

'samesign' 只在要堆叠的值与当前累积的堆叠值具有相同的正负符号时才堆叠。
'all' 堆叠所有的值，不管当前或累积的堆叠值的正负符号是什么。
'positive' 只堆积正值。
'negative' 只堆叠负值。

**Comment by lxfu1** [comment]
[V2 支持](https://ant-design-charts-next.antgroup.com/)
