### ISSUE TITLE
🧐[问题] 对于图表依赖的antd有升级到5的计划吗

### ISSUE THREAD

**Issue by LanJamRom** [ant-design/ant-design-charts#1948]

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/1689

**Comment by duwei54** [comment]
> #1689
@lxfu1 我看关联的issue 也没有说啥时候可以支撑呢,能否透漏一下么

**Comment by lxfu1** [comment]
关联的issue里面有临时方案，先看下能否解决你目前的问题

**Comment by duwei54** [comment]
> 关联的issue里面有临时方案，先看下能否解决你目前的问题

@lxfu1 临时方案不太行, 所以想看看官方有没有计划, 没有么换其他方案了 😄

**Comment by lxfu1** [comment]
> > 关联的issue里面有临时方案，先看下能否解决你目前的问题
> 
> @lxfu1 临时方案不太行, 所以想看看官方有没有计划, 没有么换其他方案了 😄

你有使用流程图吗？只有流程图会涉及antd，没有使用流程图的话，用对应子包就行
