### ISSUE TITLE
🧐[问题]来源去向图如何更改使title可以换行展示

### ISSUE THREAD

**Issue by Skylyun** [ant-design/ant-design-charts#1949]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
1.4.0 版本中，nodes里的value.title， 如何配置能够更改样式

**Comment by lxfu1** [comment]
```ts
value.title: 'xxx\nxxx'
```

**Comment by Skylyun** [comment]
尝试了，仍无效



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-charts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-charts] 🧐[问题]来源去向图如何更改使title可以换行展示 (Issue #1949)





 value.title: 'xxx\nxxx'

**Comment by Skylyun** [comment]
试了下，又可以了。
想请教一下： 如何控制css 样式去更改呀?想做到自动换行显示两行，第二行有...显示

**Comment by lxfu1** [comment]
不能通过CSS样式修改
