### ISSUE TITLE
🧐[问题]how to set min to yAxis for ColumnLine 

### ISSUE THREAD

**Issue by gww2020** [ant-design/ant-design-charts#195]
For ColumnLine, I need set min value for Line. It looks like the only thing I can so is to set min for yAxis, which is supposed to apply to both Y axis according to document. But it doesn't look like working. Can you help to let me know how to do this?

Here is my test code:

[DemoColumnLine.txt](https://github.com/ant-design/ant-design-charts/files/5242834/DemoColumnLine.txt)

**Comment by lxfu1** [comment]
```js
yAxis: {
    leftConfig: {
      min: -100,
      max: 2000
    }
  }
```

**Comment by gww2020** [comment]
Thanks, it works for leftConfig (for column),  but it looks like it doesn't work for the right axis, which is for line chart. Can you let me know what went wrong the the below config?
yAxis: {       rightConfig: {          min: 250,          max: 1000        },      }
Thanks.-Ping     On Thursday, September 17, 2020, 11:50:55 PM EDT, 柯南 <notifications@github.com> wrote:  
 
 

yAxis: {
    leftConfig: {
      min: -100,
      max: 2000
    }
  }

**Comment by lhsaq2009** [comment]
why ColumnLine without API in [column-line/API](https://antv-g2plot-v1.gitee.io/zh/examples/combo/column-line/API)

**Comment by lxfu1** [comment]
The new version is recommended.
