### ISSUE TITLE
👑 [需求] 希望坐标轴的title可以增加上下偏移

### ISSUE THREAD

**Issue by Lemon-Cai** [ant-design/ant-design-charts#1952]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
如图，如果设置了title，在极端情况下，title和坐标y轴的刻度有重叠，遮挡，希望可以给个方案解决这个问题
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/37281618/f1a2d361-8ae7-4b0b-86fc-db1fc6c24417)

**Comment by Mari-yun** [comment]
附议

**Comment by lxfu1** [comment]
2.0 https://ant-design-charts-next.antgroup.com/
```ts
    axis: {
      y: {
        title: '123',
        titleDx: 20
      }
    },
```

**Comment by Lemon-Cai** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/37281618/03529ad9-fd10-4a2f-96a4-45c3b4af7c59)


> 2.0 https://ant-design-charts-next.antgroup.com/
> 
> ```ts
>     axis: {
>       y: {
>         title: '123',
>         titleDx: 20
>       }
>     },
> ```

okok，该设置已生效，但文档好像还没有更新，要是文档更新后，使用上会更方便
![image](https://github.com/ant-design/ant-design-charts/assets/37281618/ed158666-c015-47b2-b74e-9953182b92b2)
