### ISSUE TITLE
🐛[BUG]Next.js error "Module not found: ESM packages (d3-interpolate) need to be imported. Use 'import' to reference the package instead"

### ISSUE THREAD

**Issue by Rujuu-prog** [ant-design/ant-design-charts#1956]
### 🐛 bug 描述 
Using @ant-design/charts, I get an error "Module not found: ESM packages (d3-interpolate) need to be imported. Use 'import' to reference the package instead".

I also tried the dynamic import method mentioned in the issue, but got the same error.

### 💻 复现代码
I have created a repository where the error occurs.
The main branch is for normal import, and the dynamic branch is for dynamic import.
I referred to #1771 for how to use dynamic import.

[Repository link](https://github.com/Rujuu-prog/next13-antd-error)

### © 版本信息

- "@ant-design/charts": "^1.4.2"
- "next": "13.4.4"
- "react": "18.2.0",

### Development environment
- Docker: 20.10.20
- M1 MacBook Air(Monterey 12.4)

### Error message
<img width="1244" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/81368541/d1d7e8e0-f79f-4acf-a3f0-46b5a3ebdf8f">

**Comment by aseph8083** [comment]
in my case, if using nextjs typescript, how to import antd chart should be like this 
`const Line = dynamic(
  () => import("@ant-design/plots").then((mod) => mod.Line) as any,
  { ssr: false }
);`

**Comment by Rujuu-prog** [comment]
Thank you for your comment.
I'm new to Typescript so my type definitions may be wrong, but I was able to successfully display the graph with the following code!
```typescript
import { LineConfig } from "@ant-design/plots/es/components/line";
const Line: React.ComponentType<LineConfig & React.RefAttributes<unknown>> =
  dynamic(() => import("@ant-design/plots").then((mod) => mod.Line) as any, {
    ssr: false,
  });
```
If anyone knows how to do the correct type definition, I'd appreciate it if you could let me know.
The entire modified code is [here](https://github.com/Rujuu-prog/next13-antd-error).

Thank you so much!

**Comment by Rujuu-prog** [comment]
One thing to note is that if you do not use "use client", you will get the same error message as below.

"Module not found: ESM packages (d3-interpolate) need to be imported. Use 'import' to reference the package instead"
