### ISSUE TITLE
🧐How to make column chart in dual axes

### ISSUE THREAD

**Issue by edikurniawan-dev** [ant-design/ant-design-charts#1961]
![image](https://github.com/ant-design/ant-design-charts/assets/50087198/2cd18e0d-18c5-45cd-891a-09c95a09bafa)

### 🧐 问题描述 [详细地描述问题，让大家都能理解]
How to make or setting chart look like above? in documentation i found dual axes column and line, but if dual axes using column and column not found, i try change the setting but column is stacked. How to solve?

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```
const configDualAxes = {
    data: [data, dataIrradiance],
    xField: 'date',
    yField: ['value', 'Irradiance'],
    geometryOptions: [
      {
        geometry: 'column',
        isGroup: true,
        seriesField: 'name',
        columnStyle: {
          radius: collectType === 'month' ? [2, 2, 2, 2] : [5, 5, 5, 5],
        },
        color: ['#34d399', '#f43f5e', '#38bdf8'],
      },
      {
        geometry: 'line',
        lineStyle: {
          lineWidth: 3,
        },
        smooth: true,
        color: '#fbbf24',
      },
    ],
    legend: {
      position: 'top',
    },
  };
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/50087198/27a1fdb3-2cf6-47ba-9db9-500201c3c96a)
if i change geometry from line to column
![image](https://github.com/ant-design/ant-design-charts/assets/50087198/62ba8851-6c13-416b-ab4f-7170208d1af2)

**Comment by lxfu1** [comment]
[2.0 supports arbitrary combinations](https://ant-design-charts-next.antgroup.com/examples/statistics/dual-axes/#basic)
