### ISSUE TITLE
🧐[问题]面积图中的这个line中是style要怎么使用，看描述是个function

### ISSUE THREAD

**Issue by qxz123456** [ant-design/ant-design-charts#1966]
![image](https://github.com/ant-design/ant-design-charts/assets/120540501/cbf809e8-dcdb-456e-abbc-72bc0723669b)
我想通过x轴的信息来使前半段是实线 后半段是虚线

**Comment by ai-qing-hai** [comment]
style 是 function 。 但针对的 是 分组和颜色分类。 lineDash 虚线对于一段线来说是分组了。

方案一、series 分组和style 回调结合 
![image](https://github.com/ant-design/ant-design-charts/assets/65594180/5f5aeb99-6f70-45f0-8954-8522477fa58e)
当然，图表复杂了，数据和 color 分类也需要重新写。
方案二、自定义shape， 通过 自定义的 shape 获取路径， 然后自己创建两个 Line 形状。
/**
 * A recreation of this demo: https://observablehq.com/@d3/line-chart
 */
import { Chart, register } from '@antv/g2';

register('shape.line.customShape', customShape);

function customShape(option, context) {
  return (points) => {
    const { document } = context.canvas;
    const g = document.createElement('g', {});

    const points1 = points.slice(0, 500);
    const points2 = points.slice(500, 1300);

    points1.forEach((p, index) => {
      const line1 = document.createElement('line', {
        style: {
          x1: p[0],
          y1: p[1],
          x2: points1[index + 1]?.[0],
          y2: points1[index + 1]?.[1],
          lineWidth: 1,
          stroke: 'blue',
        }
      })
      g.appendChild(line1);
    });
    points2.forEach((p, index) => {
      const line = document.createElement('line', {
        style: {
          x1: p[0],
          y1: p[1],
          x2: points2[index + 1]?.[0],
          y2: points2[index + 1]?.[1],
          lineWidth: 1,
          lineDash: [3, 4],
          stroke: 'red',
        }
      })
      g.appendChild(line);
    });

    return g;
  }
}

const chart = new Chart({
  container: 'container',
  autoFit: true,
});

chart
  .line()
  .data({
    type: 'fetch',
    value:
      'https://gw.alipayobjects.com/os/bmw-prod/551d80c6-a6be-4f3c-a82a-abd739e12977.csv',
  })
  .encode('x', 'date')
  .encode('y', 'close')
  .style({
    shape: 'customShape'
  });

chart.render();
