### ISSUE TITLE
🐛[BUG]rightConfig for yAxis does not work

### ISSUE THREAD

**Issue by gww2020** [ant-design/ant-design-charts#197]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
For ColumnLine, I need set min value for Line.  I tried the below config and it looks like only leftconfig (column) works.

yAxis: {
       leftConfig: {
          min: 700,
          max: 1000
        },
        rightConfig: {
          min: 700,
          max: 1000
        },
      }
### 🏞 期望结果 [描述你原本期望看到的结果]
I expect the min value for line chat is set to 700, but it's still 0.

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
[DemoColumnLine2.txt](https://github.com/ant-design/ant-design-charts/files/5261532/DemoColumnLine2.txt)

### © 版本信息

- ant-design-charts 版本: 0.9.13
- Chrome 85
- 开发环境: windows

**Comment by lxfu1** [comment]
Update and add customMeta config.
```ts
const config = {
    data: [uvData, transformData],
    xField: 'time',
    yField: ['value', 'count'],
    customMeta: true,
    yAxis: {
       leftConfig: {
          min: 700,
          max: 1000
        },
        rightConfig: {
          min: 700,
          max: 1000,
        },
      }
  };
```

**Comment by gww2020** [comment]
Hi, 
I  got the same graph with the updated config. Did I miss something?


Thanks.-Ping


    On Tuesday, September 22, 2020, 09:31:58 PM EDT, 柯南 <notifications@github.com> wrote:  
 
 


Update and add customMeta config.
const config = {
    data: [uvData, transformData],
    xField: 'time',
    yField: ['value', 'count'],
    customMeta: true,
    yAxis: {
       leftConfig: {
          min: 700,
          max: 1000
        },
        rightConfig: {
          min: 700,
          max: 1000,
        },
      }
  };

**Comment by lxfu1** [comment]
Delete package-lock.json and node_modules, then install, ensure dependencies @antv/g2plot version  is 1.1.28.
