### ISSUE TITLE
How to add annotations to Stacked Grouped Column

### ISSUE THREAD

**Issue by ashishshukla7** [ant-design/ant-design-charts#1978]
I am trying to add annotations to Stacked Grouped Column Plot (https://charts.ant.design/en/examples/column/grouped/#stacked)

I managed to do it by calculating x and x position manually but its not scalable as the calculation is varying based on Group Index. Below is the sample working code. 

`
import React from 'react';
import ReactDOM from 'react-dom';
import { Column } from '@ant-design/plots';

const DemoColumn = () => {
    const columnData = [
        {
            name: 'Type 1',
            key: 'Group1',
            value: 12.9,
            type: 'Type 1 - Free',
        },
        {
            name: 'Type 1',
            key: 'Group1',
            value: 10.9,
            type: 'Type 1 - Used',
        },
        {
            name: 'Type 4',
            key: 'Group1',
            value: 50.9,
            type: 'Type 2 - Used',
        },
        {
            name: 'Type 4',
            key: 'Group1',
            value: 32.4,
            type: 'Type 2 - Free',
        },
        {
            name: 'Type 3',
            key: 'Group1',
            value: 12.4,
            type: 'Type 3 - Used',
        },
        {
            name: 'Type 3',
            key: 'Group1',
            value: 12.4,
            type: 'Type 3 - Free',
        },
        {
            name: 'Type 4',
            key: 'Group2',
            value: 2.9,
            type: 'Type 4 - Used',
        },
        {
            name: 'Type 4',
            key: 'Group2',
            value: 5.9,
            type: 'Type 4 - Free',
        },
        {
            name: 'Type 5',
            key: 'Group2',
            value: 2.4,
            type: 'Type 5 _ Used',
        },
        {
            name: 'Type 5',
            key: 'Group2',
            value: 32.4,
            type: 'Type 5 - Free',
        },
        {
            name: 'Type 6',
            key: 'Group2',
            value: 42.4,
            type: 'Type 6 - Used',
        },
        {
            name: 'Type 6',
            key: 'Group2',
            value: 42.4,
            type: 'Type 6 - Free',
        },
        {
            name: 'Type 7',
            key: 'Group3',
            value: 2.9,
            type: 'Type 7 - Free',
        },
        {
            name: 'Type 7',
            key: 'Group3',
            value: 5.9,
            type: 'Type 7 - Used',
        },
    ];

    const annotations = [
        {
            content: 'Type 1',
            offsetY: -10,
            style: {
                fill: "rgba(0,0,0,0.85)",
                fontSize: 16,
                textAlign: "center"
            },
            type: "text",
            isVertical: false,
            rotate: -1.56,
            position: (xScale, yScale) => {
                return [`${xScale.scale('Group1') * 40}%`, 90];
            }
        },
        {
            content: '23.8',
            offsetY: -10,
            style: {
                fill: "rgba(0,0,0,0.85)",
                fontSize: 10,
                textAlign: "center"
            },
            type: "text",
            isVertical: false,
            position: (xScale, yScale) => {
                return [`${xScale.scale('Group1') * 55}%`, 72];
            }
        },
        {
            content: 'Type 2',
            offsetY: -10,
            style: {
                fill: "rgba(0,0,0,0.85)",
                fontSize: 16,
                textAlign: "center"
            },
            type: "text",
            isVertical: true,
            rotate: -1.56,
            position: (xScale, yScale) => {
                return [`${xScale.scale('Group1') * 85}%`, 60];
            }
        },
        {
            content: 'Type 3',
            offsetY: -10,
            style: {
                fill: "rgba(0,0,0,0.85)",
                fontSize: 16,
                textAlign: "center"
            },
            type: "text",
            isVertical: false,
            rotate: -1.56,
            position: (xScale, yScale) => {
                return [`${xScale.scale('Group1') * 125}%`, 88];
            }
        },
        {
            content: 'Type 4',
            offsetY: -10,
            style: {
                fill: "rgba(0,0,0,0.85)",
                fontSize: 16,
                textAlign: "center"
            },
            type: "text",
            isVertical: false,
            rotate: -1.56,
            position: (xScale, yScale) => {
                console.log("xScale.scale('Group2')", xScale.scale('Group2'));
                return [`${xScale.scale('Group2') * 80}%`, 96];
            }
        },
        {
            content: 'Type 5',
            offsetY: -10,
            style: {
                fill: "rgba(0,0,0,0.85)",
                fontSize: 16,
                textAlign: "center"
            },
            type: "text",
            isVertical: false,
            rotate: -1.56,
            position: (xScale, yScale) => {
                return [`${xScale.scale('Group2') * 95}%`, 83];
            }
        },
        {
            content: 'Type 6',
            offsetY: -10,
            style: {
                fill: "rgba(0,0,0,0.85)",
                fontSize: 16,
                textAlign: "center"
            },
            type: "text",
            isVertical: false,
            rotate: -1.56,
            position: (xScale, yScale) => {
                return [`${xScale.scale('Group2') * 110}%`, 58];
            }
        },
        {
            content: 'Type 7',
            offsetY: -10,
            style: {
                fill: "rgba(0,0,0,0.85)",
                fontSize: 16,
                textAlign: "center"
            },
            type: "text",
            isVertical: false,
            rotate: -1.56,
            position: (xScale, yScale) => {
                return [`${xScale.scale('Group3') * 97}%`, 95];
            }
        }
    ]

    const config = {
        width: 1000,
        autoFit: false,
        data: columnData,
        isStack: true,
        isGroup: true,
        xField: 'key',
        yField: 'value',
        seriesField: 'type',
        groupField: 'name',
        conversionTag: {},
        xAxis: {
            label: {
                autoHide: true,
                autoRotate: false,
            },
        },
        connectedArea: {
            style: (oldStyle, element) => {
                return {
                    fill: 'rgba(0,0,0,0.25)',
                    stroke: oldStyle.fill,
                    lineWidth: 0.5,
                };
            },
        },
        label: {
            position: 'middle',
            layout: [
                {
                    type: 'interval-adjust-position',
                },
                {
                    type: 'interval-hide-overlap',
                },
                {
                    type: 'adjust-color',
                },
            ],
        },
        title: {
            text: 'test',
            position: 'center',
            offset: -10
        },
        tooltip: {
            fields: ['type', 'value'],
            shared: false,
            formatter: (datum) => {
                return {name: datum.type, value: datum.value};

            }
        },
        annotations,
    };
    return <Column {...config} />;
};

ReactDOM.render(<DemoColumn/>, document.getElementById('container'));
`
I tried finding out better options using the documentation but was not very helpful.
Please suggest the best way to add annotations to the above graph.

**Comment by lxfu1** [comment]
https://ant-design-charts-next.antgroup.com/zh/examples/statistics/dual-axes/#custom-column-line

**Comment by Stephen-Strange** [comment]
@lxfu1 Could you please explain why is this closed? Is there any proper solution for this?
I am also facing the same issue. PFA some screenshots to refer. Here the annotations 2023, 2024 cannot be displayed under a particular bar/column due to its changing width

<img width="694" alt="Screenshot 2024-03-05 at 4 24 17 PM" src="https://github.com/ant-design/ant-design-charts/assets/74187417/6a214615-58a4-4f44-9302-ff9df3634b93">
<img width="607" alt="Screenshot 2024-03-05 at 4 24 32 PM" src="https://github.com/ant-design/ant-design-charts/assets/74187417/779326cc-4a48-4542-89db-4cdc43fa25be">
