### ISSUE TITLE
🐛[BUG]柱线混合图 meta中设置右坐标轴alias设置无效

### ISSUE THREAD

**Issue by chenmingjun** [ant-design/ant-design-charts#198]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
柱线混合图 meta中设置右坐标轴alias设置无效，左坐标轴没问题；
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
  meta: {
        time: {alias: '日期'},
        value: {alias: '数量'},
        count: {alias: '占比'},
      },
### 🏞 期望结果 [描述你原本期望看到的结果]
右坐标轴alias生效
### © 版本信息

- ant-design-charts 版本:  0.9.6
- 浏览器环境 Google Chrome版本 85.0.4183.102（正式版本）
- 开发环境  mac OS

**Comment by lxfu1** [comment]
参考这个： https://github.com/ant-design/ant-design-charts/issues/197
