### ISSUE TITLE
🐛[BUG]TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by zhangfu-git** [ant-design/ant-design-charts#1981]
<img width="913" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/19772048/d698d752-2334-40d6-90c6-118fa8f1ebc3">

### © 版本信息

- ant-design-charts 版本: [1.4.2]
- 浏览器环境 chrome版本 114.0.5735.133（正式版本） (x86_64)
- 开发环境 [mac OS]

**Comment by zhangfu-git** [comment]
传入data就不会报错了

**Comment by hoangviet1112** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/80023840/43137599-a7bb-43a0-a23f-236c2f2da412)
Hi @zhangfu-git I have passed in data but this bug is still remain, please help to resolve this.
