### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by tenmei18sai** [ant-design/ant-design-charts#1985]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
饼图的图例itemName 如何换行显示
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
`\n`，参考https://ant-design-charts-next.antgroup.com/examples/statistics/column/#legend
