### ISSUE TITLE
🐛[BUG]奇怪的堆叠面积图

### ISSUE THREAD

**Issue by holyeon** [ant-design/ant-design-charts#1988]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
<Area {...config} />输出奇怪的图形，WHY？

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
    const plotsData2 = [
        { meter: 0.3, value: 3, country: "test" },
        { meter: 1, value: 4, country: "test" },
        { meter: 1.4, value: 5, country: "test" },
        { meter: 3.8, value: 7, country: "test" },
        { meter: 4.5, value: 8, country: "test" },
        { meter: 5.2, value: 9, country: "test" },
        { meter: 5.5, value: 10, country: "test" },
        { meter: 5.9, value: 11, country: "test" },
        { meter: 6.2, value: 12, country: "test" },
        { meter: 6.6, value: 13, country: "test" },
        { meter: 11.4, value: 16, country: "test" },
        { meter: 19.3, value: 17, country: "test" },
        { meter: 22.1, value: 18, country: "test" },
        { meter: 28, value: 19, country: "test" },
        { meter: 32.4, value: 20, country: "test" },
        { meter: 40.7, value: 21, country: "test" },
        { meter: 42.1, value: 22, country: "test" },
        { meter: 45.9, value: 25, country: "test" },
        { meter: 46.2, value: 28, country: "test" },
        { meter: 60.7, value: 30, country: "test" },
        { meter: 61.8, value: 31, country: "test" },
        { meter: 66.9, value: 32, country: "test" },
        { meter: 68, value: 35, country: "test" },
        { meter: 68.7, value: 37, country: "test" },
        { meter: 83.9, value: 38, country: "test" },
        { meter: 84.2, value: 39, country: "test" },
        { meter: 93.9, value: 40, country: "test" },
        { meter: 97, value: 41, country: "test" },
        { meter: 97.3, value: 43, country: "test" },
        { meter: 110.4, value: 44, country: "test" },
    ];

    const config = {
        data: plotsData2,
        xField: 'meter',
        yField: 'value',
        seriesField: 'country',
    };

   return <Area {...config} />

     // 把 X、Y交换，输出更加奇怪的图形
    const config2 = {
        data: plotsData2,
        xField: 'value',
        yField: 'meter',
        seriesField: 'country',
    };
   return <Area {...config2} />

### © 版本信息

- ant-design-charts 版本: "@ant-design/charts": "1.4.2"
- 浏览器环境：firefox，chrome
- 开发环境：linux

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![Screenshot from 2023-07-10 10-10-09](https://github.com/ant-design/ant-design-charts/assets/15389754/ec9dbbba-3a2f-486f-a2b1-52354f4fc78f)
![Screenshot from 2023-07-10 10-09-35](https://github.com/ant-design/ant-design-charts/assets/15389754/ecfbf303-5757-461e-92b6-fc792a780e12)

**Comment by StevenRogers** [comment]
xField 不要使用number ,你加个""试试
