### ISSUE TITLE
🐛[BUG]分组柱+折线混合图中的多个折线的颜色相同

### ISSUE THREAD

**Issue by bennyb2sign** [ant-design/ant-design-charts#199]
### 📷 复现步骤 [官网上的示例本身就有这个问题，我本地测试和官网显示的结果是一样的，折线的颜色都是一样，没有区分
https://charts.ant.design/demos/combo#%E6%9F%B1%E7%BA%BF%E6%B7%B7%E5%90%88%E5%9B%BE-3]

### © 版本信息

- ant-design-charts 版本: [0.9.13]
- 浏览器环境 [chrom]
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
配置一下lineConfig: {} 或者根据数据自定义颜色
```ts
 lineConfig: {
      lineStyle: (name)=>{
        return {
          stroke: name === 'a' ? 'red' : 'yellow',
        }
      }
    }
```
