### ISSUE TITLE
🐛[BUG] 条形图在配置函数格式color时，滚动条显示异常？

### ISSUE THREAD

**Issue by wozien** [ant-design/ant-design-charts#1990]
### 🐛 如果配置 color 函数格式，带滚动条的条形图显示如下：
<img width="750" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/17634819/c89ddd6e-6261-489d-8fc0-81e9597ff82e">

字符串配置的话正常：
<img width="784" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/17634819/09eee0d7-d53b-464d-81c8-17e3d6126a3c">

最小复现demo： https://stackblitz.com/edit/vitejs-vite-lhusf8?file=src%2FApp.tsx

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
正确显示

### 🏞 期望结果 [描述你原本期望看到的结果]
和字符串配置的情况显示一致

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
升级到 V2 吧
