### ISSUE TITLE
折线图错位

### ISSUE THREAD

**Issue by whale-jung** [ant-design/ant-design-charts#1994]
复现地址：https://codesandbox.io/s/exciting-meninsky-75hyzz?file=/index.js

**Comment by whale-jung** [comment]
x轴2550和5200对应的值

**Comment by whale-jung** [comment]
@lxfu1 大佬麻烦帮忙看一下

**Comment by whale-jung** [comment]
把x轴为2550和5200对应的值删除，又会有新的数据错位

**Comment by CNFeffery** [comment]
@whale-jung 请参考：
![image](https://github.com/ant-design/ant-design-charts/assets/49147660/73914e66-fc13-4298-b1bf-32098ab9dbe6)

**Comment by whale-jung** [comment]
@

> @whale-jung 请参考： ![image](https://user-images.githubusercontent.com/49147660/252702078-73914e66-fc13-4298-b1bf-32098ab9dbe6.png)

感谢大佬，解决了
