### ISSUE TITLE
🐛[BUG] 为什么 axis.label 上有 autoEllipsis 属性却没有 maxLength 配置属性？

### ISSUE THREAD

**Issue by huarse** [ant-design/ant-design-charts#2005]
如题，坐标轴上的内容太长了，希望有一个配置能控制超长后省略，看到 有一个配置 `axis.label.autoEllipsis` ，但不知道这个的截取逻辑是什么，也没有地方能让我配置最大长度，我看另一个 `annotations.label` 上即有 autoEllipsis 又有 maxLength，不知道在 axis 上是不是漏掉了；

另外，虽然可以用 formatter 实现截取，但是无法直接用到 autoEllipsis 的 tips 效果

**Comment by hsp-sz** [comment]
autoEllipsis需要搭配size一起使用，只要你设置了size，就会根据size来自动缩略；具体参考文档：https://ant-design-charts-next.antgroup.com/options/plots/component/axis，【全局搜索autoEllipsis】属性：labelAutoEllipsis，描述：自动缩略刻度值，设置 size 值的时候生效
