### ISSUE TITLE
为什么找不到legend的文档🧐[问题]

### ISSUE THREAD

**Issue by LovelyPhoebe** [ant-design/ant-design-charts#2006]

**Comment by LovelyPhoebe** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/96405917/43da4c20-c110-43f5-ab2c-37cbef81aae1)

**Comment by hsp-sz** [comment]
你好，文档在这里：https://ant-design-charts-next.antgroup.com/options/plots/component/legend

**Comment by lxfu1** [comment]
[1.x API 里面查询 legend 关键字](https://ant-design-charts.antgroup.com/api/plots/line)
