### ISSUE TITLE
👑 [需求] 能不能把API文档的菜单弄的清楚一些

### ISSUE THREAD

**Issue by cxOrz** [ant-design/ant-design-charts#2007]
### 🥰 需求描述

像 Echarts 的文档一样，让人可以清晰的看到 a 属性在 abc 属性下面，abc 属性在 XYZ 属性下面，这种层级清晰的目录。
![image](https://github.com/ant-design/ant-design-charts/assets/32982052/ebd33db1-44f4-4e87-bcb8-bd91036c7cdb)

目前的文档，属性层级很不清晰，一下子全列出来，想知道某个属性到底写在哪个属性下很费劲。有加粗的、斜体的、加粗斜体的、四级标题、五级标题，他们显示在页面中很难区分，文档查起来很累而且容易搞错。
![image](https://github.com/ant-design/ant-design-charts/assets/32982052/8d4d681d-076d-480c-be5c-ae190c7605a9)

**Comment by cxOrz** [comment]
浏览器装 MD Reader 扩展，可以生成目录，直接访问仓库里文档对应的 md 文件就能看了。
![image](https://github.com/ant-design/ant-design-charts/assets/32982052/b58f1764-7c74-420e-a02d-07ab33f3a16b)

**Comment by liboliang01** [comment]
同感，官网文档不清晰，配置项也不全，有些外链到G2的链接都已经失效了还没有更新

**Comment by HuemengHm** [comment]
+1

**Comment by kogamitora** [comment]
这文档跟没有差不多，想改个属性完全不知道改哪

**Comment by thislucky** [comment]
+1

**Comment by lxfu1** [comment]
V2 版本我们在选项里面针对配置做了分组，示例页基于[AntV Theme](https://github.com/antvis/dumi-theme-antv)提供了预览功能，欢迎一起共建

![image](https://github.com/ant-design/ant-design-charts/assets/31396322/9856cddb-93ad-4c98-9d19-1819139ca33c)
