### ISSUE TITLE
👑 [需求]折线图brush-x不展示reload按钮

### ISSUE THREAD

**Issue by liboliang01** [ant-design/ant-design-charts#2009]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
在折线图使用交互brush-x后，不展示reset按钮，导致无法回退到图表的原始状态
效果和官网的散点图一样：[antd chart brush](https://charts.ant.design/examples/dynamic-plots/brush/#scatter-brush-filter)
![image](https://github.com/ant-design/ant-design-charts/assets/55911020/c7e185b6-23df-48ea-8cf4-0b37a7ea8824)
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
直接复用brush的逻辑就可以？

**Comment by lxfu1** [comment]
V2, `interaction: { brushFilter: true}`, Double click to reset.
