### ISSUE TITLE
customContent can't use jsx

### ISSUE THREAD

**Issue by RexHung0302** [ant-design/ant-design-charts#2012]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qktmsg?file=/chart.js)

### Steps to reproduce

I try to use JSX at label and tooltip, but show [object, Object], how can I use it?
我嘗試在 Chart 裡使用 JSX，但出現 [object, Object]，似乎不支援，該怎麼做呢？

### What is expected?

I want to render jsx on tooltip and label because I want to use i18n.
我想要透過 jsx 渲染一些畫面，因為我打算使用 i18n 或一些 hook.

### What is actually happening?

Show [object, Object].
目前使用 JSX 後，出現了 [object, Object].

![截圖 2023-08-03 上午11 49 11](https://github.com/ant-design/ant-design/assets/45451039/b6aa889b-e9fe-4c52-8347-f703403f2e43)

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18.2.0 |
| System | MacOS Ventura 13.3.1 |
| Browser | Chrome 115.0.5790.114 |

**Comment by lxfu1** [comment]
Label does not support JSX, you can refer to the implementation  of [V2](https://ant-design-charts-next.antgroup.com/zh/examples/statistics/column/#label-text)
