### ISSUE TITLE
🐛[BUG] Lowest value is not being plotted on Column chart

### ISSUE THREAD

**Issue by umair-mirza** [ant-design/ant-design-charts#2013]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

- ant-design-charts 版本: @ant-design/charts": "^1.4.2",

*Ant-Design charts version*: @ant-design/charts": "^1.4.2",

The lowest value is not being plotted for Column chart. I have tested this with different datasets but in every case, the lowest value is not visible on the chart.

![image](https://github.com/ant-design/ant-design-charts/assets/42217546/9f8c5181-f011-421f-a4b7-da5460f93b11)

The value 2 should be plotted on the chart but its not. In any case, the lowest value is not being plotted.

Here's the config for the chart:

```
import { Column } from '@ant-design/plots';
import { ColumnConfig } from '@ant-design/plots';

const ColumnChart = ({ data }) => {
  const brandColor = 'rgba(0, 176, 204, 0.12)';

  console.log('data', data);

  const config: ColumnConfig = {
    data,
    yField: 'value',
    xField: 'type',
    color: brandColor,
    legend: false,
    xAxis: {
      label: {
        autoHide: true,
        autoRotate: false,
      },
      grid: null,
    },
    yAxis: {
      grid: null,
    },
    tooltip: {
      showMarkers: true,
    },
    state: {
      active: {
        style: {
          fill: '#00B0CC',
          stroke: '',
        },
      },
    },
    interactions: [
      {
        type: 'element-active',
      },
    ],
    columnStyle: {
      radius: [4, 4, 0, 0],
    },
    slider: {
      start: 0,
      end: 1,
      formatter: () => ``,
    },
  };

  // eslint-disable-next-line react/jsx-props-no-spreading
  return <Column {...config} />;
};

export default ColumnChart;
```

Seems like a bug in the library. Has someone else experienced this issue?

**Comment by lxfu1** [comment]
Invalid issue, please provide data before reopening.
