### ISSUE TITLE
🧐[问题]怎么获取graphData呀？ 需要基于graphData 进行自定义侧边栏的编辑

### ISSUE THREAD

**Issue by owecbxz** [ant-design/ant-design-charts#2014]
目前只有发现在SAVE_GRAPH_DATA 能找到。 
还有其他地方吗？

**Comment by lxfu1** [comment]
需求不是很具体，不清楚你是关系图还是流程图，流程图可参考
https://github.com/ant-design/ant-design-charts/issues/2099
