### ISSUE TITLE
Line组件如何监听slider的值🧐[问题]

### ISSUE THREAD

**Issue by MBR000** [ant-design/ant-design-charts#2015]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在Line组件的底部会有一个slider，可以通过拉动它的两个滑块，调整数据展示的范围。我用下面所示的代码，想要用onChange: handleSliderChange，来监听对slider的拉动，但是handleSliderChange函数一直没有被调用。

我希望能实时监听获得，当前slider的start和end分别是多少。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
const config = {
    height: allYfield.length > 30 ? 600 : 400,
    loading: chartData.length==0,
    data: chartData,
    xField: 'commit_index',
    yField: 'score',
    seriesField: 'category',
    color: ['#5B8FF9', 'red', '#5D7092', '#F6BD16', '#6F5EF9'],
    slider: {
      start: minCount/allLength,
      end: 1,
      onChange: handleSliderChange,
    },
    xAxis: {
      nice: true,
      tickCount: 150,
      label: {
        autoRotate: true,
      },
    },  
  }

<Line {...config}/>

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/81085935/72c7f0e1-6b57-45ff-be40-cfb73a8a3f97)

**Comment by lxfu1** [comment]
```ts
onReady: (plot) => plot.on("slider:valueChanged", callback)
```
