### ISSUE TITLE
🧐 How to hide Xaxis and Yaxis?

### ISSUE THREAD

**Issue by bachlongkocanh** [ant-design/ant-design-charts#2016]
How to hide Yaxis and Xaxis properties. And provide full component chart as below?
![stack](https://github.com/ant-design/ant-design-charts/assets/28125294/ffa9b723-033c-4e7e-b52d-3aa6622018d5)

**Comment by hustcc** [comment]
See: https://charts.ant.design/examples/tiny/tiny-area/#filled-area

**Comment by xsamynox** [comment]
I'm trying to get the answer but when I enter the link I see:

![Screenshot 2024-05-06 at 17 22 46](https://github.com/ant-design/ant-design-charts/assets/26368688/cc1c5a4f-53ee-43fd-8053-627ab2ca950d)
Can you help me please?
