### ISSUE TITLE
🧐[问题]Pie label怎么自定义

### ISSUE THREAD

**Issue by Renzo-Lee** [ant-design/ant-design-charts#2017]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://github.com/ant-design/ant-design-charts/assets/52516315/74ec59ce-04c4-4b21-9e69-37540d06e48d)
饼图的这种间距怎么去掉，或者怎么把labelLine画长
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
`label: {
      type: 'spider',
      labelHeight: 40,
      offset:10,
      // offsetX:-10,
      formatter: (data, mappingData) => {
        const group = new G.Group({});
        group.addShape({
          type: 'circle',
          attrs: {
            x: 0,
            y: 0,
            width: 40,
            height: 50,
            r: 5,
            fill: mappingData.color,
          },
        });
        group.addShape({
          type: 'text',
          attrs: {
            x: 10,
            y: 8,
            text: `${data.type}`,
            fill: mappingData.color,
          },
        });
        group.addShape({
          type: 'text',
          attrs: {
            x: -5,
            y: 17,
            text: `—————————————`,
            fill: mappingData.color,
          },
        });
        group.addShape({
          type: 'text',
          attrs: {
            x: 0,
            y: 25,
            text: `${data.value}个 ${data.percent * 100}%`,
            fill: 'rgba(0, 0, 0, 0.65)',
            fontWeight: 700,
          },
        });
        return group;
      },
    },`

**Comment by leffy-yan** [comment]
这个间距看上去是版本的bug，官网示例可以参考下。 如果需要自定义样式，建议升级到antd-charts 2.x版本，参考如下示例
https://ant-design-charts-next.antgroup.com/examples/statistics/pie/#custom-label
