### ISSUE TITLE
How to setup cursor style in charts

### ISSUE THREAD

**Issue by surendranz** [ant-design/ant-design-charts#2019]
I want to change the cursor style to a pointer for all the geometries in plots - like circle packing, donuts, treemaps etc. How to do that? I can't find any documentation / example around it.

**Comment by leffy-yan** [comment]
if you are using antd-charts 1.x, just like this, means column plot use columnStyle property, pie plot use pieStyle property;

![image](https://github.com/ant-design/ant-design-charts/assets/48511770/2009da57-cc01-4686-bd06-2b3223a911ca)


but suggest you update the version to 2.x , then set up like this

![image](https://github.com/ant-design/ant-design-charts/assets/48511770/0f953b93-5132-465f-948b-3d9e3815a328)
