### ISSUE TITLE
Legend hovering

### ISSUE THREAD

**Issue by Aswin-C-Asok** [ant-design/ant-design-charts#2021]
Can we provide a hovering effect when we hover the legend items.

  legend: {
        background: {
          style: {
            stoke: 'blue',
            fill: '#808080',
            //  opacity: 0.5,
          }
        },

**Comment by leffy-yan** [comment]
you can update the version of antd-charts to 2.x, then  set up like this
![image](https://github.com/ant-design/ant-design-charts/assets/48511770/3c1b72a4-1bf2-4ca0-b120-40095be3c80a)
