### ISSUE TITLE
🧐[问题]Flowchart 有没有手动更新数据的方法,从后台获取的数据赋值以后,树图无变化

### ISSUE THREAD

**Issue by kingletMike** [ant-design/ant-design-charts#2027]
Flowchart 有没有手动更新数据的方法,从后台获取的数据赋值以后,树图无变化

**Comment by lxfu1** [comment]
https://codesandbox.io/p/sandbox/objective-wildflower-k5gqz3?file=%2Findex.js%3A840%2C1
