### ISSUE TITLE
网页顶部的api文档说明功能栏没有了

### ISSUE THREAD

**Issue by SUNNERCMS** [ant-design/ant-design-charts#203]
打开官方网站，发现昨天还有的api说明没有了
![](http://i1.fuimg.com/718245/6d1efdb2caf452b5.png)

**Comment by lxfu1** [comment]
https://g2plot-v1.antv.vision/zh/examples/general/title-description  用一下这个地址， 在发布 1.0 ， 链接没改全。

**Comment by lxfu1** [comment]
0.x 版本： https://v0-charts.ant.design/

**Comment by lxfu1** [comment]
已经修复
