### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by djwlx** [ant-design/ant-design-charts#2033]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Mix图表中Legend ts定义错误   readonly legend?: false | Record<string, Legend>;
在使用时直接使用的是Legend的类型，而不是Record<string, Legend>
### © 版本信息

- "@antv/g2plot": "^2.3.29",

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

**Comment by lxfu1** [comment]
更新下版本，https://github.com/antvis/G2Plot/blob/master/src/types/legend.ts
