### ISSUE TITLE
🧐[问题]@ant-design/graphs的OrganizationGraph如何在鼠标hover在node时，修改其中的文字颜色？

### ISSUE THREAD

**Issue by my3188** [ant-design/ant-design-charts#2039]
### 🧐 问题描述
@ant-design/graphs的OrganizationGraph如何在鼠标hover在node时，修改其中的文字颜色？

**Comment by leffy-yan** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/48511770/c1ee463a-d3f6-4c39-8c28-a2c21bde7740)
![image](https://github.com/ant-design/ant-design-charts/assets/48511770/e59bed55-c1c7-4c24-9898-99f1e5326c28)
![image](https://github.com/ant-design/ant-design-charts/assets/48511770/e65bcd5a-28eb-409c-b947-a8abcdae68f0)
需要手动绑定事件, 保存下触发的节点id，然后修改对应的label样式。
