### ISSUE TITLE
Is it possible to Dual-Axes with shared axis? Or Column-Line without Dual-Axes? 🧐

### ISSUE THREAD

**Issue by gziz** [ant-design/ant-design-charts#2047]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
I basically just want to have in a plot, a column a two lines.
This is totally feasible with Dual Axes, however, I need them to share the same axis.
I don't want each to have its own axis.

**Comment by lxfu1** [comment]
[Refer to](https://ant-design-charts-next.antgroup.com/zh/examples/statistics/dual-axes/#dual-multi-line)
