### ISSUE TITLE
🧐[问题]柱线图的slider的tooltip如何隐藏？

### ISSUE THREAD

**Issue by OctoTurboMT** [ant-design/ant-design-charts#2055]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
怎么单独隐藏slider的tooltip？希望鼠标停留在slider上的时候不显示tooltip

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="496" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/12112957/91859bac-0625-469b-a072-cb955bd6d602">

**Comment by hsp-sz** [comment]
可否提供一下代码，官方示例上面hover上去都是没有tooltip的

**Comment by Yang-yibu** [comment]
> 可否提供一下代码，官方示例上面hover上去都是没有tooltip的

有一种场景是鼠标在红色区域内，就会显示 tooltip
示例 deme 加 slider
https://ant-design-charts.antgroup.com/zh/examples/dual-axes/column-line#demo-more-1
![image](https://github.com/ant-design/ant-design-charts/assets/23130670/431113b8-d5e5-4a6f-a4fc-b57929cb9af6)

**Comment by Yang-yibu** [comment]
> 可否提供一下代码，官方示例上面hover上去都是没有tooltip的

有一种场景是鼠标在红色区域内，就会显示 tooltip
示例 deme 加 slider
https://ant-design-charts.antgroup.com/zh/examples/dual-axes/column-line#demo-more-1
![image](https://github.com/ant-design/ant-design-charts/assets/23130670/431113b8-d5e5-4a6f-a4fc-b57929cb9af6)
