### ISSUE TITLE
🧐[问题] 饼图图例的 itemName，只能通过 formatter 渲染自定义字符串吗？如果想渲染 HTML，有什么内置的方法吗？

### ISSUE THREAD

**Issue by DPGZl** [ant-design/ant-design-charts#2056]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
饼图 legend 的 itemName，只能通过 formatter 渲染自定义字符串吗？如果想渲染 HTML，有什么内置的方法吗？
有类似 statistic.title.customHtml 或 tooltip.customContent 一样的方法吗？
Thanks in advance!

**Comment by webInRoad** [comment]
同问

**Comment by webInRoad** [comment]
这个是已经支持了？为什么给关闭了？

**Comment by lxfu1** [comment]
这个不支持 HTML，如果想自定义，可以在issue里面查阅 custom legend 相关的issue
