### ISSUE TITLE
🐛[BUG] 双轴图无法设置 maxColumnWidth

### ISSUE THREAD

**Issue by xyxc0673** [ant-design/ant-design-charts#2061]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
我看见 GeometryColumnOption 的定义为
```ts
export declare type GeometryColumnOption = Pick<ColumnOptions, 'seriesField' | 'isGroup' | 'isStack' | 'isRange' | 'isPercent' | 'columnWidthRatio' | 'marginRatio' | 'columnStyle' | 'pattern' | 'maxColumnWidth'> & CommonGeometryOption;
```
没有将 maxColumnWidth 之类的字段 Pick 进来

### 🏞 期望结果 [描述你原本期望看到的结果]
希望能在双轴图中设置 maxColumnWidth

### © 版本信息

- ant-design-charts 版本: [e.g. 1.4.2]
- 浏览器环境 Microsoft Edge 116.0.1938.62 (Official build) (arm64)
- 开发环境 mac OS

**Comment by lxfu1** [comment]
这个只是类型定义问题，可以试试[2.0](https://ant-design-charts-next.antgroup.com/examples/statistics/dual-axes/#multi-line)
```ts
        style: {
          fillOpacity: 0.8,
          maxWidth: 10
        },
```
