### ISSUE TITLE
🧐[问题]能提供一个官网的镜像吗？

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-charts#2075]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在国内访问实在是太慢了，几分钟才能打开。能提供一份国内的镜像吗？
或者是告知一下如何编译出来，
git clone https://github.com/ant-design/ant-design-charts.git
pnpm install
pnpm build
就报错了

**Comment by lxfu1** [comment]
https://ant-design-charts.antgroup.com/
