### ISSUE TITLE
🐛[BUG]折线图 当x轴是从负数到正数 数据格式是number 的时候 折线会固定从x轴0 位置为起点画图

### ISSUE THREAD

**Issue by zhangfangxin** [ant-design/ant-design-charts#2083]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

折线图 当x轴是从负数到正数 数据格式是number 的时候 折线会固定从x轴 0 位置为起点画图

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
数据是从负数到正数的数据 在数据中 刚好有 x轴 为0的数据 这个时候折线图会强制从 x轴为0 的那条数据作为第一个点 开始画图

### 🏞 期望结果 [描述你原本期望看到的结果]
例如数据中x轴的数据是 -100 -50  0 50 100
期望的是折线的起点是 以-100的点来开始画 但现在的会以 0 这个点开始 第二个点是 -50  来画

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
在线上沙盒中也可以复现 只要将横坐标 改为数字 就可以
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
xField 需要是 string 类型
