### ISSUE TITLE
🐛[BUG]measureTextWidth与官网示例不一致

### ISSUE THREAD

**Issue by Ericawu-g** [ant-design/ant-design-charts#2089]
### 🐛 bug 描述
measureTextWidth官网示例中可以拿到width和height，而实际情况只能拿到width。没有方法可以拿到文字的height了。

### 📷 复现步骤
官网示例：
const { width: textWidth, height: textHeight } = measureTextWidth(text, style);

实际该方法只返回width，按照官网示例获取的为undefind

**Comment by bT0nG** [comment]
官网示例不准确，应该是measureText能拿到width和height。
const { width: textWidth, height: textHeight } = measureText(text, style);
