### ISSUE TITLE
🧐[问题]通过自定义的按钮调用onSave方法或者其他方法去获取数据呢

### ISSUE THREAD

**Issue by she1110** [ant-design/ant-design-charts#2099]

**Comment by lxfu1** [comment]
可以通过监听 onConfigChange 获取数据

**Comment by she1110** [comment]
> 可以通过监听 onConfigChange 获取数据

<Flowchart
        onConfigChange={
          (params: {
            data: Datum;
            type: string;
            config?: NsGraph.INodeConfig | NsGraph.IEdgeConfig;
          }) => {
            console.log(params);
          }
        }
        />
        您好，监听不到，添加结点或者连线或者删除都不会打印任何信息呢

**Comment by lxfu1** [comment]
```ts
 const appRef= React.useRef()

 <button onClick={()=>{
     appRef.current.commandService.executeCommand('xflow:save-graph-data', {
        saveGraphDataService: (meta, graphData) => {
          console.log(graphData)
        },
      });
  }}>点击</button>

 onReady={(graph, app)=>{
  appRef.current = app;
}}
```
