### ISSUE TITLE
🐛[BUG] 来源去向图：setState后，图重新渲染导致位置重置。updateItem方法更新样式不生效

### ISSUE THREAD

**Issue by jiangzhenxiang** [ant-design/ant-design-charts#2107]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
bug1、当图的数据较多时，我移动放大到某个ID的节点后，然后点击节点setState，整个画布会因为setState重新渲染。导致我之前的移动 放大 拖动 等结果被重置
bug2、 通过graph.updateItem方法修改style，不生效
        

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1、拖动节点，或放大 平移图。
2、点击节点，会执行setSate
3、然后图会默认重新渲染，导致第一步中的拖动的结果会被重置为最初的状态。

### 🏞 期望结果 [描述你原本期望看到的结果]
期望在第1步的拖拽 放大 平移的 结果被保留。

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://stackblitz.com/edit/react-ffdheb?file=index.js

https://react-ffdheb.stackblitz.io

### © 版本信息

- ant-design-charts 版本: "@ant-design/graphs": "^1.4.0",
- 浏览器环境 chrome最新版
- 开发环境 windows

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
第一步后的效果：
![image](https://github.com/ant-design/ant-design-charts/assets/23615624/32a55f55-97f0-46cc-a95b-d4bf50628293)

被重置的效果：
![image](https://github.com/ant-design/ant-design-charts/assets/23615624/60d68530-3723-41c7-8501-c08a78a53a51)

期望保留第一步的效果

**Comment by lxfu1** [comment]
1. 想要组件不重复渲染，可以配合 React.memo(<FC />, (pre, next) => Boolean) 使用

**Comment by Chasen-Zhang** [comment]
同样被这个问题困扰了很久，楼主现在有解决这个问题吗 @jiangzhenxiang

**Comment by lxfu1** [comment]
> 同样被这个问题困扰了很久，楼主现在有解决这个问题吗 @jiangzhenxiang

参考下这个呢？ https://codesandbox.io/p/sandbox/damp-firefly-hfd282?file=%2Findex.js%3A206%2C1
