### ISSUE TITLE
🐛[BUG] Column Chart: Legend is not showing

### ISSUE THREAD

**Issue by dmdum** [ant-design/ant-design-charts#2112]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
When using the `legend` property for the Column Chart, the legends are not showing

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1. add the `legend` property to the `Column` component `config`:
```
. . .
legend: {
    position: 'bottom',
}
. . .
```

### 🏞 期望结果 [描述你原本期望看到的结果]
The legend should show below the `Column` chart.

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
**The config used in the code below is based on: https://charts.ant.design/en/examples/column/basic/#color**

https://stackblitz.com/edit/stackblitz-starters-5nubq6?file=src%2FApp.tsx

### © 版本信息

- ant-design-charts 版本: @ant-design/plots: 1.2.5
- Browser Environment: Chrome - latest version
- Development Environment: Windows

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/95848438/4da6caea-b683-41d5-9896-4d02684dcfe9)

**Comment by hsp-sz** [comment]
there is no legend for the single channel, and the legend configuration information is all based on the legend settings for multiple channels. If you need to customize the legend, you can refer to the following link：[demo](https://github.com/ant-design/ant-design-charts/pull/2278/commits/2eae68b74243dc2a31bab4c289ef5a578656eb06)
