### ISSUE TITLE
🧐[问题] 如何自定义y轴 label 内容为图片

### ISSUE THREAD

**Issue by lin-pwd** [ant-design/ant-design-charts#2119]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
请问如何自定义y轴的label为图片？
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

是否可提供相关参数定制进行处理？如
```
// 自定义渲染器
function customYAxisRenderer(text, item, index) {
  const imgElement = document.createElement('img');
  imgElement.src = 'image-url';

  const container = document.createElement('div');
  container.appendChild(imgElement);

  return container;
}

// 图表配置项
const chartConfig = {
  data: [],
  // 其他配置项...

  yAxis: {
    label: {
      renderer: customYAxisRenderer, // 应用自定义渲染器
    },
  },
};
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/139846841/6feaa1c7-e552-482b-95d3-fcba17515541)

**Comment by mt-5678** [comment]
解决了吗？

**Comment by lin-pwd** [comment]
> 解决了吗？

没有，最后不通过图表的方式渲染，让改ui，然后div 自定义组装出所需效果

**Comment by lxfu1** [comment]
[2.0 已支持](https://ant-design-charts-next.antgroup.com/zh/examples/statistics/column/#label-text)
