### ISSUE TITLE
tip好长🐛[BUG]

### ISSUE THREAD

**Issue by pingbaobao** [ant-design/ant-design-charts#212]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/42052862/94523763-3ee34900-0264-11eb-8d83-d08d63406446.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/42052862/94523763-3ee34900-0264-11eb-8d83-d08d63406446.png)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
确认下是不是 style 样式覆盖了， 1.0 版本已经发布， 欢迎更新 https://charts.ant.design/guide/upgrade 。
