### ISSUE TITLE
🧐some wigle

### ISSUE THREAD

**Issue by Alfick** [ant-design/ant-design-charts#2127]
I'm using nextjs, and I'm facing a problem with rendering charts(jittery lines), how can I fix this problem, I'll attach a photo.
https://cloud.mail.ru/public/PMFR/9F5nRxLfz
https://cloud.mail.ru/public/6tAi/1TCbXc2Yt

**Comment by lxfu1** [comment]
The proxy is enabled, but still unable to access your images, [infer to please](https://github.com/ant-design/ant-design-charts/issues/556).
