### ISSUE TITLE
集成辐射图问题

### ISSUE THREAD

**Issue by zhoucs110** [ant-design/ant-design-charts#2131]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
宜搭使用官方示例数据集成辐射图，没有报错。但是不管怎么修改节点数据，页面都只显示一个节点
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
    export function didMount() {
      //入口方法，加载图表组件，加载完成后执行buildChart()方法
      this.utils.loadScript('https://cdn.jsdelivr.net/npm/@ant-design/charts@1.4.2/dist/charts.min.js').then(() => {
        this.buildChart()
      })
    }

    export function buildChart() {
      const DemoRadialGraph = () => {
        const { RadialGraph } = window.Charts
        const chartRef = React.useRef();
        const RadialData = {
          nodes: [
            {
              "id": "0",
              "label":"0"
            },
            {
              "id": "1",
              "label": "1"
            },
          ],
          edges: [
            {
              source: '0',
              target: '1',
            },
          ],
        };

    const fetchData = (node) => {
      return new Promise((resolve, reject) => {
        const data = new Array(Math.ceil(Math.random() * 10) + 2).fill('').map((_, i) => i + 1);
        debugger;
        console.log('data: ', data)
        setTimeout(() => {
          resolve({
            nodes: [
              {
                ...node,
              },
            ].concat(
              data.map((i) => {
                return {
                  id: `${node.id}-${i}`,
                  label: `${node.label}-${i}`,
                };
              }),
            ),
            edges: data.map((i) => {
              return {
                source: node.id,
                target: `${node.id}-${i}`,
              };
            }),
          });
        }, 1000);
      });
    };

    const asyncData = async (node) => {
      return await fetchData(node);
    };

    const config = {
      data: RadialData,
      autoFit: true,
      // layout: {
      //   unitRadius: 80,
      //   /** 节点直径 */
      //   nodeSize: 20,
      //   /** 节点间距 */
      //   nodeSpacing: 10,
      // },
      nodeCfg: {
        asyncData,
        size: 20,
        style: {
          fill: '#6CE8DC',
          stroke: '#6CE8DC',
        },
        labelCfg: {
          style: {
            fontSize: 5,
            fill: '#000',
          },
        },
      },
      menuCfg: {
        customContent: (e) => {
          return (
            <div>
              <button
                onClick={() => {
                  chartRef.current.emit('node:dblclick', e);
                }}
              >
                手动拓展(双击节点也可以拓展)
            </button>
            </div>
          );
        },
      },
      edgeCfg: {
        style: {
          lineWidth: 1,
        },
        endArrow: {
          d: 10,
          size: 2,
        },
      },
      behaviors: ['drag-canvas', 'zoom-canvas', 'drag-node'],
      onReady: (graph) => {
        chartRef.current = graph;
      },
    };
    console.log('config: ', config)
    return <RadialGraph {...config} />;
    };
      // chart-container为页面JSX中返回的div的Id，其他图表验证过没问题
        ReactDOM.render(<DemoRadialGraph />, document.getElementById('chart-container'));
    }
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
复现地址：https://www.aliwork.com/o/chart
打开开发者模式查看日志，config数据

**Comment by lxfu1** [comment]
复制你的config到官网是可以的，用 [@ant-design/graphs](https://unpkg.com/@ant-design/graphs@latest/dist/graphs.min.js) 试试，charts.min.js 后续更新一下

**Comment by ijwstl** [comment]
您好，请问您解决了吗，我也遇到了同样的问题
