### ISSUE TITLE
🧐坐标刻度线间距和网格线能修改默认样式？

### ISSUE THREAD

**Issue by wooxyz** [ant-design/ant-design-charts#214]
### 🧐 问题描述 
折线图demo中：坐标刻度线间距过大，网格线style能修改其他类型，如虚线。

### ant-design-charts截图 
![image](https://user-images.githubusercontent.com/33221294/94540751-65f84580-0279-11eb-98e5-b26ebc3f9956.png)
### bizcharts截图
![image](https://user-images.githubusercontent.com/33221294/94541106-c7b8af80-0279-11eb-866a-5986f1dd6e2c.png)

**Comment by lxfu1** [comment]
```ts
     yAxis: {
          tickCount: 10,
          grid: {
            line: {
                style: {
                stroke: 'red',
                lineDash: [2,4]
              }  
            },
          }
      }
```
