### ISSUE TITLE
🧐[问题] 环形图 如何实现点击滑块后放大的效果

### ISSUE THREAD

**Issue by hwjom** [ant-design/ant-design-charts#2140]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在环形图中， 如何实现点击某个滑块后，放大该部分。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
尝试过使用 lineWidth 来实现放大效果，存在两个问题：
1.动画卡顿；
2.遮挡。不同滑块之间存在遮挡；

**Comment by leffy-yan** [comment]
https://ant-design-charts.antgroup.com/zh/examples/pie/basic/#pie-texture
1.x版本支持类似效果。2.x版本暂不支持，需要自己手写动画效果；后面的小版本会上。
