### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by gq104631** [ant-design/ant-design-charts#2143]
### 📷 
![img_v2_4810c8b1-65fa-46c3-ba39-c2f55ea80f6g](https://github.com/ant-design/ant-design-charts/assets/53905823/020c6e72-c110-4e63-bbeb-3246c320f729)

### 

### 💻 const config = {
        padding:20,
        width: 380,
        autoFit: true,
        data: [data as Record<string, any>[], data as Record<string, any>[]],
        xField: 'xAxis',
        yField: ['columnarValue', 'lineValue'],
        yAxis: {
            // 格式化左坐标轴
            columnarValue: {
                min: 0,
                label: {
                    formatter: (val: any) => `${val}`,
                },
            },
            // 右坐标轴
            lineValue: {
                min: 0,
                max: 100,
                label: {
                    formatter: (val: any) => `${val}%`,
                },
            },
        },
        height: 200,
        geometryOptions: [
            {
                geometry: 'column',
                isGroup: true,
                seriesField: 'columnarValue',
                color: '#5B8FF9',
            },
            {
                geometry: 'line',
                lineStyle: {
                    lineWidth: 2,
                },
                color: '#EFBB7E',
            },
        ],
        interactions: [
            {
                type: 'element-highlight',
            },
            {
                type: 'active-region',
            },
        ],

        tooltip: {
            formatter: (datum: { xAxis: any; lineValue: string; columnarValue: any }) => {
                return { name: datum.xAxis, value: datum.lineValue ? datum.lineValue + '%' : datum.columnarValue };
            },
        },
        legend: {
            custom: true,
            position: 'bottom',
            items: items,
        },
    } as any;
    return data?.length ? (
        <div style={{ height: '250px' }}>
            <DualAxes {...config} />
        </div>
    ) : (
        <></>
    );
});

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
你审查下元素，应该是你盒模型不对
