### ISSUE TITLE
可以实现垂直方向的双向树功能吗

### ISSUE THREAD

**Issue by fasnow** [ant-design/ant-design-charts#2145]
请问使用charts可以实现如图功能吗
![image](https://github.com/ant-design/ant-design-charts/assets/40886524/bfaf53f1-ab94-40e2-a7a3-4c1aa3300902)

**Comment by lxfu1** [comment]
https://ant-design-charts.antgroup.com/examples/relation-graph/flow-analysis-graph/#layout
