### ISSUE TITLE
🧐[问题]：如果数据为0，柱状图怎么保留一个最小高度

### ISSUE THREAD

**Issue by zqy15641660419** [ant-design/ant-design-charts#2148]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
使用柱状图展示数据，当数据为0的时候，想要展示出来一个最小高度

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/89055367/a11bf463-18d1-4b29-9992-10ff5c46f69b)

**Comment by zqy15641660419** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/89055367/38f85574-a512-46a6-87c8-6a82cc5c158b)

**Comment by lxfu1** [comment]
2.0 版本 `style: { minHeight: 10 }`

https://ant-design-charts-next.antgroup.com/zh/examples/statistics/column/#color
