### ISSUE TITLE
🐛[BUG] Cannot use import statement outside a module

### ISSUE THREAD

**Issue by leebang** [ant-design/ant-design-charts#215]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
尝试在NextJS中使用chart，报错

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
根据官网步骤安装部署
1. yarn add @ant-design/charts
2. 按照demo 代码部署
https://charts.ant.design/demos/line/#%E9%80%9A%E8%BF%87%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0%E6%8C%87%E5%AE%9A%E6%8A%98%E7%BA%BF%E9%A2%9C%E8%89%B2

### 🏞 期望结果 [描述你原本期望看到的结果]
出现demo中的图表

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
import { InfoCircleOutlined } from "@ant-design/icons"
import { Tooltip } from "antd"
import { useState, useEffect } from "react"
import { Line } from "@ant-design/charts"

export const ScoreChart = (props: {}) => {

  const data = [
    { year: "1991", value: 3 },
    { year: "1992", value: 4 },
    { year: "1993", value: 3.5 },
    { year: "1994", value: 5 },
    { year: "1995", value: 4.9 },
    { year: "1996", value: 6 },
    { year: "1997", value: 7 },
    { year: "1998", value: 9 },
    { year: "1999", value: 13 }
  ]
  const config = {
    data,
    xField: "year",
    yField: "value"
  }
  return (
    <div>
      <Line {...config} />
    </div>
  )
}

### © 版本信息

- ant-design-charts 版本: 1.0.0
- 浏览器环境: Chrome
- 开发环境: macOS

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

Server Error
SyntaxError: Cannot use import statement outside a module

This error happened while generating the page. Any console logs will be displayed in the terminal window.

Call Stack
<unknown>
/Users/xxx/Documents/WORK/xxx/node_modules/ (antv/g6/es/index.js (1)

wrapSafe
internal/modules/cjs/loader.js (1060:16)

Module._compile
internal/modules/cjs/loader.js (1108:27)

Module._extensions..js
internal/modules/cjs/loader.js (1164:10)

**Comment by lxfu1** [comment]
你复现代码有问题， import React,  { useState, useEffect } from "react".

**Comment by leebang** [comment]
用下面的代码替换掉第四行

const Line = dynamic(
  () => import("@ant-design/charts").then((mod) => mod.Line) as any,
  { ssr: false }
)

暂时可以解决

**Comment by leebang** [comment]
> 你复现代码有问题， import React, { useState, useEffect } from "react".

忘记说这个是个component了，如果单独作为page确实要这行

**Comment by Vfurt** [comment]
I'm also having this problem with latest version of Next.js and ant-design-charts using the examples from docs.

**Comment by leebang** [comment]
> I'm also having this problem with latest version of Next.js and ant-design-charts using the examples from docs.

Try my solution

**Comment by thmohd** [comment]
@leebang  `const Line = dynamic(
  () => import("@ant-design/charts").then((mod) => mod.Line) as any,
  { ssr: false }
)`
does not work and it through syntax error `Unexpected token, expected ","`

 if I try `const Line = dynamic(
  () => import("@ant-design/charts"),
  { ssr: false }
)`

I get `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**Comment by thmohd** [comment]
@leebang if i do that i get `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**Comment by t-lochhead** [comment]
I fixed this issue by importing @ant-design/charts with .babelrc. I got the idea from [Next.js's Ant Design example](https://github.com/vercel/next.js/tree/canary/examples/with-ant-design).

`{
  "presets": ["next/babel"],
  "plugins": [
    [
      "import",
      {
        "libraryName": "@ant-design/charts",
        "libraryDirectory": "lib",
        "camel2DashComponentName": false
      },
      "@ant-design/charts"
    ]
  ]
}`

**Comment by t-lochhead** [comment]
Hi guys, a hack solution to this is to find the module you want to use in @ant-design/charts and copy it out of node modules and into some place else like /components. So if you want to use the Column module, you just copy the module and create a file like /components/column.js

**Comment by anchoice** [comment]
Hi Lee,
I tried your temp. solution with dynamic import but I get: "Server Error - ReferenceError: dynamic is not defined". Can you please me help to solve it? Thanks

**Comment by ya-s-u** [comment]
@anchoice 
```
import dynamic from 'next/dynamic';
```

**Comment by anchoice** [comment]
@ya-s-u ha, didn't notice that nextjs - feature works like a charm! thanks a lot!

**Comment by hustcc** [comment]
- fixed in https://github.com/antvis/G2/pull/6594
- release in https://github.com/antvis/G2/releases/tag/5.2.11
