### ISSUE TITLE
🧐[问题]请问双轴图支持面积图吗？

### ISSUE THREAD

**Issue by white-Hang** [ant-design/ant-design-charts#2153]
![image](https://github.com/ant-design/ant-design-charts/assets/54161396/cc019c57-49ad-484c-8f6d-47c17fe4ed76)目前官网例子里没有看到。

**Comment by lxfu1** [comment]
试一下2.0，`type: 'area'` 即可
https://ant-design-charts-next.antgroup.com/examples/statistics/dual-axes/#dual-line
