### ISSUE TITLE
ColumnWidth and IntervalPadding not working together

### ISSUE THREAD

**Issue by kzatin** [ant-design/ant-design-charts#2154]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

Hello,
I am using column chart and my requirement is that I need no space between columns and the column width should be 19.
For that I am using 
    maxColumnWidth:19,
    minColumnWidth:19,
    intervalPadding: 0,

but if I use intervalPadding alone then space is removed but column size is not set and when I add column width then space appears.

Here is my code :
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Column } from '@ant-design/plots';

const DemoColumn = () => {
  const data = [
    {
      id: 1,
      reportSize: 18,
      seqNum: 1,
      chartName: 'Report Size',
      size: 20,
    },
    {
      id: 2,
      reportSize: 183,
      seqNum: 2,
      chartName: 'Report Size',
      size: 22,
    },
  ];

  const newData = data.map((el) => {
    return {
      ...el,
      id: el.id.toString(),
    };
  });
  const config = {
    data: newData,
    xField: 'id',
    yField: 'reportSize',
    label: {
      // 可手动配置 label 数据标签位置
      position: 'middle',
      // 'top', 'bottom', 'middle',
      // 配置样式
      // style: {
      //   fill: '#FFFFFF',
      //   opacity: 0.6,
      // },
    },
    xAxis: {
      label: {
        autoHide: true,
        autoRotate: false,
      },
    },
    maxColumnWidth:19,
    minColumnWidth:19,
    intervalPadding: 0,
  };
  return <Column {...config} />;
};

ReactDOM.render(<DemoColumn />, document.getElementById('container'));

stackblitz link : https://stackblitz.com/edit/react-rtwtiz-fzyn6v?file=index.js

screenshot : <img width="570" alt="Screenshot 2023-10-31 at 12 45 06 AM" src="https://github.com/ant-design/ant-design-charts/assets/65963985/e84f748a-a6c2-429e-a0c4-fb0b6f4ae71a">

Help me with this issue

**Comment by lxfu1** [comment]
The two are mutually exclusive.
