### ISSUE TITLE
👑 [需求]antd charts 只让一根柱子变长吗

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design-charts#2157]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
antd charts 只让一根柱子变长吗？现在都是rerender的。数据变化比较快的情况下，不好看

**Comment by lxfu1** [comment]
比较快是多少？

**Comment by wangxingxing123654** [comment]
就是websocket，根本没法看，一直在刷新，看多了眼睛花

**Comment by lxfu1** [comment]
charts 目前监听到 data 变化后是全量 data 更新哈，没法让单一柱子变长，绘制有个动画过程，可以尝试关闭动画， animate: false,
