### ISSUE TITLE
👑 [需求] 1.0 文档都是旧的，看 G2 的文档跟我在编辑器里通过 TS 找到的 API 有很大的不同

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design-charts#216]

**Comment by linxianxi** [comment]
而且我发现 1.0 的折线图，默认不设置 width height autoFit ，就没有高度，手动添加了 height 才有高度显示出来

**Comment by lxfu1** [comment]
> 而且我发现 1.0 的折线图，默认不设置 width height autoFit ，就没有高度，手动添加了 height 才有高度显示出来

默认会获取容器宽高，确认下是不是容器没有高度。

**Comment by linxianxi** [comment]
> > 而且我发现 1.0 的折线图，默认不设置 width height autoFit ，就没有高度，手动添加了 height 才有高度显示出来
> 
> 默认会获取容器宽高，确认下是不是容器没有高度。

我是刚刚更新1.0的，会这样，文档就是 G2 的么，跟我在 vscode 查看 ts 类型的 api 差别很大，我暂时还是不用了

**Comment by lxfu1** [comment]
> > > 而且我发现 1.0 的折线图，默认不设置 width height autoFit ，就没有高度，手动添加了 height 才有高度显示出来
> > 
> > 
> > 默认会获取容器宽高，确认下是不是容器没有高度。
> 
> 我是刚刚更新1.0的，会这样，文档就是 G2 的么，跟我在 vscode 查看 ts 类型的 api 差别很大，我暂时还是不用了

文档是 G2Plot 的，和 G2 有差别。
