### ISSUE TITLE
🐛[BUG] Flowchart的defaultActiveKey无效

### ISSUE THREAD

**Issue by Acllex** [ant-design/ant-design-charts#2160]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
 Flowchart的defaultActiveKey无效，无法默认展开自定义节点面板
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
defaultActiveKey: ['custom']
### 🏞 期望结果 [描述你原本期望看到的结果]
默认展开自定义节点面板
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://ant-design-charts.antgroup.com/examples/flowchart/basic/#custom-node
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by asd4134365** [comment]
似乎 registerNode里的对象需要添加key，key值需要和defaultActiveKey里定义的一样，我这样配的能默认展开
```tsx
<Flowchart
  ...
  nodePanelProps={{
    ...
    defaultActiveKey: ['custom'], // ['custom', 'official']
    registerNode: {
      ...
      key: 'custom',
      nodes: [...],
    },
/>
```
