### ISSUE TITLE
🧐[问题] 目前2.0.0-beta.0版本是否支援使用ThemeSet輸出的主題檔自訂主題? 

### ISSUE THREAD

**Issue by franklintw** [ant-design/ant-design-charts#2162]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
目前2.0.0-beta.0版本是否支援使用registerTheme()自訂客制化的主題? 
或是是否有相對應的方式，讓透過ThemeSet(https://theme-set.antv.vision/) 輸出的主題檔能套用在各類圖表上?

**Comment by lxfu1** [comment]
不支持，配置有变化，暂时没有提供一键转换工具
