### ISSUE TITLE
🧐[问题]如何设置柱状图中，横向刻度值为0的网格线加粗？

### ISSUE THREAD

**Issue by GongZhuoYing** [ant-design/ant-design-charts#2166]

**Comment by GongZhuoYing** [comment]
我项目有个场景是，接口中的数据有正有负，根据接口返回的数据，柱状图自动平均分配横向网格线。我想把0这条线单独加粗，所以要先获取这条线。但是现在没法单独获取，怎么办呢？

**Comment by lxfu1** [comment]
刻度配置用回调，或者加个annotaions实现
