### ISSUE TITLE
🧐[问题] How do I prevent an event from executing?

### ISSUE THREAD

**Issue by xuCesar** [ant-design/ant-design-charts#2168]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
I have a Bar Chart component and added legend paginator. When there are many legends, I hope that legends can be paginated.

At the same time, this chart component has a parent container, which has a click event.

I want to prevent container events from bubbling up when pagination is triggered.

I tried blocking the event in the onEvent method but nothing worked and I'm not sure if that's the right thing to do.

If anyone can give help or advice, I would be very grateful.

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
[This is sample code](https://codesandbox.io/s/exciting-kate-22kffg?file=/index.js)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="728" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/13073787/e5b11231-f731-4b8a-ada4-dd35811c03e9">

**Comment by lxfu1** [comment]
Add a div, and prevent at the div level.
