### ISSUE TITLE
🧐[问题] Is it possible to set custom pie width to display the data inside correctly?

### ISSUE THREAD

**Issue by vlad-kk-CHI** [ant-design/ant-design-charts#2171]
![Screenshot_2](https://github.com/ant-design/ant-design-charts/assets/74003047/e14faf37-2925-4117-a992-f0469b371c7f)

https://ant-design-charts.antgroup.com/en/examples/pie/donut/#basic

**Comment by leffy-yan** [comment]
The color-block's width seems impossible， the width is calculated according to the data。 but you can try to set the label style to show the number clearly。or if you want to set the ring's radius, can use “innerRadius” property。
[showLast](https://g2plot.antv.antgroup.com/api/options/meta#metaoptionshowlast)
![image](https://github.com/ant-design/ant-design-charts/assets/48511770/d5225407-5714-46e3-ab91-4e6a7d8ab8d5)

**Comment by leffy-yan** [comment]
![Uploading image.png…]()

**Comment by leffy-yan** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/48511770/71aa0ebd-c1ee-449c-9a87-bd3a34e5eb0f)
or you can use spider position~
