### ISSUE TITLE
🐛[BUG] Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by daichuqi** [ant-design/ant-design-charts#218]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

从0.9.6升级到1.0.0, 用Safari打开直接白屏. 估计原因如下:

https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

重现步骤:

1. 用Safari 打开 https://charts.ant.design 

### © 版本信息

- ant-design-charts 版本: 1.0.0
- 浏览器环境
   Safari  Version 13.1.2 (15609.3.5.1.3)

- 开发环境 
   MacOS Catalina 10.15.6
 

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

<img width="763" alt="Screen Shot 2020-10-01 at 9 30 23 PM" src="https://user-images.githubusercontent.com/4661869/94888353-ab5d7400-042d-11eb-83ef-a080e728f275.png">

**Comment by lxfu1** [comment]
10月9号统一发版， [1687](https://github.com/antvis/G2Plot/issues/1687)。

**Comment by lxfu1** [comment]
无痕浏览器打开。
