### ISSUE TITLE
🐛[BUG] 折线图纵轴展示出错

### ISSUE THREAD

**Issue by moosun123** [ant-design/ant-design-charts#2180]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
折线图当有如上数据时会展示会错乱

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

`
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Line } from '@ant-design/plots';

const DemoLine = () => {
  const [data, setData] = useState([]);

  const config = {
    "data": [
        {
            "lc_day": 1,
            "series": "(聚合) 留存",
            "value": 0.676
        },
        {
            "lc_day": 3,
            "series": "(聚合) 留存",
            "value": 0.538
        }
    ],
    "xField": "lc_day",
    "yField": "value",
    "seriesField": "series"
}

  return <Line {...config} />;
};

ReactDOM.render(<DemoLine />, document.getElementById('container'));
`
![image](https://github.com/ant-design/ant-design-charts/assets/38859821/e3a29a2b-74d1-4ae5-b2a8-6cd19298792f)

> 将代码粘贴到 https://ant-design-charts.antgroup.com/examples/line/basic/#line 链接中即可复现。
将 "lc_day": 1,改为  "lc_day": 2或者任何其他数字都没有问题

### © 版本信息

- ant-design-charts 版本: 最新版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
xField 需要是 string 类型
