### ISSUE TITLE
🧐[问题] 阿里的三个图表库：Ant Design Charts v.s. Bizcharts v.s. Viser 有什么区别呢？各自的优劣？

### ISSUE THREAD

**Issue by hsluoyz** [ant-design/ant-design-charts#219]
https://github.com/ant-design/ant-design-charts 240 stars
https://www.bizcharts.net/ 5.3k stars
https://viserjs.gitee.io/ 1.3k stars

似乎都支持React，都是基于G2，下面有人对比了下 Bizcharts v.s. Viser：https://github.com/viserjs/viser/issues/324 但是Ant Design Charts似乎还比较新，没有对比。看星是Bizcharts 最多

这三个库各自的优劣是什么呢？比如功能是否强大、图表种类、性能、API友好度、可定制性、移动端支持等等，哪个与antd的集成度更好？（当然看名字应该是Ant Design Charts。。不过大家都是react，其他两个库也不会不兼容吧）（p.s. 阿里真是人才济济，光图表库就出了>=3个）

**Comment by daichuqi** [comment]
company politics :)

**Comment by arcsin1** [comment]
Ant Design Charts 需求之前提给  g2plot 原生支持，而g2plot 是 g2的原生支持 ，目前Ant Design Charts也在跟随g2plot的v2版本升级迭代

g2 ---->  g2plot ------> Ant Design Charts

**Comment by TimRChen** [comment]
Ant Design Charts 官方定义是标准版扩展产品，而 Bizcharts 定义是周边生态，Viset就不清楚了。
