### ISSUE TITLE
🧐[问题]柱状图横坐标可以展示成图片吗？

### ISSUE THREAD

**Issue by small-huge-egg** [ant-design/ant-design-charts#2203]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
如何把文字替换成图片？
![image](https://github.com/ant-design/ant-design-charts/assets/33958469/1ad53494-4d52-4b3b-93ce-455cd0ac6776)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://ant-design-charts.antgroup.com/zh/examples/column/grouped/#dodge-padding

**Comment by lxfu1** [comment]
1.x 不支持，试试 2.0  版本 https://ant-design-charts-next.antgroup.com/examples/statistics/column/#label-text
