### ISSUE TITLE
react18项目里安装最新版本的ant-design-charts后启动项目报getEllipsisText未找到

### ISSUE THREAD

**Issue by qipaoshuisugercandyaa** [ant-design/ant-design-charts#2208]
详细报错：
WARNING in ./node_modules/@antv/component/esm/util/label.js 71:27-42
export 'getEllipsisText' (imported as 'getEllipsisText') was not found in '@antv/util' (possible exports: Cache, angleTo, arcToCubic, assign, augment, clamp, clearAnimationFrame, clone, clonePath, contains, createDOM, debounce, deepMix, difference, direction, distanceSquareRoot, each, endsWith, equalizeSegments, every, extend, filter, find, findIndex, firstValue, fixedBase, flatten, flattenDeep, forIn, get, getDrawDirection, getPathArea, getPathBBox, getPathBBoxTotalLength, getPointAtLength, getRange, getRotatedCurve, getTotalLength, getType, getWrapBehavior, gradient, group, groupBy, groupToMap, has, hasKey, hasValue, head, identity, includes, indexOf, isArguments, isArray, isArrayLike, isBoolean, isDate, isDecimal, isElement, isEmpty, isEqual, isEqualWith, isError, isEven, isFinite, isFunction, isInteger, isMatch, isNegative, isNil, isNull, isNumber, isNumberEqual, isObject, isObjectLike, isOdd, isPlainObject, isPointInPolygon, isPointInStroke, isPolygonsIntersect, isPositive, isPrototype, isRegExp, isString, isType, isUndefined, keys, last, lowerCase, lowerFirst, map, mapValues, max, maxBy, memoize, min, minBy, mix, mod, modifyCSS, noop, normalizePath, number2color, omit, parseRadius, path2Absolute, path2Curve, path2String, pick, pull, pullAt, reduce, remove, requestAnimationFrame, reverseCurve, rgb2arr, set, size, some, sortBy, startsWith, substitute, throttle, toArray, toCSSGradient, toDegree, toInteger, toRGB, toRadian, toString, transform, union, uniq, uniqueId, upperCase, upperFirst, values, valuesOfKey, vertical, wrapBehavior)

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/1358
