### ISSUE TITLE
🧐[问题] 多折线图可以修改折线的渲染顺序吗

### ISSUE THREAD

**Issue by joshchiucn** [ant-design/ant-design-charts#2217]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://github.com/ant-design/ant-design-charts/assets/20282988/dd968b6c-8abc-465f-8978-69d211c04632)
如上图中的两条折线，蓝色在前，绿色在后， 所以当两条折线重叠是，绿色会覆盖蓝色。有配置项能，调整这个优先级，让蓝色这条展示在上层吗；

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
demo实例来源官网 https://ant-design-charts.antgroup.com/zh/examples/line/multiple/#line-large-data

**Comment by lxfu1** [comment]
可以调整data顺序实现，推进用2.0的混合图，可以指定层级
