### ISSUE TITLE
🐛[BUG] 折线图lenged 为false, 图例不隐藏

### ISSUE THREAD

**Issue by 951565664** [ant-design/ant-design-charts#222]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
折线图lenged 为false, 图例不隐藏
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://codesandbox.io/s/vigorous-curran-ryuse?file=/App.tsx
### 🏞 期望结果 [描述你原本期望看到的结果]
图例隐藏
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/vigorous-curran-ryuse?file=/App.tsx
### © 版本信息

- ant-design-charts 版本: 1.0.0
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] mac os

**Comment by 951565664** [comment]
非常神奇，在g2的代码示例直接改demo 是对的。然而我把charts的代码运行在本地。我发现在new 或者 update的时候config是包含lenged 为false的https://github.com/ant-design/ant-design-charts/blob/master/src/hooks/useChart.ts#L146

**Comment by lxfu1** [comment]
[1684](https://github.com/antvis/G2Plot/issues/1684)

**Comment by lxfu1** [comment]
更新试试，感觉codesandbox有问题，项目里面使用是正常的 。

**Comment by 951565664** [comment]
项目里是不对的啊。

**Comment by 951565664** [comment]
而且新版也是1.0.0 没有发包呀

**Comment by 951565664** [comment]
@lxfu1 我认为这个问题并没有解决。希望reopen
