### ISSUE TITLE
🧐[问题]使用flex布局图表不能自适应容器宽度

### ISSUE THREAD

**Issue by lj1282737116** [ant-design/ant-design-charts#2220]
### 💻 示例代码 <div style={{ display: "flex" }}>
      <div>
        <Pie {...config} />
      </div>
      <div>
        <Pie {...config} />
      </div>
    </div>

### 🚑 其他信息 
<img width="892" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/50394905/4ad9be58-0f7b-437f-b5d5-deb51b8552bd">

**Comment by lj1282737116** [comment]
![Uploading WechatIMG163.jpg…]()

**Comment by lxfu1** [comment]
```ts
  <div style={{flex: 1}}>
    <Pie {...config} />
  </div>
  <div style={{flex: 1}}>
    <Pie {...config} />
  </div>
</div>
```
