### ISSUE TITLE
🐛[BUG]  使用最新的2.0版本，必须要设置高度，否则图表会自动增长高度

### ISSUE THREAD

**Issue by fzy1344** [ant-design/ant-design-charts#2222]
### 🐛 bug 描述
使用最新的2.0版本，必须要设置高度，否则图表会自动增长高度

### 📷 复现步骤
使用2.0饼图示例https://ant-design-charts-next.antgroup.com/examples/statistics/pie/#basic

### 🏞 期望结果 
正常显示

### 💻 复现代码 
![image](https://github.com/ant-design/ant-design-charts/assets/90477223/a82c9ffc-69ab-4986-b54f-ec545b5317e4)

### © 版本信息

- ant-design-charts 版本: "@ant-design/charts": "^2.0.1",
    "@ant-design/plots": "^2.0.0",
- 浏览器环境 Chrome 版本 119.0.6045.160（正式版本） （64 位）
- 开发环境 [Windows 10]

**Comment by portisk8** [comment]
Hello,
Did you solve this problem? How?

**Comment by lxfu1** [comment]
> Hello, Did you solve this problem? How?

```tsx
<div style={{height: 300}}><Pie /></div>
```
