### ISSUE TITLE
🐛[BUG]饼图和环图渲染出来console端报错Unknown Component: shape.inner

### ISSUE THREAD

**Issue by nndong1989** [ant-design/ant-design-charts#2223]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
打开sandbox的demo代码后就能看到错误，这是环图的沙箱地址：https://codesandbox.io/p/sandbox/spring-http-m08mgm

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
打开饼图的sandbox，页面以渲染就能看到报错

### 🏞 期望结果 [描述你原本期望看到的结果]
没有这错误

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
环图的报错
<img width="1720" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/33800985/a7be37e4-9eda-4646-a092-a0049aac5951">

饼图的报错
<img width="821" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/33800985/9a493c81-d33f-4798-a4f0-eb207fbcc693">

**Comment by africa1207** [comment]
我使用ant design pro v6使用，同样出现这个报错

**Comment by lxfu1** [comment]
看下安装的 plots 版本，或者在官网上试试 https://ant-design-charts-next.antgroup.com/examples

**Comment by africa1207** [comment]
确实，换1.2.5就好了

**Comment by lxfu1** [comment]
目前latest是2.0，你示例的配置都是1.x版本的

**Comment by b5414** [comment]
@lxfu1 same with `"@ant-design/plots": "^2.0.3",`

**Comment by lxfu1** [comment]
配置不对，参考 https://ant-design-charts-next.antgroup.com/examples/statistics/pie/#basic

**Comment by lxfu1** [comment]
> 为什么close了呢？用的就是最新的antd@5.12.4, @ant-design/[charts@2.0.x](mailto:charts@2.0.x)，error: Uncaught (in promise) Error: Unknown Component: shape.point.circle
> 
> 我试了下2.0.0和2.0.3，都是同样的error

你配置不对吧，参考回复的2.0配置

**Comment by b5414** [comment]
My problem: `... label: {type: 'inner', ...`

**Comment by lxfu1** [comment]
> My problem: `... label: {type: 'inner', ...`, so: incorrect configuration

Version 2 used the configuration of Version 1.
```ts
npm i @ant-design/plots@v1 -S
```
