### ISSUE TITLE
🧐设置y轴网格线为虚线，如何取消虚线对x轴的影响

### ISSUE THREAD

**Issue by wooxyz** [ant-design/ant-design-charts#223]
### 🚑 截图
![image](https://user-images.githubusercontent.com/33221294/95548832-7ad29700-0a38-11eb-9edb-bf9400c2142a.png)

最终效果
![image](https://user-images.githubusercontent.com/33221294/95548918-afdee980-0a38-11eb-9a06-c7bbca91de02.png)

**Comment by lxfu1** [comment]
```ts
yAxis:{
        grid: {
          line: {
            style: (item, index) => {
             return index === 0 ? {
               stroke: 'transparent',
             } :  {
              stroke: 'red',
               lineDash: [2,4]
             }
            }
          }
        }
      }
```

**Comment by afc163** [comment]
感觉应该直接做成默认的。

**Comment by lxfu1** [comment]
> 感觉应该直接做成默认的。

默认的需要考虑 xAxis 是否设置了grid。
