### ISSUE TITLE
🐛[BUG]横向坐标轴刻度值在图表宽度变化后会有显示问题

### ISSUE THREAD

**Issue by IceLeach** [ant-design/ant-design-charts#2230]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
变化图表宽度无法使自动旋转后横向坐标轴刻度值恢复到不旋转的状态
这个问题在柱状图、折线图、面积图中都是存在的

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
缩小窗口宽度使刻度值自动旋转
![image](https://github.com/ant-design/ant-design-charts/assets/75960208/f2c96d10-e3a9-4bfe-b4d7-4a0b1b722f3b)
再放大窗口宽度至刻度值可以放下，刻度值仍然处于旋转状态
![image](https://github.com/ant-design/ant-design-charts/assets/75960208/d71390af-b3da-448a-b58a-ab1605c9059a)

### 🏞 期望结果 [描述你原本期望看到的结果]
刻度值恢复到默认的不旋转状态

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://ant-design-charts-next.antgroup.com/examples/statistics/column/#color

### © 版本信息

- ant-design-charts 版本: 2.0.0
- 浏览器环境 chrome 119
- 开发环境 windows 10

**Comment by lxfu1** [comment]
可以先通过配置解决一下
```ts
axis: {
  x: {labelAutoRotate: false}
}
```

**Comment by lxfu1** [comment]
@pearmini 看下这个问题
