### ISSUE TITLE
🧐[问题]1.x版本的Mix组件在2.0版本中用什么组件替代？

### ISSUE THREAD

**Issue by samotoo** [ant-design/ant-design-charts#2231]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
升级@ant-design/plots到2.0.1版本后，发现Mix组件消失了，我们使用Mix组件实现多图层的叠加，请问这个需求在2.0中应该用什么方法实现？

**Comment by TinyStorm** [comment]
同求

**Comment by lxfu1** [comment]
下个小版本会发布，目前功能可以用  DualAxes 实现， 支持任意组合
![image](https://github.com/ant-design/ant-design-charts/assets/31396322/27156517-99d0-4a5c-9f38-8d77da8584d6)
