### ISSUE TITLE
🧐[问题]1.x中环图的statistic相关配置在2.0中要怎么配置

### ISSUE THREAD

**Issue by IceLeach** [ant-design/ant-design-charts#2233]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
需要在环图中央的空白区域显示一些信息，但2.0中似乎没有statistic了

**Comment by lxfu1** [comment]
去掉了这个概念，都改为 annotations 了

**Comment by IceLeach** [comment]
请问是否有相关文档

**Comment by lxfu1** [comment]
[选项-标记](https://ant-design-charts-next-pre.alipay.com/options/plots/annotation/image)
