### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by yadprab** [ant-design/ant-design-charts#2234]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

we're using  ant charts of version 1.4.2
 我们使用的是 1.4.2 版的 Ant 图表 

![Screenshot 2023-11-24 at 11-29-42 RangeError Array size is not a small enough positive integer  — growfin — heisenberg](https://github.com/ant-design/ant-design-charts/assets/68110471/ee0b156f-17be-4ba8-96e0-8b171bb0eb2a)

we get this error in `Funnel` Chart  when the value is negative and other values are zero

当值为负而其他值为零时，我们在“漏斗”图表中收到此错误 
eg
`const data = [
  {
    type: "a",
    value: -7,
  },
  {
    type: "b",
    value: 0,
  },
  {
    type: "c",
    value: 0,
  },
  {
    type: "d",
    value: 0,
  },
  {
    type: "e",
    value: 0,
  },
];`

**Comment by lxfu1** [comment]
[Try the 2.0 version ?](https://ant-design-charts-next.antgroup.com/examples/statistics/funnel/#funnel)

![image](https://github.com/ant-design/ant-design-charts/assets/31396322/063a0363-e990-4ae6-9439-90c6bcce2ab0)
