### ISSUE TITLE
Mix 图表中tooltip在使用customContent，偶尔会出现ts报错

### ISSUE THREAD

**Issue by maodelife** [ant-design/ant-design-charts#2263]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

Mix 图表中tooltip在使用customContent自定义渲染的时候，偶现ts报错问题；
<img width="515" alt="截屏2023-11-30 17 14 50" src="https://github.com/ant-design/ant-design-charts/assets/11474990/935d1de7-fd00-465f-a541-5cf9f22721f4">
<img width="587" alt="截屏2023-11-30 17 15 33" src="https://github.com/ant-design/ant-design-charts/assets/11474990/ae6c1da8-c58b-4fe5-807c-9df4bae68d7a">

如果把customContent去掉，就不会出现这个报错；
试着把customContent中只返回一个空的div标签，同样偶现ts报错问题；

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
版本："@ant-design/plots" : 1.2.6

我们想着试图升级，升级到2.0.x之后，发现不少组件报错，Mix组件也展示不出来，就没有去升级；
业务项目里面用到的图表有10多处；

**Comment by lxfu1** [comment]
返回 htmlstring 试试，或者提供个复现地址，这个定位不了问题

**Comment by maodelife** [comment]
OK，我这边没有在用customContent，用其他形式规避了这个问题了
