### ISSUE TITLE
🐛[BUG]ml-matrix重构使用了#新特性导致报错

### ISSUE THREAD

**Issue by liuzeyang** [ant-design/ant-design-charts#2265]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
https://private-user-images.githubusercontent.com/15833097/286905502-56b5c8d6-6e93-49bb-9e16-63854a57cd72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDMxMzMsIm5iZiI6MTcwMTM0MjgzMywicGF0aCI6Ii8xNTgzMzA5Ny8yODY5MDU1MDItNTZiNWM4ZDYtNmU5My00OWJiLTllMTYtNjM4NTRhNTdjZDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDExMTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMjY4NDlkMWMyZjE4YzgzOWU1YmUwNjE2NTI3NWNmZjk3ODg2YjZlOGViMWNlZDExOTBkZTNiNzhmYzE2ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UJfXrEcAq_OJk6HlgSuoH15_8_5GTQDC2jdd44FXfEA
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by liuzeyang** [comment]
通过锁版本可以解决，
"resolutions": {
    "ml-matrix": "6.10.8"
  },

**Comment by lxfu1** [comment]
底层包问题，已修复
