### ISSUE TITLE
👑 [需求] 条形图期望不需要通过domain来限定最大值也能支持label右侧加数据

### ISSUE THREAD

**Issue by hsp-sz** [ant-design/ant-design-charts#2267]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
1. 现在需要domain写y的最大值才可以让右侧label数据正常展示
2. 现在需要手动指定 dx: 80,和 paddingRight: 80,还有domain都需要计算才能知道右侧给多少空间
3. 右侧的render无法使用，只能用label，期望能写一下render的案例，然后让那个竖线对齐
当前手动计算效果并不理想，如下：
![image](https://github.com/ant-design/ant-design-charts/assets/60083015/09a4ae88-3b70-410d-af47-e05575acd00d)

最终效果预计如下：
<img width="989" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/60083015/b426268a-507d-4625-af53-2abe79565725">

**Comment by lxfu1** [comment]
1. domain  需要上层自己控制，底层不知道最大值的逻辑，不一定是百分百
2. 底层计算会出现...的情况，可以根据业务需求给一个较大值
3. render: (_, item) => (<div style={{marginTop: x}}>{item['xx']}</div>)
