### ISSUE TITLE
🐛[BUG] 官方的示例 meta alias 不生效

### ISSUE THREAD

**Issue by doucheng** [ant-design/ant-design-charts#2269]
### 🐛 bug 描述

https://ant-design-charts.antgroup.com/examples/column/basic/#basic
官方文档是生效的。

![image](https://github.com/ant-design/ant-design-charts/assets/5676888/13da9fb2-c4a2-4a89-b317-8a606090e87b)

### 📷 复现步骤 

https://stackblitz.com/edit/react-c7qkpk?file=index.js

**Comment by lxfu1** [comment]
你指定一下版本，示例里面安装的是最新的2.X版本，你这个配置只在1.x生效

**Comment by lqzhgood** [comment]
> 你指定一下版本，示例里面安装的是最新的2.X版本，你这个配置只在1.x生效
> 
> ![image](https://private-user-images.githubusercontent.com/31396322/287912550-fdadeb87-08a6-4e24-873b-cf724476efef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDY0MzMsIm5iZiI6MTcwOTgwNjEzMywicGF0aCI6Ii8zMTM5NjMyMi8yODc5MTI1NTAtZmRhZGViODctMDhhNi00ZTI0LTg3M2ItY2Y3MjQ0NzZlZmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDEwMDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YmQ3MzA0MjBhMjk4NWRlMTNmZTA1OTNhMzU5MDcxOTVkODc0YzVlYTJlNjljNWZiNjYxZTE0YWQ5MjUxNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pHnCf1HoyiRz2BzzqZW35nkHev_pK2X99H8jMO6hWq0)

问一下, 2.0 怎么实现 meta.alias 的效果呢?
