### ISSUE TITLE
🧐[问题] 2.x版本漏斗图如何实现对比漏斗转化率放在两边

### ISSUE THREAD

**Issue by joshchiucn** [ant-design/ant-design-charts#2279]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://github.com/ant-design/ant-design-charts/assets/20282988/90c7c74c-817b-44ba-8065-d99b670e9a1b)
如上图所示，1.x版本对比漏斗可以实现，转化率放在漏斗两侧，并且每行的数字在中间，2.x版本如何实现呢，官方示例没有类似的。
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
1.x版本对比漏斗
https://ant-design-charts.antgroup.com/examples/more-plots/funnel/#compare
2.x对比漏斗
https://ant-design-charts-next.antgroup.com/zh/examples/statistics/funnel/#mirror-funnel

**Comment by lxfu1** [comment]
重新安装下依赖，参考这个[PR](https://github.com/ant-design/ant-design-charts/pull/2280/files#diff-0fbaa6ecc127f2da8d8359e2e7be0e1348b4a6318f9307148f9999b70cdcc733)
