### ISSUE TITLE
文档示例代码希望可以加个 height

### ISSUE THREAD

**Issue by Haixiang6123** [ant-design/ant-design-charts#228]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

我是从文档的 [Getting Started](https://charts.ant.design/guide/start) 开始使用 ant-design-charts 的，但是我发现无论我用哪个事例都不成功，例如：

![image](https://user-images.githubusercontent.com/17061654/95699797-0a19bd80-0c78-11eb-91bd-1a5696b4ad01.png)

一开始我还以为是 Bug 或者我自己的问题，然后我加了个 height 就好了：

```
const config = {
  appendPadding: 10,
  height: 500, // 这里加上就好了
  data,
  angleField: 'value',
  colorField: 'type',
  radius: 0.8,
  label: {
    type: 'inner',
    offset: '-0.5',
    content: '{name} {percentage}',
    style: {
      fill: '#fff',
      fontSize: 14,
      textAlign: 'center',
    },
  },
};
```

![image](https://user-images.githubusercontent.com/17061654/95699934-4ea55900-0c78-11eb-8e1f-37951897bb52.png)

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

希望文档在这个 config 配置里加个 height，或者对高度进行说明，不然在某些情况下使用时会出现上面的高度为 0 的情况，刚开始使用的时候会比较蒙逼。

**Comment by 951565664** [comment]
这个问题，我也遇到过。其实最好的方式是给你的容器加个height。。我感觉给图表加height，有可能类似图片那种。会导致页面元素块抖动

**Comment by Haixiang6123** [comment]
> 这个问题，我也遇到过。其实最好的方式是给你的容器加个height。。我感觉给图表加height，有可能类似图片那种。会导致页面元素块抖动

这个是当然，这边所指出的问题只是在文档里最好加个高度说明，因为刚开始使用事例的时候是什么都显示不出来的，对刚用的人会觉得点不知所措，或者在文档里加个注意要设置高度之类的备注会好一些。

**Comment by KiritoXF** [comment]
是官方文档的事，我也后来才发现。[#231 ](https://github.com/ant-design/ant-design-charts/issues/231)

**Comment by YoLoveLife** [comment]
应该是某次版本更新之后出现的问题，之前都没有使用height就可以正常使用DEMO的。
