### ISSUE TITLE
👑 [需求]能做成按需加载吗？

### ISSUE THREAD

**Issue by filefoxper** [ant-design/ant-design-charts#2287]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

每次编译量都很足，能做成按需加载的方式吗？主要是 @antv 不能按需加载

**Comment by lxfu1** [comment]
目前就是按需的，是不是上层配置的问题？

**Comment by filefoxper** [comment]
我用的是 @ant-design/plots v1.2.5 版本，是不是要升级到2.1.1？

**Comment by lxfu1** [comment]
是的
