### ISSUE TITLE
🐛[BUG] DagreGraph的nodeStateStyles的hover设置未能生效

### ISSUE THREAD

**Issue by zuzhang** [ant-design/ant-design-charts#229]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
DagreGraph的nodeStateStyles的hover设置未能生效

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
DagreGraph的nodeStateStyles的hover设置未能生效，selected设置有效，edgeStateStyles设置都有效。

### 🏞 期望结果 [描述你原本期望看到的结果]
hover在node上时应能触发相应设置

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
官方的示例代码 https://codesandbox.io/s/fmj84?file=/App.tsx
本地也可复现

### © 版本信息

- ant-design-charts 版本: 1.0.0
- 浏览器环境 Chrome Version 86.0.4240.75 (Official Build) (x86_64)
- 开发环境 mac OS

**Comment by lxfu1** [comment]
"@ant-design/charts": "^1.1.1"
