### ISSUE TITLE
🧐[问题]引入图表报错

### ISSUE THREAD

**Issue by passioning** [ant-design/ant-design-charts#2293]
### 使用Ant Design Pro脚手架，引入报错，使用antv S2存在同样问题
<img width="680" alt="Snipaste_2023-12-12_14-34-33" src="https://github.com/ant-design/ant-design-charts/assets/9817307/0ddbaf26-f21c-45f2-bb07-393f63a2efee">

#### 具体报错如下：

“Line”不能用作 JSX 组件。
  Its type 'ForwardRefExoticComponent<LineConfig & RefAttributes<unknown>>' is not a valid JSX element type.
    不能将类型“ForwardRefExoticComponent<LineConfig & RefAttributes<unknown>>”分配给类型“(props: any, deprecatedLegacyContext?: any) => ReactNode”。
      不能将类型“ReactElement<any, string | JSXElementConstructor<any>>”分配给类型“ReactNode”。
        类型 "ReactElement<any, string | JSXElementConstructor<any>>" 中缺少属性 "children"，但类型 "ReactPortal" 中需要该属性

**Comment by lxfu1** [comment]
// @ts-ignore 先跳过一下，能看到是那个位置出错吗？ 或者提供个复现地址~

**Comment by lxfu1** [comment]
基于最新的  `pro-cli ` + `"@ant-design/plots": "^2.1.2"`  并没有发现问题，先关闭issue，还有问题的话建议提供相关链接
