### ISSUE TITLE
🧐[问题] 升级 2.0.0 后 Tooltip + 事件绑定 不兼容

### ISSUE THREAD

**Issue by zhanyeye** [ant-design/ant-design-charts#2296]
|  2.0.2     |  1.4.2    |
| ---- | ---- |
|  ![image](https://github.com/ant-design/ant-design-charts/assets/35565811/0e7cf5cb-3ee8-46b5-b8ce-a0a8ebeb8b02)    |  ![image](https://github.com/ant-design/ant-design-charts/assets/35565811/410185fb-6669-442b-bca7-893096d75ca1)    |
|   type 不再显示    |   type 正常显示   |
|   [type 不再显示](https://ant-design-charts-next.antgroup.com/zh/examples/statistics/pie/#quarter-circle)    |   [type 正常显示](https://ant-design-charts.antgroup.com/zh/examples/pie/basic/#quarter-circle)   |

**Comment by lxfu1** [comment]
V2 先这样配置一下，内置配置的问题
```ts
    tooltip: {
      items: [
        ({type, value})=>({
          name: type,
          value
        })
      ]
    },
```

**Comment by zhanyeye** [comment]
> V2 先这样配置一下，内置配置的问题
> 
> ```ts
>     tooltip: {
>       items: [
>         ({type, value})=>({
>           name: type,
>           value
>         })
>       ]
>     },
> ```

**谢谢大佬，确实有效**，同时发现 v1.4.2 中 **典型案例** 的**点击事件**好像也失效了欸😂
![image](https://github.com/ant-design/ant-design-charts/assets/35565811/b589a9a9-7384-4384-a9b3-850ae0e7cba7)
- v1.4.2 **典型案例** 链接： [link](https://ant-design-charts.antgroup.com/manual/case#%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A)
- v2.0.0  没有相关文档介绍了

**Comment by lxfu1** [comment]
onReady: ({ chart }) => chart.on('element:click', callback)，晚点跟新文档
