### ISSUE TITLE
🐛[BUG] Browser Crash with Date values

### ISSUE THREAD

**Issue by bboure** [ant-design/ant-design-charts#2297]
### 🐛 Bug Description

In some cases, the browser crashes when data has Date values for an axis.

### 📷 Reproduction

Create a graph with some data including dates for the X axis. It sometimes make he browser crash.
I was not able to determine in which cases it happens. I tried several date and date ranges. Some work, some don't.

![CleanShot 2023-12-13 at 15 43 48@2x](https://github.com/ant-design/ant-design-charts/assets/7089997/2b3b146b-e1a8-4d54-9436-40efe32fd901)

There is no other error in the console. 

### 🏞 Expected result

It should work with any date.

### 💻  Reproduction code

This example always crashes the browser.  30 data points over 30 days.

https://codesandbox.io/p/sandbox/dates-demo-4xtfjd?file=/src/index.tsx

At first, nothing happens, no graph is shown. If you wait long enough (~ 1 min), you should see an unresponsive tab error message.

### Versions

- ant-design-charts: 2.1.2

**Comment by lxfu1** [comment]
I waiting for a long time and not found any error message

![image](https://github.com/ant-design/ant-design-charts/assets/31396322/5fd6dee9-5f41-4c0e-8c54-94a9f73d7eff)

**Comment by bboure** [comment]
Thank you for looking at this. 
I am able to reproduce this every time on every browser. The graph does not load at all (blank page) and then the tab/browser crashes.

I suspected it might be related to timezone, so I tried different ones.
Since you are located in China, I tried Beijing first and it works as expected. 

Please try the following: Change the Timezone on your computer to Central Europe (e.g. Paris), and try again.

I performed several tests, and anything east of Moscow timezone seems to work as expected. But anything west (Including US) does not.
