### ISSUE TITLE
下载图表的时候无法跟踪配置style

### ISSUE THREAD

**Issue by lgh-qt** [ant-design/ant-design-charts#230]
下载图片无论怎么调整style  始终下载默认样式的图表，我该怎么做才能下载成我需要的样式
比如背景色我想为白色但是我的主题是黑色的

**Comment by lxfu1** [comment]
下载就是下载当前看到的图表样式，可以添加 [chartRef](https://charts.ant.design/guide/case#%E8%8E%B7%E5%8F%96-chart-%E5%AE%9E%E4%BE%8B) 自行定义，参考 https://github.com/ant-design/ant-design-charts/blob/master/src/hooks/useChart.ts#L50
