### ISSUE TITLE
🐛[BUG]Circle Packing图的节点label内容显示问题

### ISSUE THREAD

**Issue by thislucky** [ant-design/ant-design-charts#2300]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
为什么label属性的autoHide默认为false，节点label内容超长之后还是会隐藏？

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
官网示例也可以复现

### 🏞 期望结果 [描述你原本期望看到的结果]
label超长后不要隐藏，可以省略号或者换行

### © 版本信息
1.4.2

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
调整下layout，`layout: 'fixedOverlap',`

**Comment by thislucky** [comment]
> 调整下layout，`layout: 'fixedOverlap',`

可以有超长显示省略号的配置嘛？

**Comment by lxfu1** [comment]
无， 建议是默认的布局算法，放不下的就不展示
