### ISSUE TITLE
🐛[BUG] Not able to fix the axis starting point

### ISSUE THREAD

**Issue by Stephen-Strange** [ant-design/ant-design-charts#2309]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

Not able to set the axis starting point value in HeatMap chart

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
<img width="744" alt="Screenshot 2023-12-20 at 2 39 08 PM" src="https://github.com/ant-design/ant-design-charts/assets/74187417/cbadc4df-ac75-496f-801c-9ec0d9f44826">

Here I need to start the yAxis label from 12AM itself instead of 3PM, even though the data starts from 13-Nov 3PM onwards.
I have tried appending values from 12AM-3PM as 0, but it is misleading since the actual data is not 0 

### 🏞 期望结果 [描述你原本期望看到的结果]
The order of yAxis labels should be [12AM, 1AM, 2AM,.... 11AM, 12PM, 1PM.... 11PM].

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
Codesandbox Link: https://codesandbox.io/p/sandbox/charming-sky-5n6djx

### © 版本信息

- ant-design-charts : 1.2.13
- 浏览器环境: Chrome 120.0.6099.109 (x86_64)
- 开发环境 : mac OS

**Comment by lxfu1** [comment]
The String type is arranged according to data index.

**Comment by Stephen-Strange** [comment]
Could you please explain more? @lxfu1

**Comment by lxfu1** [comment]
```ts
const data = [
    {
    dayOfMonth: "13-Nov",
    value: 0.22,
    hourOfDay: "03PM",
  },
  {
    dayOfMonth: "13-Nov",
    value: 1.32,
    hourOfDay: "04PM",
  },
];

change to:

const data = [
    {
      dayOfMonth: "13-Nov",
      value: 1.32,
      hourOfDay: "04PM",
    },
    {
    dayOfMonth: "13-Nov",
    value: 0.22,
    hourOfDay: "03PM",
  },
];

```

**Comment by Stephen-Strange** [comment]
How does that help? @lxfu1 
<img width="135" alt="Screenshot 2023-12-22 at 11 20 01 AM" src="https://github.com/ant-design/ant-design-charts/assets/74187417/fcfb933a-a17f-40f6-b278-03276f0191b9">

This is what I am trying to achieve. See that the starting data for 13-Nov 12AM-3PM is blank

**Comment by Stephen-Strange** [comment]
@lxfu1 Any suggestions for this?

**Comment by lxfu1** [comment]
Sorry, I don't know what you want to achieve. In the data you provided, there are value`{value: 0}`, but your configuration is colorField: "type".

**Comment by Stephen-Strange** [comment]
@lxfu1 Okay to make it clear, I have forked and created a new [sandbox](https://codesandbox.io/p/sandbox/wild-feather-zz4snk).

If you look here the yAxis starts from 3PM, but I need to rearrange the yAxis so that it starts from 12AM instead of 3PM.

**Comment by lxfu1** [comment]
You can sort the mockData, I have already replied to you above.
