### ISSUE TITLE
🧐[问题]文档里的一些demo链接里的图表，显示异常。

### ISSUE THREAD

**Issue by KiritoXF** [ant-design/ant-design-charts#231]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

文档里的一些demo链接里的图表，似乎显示上存在一些问题。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

比如这个链接里的 demo 按钮 https://charts.ant.design/demos/line

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/14950411/95727332-9645d800-0cac-11eb-9fba-572054a7c577.png)

**Comment by lxfu1** [comment]
config 里面配置一下 height

**Comment by KiritoXF** [comment]
确实是 height 的问题，但是是在图表容器那加。文档里给的 CodeSandbox 链接和 `open demo in new tab` 按钮，似乎是配成了 `height: 100%`

**Comment by 951565664** [comment]
容器没有高度，改一下root 的样式就好了

**Comment by KiritoXF** [comment]
好的 谢谢大家
