### ISSUE TITLE
🧐[问题] 🙏please help me change format text for this

### ISSUE THREAD

**Issue by vinhhypc** [ant-design/ant-design-charts#2312]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
I want change format text. I stuck this for 8 hrs :
(1). format to 0, 2, 4, 6, 8
(2). change text to other text but keep (4) text
(3).format number to 7,450,629
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image_1703166876](https://github.com/ant-design/ant-design-charts/assets/85604490/158e7361-819d-4c1e-85d2-72162b72134e)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
Thank a lot !

**Comment by lxfu1** [comment]
Which version?

**Comment by lxfu1** [comment]
V2: `axis: {y: {labelFormatter: (arg)=> 'xxx'}}`

**Comment by vinhhypc** [comment]
> yAxis: {label: {formatter: (arg) => 'xxx' }}

this is my config, where can I put it
![1111](https://github.com/ant-design/ant-design-charts/assets/85604490/2d29e946-6744-4a92-8e77-a2678da9de0b)
