### ISSUE TITLE
🐛[BUG] Tiny* has no exported members using latest Antd version

### ISSUE THREAD

**Issue by facos86** [ant-design/ant-design-charts#2315]
### 🐛 bug 

Cannot import TinyLine, TinyArea etc... in latest Antdesign charts

- ant-design-charts 版本: [2.0.3]
- 开发环境 [mac OS]

<img width="689" alt="Screenshot 2023-12-22 at 12 19 18" src="https://github.com/ant-design/ant-design-charts/assets/2879114/6e71b403-ea0d-4480-9ca6-cc1805222a11">
<img width="696" alt="Screenshot 2023-12-22 at 12 20 05" src="https://github.com/ant-design/ant-design-charts/assets/2879114/097b957a-c498-4bcb-aded-718dbb752686">

**Comment by lxfu1** [comment]
Tiny.Line  

https://ant-design-charts-next.antgroup.com/zh/examples/statistics/tiny/#basic-column

**Comment by facos86** [comment]
Thanks a lot, it seems that https://ant-design-charts.antgroup.com/en/examples/tiny/tiny-line#basic-line is not updated

> Tiny.Line
> 
> https://ant-design-charts-next.antgroup.com/zh/examples/statistics/tiny/#basic-column
