### ISSUE TITLE
🧐[问题] 咨询一下 坐标轴底部不对齐的问题  line组件

### ISSUE THREAD

**Issue by zhucheng1991** [ant-design/ant-design-charts#2317]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
我现在只有一条数据 lineData =[{year:'2023-12-03'，value:0}] 
代码如下
const config = {
    data:lineData,
    xField: 'year',
    yField: 'value',
    height: 300,
    animate:false,
    axis: {   
      y: {
        line:true,
        labelFormatter: (value) => `${Number(value).toFixed(2)}%`,
      },
      x:{
        line:true
      } 
    },
    tooltip:{
      items: [
        ({type, value})=>({
          name: '交件准点率',
          value:`${Number(value).toFixed(2)}%`
        })
      ]
    }
  };
<Line {...config} />
出来的效果如下
![WechatIMG36470](https://github.com/ant-design/ant-design-charts/assets/33744918/95c0bdc6-0a8b-4325-b95b-e5aab810a94e)
我的问题是为什么y轴的0.00不是在我图中圈出来的位置 而是在偏上的位置
而如果我的数据不止一条的时候 就会正常显示 比如我的lineData是const lineData = [
    { name: '1991', value: 3 },
    { name: '1992', value: 4 },
    { name: '1993', value: 3.5 },
    { name: '1994', value: 5 },
    { name: '1995', value: 4.9 },
    { name: '1996', value: 6 },
    { name: '1997', value: 7 },
    { name: '1998', value: 9 },
  ]
显示的效果如下
![WechatIMG36471](https://github.com/ant-design/ant-design-charts/assets/33744918/eba15869-cfc1-4dd7-a317-b7de4dc9001f)

这是为什么

**Comment by lxfu1** [comment]
可以配置下domain,
```ts
      scale: {
        y: {
          domain: [0, 100], // domainMin/domainMax
        }
      }
```
