### ISSUE TITLE
🐛[BUG] Column group: incorrect location of second column if first is absent

### ISSUE THREAD

**Issue by d00rsfan** [ant-design/ant-design-charts#2318]
Great project, the really best, but....
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Incorrect grouping if first grouped value is absent but second (or third) is present. It uses correct color of column, but wrong place - for first column in group
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
I't realy easy to look at
https://stackblitz.com/edit/react-juzwd1-8x4xgj?file=index.js
remove or comment object from data:
//  {
//    "name": "London",
//    "月份": "Feb.",
//    "月均降雨量": 28.8
//  },
Column Feb. moded to the end of the list, Berlin has correct color, but wrong place (where must be London). Tooltip is incorrect: it show London instead of Berlin.
### 🏞 期望结果 [描述你原本期望看到的结果]
Feb must be between Jan and Mar, Berlin must be on right side, tooltip must show Berlin
### © 版本信息

- ant-design-charts 版本: "@ant-design/plots": "^2.1.3", "@antv/g": "^5.18.23",
- 浏览器环境
Chromium-based (Opera, Vivaldi)
- 开发环境 [e.g. mac OS]
doesn't matter, it reproduced in stackblitz
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/22635889/dec00f06-45b6-4f4c-a75f-8f098c093849)

Workaround - prevent such cases in data structure - populate absent data by zero value.

**Comment by lxfu1** [comment]
The grouping rules are related to the data order. The value can be null, but the data cannot be missing.
