### ISSUE TITLE
🐛[BUG] @ant-design/charts gives error when building or reloading next.js page

### ISSUE THREAD

**Issue by drtobbyas** [ant-design/ant-design-charts#232]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
I'm sorry if I didn't comply strictly to the rules of creating issues as I don't understand chinese text.
@ant-design/charts gives error when building or reloading next.js page
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
Reference：[215](https://github.com/ant-design/ant-design-charts/issues/215)

**Comment by afc163** [comment]
直接填 `https://github.com/ant-design/ant-design-charts/issues/215` https://github.com/ant-design/ant-design-charts/issues/215 就行了，不用自己写 `[]()` 链接语法。
