### ISSUE TITLE
🐛[BUG] 词云图渲染canvas无内容，无报错

### ISSUE THREAD

**Issue by xiaobeilo** [ant-design/ant-design-charts#2322]
### 📷 复现步骤 
    按照官方代码示例就可以复现

### 🏞 期望结果 
正常展示

### 💻 复现代码
引用自官方实例代码：
https://codesandbox.io/p/sandbox/charming-brahmagupta-w01fyj?file=%2Findex.js%3A11%2C1

### © 版本信息

- ant-design-charts 版本: [2.0.3]
- 浏览器环境
- 开发环境 [mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1505" alt="Snipaste_2023-12-27_14-40-56" src="https://github.com/ant-design/ant-design-charts/assets/17754668/5cd4dd3b-6a31-4c2e-9c7f-74adf9171438">

**Comment by zystudios** [comment]
词云图没有做resize适配，当容器size改变的时候就没了

**Comment by lxfu1** [comment]
确认下版本，示例没有复现，V1 确实有这个问题，建议升级到 V2 

https://ant-design-charts-next.antgroup.com/zh/examples/statistics/wordCloud/#wordCloud
