### ISSUE TITLE
🐛[BUG]2.x版本饼图value为0时图形是不渲染的

### ISSUE THREAD

**Issue by Junglexuan** [ant-design/ant-design-charts#2324]
当饼图的value都为空的时候，饼图是不展示的，但是在1.x的版本中value即使为0也会基于分类等分呈现
**1.x呈现效果：** =======>
![antd-echarts-1 x](https://github.com/ant-design/ant-design-charts/assets/108848621/66e12a05-a3e9-47a4-9d44-40267c1697f1)
**2.x呈现效果** =======>
![antd-charts-2 x](https://github.com/ant-design/ant-design-charts/assets/108848621/03a9879b-d2c9-46b6-87f8-db20ae14d6fd)

**Comment by ReiAccept** [comment]
2.0之后更坑的一点是你发现那个“其他”项在图例里不展示了……但是图上有，每次最后一个数据项在图例里都没有
