### ISSUE TITLE
🧐[问题] How can I apply regionFilter for a single series only? (如何仅对单个系列应用“regionFilter”?)

### ISSUE THREAD

**Issue by Wokarol** [ant-design/ant-design-charts#2326]
### 🧐 问题描述
I want to display a graph with multiple series. Each series has a specific danger threshold. I want to highlight the series in red when the value is below the threshold for a given series.

我想显示包含多个系列的图表。 每个系列都有特定的危险阈值。 当该值低于给定系列的阈值时，我想以红色突出显示该系列。

### 💻 示例代码

This is the expected result:

这是预期的结果：

![image](https://github.com/ant-design/ant-design-charts/assets/38141841/3371b065-78d7-4c28-a289-f1988ecc3f00)

Both series have a filter with a different threshold.

两个系列都有一个具有不同阈值的过滤器。

(Translations are done using Google Translate, sorry if they are wrong)

**Comment by lxfu1** [comment]
V1 not supported,  [refer to V2](https://codesandbox.io/p/sandbox/exciting-napier-tn8gpv?file=%2Findex.js%3A41%2C22)
