### ISSUE TITLE
🧐[问题] Sankey图能做到边不交叉吗？

### ISSUE THREAD

**Issue by rkxie** [ant-design/ant-design-charts#2327]
![222](https://github.com/ant-design/ant-design-charts/assets/25046356/fb389082-3857-4011-9568-4fb0f5eaee23)
这个图的数据是没那种交叉结构的【之后也不会有 --- 一个子节点永远只有一个父节点】，结点数量少的时候确实可以有不交叉的情况，但是节点是动态变更的，可能变得很多，怎么做才能像tree结构一样不交叉？求指导 大佬们

**Comment by lxfu1** [comment]
可以的

![image](https://github.com/ant-design/ant-design-charts/assets/31396322/7ea92d09-c0de-4cbb-8279-826cdb905d62)
