### ISSUE TITLE
tooltip数据过长如何设置高度或者如何限制展示条数

### ISSUE THREAD

**Issue by zwtcici** [ant-design/ant-design-charts#2330]
按照以下例子如何设置tooltip展示的条数或者自定义tootlp控制高度滚动，我试了很多种方法设置高度不起作用
利用  customContent也不能实现
// customContent: (x, data) => {
      //   console.log('data',data);
      //   let vDom=[];
      //   if(data?.length>0){
      //     data?.map(item=>{
      //       return  vDom.push(
      //         `<li>${item?.name}:${item?.value}</li>`
      //       );
      //     });
      //   }
      //   // const columns=[
      //   //   {
      //   //     title: 'name',
      //   //     dataIndex: 'name',
      //   //     key: 'name',
      //   //   },
      //   //   {
      //   //     title: 'value',
      //   //     dataIndex: 'name',
      //   //     key: 'name',
      //   //   },
      //   // ];
      //   //  vDom.push(
      //   //   <Table columns={columns} dataSource={data} scroll={{y:200}}></Table>
      //   // );
      //
      //   return `<ul style={{max-height:'200px',height:'100px',overflow-y:'scroll',padding:'6px'}}>${vDom}</>`;
      // },
以下是例子代码，希望可以得到解决，谢谢

import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Pie, G2 } from '@ant-design/plots';

const DemoPie = () => {
  const { registerTheme } = G2;
  registerTheme('custom-theme', {
    colors10: [
      '#025DF4',
      '#DB6BCF',
      '#2498D1',
      '#BBBDE6',
      '#4045B2',
      '#21A97A',
      '#FF745A',
      '#007E99',
      '#FFA8A8',
      '#2391FF',
    ],
    colors20: [
      '#025DF4',
      '#DB6BCF',
      '#2498D1',
      '#BBBDE6',
      '#4045B2',
      '#21A97A',
      '#FF745A',
      '#007E99',
      '#FFA8A8',
      '#2391FF',
      '#FFC328',
      '#A0DC2C',
      '#946DFF',
      '#626681',
      '#EB4185',
      '#CD8150',
      '#36BCCB',
      '#327039',
      '#803488',
      '#83BC99',
    ],
  });
  const data = [
    {
      type: '分类一',
      value: 27,
    },
    {
      type: '分类二',
      value: 25,
    },
    {
      type: '分类三',
      value: 18,
    },
    {
      type: '分类四',
      value: 15,
    },
    {
      type: '分类五',
      value: 10,
    },
    {
      type: '其他',
      value: 5,
    },
  ];
  const config = {
    appendPadding: 10,
    data,
    angleField: 'value',
    colorField: 'type',
    radius: 0.8,
    label: {
      type: 'inner',
      offset: '-10%',
      content: '{percentage}',
    },
    interactions: [
      {
        type: 'element-active',
      },
    ],
    theme: 'custom-theme',
  };
  return <Pie {...config} />;
};

ReactDOM.render(<DemoPie />, document.getElementById('container'));

**Comment by lxfu1** [comment]
data?.map 换成 data.slice(limit).map不行么？

**Comment by zwtcici** [comment]
循环数据可以拿到数据并展示，但是解决不了高度问题

**Comment by zwtcici** [comment]
或者怎么改g2-tooltip的默认样式，在外层和Line上添加calss类名antChartsCss 不起作用
.antChartsCss{
  :global{
    .g2-tooltip {
      height: 200px!important;
      overflow-y: scroll!important;
      background: #717bb8 !important;
      box-shadow: #fff 0px 0px 0px !important;
      opacity: 1 !important;
      display: flex;
      flex-direction: column;
      align-items: flex-start;
    }
  }
}

**Comment by lxfu1** [comment]
高度有另外一个issue了，这个先关闭  #2332
