### ISSUE TITLE
🐛[BUG]水波图 100%时候顶部最好不要有动画效果，全部填满

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design-charts#2333]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

![image](https://github.com/ant-design/ant-design-charts/assets/29728228/e0baff2c-d909-4c8c-a795-4f318120dd6d)

水波图 100%时候顶部最好不要有动画效果，全部填满

否则给人一个没有填满的感觉

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://ant-design-charts.antgroup.com/examples/progress-plots/liquid/#basic

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://ant-design-charts.antgroup.com/examples/progress-plots/liquid/#basic

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
不支持直接配置，上层可以判断一下
```ts
const liquidPlot = new Liquid('container', {
  percent: 1,
  outline: {
    border: 4,
    distance: 8,
  },
  wave: {
    length: 128,
    count: 0,
  },
  shapeStyle: {
    fill: '#ff2'
  },
});
```
