### ISSUE TITLE
🧐[问题] legend 怎么选中点击的曲线

### ISSUE THREAD

**Issue by jianqingdu** [ant-design/ant-design-charts#2337]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
legend 怎么选中点击的曲线，默认是相反的行为，看文档也没这方面的示例

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
无

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
无

**Comment by lxfu1** [comment]
不支持，可以上层用div模拟一下，配合legendFilter使用，`onReady: ({chart}) => void` 可以拿到chart实例
  
https://g2.antv.antgroup.com/spec/interaction/legend-filter
