### ISSUE TITLE
🧐[问题]  项目在启动时报错，Please add `@babel/plugin-transform-private-methods`

### ISSUE THREAD

**Issue by Earlzs** [ant-design/ant-design-charts#2339]
### 🧐 之前的项目使用到此插件，过去一直运行没问题。最后在拿出来修改后，安装别的插件时候重新Install了一下依赖。现在打开项目
，有此报错

### 💻 import React from 'react';
import { Pie } from '@ant-design/charts';
const DemoPie = ({ data = [] }) => {
  const config = {
    forceFit: true,
    title: {
      visible: true,
      text: '多色饼图',
    },
    description: {
      visible: true,
      text:
        '指定颜色映射字段(colorField)\uFF0C饼图切片将根据该字段数据显示为不同的颜色\u3002指定颜色需要将color配置为一个数组\u3002\n当把饼图label的类型设置为inner时\uFF0C标签会显示在切片内部\u3002设置offset控制标签的偏移值\u3002',
    },
    radius: 0.8,
    data,
    angleField: 'value',
    colorField: 'type',
    color: ['#0775EF', '#FF691E', '#7484FF'],
    // legend: {
    //   visible: true,
    //   // position: 'right-center',
    // },
    label: {
      visible: true,
      type: 'spider',
      formatter: function(item) {
        return `${item.type}\n${item.value}\n${item.percent}\n`;
      },
    },
  };
  return <Pie {...config} />;
};
export default DemoPie;

### 🚑 ![image](https://github.com/ant-design/ant-design-charts/assets/21009076/3b1188a5-eae7-4f9d-93af-cd2f46fefb8d)

**Comment by lxfu1** [comment]
删除node_modules重新安装，检测下是否有依赖冲突

**Comment by Earlzs** [comment]
> 看上去配置的问题，看下node_modules里面安装多版本，查阅一下相关错误
![image](https://github.com/ant-design/ant-design-charts/assets/21009076/410c0abd-64e3-43fc-a47a-98361d747d2f)
报错信息全是antv相关的，我尝试把项目用引用到的antv组件注释掉，项目可以正常运行，项目中并没有配置loader, 用的Umi框架，  node v16.20.0

**Comment by lxfu1** [comment]
能提供个最新复现不？建议升级到V2版本

**Comment by Earlzs** [comment]
> 能提供个最新复现不？建议升级到V2版本
好的，我尝试下升级到v2，之前使用的是 v1.2.14版本的。
升级v2.0.3后，出现了新的报错信息
![image](https://github.com/ant-design/ant-design-charts/assets/21009076/23623b70-d908-44bd-9758-f1a2ef54bcf8)

**Comment by cixiu** [comment]
遇到了相同的问题。
