### ISSUE TITLE
🧐[问题] 饼图在自定义颜色时如何同时应用到tooltip和legend

### ISSUE THREAD

**Issue by IceLeach** [ant-design/ant-design-charts#2346]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在一些场景下需要对显示颜色进行定制，使用style.fill可以修改颜色却无法应用到tooltip和legend，需要单独配置进行覆盖，是否有更好的方式？

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/75960208/e25ea2fb-c656-441f-a5a9-8c7c4907ed73)

**Comment by i11I04i** [comment]
目前可以通过以下方式解决
![image](https://github.com/ant-design/ant-design-charts/assets/58681207/c014a88e-263d-4cf4-b1d3-154e764a3330)
