### ISSUE TITLE
🧐[问题] 官方文档 - 演示代码报错，请检查

### ISSUE THREAD

**Issue by imnxg** [ant-design/ant-design-charts#2349]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
官方文档：热力图 --演示代码报错，请检查
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

地址：[https://ant-design-charts-next.antgroup.com/zh/examples/statistics/heatmap/#basic](https://ant-design-charts-next.antgroup.com/zh/examples/statistics/heatmap/#basic)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/73350203/112611f4-17de-4e9c-acf7-c4db86f7008d)

**Comment by imnxg** [comment]
好多问题，感觉提供的案例都不能在 **StackBlitz** 和  **CodeSandbox** 中打开：
![image](https://github.com/ant-design/ant-design-charts/assets/73350203/84cbd1ad-3828-4cd5-acdf-23d3dc73d7b7)

**Comment by lxfu1** [comment]
这个是部署受限了，你先选择在codesandbox中打开是OK的

**Comment by imnxg** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/73350203/a2926fdc-7436-411f-9bfb-bc6f620bcc93)

案例：
[https://ant-design-charts.antgroup.com/examples/heatmap/basic/#calendar](https://ant-design-charts.antgroup.com/examples/heatmap/basic/#calendar)

在CodeSandbox也运行不了
[https://codesandbox.io/p/sandbox/stoic-dhawan-z6pb62](https://codesandbox.io/p/sandbox/stoic-dhawan-z6pb62)

1.4.2版本的，在CodeSandbox中报错：
![image](https://github.com/ant-design/ant-design-charts/assets/73350203/c82f6223-7c2a-491f-a993-bd2993a0f8d8)

难道1.4.2版本的registerShape也改为了register吗？？？
没有可运行的案例真的无法组装组件库了~-~

**Comment by lxfu1** [comment]
是的，换成 register 了，先参考这个吧，我们近期完善示例

https://g2.antv.antgroup.com/manual/extra-topics/customization#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BD%A2%E7%8A%B6shape
