### ISSUE TITLE
🐛[BUG] 折线图x坐标为时间的时候超出数据最大值

### ISSUE THREAD

**Issue by 951565664** [ant-design/ant-design-charts#235]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

![image](https://user-images.githubusercontent.com/22285404/95832431-d40a3580-0d6c-11eb-8704-19aa867dc300.png)

折线图x坐标轴超出数据的最大值
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://codesandbox.io/s/funny-firefly-8784m?file=/App.tsx
### 🏞 期望结果 [描述你原本期望看到的结果]
x坐标轴的最大值是数据的最大值

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://codesandbox.io/s/funny-firefly-8784m?file=/App.tsx

### © 版本信息

- ant-design-charts 版本:1.0.0 | 1.0.0-beta.2 都有
- 浏览器环境 chrome
- 开发环境 mac OS

**Comment by lxfu1** [comment]
这个已经修改默认类型了，还没发布。
```ts
   xAxis: {
      type: 'cat'
    },
```

**Comment by 951565664** [comment]
@lxfu1 改为cat 后。又会出现部分case  x坐标轴少值的情况。

**Comment by 951565664** [comment]
尤其是当数据发生改变的时候，目前能稳定复现的是这个例子。因为间隔没有重新计算，所以最后的值没了。https://codesandbox.io/s/nifty-breeze-yv623?file=/App.tsx

**Comment by 951565664** [comment]
我不知道是不是应该重开一个issues，感觉是同一个问题导致的。有些type是会多算，有些type会少算

**Comment by 951565664** [comment]
https://codesandbox.io/s/funny-firefly-8784m?file=/App.tsx type 改为time也是不对的。

**Comment by lxfu1** [comment]
> @lxfu1 改为cat 后。又会出现部分case x坐标轴少值的情况。

少值是因为数据太多， 内部算法做了优化，要展示全的话可以设置
```ts
xAxis: {
  tickCounts:  data.length
}
```

**Comment by 951565664** [comment]
@lxfu1 是data变化后，内部算法对于展示没有重新计算吧。

**Comment by 951565664** [comment]
我看了源码找到了 https://github.com/antvis/scale/blob/master/src/index.ts 这个代码。看了下源码找到了这几种类型的区别。这个场景其实应该用 'timeCat' 这样坐标轴的最大值就能覆盖到了
