### ISSUE TITLE
🐛[BUG] Slider not showing underneath simple line chart

### ISSUE THREAD

**Issue by bryandandan** [ant-design/ant-design-charts#2359]
I'm trying to replicate this simple example: https://ant-design-charts.antgroup.com/en/examples/line/basic/#line-slider
However, the slider does not appear under the chart

<img width="1479" alt="Screenshot 2024-01-10 at 7 32 45 PM" src="https://github.com/ant-design/ant-design-charts/assets/42372855/5b5438d0-4052-4a6a-8297-6efa3b469d14">

```js
  const DemoLine = () => {
  const [data, setData] = useState([])

  useEffect(() => {
    asyncFetch()
  }, [])

  const asyncFetch = () => {
    fetch(
      'https://gw.alipayobjects.com/os/bmw-prod/1d565782-dde4-4bb6-8946-ea6a38ccf184.json'
    )
      .then(response => response.json())
      .then(json => setData(json))
      .catch(error => {
        console.log('fetch data failed', error)
      })
  }
  const config = {
    data,
    padding: 'auto',
    xField: 'Date',
    yField: 'scales',
    xAxis: {
      tickCount: 5,
    },
    slider: {
      start: 0.1,
      end: 0.5,
    },
  }

  return <Line {...config} />
}
```

**Comment by lxfu1** [comment]
It is recommended to use [V2](https://ant-design-charts-next.antgroup.com/)

```ts
slider: {
      x: {
        values: [0.1,0.5],
      }
    },
```

**Comment by bryandandan** [comment]
> It is recommended to use [V2](https://ant-design-charts-next.antgroup.com/)
> 
> 
> 
> ```ts
> 
> slider: {
> 
>       x: {
> 
>         values: [0.1,0.5],
> 
>       }
> 
>     },
> 
> ```

Exactly what i was looking for thanks
