### ISSUE TITLE
🐛[BUG] 使用ahooks的useSize时，仪表盘渲染异常

### ISSUE THREAD

**Issue by sunyum** [ant-design/ant-design-charts#236]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/20025971/95936306-d2418000-0e07-11eb-8bde-b93f47273679.png)
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
[https://codesandbox.io/s/twilight-haze-wot4d?file=/App.tsx](https://codesandbox.io/s/twilight-haze-wot4d?file=/App.tsx)

**Comment by lxfu1** [comment]
数据不对
```ts
 range: { 
  ticks: [0, 0.25, 0.5, 0.75, 1], 
  color: ["l(0) 0:#5d7cef 1:#e35767"] 
},
```

**Comment by sunyum** [comment]
> 数据不对，需要指定ticks。
> 
> ```ts
>  range: { 
>   ticks: [0, 0.25, 0.5, 0.75, 1], 
>   color: ["l(0) 0:#5d7cef 1:#e35767"] 
> },
> ```
那个是在官方Demo上改的，官方Demo就没有指定ticks。而且指定ticks之后虽然可以渲染出来了，但是图表明显变形了

**Comment by lxfu1** [comment]
> > 数据不对，需要指定ticks。
> > ```ts
> >  range: { 
> >   ticks: [0, 0.25, 0.5, 0.75, 1], 
> >   color: ["l(0) 0:#5d7cef 1:#e35767"] 
> > },
> > ```
> 
> 那个是在官方Demo上改的，官方Demo就没有指定ticks。而且指定ticks之后虽然可以渲染出来了，但是图表明显变形了

变形看起来是 ahooks 引起的。

**Comment by lxfu1** [comment]
升级 1.0.2，被遗忘的 issue 欢迎钉钉扫描加群。
