### ISSUE TITLE
🐛[BUG] Sankey throws error when data = []

### ISSUE THREAD

**Issue by nerdess** [ant-design/ant-design-charts#2361]
### 🐛 Bug Description [Provide a detailed description of the bug for everyone to understand]

As of @ant-design/charts > 2.0.0 the Sankey chart is broken when an empty array is passed in

### 📷 Reproduction Steps [Clearly describe the steps to reproduce the issue, so others can see the problem]

This can easily be reproduced here:

https://ant-design-charts-next.antgroup.com/en/examples/statistics/sankey/#alipay

Just change the data const to be this:

```
const data = []
```

Then you get this error:

RangeError: invalid array length

### 🏞 Expected Result [Describe the result you expected to see originally]

No error 

### 💻 Reproduction Code [Provide reproducible code, repository, or an online example]

See sandbox here https://codesandbox.io/p/sandbox/inspiring-stonebraker-v4d8x9

### © Version Information

- ant-design-charts Version: 2.0.0 (or higher)
- Browser Environment (any)

### 🚑 Other Information [Include other information like screenshots, if available]

<img width="999" alt="Bildschirmfoto 2024-01-11 um 13 01 10" src="https://github.com/ant-design/ant-design-charts/assets/711925/2f2e2cce-d487-4274-8a90-ebd8edcefb28">

Is anyone working on this bug? If not I can have a look.

**Comment by lxfu1** [comment]
`if(!data.length) return null`, Fix in the next minor version.
