### ISSUE TITLE
🐛[BUG]柱图配置选中态交互，预期之外取消选中态

### ISSUE THREAD

**Issue by hewitt99** [ant-design/ant-design-charts#2365]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
antv 2.0图表添加elementSelect交互；
点击后切换为选中态，移动鼠标，状态自行回退。
复现地址：https://codesandbox.io/p/sandbox/modest-gagarin-f33snx?file=%2Findex.js
与g2 5.0 效果不一致，地址：https://g2.antv.antgroup.com/examples/interaction/element/#select

### 🏞 期望结果
期望同：https://g2.antv.antgroup.com/examples/interaction/element/#select，效果

### 💻 复现代码 

https://github.com/ant-design/ant-design-charts/assets/81789871/8bc82278-fcc1-497a-8a1c-e73790510c75

### © 版本信息

- ant-design-charts 版本: 2.0
- 浏览器环境 chrome latest
- 开发环境 mac OS

**Comment by i11I04i** [comment]
@hewitt99 可以先把另外一个交互关闭

`
interaction: {
  elementHighlightByColor: false
}
`
