### ISSUE TITLE
🐛[BUG] 通过回调函数指定折线图样式不生效

### ISSUE THREAD

**Issue by liboliang01** [ant-design/ant-design-charts#2366]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
网页demo如下：  
![image](https://github.com/ant-design/ant-design-charts/assets/55911020/3de96ebe-e66d-4104-a9be-628525eae0ae)   
CodeBox运行如下：  
![image](https://github.com/ant-design/ant-design-charts/assets/55911020/4e0edafa-7346-4253-ad38-49af794631ef)    
可以看到样式没有生效

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
我没有改变代码，直接从网页的codesandbox地址进去就可以看到异常      
网页地址：https://ant-design-charts.antgroup.com/examples/line/multiple/#style-callback     
![image](https://github.com/ant-design/ant-design-charts/assets/55911020/2038364d-6339-4255-9877-9c2e80f50216)

### 🏞 期望结果 [描述你原本期望看到的结果]
和网页demo一致

### © 版本信息

- ant-design-charts 版本: 1.4.2
- 浏览器环境 最新chrome
- 开发环境  windows11

**Comment by i11I04i** [comment]
@liboliang01 CodeBox上demo用的是latest版本，可以参考以下代码(v2版本): 
![image](https://github.com/ant-design/ant-design-charts/assets/58681207/819657db-e67b-45de-936f-bb11fa1e218d)
