### ISSUE TITLE
渲染图形很卡顿，为什么没有官方列子那么顺畅呢🧐[问题]

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-charts#2369]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

https://github.com/ant-design/ant-design-charts/assets/23183393/0c827853-e1ac-40da-a7bb-ac505a4ba59f

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
  "@ant-design/charts": "^2.0.3",
   "react": "^18.2.0",
    "react-dom": "^18.2.0",
    使用的是ant-desing-pro 5版本
[直接复制上面列子代码运行的](    https://ant-design-charts.antgroup.com/zh/examples/pie/basic/#basic
)### 🚑 其他信息 [如截图等其他信息可以贴在这里]

**Comment by lxfu1** [comment]
你打印一下，是不是触发了多次render，可以考虑加上React.memo(<FC />, () => boolean)

**Comment by xyy7260** [comment]
一样的会卡呢， 
<img width="852" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/23183393/0ef61a63-1f46-498a-b226-374befa4cab9">

**Comment by lxfu1** [comment]
> @lxfu1 我去试一试， 还提示了 Uncaught (in promise) Error: Unknown Component: shape.outer 会不会和这个有关系呢

你这个应该是配置和版本对不上，[V2 版本看下这个哈](https://ant-design-charts-next.antgroup.com)

**Comment by xyy7260** [comment]
<img width="972" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/23183393/2bd2fc1c-98fc-4476-a07b-34803dbb2672">
奇怪了 我按照V2版本方式去安装

 
 
 "react": "^18.2.0",
 "react-dom": "^18.2.0",
"lodash-es": "^4.17.20",     
 "@ant-design/charts": "^2.0.3",
 "@ant-design/icons": "^5.1.4",
 "@ant-design/plots": "^2.1.11",
 
 还是卡 
` import { Pie } from '@ant-design/plots';
`
 @lxfu1

**Comment by xyy7260** [comment]
知道了 我 是按照V1版本列子 去看的 所以导致卡
