### ISSUE TITLE
🧐[问题]0.9.13 升级 1.0.0 后，官方示例运行结果，纵坐标显示 "..."

### ISSUE THREAD

**Issue by wadezhan** [ant-design/ant-design-charts#237]
### 🧐 问题描述
0.9.13 升级 1.0.0 后，官方示例，拷贝到 ant-design-pro 框架中运行，截图如下，纵坐标轴显示 "..."，可能是什么原因导致？

![image](https://user-images.githubusercontent.com/998505/95964548-7e508e80-0e3b-11eb-85ea-c3c2bae995b4.png)

### 💻 示例代码
```ts
import React, { useState, useEffect } from 'react';
import { Line } from '@ant-design/charts';
import { Card } from 'antd';

const DemoLine: React.FC = () => {
  const [data, setData] = useState([]);
  const asyncFetch = () => {
    fetch('https://gw.alipayobjects.com/os/bmw-prod/1d565782-dde4-4bb6-8946-ea6a38ccf184.json')
      .then(response => response.json())
      .then(json => setData(json))
      .catch(error => {
        console.log('fetch data failed', error);
      });
  };

  useEffect(() => {
    asyncFetch();
  }, []);

  const config: any = {
    data,
    height: 400,
    xField: 'Date',
    yField: 'scales',
    xAxis: {
      type: 'timeCat',
      tickCount: 5,
    },
  };
  return (
    <Card title="标题示例">
      <Line {...config} />
    </Card>
  );
};

export default DemoLine;

```

### 其他
官方示例，默认配置，横坐标显示为 "..."
![image](https://user-images.githubusercontent.com/998505/95966970-4d258d80-0e3e-11eb-91f3-a00d95837dae.png)

https://github.com/ant-design/ant-design-charts/issues/237#issue-721260677

**Comment by lxfu1** [comment]
升级不对吧？删除node_modules重新安装试试。

**Comment by wadezhan** [comment]
试过了，清空 node_modules ，uninstall 后重新安装 @1.0.0 都不行

**Comment by wadezhan** [comment]
官方示例，默认配置，横坐标显示为 "..." ，貌似也有这个问题

![image](https://user-images.githubusercontent.com/998505/95966970-4d258d80-0e3e-11eb-91f3-a00d95837dae.png)

https://github.com/ant-design/ant-design-charts/issues/237#issue-721260677

**Comment by lxfu1** [comment]
添加 padding: [100] 试试，最好能提供一个复现地址 类似 https://codesandbox.io/s/serene-payne-ojs4u?file=/App.tsx ，内部超出确实会...，但你这个配置我试了多个环境也不会出现。

**Comment by 951565664** [comment]
同样没有复现。

**Comment by wadezhan** [comment]
复现示例：https://github.com/wadezhan/cra-demo

复现过程：
1. 初始化 create-react-app 脚手架
2. 安装 @ant-design/chart@1.0.0 antd 依赖
3. 启动服务 yarn start

问题截图：
![image](https://user-images.githubusercontent.com/998505/96069295-7c84da80-0ed0-11eb-82ab-1a88370e117b.png)

**Comment by wadezhan** [comment]
是否支持微软Edge浏览器最新版本，目前貌似渲染异常
![image](https://user-images.githubusercontent.com/998505/96070757-6593b780-0ed3-11eb-81de-d34cdd193ec9.png)

**Comment by lxfu1** [comment]
你代码跑出来的效果，MacOS  + edge.
![image](https://user-images.githubusercontent.com/31396322/96071823-83621c00-0ed5-11eb-9b15-788c0147f411.png)

**Comment by wadezhan** [comment]
在 Windows 中测试，必现如上2个问题：
1. Chrome 渲染纵坐标显示 "..." ；
2. Edge 渲染空白；

找了台 Mac 环境测试下，也是同样问题

**Comment by wadezhan** [comment]
测试了3个环境，都有问题，如何解决呢

测试环境：

系统版本：Windows 10 Pro 10.0.18362 版本 18362
浏览器版本：Chrome 86.0.4240.75 / Edge 
Node版本：14.12.0

系统：Mac Catalina 10.15.6
浏览器：Chrome 86.0.4240.75
Node版本：12.16.1

**Comment by wadezhan** [comment]
![image](https://user-images.githubusercontent.com/998505/96075187-16528480-0edd-11eb-9bc3-bb393c8a9a88.png)

**Comment by lxfu1** [comment]
你是不是有package-lock.json没有删除  底层包没有被更新？

**Comment by hustcc** [comment]
@wadezhan 你安装依赖是使用哪个 npm 源，内部的吗？

**Comment by wadezhan** [comment]
是内部源的问题，已修复，谢谢
