### ISSUE TITLE
Annotations 标记中RangeY 类型标记的填充色配置不生效 🐛[BUG]

### ISSUE THREAD

**Issue by X-x-start** [ant-design/ant-design-charts#2371]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://github.com/ant-design/ant-design-charts/assets/31983804/47d308a6-3ca7-4f57-bdb0-bfb8e952398c)
![image](https://github.com/ant-design/ant-design-charts/assets/31983804/e0fb4969-30e8-4fa8-9fef-3d72cd957def)
按照文档中配置 标记填充色未改变

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
在 图表配置中添加 类型为 rangeY 的 annotations
const config = {
    data,
    xField: 'year',
    yField: 'value',
    point: {
      shapeField: 'square',
      sizeField: 4,
    },
    interaction: {
      tooltip: {
        marker: false,
      },
    },
    style: {
      lineWidth: 2,
    },
    annotations:[
      {
          type: 'rangeY',
          data: [{ y: [0, 10] }],
          yField: 'y',
          range: {
            fill: 'red',
            fillOpacity: '0.5',
          },
        },
    ]
  };

### 🏞 期望结果 [描述你原本期望看到的结果]
背景色修改

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/p/sandbox/winter-bird-z6n7kr

### © 版本信息
   "@ant-design/plots": "^2.1.5",

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by i11I04i** [comment]
目前可以改成style解决
![image](https://github.com/ant-design/ant-design-charts/assets/58681207/e347cb2c-d968-4ac9-ad01-0ce76cfb9f40)
