### ISSUE TITLE
🐛[BUG]不显示图例

### ISSUE THREAD

**Issue by jefferybai** [ant-design/ant-design-charts#2375]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
柱状图不显示图例，且报错
×
Error
Unknown position: middle

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/p/sandbox/sharp-bassi-670sry

### © 版本信息

- ant-design-charts 版本: 2.0.3
- 浏览器环境：Chrome 120.0.6099.217
- 开发环境 ：nodejs v16.17.1

**Comment by lxfu1** [comment]
你用了1.X的配置，可以看下[2.0的官网](https://ant-design-charts-next.antgroup.com/examples#statistics-column)哈
