### ISSUE TITLE
🐛[BUG] 图表联动功能在线环境出错 plots_1.G2.registerInteraction is not a function

### ISSUE THREAD

**Issue by huangkenicole** [ant-design/ant-design-charts#2379]
![image](https://github.com/ant-design/ant-design-charts/assets/112435311/808ad37f-8efb-4732-bb74-c40c559f8982)

## 报错内容
Error in /~/index.js (45:16)
plots_1.G2.registerInteraction is not a function

通过重装plot相关包并未解决该问题

**Comment by lxfu1** [comment]
版本不对，你这个是 1.X 的版本，你安装了 2.X 的

**Comment by Aliveing** [comment]
@lxfu1 请教个问题，根据您的回复，升级到 V2 需要开发者自行实现联动功能，那 V2 考不考虑内置 [V1 图表联动](https://ant-design-charts.antgroup.com/zh/examples/plugin/association/#association-pie) 功能？近期有没有计划。
