### ISSUE TITLE
🧐[问题] @ant-design/charts 2.0.3 version DualAxes chart - How to display on tooltip data of two columns?

### ISSUE THREAD

**Issue by vadym9** [ant-design/ant-design-charts#2382]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

In @ant-design/charts 1.4.2 with DualAxes chart when moving cursor on section appears tooltip that displays data for two columns and a line but in @ant-design/charts 2.0.3 displays data only for one column and a line

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

Documentation on 1.4.2 version
https://ant-design-charts.antgroup.com/en/examples/dual-axes/grouped-column-line#grouped-column-line

Documentation on 2
https://ant-design-charts-next.antgroup.com/en/examples/statistics/dual-axes#grouped-column-line

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

Documentation on 1.4.2 version

![Screenshot from 2024-01-22 10-40-35](https://github.com/ant-design/ant-design-charts/assets/59872680/d215b958-4a7c-4e7d-adcf-7b2317b15c85)

Documentation on 2

![Screenshot from 2024-01-22 10-44-19](https://github.com/ant-design/ant-design-charts/assets/59872680/3db0db6c-3e2f-445b-8a59-4433078fdc60)

**Comment by lxfu1** [comment]
https://ant-design-charts-next.antgroup.com/en/examples/statistics/dual-axes/#column-multi-line

**Comment by vadym9** [comment]
> https://ant-design-charts-next.antgroup.com/en/examples/statistics/dual-axes/#column-multi-line

@lxfu1 But I use chart with two columns and a line
