### ISSUE TITLE
🐛[BUG] @ant-design/charts 2.0.3 DualAxes grouped column line - color of line doesn't change when legend: false

### ISSUE THREAD

**Issue by vadym9** [ant-design/ant-design-charts#2386]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

When setting` legend: false`  the color of the line is not changed

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

In the documentation of 2 version of @ant-design/charts the color of the line is changed to light green

![image](https://github.com/ant-design/ant-design-charts/assets/59872680/a62b439a-9107-4fea-ab4f-a42f3325fb6f)

After setting `legend: false` the color of the line doesn't change

![image](https://github.com/ant-design/ant-design-charts/assets/59872680/d2032edd-9071-43ce-84f4-3df4dce51cbd)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

Link to the documentation:
https://ant-design-charts-next.antgroup.com/en/examples/statistics/dual-axes#custom-grouped-column-line

### © 版本信息

- ant-design-charts 版本: 2.0.3
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
```ts
children: [
  {
    type: 'interval'
  },
  {
    type: 'line',
    colorField: '#5AD8A6'
  }
]
```

**Comment by vadym9** [comment]
@lxfu1 Unfortunately your solution doesn't work. The color of the line doesn't change to light green

![image](https://github.com/ant-design/ant-design-charts/assets/59872680/676a22ba-127e-403d-ad95-66a1ece43373)

**Comment by i11I04i** [comment]
@vadym9 
`
children: [
  {
    type: 'interval'
  },
  {
    type: 'line',
    colorField: () => 'count'
  }
]
`

**Comment by vadym9** [comment]
> @vadym9 `children: [ { type: 'interval' }, { type: 'line', colorField: () => 'count' } ]`

Thank you it works
