### ISSUE TITLE
🧐[问题]请问来源去向图FlowAnalysisGraph支持渲染多少个节点？

### ISSUE THREAD

**Issue by jiangzhenxiang** [ant-design/ant-design-charts#2389]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

虽然说性能可能受限于硬件性能和浏览器的处理能力，
但按现代浏览器和一般笔记本电脑配置，请问来源去向图FlowAnalysisGraph最多支持渲染多少个节点。
给出一个大概范围

**Comment by lxfu1** [comment]
没有实际测试过，由于节点比较复杂，100以内应该比较流畅，建议设置level做异步加载。

**Comment by Chasen-Zhang** [comment]
@lxfu1 请问下，来源去向图的文档放在哪里了呢，树形相关的找不到了

**Comment by lxfu1** [comment]
> @lxfu1 请问下，来源去向图的文档放在哪里了呢，树形相关的找不到了

右上角有个版本，切换到V1就行了

**Comment by Chasen-Zhang** [comment]
@lxfu1 我升级到2.0, 相关的关系图的文档或者示例没看到了呀

**Comment by lxfu1** [comment]
V2 关系图还在开发中

**Comment by Chasen-Zhang** [comment]
@lxfu1 你好呀，能否帮我看看这个问题不，https://ant-design-charts.antgroup.com/api/graphs/common/common-graph

import { FlowAnalysisGraph } from '@ant-design/graphs';
graphCfg: {
      minZoom: 0.5,
      maxZoom: 2,
      containerStyle: {
        backgroundColor: '#f0f0f0', 
      },
    },
   我想控制下最小缩放比和最大缩放比，发现这样写行不通，不然灵敏度太高了。文档似乎也没看法哪里有体现。

**Comment by lxfu1** [comment]
这是个BUG，可以先这样跳过一下

```ts
  onReady: (graph) => {
      graph.setMaxZoom(2)
    },
```
