### ISSUE TITLE
🐛In Venn chart, not able to set the data using state

### ISSUE THREAD

**Issue by Yamini1406** [ant-design/ant-design-charts#2391]
### Expected result:
![Screenshot from 2024-01-30 12-30-23](https://github.com/ant-design/ant-design-charts/assets/77901391/71ed092d-298b-4198-a3ce-fd459993552b)
### Actual result:
![Screenshot from 2024-01-30 12-28-23](https://github.com/ant-design/ant-design-charts/assets/77901391/b1b97843-a2e2-458a-a9ee-0fb40861c9d7)

### 💻 Below is the link to replicate the issue: 
https://stackblitz.com/edit/react-pt7r53-szzyuw?file=index.js : venn chart(not working)
https://stackblitz.com/edit/react-o5coaq?file=index.js : bidirectional bar(working)

### © 版本信息

- @ant-design/plots : version - 2.1.12

**Comment by lxfu1** [comment]
Your data is incorrect
```ts
 {
    sets: ['D'], // ['A']
    size: 12,
    label: 'A',
  },
```
