### ISSUE TITLE
🐛[BUG] 条形图等图形加载不全

### ISSUE THREAD

**Issue by icecliffs** [ant-design/ant-design-charts#2394]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

显示BUG

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

使用Charts官网自带的条形图代码加载不全

![image](https://github.com/ant-design/ant-design-charts/assets/48086093/1024fe43-0814-45bd-bc70-1935d50a71eb)

![image](https://github.com/ant-design/ant-design-charts/assets/48086093/7955bb2b-1e04-4b3e-894a-3fde6e3bf54e)

### 🏞 期望结果 [描述你原本期望看到的结果]

![image](https://github.com/ant-design/ant-design-charts/assets/48086093/a3927c23-0fc9-424e-b77c-c52b5885de36)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

```typescript
import { Bar } from "@ant-design/charts";
import { ProCard } from "@ant-design/pro-components";

const DemoBar = () => {
  const data = [
    {
      year: '1951 年',
      value: 38,
    },
    {
      year: '1952 年',
      value: 52,
    },
    {
      year: '1956 年',
      value: 61,
    },
    {
      year: '1957 年',
      value: 145,
    },
    {
      year: '1958 年',
      value: 48,
    },
  ];
  const config = {
    data,
    xField: 'value',
    yField: 'year',
    seriesField: 'year',
    legend: {
      position: 'top-left',
    },
  };
  return <Bar {...config} />;
};

const Screen: React.FC = () => {
     return (
          <>
          <DemoBar />
          </>
     );
};

export default Screen;
```

### © 版本信息

- ant-design-charts 版本: 2.0.3
- 浏览器环境 Edge
- 开发环境 Windows

**Comment by swsoyee** [comment]
@icecliffs Hi, 我遇到了相同的问题，请问是解决了吗？怎么解决的，谢谢。

**Comment by icecliffs** [comment]
> @icecliffs Hi, 我遇到了相同的问题，请问是解决了吗？怎么解决的，谢谢。

我这解决的办法很简单，也很蠢，只需要把剩下的包安装上即可

```bash
npm install @ant-design/plots
```

https://ant-design-charts.antgroup.com/manual/getting-started
