### ISSUE TITLE
🐛[BUG] 柱线混合图，加 slider 后，样式问题

### ISSUE THREAD

**Issue by Yang-yibu** [ant-design/ant-design-charts#2395]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
添加 slider 和 轴线上的标题后，首次渲染 slider 区域显示有问题，拖动 slider 时比较卡顿，有时候图形会覆盖 y周 区域

![image](https://github.com/ant-design/ant-design-charts/assets/23130670/955a3c2e-1f47-4cc8-af5c-cf687039b635)

![image](https://github.com/ant-design/ant-design-charts/assets/23130670/ed076dd1-815b-45f7-9f10-9b6fc19d4b41)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
线上示例就可以复现
https://ant-design-charts.antgroup.com/zh/examples/dual-axes/column-line#demo-more-1
### © 版本信息

- ant-design-charts 版本: [e.g. 1.4.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
样式问题可以通过如下配置实现，缺失会有点卡，建议升级到V2试试
```ts
 meta: {
      time: { // xField
        sync: false,
      },
    },
```

**Comment by Yang-yibu** [comment]
> 样式问题可以通过如下配置实现，缺失会有点卡，建议升级到V2试试
> 
> ```ts
>  meta: {
>       time: { // xField
>         sync: false,
>       },
>     },
> ```

感觉效果不明显，有时候还是会遮住；升级的话，v2 兼容 v1 的配置么？

**Comment by lxfu1** [comment]
不兼容，配置有变更，可以看下官网的升级文档

**Comment by Yang-yibu** [comment]
可以定位到是什么原因么？
