### ISSUE TITLE
🧐problem in @ant-design/plots

### ISSUE THREAD

**Issue by GrostRane** [ant-design/ant-design-charts#2396]
### 🧐 all I do is reproduce the example from {https://ant-design-charts.antgroup.com/en/examples/tiny/tiny-area/#basic-area} and it doesn’t work - what should I do?
![image](https://github.com/ant-design/ant-design-charts/assets/79666398/c9cae84b-f565-42a0-9c6a-122c36e8ce73)

**Comment by lxfu1** [comment]
The version you installed is incorrect. Your code is for version 1.x, but the actual installation is for 2.x.
```bash
npm install @ant-design/plots@1.2.5 -S
```
