### ISSUE TITLE
🐛[BUG] 2.0.3版本 treemap 数据解析异常

### ISSUE THREAD

**Issue by jonahcui** [ant-design/ant-design-charts#2399]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
数据: {"name":"root","children":[{"id":26,"name":"板房","group":"板房","value":102,"children":[{"groupId":26,"group":"板房","id":1,"name":"admin","value":69},{"groupId":26,"group":"板房","id":26,"name":"李xxx","value":33}]},{"id":6,"name":"管理部","group":"管理部","value":169,"children":[{"groupId":6,"group":"管理部","id":21,"name":"审版师","value":77},{"groupId":6,"group":"管理部","id":22,"name":"李222","value":62},{"groupId":6,"group":"管理部","id":24,"name":"33","value":30}]},{"id":27,"name":"职能","group":"职能","value":138,"children":[{"groupId":27,"group":"职能","id":23,"name":"分厂管理员","value":61},{"groupId":27,"group":"职能","id":27,"name":"分厂员工","value":77}]},{"id":30,"name":"6666部","group":"6666部","value":173,"children":[{"groupId":30,"group":"6666部","id":25,"name":"李7777","value":76},{"groupId":30,"group":"6666部","id":28,"name":"AAAA","value":73},{"groupId":30,"group":"6666部","id":29,"name":"张伟22","value":24}]}]}

配置：{   data: tree,
      colorField: 'group',
      valueField: 'value'}

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
<img width="719" alt="image" src="https://github.com/antvis/G2Plot/assets/101780038/de6ea23a-3ccb-4845-8415-3d1b590b09d4">

### © 版本信息

- ant-design-charts 版本: 2.0.3
- 浏览器环境
- 开发环境  mac OS

**Comment by lxfu1** [comment]
内部有特殊逻辑，先这样处理一下
```ts
colorField: (d) => d.data['group']
```
