### ISSUE TITLE
🐛[BUG] label相关的配置全部失效

### ISSUE THREAD

**Issue by sekayhahaha** [ant-design/ant-design-charts#2400]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
1、label的配置失效，例如：
label: {
      type: 'spider',
      labelHeight: 28,
      content: '{name}\n{percentage}',
},
其中type:"spider"并不能让饼图显示出label
且sandbox中的代码会报错：Unknown Component: shape.spider

2、[快速上手](https://ant-design-charts.antgroup.com/manual/getting-started)中写的：同时记得引入样式文件 import "@ant-design/flowchart/dist/index.css";

实际安装后包内dist下并没有任何的css文件

**Comment by lxfu1** [comment]
你版本安装成V2了，看的是V1的文档，我们稍后更正一下文档安装教程

**Comment by sekayhahaha** [comment]
好的，没注意到版本的问题，谢谢
