### ISSUE TITLE
🐛[BUG] 柱状图的label在小屏幕变成竖向之后，不会自动变回横向

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/ant-design-charts#2402]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

如题

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

1. 画一个柱状图
2. 变成小屏幕
3. 变回大屏幕

### 🏞 期望结果 [描述你原本期望看到的结果]

label重新变回横向

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

不太方便提供现成代码，任何带下方label的柱状图都可以。如果需要我可以在stackblitz上弄一个，但应该很好复现

### © 版本信息

- ant-design-charts 版本: ^2.0.3
- 浏览器环境: Chrome 121
- 开发环境 Windows 11 WSL2 Ubuntu

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

1.
![image](https://github.com/ant-design/ant-design-charts/assets/45784210/d3b5a1e6-5e06-4245-8c7b-0da5edb7f453)
2.
![image](https://github.com/ant-design/ant-design-charts/assets/45784210/391446e7-892f-422f-bbca-0d87e240730d)
3.
![image](https://github.com/ant-design/ant-design-charts/assets/45784210/24c30dd7-b01a-4f66-8d54-543bb83a108f)

**Comment by lxfu1** [comment]
需要配合size使用
```ts
 axis: {
  x: {
    size: 80,
    labelAutoRotate: true,
  }
},
```
