### ISSUE TITLE
Column plot with slider example is broken 🐛[BUG]

### ISSUE THREAD

**Issue by ROTGP** [ant-design/ant-design-charts#2403]
The following example is broken (or the library itself doesn't seem to do what the example is demonstrating)

https://ant-design-charts-next.antgroup.com/en/examples/statistics/column#slider

I understand that the following code is supposed to set the selection of the slider once the onReady event fires. However, this is not happening.

```
chartsInstance.emit('sliderX:filter', {
    data: { selection: [[0.1, 0.2], undefined] },
})
```

Is this a bug? Is there some other way to set the initial slider values on re-rendering?  I have tried everywhere, i can't find it in the documentation. This is a blocker because any time the chart is resized, the slider resets to the min/max values. I'm using V2 of the library.

**Comment by lxfu1** [comment]
The example has not been updated in time, please use the following method.

```ts
 slider: {
  x: {
    values: [0.1, 0.2]
  },
},
```
