### ISSUE TITLE
🧐[问题] CSS of tooltip inreaction is not applied

### ISSUE THREAD

**Issue by seilkhanovk** [ant-design/ant-design-charts#2406]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

I attempted to apply CSS properties to the container of the "tooltip interaction," but unfortunately, it's not working as expected. Could you assist me in identifying what might be causing the issue or what I might be overlooking?

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

```   
 interaction: {
      tooltip: {
        css: {
          backgroundColor: 'red',
        },
      },
    },
```

**Comment by hustcc** [comment]
issue 中的写法有一些小问题，参考这个案例的写法：https://g2.antv.antgroup.com/examples/component/tooltip/#tooltip-style

**Comment by msickpaler** [comment]
I think this should be in the documentation, not just in the example. In fact I spent 3 hours and finally solved it with this issue. how about writing in the tooltip documentation what it refers to for the css key?
