### ISSUE TITLE
🧐[问题] 能否对坐标轴的部分 label 设置样式 

### ISSUE THREAD

**Issue by ZbWeR** [ant-design/ant-design-charts#2410]
### 🧐 问题描述

例如，数据 index 小于某个值是 label 显示为灰色，index 大于某个值时显示为红色。查阅文档发现似乎只能实现统一的 label 样式设置。

### 💻 示例代码

无

### 🚑 其他信息

无

**Comment by hustcc** [comment]
v2 中直接回调即可：

```ts
import { Column } from '@ant-design/plots';
import React from 'react';
import ReactDOM from 'react-dom';

const DemoColumn = () => {
  const config = {
    data: {
      type: 'fetch',
      value: 'https://render.alipay.com/p/yuyan/180020010001215413/antd-charts/column-column.json',
    },
    xField: 'letter',
    yField: 'frequency',
    label: {
      text: (d) => `${(d.frequency * 100).toFixed(1)}%`,
      textBaseline: 'bottom',
      fill: (d, i) => i > 3 ? 'red' : 'blue',  // 👈🏻这里
    },
    axis: {
      y: {
        labelFormatter: '.0%',
      },
    },
    style: {
      // 圆角样式
      radiusTopLeft: 10,
      radiusTopRight: 10,
    },
  };
  return <Column {...config} />;
};

ReactDOM.render(<DemoColumn />, document.getElementById('container'));

```

**Comment by ZbWeR** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/49082837/aa6e86d2-ff3b-4d9b-9497-3b62fc961c67)
很抱歉我对问题的描述不够详细，我的意思是坐标轴（上图红色部分）能否单独控制样式，例如：
![image](https://github.com/ant-design/ant-design-charts/assets/49082837/5f8e404f-d91e-40b5-9d1a-9f12cb3f0a29)

**Comment by hustcc** [comment]
同样的写法，配置 axis.labelFill 属性即可。

**Comment by yyn1108** [comment]
@hustcc 你好，我使用的是v1.2.6版本，想实现你截图里的效果——根据数据自定义label的颜色怎么实现呢？v1不支持fill的函数式写法，试了很多都实现不了，请帮忙指导一下，谢谢！

**Comment by lxfu1** [comment]
去V1官网看一下xAxis的配置

**Comment by yyn1108** [comment]
> 去V1官网看一下xAxis的配置
@lxfu1 
我要实现的是根据数据自定义label的颜色哈，是要去看xAxis的配置吗？刚去看了下，有点困惑，，，
![e651aa3b-f2f5-412a-ac81-551ddf16f18a](https://github.com/ant-design/ant-design-charts/assets/28032523/59ee04a6-4d42-4b25-8067-6d6ef0a7eab4)

**Comment by lxfu1** [comment]
1.x 好像不支持回调，配置颜色的话可以这么操作
```ts
    label: {
      layout: [],
      style: {
          fill: 'red'
        }
    },
```

**Comment by yyn1108** [comment]
我这边的需求是要根据数据自定义label的颜色，比如大于80%展示红色label，小于则展示灰色label，这种v1.x版本怎么实现呢

**Comment by hustcc** [comment]
v1做不到回调。
