### ISSUE TITLE
🐛[BUG] The demo code is not working as it appears in the example

### ISSUE THREAD

**Issue by doiya46** [ant-design/ant-design-charts#2411]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

The demo code is not working as it appears in the example.

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

This is the document: https://ant-design-charts.antgroup.com/en/examples/line/multiple/#line-label
And this is demo code for: https://codesandbox.io/s/p4yu7k

<img width="1092" alt="Screenshot 2024-02-18 at 17 43 48" src="https://github.com/ant-design/ant-design-charts/assets/61301244/0824cf92-ced3-4833-acf6-5326e9688a0e">

### 🏞 期望结果 [描述你原本期望看到的结果]

<img width="1016" alt="Screenshot 2024-02-18 at 17 41 53" src="https://github.com/ant-design/ant-design-charts/assets/61301244/cc7b7869-4403-4148-ba29-f10eaa9ba004">

**Comment by lxfu1** [comment]
Use version V1，latest(2.1.13) => 1.2.6

**Comment by doiya46** [comment]
> Use version V1，latest(2.1.13) => 1.2.6

If I use the latest version, how can I make the UI look like the demo version? Or is the user manual outdated?
