### ISSUE TITLE
antd5项目中使用图表报错问题

### ISSUE THREAD

**Issue by star198474** [ant-design/ant-design-charts#2414]
项目升级到antd5后所有图表都以下错误
Cannot read properties of null (reading 'useRef')
![image](https://github.com/ant-design/ant-design-charts/assets/54663922/81a4f2c1-834e-480a-be6c-36833b79bd8c)

项目依赖
![image](https://github.com/ant-design/ant-design-charts/assets/54663922/e6e2ad82-c823-4349-a970-16de298e3dd7)

**Comment by lxfu1** [comment]
你这个是没有正确加载React，看下Window.React 是否存在，删除node_moduels重新安装试试

**Comment by star198474** [comment]
重新安装后还是不行，目前项目可以正常启动，页面也正常显示，只有用到图表的地方会报错，没有正确加载React是指什么？

**Comment by lxfu1** [comment]
> 重新安装后还是不行，目前项目可以正常启动，页面也正常显示，只有用到图表的地方会报错，没有正确加载React是指什么？

你通过CDN的方式加载 React 试一下，代码里面执行 React.useRef 的时候找不到 React

**Comment by star198474** [comment]
改成CDN方式修改量太大 没有尝试
但目前代码上下文都 可以使用react和useRef（不使用图表即可正常显示），是否底层里对react加载方式有什么要求？
![image](https://github.com/ant-design/ant-design-charts/assets/54663922/cab47152-35e4-46da-9714-b37d23940878)

**Comment by star198474** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/54663922/497c506e-b499-4908-8d3e-f8657157629f)
![image](https://github.com/ant-design/ant-design-charts/assets/54663922/5ba2c98e-c61c-4b1b-b0a9-55d805e71226)
底层代码的这个部分正常加载了react，但是useref这里空指针了

**Comment by lxfu1** [comment]
能提供个最小复现吗？

**Comment by wangzhoubin** [comment]
这个问题怎么解决的呢

**Comment by lxfu1** [comment]
> 这个问题怎么解决的呢

能提供个最小复现吗？

**Comment by wangzhoubin** [comment]
> > 这个问题怎么解决的呢
> 
> 能提供个最小复现吗？

不好意思，不知道什么原因，但是重复删除了node_module 和umi后，弄几下yarn install 就又可以了。

**Comment by Ever-Bright-V** [comment]
我也遇到了

**Comment by zhangyiabc** [comment]
> 我也遇到了

解决了吗？
我也遇见了，react版本16.8.4
