### ISSUE TITLE
🧐[问题] 2.x版本如何使用annotation绘制辅助线和文本

### ISSUE THREAD

**Issue by crystaldust** [ant-design/ant-design-charts#2415]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
现状描述：
在1.x中，可以方便的添加`line`类型的annotation，并添加文本，如绘制中位线：
https://ant-design-charts.antgroup.com/zh/examples/component/annotation#line-annotation-position

在2.x中，line类型分为lineX和lineY，而text类型的annotation似乎必须绑定某个数据项（传入data，xField，yField等），常用于某个特定数据项的辅助文本绘制。而不是像1.x中一样，自行指定内容、相对位置等。

问题：如何在2.x中绘制1.x例子中的辅助线，是使用lineY+text吗？

**Comment by lxfu1** [comment]
是的，参考 [lineY](https://ant-design-charts-next.antgroup.com/options/plots/annotation/line-y)

**Comment by crystaldust** [comment]
> 是的，参考 [lineY](https://ant-design-charts-next.antgroup.com/options/plots/annotation/line-y)

谢谢，那么如果想绘制一个类似1.x示例的辅助文本的话（文本在辅助线上方，在图标最左边），就要使用text Annotation，然后把这个text Annotation的xField设置为整个数据中最早的时间，yField设置和lineY Annotation的yField一致（或者用data设置，data[0]为初始时间，data[1]为lineY的value），是这个思路吗？

**Comment by crystaldust** [comment]
@lxfu1 感谢回复，我按照上述思路测试了一下，遇到几个问题，可能主要是文档方面的，供更新文档时参考：

1. 文档中对shape类型的描述是“目前 area 有以下几个内置的 shape 图形，默认为 text。"第一印象很容易理解成设置area为'badge'或者'text'，但实际是要设置shape字段为'badge'或'text'。最好能把shape字段明确提出来（类似style字段的说明）
2. 文档中说style.textBaseline默认值为'bottom'，但是实际默认值效果是'middle'（文字被辅助线穿过）
3. dx、dy等字段只有示例中出现，没有在后面style选项中说明

另外按照文档测试遇到几个问题：
1. 用annotation.text设置文字内容无效，annotation.encode.text设置生效
2. 以绘制平均值辅助线为例，使用xField=firstItem.date、yField=avgValue映射text Annotation的位置生效。但是使用data = [firstItem.date, avgValue]提示x channel missing
