### ISSUE TITLE
🐛[BUG]to parse source map from 这个问题不能解决一下吗 满屏幕报错

### ISSUE THREAD

**Issue by skyliwq** [ant-design/ant-design-charts#2418]
WARNING in ./node_modules/@antv/util/esm/path/util/segment-quad-factory.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 

这个问题不能解决一下吗 满屏幕报错

**Comment by lxfu1** [comment]
GENERATE_SOURCEMAP 设置为 false 试试

**Comment by HanShuai-me** [comment]
https://bobbyhadz.com/blog/failed-to-parse-source-map-in-create-react-app#:~:text=To%20resolve%20the%20issue%2C%20set%20the%20GENERATE_SOURCEMAP%20environment,ENOENT%3A%20no%20such%20file%20or%20directory%2C%20open%20%27path%27
