### ISSUE TITLE
在behaviors属性中配置scroll-canvas和zoom-canvas:来缩放画布，如何控制缩放的最大最小值

### ISSUE THREAD

**Issue by hunter95671** [ant-design/ant-design-charts#2419]
在behaviors属性中配置scroll-canvas和zoom-canvas:来缩放画布，如何控制缩放的最大最小值

**Comment by lxfu1** [comment]
https://g6.antv.antgroup.com/api/graph-func/get_set#graphsetmaxzoomratio

**Comment by vanthaodhdt** [comment]
@lxfu1 @hunter95671 
can you give me code config scroll-canvas and zoom-canvas?
