### ISSUE TITLE
Ability to format values inside tooltip

### ISSUE THREAD

**Issue by JoeCMorgan** [ant-design/ant-design-charts#242]
It would be incredibly useful to be able to format the values inside the tooltip, in the same way as you can format the values for the axis.

<img width="225" alt="Screenshot 2020-10-14 at 12 23 56" src="https://user-images.githubusercontent.com/10391416/95982672-4ab03d00-0e18-11eb-938b-a56f0f78811c.png">

**Comment by lxfu1** [comment]
customContent, https://charts.ant.design/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip

**Comment by JoeCMorgan** [comment]
Thanks for the reply, I realise that I can create an entirely custom tooltip, having to reproduce everything in the screenshot above, but that seems extremely excessive just to format the values?

**Comment by JoeCMorgan** [comment]
Is there a full list of eventNames anywhere? I have tried element and plot but neither work for what I need.

https://g2plot.antv.vision/en/docs/manual/plots/column#eventname

**Comment by lxfu1** [comment]
> Thanks for the reply, I realise that I can create an entirely custom tooltip, having to reproduce everything in the screenshot above, but that seems extremely excessive just to format the values?

This is not supported at present.

**Comment by lxfu1** [comment]
> Is there a full list of eventNames anywhere? I have tried element and plot but neither work for what I need.
> 
> https://g2plot.antv.vision/en/docs/manual/plots/column#eventname

What events do you want to bind to ?

**Comment by lxfu1** [comment]
> > Is there a full list of eventNames anywhere? I have tried element and plot but neither work for what I need.
> > https://g2plot.antv.vision/en/docs/manual/plots/column#eventname
> 
> What events do you want to bind to ? https://charts.ant.design/guide/case#%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A

**Comment by lxfu1** [comment]
删除package-lock.json重新install
```ts
tooltip: {
  formatter: (item) => item?.value + '%'
}
```

**Comment by lxfu1** [comment]
```ts
tooltip: {
      formatter: (item ) => {
        return {name: item.name, value: `${item.value}%`}
      }
  }
```
