### ISSUE TITLE
🐛[BUG] 饼图使用蜘蛛布局标签，用render方法自定义饼图的label时无连接线，位置处于左上角

### ISSUE THREAD

**Issue by cxOrz** [ant-design/ant-design-charts#2423]
### 🥰 需求描述
G2Plot 的效果如图
![image](https://github.com/ant-design/ant-design-charts/assets/32982052/1703d3c4-81b5-4f1f-b166-3f5a35684277)

在 ant-design-charts 2.0 文档中有这样的描述，可以使用render来自定义，但在使用蜘蛛布局标签的情况下，发现效果并不是预期的那样。
![image](https://github.com/ant-design/ant-design-charts/assets/32982052/ab5ac066-808c-45b3-9a39-5630396a8902)

ant-design-charts 2.0 的效果如图
![image](https://github.com/ant-design/ant-design-charts/assets/32982052/4ac505b6-aa2f-4ae5-a360-f1cac93b1d3e)

**Comment by lxfu1** [comment]
参考这个试试，https://ant-design-charts-next.antgroup.com/examples/statistics/funnel/#pyramid
