### ISSUE TITLE
🐛[BUG] On data change the chart is being vertically stretched by 5 px

### ISSUE THREAD

**Issue by nazar-dzhura** [ant-design/ant-design-charts#2424]
### 📷 On the attached video you can see that the initial chart height is 510px, but when I changed the data - it became 515px. When I changed it back it became 520px. And with each change, it continues to grow vertically.

https://github.com/ant-design/ant-design-charts/assets/17047247/3ce8186b-8e0f-4157-b73d-81fe741e9616

- ant-design-charts: [2.0.3]
- Windows, Chrome Version 121.0.6167.185 (Official Build) (64-bit)

**Comment by lxfu1** [comment]
Specify the height for the container or: 
```ts
{
  autoFit: false,
  height: 515
}
```

**Comment by nazar-dzhura** [comment]
Using autoFit: false and setting chart height manually helped, thanks. 

However, using autoFit: true and specifying the height of the container didn't help, it just overflowed. So you can't make the height dynamic and let the chart take up all available space:
![image](https://github.com/ant-design/ant-design-charts/assets/17047247/c92e13d7-e37e-4d98-952e-b95810701f4d)
