### ISSUE TITLE
🐛[BUG] Area does not support animate prop

### ISSUE THREAD

**Issue by AO19** [ant-design/ant-design-charts#2426]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

When using the Area component, I cannot use the animate prop on the component without TypeScript showing the error: "animate does not exist".

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

1. Use Area component
2. Set in config animate: { enter: { type: "linear" } }
3. Watch crash/ typescript error

### 🏞 期望结果 [描述你原本期望看到的结果]
I can use animate: { enter: { type: "linear" } }

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/p/sandbox/area-no-animate-hhy9d2

### © 版本信息

- ant-design-charts 版本: 2.0.3
- 浏览器环境 Chrome 122.0.6261.57
- 开发环境 macOS 14.3.1 (23D60)

**Comment by lxfu1** [comment]
Type is incorrect, [refer to](https://ant-design-charts-next.antgroup.com/options/plots/animation/overview)
```ts
animate: { 
  enter: { 
    type: 'waveIn',
    easing: "ease-in"
  }
}
```
