### ISSUE TITLE
🧐[问题]能否监听坐标轴的点击事件，并获取到点击的值

### ISSUE THREAD

**Issue by ZbWeR** [ant-design/ant-design-charts#2428]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

我知道可以通过 `component:click` 去监听坐标轴的点击事件，但是从回调函数的 event 对象中我似乎不能找到所需的信息。
我的需求如下：
当我在下图红色区域点击时，能够获取到类似 `tooltip:show` 事件中的 data 值。
![image](https://github.com/ant-design/ant-design-charts/assets/49082837/68495a93-364e-4ec7-83c6-974300c698bd)

**Comment by ZbWeR** [comment]
提供自己的一个方案：
在 `e.target.attributes.text` 中能够拿到被点击部位的 label 值，然后再根据 label 就可以获得相应的 data 值。
```
 chart.on('component:click',(e)=>{
    console.log(e.target.attributes.text);
  })
```

**Comment by lxfu1** [comment]
获取不到，只能绑定到对应的element上才行
