### ISSUE TITLE
完整的配置属性默认值在哪可以找到呢？🧐[问题]

### ISSUE THREAD

**Issue by LazyJoke** [ant-design/ant-design-charts#243]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
非常感谢团队开源了该项目，为广大开发者提供了便利！

问题：目前要基于该组件库进行二次开发，需要给用户提供图表大部分属性的可视化配置功能，看了说明文档，并没有找到详细的属性默认值或可选值说明

**Comment by 951565664** [comment]
https://antv-g2plot.gitee.io/zh/examples/gallery

**Comment by lxfu1** [comment]
参考对应图表getDefaultOptions, https://github.com/antvis/G2Plot/blob/master/src/plots/area/index.ts

**Comment by LazyJoke** [comment]
谢谢回答，还有个小问题，枚举类的属性值在哪能找到？

**Comment by lxfu1** [comment]
大部分在API文档里面，例如 https://github.com/antvis/G2Plot/blob/master/examples/scatter/basic/API.zh.md#shape- ，如果有没有列举的，欢迎issue反馈， 或者直接到更底层的库查看 https://g2.antv.vision/zh/docs/manual/about-g2。

**Comment by LazyJoke** [comment]
感谢解答
