### ISSUE TITLE
🧐[问题]使用Ant Design Charts 中的折线图，X轴时候英文的

### ISSUE THREAD

**Issue by BreezeBoy1** [ant-design/ant-design-charts#2433]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
使用Ant Design Charts 中的折线图，X轴是英文的，怎么改成 2022-11-11

**Comment by BreezeBoy1** [comment]
使用 xField:(d)=> new Date(d.date)
![image](https://github.com/ant-design/ant-design-charts/assets/120365278/7adc35a5-79a4-4615-b7ce-22ad6214b24f)
使用 xField: 'date'  x轴文字太多了

**Comment by BreezeBoy1** [comment]
![image](https://github.com/ant-design/ant-design-charts/assets/120365278/1b4374c0-b1f1-47a9-950d-1e7514af3901)

**Comment by lxfu1** [comment]
axis.x.labelFormatter: (label) => 'xxx'
