### ISSUE TITLE
How to set up different interval for each step for Line chart Y axis 🧐[问题]

### ISSUE THREAD

**Issue by Enigama** [ant-design/ant-design-charts#2436]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
For example  Base line Plot:
from 0 to 500 we have a huge gap how to decrease this gap and do not break the gap that is after 500 - 2500?
I would like to see these steps: [0, 75, 125, 250, 350, 500, ... ,2500] is it possible?
I've tried `tickMethod, tickInterval and tickCount` but it didn't help me.
![image](https://github.com/ant-design/ant-design-charts/assets/28072229/3ff344a5-1f49-4987-bd28-28c60c49992b)

**Comment by lxfu1** [comment]
```ts
    meta: {
      scales: { // yField
        ticks: [0, 75, 125, 250, 350, 500, ... ,2500] 
      }
    },
```
