### ISSUE TITLE
Proper Annotation in Stacked Grouped Bar/Column Chart

### ISSUE THREAD

**Issue by Stephen-Strange** [ant-design/ant-design-charts#2437]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

The annotation calculation is not applied properly in Bar/Column Stacked Grouped Bar Charts due to varying bar/column width when the data index changes.

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库] 
Sandbox : https://codesandbox.io/p/sandbox/stacked-grouped-chart-annotation-gjlfl6

I am trying to provide the year value as annotation. But due to the data index, the bar/column width is changing and the annotation is not displayed properly.

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
Attaching screenshots for reference : 

<img width="694" alt="Screenshot 2024-03-05 at 4 24 17 PM" src="https://github.com/ant-design/ant-design-charts/assets/74187417/e7ad3fad-52b7-45f1-90e4-56a6372b54e5">
<img width="607" alt="Screenshot 2024-03-05 at 4 24 32 PM" src="https://github.com/ant-design/ant-design-charts/assets/74187417/fcbd5a60-255a-404e-93eb-7aff628d7d70">

**Comment by khjabir** [comment]
+1

**Comment by lxfu1** [comment]
I don't understand your question！

**Comment by Stephen-Strange** [comment]
@lxfu1 It is basically, how can we show the annotations properly for a stacked grouped bar/column chart? I need to center the annotations against each bar/column

**Comment by Stephen-Strange** [comment]
@lxfu1 To be more clear,

![WhatsApp Image 2024-03-06 at 7 47 51 PM](https://github.com/ant-design/ant-design-charts/assets/74187417/2c4dcd0b-8c90-4211-9cd4-da2748be4e34)

This is what I am trying to achieve in Bar/Column chart

**Comment by lxfu1** [comment]
Refer to [custom x label](https://ant-design-charts.antgroup.com/examples/statistics/column/#label-text)

```ts
const { chart } = chartRef.current;
const { document } = chart.getContext().canvas;
const elements = document.getElementsByClassName('element');
const bbox = elements[0].getBBox(); // elements[index];
```
