### ISSUE TITLE
👑 [需求]多折线图 如何自定义颜色没有文档

### ISSUE THREAD

**Issue by BlazeXue** [ant-design/ant-design-charts#2438]

**Comment by lxfu1** [comment]
[scale.color](https://ant-design-charts-next.antgroup.com/zh/examples/statistics/line/#color)

**Comment by BlazeXue** [comment]
scale只对折线起作用吗，柱状，饼图呢？

**Comment by lxfu1** [comment]
都生效的，你看下是不是版本问题，示例里面多找一下
