### ISSUE TITLE
ant-design-charts x轴 固定label的宽度🧐

### ISSUE THREAD

**Issue by kkkccc100** [ant-design/ant-design-charts#2439]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我想在图标的x轴上，设定固定的宽度来展示
比如：设定10xp的宽度，每个10px展示一个刻度，还有刻度值

**Comment by lxfu1** [comment]
看下 axis 相关的配置，可以指定相关ticks

**Comment by kkkccc100** [comment]
好的谢谢
得从 tickFilter 下手了
