### ISSUE TITLE
🧐[问题]折线图怎么在一开始默认展示某个点的tooltip

### ISSUE THREAD

**Issue by ChrisXYF** [ant-design/ant-design-charts#2441]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
折线图怎么在一开始默认展示某个点的tooltip，目前想一开始渲染时展示折线图最低点点tooltip

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
目前写了但是没有作用：
onReady: (plot) => {
      const { chart } = plot;
      chart.showTooltip({ x: '24.03.04', y: 7.8 });
    },

**Comment by lxfu1** [comment]
那个版本？看下相关issue

https://github.com/ant-design/ant-design-charts/issues/1297
