### ISSUE TITLE
🐛[BUG]渐变色面积图Area组中Tooltip的Item重复显示

### ISSUE THREAD

**Issue by smoothdvd** [ant-design/ant-design-charts#2443]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
面积图Area组中Tooltip的Item重复显示

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
官方例子：https://ant-design-charts-next.antgroup.com/examples/statistics/area/#area-gradient

### 🏞 期望结果 [描述你原本期望看到的结果]
Tooltip正确显示Item数量

### © 版本信息

- ant-design-charts 版本: [e.g. 2.0.3]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="673" alt="Screenshot 2024-03-09 at 2 38 10 PM" src="https://github.com/ant-design/ant-design-charts/assets/22420/011a75db-c6e7-4c6c-988a-38349bd00f26">

**Comment by lxfu1** [comment]
先这样处理一下
```ts
line: {
  tooltip: false,
},
```
