### ISSUE TITLE
🐛[BUG]堆叠面积图-数据的y轴和图内的点对应不上

### ISSUE THREAD

**Issue by yuaiai0419** [ant-design/ant-design-charts#2451]
### © 版本信息  1.x，2.x都不行

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by yuaiai0419** [comment]
这个套data  const mock=[
    {
        "value": 330.6255302429199,
        "date": 1710321660,
        "category": "diskFree(GB)[max]"
    },
    {
        "value": 330.6252784729004,
        "date": 1710322200,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.6252555847168,
        "date": 1710322260,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.62522888183594,
        "date": 1710322320,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.6252021789551,
        "date": 1710322380,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.62517166137695,
        "date": 1710322440,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.6251411437988,
        "date": 1710322500,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.6251106262207,
        "date": 1710322560,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.6250877380371,
        "date": 1710322620,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.625057220459,
        "date": 1710322680,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.6250343322754,
        "date": 1710322740,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.625,
        "date": 1710322800,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.6249694824219,
        "date": 1710322860,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.624942779541,
        "date": 1710322920,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.6249122619629,
        "date": 1710322980,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.6248893737793,
        "date": 1710323040,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.62486267089844,
        "date": 1710323100,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330,
        "date": 1710323160,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.624813079834,
        "date": 1710323220,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.62478256225586,
        "date": 1710323280,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.62475204467773,
        "date": 1710323340,
        "category": "diskFree(GB)[p99]"
    },
    {
        "value": 330.6255302429199,
        "date": 1710321660,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6254997253418,
        "date": 1710321720,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.62547302246094,
        "date": 1710321780,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.62545013427734,
        "date": 1710321840,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6254234313965,
        "date": 1710321900,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6254005432129,
        "date": 1710321960,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.62537002563477,
        "date": 1710322020,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6253356933594,
        "date": 1710322080,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6253128051758,
        "date": 1710322140,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6252784729004,
        "date": 1710322200,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6252555847168,
        "date": 1710322260,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.62522888183594,
        "date": 1710322320,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6252021789551,
        "date": 1710322380,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.62517166137695,
        "date": 1710322440,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6251411437988,
        "date": 1710322500,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6251106262207,
        "date": 1710322560,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6250877380371,
        "date": 1710322620,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.625057220459,
        "date": 1710322680,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6250343322754,
        "date": 1710322740,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.625,
        "date": 1710322800,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6249694824219,
        "date": 1710322860,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.624942779541,
        "date": 1710322920,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6249122619629,
        "date": 1710322980,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6248893737793,
        "date": 1710323040,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.62486267089844,
        "date": 1710323100,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330,
        "date": 1710323160,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.624813079834,
        "date": 1710323220,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.62478256225586,
        "date": 1710323280,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.62475204467773,
        "date": 1710323340,
        "category": "diskFree(GB)[p95]"
    },
    {
        "value": 330.6255302429199,
        "date": 1710321660,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6254997253418,
        "date": 1710321720,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.62547302246094,
        "date": 1710321780,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.62545013427734,
        "date": 1710321840,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6254234313965,
        "date": 1710321900,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6254005432129,
        "date": 1710321960,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.62537002563477,
        "date": 1710322020,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6253356933594,
        "date": 1710322080,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6253128051758,
        "date": 1710322140,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6252784729004,
        "date": 1710322200,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6252555847168,
        "date": 1710322260,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.62522888183594,
        "date": 1710322320,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6252021789551,
        "date": 1710322380,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.62517166137695,
        "date": 1710322440,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6251411437988,
        "date": 1710322500,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6251106262207,
        "date": 1710322560,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6250877380371,
        "date": 1710322620,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.625057220459,
        "date": 1710322680,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6250343322754,
        "date": 1710322740,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.625,
        "date": 1710322800,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6249694824219,
        "date": 1710322860,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.624942779541,
        "date": 1710322920,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6249122619629,
        "date": 1710322980,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.6248893737793,
        "date": 1710323040,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330.62486267089844,
        "date": 1710323100,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330,
        "date": 1710323160,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330,
        "date": 1710323220,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330,
        "date": 1710323280,
        "category": "diskFree(GB)[p50]"
    },
    {
        "value": 330,
        "date": 1710323340,
        "category": "diskFree(GB)[p50]"
    }
]

**Comment by yuaiai0419** [comment]
不知道为啥，上传不了图片

**Comment by lxfu1** [comment]
应该是数据问题，建议用简单数据测试一下，参考官网数据结构

**Comment by yuaiai0419** [comment]
> 应该是数据问题，建议用简单数据测试一下，参考官网数据结构

是数据精度太大了吗

**Comment by lxfu1** [comment]
可能有回路，你把 xFIield 转换为 time string 试一下

**Comment by yuaiai0419** [comment]
> 可能有回路，你把 xFIield 转换为 time string 
转完也是一样的，y轴还是有问题,主要是y轴 ，配置是这个，可以拿上边那套数据在官网试试，官网的1.x，2.x 都一样的效果
const config = {
    data: mock,
    xField: 'date',
    yField: 'value',
    xAxis: {
      label: {
        formatter: (v)=>   new Date(v)
      },
    },
    seriesField: 'category',
  };

**Comment by yuaiai0419** [comment]
> 可能有回路，你把 xFIield 转换为 time string 试一下
这套数据和配置用在折线图，线就是重叠起来的，但用在面积图里就不行了

**Comment by lxfu1** [comment]
你提供的数据确实有问题，咨询看下图，第一条数据就缺失了一个类别

![image](https://github.com/ant-design/ant-design-charts/assets/31396322/c4983f04-24fe-462a-9ea9-8bfa40692f8c)

**Comment by yuaiai0419** [comment]
> 你提供的数据确实有问题，咨询看下图，第一条数据就缺失了一个类别
> 
> ![image](https://private-user-images.githubusercontent.com/31396322/314434628-c4983f04-24fe-462a-9ea9-8bfa40692f8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzEzMjYsIm5iZiI6MTcxNjE3MTAyNiwicGF0aCI6Ii8zMTM5NjMyMi8zMTQ0MzQ2MjgtYzQ5ODNmMDQtMjRmZS00NjJhLTllYTktOGJmYTQwNjkyZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAyMTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYjk1ZGE1N2Y3MDVhNWZkYzlhMDQ4NzhkNGZkNTc4ZDEzYTJmN2YyYjE1Y2JkZGEzOWFjOTI5MzEwNmEwYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3siJThdlviTAMqcBMK3xGu734nUosMcuALY_JubARiY)
但这个数据换成 折线图，就是正常展示的，没看懂标记搜索的是什么
