### ISSUE TITLE
🐛[BUG] 新版雷达图,指标值都相同时,如果没有area这个属性,会出现报错,图表显示不出来

### ISSUE THREAD

**Issue by qtj4js** [ant-design/ant-design-charts#2453]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
见title

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://ant-design-charts-next.antgroup.com/zh/examples/statistics/radar#basic
将指标值设置为一样,并且删除area
![企业微信截图_17103985007597](https://github.com/ant-design/ant-design-charts/assets/47909978/3b31b1c6-4e32-4747-b533-6d0c741ea537)

### 🏞 期望结果 [描述你原本期望看到的结果]
正常显示图表

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
参考截图即可

### © 版本信息

- ant-design-charts 版本: 2.1.14
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
这种情况下需要配置一下domainMin
```ts
scale.y.domainMin: 0
```
