### ISSUE TITLE
f2 如何在RN 中使用呢

### ISSUE THREAD

**Issue by laichangp** [ant-design/ant-design-charts#2457]
### 🧐 f2如何在RN 中引用呢,以下代码在RN 中加载不出来

import React from 'react';
import { Line } from '@ant-design/charts';

const Page: React.FC = () => {
  const data = [
    { year: '1991', value: 3 },
    { year: '1992', value: 4 },
    { year: '1993', value: 3.5 },
    { year: '1994', value: 5 },
    { year: '1995', value: 4.9 },
    { year: '1996', value: 6 },
    { year: '1997', value: 7 },
    { year: '1998', value: 9 },
    { year: '1999', value: 13 },
  ];

  const config = {
    data,
    height: 400,
    xField: 'year',
    yField: 'value',
  };
  return <Line {...config} />;
};
export default Page;

**Comment by lxfu1** [comment]
不支持RN
