### ISSUE TITLE
🐛[BUG]: issue with types for some base options

### ISSUE THREAD

**Issue by pranit1705** [ant-design/ant-design-charts#2462]
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

Getting typescript errors for xFields and sizeField options in chart configuration, when using in react js typescript application 

![Screenshot from 2024-03-19 18-16-55](https://github.com/ant-design/ant-design-charts/assets/51791997/4b812c41-459e-4061-883b-3949d6e24373)

![image](https://github.com/ant-design/ant-design-charts/assets/51791997/22ae5942-79b6-41a0-bac5-7dcf888871a5)

This issue is there for some other options as well such as ```reverse``` in sort
```js
sort: {
    reverse: true,
},
```

### 🏞 期望结果 [描述你原本期望看到的结果]

I guess, xField should have been type of **PrimitiveEncodeSpec** but when using in application, it only has string type
below image is from source code
![image](https://github.com/ant-design/ant-design-charts/assets/51791997/cc34c681-7b50-40c7-b77b-e905656fe16a)

type when using in application
![image](https://github.com/ant-design/ant-design-charts/assets/51791997/5a6f94e5-f998-4df3-a2ff-58922c61e6c2)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
LineChart.tsx

```ts
const LineChart = () => {
  const config: LineConfig = {
    data: {
      type: "fetch",
      value:
        "https://gw.alipayobjects.com/os/bmw-prod/55424a73-7cb8-4f79-b60d-3ab627ac5698.json",
    },
    xField: (d: any) => new Date(d.year),
    yField: "value",
    point: {
      shapeField: "square",
      sizeField: 4,
    },
    interaction: {
      tooltip: {
        marker: false,
      },
    },
    style: {
      lineWidth: 2,
    },
  };

  return <Line {...config} />;
};
```

### © 版本信息

- ant-design/charts: 2.0.3
- ant-design/plots: 2.1.14
- react: 18.2.0
- Browser: Chrome
- 开发环境 : Ubuntu

**Comment by lxfu1** [comment]
We will fix it in the next minor version.

```ts
// @ts-nocheck
// This first line takes effect

OR 

// @ts-ignore
```
