### ISSUE TITLE
Installing ant-design-charts

### ISSUE THREAD

**Issue by Vincenteliezer** [ant-design/ant-design-charts#2464]
Hello have installed ant-design-charts with; npm install @ant-design/charts --save in my nextjs project but am getting these npm issues;

18 high severity vulnerabilities

To address all issues, run:
  npm audit fix
  
 Tried using npm audit fix nothing works, Nothing gets fixed, also tried npm audit fix --force and more errors just came. 
 
 I don't know why am getting all these 18 high severity vulnerabilities npm issues
 
 Full audit report
 up to date, audited 709 packages in 7s

# npm audit report

d3-color  <3.1.0
Severity: high
d3-color vulnerable to ReDoS - https://github.com/advisories/GHSA-36jr-mh4h-2g58
fix available via `npm audit fix`
node_modules/@antv/g-lite/node_modules/d3-color
  @antv/g-lite  *
  Depends on vulnerable versions of d3-color
  node_modules/@antv/g-lite
    @antv/g  >=5.8.9
    Depends on vulnerable versions of @antv/g-camera-api
    Depends on vulnerable versions of @antv/g-dom-mutation-observer-api
    Depends on vulnerable versions of @antv/g-lite
    Depends on vulnerable versions of @antv/g-web-animations-api
    node_modules/@antv/g
      @ant-design/plots  >=2.0.0-alpha.0
      Depends on vulnerable versions of @antv/g
      Depends on vulnerable versions of @antv/g2
      Depends on vulnerable versions of @antv/g2-extension-plot
      node_modules/@ant-design/plots
      @antv/component  >=1.0.0-beta.1
      Depends on vulnerable versions of @antv/g
      node_modules/@antv/component
        @antv/g2  >=5.0.17
        Depends on vulnerable versions of @antv/component
        Depends on vulnerable versions of @antv/g
        Depends on vulnerable versions of @antv/g-canvas
        Depends on vulnerable versions of @antv/g-plugin-dragndrop
        node_modules/@antv/g2
      @antv/g2-extension-plot  *
      Depends on vulnerable versions of @antv/g
      Depends on vulnerable versions of @antv/g2
      node_modules/@antv/g2-extension-plot
    @antv/g-camera-api  *
    Depends on vulnerable versions of @antv/g-lite
    node_modules/@antv/g-camera-api
    @antv/g-canvas  >=1.9.0
    Depends on vulnerable versions of @antv/g-lite
    Depends on vulnerable versions of @antv/g-plugin-canvas-path-generator
    Depends on vulnerable versions of @antv/g-plugin-canvas-picker
    Depends on vulnerable versions of @antv/g-plugin-canvas-renderer
    Depends on vulnerable versions of @antv/g-plugin-dom-interaction
    Depends on vulnerable versions of @antv/g-plugin-html-renderer
    Depends on vulnerable versions of @antv/g-plugin-image-loader
    node_modules/@antv/g-canvas
    @antv/g-dom-mutation-observer-api  *
    Depends on vulnerable versions of @antv/g-lite
    node_modules/@antv/g-dom-mutation-observer-api
    @antv/g-plugin-canvas-path-generator  >=1.1.12
    Depends on vulnerable versions of @antv/g-lite
    node_modules/@antv/g-plugin-canvas-path-generator
      @antv/g-plugin-canvas-picker  <=1.0.0-alpha.32 || 1.1.8-alpha.0 - 1.6.0 || >=1.8.9
      Depends on vulnerable versions of @antv/g-lite
      Depends on vulnerable versions of @antv/g-plugin-canvas-path-generator
      Depends on vulnerable versions of @antv/g-plugin-canvas-renderer
      node_modules/@antv/g-plugin-canvas-picker
      @antv/g-plugin-canvas-renderer  1.1.8-alpha.0 - 1.6.0 || >=1.7.15
      Depends on vulnerable versions of @antv/g-lite
      Depends on vulnerable versions of @antv/g-plugin-canvas-path-generator
      Depends on vulnerable versions of @antv/g-plugin-image-loader
      node_modules/@antv/g-plugin-canvas-renderer
    @antv/g-plugin-dom-interaction  >=1.7.12
    Depends on vulnerable versions of @antv/g-lite
    node_modules/@antv/g-plugin-dom-interaction
    @antv/g-plugin-dragndrop  >=1.6.12
    Depends on vulnerable versions of @antv/g-lite
    node_modules/@antv/g-plugin-dragndrop
    @antv/g-plugin-html-renderer  >=1.7.12
    Depends on vulnerable versions of @antv/g-lite
    node_modules/@antv/g-plugin-html-renderer
    @antv/g-plugin-image-loader  >=1.1.13
    Depends on vulnerable versions of @antv/g-lite
    node_modules/@antv/g-plugin-image-loader
    @antv/g-web-animations-api  *
    Depends on vulnerable versions of @antv/g-lite
    node_modules/@antv/g-web-animations-api

18 high severity vulnerabilities

To address all issues, run:
  npm audit fix

**Comment by lxfu1** [comment]
#package.json

```sh
resolutions: {
  "d3-color": "^3.1.0"
}
```

**Comment by Vincenteliezer** [comment]
Tried this but no change!

**Comment by pferreirafabricio** [comment]
> #package.json
> 
> ```shell
> resolutions: {
>   "d3-color": "^3.1.0"
> }
> ```

That works for me, but as I'm using npm I have to use the "overrides" configuration instead of "resolutions".

**Comment by Vincenteliezer** [comment]
@pferreirafabricio Thank you! This worked!
