### ISSUE TITLE
轴标题如何设置成水平方向？

### ISSUE THREAD

**Issue by wooxyz** [ant-design/ant-design-charts#2467]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://github.com/ant-design/ant-design-charts/assets/33221294/3143e5e9-f9d5-471b-8c3a-de481a970f62)

**Comment by lxfu1** [comment]
axis.y.titleTransform:  'rotate(90deg)'

**Comment by lxfu1** [comment]
额，你是V1版本啊
```ts
 title: {
        rotate: Math.PI / 6,
        text: '年份',
        style: {
          fontSize: 16,
        },
      },
```

**Comment by wooxyz** [comment]
> 额，你是V1版本啊
> 
> ```ts
>  title: {
>         rotate: Math.PI / 6,
>         text: '年份',
>         style: {
>           fontSize: 16,
>         },
>       },
> ```

不好意思，问题没说清楚。谢谢你的回答。

**Comment by AmorDiamond** [comment]
> axis.y.titleTransform: 'rotate(90deg)'

你好，2.2.6版本这样设置，知识镜像翻转里title，并不是水平旋转90度

默认效果

![Image](https://github.com/user-attachments/assets/e0fb6ede-d537-4ac9-8ad7-0ae3f4105993)

设置 axis.y.titleTransform: 'rotate(90deg)' 效果

![Image](https://github.com/user-attachments/assets/951c8d1e-e1b6-4e9a-938d-b3ea91566a41)

另外，设置axis.y.titlePosition = 'top'，图表和容器左侧仍然存在很宽的间距。

**Comment by AmorDiamond** [comment]
> > axis.y.titleTransform: 'rotate(90deg)'
> 
> 你好，2.2.6版本这样设置，只是镜像翻转了title（垂直180度），并不是水平旋转90度
> 
> 默认效果
> 
> ![Image](https://github.com/user-attachments/assets/e0fb6ede-d537-4ac9-8ad7-0ae3f4105993)
> 
> 设置 axis.y.titleTransform: 'rotate(90deg)' 效果
> 
> ![Image](https://github.com/user-attachments/assets/951c8d1e-e1b6-4e9a-938d-b3ea91566a41)
> 
> 另外，设置axis.y.titlePosition = 'top'，图表和容器左侧仍然存在很宽的间距。
> 
> [@lxfu1](https://github.com/lxfu1)

🤦原来rotate(90deg)是默认值，设置为rotate(0deg)就是水平了，但是设置titlePosition: 'top'后，左边还是有很宽的间距，请问有左边间距的配置吗？

![Image](https://github.com/user-attachments/assets/99e03a12-dbc0-4ee9-b7af-dcfe75f20314)
