### ISSUE TITLE
🐛[BUG]Can't resolve '@antv/path-util/lib/is-polygons-intersect'

### ISSUE THREAD

**Issue by HZ-RotatingBlock** [ant-design/ant-design-charts#247]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
模块缺失导致webpack打包报错，项目无法正确运行
### 🏞 期望结果 [描述你原本期望看到的结果]
项目正确运行
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
![image](https://user-images.githubusercontent.com/22911435/96106172-75c88880-0f0d-11eb-9afa-5741270de948.png)

### © 版本信息

- ant-design-charts 版本: 0.9.13 or 1.0.0 or 1.0.1
- 浏览器环境: chrome 86.0.4240.80
- 开发环境：mac OS 10.15.7

**Comment by HZ-RotatingBlock** [comment]
手动安装@antv/path-util

**Comment by afc163** [comment]
这大概率是 bug。
