### ISSUE TITLE
怎么修改过y轴轴线的背景色呢 默认的太淡了 👑 [需求]

### ISSUE THREAD

**Issue by wscymdb** [ant-design/ant-design-charts#2474]
怎么修改过y轴轴线的背景色呢 默认的太淡了
读了你们的文档
真心想吐槽啊

**Comment by pranit1705** [comment]
if you want to change the color of axis line. 

```js
axis: {
      x: {
        line: true,
        lineExtension: [5, 5],
        lineStroke: '#4CAF50',
        lineLineWidth: 2,
      },
      y: {
        line: true,
        // lineExtension: [5, 5],
        lineStroke: '#4CAF50',
        lineLineWidth: 2,
        lineLineDash: [5, 5],
      },
    }
```
![image](https://github.com/ant-design/ant-design-charts/assets/51791997/660f168e-f5d9-4b69-b118-360764a84ff5)

Doc: https://ant-design-charts.antgroup.com/en/options/plots/component/axis

**Comment by hawohawo** [comment]
大佬，antd design的charts中的x轴刻度太长自动换行这个labelAutoWrap中说指定size才能生效，这个size指的是哪个？

**Comment by wscymdb** [comment]
![Uploading image.png…]()
我想更改的是这里面的线条颜色

**Comment by wscymdb** [comment]
![Snipaste_2024-03-28_10-39-28](https://github.com/ant-design/ant-design-charts/assets/84276539/ee346da2-7d16-4623-9dc8-43d1bc8298ed)
wo我想更改的是如图所示的线条颜色 默认的太浅了

**Comment by pranit1705** [comment]
use grid options
```js
axis: {
      x: {
        grid: true,
        gridLineWidth: 1,
        gridStroke: '#4CAF50',
        gridLineDash: [5, 5],
        gridStrokeOpacity: 0.8,
      },
      y: {
        grid: true,
        gridLineWidth: 1,
        gridStroke: '#7E57C2',
        gridLineDash: [5, 5],
        gridStrokeOpacity: 0.8,
      },
    },
```

**Comment by wscymdb** [comment]
thank you so much
