### ISSUE TITLE
【问题】引用charts的时候提示Object(...) is not a function

### ISSUE THREAD

**Issue by sumuyang** [ant-design/ant-design-charts#248]
![image](https://user-images.githubusercontent.com/33046550/96109306-19fffe80-0f11-11eb-9374-e11c4966239f.png)
![image](https://user-images.githubusercontent.com/33046550/96109372-25532a00-0f11-11eb-9252-f9cb2bf0642b.png)

**Comment by lxfu1** [comment]
升级下 React 版本 ，能支持 hooks 的。

**Comment by lxfu1** [comment]
给个复现地址吧

**Comment by sumuyang** [comment]
![image](https://user-images.githubusercontent.com/33046550/96203189-cd113c00-0f93-11eb-86bc-10ada7abbfec.png)
yijieju已解决，react版本不支持造成的，谢谢

**Comment by JZue** [comment]
我用的16.6.3的react也出现了这个问题，还没解决

**Comment by ccksfh** [comment]
+1

"react": "^16.8.6",
"react-dom": "^16.8.6",
"@ant-design/charts": "^1.0.7",

依然有问题，简单的demo都跑不通

**Comment by startgirl** [comment]
> +1
> 
> "react": "^16.8.6",
> "react-dom": "^16.8.6",
> "@ant-design/charts": "^1.0.7",
> 
> 依然有问题，简单的demo都跑不通

后来有解决嘛

**Comment by ConnectionLeve** [comment]
有解决吗？我的一值报这个错误 切换了recat版本也是无济于事 @ant-design/charts  TypeError: Object(...) is not a function

**Comment by lxfu1** [comment]
[FAQ](https://charts.ant.design/zh-CN/guide/faq#2%E3%80%81object-is-not-a-function)

**Comment by lxfu1** [comment]
> 有解决吗？我的一值报这个错误 切换了recat版本也是无济于事 @ant-design/charts TypeError: Object(...) is not a function

直接拷贝代码试一下，新建一个.tsx 或 .jsx 文件，不要做任何改动。

**Comment by ConnectionLeve** [comment]
![image](https://user-images.githubusercontent.com/52031408/127586740-e940386d-e4d1-4d8a-947c-306cbd91e059.png)
打包没没有报错，本地运行也是ok的。调试发现引入@ant-design/charts  就会抛出图片中的错误。  "dependencies": {
    "@ant-design/charts": "^0.9.6",
    "antd": "^3.4.1",
    "axios": "^0.18.0",
    "babel-polyfill": "^6.23.0",
    "classnames": "^2.2.5",
    "cross-env": "^5.0.5",
    "d3-shape": "^1.2.0",
    "draftjs-to-markdown": "^0.5.0",
    "dva": "^2.2.2",
    "dva-loading": "^2.0.0",
    "echarts": "^4.0.0",
    "echarts-for-react": "^2.0.0",
    "echarts-gl": "^1.0.0-beta.5",
    "echarts-liquidfill": "^2.0.0",
    "ejs-loader": "^0.3.0",
    "highcharts-exporting": "^0.1.2",
    "highcharts-more": "^0.1.2",
    "history": "^4.7.2",
    "js-beautify": "^1.6.14",
    "jsonp": "^0.2.1",
    "less-vars-to-js": "^1.1.2",
    "lodash": "^4.17.4",
    "mockjs": "^1.0.1-beta3",
    "nprogress": "^0.2.0",
    "path-to-regexp": "^2.1.0",
    "prop-types": "^15.5.10",
    "qs": "^6.5.0",
    "query-string": "^5.1.1",
    "rc-tween-one": "^1.3.1",
    "react": "^16.14.0",
    "react-countup": "^3.0.2",
    "react-dom": "^16.2.0",
    "react-draft-wysiwyg": "^1.10.0",
    "react-helmet": "^5.1.3",
    "react-highcharts": "^16.0.2",
    "recharts": "^1.0.0-beta.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.1.0",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-dva-hmr": "^0.4.0",
    "babel-plugin-import": "^1.1.1",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-runtime": "^6.9.2",
    "copy-webpack-plugin": "^4.0.1",
    "draftjs-to-html": "^0.8.1",
    "dva-model-extend": "^0.1.1",
    "eslint": "^4.1.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-import-resolver-node": "^0.3.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": "^2.6.1",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.1.0",
    "html-webpack-plugin": "^3.2.0",
    "redbox-react": "^1.2.10",
    "roadhog": "1.3.1"
  },

**Comment by wansuiasdn** [comment]
"react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.0.16"
