### ISSUE TITLE
🐛[BUG] Can change the background of <Line> component

### ISSUE THREAD

**Issue by SquirrelCorporation** [ant-design/ant-design-charts#2485]
Hi,
I don't really get how you can customize the background of a Line Chart
`
import { Line } from '@ant-design/plots';
`

I tried settings:
```
theme: { backgroundColor: "white"}
theme: { color: "white"}
theme: { background: "white"}
theme: { fill: "white"}
```
In config

The same apply with registering a custom theme like:
https://g2plot.antv.antgroup.com/en/examples/general/theme/#register-theme
That said "theme not found"

full code here https://github.com/SquirrelCorporation/SquirrelServersManager/blob/master/client/src/pages/Dashboard/Components/MainChartCard.tsx#L92

**Comment by hustcc** [comment]
Which version?

- v1

```ts
theme: {
  background: 'red'
}
```

- v2

```ts
{
theme: {
  view: {
    viewFill: 'red',
  }
}
```
