### ISSUE TITLE
🧐 Column 自定义 tooltip 展示 [Object object]

### ISSUE THREAD

**Issue by SageKwun** [ant-design/ant-design-charts#2487]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

设置 config 的 interaction tooltip，展示 [Object object]，在官网的示例代码里能渲染出来，本地不行

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

```
	const config: ColumnConfig = {
		data,
		width: 500,
		height: 200,
		xField: 'month',
		yField: 'total_containers',
		axis: {
			grid: true,
		},
		style: {
			fill: () => '#C8E3FF',
			maxWidth: 18,
			minWidth: 18,
		},
		state: {
			active: {
				fill: 'l(0.3) 0:#0094FF 1:#0165FA',
			},
		},
		interaction: {
			tooltip: {
				render: (e, { title, items }) => {
					return (
						<div>1</div>
					);
				},
			},
		},
	};
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://github.com/ant-design/ant-design-charts/assets/65765025/577909c1-9817-4d0c-be1d-9f4f3c74605f)

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 172.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    pnpm: 8.11.0 - ~/.nvm/versions/node/v18.14.0/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.87
    Safari: 16.1
  npmPackages:
    @ant-design/charts: 2.0.3

**Comment by lxfu1** [comment]
检查下@ant-design/plots的版本，是否是最新的

**Comment by SageKwun** [comment]
> 检查下@ant-design/plots的版本，是否是最新的

没有直接安装 @ant-design/plots，node_modules/@ant-design/charts/package.json 里是 "@ant-design/plots": "^2.1.3"，看了一下 pnpm-lock.yaml 是：

```
  /@ant-design/charts@2.0.3(lodash-es@4.17.21)(react-dom@18.2.0)(react@18.2.0):
    resolution: {integrity: sha512-CDyDRoMLtUcZ6ZU92nmW23Yt9a9KJU3Z/i5RPMasDuBMShTPNY3i/sOQgv5nTho+7FfBMVrdAax+cKAYcAz3jQ==}
    peerDependencies:
      lodash-es: ^4.17.21
      react: '>=16.8.4'
      react-dom: '>=16.8.4'
    dependencies:
      '@ant-design/plots': 2.1.15(lodash-es@4.17.21)(react-dom@18.2.0)(react@18.2.0)
      lodash-es: 4.17.21
      react: 18.2.0
      react-dom: 18.2.0(react@18.2.0)
    dev: false
```

在node_modules/.pnpm/@ant-design+plots@2.1.15_lodash-es@4.17.21_react-dom@18.2.0_react@18.2.0也确认是，应该是最新的 2.1.15

**Comment by lxfu1** [comment]
最外层容器加个标识跳过一下，应该和构建脚本有关，<div data-type="react">1</div>。

**Comment by SageKwun** [comment]
> 最外层容器加个标识跳过一下，应该和构建脚本有关，
> 
> 1
> 。

没有理解，能麻烦详细说一下吗

**Comment by saaadshot** [comment]
> > Check the version of @ant-design/plots to see if it is the latest one
> 
> @ant-design/plots is not installed directly, node_modules/@ant-design/charts/package.json contains "@ant-design/plots": "^2.1.3", and after looking at pnpm-lock.yaml, it is:
> 
> ```
>   /@ant-design/charts@2.0.3(lodash-es@4.17.21)(react-dom@18.2.0)(react@18.2.0):
>     resolution: {integrity: sha512-CDyDRoMLtUcZ6ZU92nmW23Yt9a9KJU3Z/i5RPMasDuBMShTPNY3i/sOQgv5nTho+7FfBMVrdAax+cKAYcAz3jQ==}
>     peerDependencies:
>       lodash-es: ^4.17.21
>       react: '>=16.8.4'
>       react-dom: '>=16.8.4'
>     dependencies:
>       '@ant-design/plots': 2.1.15(lodash-es@4.17.21)(react-dom@18.2.0)(react@18.2.0)
>       lodash-es: 4.17.21
>       react: 18.2.0
>       react-dom: 18.2.0(react@18.2.0)
>     dev: false
> ```
> 
> In node_modules/.pnpm/@ant-design+plots@2.1.15_lodash-es@4.17.21_react-dom@18.2.0_react@18.2.0 is also confirmed, it should be the latest 2.1.15

Did explicitly adding @ant-design/plots to latest version fixed the issue?

**Comment by lxfu1** [comment]
> > 最外层容器加个标识跳过一下，应该和构建脚本有关，
> > 1
> > 。
> 
> 没有理解，能麻烦详细说一下吗

没注意被转换了，`<div>1</div>` 改为 `<div data-type="react">1</div>`

**Comment by lxfu1** [comment]
> > > Check the version of @ant-design/plots to see if it is the latest one
> > 
> > 
> > @ant-design/plots is not installed directly, node_modules/@ant-design/charts/package.json contains "@ant-design/plots": "^2.1.3", and after looking at pnpm-lock.yaml, it is:
> > ```
> >   /@ant-design/charts@2.0.3(lodash-es@4.17.21)(react-dom@18.2.0)(react@18.2.0):
> >     resolution: {integrity: sha512-CDyDRoMLtUcZ6ZU92nmW23Yt9a9KJU3Z/i5RPMasDuBMShTPNY3i/sOQgv5nTho+7FfBMVrdAax+cKAYcAz3jQ==}
> >     peerDependencies:
> >       lodash-es: ^4.17.21
> >       react: '>=16.8.4'
> >       react-dom: '>=16.8.4'
> >     dependencies:
> >       '@ant-design/plots': 2.1.15(lodash-es@4.17.21)(react-dom@18.2.0)(react@18.2.0)
> >       lodash-es: 4.17.21
> >       react: 18.2.0
> >       react-dom: 18.2.0(react@18.2.0)
> >     dev: false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In node_modules/.pnpm/@ant-design+plots@2.1.15_lodash-es@4.17.21_react-dom@18.2.0_react@18.2.0 is also confirmed, it should be the latest 2.1.15
> 
> Did explicitly adding @ant-design/plots to latest version fixed the issue?

Delete pnpm-lock.yaml and reinstall.

**Comment by zhouzhouya1** [comment]
> > > 最外层容器加个标识跳过一下，应该和构建脚本有关，
> > > 1
> > > 。
> > 
> > 
> > 没有理解，能麻烦详细说一下吗
> 
> 没注意被转换了，`<div>1</div>` 改为 `<div data-type="react">1</div>`

大佬 目前除了这种解决方法 还有别的吗，

**Comment by saaadshot** [comment]
> > > The outermost container is marked as skipped, which should be related to the build script, 
> > > 1 
> > > .
> > 
> > 
> > I don't understand, could you explain it in detail?
> 
> I didn't notice it was converted `<div>1</div>`.`<div data-type="react">1</div>`

Could someone explain how this worked exactly

**Comment by caoML** [comment]
> > > 最外层容器加个标识跳过一下，应该和构建脚本有关，
> > > 1
> > > 。
> > 
> > 
> > 没有理解，能麻烦详细说一下吗
> 
> 没注意被转换了，`<div>1</div>` 改为 `<div data-type="react">1</div>`
我这边还是不行，是这种效果
<img width="682" alt="Image" src="https://github.com/user-attachments/assets/2d45bfc7-5d4e-4250-9339-d09a93e4bf3c" />

**Comment by caoML** [comment]
> > > 最外层容器加个标识跳过一下，应该和构建脚本有关，
> > > 1
> > > 。
> > 
> > 
> > 没有理解，能麻烦详细说一下吗
> 
> 没注意被转换了，`<div>1</div>` 改为 `<div data-type="react">1</div>`





我这边还是按照上面的配置不行：

**Comment by caoML** [comment]
> > > 最外层容器加个标识跳过一下，应该和构建脚本有关，
> > > 1
> > > 。
> > 
> > 
> > 没有理解，能麻烦详细说一下吗
> 
> 没注意被转换了，`<div>1</div>` 改为 `<div data-type="react">1</div>`





我这边按上面的配置了还是不行，同时控制台也有报错：

<img width="1131" alt="Image" src="https://github.com/user-attachments/assets/181c7e2a-e52d-4af4-ba92-38ecc07c30fe" />
