### ISSUE TITLE
🧐[问题]双折线图或者双轴图，每一条数据分一个折线图展示怎么实现？

### ISSUE THREAD

**Issue by snowrain0722** [ant-design/ant-design-charts#2488]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
如截图所示，我这里可能不止两条数据，每一条都有历史做对比。有两点我想知道怎么配置去实现：
1.需要每一条指标都要单独一个折线图展示。
2.下方还要有缩略轴同一控制所有的折线图。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![Screenshot_20240407_162050_com.alibaba.android.rimet.aliding.jpg](https://github.com/ant-design/ant-design-charts/assets/48642074/8cf6afcc-c55f-4955-8fb9-c43568ecaaa9)

**Comment by lxfu1** [comment]
https://ant-design-charts.antgroup.com/examples/statistics/dual-axes/#multi-line

**Comment by snowrain0722** [comment]
> https://ant-design-charts.antgroup.com/examples/statistics/dual-axes/#multi-line

这里有哪个API可以分开多张图啊，我这不能多个数据共用一张图吧？

**Comment by snowrain0722** [comment]
> https://ant-design-charts.antgroup.com/examples/statistics/dual-axes/#multi-line

这个多轴图，怎么才能让多个Y轴处于同一水平线上啊，多个折线已经用比例尺分开了。
