### ISSUE TITLE
🧐[问题]ESM packages (lodash-es) need to be imported.

### ISSUE THREAD

**Issue by FallingHeart** [ant-design/ant-design-charts#2489]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Server Error
Error: [31m[1mModule not found[22m[39m: ESM packages (lodash-es) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

Import trace for requested module:
./node_modules/@ant-design/plots/lib/index.js
./node_modules/@ant-design/charts/lib/index.js
./src/components-product/Graph/bar.tsx

在next.config.js中用了experimental.esmExternals: 'loose'之后变成

Server Error
Error: require() of ES Module ./node_modules/d3-array/src/index.js from ./node_modules/@antv/g2/lib/transform/utils/order.js not supported.
Instead change the require of index.js in ./node_modules/@antv/g2/lib/transform/utils/order.js to a dynamic import() which is available in all CommonJS modules.

**Comment by paul-barilla-1** [comment]
Any update on this? It's preventing us migrating to v2

**Comment by cmjacques** [comment]
This is also blocking us from upgrading.

**Comment by MarkLyck** [comment]
Also running into this error when upgrading to v2
