### ISSUE TITLE
🧐[问题]升级2.0版本后启动失败

### ISSUE THREAD

**Issue by lzshenpan** [ant-design/ant-design-charts#2504]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
代码启动时报错，webpack需要特殊配置吗
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
./node_modules/@ant-design/plots/es/index.js
Module parse failed: Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
| export * as G2 from '@antv/g2';
| export * from './components';
| export * from './interface';

**Comment by lxfu1** [comment]
看下 webpack 的 externals 配置，添加 cdn 地址后引入的时候用 const { Line } =  window.Plots，我们近期修复

**Comment by hustcc** [comment]
这种如果上层能解决，就 FAQ 告诉怎么加 webpack 配置解决，如果不行，尽量能做到兼容修改。

```ts
import * as G2 from '';

export { G2 };
```

**Comment by mianxiaoqian** [comment]
![Uploading iwEcAqNwbmcDAQTRCIAF0QPgBrDwylfVfjyw6AZmnL6pDT4AB9IdlrJ3CAAJomltCgAL0gATMBM.png_720x720q90.jpg…]()
2.2.4版本的@ant-design/plots，还没有改完，需要再改动兼容下

**Comment by mianxiaoqian** [comment]
@lxfu1 最新版项目内还有export * as G2 from '@antv/g2';麻烦兼容下

**Comment by lxfu1** [comment]
这个在webpack的loader includes 里面把 plots 加入进去吧，不知道怎么配置的话，提供个在线地址我给你配置，低版本webpack确实有问题。

**Comment by PaulBykov** [comment]
What lxfu1 was talking about, its by adding something like this to your webpack config rules:
```javascript
 {
     test: /\.m?js$/,
     include: [
         resolve(__dirname, "node_modules/@ant-design/plots")
     ],
     use: {
         loader: "babel-loader",
         options: {
             presets: ["@babel/preset-env"],
         },
     },
},
```
