### ISSUE TITLE
🧐[问题] 这个库没有接口文档吗。找了半天没找到

### ISSUE THREAD

**Issue by renny-ren** [ant-design/ant-design-charts#2505]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
没有 API 文档吗，比如我引入了一个组件
`import { Liquid } from '@ant-design/plots'`

这个组件有哪些参数？
[除了这个示例的地方](https://ant-design-charts.antgroup.com/examples/statistics/liquid/#liquid)，还有文档吗

找到官网的链接 404 了，如下图
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
https://antv.antgroup.com/

![image](https://github.com/ant-design/ant-design-charts/assets/19547819/e365d804-52c5-47bf-b519-83980fedbcc8)
![image](https://github.com/ant-design/ant-design-charts/assets/19547819/936ac827-59b7-41de-92e4-b9bb3e186d41)

**Comment by lxfu1** [comment]
确认下版本

![image](https://github.com/ant-design/ant-design-charts/assets/31396322/c55d9bb2-c383-4232-86ab-469b04ea003e)
