### ISSUE TITLE
🐛[BUG] 折线图组件，当鼠标hover在两个数据点中间的线上时，tooltip会将两个数据点的信息都显示出来

### ISSUE THREAD

**Issue by boyulin5697** [ant-design/ant-design-charts#2506]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
我使用了ant design 的时间范围选择器选择时间，选择完之后会刷新数据，刷新数据之后，
当鼠标hover在两个数据点中间的线上时，tooltip会将两个数据点的信息都显示出来
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

使用antd-charts折线图，在刷新数据之后，当鼠标hover在两个数据点中间的线上时，tooltip会将两个数据点的信息都显示出来

### 🏞 期望结果 [描述你原本期望看到的结果]
不会同时出现两个数据点的数据，只会有其中一个
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
组件为Plot,plot折线图配置如下：
```typescript
export const plotConfig = {
  xField: 'time',
  yField: 'value',
  point: {
    shapeField: 'square',
    sizeField: 3,
  },
  colorField: 'value',
  style: {
    gradient: 'y',
    lineWidth: 1.5,
    lineJoin: 'round',
  },
  scale: {
  },
  legend: false,
  tooltip: {
    title: '',
    items: [
      { 
        channel: 'x',
        name: '时间',
        color: 'gray' 
      },
      { 
        channel: 'y',
        name: '数值',
        color: 'blue' 
      },
    ],
  },
  axis: {
    x: {
      label: false,
      tickStroke: 'white'
    },
    y: {
      labelFill: 'white',
      labelFontSize: 15,
    },
  },
  interaction: {
    tooltip: {
      marker: false,
      title: 'category',
    },
  },
     scale:{
           color: { type: 'threshold', domain: [5,15], range: ['red','skyblue','red'] },
      },
  theme: "academy",
};
```

### © 版本信息

- ant-design-charts 版本: 2.0.3
- Google Chrome, Edge, Safari
- 开发环境 MacOS & Windows

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![Uploading 截屏2024-04-18 10.16.34.png…](https://img2.imgtp.com/2024/04/18/5RfYha1V.png)

**Comment by liusHusband** [comment]
你可以把那个point的设置取消掉试试，原因不知道是啥

**Comment by boyulin5697** [comment]
> 你可以把那个point的设置取消掉试试，原因不知道是啥

谢谢大佬，这样确实可以了哈哈，是真的邪门
