### ISSUE TITLE
🧐[问题] Preselect Pie chart slice on initial render

### ISSUE THREAD

**Issue by aliaksandr-sakalou-sonatus** [ant-design/ant-design-charts#2509]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Antd pie chart support element selection via user interaction. That's ok when we expect interaction from the user.
in our case we use Pie chart slice selection in order to apply filter to the associated table and there is case where we need to have some filter by default so we should have a slice to be preselected when chart is rendered.

We are still on version 1.4 and I've prepared an example trying to implement this but with no luck using `emit`.

Please let me know if that's possible to preselect the slice of the Pie chart when data loaded.

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
Link to play: https://stackblitz.com/edit/react-7cvkpz?file=index.js

https://github.com/ant-design/ant-design-charts/assets/141123711/ee3208c8-9f94-476d-9896-6c13f3d9c626

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
In the stackblitz example you can find select button where I am emitting element:select event but selection doesn't happen.

**Comment by lxfu1** [comment]
`emit('xx')` and `on('xx')`  are used in combination, like this

```ts
chartRef.current.getChart().chart.getElements()[0].clearStates()
```

**Comment by aliaksandr-sakalou-sonatus** [comment]
@lxfu1 Thanks for you comment but how does it work with selection? I tried in stackblitz and this didn't work.
Could you please let me know what is wrong?

Thanks.
