### ISSUE TITLE
🐛[BUG] 在手机上不能滑动图表

### ISSUE THREAD

**Issue by gkendiy** [ant-design/ant-design-charts#2520]
请问是设计原因吗？f2可以滑动的，这个即便是官网上的例子，也不能在触碰图表的时候，滑动屏幕

**Comment by lxfu1** [comment]
移动端推荐使用f2哈，目前移动端没有做过测试。

**Comment by gkendiy** [comment]
> 移动端推荐使用f2哈，目前移动端没有做过测试。

f2的时间刻度显示没这个灵活，这个能自动调节显示小时，还是日期，还是月份。可以尝试支持下不?其他图表highcharts，echart都没这个问题

**Comment by hustcc** [comment]
在图表上也能滑动外面的滚动条吗？感觉是底层事件默认 prevent了
