### ISSUE TITLE
使用line折线图使，config配置没效果🧐[问题]

### ISSUE THREAD

**Issue by PKLNB** [ant-design/ant-design-charts#2523]
const config: any = {
    title: {
      visible: true,
      text: '多折线图',
    },
    description: {
      visible: true,
      text: '通过回调函数指定折线颜色',
    },
    padding: 'auto',
    forceFit: true,
    data,
    xField: 'date',
    yField: 'value',
    yAxis: { label: { formatter: (v) => `${v}`.replace(/\d{1,3}(?=(\d{3})+$)/g, (s) => `${s},`) } },
    legend: { position: 'right-top' },
    seriesField: 'type',
    color: (d) => {
      return d === 'register' ? '#93D072' : '#2D71E7';
    },
    responsive: true,
  };
  return <Line {...config} />;
};
除了data,xField,yField之外,其他属性都没在图形上显示。
图形显示:
![QNRINHEC4%W$0`I(2X2VAQX](https://github.com/ant-design/ant-design-charts/assets/95152962/805c2196-0985-437e-a86d-53f80aa26fda)

**Comment by one-rain** [comment]
我按照 https://v0-charts.ant.design/demos/line#line-2 中的案例，没有出现期望的效果，样式丢失。
![Uploading 微信图片_20240430141725.png…]()

**Comment by lxfu1** [comment]
你核对一下安装的版本，你可能安装了2.X版本，附上版本信息后再打开哈
