### ISSUE TITLE
🐛[BUG] 多折线图设置 point属性后，鼠标在接近指示线时， tooltip会显示多余的数据

### ISSUE THREAD

**Issue by DrMuda** [ant-design/ant-design-charts#2527]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在显示多条折线时， 一般情况下，假设数据为 { year: 2020, value: 1, type: "GMV"|"销售数据"|"订单数" } (三条折线) ， tooltip会显示 纵轴数据 (year:2020) 和 三个纵轴数据(GMV: 1， 销售数据： 1， 订单数：1)。 然而当鼠标靠近指示线时， 还会额外显示三行 value: 1,  year：2020

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
直接看复现代码就行

### 🏞 期望结果 [描述你原本期望看到的结果]
不应显示额外的三行 value: 1， year：2020

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
[test-antd-line-chart](https://codesandbox.io/p/sandbox/test-antd-line-chart-842lxc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvm032qp00063p6kxdtqmvcq%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvm032qp00023p6ky2czmvx0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvm032qp00033p6k8oh8upxw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvm032qp00053p6kxtyxr63t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvm032qp00023p6ky2czmvx0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvm032qo00013p6kuz7x6cbc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clvm032qp00023p6ky2czmvx0%2522%252C%2522activeTabId%2522%253A%2522clvm032qo00013p6kuz7x6cbc%2522%257D%252C%2522clvm032qp00053p6kxtyxr63t%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvm032qp00043p6k68v9zspm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvm032qp00053p6kxtyxr63t%2522%252C%2522activeTabId%2522%253A%2522clvm032qp00043p6k68v9zspm%2522%257D%252C%2522clvm032qp00033p6k8oh8upxw%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvm032qp00033p6k8oh8upxw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### © 版本信息

- ant-design-charts 版本: [2.2.1]
- 浏览器环境 goolgle chorme 124.0.6367.92
- 开发环境 [mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
不知道是不是我的用法有问题， 如果有， 希望能指出， 我在文档中没找到除了自定义tooltip的其他解决方法， 但我觉得这种情况不太应该需要用自定义tooltip处理
<img width="805" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/73845204/a5e5a387-af8a-4346-8036-e36cbd9029a4">

**Comment by huyinghuan** [comment]
我也遇到了

**Comment by huyinghuan** [comment]
建议使用 DualAxes 组件来完成。我使用该组件完成了同样的功能。 根据文档 https://g2.antv.antgroup.com/manual/core/mark， 这个点也是由数据合成的。
下面是我的完成此项的一个配置：仅供参考

```
const config: DualAxesConfig = {

    xField: 'year',
    children: [{
        type: "line",
        data: [{year:"2020",value: 100, type:"a"}, {year:"2021",value: 200, type:"b"}],
        yField: 'value',

        colorField: 'type',
        seriesField: 'type',
        tooltip: {
            title: 'year',
        },
    }, {
        type: "point",
        data: allData,
        yField: 'value',
        colorField: 'type',
        shapeField: 'square',
        sizeField: 3,
        axis: { y: false },
        tooltip: false,
    }
    ]
}

<DualAxes {...config} />
```

**Comment by huyinghuan** [comment]
更正一次，根据摸索，可以把折线图当成一种简化的复合图表，上面只有一种 `type=line`的图表， 当你设置了`point` 可以看做再这个图表上在画了一个 `type=point`的图表，这个时候,鼠标移到 point上时就会显示  line和point两个的数据，因为可以point也是一个图表，所以它也有一个 tooltip 属性， 把这个tooltip属性设置为false即可。 吐槽一下，antd charts的文档是真的不详细 好多配置想没有明说，包括设置point的shapeField 都没在文档中搜索到


```
{
  ....,
  point: {
      xxxx:xxxx,
      tooltip: false
 }
}
```

**Comment by DrMuda** [comment]
> 更正一次，根据摸索，可以把折线图当成一种简化的复合图表，上面只有一种 `type=line`的图表， 当你设置了`point` 可以看做再这个图表上在画了一个 `type=point`的图表，这个时候,鼠标移到 point上时就会显示 line和point两个的数据，因为可以point也是一个图表，所以它也有一个 tooltip 属性， 把这个tooltip属性设置为false即可。 吐槽一下，antd charts的文档是真的不详细 好多配置想没有明说，包括设置point的shapeField 都没在文档中搜索到
> 
> ```
> {
>   ....,
>   point: {
>       xxxx:xxxx,
>       tooltip: false
>  }
> }
> ```

确实设置tooltip 为 false 就可以了， 文档关于point属性的就只有一行无关痛痒的说明， 大概需要找更底层的 G2 文档
