### ISSUE TITLE
customContent not works in legends

### ISSUE THREAD

**Issue by mohammad-hm** [ant-design/ant-design-charts#2528]
Hi
while, customContent works for tooltip like this:
 tooltip: {
            customContent(title, data) {
                return (
                    <div style={{ padding: 10 }}>
                        <Typography.Text style={{ display: 'block' }}>{title}</Typography.Text>
                        {data.map((item) => {
                            return (
                                <Typography.Text key={item.name}>
                                    {props.chart?.chartName} : {item.value}
                                </Typography.Text>
                            );
                        })}
                    </div>
                );
            },
        },
and also in ant d document, write that in legend we can use it too, with this example:
customContent (title: string, items: ILegendListItem[]) {
  const container = document.createElement('div');
  container.innerHTML = '内容'
  return container;
}
but it does not work at all!!!

**Comment by lxfu1** [comment]
Check the version，https://ant-design-charts-next.antgroup.com/examples/statistics/column/#tooltip
