### ISSUE TITLE
How to change color text and remove border in Treemap?

### ISSUE THREAD

**Issue by vuadenthuj1** [ant-design/ant-design-charts#2529]
![Screen Shot 2024-05-06 at 10 35 45](https://github.com/ant-design/ant-design-charts/assets/29425356/281b3654-8afd-42c0-9288-2af82dfabe57)

I want to change the text color from black to white and remove the white border between cells in the treemap. What should I do?

**Comment by lxfu1** [comment]
```ts
 style: {
      stroke: 'transparent',
      labelFill: () => 'red' // 'red'
    },
```
