### ISSUE TITLE
🐛[BUG] 图表在缩放状态下，导致鼠标位置偏移

### ISSUE THREAD

**Issue by LazyJoke** [ant-design/ant-design-charts#253]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

给图表组件父级节点添加 transform: scale(0.5) 样式，会导致鼠标在图表中的位置偏移，不能准确触发 hover 效果

### 🏞 期望结果 [描述你原本期望看到的结果]

缩放后鼠标在图表内的位置应该能准确触发原本的 hover 效果

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
今晚会发个版本。

**Comment by lxfu1** [comment]
删除 package-lock.json 重新 install，增加配置 supportCSSTransform: true

**Comment by LazyJoke** [comment]
非常感谢🙏，升级后问题已经解决
