### ISSUE TITLE
🧐[问题] 折线图Line上下顶部被遮挡显示不全

### ISSUE THREAD

**Issue by xzajyjs** [ant-design/ant-design-charts#2535]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Line图表折线上下顶部有一小部分显示不全

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```js
import { Line } from '@ant-design/plots';
import {useEffect, useState} from "react";

const simpleAxis = {
    line: false,
    title: false,
    tick: false,
    label: false,
    grid: false
}

function Qps({data}){
    const config = {
        data: data,
        xField: 'time',
        yField: 'count',
        interaction: {
            tooltip: {
                marker: false,
            },
        },
        animate: { enter: { type: 'growInX' } },
        style: {
            lineWidth: 2,
        },
        height: 84,
        margin: 0,
        axis: {
            x: simpleAxis,
            y: simpleAxis
        },
        title: "实时流量",
        shapeField: 'smooth'
    };
    return(
      <Line {...config}/>
    )
}
export default Qps
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="545" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/25580455/919014a3-412e-43ac-831c-f0d8d0b791b9">

**Comment by lxfu1** [comment]
paddingTop: 10

**Comment by xzajyjs** [comment]
去掉margin
<img width="556" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/25580455/d0a92dcd-8738-464f-83f7-3e3838a306ff">

---

添加padding: 10（title也不显示了）
<img width="547" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/25580455/89bbe074-77dd-49be-8515-8fcbc8200cdf">

**Comment by hustcc** [comment]
应该是看这个，就知道 margin、padding、inset 都是什么含义了。https://g2.antv.antgroup.com/examples/style/theme/#layout-area

**Comment by xzajyjs** [comment]
> 应该是看这个，就知道 margin、padding、inset 都是什么含义了。https://g2.antv.antgroup.com/examples/style/theme/#layout-area

这些都尝试过了，还是不行。并且它没有到坐标轴的上下边界就显示不了了  
<img width="1147" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/25580455/e8115286-d01b-4c3a-9116-de6341d730d9">

**Comment by xzajyjs** [comment]
https://codesandbox.io/p/sandbox/stoic-dirac-qj74zx?file=%2Fsrc%2Findex.js&from-embed=

**Comment by xzajyjs** [comment]
请问有解决方案了吗 @lxfu1

**Comment by lxfu1** [comment]
> 请问有解决方案了吗 @lxfu1

上面回复的链接里面已经有答案了，`inset: 20`

**Comment by xzajyjs** [comment]
> > 请问有解决方案了吗 @lxfu1
> 
> 上面回复的链接里面已经有答案了，`inset: 20`

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/588c3bd7-cd43-4294-b4a5-12481fec9250">
<img width="1118" alt="image" src="https://github.com/user-attachments/assets/3dee87f6-eb12-4ad6-a3e2-202a55157d76">
您自己测试一下看看，我多种设备和浏览器全都测试过了，排除了浏览器的问题

**Comment by lxfu1** [comment]
先关闭一下animate吧，animate的bug!

**Comment by xzajyjs** [comment]
感谢
