### ISSUE TITLE
🧐[问题]Liquid水波图中间的例如  35% 鼠标焦点时 显示的 x 50% y 50%  可以修改 或是 删除吗 如图

### ISSUE THREAD

**Issue by Yishueitian** [ant-design/ant-design-charts#2537]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![新建 BMP 图像](https://github.com/ant-design/ant-design-charts/assets/139477773/558d309e-4fd8-47ee-9b31-9d6c7427e91b)

**Comment by Yishueitian** [comment]
版本信息 "@ant-design/charts": "^2.1.1",

**Comment by Yishueitian** [comment]
https://github.com/ant-design/ant-design-charts/issues/2507 参照这个居然解决了。
thanks

附上源码：
  const config = {
    percent: 0.35,
    interaction:{
      Tooltip:{
        marker:false,
      }
    }
  };
  return <Liquid {...config} />;

**Comment by izuoslalala** [comment]
![interaction](https://github.com/ant-design/ant-design-charts/assets/36066040/f0a24cd9-36f8-4484-b24e-4c8be093bed9)
我也是这个问题，但是这个方法好像是因为识别不了interaction.Tooltip所以才不显示，要是这个弹窗能配置就好了

**Comment by Yishueitian** [comment]
研究了一上午  完美解决
代码：
    interaction: {
      tooltip: {
        filter: (item) => item.value > 1,
        position: "right",
      },
    },
    tooltip: {
      title: "",
      items: [
        { name: "ALL：", channel: "y", color: "red", valueFormatter: () => valueAll },
        { name: "A：", channel: "y", color: "green", valueFormatter: () => valueA },
      ],
    },
