### ISSUE TITLE
🧐[问题] Can we get the Graph component from `g6`?

### ISSUE THREAD

**Issue by maifeeulasad** [ant-design/ant-design-charts#2541]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

`g6` has a graph component to render graphs. But as far as I know `ant-design-charts` has no wrapper for react. Can we get it?

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

```
const graph = new G6.Graph({
  container: 'mountNode',
  width: 1000,
  height: 600,
  layout: {
    type: 'random',
    width: 300,
    height: 300,
  },
});
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

ref: https://g6-v3-2.antv.vision/en/docs/api/layout/Graph

**Comment by lxfu1** [comment]
V2 is not supported.

**Comment by maifeeulasad** [comment]
@lxfu1 any idea when it is going to be supported? Any plan for that?
