### ISSUE TITLE
🐛[BUG]堆叠面积图展示好像有问题，y轴对应不上

### ISSUE THREAD

**Issue by luzeao** [ant-design/ant-design-charts#2543]
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
数据没问题，所有的value都是number类型，但是他们的数据差异明明很大，数据却在一起，好像在在原有的基础上加上了另一个数据

### 🏞 期望结果 [描述你原本期望看到的结果]
正确展示数据
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![1715827773120](https://github.com/ant-design/ant-design-charts/assets/128207865/139dca71-76e3-4bba-98ac-96d0a3397a9f)
![1715827831878](https://github.com/ant-design/ant-design-charts/assets/128207865/fee35bde-c8b1-4f69-94ee-0d5138a3b999)
![1715827873672](https://github.com/ant-design/ant-design-charts/assets/128207865/4aff67da-2282-49d6-9298-b63bc091aa88)
![1715826927934](https://github.com/ant-design/ant-design-charts/assets/128207865/9244be04-a21e-4814-8d37-01561c8eb176)

**Comment by lxfu1** [comment]
stack: false

**Comment by lxfu1** [comment]
堆叠就是在之前的基础上叠加
