### ISSUE TITLE
Pie 如何设置百分百呢？ 🧐[问题]

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-charts#2546]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我看了文档 没看见有设置百分比的呢
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
[我开了G2的 g2plot版本 是通过content: '{name}\n{percentage}', ](https://g2plot.antv.antgroup.com/examples/pie/basic/#spider-label
)

**Comment by lxfu1** [comment]
```ts
    label: {
      formatter: (arg)=>{
        return xx
      }
    },
```
