### ISSUE TITLE
🧐[问题] 模块“"@ant-design/charts"”没有导出的成员“DualLine”。

### ISSUE THREAD

**Issue by taofeifanIT** [ant-design/ant-design-charts#2550]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
模块“"@ant-design/charts"”没有导出的成员“DualLine”。
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
我更新成最新的2.1.1的版本还有没有DualLine
![image](https://github.com/ant-design/ant-design-charts/assets/42193371/fe7ae60d-aba2-41ac-8bec-865771ad640e)
![image](https://github.com/ant-design/ant-design-charts/assets/42193371/c091310a-f163-4caa-9b79-719748b4c1d6)

**Comment by lxfu1** [comment]
版本不对，官网右上角可以查看相关版本配置
