### ISSUE TITLE
🐛[BUG]条形图在数据量过多时label会自动计算隐藏部分 我想全部显示

### ISSUE THREAD

**Issue by HenryLee951020** [ant-design/ant-design-charts#2554]
### 🐛 bug 描述

![image](https://github.com/ant-design/ant-design-charts/assets/169737025/72d32eee-6c01-4dc7-920c-5f29861fbaa8)

### © 版本信息

- ant-design-charts 版本:  "@ant-design/plots": "^2.2.2",
- 浏览器环境: google
- 开发环境 window

**Comment by HenryLee951020** [comment]
https://codesandbox.io/p/sandbox/white-grass-pxdj46?file=%2Findex.js

**Comment by lxfu1** [comment]
```ts
    axis: {
      x: {
        size: 30,
        labelAutoHide: false
      }
    }
```

**Comment by HenryLee951020** [comment]
> ```ts
>     axis: {
>       x: {
>         size: 30,
>         labelAutoHide: false
>       }
>     }
> ```

![image](https://github.com/ant-design/ant-design-charts/assets/169737025/52d53a97-9571-487e-8fa5-90c92b2957a2)
 并没有生效
