### ISSUE TITLE
🧐[问题]请问坐标的刻度值怎么进行换行显示啊？

### ISSUE THREAD

**Issue by xian107** [ant-design/ant-design-charts#2556]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
设置labelAutoWrap: true,无效

![image](https://github.com/ant-design/ant-design-charts/assets/13252682/e195098d-e25d-4ce0-802b-ecca9fcb6f0c)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
`
import { Column } from '@ant-design/charts';
const config: any = {
	group: true,
	xField: 'user',
	yField: 'value',
	seriesField: 'seriesField',
	colorField: 'seriesField',
	style: { inset: 1 },
	slider: {
		x: {
			values: [0, 1],
		},
	},
	axis: {
		x: {
			size: 30,
			labelFontSize: 10,
			labelAutoRotate: false,
			labelAutoWrap: true,
		},
	},
}
<Column {...config} data={barData} />
`

**Comment by lxfu1** [comment]
labelFormatter: (x) => `xx\\nxx`

**Comment by xian107** [comment]
> labelFormatter: (x) => `xx\\nxx`

@lxfu1  不起作用，并没有换行
![image](https://github.com/ant-design/ant-design-charts/assets/13252682/1f7fb19f-9477-42a6-aded-ae3a3bb3ae92)

`const config: any = {
	group: true,
	xField: 'user',
	yField: 'value',
	seriesField: 'seriesField',
	colorField: 'seriesField',
	style: { inset: 1 },
	slider: {
		x: {
			values: [0, 1],
		},
	},
	axis: {
		x: {
			size: 60,
			labelFontSize: 10,
			labelAutoRotate: false,
			labelAutoWrap: true,
			//labelAutoEllipsis: 'true',
			labelFormatter: v => {
				console.log(
					'ggggggggggggggggggggggggg',
					v.replace('(', '\\n(')
				);
				return v.replace('(', '\n(');
			},
		},
	},
}`
