### ISSUE TITLE
🧐[问题] @ant-design/charts v2版本如何实现v1的条件样式折线图

### ISSUE THREAD

**Issue by sp4rkw** [ant-design/ant-design-charts#2557]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

@ant-design/charts v2版本如何实现

https://ant-design-charts-v1.antgroup.com/examples/line/basic/#line-annotation

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
无
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
无

**Comment by lxfu1** [comment]
[threshold](https://ant-design-charts-next.antgroup.com/zh/examples/statistics/line/#line-threshold) + [annotations](https://ant-design-charts-next.antgroup.com/options/plots/overview)

**Comment by sp4rkw** [comment]
不是，大佬，能给个demo么？像v1版本那样开箱即用？

**Comment by sp4rkw** [comment]
@lxfu1

**Comment by sp4rkw** [comment]
补充给其他需要的小伙伴，直接用antv/g2plot库

demo例子：
`const LineChart = ({}) => {
    useEffect(() => {
        const line = new Line('container', {
            data:[
                {
                    "log_day": "03/28",
                    "total": 16
                },
                {
                    "log_day": "03/29",
                    "total": 70
                },
                {
                    "log_day": "03/30",
                    "total": 50
                },
                {
                    "log_day": "03/31",
                    "total": 75
                },
                {
                    "log_day": "04/01",
                    "total": 207
                },
                {
                    "log_day": "04/02",
                    "total": 198
                },
                {
                    "log_day": "04/03",
                    "total": 109
                },
                {
                    "log_day": "04/04",
                    "total": 122
                },
                {
                    "log_day": "04/05",
                    "total": 178
                },
                {
                    "log_day": "04/06",
                    "total": 90
                },
                {
                    "log_day": "04/07",
                    "total": 102
                },
                {
                    "log_day": "04/08",
                    "total": 109
                },
                {
                    "log_day": "04/09",
                    "total": 114
                },
                {
                    "log_day": "04/10",
                    "total": 637
                },
                {
                    "log_day": "04/11",
                    "total": 2263
                },
                {
                    "log_day": "04/12",
                    "total": 78
                }
            ],
            padding: 'auto',
            xField: 'log_day',
            yField: 'total',
            annotations: [
                {
                    type: 'regionFilter',
                    start: ['min', 'median'],
                    end: ['max', '0'],
                    color: '#F4664A',
                },
                {
                    type: 'text',
                    position: ['min', 'median'],
                    content: '中位数',
                    offsetY: -4,
                    style: {
                        textBaseline: 'bottom',
                    },
                },
                {
                    type: 'line',
                    start: ['min', 'median'],
                    end: ['max', 'median'],
                    style: {
                        stroke: '#F4664A',
                        lineDash: [2, 2],
                    },
                },
            ],
        });

        line.render();

        // 清理函数，在组件卸载时销毁图表实例
        return () => {
            line.destroy();
        };
    }, []); // 当 data 发生变化时，重新渲染图表

    return <div id="container"></div>;
};`
