### ISSUE TITLE
🐛[BUG]upgrage to v.1.0.1 chart height get lost

### ISSUE THREAD

**Issue by moale** [ant-design/ant-design-charts#256]
Hi!
### 🐛 bug  
after upgrade from v0.9.13 to v1.0.1 the chart are not longer visible,  below the HTML result 
```HTML
<div style="position:relative;"><canvas width="746" height="20" style="width: 746px; height: 20px; display: inline-block; vertical-align: middle;"></canvas></div>
```

### 📷
upgrade to v1.0.1

macOS: 10.15.7
chrome: 86.0.4240.80
ant-design-charts: v1.0.1

**Comment by lxfu1** [comment]
Which chart ?  reference https://charts.ant.design/guide/upgrade .

**Comment by moale** [comment]
rigth now i use these charts: Area, Pie, Radar, Line.
I also try to open an example on codesandbox and i get the same result

**Comment by lxfu1** [comment]
Set height config or add height to the parent container.
```ts
height: 500
```
