### ISSUE TITLE
🧐[问题]ant-design-charts 2.0.0 版本自定义tootip，tootip中的按钮可以点击

### ISSUE THREAD

**Issue by ChenKRicardo** [ant-design/ant-design-charts#2560]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
自定义tootip，tootip中的按钮可以点击现在每次想移入tootip，都会立马消失偏移到下一个坐标
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
interaction: {
      tooltip: {
        render: (
          _e: any,
          { title, items }: { title: string; items: any[] },
        ) => {
   return <button> </button>
  }
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/ant-design/ant-design-charts/assets/96281398/97f81f6d-04f1-4583-a89d-eb21454b5cda)

**Comment by pearmini** [comment]
closed by: https://github.com/antvis/G2/pull/6296
