### ISSUE TITLE
🧐[问题]柱形图该如何设置每个Bar之间的间隔

### ISSUE THREAD

**Issue by initiali** [ant-design/ant-design-charts#2565]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
柱形图该如何设置每个Bar之间的间隔，我按如下代码设置后 每个bar会堆叠到一起，我希望的效果是能够在400px*400px容器的范围内显示8个bar 如果超过8个则这个容器内部可使用鼠标滚轮上下查看数据。
另外我想实现能过点击bar来实现选中数据并高亮，支持多选，目前没有看到相关的示例，还望大佬解答。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```
const config = {
    width: 400,
    height: 400,
    data: {
      type: 'fetch',
      value: 'https://render.alipay.com/p/yuyan/180020010001215413/antd-charts/bar-bar.json',
    },
    style: {height: 20},
    scrollBar: {
      x: {
        ratio: 7 / 24,
        slidable: true,
        scrollable: true
      }
    },
    xField: 'letter',
    yField: 'frequency',
    sort: {
      reverse: true,
      by: 'y',
    },
    label: {
      text: 'frequency',
      formatter: '.1%',
    },
    axis: {
      y: {
        labelFormatter: '.0%',
      },
    },
  };

<Bar {...config} />
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
现在的情况
![image](https://github.com/ant-design/ant-design-charts/assets/31793204/d753cdb7-5288-495b-904a-9894f005487e)

想要达到的效果
![image](https://github.com/ant-design/ant-design-charts/assets/31793204/c9212181-8298-4396-a73d-9f27b12cf3f8)

**Comment by lxfu1** [comment]
```ts
    scrollbar: {
      x: {}
    },
    interaction: {
      elementSelect: true,
      elementHighlightByColor: false
    },
    state: {
      selected: {
        fill: 'red'
      },
      unselected: {
        opacity: 0.5
      }
    },
```

**Comment by initiali** [comment]
@lxfu1  感谢回答，在补充您贴出的代码块之后，已经实现大部分效果，但是鼠标滚轮无法滚动该图表。我使用的浏览器版本为MS EDGE 126.0.2592.87
