### ISSUE TITLE
🐛[BUG]首次渲染无法自适应容器高度

### ISSUE THREAD

**Issue by ianzone** [ant-design/ant-design-charts#2568]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
每次刷新页面的时候图表都没有自适应容器高度。
<img width="1162" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/20043230/a4e5ee12-8762-4123-85d4-4c5f0fbfb33f">

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
将图表用antd Card 组件包裹，不设图表的高度。然后刷新页面。

### 🏞 期望结果 [描述你原本期望看到的结果]
图表大小自适应容器大小

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0] 2.1.1
- 浏览器环境 Edge
- 开发环境 [e.g. mac OS] WSL

**Comment by hsp-sz** [comment]
adc层面好像暂时无法解决，你可以看下你重新缩放浏览器后这个图表会重新触发一次，用ahooks的 useSize，监听外层容器宽度/高度，再给config重新设置width/height。

**Comment by ianzone** [comment]
2.1.2 没有包含这个修复？
