### ISSUE TITLE
🐛[BUG] "@ant-design/charts-util@workspace:*" is in the dependencies but no package named "@ant-design/charts-util" is present in the workspace

### ISSUE THREAD

**Issue by duonghkhanh** [ant-design/ant-design-charts#2570]
ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@ant-design/charts-util@workspace:*" is in the dependencies but no package named "@ant-design/charts-util" is present in the workspace

This error happened while installing the dependencies of @ant-design/charts@2.1.1
 at @ant-design/plots@2.2.3
 
 
 << This issue happen after @ant-design/plots pump to version 2.2.3 this afternoon

**Comment by lxfu1** [comment]
`@ant-design/plots@2.2.4` fixed it!
