### ISSUE TITLE
🐛[BUG]@ant-design/plots， v1.2.5升级到最新版后报错

### ISSUE THREAD

**Issue by LegendarySSS** [ant-design/ant-design-charts#2572]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境 Chrome 125.0.6422.142
- 开发环境 mac OS

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="671" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/93976312/a3993d7b-9f4e-479b-b772-bfbe33f90f3e">

**Comment by lxfu1** [comment]
看下[新官网](https://ant-design-charts.antgroup.com/)噢，V2和V1是不兼容的。

**Comment by LegendarySSS** [comment]
> 看下[新官网](https://ant-design-charts.antgroup.com/)噢，V2和V1是不兼容的。

看的就是这个官网，引入方式是这样的
<img width="774" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/93976312/b8dc9681-ee23-4f1b-8bfd-2bb42d4bfffa">

**Comment by lxfu1** [comment]
能提供个在线复现吗？

**Comment by LegendarySSS** [comment]
> 能提供个在线复现吗？
好的稍等。

**Comment by LegendarySSS** [comment]
> 能提供个在线复现吗？

https://codesandbox.io/p/sandbox/practical-leakey-9yyggk?file=%2Fsrc%2FApp.js%3A163%2C9

**Comment by LegendarySSS** [comment]
> 无效地址
设为公开了
https://codesandbox.io/p/sandbox/practical-leakey-9yyggk?file=%2Fsrc%2FApp.js%3A163%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvupnneu00063b6jb90ofoo3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvupnneu00023b6j7zkxev5w%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvupnneu00033b6j3xkqn0yk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvupnneu00053b6jwakrm7lu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvupnneu00023b6j7zkxev5w%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvupnnet00013b6jn4tgshho%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvxgukjf00633b6jd4ciqtey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A163%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A163%252C%2522endColumn%2522%253A9%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvupnneu00023b6j7zkxev5w%2522%252C%2522activeTabId%2522%253A%2522clvxgukjf00633b6jd4ciqtey%2522%257D%252C%2522clvupnneu00053b6jwakrm7lu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvupnneu00043b6jcfvw6pro%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvupnneu00053b6jwakrm7lu%2522%252C%2522activeTabId%2522%253A%2522clvupnneu00043b6jcfvw6pro%2522%257D%252C%2522clvupnneu00033b6j3xkqn0yk%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvupnneu00033b6j3xkqn0yk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
