### ISSUE TITLE
🧐[问题] V2.2.1 y轴坐标的标题怎么设置？

### ISSUE THREAD

**Issue by CodeMak1r-zy** [ant-design/ant-design-charts#2573]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

<img width="265" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/90091332/068fa359-8b43-472a-99cb-e2d18dc6a721">
axis: {
      y: {
        labelFill: '#8C9ECB',
        tickStroke: 'transparent',
        grid: true,
        gridLineWidth: 1,
        gridStroke: '#8C9ECB',
        gridLineDash: [0, 0],
        title: {
          text: '（数量）',
          style: {
            fill: '#8C9ECB',
          },
        },
      }
这个无效

**Comment by lxfu1** [comment]
```ts
    paddingTop: 40,
    axis: {
      y: {
        title: 'Y轴标题',
        titlePosition: 'top'
      }
    },
```
