### ISSUE TITLE
🐛[BUG]来源去向图更新数据后fitCenter无效

### ISSUE THREAD

**Issue by nakyooo** [ant-design/ant-design-charts#2574]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
设置 fitCenter: true后，会使来源去向图居中。对于初始数据是有效的。
但我们需要对数据进行一些筛选，后重新查看剩下节点的来源去向图。
此时更新数据就会导致fitCenter无效，并不居中。
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
用一个简单场景复现，两个按钮，点击切换数据，点击后不居中，再多一点次才能居中。
### 🏞 期望结果 [描述你原本期望看到的结果]
设置 fitCenter: true后，切换数据前后来源去向图都居中。
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
import React,{useState} from 'react';
import ReactDOM from 'react-dom';
import { FlowAnalysisGraph } from '@ant-design/graphs';

const DemoFlowAnalysisGraph = () => {
  
  const data1 = {
    nodes: [
      {
        id: "1",
        value: {
          title: "去向页面A",
          items: [
            {
              text: "访问页面UV"
            }
          ]
        }
      },
    ],
    edges: []
  };
  const data2 = {
    nodes: [
      {
        id: '-3',
        value: {
          title: '来源页面A',
          items: [
            {
              text: '曝光PV',
              value: '10.30万',
              icon: 'https://gw.alipayobjects.com/zos/antfincdn/iFh9X011qd/7797962c-04b6-4d67-9143-e9d05f9778bf.png',
            },
          ],
        },
      },
      {
        id: '-2',
        value: {
          title: '来源页面B',
          items: [
            {
              text: '点击UV',
              value: '10.30万',
              icon: 'https://gw.alipayobjects.com/zos/antfincdn/iFh9X011qd/7797962c-04b6-4d67-9143-e9d05f9778bf.png',
            },
          ],
        },
      },
      {
        id: '-1',
        value: {
          title: '来源页面C',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
      {
        id: '0',
        value: {
          title: '活动页面',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
      {
        id: '1',
        value: {
          title: '去向页面A',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
      {
        id: '2',
        value: {
          title: '去向页面B',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
      {
        id: '3',
        value: {
          title: '去向页面C',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
      {
        id: '4',
        value: {
          title: '去向页面D',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
      {
        id: '5',
        value: {
          title: '去向页面E',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
      {
        id: '6',
        value: {
          title: '去向页面F',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
      {
        id: '6',
        value: {
          title: '去向页面F',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
      {
        id: '7',
        value: {
          title: '去向页面G',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
      {
        id: '8',
        value: {
          title: '去向页面H',
          items: [
            {
              text: '访问页面UV',
            },
          ],
        },
      },
    ],
    edges: [
     ]
  };
  const [data,setData]=useState(data1);
  const buttonClick1=()=>{
      setData(data1);
  }
  const buttonClick2=()=>{
      setData(data2);
  }
  const config = {
    data:data,
    autoFit:false,
    animate: false, //关闭动画
    height: 500,
    layout: {
      type: 'grid',
      cols: 3,
      begin:[0,0],
      preventOverlap: false, // 防止节点重叠，如果空间不足，可能会溢出边界框
      preventOverlapPadding: 10, // preventOverlap: true 时节点周围的额外间距
      ranksepFunc: () => 30,
      nodesepFunc: () => 40,
      //fitCenter: true,
    },
    fitCenter: true,
    nodeCfg: {
      size: [140, 25],
      badge: {
        style: (cfg) => {
          const ids = ['-3', '-2', '-1'];
          const fill = ids.includes(cfg.id) ? '#c86bdd' : '#5ae859';
          return {
            fill,
            radius: [2, 0, 0, 2],
          };
        },
      },
      items: {
        padding: 6,
        containerStyle: {
          fill: '#fff',
        },
        style: (cfg, group, type) => {
          const styles = {
            icon: {
              width: 12,
              height: 12,
            },
            value: {
              fill: '#f00',
            },
            text: {
              fill: '#aaa',
            },
          };
          return styles[type];
        },
      },
      nodeStateStyles: {
        hover: {
          stroke: '#1890ff',
          lineWidth: 2,
        },
      },
      title: {
        containerStyle: {
          fill: 'transparent',
        },
        style: {
          fill: '#000',
          fontSize: 12,
        },
      },
      style: {
        fill: '#E6EAF1',
        stroke: '#B2BED5',
        radius: [2, 2, 2, 2],
      },
    },
    edgeCfg: {
      label: {
        style: {
          fill: '#aaa',
          fontSize: 12,
          fillOpacity: 1,
        },
      },
      style: (edge) => {
        const stroke = edge.target === '0' ? '#c86bdd' : '#5ae859';
        return {
          stroke,
          lineWidth: 1,
          strokeOpacity: 0.5,
        };
      },
      edgeStateStyles: {
        hover: {
          lineWidth: 2,
          strokeOpacity: 1,
        },
      },
    },
    behaviors: ['drag-canvas', 'zoom-canvas', 'drag-node'],
  };

  return <>
  <button onClick={buttonClick1}>1</button>
  <button onClick={buttonClick2}>2</button>
  <FlowAnalysisGraph {...config} />
  </>;
};

ReactDOM.render(<DemoFlowAnalysisGraph />, document.getElementById('container'));

希望给出解答和解决办法，感谢

### © 版本信息

- ant-design-charts 版本: 1.2.7
- 浏览器环境 Chrome
- 开发环境 mac

**Comment by lxfu1** [comment]
先手动调用 fitCenter跳过一下
```ts
onReady: (graph) => {
  graphRef = graph;
}

// When needed
graphRef.fitCenter()
```

**Comment by nakyooo** [comment]
graphRef.fitCenter is not a function.
是我哪里写的有问题嘛
https://codesandbox.io/s/condescending-frog-w8qtlp?file=/App.tsx

**Comment by lxfu1** [comment]
你提供的链接打开空白，打印grapRef 看看，记得结合 React.useRef() 使用
