### ISSUE TITLE
🧐[问题] 文档是否过时了？模块“"@ant-design/charts"”没有导出的成员“Donut”。ts(2305)

### ISSUE THREAD

**Issue by chaocwu** [ant-design/ant-design-charts#2578]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
import { Donut } from '@ant-design/charts';
模块“"@ant-design/charts"”没有导出的成员“Donut”。ts(2305)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image](https://github.com/ant-design/ant-design-charts/assets/143390961/5bea497d-d3d6-4a1c-adc9-743059f470b0)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
"@ant-design/charts": "^2.1.1",
"next": "14.2.4",
"react": "^18",

**Comment by lxfu1** [comment]
最新版本没有这个组件了，可以通过配置实现， https://ant-design-charts.antgroup.com/examples/statistics/pie/#basic-donut

**Comment by Mrzhugq** [comment]
怎么文档上还有😂
![image](https://github.com/user-attachments/assets/79a60586-53b9-4993-a2d7-d0c6b0331d29)
