### ISSUE TITLE
🧐[问题] 词云图rerender之后就不显示内容了

### ISSUE THREAD

**Issue by JellyFishDing** [ant-design/ant-design-charts#258]
### 🧐 问题描述
父组件异步获取数据后使用`setState()`更新，子组件从props获取数据并渲染词云图。从props获取到的数据是没有问题的，也有过一瞬间渲染出来，但是闪烁了一下就没有了，之后就什么都不显示了。
顺便一提官网词云图的demo如果刷新几次也有几率掉落这个问题。

### 💻 示例代码
```js
import React from "react";
import { WordCloud } from "@ant-design/charts";
import "./TopicCard.css";

class TopicCard extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    const data = this.props.topicList;

    const config = {
      data,
      width: 500,
      height: 500,
      color: "#6262ff",
      loading: this.props.loading,
      wordField: "name",
      weightField: "value",
      wordStyle: {
        fontFamily: "Verdana",
        fontSize: [24, 80],
      },
    };
    return (
      <div className="topic-card">
        <WordCloud {...config} onlyChangeData={true}/>
      </div>
    );
  }
}

export default TopicCard;
```

### 🚑 其他信息
本地开发：![word cloud.gif](https://i.loli.net/2020/10/17/uxGklPyOACB47ph.gif)
官网：![word cloud official.gif](https://i.loli.net/2020/10/17/3kdwBzqV7aKiWPr.gif)

**Comment by lxfu1** [comment]
autoFit: false

**Comment by JellyFishDing** [comment]
> autoFit: false

感谢！问题基本上解决了！可以请问一下这是为什么吗？感觉好像是自适应容器的时候画布的大小有一点问题？

**Comment by lxfu1** [comment]
> > autoFit: false
> 
> 感谢！问题基本上解决了！可以请问一下这是为什么吗？感觉好像是自适应容器的时候画布的大小有一点问题

不设置 autoFit：false， charts 会监听 changeSize 事件，词云图底层设置了计算时间， 产生了冲突。

**Comment by JellyFishDing** [comment]
> > > autoFit: false
> > 
> > 
> > 感谢！问题基本上解决了！可以请问一下这是为什么吗？感觉好像是自适应容器的时候画布的大小有一点问题
> 
> 不设置 autoFit：false， charts 会监听 changeSize 事件，词云图底层设置了计算时间， 产生了冲突。

明白了！感谢！

**Comment by philongn** [comment]
image mask is required to ensure that the wordcloud refits on resize
`imageMask: RectanglePattern`

**Comment by xiaopujun** [comment]
![bug](https://user-images.githubusercontent.com/38376350/189038553-b3cc7d38-62d7-4685-b112-ce698b81bebc.gif)

问题描述：
1、当词云图所在容器的大小发生了变化之后，词云图中的书内容消失；重新渲染后可重新出现
2、当设置了autoFit：false后，容器大小发生改变，虽然词云图中数据不消失，但内容没有跟随容器自适应进行填充
3、注：当data写死后，没有上述的1、2问题，容器大小即使发生变化，数据不会消失，并且能自适应填充

这个问题是否为已知bug呢？

> > > autoFit: false
> > 
> > 
> > 感谢！问题基本上解决了！可以请问一下这是为什么吗？感觉好像是自适应容器的时候画布的大小有一点问题
> 
> 不设置 autoFit：false， charts 会监听 changeSize 事件，词云图底层设置了计算时间， 产生了冲突。
