### ISSUE TITLE
🐛[BUG]使用原生的downloadImage()方法下载环图，不展示环图中间的label

### ISSUE THREAD

**Issue by q347446612** [ant-design/ant-design-charts#2582]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

使用原生的downloadImage()方法下载环图，不展示环图中间的label

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

点击下载按钮，查看下载下来的图片

### 🏞 期望结果 [描述你原本期望看到的结果]

下载下来的图片展示中间的label

![download](https://github.com/ant-design/ant-design-charts/assets/59631120/1d0dff00-60b5-48d2-8fe3-84c5b7844266)
![20240704154924](https://github.com/ant-design/ant-design-charts/assets/59631120/e1b39cb5-70cb-4ad7-a3ce-92b7e8d59f67)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
import React, { useRef } from 'react';
import { Button } from 'antd';
import { Pie } from '@ant-design/plots';

const App = () => {
  const chartRef = useRef(null);

  const data = [
    { type: 'Category A', value: 27 },
    { type: 'Category B', value: 25 },
    { type: 'Category C', value: 18 },
    { type: 'Category D', value: 15 },
    { type: 'Category E', value: 10 },
    { type: 'Others', value: 5 },
  ];

  const config = {
    appendPadding: 10,
    data,
    angleField: 'value',
    colorField: 'type',
    radius: 1,
    innerRadius: 0.6,
    label: {
      type: 'inner',
      offset: '-50%',
      content: '{value}',
      style: {
        textAlign: 'center',
        fontSize: 14,
      },
    },
    interactions: [{ type: 'element-selected' }, { type: 'element-active' }],
    statistic: {
      title: false,
      content: {
        style: {
          whiteSpace: 'pre-wrap',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
        },
      },
    },
  };

  const downloadImage = () => {
    if (chartRef.current) {
      chartRef.current.downloadImage();
    }
  };

  return (
    <div>
      <div id="chart-container" style={{ width: '600px', height: '400px' }}>
        <Pie {...config} chartRef={chartRef} />
      </div>
      <Button onClick={downloadImage}>Download Image</Button>
    </div>
  );
};

export default App;

### © 版本信息

"@ant-design/plots": "^1.2.5",

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by q347446612** [comment]
使用html2canvas也不行

**Comment by lxfu1** [comment]
参考这个，https://ant-design-charts.antgroup.com/examples/statistics/pie/#basic-donut
