### ISSUE TITLE
🐛[BUG] Demo中的label的textAnchor这个属性是过期属性，现在文档中的应该是textAlign

### ISSUE THREAD

**Issue by xinrunxie** [ant-design/ant-design-charts#2585]
### 🐛 bug 文档中的textAnchor属性应该是过期属性，现在的应该是textAlign

问题复现地址： https://ant-design-charts.antgroup.com/zh/examples/statistics/bar#bar

<img width="627" alt="image" src="https://github.com/ant-design/ant-design-charts/assets/28630911/1926c8af-691a-4cf6-bc94-d3d3dcf361cd">

这个问题应该是G2就有的，应该更新下demo了

**Comment by lxfu1** [comment]
感兴趣直接提个PR吗

**Comment by xinrunxie** [comment]
可以

**Comment by xinrunxie** [comment]
https://github.com/ant-design/ant-design-charts/pull/2587 @lxfu1
