### ISSUE TITLE
2x版本的仪表盘怎么设置指针颜色？🧐[问题]

### ISSUE THREAD

**Issue by Torstentjh** [ant-design/ant-design-charts#2590]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
已经在仓库里搜了，发现有这个问题但是好像没有回复。
找了很久，只有老版本可以通过 pivot来设置，2x版本使用无效。如下图
![image](https://github.com/ant-design/ant-design-charts/assets/75771172/0a94db0b-362a-402b-b48c-90e78ed05da6)

**Comment by lxfu1** [comment]
@pearmini

**Comment by lxfu1** [comment]
```ts
    style: {
      pointerStroke: 'red',
      pinFill: 'red',
      pinStroke: 'red'
    }
```
