### ISSUE TITLE
🐛[BUG] 文档中的环图 demo 六个分类项只展示了五个

### ISSUE THREAD

**Issue by QHM-tjut** [ant-design/ant-design-charts#2592]
### 🐛 bug 描述 

文档中的饼图 demo 六个分类项只展示了五个

### 📷 复现步骤

打开官方demo
https://ant-design-charts.antgroup.com/examples/statistics/pie/#basic-donut

### 🏞 期望结果

正确的展示六个分类项

### 💻 复现代码

https://ant-design-charts.antgroup.com/examples/statistics/pie/#basic-donut

### © 版本信息

- ant-design-charts 版本: 2.0.0
- 浏览器环境 Chrome 版本 126.0.6478.127（正式版本） (arm64)
- 开发环境 mac OS

### 🚑 其他信息

![image](https://github.com/user-attachments/assets/5140e4c8-e25a-4042-b611-07a857f559f7)

**Comment by lxfu1** [comment]
`paddingRight: 80, ` 去掉一下，求帮忙提个 PR
