### ISSUE TITLE
🐛[BUG]@ant-design/plots@2.x.x版本的图表无法配置y轴的min

### ISSUE THREAD

**Issue by HenryLee951020** [ant-design/ant-design-charts#2596]
### 🐛 bug 描述
在将我使用的版本从1.x.x升级到2.x.x版本后， 无法手动配置axis.y.min来设置y轴的最小坐标点

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://github.com/user-attachments/assets/eefde1b4-445c-4506-9def-0c5c6f678c23)

### 🏞 期望结果 [描述你原本期望看到的结果]
能否保留原有的配置参数 或者有其他的方案我这边没有找到？

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
![image](https://github.com/user-attachments/assets/6043f0ba-e939-47a9-b8ff-7b4d5ca2267c)

### © 版本信息
"@ant-design/plots": "^2.2.2"

- ant-design-charts 版本: @2.2.2
- 浏览器环境: google
- 开发环境: windows

**Comment by lxfu1** [comment]
```ts
    scale: {
      y: {
        domainMin: 0
      }
    },
```
