### ISSUE TITLE
[BUG] export 'StackedArea' (imported as 'StackedArea') was not found in '@ant-design/charts'

### ISSUE THREAD

**Issue by lizihao12** [ant-design/ant-design-charts#2601]
引入 import { StackedArea } from '@ant-design/charts';

使用 return <StackedArea {...config} />;
（我使用import { Line } from '@ant-design/charts'; 可以正常引入使用的
![488F1DC7-D9FB-44b5-BFC5-83A78FAC3E15](https://github.com/user-attachments/assets/e1963050-895b-4dd6-9e7a-1882334e8e36)
）
然后报错 ERROR in ./src/component/finalunitcharts/demoStackedArea.jsx 39:30-41
export 'StackedArea' (imported as 'StackedArea') was not found in '@ant-design/charts' (possible exports: Area, Bar, Base, BidirectionalBar, Box, Bullet, CirclePacking, Column, DualAxes, Funnel, G2, Gauge, Heatmap, Histogram, Line, Liquid, Mix, Pie, Radar, RadialBar, Rose, Sankey, Scatter, Stock, Sunburst, Tiny, Treemap, Venn, Violin, Waterfall, WordCloud, measureTextWidth)

依赖  "dependencies": {
      "@ant-design/charts": "^2.1.1",
      "@ant-design/icons": "^4.7.0",
      "@ant-design/plots": "^2.2.5",
      "@antv/g2": "^5.2.1",
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "lodash-es": "^4.17.21",
      "vite": "^5.2.11",
      }

![image](https://github.com/user-attachments/assets/9e7efcf4-9836-4a5e-bb76-f669f1a5c4d9)

**Comment by allure11** [comment]
解决了吗

**Comment by lizihao12** [comment]
没解决，我换用了这个@ant-design/plots包，https://ant-design-charts.antgroup.com/examples/statistics/scatter#point-log

**Comment by lxfu1** [comment]
StackedArea 是V1版本，注意版本号。
