### ISSUE TITLE
👑 [需求]ant-design-charts 2.1.0，Chrome 83.0.4103.122 图标tooltip展示有失效

### ISSUE THREAD

**Issue by TiankeTt** [ant-design/ant-design-charts#2614]
图表2.x的版本，在上述Chrome浏览器中，Tooltip 展示不出来。
1
![image](https://github.com/user-attachments/assets/82cfcc54-16af-4538-8450-45d487378f61)

**Comment by TiankeTt** [comment]
Tooltip is bad，can't show as the top picture

**Comment by lxfu1** [comment]
审查元素看一下，是否有`.g2-tooltip` 容器，提供下代码或者在线链接

**Comment by TiankeTt** [comment]
> 审查元素看一下，是否有`.g2-tooltip` 容器，提供下代码或者在线链接

您好，这个容器是不存在的。控制台会提示 
![image](https://github.com/user-attachments/assets/198f883a-789f-4899-9d2d-86b5c0b0f3d1)
只有在chrome 83.xxx版本上会这样，导致组件的所有tooltip无法展示。但是最新版本的127版本浏览器显示正常

**Comment by TiankeTt** [comment]
> 审查元素看一下，是否有`.g2-tooltip` 容器，提供下代码或者在线链接

您好，我这边查看后 应该是低版本浏览器不支持 ul.replaceChildren 这个属性
![image](https://github.com/user-attachments/assets/0ec30880-65e0-48a5-8072-ac0712be42ea)

![image](https://github.com/user-attachments/assets/2afd38da-8f87-4d4d-a7a6-3002c4171e89)

**Comment by lxfu1** [comment]
@pearmini

**Comment by TiankeTt** [comment]
@pearmini 辛苦同学帮忙看下这个问题。🧎🏻谢

**Comment by pearmini** [comment]
@TiankeTt 好的我去掉一下这个方法

**Comment by TiankeTt** [comment]
> @TiankeTt 好的我去掉一下这个方法

请问你去掉后我咋更新本地呢，是会发布一个新包么

**Comment by pearmini** [comment]
@TiankeTt 可以试试这个版本 @antv/component@2.0.2

**Comment by TiankeTt** [comment]
> @TiankeTt 可以试试这个版本 @antv/component@2.0.2

收到！谢谢同学。我这边客户端同事升级了浏览器版本，解决这个问题了也。

**Comment by TiankeTt** [comment]
> @TiankeTt 可以试试这个版本 @antv/component@2.0.2

同学您好，我今天尝试了一下 83版本浏览器出现新问题了。可能别的地方还在使用 replaceChildren 这个方法导致的
<img width="525" alt="image" src="https://github.com/user-attachments/assets/0300571a-4828-4e2f-94ca-cec44b3c8a1e">
<img width="346" alt="image" src="https://github.com/user-attachments/assets/e609ccf1-7ab0-47f1-906c-808b80de3c5f">

**Comment by TiankeTt** [comment]
> > @TiankeTt 可以试试这个版本 @antv/component@2.0.2
> 
> 同学您好，我今天尝试了一下 83版本浏览器出现新问题了。可能别的地方还在使用 replaceChildren 这个方法导致的 <img alt="image" width="525" src="https://private-user-images.githubusercontent.com/27058669/354175651-0300571a-4828-4e2f-94ca-cec44b3c8a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjI4NzQsIm5iZiI6MTcyMjgyMjU3NCwicGF0aCI6Ii8yNzA1ODY2OS8zNTQxNzU2NTEtMDMwMDU3MWEtNDgyOC00ZTJmLTk0Y2EtY2VjNDRiM2M4YTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAxNDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MGRmMjUzM2Q4MjA1NGM0ZjllNGIwNzJmYzAyZTcyMzY0YmNiNTY4MWJiNGMwZjRjMjIwMDZjNmI1Y2IzNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JrjY7p6--_ADQ0CD6Ms7Mm8GlVBPpzJigbIujK0GPZk"> <img alt="image" width="346" src="https://private-user-images.githubusercontent.com/27058669/354175680-e609ccf1-7ab0-47f1-906c-808b80de3c5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjI4NzQsIm5iZiI6MTcyMjgyMjU3NCwicGF0aCI6Ii8yNzA1ODY2OS8zNTQxNzU2ODAtZTYwOWNjZjEtN2FiMC00N2YxLTkwNmMtODA4YjgwZGUzYzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAxNDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwOGViZDc2NDYzMTI2ODczMzFkMDA5MGNlMGUzY2ViZTIzNTg0ZGQ3NDFjOTU0NjJlMTgzYzZkNzYzZTk1ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QbGtA7yi9GKbX3vPMOFIGfOJPRmOsNZiSwBp9nVCZ2k">

@pearmini

**Comment by TiankeTt** [comment]
> @TiankeTt 可以试试这个版本 @antv/component@2.0.2

您好，这个版本没解决了问题，出现新问题了。

**Comment by lxfu1** [comment]
> @TiankeTt 可以试试这个版本 @antv/component@2.0.2

2.0.3

**Comment by TiankeTt** [comment]
> > @TiankeTt 可以试试这个版本 @antv/component@2.0.2
> 
> 2.0.3

您好同学，试过了。还没解决这个问题。

/node_modules/@antv/component/esm/ui/tooltip/index.js

133行
Tooltip.prototype.renderHiMLTooltipElement = function (){} 这个方法上方还在使用 this.element.replacechildren(content)，this.element上不存在 replacechildren 这个方法

**Comment by lxfu1** [comment]
> > > @TiankeTt 可以试试这个版本 @antv/component@2.0.2
> > 
> > 
> > 2.0.3
> 
> 您好同学，试过了。还没解决这个问题。
> 
> /node_modules/@antv/component/esm/ui/tooltip/index.js
> 
> 133行 Tooltip.prototype.renderHiMLTooltipElement = function (){} 这个方法上方还在使用 this.element.replacechildren(content)，this.element上不存在 replacechildren 这个方法

建议看下实际安装的版本号，还有问题的话，提供下截图

**Comment by TiankeTt** [comment]
> > > > @TiankeTt 可以试试这个版本 @antv/component@2.0.2
> > > 
> > > 
> > > 2.0.3
> > 
> > 
> > 您好同学，试过了。还没解决这个问题。
> > /node_modules/@antv/component/esm/ui/tooltip/index.js
> > 133行 Tooltip.prototype.renderHiMLTooltipElement = function (){} 这个方法上方还在使用 this.element.replacechildren(content)，this.element上不存在 replacechildren 这个方法
> 
> 建议看下实际安装的版本号，还有问题的话，提供下截图

![image](https://github.com/user-attachments/assets/bca1b725-bbe7-48e9-a10a-a0724533917d)

**Comment by lxfu1** [comment]
> > > > > @TiankeTt 可以试试这个版本 @antv/component@2.0.2
> > > > 
> > > > 
> > > > 2.0.3
> > > 
> > > 
> > > 您好同学，试过了。还没解决这个问题。
> > > /node_modules/@antv/component/esm/ui/tooltip/index.js
> > > 133行 Tooltip.prototype.renderHiMLTooltipElement = function (){} 这个方法上方还在使用 this.element.replacechildren(content)，this.element上不存在 replacechildren 这个方法
> > 
> > 
> > 建议看下实际安装的版本号，还有问题的话，提供下截图
> 
> ![image](https://private-user-images.githubusercontent.com/27058669/355001411-bca1b725-bbe7-48e9-a10a-a0724533917d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDE4NDYsIm5iZiI6MTcyMjg0MTU0NiwicGF0aCI6Ii8yNzA1ODY2OS8zNTUwMDE0MTEtYmNhMWI3MjUtYmJlNy00OGU5LWExMGEtYTA3MjQ1MzM5MTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA3MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNDM5ZTMwNTY3MzI1ZDY4MzcxNzA0ODdlNWQwOWU3NTJlOTZmYjdiN2U0MGExZDFmZDBhOWQyYmUwN2RmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFKNpwvjY4JN68XPvJIkv0rU3PaC7_A0eHf3U9e3VCE)

你这个版本不对，去node_modules里面看

**Comment by TiankeTt** [comment]
> > > > @TiankeTt 可以试试这个版本 @antv/component@2.0.2
> > > 
> > > 
> > > 2.0.3
> > 
> > 
> > 您好同学，试过了。还没解决这个问题。
> > /node_modules/@antv/component/esm/ui/tooltip/index.js
> > 133行 Tooltip.prototype.renderHiMLTooltipElement = function (){} 这个方法上方还在使用 this.element.replacechildren(content)，this.element上不存在 replacechildren 这个方法
> 
> 建议看下实际安装的版本号，还有问题的话，提供下截图

你看下上面的

> > > > > > @TiankeTt 可以试试这个版本 @antv/component@2.0.2
> > > > > 
> > > > > 
> > > > > 2.0.3
> > > > 
> > > > 
> > > > 您好同学，试过了。还没解决这个问题。
> > > > /node_modules/@antv/component/esm/ui/tooltip/index.js
> > > > 133行 Tooltip.prototype.renderHiMLTooltipElement = function (){} 这个方法上方还在使用 this.element.replacechildren(content)，this.element上不存在 replacechildren 这个方法
> > > 
> > > 
> > > 建议看下实际安装的版本号，还有问题的话，提供下截图
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/27058669/355001411-bca1b725-bbe7-48e9-a10a-a0724533917d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDE4NDYsIm5iZiI6MTcyMjg0MTU0NiwicGF0aCI6Ii8yNzA1ODY2OS8zNTUwMDE0MTEtYmNhMWI3MjUtYmJlNy00OGU5LWExMGEtYTA3MjQ1MzM5MTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA3MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNDM5ZTMwNTY3MzI1ZDY4MzcxNzA0ODdlNWQwOWU3NTJlOTZmYjdiN2U0MGExZDFmZDBhOWQyYmUwN2RmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFKNpwvjY4JN68XPvJIkv0rU3PaC7_A0eHf3U9e3VCE)
> 
> 你这个版本不对，去node_modules里面看

稍等我去看看

**Comment by TiankeTt** [comment]
> > > > > > @TiankeTt 可以试试这个版本 @antv/component@2.0.2
> > > > > 
> > > > > 
> > > > > 2.0.3
> > > > 
> > > > 
> > > > 您好同学，试过了。还没解决这个问题。
> > > > /node_modules/@antv/component/esm/ui/tooltip/index.js
> > > > 133行 Tooltip.prototype.renderHiMLTooltipElement = function (){} 这个方法上方还在使用 this.element.replacechildren(content)，this.element上不存在 replacechildren 这个方法
> > > 
> > > 
> > > 建议看下实际安装的版本号，还有问题的话，提供下截图
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/27058669/355001411-bca1b725-bbe7-48e9-a10a-a0724533917d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDE4NDYsIm5iZiI6MTcyMjg0MTU0NiwicGF0aCI6Ii8yNzA1ODY2OS8zNTUwMDE0MTEtYmNhMWI3MjUtYmJlNy00OGU5LWExMGEtYTA3MjQ1MzM5MTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA3MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNDM5ZTMwNTY3MzI1ZDY4MzcxNzA0ODdlNWQwOWU3NTJlOTZmYjdiN2U0MGExZDFmZDBhOWQyYmUwN2RmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFKNpwvjY4JN68XPvJIkv0rU3PaC7_A0eHf3U9e3VCE)
> 
> 你这个版本不对，去node_modules里面看

我重新卸载安装的。在 node_modules 里ant charts 的package.json 里看的 确实是2.0.3

**Comment by lxfu1** [comment]
> > > > > > > @TiankeTt 可以试试这个版本 @antv/component@2.0.2
> > > > > > 
> > > > > > 
> > > > > > 2.0.3
> > > > > 
> > > > > 
> > > > > 您好同学，试过了。还没解决这个问题。
> > > > > /node_modules/@antv/component/esm/ui/tooltip/index.js
> > > > > 133行 Tooltip.prototype.renderHiMLTooltipElement = function (){} 这个方法上方还在使用 this.element.replacechildren(content)，this.element上不存在 replacechildren 这个方法
> > > > 
> > > > 
> > > > 建议看下实际安装的版本号，还有问题的话，提供下截图
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/27058669/355001411-bca1b725-bbe7-48e9-a10a-a0724533917d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDE4NDYsIm5iZiI6MTcyMjg0MTU0NiwicGF0aCI6Ii8yNzA1ODY2OS8zNTUwMDE0MTEtYmNhMWI3MjUtYmJlNy00OGU5LWExMGEtYTA3MjQ1MzM5MTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA3MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNDM5ZTMwNTY3MzI1ZDY4MzcxNzA0ODdlNWQwOWU3NTJlOTZmYjdiN2U0MGExZDFmZDBhOWQyYmUwN2RmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFKNpwvjY4JN68XPvJIkv0rU3PaC7_A0eHf3U9e3VCE)
> > 
> > 
> > 你这个版本不对，去node_modules里面看
> 
> 我重新卸载安装的。在 node_modules 里ant charts 的package.json 里看的 确实是2.0.3

你没搞清楚啊，你要看node_modules里面的 @antv/components ~，其次，ant charts 用最新版本，不要限定到2.0.3

**Comment by TiankeTt** [comment]
谢谢同学。我这边解决了。我弄混了一直升级的是 chats 的包。辛苦了
---- 回复的原邮件 ----
| 发件人 | Joel ***@***.***> |
| 日期 | 2024年08月05日 15:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ant-design/ant-design-charts] [需求]ant-design-charts 2.1.0，Chrome 83.0.4103.122 图标tooltip展示有失效 (Issue #2614) |

@TiankeTt 可以试试这个版本 @***@***.***

2.0.3

您好同学，试过了。还没解决这个问题。
***@***.***/component/esm/ui/tooltip/index.js
133行 Tooltip.prototype.renderHiMLTooltipElement = function (){} 这个方法上方还在使用 this.element.replacechildren(content)，this.element上不存在 replacechildren 这个方法

建议看下实际安装的版本号，还有问题的话，提供下截图

你这个版本不对，去node_modules里面看

我重新卸载安装的。在 node_modules 里ant charts 的package.json 里看的 确实是2.0.3

你没搞清楚啊，你要看node_modules里面的 @antv/components ~，其次，ant charts 用最新版本，不要限定到2.0.3
