### ISSUE TITLE
🐛[BUG]点击图中的标记，打开弹窗的瞬间，标记会偏移

### ISSUE THREAD

**Issue by Eileen-v** [ant-design/ant-design-charts#2616]
### 🐛 bug 描述  
点击图中的标记，打开弹窗的瞬间，标记会偏移，关闭弹窗后，偏移的标记又回来了

### 🏞 期望结果 
标记不要发生偏移

### 💻 复现代码 
  const analyzeConfig = {
    data: querychartData,
    xField: 'baseSampleNumber',
    yField: 'value',
    height: 600,
    colorField: 'type',
    legend: {
      color: {
        itemLabelFontSize: 15,
      },
    },
    interaction: {
      tooltip: {
        render: (event, options) => {
          const change = querychartData.filter(
            (querychart) =>
              querychart.baseSampleNumber === options.title && querychart.formulaChangeValue,
          )[0];
          return (
            <div style={{ background: '#fff' }}>
              <p style={{ fontWeight: '600' }}>{options.title}</p>
              {options.items.map((item, index) => {
                return (
                  <div key={index}>
                    <p style={{ fontWeight: '600' }}>
                      {item.name}: {item.value}
                    </p>
                    {change && index === 0 && (
                      <>
                        <p>卷烟牌号：{change?.baseSampleName}</p>
                      </>
                    )}
                  </div>
                );
              })}
            </div>
          );
        },
      },
    },
    style: {
      lineWidth: 2,
    },
    scale: {
      y: {
        domainMin:
          Math.ceil(Math.min(...querychartData.map((item) => item.value)) * 0.3) > 1
            ? Math.ceil(Math.min(...querychartData.map((item) => item.value)) * 0.3)
            : 0,
        domainMax:
          Math.max(...querychartData.map((item) => item.value)) > 1
            ? Math.ceil(Math.max(...querychartData.map((item) => item.value)) * 1.3)
            : 1.3,
      },
    },
    annotations: showAnnotations
      ? [
          ...handleDesignAnnotation(),
          ...handleCheckAnnotation(),
          {
            type: 'lineY',
            data: [
              Math.min(...querychartData.map((item) => item.value)) > 1
                ? Math.ceil(Math.min(...querychartData.map((item) => item.value)) * 0.5)
                : 0.4,
            ],
            label: {
              text: '下限',
              position: 'left',
              dx: -10,
              style: { textBaseline: 'bottom' },
            },
            style: { stroke: 'rgba(0, 0, 0)', lineDash: [4, 4] },
          },
          {
            type: 'lineY',
            data: [
              Math.max(...querychartData.map((item) => item.value)) > 1
                ? Math.ceil(Math.max(...querychartData.map((item) => item.value)) * 1.1)
                : 1.3,
            ],
            label: {
              text: '上限',
              position: 'left',
              dx: -10,
              style: { textBaseline: 'bottom' },
            },

            style: { stroke: 'rgba(0, 0, 0)', lineDash: [4, 4] },
          },
        ]
      : [...handleDesignAnnotation(), ...handleCheckAnnotation()],
    onReady: ({ chart }) => {
      chart.on(`element:click`, (event) => {
        if (typeof event.data.data === 'string') {
          handleDefectDetailsOpen(true);
          setRetrospectSampleNumber(event.data.data);
        }
      });
    },
  };

### © 版本信息

- "@ant-design/charts": "1.4.2",
- 浏览器环境  谷歌
- 开发环境 window10  11

**Comment by lxfu1** [comment]
应该是你打开弹窗触发了二次渲染，配合React.memo把 onReady\data 抽离实现
https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx
