### ISSUE TITLE
🧐[问题] PieChart 的tooltip 呈現"value"文字, 而不是真正的數值

### ISSUE THREAD

**Issue by astroneurosan** [ant-design/ant-design-charts#2617]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
PieChart 的tooltip 呈現"value", 而不是真正的數值 "No"
![image](https://github.com/user-attachments/assets/48204d1e-b5a4-4efe-8f21-41fb20ce84cb)

請問是哪部分出現問題？
代碼檢查後跟範例上一樣 但還是看不出問題
謝謝！

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
`
const PieChart: React.FC<PieProps> = ({ data, title }) => {
  const config = {
    theme: 'classicDark',
    data,
    height: 240,
    title: title,
    angleField: 'value',
    colorField: 'type',
    scale: {
      color: {
        range: ['#7a7979', '#4287f5', '#4ce085'],
      },
    },
    legend: {
      color: {
        itemLabelFontSize: 14,
        title: title,
        position: 'right',
      },
    },
  };
  return <Pie {...config} />;
};
`

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
  "@ant-design/charts": "^2.1.2",
  "next": "^14.2.3",

**Comment by lxfu1** [comment]
https://ant-design-charts.antgroup.com/examples/statistics/column/#tooltip

**Comment by DaHeaths** [comment]
// ant design charts v2.2.1 

const config = {
    data: pieData,
    angleField: 'value',
    colorField: 'type',
    innerRadius: 0.8,
    scale: {
      color: { range: colors }
    },
    // 重点：看这里，修改为这个
    tooltip: (data) => ({
      name: data.type,
      value: `${data.value}%`
    }),
    legend: false,
    annotations: [
      {
        type: 'text',
        style: {
          text: '',
          x: '50%',
          y: '42%',
          textAlign: 'center',
          fontSize: 23,
          fontStyle: 'bold',
        },
      },
      {
        type: 'text',
        style: {
          text: '',
          x: '50%',
          y: '56%',
          textAlign: 'center',
          fontSize: 12,
          fontStyle: 'bold',
        },
      },
      {
        type: 'text',
        style: {
          text: '',
          x: '50%',
          y: '66%',
          textAlign: 'center',
          fontSize: 12,
          fontStyle: 'bold',
        },
      },
    ],
  };
