### ISSUE TITLE
🐛[BUG]面积图y轴刻度最小值不是0的时候，会遮盖x轴

### ISSUE THREAD

**Issue by maoyuehui** [ant-design/ant-design-charts#2619]
![C4A2D9F7-73AD-4EE5-93A8-AECDC1C50A71](https://github.com/user-attachments/assets/cef1f023-cf31-4c9e-bdf2-5f0b04f02bb6)
使用面积图，当配置最小值不是0的时候，会遮盖x轴
scale: {
   y: {
       type: 'linear',
      domain: [100, 750],
      tickMethod: () => [100, 300, 750]
     }
 },

**Comment by maoyuehui** [comment]
面积图的刻度的区间也期望根据传入的data,自动适配，比如这个官网的这个demo
data中最小值是3，最大值是13，刻度适配的最小值就是2，最大值是14，这个非常好，期望能一样的
![image](https://github.com/user-attachments/assets/365d327e-2434-4306-88e5-8cdee5017df8)

**Comment by lxfu1** [comment]
> ![C4A2D9F7-73AD-4EE5-93A8-AECDC1C50A71](https://private-user-images.githubusercontent.com/165237469/352452076-cef1f023-cf31-4c9e-bdf2-5f0b04f02bb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODUyMjIsIm5iZiI6MTcyMTk4NDkyMiwicGF0aCI6Ii8xNjUyMzc0NjkvMzUyNDUyMDc2LWNlZjFmMDIzLWNmMzEtNGM5ZS1iZGYyLTVmMGIwNGYwMmJiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwOTA4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2Y1ZGMyNDZhN2U5ZjM0OTE3MjgzOGNkN2JhNWFiNDhhOGE1ZTg4MGRlMzA1NjNjNDlmZWUwZDMyNmQ1MTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4NC7bvPSAAUHskZshHImiUOsUa3KD1zO8eg0SzBD_Bc) 使用面积图，当配置最小值不是0的时候，会遮盖x轴 scale: { y: { type: 'linear', domain: [100, 750], tickMethod: () => [100, 300, 750] } },

这个是因为你设置了domain，数据里面最小值低于domainMin导致的

**Comment by maoyuehui** [comment]
![image](https://github.com/user-attachments/assets/b36297b8-a661-44b3-ace5-4945e49ffea1)
现在我写死数据，data中没有比我设置的domain小了，还是一样的会遮盖
import React from 'react';
import ReactDOM from 'react-dom';
import { Area } from '@ant-design/plots';

const DemoArea = () => {
  const config = {
    data: [
      {
        "date": "1994",
        "price": 325
      },
      {
        "date": "1995",
        "price": 600
      },
      {
        "date": "1996",
        "price": 233
      },
      {
        "date": "1998",
        "price": 150
      },
    ],
    xField: 'date',
    yField: 'price',
    style: {
      fill: 'linear-gradient(-90deg, white 0%, darkgreen 100%)',
    },
    axis: {
      y: { labelFormatter: '~s' },
    },
    line: {
      style: {
        stroke: 'darkgreen',
        strokeWidth: 2,
      },
    },
    scale: {
      y: {
        type: 'linear',
        domain: [100, 750],
        // domainMin: 100,
        tickMethod: () => [100, 300, 750]
      }
    },
  };
  return <Area {...config} />;
};

ReactDOM.render(<DemoArea />, document.getElementById('container'));

**Comment by maoyuehui** [comment]
顺便麻烦问一下有钉钉的答疑群吗？

**Comment by maoyuehui** [comment]
或者按照数学角度来说面积图的设定是必须从0开始，不是简单的一个渐变效果，就是面积
那就换个组件比如用折线图的哪个属性可以实现这个效果？
类似bizcharts的这种折线图，实现这个渐变效果
![image](https://github.com/user-attachments/assets/39dad53f-c359-4761-92f0-459c67a2dfc5)

**Comment by mahsa-shabaninezhad** [comment]
> https://ant-design-charts.antgroup.com/examples/statistics/area/#area-gradient

I have the same problem reported in this issue. The link you shared doesn't have the problem specified in the issue. I only added the scale to the code as below:
```
import React from 'react';
import ReactDOM from 'react-dom';
import { Area } from '@ant-design/plots';

const DemoArea = () => {
  const config = {
    data: {
      type: 'fetch',
      value: 'https://assets.antv.antgroup.com/g2/stocks.json',
      transform: [{ type: 'filter', callback: (d) => d.symbol === 'GOOG' }],
    },
    xField: (d) => new Date(d.date),
    yField: 'price',
    style: {
      fill: 'linear-gradient(-90deg, white 0%, darkgreen 100%)',
    },
    // I added this 
    scale: {
      y: {
          type: 'linear',
          domain: [102, 800],

      },
    },
    axis: {
      y: { labelFormatter: '~s' },
    },
    line: {
      style: {
        stroke: 'darkgreen',
        strokeWidth: 2,
      },
    },
  };
  return <Area {...config} />;
};

ReactDOM.render(<DemoArea />, document.getElementById('container'));

```

The outcome is:

![Image](https://github.com/user-attachments/assets/bfe4c1d4-39a3-49e6-9a7a-a5b528bee6ec)

So The x-axis is covered by gradient area, which obviously I don't want.
