### ISSUE TITLE
🧐[问题]xAxis的label怎么实现带有tooltip的效果

### ISSUE THREAD

**Issue by jarvislin94** [ant-design/ant-design-charts#2620]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
xAxis.label.formatter 不支持返回react node, 如果想实现这个效果，有什么其它办法吗？

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/user-attachments/assets/2a73fffe-00fc-4e79-bbaf-7890bfea5923)

**Comment by lxfu1** [comment]
V1不支持的，V2可以自定义标签+绑定事件实现，https://ant-design-charts.antgroup.com/zh/examples/statistics/column/#label-text
