### ISSUE TITLE
🐛[BUG]autoRotate=true时，在label文字介于旋转和不旋转的临界值，横坐标文字被隐藏

### ISSUE THREAD

**Issue by xinjiahuan** [ant-design/ant-design-charts#2625]
### 🐛 bug 描述
autoRotate=true时，在label文字介于旋转和不旋转的临界值，横坐标文字被隐藏

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
设置autoRotate=true时，拖拽浏览器页面，使文字由旋转变为不旋转，（慢慢拖拽），即可复现此问题
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom';
import { DualAxes } from '@ant-design/plots';

const DemoDualAxes = () => {
  const uvData = [
    {
      time: '2019-03',
      value: 35,
    },
    {
      time: '2019-04',
      value: 90,
    },
    {
      time: '2019-05',
      value: 30,
    },
    {
      time: '2019-06',
      value: 45,
    },
    {
      time: '2019-07',
      value: 47,
    },
  ];
  const transformData = [
    {
      time: '2019-03',
      count: 800,
      name: 'a',
    },
    {
      time: '2019-04',
      count: 600,
      name: 'a',
    },
    {
      time: '2019-05',
      count: 400,
      name: 'a',
    },
    {
      time: '2019-06',
      count: 380,
      name: 'a',
    },
    {
      time: '2019-07',
      count: 220,
      name: 'a',
    },
    {
      time: '2019-03',
      count: 750,
      name: 'b',
    },
    {
      time: '2019-04',
      count: 650,
      name: 'b',
    },
    {
      time: '2019-05',
      count: 450,
      name: 'b',
    },
    {
      time: '2019-06',
      count: 400,
      name: 'b',
    },
    {
      time: '2019-07',
      count: 320,
      name: 'b',
    },
    {
      time: '2019-03',
      count: 900,
      name: 'c',
    },
    {
      time: '2019-04',
      count: 600,
      name: 'c',
    },
    {
      time: '2019-05',
      count: 450,
      name: 'c',
    },
    {
      time: '2019-06',
      count: 300,
      name: 'c',
    },
    {
      time: '2019-07',
      count: 200,
      name: 'c',
    },
  ];
  const config = {
    data: [uvData, transformData],
    xField: 'time',
    yField: ['value', 'count'],
    xAxis:{
      label:{
        autoRotate:true,
      }
    },
    geometryOptions: [
      {
        geometry: 'column',
        columnWidthRatio: 0.4,
      },
      {
        geometry: 'line',
        seriesField: 'name',
      },
    ],
  };
  return <DualAxes {...config} />;
};

ReactDOM.render(<DemoDualAxes />, document.getElementById('container'));

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/user-attachments/assets/4fe3e4fb-67e0-4485-b7c5-dea72688f2bb)

**Comment by xinjiahuan** [comment]
Uploading 飞书20240730-165837.mp4…

**Comment by lxfu1** [comment]
设置一下padding: [40, 60]

**Comment by xinjiahuan** [comment]
> 设置一下padding: [40, 60]

设置padding是为了留出label旋转时要用的位置吧，但是我不确定label的长度，所以不能写死padding，这个是个bug，是只有在临界值的时候才会隐藏，不是一直隐藏，如果再继续缩小就会自适应不隐藏了，并不是靠padding简单解决的问题
