### ISSUE TITLE
chrome 83版本，ant-design-charts 2.0.2 版本

### ISSUE THREAD

**Issue by TiankeTt** [ant-design/ant-design-charts#2629]
> @TiankeTt 可以试试这个版本 @antv/component@2.0.2

同学您好，我今天尝试了一下 83版本浏览器出现新问题了。可能别的地方还在使用 replaceChildren 这个方法导致的
<img width="525" alt="image" src="https://github.com/user-attachments/assets/0300571a-4828-4e2f-94ca-cec44b3c8a1e">
<img width="346" alt="image" src="https://github.com/user-attachments/assets/e609ccf1-7ab0-47f1-906c-808b80de3c5f">

_Originally posted by @TiankeTt in https://github.com/ant-design/ant-design-charts/issues/2614#issuecomment-2262626779_

**Comment by hustcc** [comment]
是不是因为使用的 umd 的 js 包，这个包还没有更新版本。

**Comment by TiankeTt** [comment]
没有使用umd 就单纯引入了ant-design-charts 之前用的2.1.0 高版本浏览器没问题，在83版本chrome浏览器会出现tooltip无法出现，然后我提了issue后，作者同学让我使用2.0.2版本。这个版本在旧版浏览器是上面的效果，新版浏览器在鼠标移动的时候也会出现闪烁问题

**Comment by lxfu1** [comment]
闪烁问题给tooltip的容器加个key试试

**Comment by TiankeTt** [comment]
> 闪烁问题给tooltip的容器加个key试试
@lxfu1 
怎么给容器添加key呢，另外再83版本的chrome浏览器的话 tooltip是无法出现内容的，最新的版本可以出现但是会先出现一个白色的框然后马上闪出正确的tooltip。
ant-design-charts 2.0.2

**Comment by lxfu1** [comment]
提供个在线示例吧

**Comment by TiankeTt** [comment]
> 闪烁问题给tooltip的容器加个key试试
@lxfu1 
怎么给容器添加key呢，另外再83版本的chrome浏览器的话 tooltip是无法出现内容的，最新的版本可以出现但是会先出现一个白色的框然后马上闪出正确的tooltip。
ant-design-charts 2.0.2
