### ISSUE TITLE
在react hooks里面使用词云图的示例无效，渲染为空

### ISSUE THREAD

**Issue by aguoshuai** [ant-design/ant-design-charts#263]
代码是直接复制示例的js代码，渲染空白

**Comment by lxfu1** [comment]
提供下错误信息或者在线demo。

**Comment by aguoshuai** [comment]
import React, { useState, useEffect } from 'react';
import { WordCloud } from '@ant-design/charts';
const DemoWordCloud = () => {
  const [data, setData] = useState([]);
  useEffect(() => {
    asyncFetch();
  }, []);
  const asyncFetch = () => {
    fetch('https://gw.alipayobjects.com/os/antvdemo/assets/data/antv-keywords.json')
      .then(response => response.json())
      .then(json => setData(json))
      .catch(error => {
        console.log('fetch data failed', error);
      });
  };
  const config = {
    data,
    width: 600,
    height: 400,
    autoFit: false,
    wordField: 'name',
    weightField: 'value',
    imageMask:
      'https://gw.alipayobjects.com/mdn/rms_2274c3/afts/img/A*07tdTIOmvlYAAAAAAAAAAABkARQnAQ',
    wordStyle: {
      fontFamily: 'Verdana',
      fontSize: [8, 32],
    },
  };
  return <WordCloud {...config} />;
};
export default DemoWordCloud;



这段代码在本地就无法生成图表，渲染出来为空白，换成折线图都可以

**Comment by lxfu1** [comment]
你看一下 fetch  这个需要你自己引入的。

**Comment by aguoshuai** [comment]
我知道，我数据写是单独写死的，还是无法渲染出来

**Comment by lxfu1** [comment]
https://codesandbox.io/s/quizzical-ramanujan-v1er5?file=/src/App.js
