### ISSUE TITLE
🧐[问题]legend的大小粗细

### ISSUE THREAD

**Issue by YH-82** [ant-design/ant-design-charts#2631]
1.x版本的
![image](https://github.com/user-attachments/assets/fa81e849-bdfc-4ee5-ad56-110a7d09ec9c)
2.x版本的
![image](https://github.com/user-attachments/assets/ff4721dc-db97-43cc-85d6-872decec297b)

如何配置2.x版本的代码才能像1.x版本的图例大小一致呢。目前的这个太细了

**Comment by YH-82** [comment]
配置无效
```
legend: {
      size: 'big'
  },
```

**Comment by lxfu1** [comment]
```ts
legend.color.itemMarkerSize: 16
```
