### ISSUE TITLE
🧐[问题] In Ant Design Charts v2, when the value of the axis is 0, the line representing 0 is shown in the center of the screen instead of aligning with the bottom of the x-axis.

### ISSUE THREAD

**Issue by hello-klyen** [ant-design/ant-design-charts#2632]
``### 🧐 问题描述 [详细地描述问题，让大家都能理解]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![Screenshot 2024-08-03 at 01 13 46](https://github.com/user-attachments/assets/ec4d2882-1d84-470e-be47-89feb258c7bf)

`import { Column } from '@ant-design/plots';
import React from 'react';
import ReactDOM from 'react-dom';

const dummyData = [
  {
    month: 'Aug',
    date: '2023-08-31',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Aug',
    date: '2023-08-31',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'Sep',
    date: '2023-09-30',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Sep',
    date: '2023-09-30',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'Oct',
    date: '2023-10-31',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Oct',
    date: '2023-10-31',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'Nov',
    date: '2023-11-30',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Nov',
    date: '2023-11-30',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'Dec',
    date: '2023-12-31',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Dec',
    date: '2023-12-31',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'Jan',
    date: '2024-01-31',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Jan',
    date: '2024-01-31',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'Feb',
    date: '2024-02-29',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Feb',
    date: '2024-02-29',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'Mar',
    date: '2024-03-31',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Mar',
    date: '2024-03-31',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'Apr',
    date: '2024-04-30',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Apr',
    date: '2024-04-30',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'May',
    date: '2024-05-31',
    type: 'income',
    amount: 0,
  },
  {
    month: 'May',
    date: '2024-05-31',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'Jun',
    date: '2024-06-30',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Jun',
    date: '2024-06-30',
    type: 'expenses',
    amount: 0,
  },
  {
    month: 'Jul',
    date: '2024-07-30',
    type: 'income',
    amount: 0,
  },
  {
    month: 'Jul',
    date: '2024-07-30',
    type: 'expenses',
    amount: 0,
  },
];

const DemoColumn = () => {
  const config = {
    data: dummyData,
    xField: 'month',
    yField: 'amount',
    colorField: 'type',
    group: true,
  
    style: {
     
      inset: 5,
    
    },
  };
  return <Column {...config} />;
};

ReactDOM.render(<DemoColumn />, document.getElementById('container'));
`

**Comment by lxfu1** [comment]
```ts
scale: {
  y: {
    domain: [0, 10] 
  }
},

```

**Comment by s587427** [comment]
If the values ​​of the data are all the same but not 0, the same situation will occur. How to solve it?
