### ISSUE TITLE
🧐[问题] 柱状图配置自定义坐标轴文案后，图表左上角会出现多余相同的文案，该怎么办？

### ISSUE THREAD

**Issue by wangwenhao30** [ant-design/ant-design-charts#2633]
### 🧐 如题，配置是和文档给的例子类似的
[https://ant-design-charts-next.antgroup.com/examples/statistics/column/#label-text](url)
### 💻 具体的配置代码
![企业微信截图_655b5f71-0494-43b1-868b-e01777e9c931](https://github.com/user-attachments/assets/782a37fc-d41b-42e3-aacd-c27690463088)

### 🚑 效果样式
<img width="600" alt="企业微信截图_a1b835b6-b40b-4cdb-a075-3c99a2911b2a" src="https://github.com/user-attachments/assets/218b601c-7189-48d2-b0c6-5ef98cdb5cf4">

**Comment by lxfu1** [comment]
指定一下 axis.x.size: 60
