### ISSUE TITLE
🧐[问题]   设置X轴的tickCount 无效 

### ISSUE THREAD

**Issue by elmelloi** [ant-design/ant-design-charts#2634]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

面对这种情况
![image](https://github.com/user-attachments/assets/794380ce-fa41-45d4-8999-ff8d7d095c5a)

想使用
` axis={{
        x: { tickCount: 2 },
        y: { tickCount: 2 },
      }}`
   发现X轴没有效果，Y轴有效果
      

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

https://codesandbox.io/p/sandbox/xenodochial-chandrasekhar-vyhs69?file=%2Findex.js

更改axis下的x,y轴的tickCount就能发现问题

**Comment by lxfu1** [comment]
tickCount 只针对连续类型，例如 number、date，建议使用labelFormatter。或者自定义 `tickMethod(min, max, tickCount)`

**Comment by elmelloi** [comment]
好吧，主要是1.x 版本的时候可以通过`xAxis: {
      range: [0, 1],
      tickCount: 5,
    },`
来配置。谢谢解答
