### ISSUE TITLE
👑 [需求]2.0版本axis如何设置最大值？

### ISSUE THREAD

**Issue by a1782680475** [ant-design/ant-design-charts#2638]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
1.x版本有max这个属性设置axis最大值，但是2.0没有对应api。

**Comment by lxfu1** [comment]
```ts
  scale:{
      y: {
        domainMax: 100,
      }
    },
```

**Comment by a1782680475** [comment]
> ```ts
>   scale:{
>       y: {
>         domainMax: 100,
>       }
>     },
> ```



> ```ts
>   scale:{
>       y: {
>         domainMax: 100,
>       }
>     },
> ```

可以了，谢谢！
