### ISSUE TITLE
🧐[问题] 怎么禁用首次加载动画?

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design-charts#264]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
仪表盘从后台更新数据后重新渲染出现首次加载动画,就导致只要数据更新仪表盘就闪一下太明显,

animate配置为false无效,animation也无效
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
 "name": "@ant-design/charts",
  "version": "1.0.1",

**Comment by lxfu1** [comment]
animation: false

**Comment by laolaolulu** [comment]
> animation: false

没效果,

**Comment by laolaolulu** [comment]
> animation: false

其他图形有效果,就仪表盘没

**Comment by lxfu1** [comment]
> > animation: false
> 
> 其他图形有效果,就仪表盘没

应该是bug，你先加个 loading 处理一下。

**Comment by laolaolulu** [comment]
> loading

我也发现不对劲,我更新数据应该执行数据更新动画,但还是执行了初始化动画

**Comment by lxfu1** [comment]
> > loading
> 
> 我也发现不对劲,我更新数据应该执行数据更新动画,但还是执行了初始化动画

这个是底层实现的问题， 目前更新走的是 rerender，效果和初始化一样。

**Comment by laolaolulu** [comment]
> > > loading
> > 
> > 
> > 我也发现不对劲,我更新数据应该执行数据更新动画,但还是执行了初始化动画
> 
> 这个是底层实现的问题， 目前更新走的是 rerender，效果和初始化一样。

**Comment by laolaolulu** [comment]
> > > > 装货
> > > 
> > > 
> > > 我也发现不对劲，我更新数据应该执行数据更新动画，但还是执行了初始化动画
> > 
> > 
> > 这个是可行的问题，目前更新走的是rerender，效果和初始化一样。

如果更新也执行初始化动画那我更新频率快就导致了一直是个白板显示

**Comment by wozien** [comment]
这个问题还没解决吧，为啥要close呢？明显数据更新动画有点问题，没有echarts那样丝滑
