### ISSUE TITLE
🐛[BUG]Error: Unknown Component: shape.inner

### ISSUE THREAD

**Issue by yjy0202** [ant-design/ant-design-charts#2640]
### 💻 复现代码 import React from 'react';
import { Pie } from '@ant-design/charts';

const DemoPie: React.FC = () => {
  const data = [
    {
      type: '分类一',
      value: 1,
    },
    {
      type: '分类二',
      value: 2,
    },
    {
      type: '分类三',
      value: 3,
    },
    {
      type: '分类四',
      value: 4,
    },
    {
      type: '分类五',
      value: 5,
    },
    {
      type: '其它',
      value: 6,
    },
  ];
  const config = {
    forceFit: true,
    title: {
      visible: true,
      text: '饼图-图形标签蜘蛛布局',
    },
    description: {
      visible: true,
      text:
        '当把饼图label的类型设置为spider时\uFF0C标签分为两组\uFF0C在图表两侧拉线对齐显示\u3002一般来说\uFF0C蜘蛛布局的label更不容易相互遮挡\u3002',
    },
    radius: 0.8,
    data,
    angleField: 'value',
    colorField: 'type',
    label: {
      type: 'inner',
      offset: '-50%',
      content: '{value}G',
      style: {
        textAlign: 'center',
        fontSize: 14,
      },
    },
  };
  // eslint-disable-next-line react/jsx-props-no-spreading
  return <Pie {...config} />;
};

export default DemoPie;

### © 版本信息 

- ant-design-charts 版本: [e.g.2.1.2]
- 浏览器环境 Chrome
- 开发环境 windows

**Comment by lxfu1** [comment]
版本不对，官网右上角有对应版本信息。
