### ISSUE TITLE
antdesign charts使用地图组件为什么背景地图没有出来？👑 [需求]

### ISSUE THREAD

**Issue by liushunli** [ant-design/ant-design-charts#2641]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

![image](https://github.com/user-attachments/assets/a7cc17ba-c149-47e8-b4e7-70ec9862e24d)

框架用的是umi4
`

import React, { useState, useEffect } from 'react';
import { FlowMap } from '@ant-design/charts';

const DemoDotMap = () => {
  const [data, setData] = useState({ type: 'FeatureCollection', features: [] });

  useEffect(() => {
    asyncFetch();
  }, []);

  const asyncFetch = () => {
    fetch('https://gw.alipayobjects.com/os/antfincdn/SIybYh6xr1/arc.json')
      .then((response) => response.json())
      .then((json) => setData(json))
      .catch((error) => {
        console.log('fetch data failed', error);
      });
  };

    const config = {
      map: {
        type: 'amap',
        style: 'dark',
       // center: [116.60039, 39.9392],
        pitch: 0,
        zoom: 10,
       // token: 'zLhopYPPERGtpGOgimcdKcCimGRyyIsh',
      },
      source: {
        data: data,
        parser: {
          type: 'json',
          x: 'x1',
          y: 'y1',
          x1: 'x',
          y1: 'y',
        },
      },
      autoFit: true,
      shape: 'arc',
      size: 1.5,
      color: {
        field: 'count',
        value: ['rgba(1,124,247,0.9)', 'rgba(230,129,28,0.9)'],
        scale: { type: 'quantize' },
      },
      style: {
        opacity: 0.8,
        segmentNumber: 60,
      },
      animate: {
        interval: 2,
        trailLength: 1,
        duration: 2,
      },
      radiation: {
        color: 'white',
        size: 30,
      },
      label: {
        visible: true,
        field: 'count',
        style: {
          fill: '#000',
          opacity: 0.8,
          fontSize: 10,
          stroke: '#fff',
          strokeWidth: 2,
          textAllowOverlap: false,
          padding: [5, 5],
          textOffset: [0, 35],
        },
      },
      zoom: {
        position: 'bottomright',
      },
      scale: {
        position: 'bottomright',
      },
      layerMenu: {
        position: 'topright',
      },
      legend: {
        position: 'bottomleft',
      },
    }
    return  <div style={{ height: '100%'}}><FlowMap {...config} /></div>;
};

export default DemoDotMap`
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
想要的效果：
![image](https://github.com/user-attachments/assets/7ddef5ac-7bf0-470d-b9d1-c75d164a66cb)

https://l7plot.antv.antgroup.com/examples/flow/flow/#ground-flow

**Comment by lvisei** [comment]
申请并设置高德地图 key

https://github.com/antvis/L7/discussions/1112
