### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by tda1017** [ant-design/ant-design-charts#2642]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
v2版本显示只显示默认样式，更改了网格线为红色不显示，用codebox 0.9.13的charts就可以正常显示
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://github.com/user-attachments/assets/57e80263-d09b-4830-ae3c-40e4a03c0fdf)

### 🏞 期望结果 [描述你原本期望看到的结果]

![image](https://github.com/user-attachments/assets/268761d3-7d59-4aef-ae01-54fec47232be)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
import React, { useState, useEffect } from "react";
import { Line } from "@ant-design/charts";

const LineChart: React.FC = () => {
  const [data, setData] = useState([]);

  useEffect(() => {
    asyncFetch();
  }, []);

  const asyncFetch = () => {
    fetch(
      "https://gw.alipayobjects.com/os/antfincdn/YdLK%24VvSkW/fireworks-sales.json"
    )
      .then((response) => response.json())
      .then((json) => setData(json))
      .catch((error) => {
        console.log("fetch data failed", error);
      });
  };

  const config = {
    data,
    xField: "Date",
    yField: "scales",
    padding: "auto",
    xAxis: {
      type: "timeCat",
      tickCount: 5,
      grid: {
        line: {
          style: {
            stroke: "#ff0000", // 红色网格线颜色
            lineWidth: 2
          }
        }
      },
      label: {
        style: {
          fill: "#ff0000" // 红色标签颜色
        }
      },
      line: {
        style: {
          stroke: "#ff0000" // 红色坐标轴线颜色
        }
      },
      tickLine: {
        style: {
          stroke: "#ff0000" // 红色刻度线颜色
        }
      }
    },
    yAxis: {
      grid: {
        line: {
          style: {
            stroke: "#ff0000", // 红色网格线颜色
            lineWidth: 2
          }
        }
      },
      label: {
        style: {
          fill: "#ff0000" // 红色标签颜色
        }
      },
      line: {
        style: {
          stroke: "#ff0000" // 红色坐标轴线颜色
        }
      },
      tickLine: {
        style: {
          stroke: "#ff0000" // 红色刻度线颜色
        }
      }
    },
    tooltip: {
      showMarkers: true,
      domStyles: {
        "g2-tooltip": {
          backgroundColor: "#000",
          border: "1px solid #333",
          color: "white"
        }
      }
    }
  };

  return <Line {...config} />;
};

export default LineChart;

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境 chrome

**Comment by lxfu1** [comment]
```ts
    axis: {
      x: {
        grid: true,
        gridStrokeOpacity: 1,
        gridStroke: 'red',
        gridLineDash: [0,0],
        labelFill: 'red'
      }
    },
```
