### ISSUE TITLE
需要 x 是连续类型、date类型。

### ISSUE THREAD

**Issue by YH-82** [ant-design/ant-design-charts#2645]
需要 x 是连续类型、date类型。
```ts
    scale: {
      x: {
        range: [0, 1]
      }
    },
```
为什么1.x版本不需要x是连续类型、date类型就可以两端对齐，2.x版本却要做这个限制呢，有没有什么办法，可以使不是这两种类型的数据，也可以两端对齐呢

_Originally posted by @lxfu1 in https://github.com/ant-design/ant-design-charts/issues/2630#issuecomment-2268687616_

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/2644
