### ISSUE TITLE
🐛[BUG] 如何对legend以及tooltip 进行自定义排序

### ISSUE THREAD

**Issue by bingyang519** [ant-design/ant-design-charts#2657]
相关data：
[
      {
        data: '2024-08-13',
        from: '官网',
        value: 2,
      },
      {
        data: '2024-08-13',
        from: '下载页',
        value: 1,
      },
      {
        data: '2024-08-13',
        from: '总量',
        value: 3,
      },
      {
        data: '2024-08-14',
        from: '官网',
        value: 10,
      },
      {
        data: '2024-08-14',
        from: '分享h5',
        value: 13,
      },
      {
        data: '2024-08-14',
        from: '下载页',
        value: 2,
      },
      {
        data: '2024-08-14',
        from: '总量',
        value: 25,
      },
      {
        data: '2024-08-15',
        from: '官网',
        value: 4,
      },
      {
        data: '2024-08-15',
        from: '分享h5',
        value: 18,
      },
      {
        data: '2024-08-15',
        from: '下载页',
        value: 3,
      },
      {
        data: '2024-08-15',
        from: '总量',
        value: 25,
      },
      {
        data: '2024-08-16',
        from: '官网',
        value: 2,
      },
      {
        data: '2024-08-16',
        from: '分享h5',
        value: 27,
      },
      {
        data: '2024-08-16',
        from: '总量',
        value: 29,
      },
      {
        data: '2024-08-17',
        from: '官网',
        value: 5,
      },
      {
        data: '2024-08-17',
        from: '分享h5',
        value: 19,
      },
      {
        data: '2024-08-17',
        from: '下载页',
        value: 1,
      },
      {
        data: '2024-08-17',
        from: '总量',
        value: 25,
      },
      {
        data: '2024-08-18',
        from: '官网',
        value: 7,
      },
      {
        data: '2024-08-18',
        from: '分享h5',
        value: 7,
      },
      {
        data: '2024-08-18',
        from: '下载页',
        value: 1,
      },
      {
        data: '2024-08-18',
        from: '总量',
        value: 15,
      },
      {
        data: '2024-08-19',
        from: '官网',
        value: 8,
      },
      {
        data: '2024-08-19',
        from: '总量',
        value: 8,
      },
    ]

config 如下：
config = {
    data,
    xField: 'data',
    yField: 'value',
    seriesField: 'from',
  };

![444444](https://github.com/user-attachments/assets/beb37232-f344-4a04-9aaf-962e0fc6c261)

如何对legend以及tooltip 进行自定义排序，我需要按 【官网、分享h5、下载页、总量】 排序

**Comment by lxfu1** [comment]
排序数据
