### ISSUE TITLE
这个库跟   - 'ant-design-pro/lib/Charts';  - bizchart - viser啥区别

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design-charts#266]
这个库跟  
- 'ant-design-pro/lib/Charts'; 
- bizchart
- viser
啥关系和区别？ 是不同团队的KPI嘛？

**Comment by lxfu1** [comment]
- Ant Design Charts 和 G2、G2Plot 是一个组的人，长期维护持续更新。
- ant-design-pro/lib/Charts 是基于 G2 直接封装的，新版本已经再推  Ant Design Charts 。
- bizCharts、viser 是其它组的同学基于 G2 来封装的。

**Comment by pkaq** [comment]
antd pro 最新文档里推荐的是 bizchart ；） ， 所以好迷
