### ISSUE TITLE
🧐怎么给面积图不同分段设置不同的颜色

### ISSUE THREAD

**Issue by tangyunfeng12138** [ant-design/ant-design-charts#2660]
### 🧐 想用面积图实现下面的效果
![image](https://github.com/user-attachments/assets/509382d9-6949-4714-882b-c7d9904eb939)

**Comment by lxfu1** [comment]
参考： https://ant-design-charts.antgroup.com/examples/case/interactions/#segmented-line

**Comment by tangyunfeng12138** [comment]
ok，感谢
