### ISSUE TITLE
🐛[BUG] 2.2.1版本引入GroupedColumn报没有找个组件

### ISSUE THREAD

**Issue by Ghh118** [ant-design/ant-design-charts#2668]
![1724756055219](https://github.com/user-attachments/assets/69d7bc6c-78e0-4c6d-a858-4807346c68a5)
我去一层层找了确实没有找个组件

**Comment by lxfu1** [comment]
https://ant-design-charts.antgroup.com/examples/statistics/column/#dodge-padding
