### ISSUE TITLE
🧐[Question] How can I programmatically select an element and set it's state to 'selected'?

### ISSUE THREAD

**Issue by jsteenkamp** [ant-design/ant-design-charts#2669]
I am have column plot with `interaction: { elementSelect: {single: true}}` which enables selecting an interval (column).

I can emit an event to select an element programmatically, where the data object matches my element data:

```
  chart.emit('interval:click', {
      data: {
          data: {
              time: 1722384000000,
              count: 1,
              nodeIds: ['416'],
          },
      }
  });
```
How can I also set the state of the element to 'selected' so that it is the same as when a user clicked on the element?

**Comment by lxfu1** [comment]
https://codesandbox.io/p/sandbox/holy-morning-ngh9gp?file=%2Findex.js%3A40%2C16
