### ISSUE TITLE
图表缩放🧐[问题]

### ISSUE THREAD

**Issue by zhengAnBin** [ant-design/ant-design-charts#267]
### 🧐 问题描述 

Line组件，折线图。
由于显示的数据太多，展示得不够清晰，我希望可以放大或缩小

例如：像地图一样功能。
1，鼠标双击放大，再双击缩小
2，鼠标滚动，向滚动放大，向下滚动缩小

在文档中找到了 slider 的配置，但用户体验十分不好。
也没有找相关API配置，或者是我太粗心忽略相关API配置

可以告诉我应该怎么做吗？
还是说暂时不支持这个功能？
不考虑 slider 下，有比 slider 更好的替代方案吗？

（图标上传不了，很抱歉）请详细一点告诉我，谢谢您

**Comment by lxfu1** [comment]
https://charts.ant.design/demos/line/?type=api

**Comment by zhengAnBin** [comment]
> https://charts.ant.design/demos/line/?type=api

？

**Comment by zhengAnBin** [comment]
> https://charts.ant.design/demos/line/?type=api
还是麻烦您直接告诉怎么相关的配置，文档里的一些描述看不太懂，也不明白一些配置是根我提的问题有关联

**Comment by lxfu1** [comment]
折线图目前没有支持点击缩放，slider 可以配置 start 和 end ， 对于折线图目前没有更好的方案。
- 思路： 算法优化数据，大数据量时对图影响较小的数据可以优化掉，减少数据量，[1，2，2，2，5] => [1, 2, 2, 5]。

**Comment by zhengAnBin** [comment]
> 折线图目前没有支持点击缩放，slider 可以配置 start 和 end ， 对于折线图目前没有更好的方案。
> 
> * 思路： 算法优化数据，大数据量时对图影响较小的数据可以优化掉，减少数据量，[1，2，2，2，5] => [1, 2, 2, 5]。

好的，谢谢您

**Comment by zhengAnBin** [comment]
好的，谢谢您
