### ISSUE TITLE
🧐[Question] Save plot state and re-render from saved state?

### ISSUE THREAD

**Issue by jsteenkamp** [ant-design/ant-design-charts#2672]
Is it possible to save the state of a plot, including any selection (slider) and selected element/s and then re-render the plot from the saved state?

**Comment by lxfu1** [comment]
slider with `slider.x. values: [start, end]， range: 0 ~ 1`, selected refer to https://codesandbox.io/p/sandbox/mutable-thunder-xtkc97?file=%2Findex.js%3A3%2C34

**Comment by jsteenkamp** [comment]
@lxfu1 many thanks - hopefully there is a way to do this using `emit` in the future, I assumed `_context` is 'private'  not intended to be used directly, but this gives me a solution. Thanks again.

**Comment by lxfu1** [comment]
> @lxfu1 many thanks - hopefully there is a way to do this using `emit` in the future, I assumed `_context` is 'private' not intended to be used directly, but this gives me a solution. Thanks again.

See  again.
