### ISSUE TITLE
🧐[问题]  Issue with Accessing Full Data Object in Tooltip in Ant Design Charts v2

### ISSUE THREAD

**Issue by RosaErick** [ant-design/ant-design-charts#2674]
### 🧐

I am currently migrating a project from Ant Design Charts v1.4 to v2 and encountered an issue with the tooltip functionality. In v1.4, I was able to access and display custom fields from the full data object using the customContent option in the tooltip configuration. This allowed me to format and display various data fields that were not directly tied to xField, yField, colorField, or sizeField.

However, after upgrading to v2, it seems that the customContent option is no longer available, and I am unable to access additional fields from the data object within the tooltip. The items array in the tooltip options only provides fields directly associated with the plot configuration, and I am unable to include or format other data properties that are crucial for our use case.

### 💻
Expected Behavior:

I expect to be able to access and display additional fields from the full data object in the tooltip, similar to how it was done in v1.4. The ability to customize the tooltip content with data fields not directly associated with the primary fields is critical for our project.

Steps to Reproduce:

Create a scatter plot in Ant Design Charts v2.
Configure the plot with xField, yField, colorField, and sizeField.
Attempt to access and display additional fields from the data object in the tooltip.
Notice that only the fields directly associated with the primary plot configuration are accessible, and other custom fields are not available.

  const configBubblePlot = {
  data: myData,
  xField: "indiceComp",
  yField: "margem",
  sizeField: "faturamento",
  colorField: "descricao",
  tooltip: {
    // Expectation: to access full data object to display additional fields.
    render: (e, options) => {
      const { title, items } = options;
      console.log(items); // Only primary fields are available
      return `<div>${title}</div>`;
    },
  },
};

The tooltip only receives fields that are directly associated with xField, yField, colorField, and sizeField. Other fields from the data object are not accessible, limiting the customization of tooltip content.

**Comment by MadiAbhilash** [comment]
In a grouped column chart What I am doing to get the full object to customize the tooltip 👇🏻, 

    interaction: {
      tooltip: {
        wait: 300,
        render: (_: unknown, { title, items }: { title: string, items: { name: string, value: number, color: string }[] }) => {
          const item = items[0];

          const obj: ComparisonLatestPriceFlowDataSchema = data.find(o => o[ServerKeys.RANGE] === title && o[ServerKeys.CARRIER] === item[ServerKeys.NAME])!;

          return `<p class="text-[12px] dark:text-white">
                ${labels?.carrier}: <strong style="background: ${item?.color}" class="p-1 text-white rounded">${obj?.[ServerKeys.CARRIER]}</strong></br>
                <strong>${obj?.percent.toFixed(2)}%</strong> represents <strong>${obj?.[ServerKeys?.NO_OF_OBSERVATION]}</strong> observations<br/> of prices between <strong>${obj?.range}</strong> range
               </p>`
        },
      },
    },

**Comment by lxfu1** [comment]
```ts
tooltip:  (...args) => {
  return  {xx}; // something you need.
}

combined:  https://ant-design-charts.antgroup.com/examples/statistics/column/#tooltip
```

**Comment by wenshanzhang** [comment]
> ```ts
> tooltip:  (...args) => {
>   return  {xx}; // something you need.
> }
> 
> combined:  https://ant-design-charts.antgroup.com/examples/statistics/column/#tooltip
> ```

...args的内容，只有event, { title, items }，items只有value，color，name三个字段，如果我需要做一个复杂的tooltip，每一个数据点有多个数据（value1, value2, value3...）需要展示，那现在这个使用示例将完全无法使用，注入数据点完整的数据应该是一个必要的，而不是只提供图表当前用到的数据。
