### ISSUE TITLE
How to show the annotations on top of column in column chart when it is a grouped column chart

### ISSUE THREAD

**Issue by MadiAbhilash** [ant-design/ant-design-charts#2675]
- I am facing an issue with the documentation to know how we can show the annotation on top of a bar when it is a grouped column chart, here I am requesting for an help know it, 

## What currently I have
![image](https://github.com/user-attachments/assets/f15f68bc-6d5a-4396-9225-ad5b3a716020)

## What is Expected ( I need to show an annotations on top of the bar, how can I in grouped bar chart?)
![image](https://github.com/user-attachments/assets/2dae9d8d-aa29-43e2-aa23-7d3c5cb7937a)

**Comment by lxfu1** [comment]
https://ant-design-charts.antgroup.com/examples/statistics/column/#dodge-padding
```ts
    label: {
      position: 'top',
      dy: -10, 
      textBaseline: 'bottom'
    },
```

**Comment by MadiAbhilash** [comment]
sorry for the miss understanding @lxfu1  I need the markers on top of the bars in an grouped column chart,
for example : - 

![image](https://github.com/user-attachments/assets/88ca09fb-94b6-4a8e-bc99-f2ed799047f9)


![image](https://github.com/user-attachments/assets/ebb93aa5-5d65-4d88-a0e5-13df7fd55cb0)
