### ISSUE TITLE
How we can show a marker on top of the column when it is an grouped column chart?

### ISSUE THREAD

**Issue by MadiAbhilash** [ant-design/ant-design-charts#2676]
- Here I need to show the markers on top of the bars, when the column chart is grouped

## what is actual
![image](https://github.com/user-attachments/assets/44e7cc14-c605-4a1f-91ce-b0986c6965ec)

## what is expected (This image has single column but, I need help with grouped column chart to show markers on top)
![image](https://github.com/user-attachments/assets/c3371bb7-dba2-4d71-b3f3-b741a68e9165)

**Comment by lxfu1** [comment]
https://codesandbox.io/p/sandbox/holy-morning-ngh9gp?file=%2Findex.js%3A21%2C25
