### ISSUE TITLE
Is it possible to hide axis and background lines in the Line chart?

### ISSUE THREAD

**Issue by hkhangus** [ant-design/ant-design-charts#2677]
![image](https://github.com/user-attachments/assets/6365cf27-a895-44fa-87a6-f6540330de49)

How do I display only the blue line?

**Comment by AbhilashMadi** [comment]
```typescript
//want to hide x or y axis
axis: {x: {line: false}, y: {line: false}}
```
docs: https://ant-design-charts.antgroup.com/en/options/plots/component/axis

```typescript
//want to hide the grid lines
{grid: false}
```
docs: https://ant-design-charts.antgroup.com/en/options/plots/component/axis#%E7%BD%91%E6%A0%BC%E7%BA%BF
