### ISSUE TITLE
🐛[BUG] Pie chart tooltip without callback with all zero values

### ISSUE THREAD

**Issue by d0ublezer0** [ant-design/ant-design-charts#2681]
Hello! 
Ant plots 2.3.1
if Pie chart has all zero values, tooltip callback is not called.
But if change some value to non zero - callback works fine .

https://codesandbox.io/p/sandbox/upbeat-feather-ddz34g?workspaceId=4a51293e-d490-4101-9876-03eeeb8e7999

<img width="973" alt="image" src="https://github.com/user-attachments/assets/4ace7dac-cf3f-4880-b668-0c3eefc368aa">
<img width="993" alt="image" src="https://github.com/user-attachments/assets/1dccc330-7b99-40b0-ab5f-1fb3c29ec02e">

**Comment by lxfu1** [comment]
Under normal, when the data is all zeros, the chart is not drawn, and the tooltip is meaningless. Since someone previously mentioned the expectation of showing the chart even when it's all zeros, we intercepted the user configuration and made deal with when it's all zeros. These two issues are mutually exclusive~

**Comment by ym-project** [comment]
> Under normal, when the data is all zeros, the chart is not drawn, and the tooltip is meaningless. Since someone previously mentioned the expectation of showing the chart even when it's all zeros, we intercepted the user configuration and made deal with when it's all zeros. These two issues are mutually exclusive~

But pie chart draws, default tooltip works anyway. And we have the case where tooltip interaction works but tooltip callback does't call.
For example
```ts
tooltip: () => ({ hello: 'world' }),
interactions: {
  tooltip: {
    render: (event. { items }) => {
      // without callcak items = [{ color: '', name: '', value: 0 }]
      // with callback items = [{ color: '', hello: 'world' }],
    },
  },
},
```

I think tooltip callback should be called anyway regardless of the values. Data field array is not empty so why tooltip depends on zero values?
