### ISSUE TITLE
🐛[BUG] horizontal lines very faint in dark mode

### ISSUE THREAD

**Issue by riwu** [ant-design/ant-design-charts#2682]
https://ant-design-charts.antgroup.com/en/options/plots/theme/classic-dark
The classicDark mode makes the horizontal lines (that extends from each y-axis value) very faint.  
Can we make it more visible?
![original](https://github.com/user-attachments/assets/14d65ca1-487a-44c5-a299-d05a6ae13d13)

**Comment by lxfu1** [comment]
```ts
    axis: {
      y: {
        gridStrokeOpacity: 1,
        gridLineWidth: 2,
        gridLineDash: [4,0],
        gridStroke: 'red',
      },
    },
```

**Comment by riwu** [comment]
@lxfu1 No I didn't mean that I want the line color to be red.  
The red circle is to highlight the horizontal lines that are faint.
Will the library adjust the color so that the horizontal lines are more visible in dark mode?
