### ISSUE TITLE
🐛[BUG] tooltip如何修改title名称

### ISSUE THREAD

**Issue by rookie-luochao** [ant-design/ant-design-charts#2689]
![tooltip](https://github.com/user-attachments/assets/794bd4b7-25a2-46db-8745-ae9a869648d7)
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
图中value名称如何修改成使用x轴名称('colorField')
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
看图
### 🏞 期望结果 [描述你原本期望看到的结果]
看图
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
看图
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
```ts
    tooltip:{
      items: [{ field: 'height', name: '123' }, {field: 'weight', name: '1234'}]
    }

    tooltip:{
      items: [{ channel: 'y', name: '123' }]
    }
```

**Comment by NiuZhuang** [comment]
> ```ts
>     tooltip:{
>       items: [{ field: 'height', name: '123' }, {field: 'weight', name: '1234'}]
>     }
> 
>     tooltip:{
>       items: [{ channel: 'y', name: '123' }]
>     }
> ```

<img width="746" alt="image" src="https://github.com/user-attachments/assets/edbb9ce0-5967-4836-9c64-700836cef614">
没有效果，解决不了问题

**Comment by echoyl** [comment]
1.直接将数据value键值名修改成中文 学员
2.使用 colorField 参数，但是使用这个后就有颜色区分，使用柱状时效果不好
[colorField](https://ant-design-charts.antgroup.com/zh/examples/statistics/column/#label-text)
如果使用render 那么就没办法使用json配置，无法实现无代码
蹲一个方法

**Comment by rookie-luochao** [comment]
> 1.直接将数据value键值名修改成中文 学员 2.使用 colorField 参数，但是使用这个后就有颜色区分，使用柱状时效果不好 [colorField](https://ant-design-charts.antgroup.com/zh/examples/statistics/column/#label-text) 如果使用render 那么就没办法使用json配置，无法实现无代码 蹲一个方法

建议换一个图表，这个包装的g2plot, 还不如g2plot
