### ISSUE TITLE
🐛[BUG]图标的demo显示有问题

### ISSUE THREAD

**Issue by NnnLillian** [ant-design/ant-design-charts#269]
### 🐛 bug 描述
从官网进入【概览图表】，然后随便选择一个类型的图表，打开下面的 *Open demo in new tab*。 出现的 demo 高度只有 25px

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1.  查看图表概览（以柱状图为例）：https://charts.ant.design/demos/column
2.  随便选择一个图表下面的  *Open demo in new tab* 图标按钮
3.  进入 https://charts.ant.design/~demos/demos-column
整个表都是被压扁的
### 🏞 期望结果 [描述你原本期望看到的结果]
正常显示图表
### © 版本信息
- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境: [Chrome  86.0.4240.111]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/38904256/96974325-a763d400-154b-11eb-91ee-633b7407b7d4.png)

**Comment by lxfu1** [comment]
配置一下 height: 400，下个版本我们统一加上。
