### ISSUE TITLE
🧐[问题] 玉环图如何配置圆环一圈最大的值，已实现自定义控制渲染的比列

### ISSUE THREAD

**Issue by MrMengJ** [ant-design/ant-design-charts#2698]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
玉环图如何配置圆环一圈最大的值，已实现自定义控制渲染的比列

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://codesandbox.io/p/sandbox/vk8cwq?file=%2Findex.js

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/user-attachments/assets/63a5810a-a28a-4e27-8669-ae10ec658806)
如图所示，G2的数据大概是10000左右，占圆环3/4，我现在想将G2显示只占圆环的一半左右，即圆环旋转一圈最大值为20000，这种该怎么设置

**Comment by MrMengJ** [comment]
@mjul @fengmk2 @BANG88 @yesmeck 请问这种有配置么

**Comment by lxfu1** [comment]
maxAngle: 180,

**Comment by lxfu1** [comment]
https://ant-design-charts.antgroup.com/zh/examples/statistics/radial-bar/#round-corner
