### ISSUE TITLE
🧐[问题]饼图自定义图例 legend（legend 是个dom 元素）

### ISSUE THREAD

**Issue by zhaoxiaotao** [ant-design/ant-design-charts#271]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在写需求的时候遇到，饼图并且需要自定义图例的那种，自定义的图例还是个dom元素
自定义图例内容如下：
<Badge text={item.type} />
<Divider  type="vertical"/>
 <Space>{`${item.value}%`}</Space>
 <Space size={24}>{item.value}</Space>
 <Progress percent={item.value} showInfo={false} />

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

目前的方法是 用 const ref = React.useRef(); 得到ref，绑定到Pie上之后，在useEffect里面设置，但是目前没有效果，所以请问下 该如何自定义？

useEffect(() => {
    console.log(ref.current.chart.legend,pieData, 'ref');
    ref.current.chart.legend({
      useHtml: true,
      itemTpl: (value, color, checked, index) => {
      checked = checked ? 'checked' : 'unChecked';
      return (
        <div>
          <Badge color="#f50" text={value} />
          <Divider  type="vertical"/>
          <Space>{`${value}%`}</Space>
          <Progress percent={value} showInfo={false} />
        </div>
      );
    },// 可选，用户设置的图例项 html 模板，默认提供的模板不满足要求时使用
    });
  }, []);

**Comment by zhaoxiaotao** [comment]
自定义图例dom 元素如下
     <div>
          <Badge color="#f50" text={value} />
          <Divider  type="vertical"/>
          <Space>{`${value}%`}</Space>
          <Progress percent={value} showInfo={false} />
        </div>

**Comment by lxfu1** [comment]
参考下： https://codesandbox.io/s/condescending-glitter-y8unk?file=/src/App.js  或者使用 DOM 模拟

**Comment by zhaoxiaotao** [comment]
> 参考下： https://codesandbox.io/s/condescending-glitter-y8unk?file=/src/App.js 或者使用 DOM 模拟

这个今天看了 满足不了需求  用dom 模拟的话 用 const ref = React.useRef(); 和 useHtml 就可以了吧？

**Comment by lxfu1** [comment]
没有useHtml这个用法，你在哪里看到的文档~

**Comment by zhaoxiaotao** [comment]
> 没有useHtml这个用法，你在哪里看到的文档~

没找到正式的文档，在网上搜索的时候看到的. 我现在写了一个自定义的图例例子，但是使用chart.filter的时候 没有作用  能麻烦帮忙看下吗？  地址：https://codesandbox.io/s/awesome-jones-yj5hv?file=/src/App.js

**Comment by lxfu1** [comment]
调用一下 render
```ts
      pieChart.filter("type", (val) => {
        return filteredLegendData.indexOf(val) > -1;
      });
      pieChart.render();
```
