### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by printfshen** [ant-design/ant-design-charts#272]
### 🧐 问题描述 
![image](https://user-images.githubusercontent.com/26736621/97285516-4571da00-187d-11eb-885f-d7cec55bd44c.png)
配置如下 为什么会出现如图情况
`
配置文件
  const config = {
    data: [ {
            "id": 15,
            "title": "CSS秘笈",
            "count": 1
        },
        {
            "id": 14,
            "title": "Web前端开发",
            "count": 11
        }],
    width: 600,
    height: 300,
    wordField: 'title',
    weightField: 'count',
    wordStyle: {
      fontFamily: 'Verdana',
      fontSize: [20, 60],
    },
  }
`

**Comment by lxfu1** [comment]
配置没生效吧,  在上提供一下复现代码 https://codesandbox.io/

**Comment by printfshen** [comment]
https://codesandbox.io/s/nice-germain-c612w?file=/src/App.js   title  和 count 对不上

**Comment by printfshen** [comment]
![image](https://user-images.githubusercontent.com/26736621/97379802-9d9df000-1900-11eb-8067-e4ef063be0fb.png)
这个也是遇到了

**Comment by zhangzhonghe** [comment]
该问题以修复，请等待发布最新的版本！

**Comment by zhangzhonghe** [comment]
@printfshen 周五会发布新版本，敬请期待~
