### ISSUE TITLE
🐛[BUG] [Security] Deprecated dependencies on @ant-design/plots

### ISSUE THREAD

**Issue by sabelaV** [ant-design/ant-design-charts#2724]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
I want to notice that the latest version of "@ant-design/plots": "^2.3.2" has a deprecated dependency, it´s rollup, it depends on fmin@0.0.2. This dependency: fmin@0.0.2 depends on rollup@0.25.8. This is a very old version of this library and this means introducing vulnerabilities in the project. Theese libraries has been installed also with npm install --omit=optional command.  Could you review this issue, please? Thanks in advance.

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by archisvaze** [comment]
```
rollup  <2.79.2
Severity: high
DOM Clobbering Gadget found in rollup bundled scripts that leads to XSS - https://github.com/advisories/GHSA-gcx4-mw62-g8wm
fix available via npm audit fix
node_modules/rollup
  fmin  *
  Depends on vulnerable versions of rollup
  node_modules/fmin
    @antv/g2plot  2.3.33 - 2.4.32
    Depends on vulnerable versions of fmin
    node_modules/@antv/g2plot

18 high severity vulnerabilities
```

**Comment by lxfu1** [comment]
https://github.com/benfred/fmin/issues/13 ?

**Comment by alii13** [comment]
Any possible fix for this? facing the same issue

**Comment by allisonphillips** [comment]
Might want to add [Security] after bug in your issue title for more visibility, like in https://github.com/ant-design/ant-design-charts/issues/1930

**Comment by claudio-park-here** [comment]
Same issue here
