### ISSUE TITLE
Assistance: How to add custom tooltip to Waterfall Chart

### ISSUE THREAD

**Issue by kunalshewale** [ant-design/ant-design-charts#273]
Hi,

I need to customise the tooltip for the Waterfall Chart. I have tried to use `customContent` but unable to get the desired result as HTMLElement is shown as norma string.

Config:
![image](https://user-images.githubusercontent.com/7191378/97337834-c2fe1000-18a6-11eb-916d-7459fa05b818.png)

Output:
![image](https://user-images.githubusercontent.com/7191378/97338036-fe004380-18a6-11eb-8ce4-72fabff248a1.png)

Can you please let me know the proper way to do this.

**Comment by lxfu1** [comment]
https://charts.ant.design/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip
