### ISSUE TITLE
🐛[BUG]在饼图中点击legend会导致annotations消失

### ISSUE THREAD

**Issue by 2098616238** [ant-design/ant-design-charts#2731]
### © 版本信息

- ant-design-charts 版本: [e.g. 2.1.2]
- 浏览器环境 [Google]
- 开发环境 [e.g. mac mini]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
一开始情况如下:
![image](https://github.com/user-attachments/assets/c8ad99cb-b55b-453b-a68b-893f1609f3f2)
点击图例后导致注解消失:
![image](https://github.com/user-attachments/assets/df37cafe-32b6-4aa1-8a94-43748f52002d)

**Comment by TaoTao2deng** [comment]
解决了吗 ？

**Comment by lxfu1** [comment]
`data: []`
![image](https://github.com/user-attachments/assets/645142d9-0e8d-4b23-9225-9a16fd995a40)
