### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by giovannicuce** [ant-design/ant-design-charts#2738]
I try to use this example https://ant-design-charts.antgroup.com/en/examples/relations/organization-chart/#horizontal

But the component OrganizationChart doesn't exist, why?

"@ant-design/charts": "^2.2.1",
"@ant-design/graphs": "^1.4.2",

**Comment by yvonneyx** [comment]
`OrganizationChart` is a graph component provided by `@ant-design/graphs`. It is currently in the beta stage and is scheduled for official release on 11.22. We welcome early feedback, and you can install it via `@ant-design/graphs@2.0.0-beta.4`.

**Comment by giovannicuce** [comment]
Thank you
