### ISSUE TITLE
🧐[问题]slider does not work for DualAxes

### ISSUE THREAD

**Issue by gww2020** [ant-design/ant-design-charts#274]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
DualAxes graph does not display slider with slider configgged. I wonder if there is any issue with my config?
Please see attached js code
[DemoDualAxes.txt](https://github.com/ant-design/ant-design-charts/files/5448024/DemoDualAxes.txt)

**Comment by lxfu1** [comment]
Not supported,  next version.

**Comment by lxfu1** [comment]
update.

**Comment by wengsj11** [comment]
> Not supported.

同问，现在是否已经支持slider？

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/489
