### ISSUE TITLE
Sort in OrganizationChart

### ISSUE THREAD

**Issue by giovannicuce** [ant-design/ant-design-charts#2743]
HI,

i installed this library: "@ant-design/graphs": "2.0.0-beta.4"

I use the component OrganizationChart. My question is: how are nodes and child nodes sorted? 
For example, i have 3 nodes: A, B and C where B and C are children of A. how B and C are sorted?

**Comment by yvonneyx** [comment]
As mentioned in #2746 , you can adjust it using [layout.nodeorder](https://g6.antv.antgroup.com/en/api/layouts/antv-dagre-layout#nodeorder).

**Comment by giovannicuce** [comment]
I have this nodes:

![Screenshot 2024-10-24 alle 14 12 20](https://github.com/user-attachments/assets/af6fd404-bdae-49d6-be77-c7d5a53d94d6)

after insert the nodeOrder there is a issue

![Screenshot 2024-10-24 alle 14 12 45](https://github.com/user-attachments/assets/2001a734-db6b-4775-8390-bbc0ed8cb3f2)

The nodeOrder contains an array of string id of elements

How i can fix?

**Comment by giovannicuce** [comment]
I don't know why, but now it's working

**Comment by yvonneyx** [comment]
What effect are you looking for?

Would sorting the data before rendering meet your needs?

If possible, could you provide a mockup or example image to help me better understand your needs 😊😊
