### ISSUE TITLE
"@ant-design/graphs": "2.0.0-beta.4" Organization Chart, prop onChange of x and y

### ISSUE THREAD

**Issue by giovannicuce** [ant-design/ant-design-charts#2746]
Hi,

I need a prop in library "@ant-design/graphs": "2.0.0-beta.4" and component OrganizationChart.

Is there a prop for intercept change of position x and y of chart by user?

**Comment by yvonneyx** [comment]
Are you looking to adjust the layout results? Currently, the organizational chart uses the Dagre layout, which you can check via [this link](https://g6.antv.antgroup.com/en/api/layouts/antv-dagre-layout).

We are also actively preparing the API documentation and will update it on the official website as soon as possible.

**Comment by giovannicuce** [comment]
I set props x and y, because I need to set it. But I have situation where I change the data of charta and the chart come back to first position of x and y. I need a props to intercept the user's movement to set x and y with the new value, so the chart don't move

**Comment by yvonneyx** [comment]
This is because each data change triggers a render, which results in a redraw and layout. You can use the graph's API to handle data and call `graph.draw()` to perform drawing without redoing the layout.
