### ISSUE TITLE
🧐[问题] Can we have different point config for lines in DualAxes ?

### ISSUE THREAD

**Issue by gww2020** [ant-design/ant-design-charts#278]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
From DualAxes Demo, I see we can have different  lineStyle config like this:
      lineStyle: ({ name }) => {
        if (name === 'a') {
          return {
            lineDash: [2, 2],
            opacity: 1,
          };
        }
        return { opacity: 0.5 };
      },

Can we have similar different point config for different lines in DualAxes?

**Comment by lxfu1** [comment]
```ts
geometryOptions: [
    {
      geometry: 'line', // line 1
    },
    {
      geometry: 'line',
      lineStyle: {
        lineWidth: 2,
        stroke: '#FAA219',
      },
      point: {
        style: (item)=> {
          if(item?.time === 'xxx'){
              return {
                fill: 'blue'
              }
          }
          return {
            fill: 'red'
          }
        }
      }
    },
  ],
```

**Comment by juxiezuo-cyh** [comment]
为什么shape函数拿不到点的全部数据
