### ISSUE TITLE
🧐折线图自定义标题字体样式不生效

### ISSUE THREAD

**Issue by Makecodeeasy** [ant-design/ant-design-charts#2783]
### 💻 

示例代码: 
style: {
      lineWidth: 2,
      titleFontText: '实例',
      titleFontSize: 20,
      titleFontWeight: 600,
    },

代码地址： 
https://codesandbox.io/p/sandbox/heuristic-waterfall-lcgr6y?file=%2Findex.js%3A33%2C20

**Comment by lxfu1** [comment]
```ts
    title: {
      title: '实例',
      subtitle: 'a title example',
      titleFontSize: 30
    },
```
