### ISSUE TITLE
🐛[BUG] 折线图缺少数据时出现系列和提示颜色错乱

### ISSUE THREAD

**Issue by TimChen44** [ant-design/ant-design-charts#2787]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在双轴图中如果发生折线图的数据不完整时，发现是系列中标记的颜色和鼠标悬停提示的颜色错乱问题

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

![image](https://github.com/user-attachments/assets/00dad146-3acc-4247-947d-b044d017af70)

### 🏞 期望结果 [描述你原本期望看到的结果]

系列中的颜色和鼠标悬停的颜色应该保持一致

### © 版本信息

- ant-design-charts 版本: 2.0.0
- 浏览器环境 Microsoft Edge 版本 131.0.2903.63

**Comment by lxfu1** [comment]
数据类别不能丢失，值可以速 null
