### ISSUE TITLE
🧐[问题]如何才能使X轴的日期和折线图上的数据对应上

### ISSUE THREAD

**Issue by sangxiaolong** [ant-design/ant-design-charts#2788]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
原始数据中有date字段，格式为“2024-05-01”，为了使x轴能连续显示，对xField字段进行处理转成了date类型 xField={(d: any) => new Date(d.date)}，但是折线图上显示的都加了8小时，与x轴的数据对应不上

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![Screen Shot 2024-11-29 at 9 48 30 AM](https://github.com/user-attachments/assets/b917a77a-c20d-4d95-a653-3d671101f7b9)

**Comment by lxfu1** [comment]
数据问题，提供复现再打开，没有data无法排查。
