### ISSUE TITLE
🐛[BUG]style config function does not work for point config with DualAxes

### ISSUE THREAD

**Issue by gww2020** [ant-design/ant-design-charts#279]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
all points are filled with yellow with the following config. 

 point: {           
        style: ({name}) => {
          if(name === 'a'){
              return {   fill: 'blue'    }
          }
          return {  fill: 'yellow' }
        }
      },
### 🏞 期望结果 [描述你原本期望看到的结果]
the points on line 'a' should be filled with blue

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
[DemoDualAxes.txt](https://github.com/ant-design/ant-design-charts/files/5455815/DemoDualAxes.txt)

**Comment by lxfu1** [comment]
Tomorrow next version.

**Comment by lxfu1** [comment]
V: 1.0.3
