### ISSUE TITLE
organization-chart - control default expand collapsed nodes 

### ISSUE THREAD

**Issue by MithranKesavan** [ant-design/ant-design-charts#2790]
Hi,

I want to control expand/collapsed nodes and edges by data/function. 

https://ant-design-charts.antgroup.com/en/examples/relations/organization-chart#horizontal

**Comment by yvonneyx** [comment]
By data:

```ts
const data = { nodes: 
    [{
        id: 'node1' , 
        children: [ 'node2', 'node3' ], 
        style: { collapsed: true },
    }]
}
```

By interaction:

```js
export default () => {
    const ref = useRef();

    useEffect(() => {
        const graph = ref.current;
        graph.expandElement('xxx');
   }, [ref.current])

    return <OrganizationChart onReady={(graph) => { ref.current = graph }} />
}
```

More api refers to [G6](https://g6.antv.antgroup.com/en/api/graph/method#graphcollapseelementid-options)

**Comment by MithranKesavan** [comment]
Hi,
Thanks for quick response.

Partially works. Only change the expand collapse icon. but child nodes are displaying..

![image](https://github.com/user-attachments/assets/ceb05a4b-3115-4b5a-8f76-0ccc6f8d0ed6)



Here is my code 

import React, { useRef, type FunctionComponent, useEffect, useState, Children } from "react";
import { OrganizationChart, RCNode, CollapseExpandIcon } from "@ant-design/graphs";
// import { GraphData } from "@ant-design/";

const { OrganizationChartNode } = RCNode;
const { ArrowCountIcon } = CollapseExpandIcon;

export const OrgChart2: FunctionComponent<any> =
  (props) => {

    const [data, setData] = useState<any>({
      nodes: [
        {
          "id": "0",
          "data": {
            "email": "ejoplin@yoyodyne.com",
            "fax": "555-0101",
            "name": "Eric Joplin",
            "phone": "555-0100",
            "position": "Chief Executive Officer",
            "status": "online"
          },
          Children:["1","17","18","19"],        
        },
        {
          "id": "1",
          "data": {
            "email": "groberts@yoyodyne.com",
            "fax": "555-0101",
            "name": "Gary Roberts",
            "phone": "555-0100",
            "position": "Chief Executive Assistant",
            "status": "busy"
          },
          Children:["2"],        
          style:{
            collapsed:true 
          }
        },
        {
          "id": "2",
          "data": {
            "email": "aburns@yoyodyne.com",
            "fax": "555-0103",
            "name": "Alex Burns",
            "phone": "555-0102",
            "position": "Senior Executive Assistant",
            "status": "offline"
          },
          style:{
            collapsed:true 
          }
        },
        {
          "id": "4",
          "data": {
            "email": "msmith@yoyodyne.com",
            "fax": "555-0115",
            "name": "Mary Smith",
            "phone": "555-0114",
            "position": "Finance Manager",
            "status": "busy"
          }
        },
        {
          "id": "5",
          "data": {
            "email": "bwhite@yoyodyne.com",
            "fax": "555-0117",
            "name": "Bob White",
            "phone": "555-0116",
            "position": "HR Manager",
            "status": "online"
          }
        },
        {
          "id": "6",
          "data": {
            "email": "jjones@yoyodyne.com",
            "fax": "555-0119",
            "name": "John Jones",
            "phone": "555-0118",
            "position": "IT Manager",
            "status": "offline"
          }
        },
        {
          "id": "7",
          "data": {
            "email": "klee@yoyodyne.com",
            "fax": "555-0121",
            "name": "Karen Lee",
            "phone": "555-0120",
            "position": "Marketing Manager",
            "status": "online"
          }
        },
        {
          "id": "8",
          "data": {
            "email": "dmiller@yoyodyne.com",
            "fax": "555-0123",
            "name": "David Miller",
            "phone": "555-0122",
            "position": "Sales Manager",
            "status": "busy"
          }
        },
        {
          "id": "9",
          "data": {
            "email": "rjoe@yoyodyne.com",
            "fax": "555-0125",
            "name": "Rachel Joe",
            "phone": "555-0124",
            "position": "Operations Manager",
            "status": "offline"
          }
        },
        {
          "id": "10",
          "data": {
            "email": "tadams@yoyodyne.com",
            "fax": "555-0127",
            "name": "Tom Adams",
            "phone": "555-0126",
            "position": "Product Manager",
            "status": "online"
          }
        },
        {
          "id": "11",
          "data": {
            "email": "wbrown@yoyodyne.com",
            "fax": "555-0129",
            "name": "Will Brown",
            "phone": "555-0128",
            "position": "Customer Support Manager",
            "status": "busy"
          }
        },
        {
          "id": "12",
          "data": {
            "email": "dmartin@yoyodyne.com",
            "fax": "555-0131",
            "name": "Diana Martin",
            "phone": "555-0130",
            "position": "Compliance Officer",
            "status": "offline"
          }
        },
        {
          "id": "13",
          "data": {
            "email": "jwilson@yoyodyne.com",
            "fax": "555-0133",
            "name": "Jim Wilson",
            "phone": "555-0132",
            "position": "Legal Counsel",
            "status": "online"
          }
        },
        {
          "id": "14",
          "data": {
            "email": "charris@yoyodyne.com",
            "fax": "555-0135",
            "name": "Cathy Harris",
            "phone": "555-0134",
            "position": "Procurement Manager",
            "status": "busy"
          }
        },
        {
          "id": "15",
          "data": {
            "email": "eblack@yoyodyne.com",
            "fax": "555-0137",
            "name": "Evan Black",
            "phone": "555-0136",
            "position": "Logistics Manager",
            "status": "offline"
          }
        },
        {
          "id": "16",
          "data": {
            "email": "ywang@yoyodyne.com",
            "fax": "555-0139",
            "name": "Yvonne Wang",
            "phone": "555-0138",
            "position": "Research and Development Manager",
            "status": "online"
          }
        },
        {
          "id": "17",
          "data": {
            "email": "jsanchez@yoyodyne.com",
            "fax": "555-0141",
            "name": "Juan Sanchez",
            "phone": "555-0140",
            "position": "Chief Technology Officer",
            "status": "busy"
          }
        },
        {
          "id": "18",
          "data": {
            "email": "mjones@yoyodyne.com",
            "fax": "555-0143",
            "name": "Molly Jones",
            "phone": "555-0142",
            "position": "Chief Financial Officer",
            "status": "offline"
          }
        },
        {
          "id": "19",
          "data": {
            "email": "rking@yoyodyne.com",
            "fax": "555-0145",
            "name": "Richard King",
            "phone": "555-0144",
            "position": "Chief Operating Officer",
            "status": "online"
          }
        }
      ],
      edges: [
        {
          "source": "0",
          "target": "1"
        },
        {
          "source": "1",
          "target": "2",
          style:{
            collapsed:true 
          }
        },
        {
          "source": "0",
          "target": "17"
        },
        {
          "source": "0",
          "target": "18"
        },
        {
          "source": "0",
          "target": "19"
        },
        {
          "source": "17",
          "target": "6"
        },
        {
          "source": "17",
          "target": "16"
        },
        {
          "source": "18",
          "target": "4"
        },
        {
          "source": "18",
          "target": "12"
        },
        {
          "source": "19",
          "target": "9"
        },
        {
          "source": "19",
          "target": "15"
        },
        {
          "source": "4",
          "target": "5"
        },
        {
          "source": "4",
          "target": "10"
        },
        {
          "source": "5",
          "target": "8"
        },
        {
          "source": "6",
          "target": "11"
        },
        {
          "source": "9",
          "target": "7"
        },
        {
          "source": "15",
          "target": "13"
        },
        {
          "source": "15",
          "target": "14"
        }
      ]
    });

    const refGraph = useRef<any | null>(null);

    const onChartReady = (graph: any) => {
      console.log("on Ready");
      refGraph.current=graph;
      console.log(graph);
      //debugger;
    };

    const onChartInit = (graph: any) => {
      refGraph.current=graph;
    };

    const transforms = (prev: any) => [
      ...prev.filter((transform: any) => transform.type !== 'collapse-expand-react-node'),
      {
        ...prev.find((transform: any) => transform.type === 'collapse-expand-react-node'),
        enable: true,
        //  iconRender: (isCollapsed, data) =>{
        //    return <ArrowCountIcon style={{ display: 'flex' }} graph={refGraph.current} data={data} isCollapsed={isCollapsed} />;
        //  },
        iconOffsetY: 12
      },
    ];

    const onButtonClick=()=>{
      if(refGraph.current){
        
      }
    };


    return (
      <div>
        <button id="btnExpandCollapse" onClick={onButtonClick} value="Click" name="Click" >test</button>
      
      <OrganizationChart
        autoFit="view"
        onInit={onChartInit}
        onReady={onChartReady}
        data={data}
        node={{
          style: {
            //collapsed:(d)=>{ console.log(d); return true},
             component: (d:any) => {
            //  // console.log(d);

               const { name, position, status } = d.data || {};
               const isActive = d.states?.includes('active');
               return <OrganizationChartNode name={name} position={position} status={status} isActive={isActive} />;
            //   return (<div> <span>{name}</span> </div>);
             },
            size: [240, 80],
            //direction: "in",
            //badgeFontSize: 30
          },
        }}
        layout={{
          type: 'dagre',
          nodesep: 20,
          ranksep: 60,
        }}
        edge={{
          style: {
            collapsed:true,
            lineWidth: 2,
            radius: 15,
            endArrow: true
          }
        }}
        transforms={transforms}
      />
      </div>);
  };

**Comment by MithranKesavan** [comment]
Thanks for quick response. It works...
:)
