### ISSUE TITLE
🧐[问题] How to use Donut plot with statistics dynamic like version 1.x in version 2.x?

### ISSUE THREAD

**Issue by aseph8083** [ant-design/ant-design-charts#2794]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
How to use Donut plot with statistics dynamic like version 1.x in version 2.x?
[https://ant-design-charts-v1.antgroup.com/en/examples/pie/donut/#statistics](https://ant-design-charts-v1.antgroup.com/en/examples/pie/donut/#statistics)

**Comment by lxfu1** [comment]
https://codesandbox.io/p/sandbox/dreamy-carson-9yygn2?file=%2Findex.js%3A61%2C10
