### ISSUE TITLE
👑 [需求] 找个正常人写使用文档

### ISSUE THREAD

**Issue by wycnewu** [ant-design/ant-design-charts#2810]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/user-attachments/assets/45060a5c-e5ab-4e72-b0c0-765378a2bbac)
用了一上午时间，都没搞明白怎么把legend从默认的方框改成圆圈；
文档写的DisplayObject包含哪些值？看起来是个Object类型，为什么默认值又是String?

**Comment by lxfu1** [comment]
文档更新计划已经在推进了^:_:^
```ts
    legend: {
      color: {
        itemMarker: 'circle',
      },
    },
```

**Comment by wycnewu** [comment]
![image](https://github.com/user-attachments/assets/203d7595-2e29-4d47-a7a2-1b2d364e76d3)
![image](https://github.com/user-attachments/assets/3bd1bd7f-da73-4d1a-b8d8-27104bba9537)
并不好使

**Comment by wycnewu** [comment]
![image](https://github.com/user-attachments/assets/e1ef0c49-5b19-492f-872d-c8e94b986bad)
![image](https://github.com/user-attachments/assets/a58216e1-81ef-453a-a204-f62e0e95b381)
貌似并不好使
