### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design-charts#2811]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
这个文本溢出的是通过什么参数配置的，看了半天文档也没找到。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

`<Pie data={policyMoneyType}
                                 height={250}
                                 angleField={'value'}
                                 colorField={'name'}
                                 legend={{
                                     color: {title: false, position: 'rightTop', rowPadding: 5},
                                     position: 'right',
                                     itemName: {style: {fontSize: 12}},
                                 }}
                                 radius={0.85}
                                 label={{type: 'inner', style: {opacity: 0}}}
                                 title={'金额'}
                            />`

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://github.com/user-attachments/assets/4aefad34-30f7-4793-9f28-fb3825f257b5)

**Comment by lxfu1** [comment]
正常会默认向右填充的，如果配置了 padding ，可以结合 callback 处理一下。

```ts
    legend: {
      color: {
        position: 'right',
        itemLabelText: () => 'xx'
      },
    },
```
