### ISSUE TITLE
🧐[问题] ant-design-charts和G2 Plot是什么关系 我该用哪个？

### ISSUE THREAD

**Issue by BluesVN** [ant-design/ant-design-charts#291]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
ant-design-charts和G2 Plot是什么关系 我该用哪个？

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
我需要基于一个图表库做二次封装 ant-design-charts、G2 Plot、还是G2？

**Comment by lxfu1** [comment]
G2 -> G2Plot -> ant-design-charts,  ant-design-charts 是 G2Plot 的 react 版本， G2 功能比较强大。

**Comment by BluesVN** [comment]
> G2 -> G2Plot -> ant-design-charts, ant-design-charts 是 G2Plot 的 react 版本， G2 功能比较强大。

React技术栈直接用G2Plot就行了吧

**Comment by lxfu1** [comment]
React 技术栈推荐 Ant Design Charts， 功能和 G2Plot 是同步的，开发也是一波人。

**Comment by 1990jtf** [comment]
> React 技术栈推荐 Ant Design Charts， 功能和 G2Plot 是同步的，开发也是一波人。

解决了我心中的疑惑！

**Comment by BluesVN** [comment]
> React 技术栈推荐 Ant Design Charts， 功能和 G2Plot 是同步的，开发也是一波人。

我看到ant design pro的文档中还写着推荐使用bizcharts，看来后面都要换成Ant Design Charts了，我现在已经开始使用了。

**Comment by devsvc** [comment]
那么，和bizcharts又是什么关系呢。。。

**Comment by Me-Momo** [comment]
关于 G2、G2Plot、ant-design-charts 的关系，可以看下这篇文章：https://www.yuque.com/antv/g2plot/iqimgm
