### ISSUE TITLE
👑 [需求] 可以把 heatmap 加回来吗？

### ISSUE THREAD

**Issue by bbtfr** [ant-design/ant-design-charts#292]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

看到这个 #202 把 heatmap 移除了，但看起来 2.0.5 以后 g2plot 已经重新实现了 heatmap
可以把 heatmap 加回来吗？

**Comment by lxfu1** [comment]
好的  今晚加上

**Comment by bbtfr** [comment]
太靠谱了 💯

**Comment by lxfu1** [comment]
> 太靠谱了 💯

Heatmap  G2Plot   底层有bug，修复了还没发布。 代码昨天就添加了， 不想透露有明显bug 的版本，谅解一下。 https://github.com/ant-design/ant-design-charts/blob/docs/apis/src/heatmap/index.tsx

**Comment by lxfu1** [comment]
1.0.4
