### ISSUE TITLE
🧐[问题]how to config point size by series with DualAxes ?

### ISSUE THREAD

**Issue by gww2020** [ant-design/ant-design-charts#293]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
With v1.0.3, the following config displays point size 3 for all lines. I wonder if this is the correct way to config?

 point: {              
        size: (name) => {
          if(name === 'a'){
            return 10;
          }
          return 3;
        }
      },

**Comment by lxfu1** [comment]
Point size params can't be specified.

**Comment by gww2020** [comment]
according to your document, it can be specified for Line, size: (x, y, series) => number. I wonder if you can make it work like point style?

**Comment by lxfu1** [comment]
https://codesandbox.io/s/fancy-bird-4sxii?file=/App.tsx

**Comment by gww2020** [comment]
the above example shows size is same for all series. what I want to achieve is something like this, which doesn't work.
size: (item) => {
        if (item.type === "register") 
          return 10
        return 3},

**Comment by lxfu1** [comment]
Add rawFields
```ts
    rawFields: ['type'],
    point: {
      size: (item) => {
        if (item.type === "register") {
          return 4;
        }
        return 2;
      },
    },
```
