### ISSUE TITLE
🧐[问题]DualAxes graph messed up after upgrade to v1.0.3

### ISSUE THREAD

**Issue by gww2020** [ant-design/ant-design-charts#294]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
My DualAxes graph contains  three lines and one bar, which works fine with v1.0.0. It's messed up to the graph below after I upgraded to v1.0.3.
![messedupGraph](https://user-images.githubusercontent.com/66972355/98044286-a1e07680-1df4-11eb-8bea-2ee6c992f55d.png)

Here is my config for this graph:
 config = {
        data: [mydata, mydata],
        height: 300,
        xField: 'time',
        yField: ['price','execQty'],
        legend: {       
          position: 'bottom',
        }, 
        geometryOptions: [        
          {
            geometry: 'line',
            seriesField: 'type',           
            color:['red','green','grey'],
            lineStyle: {
              lineWidth: 1,
            },
          },
          { geometry: 'column',
            color:'blue', 
            columnWidthRatio: 0.1,
          }
        ],      
      };

Then I rolled back to v1.0.0, but got the same result. I wonder where could go wrong?

**Comment by lxfu1** [comment]
1.0.4
