### ISSUE TITLE
🐛[BUG]环形图在只有1个type时，鼠标移上去，显示会出问题

### ISSUE THREAD

**Issue by Yuiffy** [ant-design/ant-design-charts#295]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
看截图，鼠标移上去圈就飞了

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
```
const donutConfig = {
  autoFit: true,
  label: {
    type: "spider",
    content: '{name}\n{value}',
  },
  radius: 0.7,
  innerRadius: 0.6,
  appendPadding: 20,
  angleField: "value",
  colorField: "type",
  statistic: {
    title: {
      formatter: (data, datum) => {
        var getDefaultContent = function (data, datum) {
          if (data) return data.type;
          else return '总计';
        };
        return getDefaultContent(data, datum);
      }
    },
  },
  interactions: [{ type: 'pie-statistic-active' }],
};

const donutData = [{
        type: '一种分类',
        value: count + 100
      }];
```
```
<Pie {...donutConfig} data={donutData} />
```

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/8912753/98066748-ddca1900-1e92-11eb-86af-177e5015a180.png)

**Comment by lxfu1** [comment]
update 试试

**Comment by Yuiffy** [comment]
1.0.3升到1.0.6未解决。
应该是环图+蜘蛛布局标签 会出现。我先暂时不用环图，改用一般的饼图。

下面附gif
![环状图bug](https://user-images.githubusercontent.com/8912753/98777273-657fcc80-242b-11eb-8d53-bb2a47fac7de.gif)

**Comment by lxfu1** [comment]
interactions: [{ type: 'pie-statistic-active' }] 引起的。

**Comment by Me-Momo** [comment]
在 G2Plot 上没有复现这个问题，可以提供一个复现场景吗

**Comment by Fengfa101126** [comment]
这个问题 最后怎么解决的呢，我这边也遇到了
