### ISSUE TITLE
🐛[BUG] chartRef not work

### ISSUE THREAD

**Issue by jaredleechn** [ant-design/ant-design-charts#296]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

chartRef 没有执行

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://riddle.alibaba-inc.com/riddles/365f8ad1

### © 版本信息

- ant-design-charts 版本: 1.0.3

**Comment by lxfu1** [comment]
1.0.4
