### ISSUE TITLE
[BUG] Facing an issue in Funnel chart

### ISSUE THREAD

**Issue by adityasingh931** [ant-design/ant-design-charts#297]
![FunnelChartIssue](https://user-images.githubusercontent.com/36739455/98088116-14aa2a00-1ea7-11eb-8647-8091fc1af8fe.png)

**Comment by lxfu1** [comment]
Provide a online demo.  https://codesandbox.io/s/serene-beaver-b7s4b?file=/src/App.js

**Comment by adityasingh931** [comment]
Here is the issue with the Funnel chart https://codesandbox.io/s/trusting-hugle-h4rgu?file=/Funnel.js  this code will work with other charts example: Line chart etc.

The Funnel chart issue #297 got fixed after updating the version from "^0.9.10" to "^1.0.7"
