### ISSUE TITLE
🐛[BUG] Gauge bad render

### ISSUE THREAD

**Issue by vinceplayer** [ant-design/ant-design-charts#302]
🐛 bug In the official documentation the gauge element is not very visible, even in the official codesandboxes.

### © 版本信息

- ant-design-charts 版本: [e.g. 1.0.3]
![image](https://user-images.githubusercontent.com/19310863/98124425-77092780-1eb3-11eb-8f8f-1d0a0b39dd5d.png)
https://codesandbox.io/s/93pfq linked in the docs of gauge

**Comment by lxfu1** [comment]
```ts
 const config = {
    width: 600,
    height: 400,
    percent: 0.65,
    range: { color: ['l(0) 0:#5d7cef 1:#e35767'] },
  };
```
