### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by zhaoxiaotao** [ant-design/ant-design-charts#303]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
有三个疑问需要解答下
1、在用折线图的时候 时间格式为  YYYYMMDD 这种格式 在展示的时候 没有按照时间顺序展示，设置了 
aAxis: { tickMethod: ' time-cat' } 没有用，这是为什么呢？

2、折线图的X轴显示的样子
目前数据返回的数据是包含7月份和8月份的以天维度返回的数据，用折线图显示出来，折线图的X轴 只显示 七月  八月 这2个标识，请问要怎么设置？？

3、进度条图 marker的显示
目前用Progress组件，显示如下所示界面，代码如下所示,marker 不起效。
<Progress
            percent={80}
            animation={false}
            color={['#5B8FF9', '#E8EDF3']}
            // todo marker 不起效
            // marker={[
            //   {
            //     value: 0.8,
            //     style: {
            //       stroke: '#D8D8D8',
            //     },
            //   },
            // ]}
          />
![image](https://user-images.githubusercontent.com/38000028/98187762-9dc76c80-1f4c-11eb-9d4b-16a27ffa20ef.png)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

**Comment by lxfu1** [comment]
1、aAxis:{type: ''}

**Comment by lxfu1** [comment]
看了下你提供的示例，建议升级 1.0 版本。
1、xAxis:{type: ''}   type 可选值 cat  、 time 等，详细参考文档
2、xAxis:{nice: false , tickCount: number} 
3、使用最新版本的 annotations

**Comment by zhaoxiaotao** [comment]
> 看了下你提供的示例，建议升级 1.0 版本。
> 1、xAxis:{type: ''} type 可选值 cat 、 time 等，详细参考文档
> 2、xAxis:{nice: false , tickCount: number}
> 3、使用最新版本的 annotations

针对问题3：使用annotations之后 样式也有变化了吗？
![image](https://user-images.githubusercontent.com/38000028/98241214-984a4080-1fa5-11eb-87cb-6edc07a252b5.png)

**Comment by zhaoxiaotao** [comment]
> 看了下你提供的示例，建议升级 1.0 版本。
> 1、xAxis:{type: ''} type 可选值 cat 、 time 等，详细参考文档
> 2、xAxis:{nice: false , tickCount: number}
> 3、使用最新版本的 annotations

目前antd 版本就是1.0版本。
问题1：已解决
最终使用 xAxis: { type: 'timeCat'},

**Comment by lxfu1** [comment]
```ts
  {
height: 20,
  width: 300,
  autoFit: false,
  percent: 0.536,
  barWidthRatio: 1,
  color: ['#F4664A', '#E8EDF3'],
  annotations: [
    {
      type: 'line',
      start: ['90%', '0%'],
      end: ['90%', '100%'],
      style: {
        stroke: 'red'
      }
    }
  ]
}
```
