### ISSUE TITLE
图例显示不全 顶部没有绘制出来

### ISSUE THREAD

**Issue by IMlixingwang** [ant-design/ant-design-charts#305]
<img width="648" alt="1" src="https://user-images.githubusercontent.com/31892121/98317837-3e369300-2018-11eb-973e-8f7ab5ac5b95.png">
<img width="703" alt="2" src="https://user-images.githubusercontent.com/31892121/98317841-41ca1a00-2018-11eb-9f67-ac057c63d816.png">

**Comment by lxfu1** [comment]
单折线图不支持图例的， 可以设置下 padding 。
