### ISSUE TITLE
🧐[问题]从0.x升级到1.x报错，Cannot read property 'Graph' of undefined 

### ISSUE THREAD

**Issue by moxun33** [ant-design/ant-design-charts#306]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
自行配置的`webpack4`，升级1.x版本后就报错。经测试，使用`create-react-app`脚手架就没有问题。
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
[![BfuXxe.png](https://s1.ax1x.com/2020/11/06/BfuXxe.png)](https://imgchr.com/i/BfuXxe)

**Comment by lxfu1** [comment]
React 版本问题？

**Comment by lxfu1** [comment]
感觉是loader的问题， 参考 create-react-app 的配置一下， npm run eject .

**Comment by moxun33** [comment]
解决了， `webpack` 的 `noParse`属性中移除 `lodash`就不会报错了。
