### ISSUE TITLE
🐛[BUG] RingProgress进度环图 percent改变图没有重绘，使用update()方法更新参数值无法居中

### ISSUE THREAD

**Issue by 15390410330** [ant-design/ant-design-charts#307]
### 🐛 bug 描述 
1.在使用进度环图时，我配置了一组默认参数，而后在标签内解构新数据, 这样做进度环图只会重绘一次，即第一次数据发生改变时能重绘，第二次第三次无效(在使用折线图的时候没有此bug)

2.当我放弃第一种方案，开始使用update（）方法后，参数值没有居中, 在api中也没有相关配置项

### © 版本信息

- ant-design-charts 版本: [^1.0.1]
- 浏览器环境 chrome 85.0.4183.121（正式版本） （32 位）
- 开发环境 [e.g. mac OS] windows 7  vscode

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/45443940/98349852-77d9bf00-2055-11eb-8fd0-1a263e23da1b.png)

**Comment by lxfu1** [comment]
update, 打印一下传入的值， 试了一下 1.0.4没问题。 https://codesandbox.io/s/loving-feynman-8fct0?file=/App.tsx:317-319

**Comment by 15390410330** [comment]
> 更新，打印一下传入的值，试了一下1.0.4没问题。https://codesandbox.io/s/loving-feynman-8fct0?file=/App.tsx:317-319

谢谢，更新到1.0.4之后确实好了，也不知道为啥yarn默认给我装的1.0.1版本

**Comment by lxfu1** [comment]
可能是你package-lock.json的问题，删掉就行了。
