### ISSUE TITLE
🧐[问题] 关于环形图的文档和API说明很让人迷惑

### ISSUE THREAD

**Issue by Arvin-He** [ant-design/ant-design-charts#308]
### 🧐 问题描述 
1. title属性在0.9.13版本还是支持的,但在升级指南中说不支持, 并且没有说明在哪一个版本不支持
2. 百分比percentage没有用,在图表上没有显示, 用法是完全参照demo上使用方式, 是不是用法有什么问题,? 还是在最新版才能使用这个属性? 文档中并没有说明
3. statistic统计信息显示不出来,  是不是在最新版才支持? 
4. 关于label中formatter属性是一个格式化函数,函数的参数在文档中找不到, 但是我从[https://antv-g2plot-v1.gitee.io/zh/examples/pie/donut](https://antv-g2plot-v1.gitee.io/zh/examples/pie/donut)找到了相关用法,这也让使用者太难了
5. 图表中有哪些属性是可以直接使用的, 如果可以的话,请在文档中列出来? 比如percentage, datum等
6. 关于文档还有很多说明是在[G2Plot](https://antv-g2plot-v1.gitee.io/zh/examples/pie/donut/API)中找到的, 如果可以的话,在
ant-design-charts的文档中尽量全部列出来,或者给出相应链接, 因为直接使用ant-design-charts的开发者会有很多属性在ant-design-charts的文档中找不到或者不知道该怎么使用

以上是作为一个ant-design-charts使用新手遇到的一些痛点, 希望ant-design-charts功能和API文档能够更加完善

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```js
import React from 'react';
import {connect} from 'dva';
import { Pie } from '@ant-design/charts';

const AAAAA = (props) => {
  const data =  [
    { type: 'aaa', value: 3, },
    { type: 'bbb', value: 0, },
    { type: 'ccc', value: 5, },
  ];
  const config = {
    title: {
      visible: true,
      text:'abcabc'
    },
    appendPadding: 10,
    data: data,
    angleField: 'value',
    colorField: 'type',
    radius: 0.8,
    innerRadius: 0.6,
    label: {
      visible: true,
      type: 'spider',
      formatter: (text, item) => {
        return `${item._origin.type}: ${item._origin.value} 个`
      },
    },
    tooltip: {
      showTitle: false,
      fields: ['type', 'value'],
      formatter: (text, item) => {
        return { name: text, value: `${item}` }
      }
    },
    interactions: [{ type: 'element-selected' }, { type: 'element-active' }],
    statistic: true,
    statistic: {
      visible: true,
      title: {
        style: { fontSize: 44 },
        formatter: function formatter(datum) {
          return datum ? datum.type : '总计';
        },
      },
      content: {
        style: { fontSize: 44 },
        formatter: function formatter(datum, data) {
          return datum
            ? '\xA5 '.concat(datum.value)
            : '\xA5 '.concat(
                data.reduce(function (r, d) {
                  return r + d.value;
                }, 0),
              );
        },
      },
    },
    legend: {
      layout: 'horizontal',
      position: 'bottom'
    },
  };
  return(
  <div>
        <Pie {...config} />
  </div>)
}

export default connect()(AAAAA);


```
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/16191792/98430972-88894400-20ec-11eb-84ac-25a54d573367.png)

**Comment by lxfu1** [comment]
反馈已经收到，欢迎扫描进群讨论。

**Comment by imakan** [comment]
@lxfu1  求拉群，我也遇到一些问题

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts 滚动到底部  有二维码

**Comment by laosandegudai** [comment]
基本迷茫甚至凌乱，特别是` percentage`。😂

**Comment by she1110** [comment]
antdesign的环形图真的很无语，这么简单的代码写的乱的不行，一堆参数不起作用，一堆bug不进行处理，不同版本也挺混乱
