### ISSUE TITLE
👑 [需求]编译出的源码支持ie11

### ISSUE THREAD

**Issue by NoahStepheno** [ant-design/ant-design-charts#311]

**Comment by lxfu1** [comment]
近期支持

**Comment by lxfu1** [comment]
https://unpkg.com/@ant-design/charts@1.0.6/dist/charts.min.js

**Comment by NoahStepheno** [comment]
> https://unpkg.com/@ant-design/charts@1.0.6/dist/charts.min.js
> 
> 无痕浏览器打开 https://charts.ant.design/guide/start 看一下

这个 bundle 仍有箭头函数。

**Comment by lxfu1** [comment]
最新版本， head 里面引入 <script type="text/javascript"  src="https://unpkg.com/@babel/polyfill@7.12.1/dist/polyfill.js"></script> 即可， 有问题欢迎加群讨论。
