### ISSUE TITLE
🐛[BUG]混合图表- data 中子项动态更新为空数组时会报错

### ISSUE THREAD

**Issue by LazyJoke** [ant-design/ant-design-charts#312]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
如 data: [[], []] 时，会发生报错
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
可在 https://codesandbox.io/s/intelligent-shadow-si7i4?file=/App.tsx 中复现
### 🏞 期望结果 [描述你原本期望看到的结果]
当 data 中子项为空时，应该能正常显示
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/intelligent-shadow-si7i4?file=/App.tsx
### © 版本信息

- ant-design-charts 版本: 1.0.4
- 浏览器环境: chrome
- 开发环境: mac OS

**Comment by lxfu1** [comment]
这个修改了 还没发布，临时解决方案是data为空时对应的geometryOptions附加属性不要配置，近期会发布。

**Comment by lxfu1** [comment]
修改一下配置。
```ts
    data: [[], []],
    xField: "time",
    yField: ["count", "count"],
    meta: {
      time: {
        type: 'cat'
      }
    },
```
