### ISSUE TITLE
🐛[BUG]饼图设置statistic和tooltip之后，自定义的legend，有问题

### ISSUE THREAD

**Issue by zhaoxiaotao** [ant-design/ant-design-charts#315]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
1、自定义的图例，在不设置statistic和 tooltip之前，是可以生效的，但是设置了 statistic 或者 tooltip之后，自定义的图例不生效了。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1、将 设置的 statistic 属性和 tooltip属性 都注释掉，点击自定义图例，可看到图表有变化，此时的展示数据正常，效果是正常的。
![image](https://user-images.githubusercontent.com/38000028/98627016-1ca61600-234e-11eb-8a95-4d43a8dbac6e.png)

2、将 statistic 属性和 tooltip属性 任一个 注释去掉，此时点击自定义图例，可看到图表会闪一下，但是展示的数据不正常，需要的效果不对
![image](https://user-images.githubusercontent.com/38000028/98627032-2c255f00-234e-11eb-84f4-b4092877be71.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
期望在不论是否设置statistic 属性和 tooltip属性，自定义的图例都正常。

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
复现demo链接：https://codesandbox.io/s/angry-euler-35dfy?file=/src/App.js:1165-1172

### © 版本信息

- ant-design-charts 版本: [e.g. 1.0.1]
- 浏览器环境
- 开发环境 [mac OS]

**Comment by lxfu1** [comment]
这个是配置里面包含了function，内部比对被认为是更新，执行了 update 操作， 可以考虑把 Pie 放到 useMemo 中，类似 pureComponent。

**Comment by zhaoxiaotao** [comment]
> 这个是配置里面包含了function，内部比对被认为是更新，执行了 update 操作， 可以考虑把 Pie 放到 useMemo 中，类似 pureComponent。

正常了， https://codesandbox.io/s/loving-chebyshev-gonzx?file=/src/App.js  用useMemo可以的
