### ISSUE TITLE
🐛[BUG]关于饼图图例崩

### ISSUE THREAD

**Issue by yzy2857895027** [ant-design/ant-design-charts#319]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/64308038/98893460-6bce8100-24dd-11eb-8b60-bf63a5df4b07.png)

**Comment by lxfu1** [comment]
label: {}
