### ISSUE TITLE
在数据较少的情况下能否做自动居中美化👑 [需求]

### ISSUE THREAD

**Issue by LazyJoke** [ant-design/ant-design-charts#322]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
单个数据点下，图表能否将该点做居中显示？
可通过下方连接查看单数据点的展示情况：

> 请将案例中改为单条数据

[ant-design-charts 折线图案例](https://codesandbox.io/s/otcde?file=/App.tsx)
[echarts 折线图案例](https://echarts.apache.org/examples/zh/editor.html?c=line-simple)

**Comment by Me-Momo** [comment]
最新版本应该解决了
