### ISSUE TITLE
New component appeared on the screen

### ISSUE THREAD

**Issue by SrScottz** [ant-design/ant-design-charts#324]
After updating the bookstore, these controls marked by the arrow appeared, I looked in the documentation but I didn't find how to hide them, could you help me? V1.0.4 installed.
![Captura de Tela 2020-11-13 às 09 10 54](https://user-images.githubusercontent.com/52793930/99071622-3daa7900-2591-11eb-9371-62ce47a9a49e.png)

**Comment by lxfu1** [comment]
scrollbar:  false
legend: false
