### ISSUE TITLE
🧐[问题] English Documentation Request

### ISSUE THREAD

**Issue by ZLester** [ant-design/ant-design-charts#325]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

My company is currently using Ant Design as its open source component framework, and is interested adopting ant-design-charts for our charting library, but the lack of an English docs site is preventing us from picking this library over other open source alternatives. While the English docs for the underlying g2plot library are helpful (as suggested in #165), the lack of translated docs for this library are a deal breaker for us.

Would the maintainers of this lib be willing to accept a pull to translate the existing Chinese documentation and have an English site, similar to what is done for g2plot's English documentation? We have bilingual engineers on staff who could assist in creating the pull if this lib's maintainers are open to it. @afc163 @lxfu1

**Comment by lxfu1** [comment]
The Chinese documentation needs to be improved at present, in order to avoid repeated work, we plan to complete the English document by the end of January 2021.

**Comment by ZLester** [comment]
Thank you for the fast response @lxfu1! We're looking forward to the updated documentation.

**Comment by MarkLyck** [comment]
@lxfu1 any update on this work?

We're in the same boat, love how @antdesign charts work over competitors, but lack of English docs is a dealbreaker.

**Comment by lxfu1** [comment]
> @lxfu1 any update on this work?
> 
> We're in the same boat, love how @antdesign charts work over competitors, but lack of English docs is a dealbreaker.

This week.

**Comment by lxfu1** [comment]
Based on the translation software translated a version, welcome PR together to build.

**Comment by ZLester** [comment]
Closed by #462
