### ISSUE TITLE
🐛[BUG]双轴图y轴设置最大值时渲染出来会超过图例

### ISSUE THREAD

**Issue by yuruwang** [ant-design/ant-design-charts#326]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

双轴图y轴设置最大值时渲染出来会超过图例，截图：
![image](https://user-images.githubusercontent.com/31492974/99219424-8ffccb80-2817-11eb-9714-4c0d237a4632.png)

online demo: https://riddle.alibaba-inc.com/riddles/6ca974d9

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
1.0.7
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by liuzhenying** [comment]
hi，demo 中提供的数据，value 的最大值远远大于 200.

**Comment by yuruwang** [comment]
> hi，demo 中提供的数据，value 的最大值远远大于 200.

是的，在y轴的最大值上配置了200，期望是渲染出来的柱状图不会溢出200的范围，现在的表现是会溢出

**Comment by lxfu1** [comment]
limitInPlot: true
