### ISSUE TITLE
🐛[BUG]legend选项只勾选一个其余全部取消图像会出现错乱问题

### ISSUE THREAD

**Issue by yzy2857895027** [ant-design/ant-design-charts#327]
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

import { Pie } from '@ant-design/charts';
import React from 'react';

/**
 * 环形饼图
 */
export default (props) => {
  const { data } = props;

  data.map((item, index) => {
    let { value } = item;
    if (value === 0) {
      data.splice(index, 1);
    } else if (value) {
      item.value = parseInt(value);
    }
    return data;
  });

  const config = {
    appendPadding: 10,
    data: data || [],
    angleField: 'value',
    colorField: 'nameChinese',
    radius: 0.8,
    innerRadius: 0.64,
    // label: {
    //   type: 'inner',
    //   offset: '-0.5',
    //   content: '{percentage}',
    //   style: {
    //     fill: '#fff',
    //     fontSize: 14,
    //     textAlign: 'center',
    //   },
    // },
    statistic: {
      title: false,
      content: {
        style: { fontSize: 44 },
        formatter: function formatter() {
          return '';
        },
      },
    },
    label: {
      type: 'spider',
      content: '{percentage}',
    },
    legend: {
      layout: 'horizontal',
      position: 'bottom',
    },
    'interactions': [{ type: 'pie-statistic-active' }],
  };
  return <Pie {...config} />;
}

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/64308038/99230842-c3952100-282a-11eb-8551-723343df5664.png)

**Comment by lxfu1** [comment]
先去掉 interactions: [{ type: 'pie-statistic-active' }]  。
