### ISSUE TITLE
👑 [需求]饼图的legend属性 可否设定标签锁住不可选

### ISSUE THREAD

**Issue by yzy2857895027** [ant-design/ant-design-charts#328]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/64308038/99230980-f212fc00-282a-11eb-997c-39f68dd34945.png)

**Comment by lxfu1** [comment]
useEffect(()=>{
 if(ref){
    ref.removeInteraction('legend-filter')
}
}, [])
<Pie  chartRef={chartRef => ref=chartRef}>
