### ISSUE TITLE
🐛[BUG][1.x] tooltip.customContent 的表现不符合预期，也和 G2Plot 表现不一致

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design-charts#333]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/14918822/99616910-22d87880-2a59-11eb-818c-88cdf45f78b2.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/wild-snowflake-1zh1h?file=/App.tsx
### © 版本信息

- ant-design-charts 版本: 1.0.8
- 浏览器环境: Chrome
- 开发环境: Mac OS

**Comment by lxfu1** [comment]
不需要模板字符串， 直接使用 React dom 即可。  
`<div>${title}</div>`   =>  <div>{title}</div>

**Comment by lxfu1** [comment]
新版本已经修复
