### ISSUE TITLE
饼图在项目中不能显示百分比

### ISSUE THREAD

**Issue by liushuai512** [ant-design/ant-design-charts#335]
var config = {
        appendPadding: 10,
        data: data,
        angleField: 'value',
        colorField: 'type',
        radius: 0.8,
        label: {
            type: 'spider',
            content: '{name}\n{percentage}',
        },
        interactions: [{ type: 'pie-legend-active' }, { type: 'element-active' }],
    };

按照实例这样写，不能显示百分比

**Comment by lxfu1** [comment]
能提供一个在线demo吗？

**Comment by lxfu1** [comment]
无法复现，提提在线demo时再打开。
