### ISSUE TITLE
🐛[BUG] TinyColumn 的annotation没有顶边

### ISSUE THREAD

**Issue by rdmclin2** [ant-design/ant-design-charts#336]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

![image](https://user-images.githubusercontent.com/4705237/99751034-67791800-2b1c-11eb-942c-afa233449e35.png)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
meta: {
     x: {
      range: [0, 1]
    },
  }
