### ISSUE TITLE
Empty chart message display option missing🐛[BUG] Kōng túbiǎo xiāoxī xiǎnshì xuǎnxiàng diūshī

### ISSUE THREAD

**Issue by sourabhsurana1008** [ant-design/ant-design-charts#339]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
Which chart? provide your config please.

**Comment by sourabhsurana1008** [comment]
Line 

  const data = [
    { year: '1991', value: 0 },
    { year: '1992', value: 0 },
  ];

some time  const data = [];

  const config = {
    data,
    meta: {
      genre: {
        alias: '33333333333333333333', // 列定义，定义该属性显示的别名
      },
      sold: {
        alias: 'ssssssssssssssss',
      },
    },
    fill: 'red',
  
    xField: 'year',
    yField: 'value',
    point: {
      size: 5,
      shape: 'diamond',
    },
    label: {
      style: {
        fill: '#aaa',
      },
    },
  };

**Comment by lxfu1** [comment]
This is your expected ?
```ts
 yAxis: {
      title: {
        text: 'ssssssssssssssss'
      }
    },
    xAxis: {
       title: {
      	text: '33333333333333333333', // 列定义，定义该属性显示的别名
      },
    },

```

**Comment by sourabhsurana1008** [comment]
No if no data then want to show placeholder **no data**.

**Comment by lxfu1** [comment]
```ts
if(!data.length){
   return <div>no data</div>
}
return <Line  {...config}  />
```
