### ISSUE TITLE
🧐[问题]延迟加载数据的时候报错：Cannot read property 'view' of null

### ISSUE THREAD

**Issue by wood3n** [ant-design/ant-design-charts#342]
### 🧐 问题描述

环图加上`interactions: [{ type: 'pie-statistic-active' }]`和配置`statistic`字段后，加载完数据就闪退报错

![image](https://user-images.githubusercontent.com/31716713/99951296-d8d4f700-2db8-11eb-838f-243dc8c16f74.png)

### 💻 示例代码

```tsx
export interface Data {
  type: string;
  value: number | string;
}

interface Props {
  data: Data[]
}

const config = {
  legend: {
    position: 'bottom',
    flipPage: false,
  },
  radius: 0.8,
  innerRadius: 0.7,
  autoRotate: false,
  width: 300,
  height: 300,
  label: {
    type: 'spider',
  },
  angleField: 'value',
  colorField: 'type',
  interactions: [{ type: 'pie-statistic-active' }],
};

/**
 * 自定义环图
 */
const CustomizedPie = ({ data = [] }: Props) => {
  return (
    <Pie
      {...config}
      statistic={{
        title: {
          style: {
            fontSize: '14px'
          },
          formatter: function formatter(datum) {
            return datum ? datum.type : "总数";
          }
        },
        content: {
          offsetY: 10,
          style: {
            fontSize: '22px'
          },
          formatter: function formatter(datum) {
            return datum?.value ? `${datum.value}` : `${0}`;
          }
        }
      }}
      data={data}
    />
  )
}

export default CustomizedPie
```

### 🚑 其他信息

版本`1.0.8`

**Comment by wood3n** [comment]
加载数据是通过请求服务端以后`setState`传递进去的

**Comment by lxfu1** [comment]
更新到 1.0.9 试试  https://codesandbox.io/s/nice-dawn-kgyp7?file=/App.tsx

**Comment by wood3n** [comment]
> 更新到 1.0.9 试试 https://codesandbox.io/s/nice-dawn-kgyp7?file=/App.tsx

一样啊，还是报这个错误，我好奇怪，我这个配置挪出来放codesanbox上就正常，本地就一直提示这个错误

**Comment by lxfu1** [comment]
> > 更新到 1.0.9 试试 https://codesandbox.io/s/nice-dawn-kgyp7?file=/App.tsx
> 
> 一样啊，还是报这个错误，我好奇怪，我这个配置挪出来放codesanbox上就正常，本地就一直提示这个错误

你本地可能被lock了，删除package-lock.json 和 node_modules 重新 install

**Comment by wood3n** [comment]
试了，还是一样

**Comment by wood3n** [comment]
@lxfu1 不加`statistic`就没问题，交互什么的都正常，加了以后页面渲染完以后2~3后就闪退报错

**Comment by wood3n** [comment]
@lxfu1 请问有钉钉交流群吗？方便的话分享个CloudIDE给你看看

**Comment by lxfu1** [comment]
> @lxfu1 请问有钉钉交流群吗？方便的话分享个CloudIDE给你看看

https://github.com/ant-design/ant-design-charts  滚动到底部
