### ISSUE TITLE
🧐[问题] 折线图数据重叠，是否有优化显示的方法？

### ISSUE THREAD

**Issue by iambool** [ant-design/ant-design-charts#344]
### 🧐 问题描述
当线条比较多的时候，显示数据时，数据会重叠，如下所示
![image](https://user-images.githubusercontent.com/30134533/100202655-92a8a080-2f3c-11eb-86ba-2377c2a51e25.png)

查看文档，没有找到关于事件绑定的内容。尝试了用useRef挂载到图表的chartRef上，但是事件是整个图表的事件，不能具体到某个线条上。
是否有什么方法，可以在鼠标移动到某条线上时，才显示具体数值？

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
"@ant-design/charts": "^1.0.8"

**Comment by lxfu1** [comment]
label: {
         layout: [{ type: 'hide-overlap' }],
      },

**Comment by lxfu1** [comment]
事件绑定可以使用 element:click , label  可以设置 formatter 的 ， 根据情况自己判断。

**Comment by iambool** [comment]
您好，我尝试了绑定事件的方式。当鼠标移动至某个图例上时，才显示此类数据。
但是，绑定事件后，每次事件触发时，都会重新刷新图表，导致当隐藏某图例后，鼠标移动至其他图例时，隐藏的线条还是会重新出现。
代码在此：https://codesandbox.io/s/still-river-lrn8q?file=/src/demo.tsx

表现如下：
![问题](https://user-images.githubusercontent.com/30134533/100492547-42158b00-3168-11eb-9284-8acb1383342f.gif)

**Comment by iambool** [comment]
> 事件绑定可以使用 element:click , label 可以设置 formatter 的 ， 根据情况自己判断。

我按照上方说明绑定了事件，但是每次事件触发时，都会刷新图表，导致已隐藏的线条也会出现，请问这个是bug还是我使用有误呢…我是按官方文档来定义的事件

**Comment by Me-Momo** [comment]
现在的更新确实会直接重新渲染图表，没有保存 legend 隐藏状态，这个问题应该要到 G2Plot 层解决
