### ISSUE TITLE
🧐[问题]报错Unhandled Rejection (TypeError): Object(...) is not a function，我的React版本是16.14.0

### ISSUE THREAD

**Issue by ChrisXYF** [ant-design/ant-design-charts#345]
本地项目React版本是16.14.0，但是引入：
import { Pie } from '@ant-design/charts';
就报错 
![image](https://user-images.githubusercontent.com/38465558/100315809-3a34da00-2ff4-11eb-8c44-6f5e62378bab.png)

希望解答一下！谢谢！

**Comment by lxfu1** [comment]
执行 update 试试，这错误太普通看不出问题， 16.14.0 我测试了一下， 没发现问题， 建议提供一下复现代码。
https://codesandbox.io/s/interesting-architecture-v0ll5?file=/App.tsx

**Comment by ChrisXYF** [comment]
> 执行 update 试试，这错误太普通看不出问题， 16.14.0 我测试了一下， 没发现问题， 建议提供一下复现代码。
> https://codesandbox.io/s/interesting-architecture-v0ll5?file=/App.tsx

感谢，已经解决了，是这边版本问题！不好意思🌹
