### ISSUE TITLE
👑 [需求]是否可以提供矩形树图？

### ISSUE THREAD

**Issue by viewweiwu** [ant-design/ant-design-charts#346]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
是否可以提供矩形树图，如图所示。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/14287892/100323108-31e29c00-3000-11eb-90f8-95224c92163a.png)
原链接：
https://bizcharts.net/product/bizcharts/demo/217

**Comment by lxfu1** [comment]
近期提供  欢迎扫描 README.md 的二维码加群。

**Comment by viewweiwu** [comment]
好的，非常感谢🙏
