### ISSUE TITLE
🧐[问题]: 您好，ant-design/charts升至1.0.9版本后，请问是不再支持columnSize属性了么，还有就是connectedArea是只有在hover或click时才会显示，不会是使用该属性立即会显示了

### ISSUE THREAD

**Issue by liuajingliu** [ant-design/ant-design-charts#347]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]

未升级时：
![截屏2020-11-26 下午4 09 34](https://user-images.githubusercontent.com/33769618/100326088-78d29080-3004-11eb-8afd-4c94807bc7fc.png)

升级以后变成这样了：
![截屏2020-11-26 下午4 29 14](https://user-images.githubusercontent.com/33769618/100326180-9869b900-3004-11eb-9d57-c87b078a4fed.png)

主要问题如下：
1. 列宽度没有看到属性可以去改变，columnStyle 下的 lineWidth 无效
2. 柱状图上的数值无法去掉
  yAxis: {
        label: {
          autoHide: true,
          autoRotate: false,
          formatter: (v: any) => {
            return `${v}`.replace(/\d{1,3}(?=(\d{3})+$)/g, s => `${s},`);
          }
      }
无效
3. 堆叠效果hover才会显示

**Comment by lxfu1** [comment]
1、columnWidthRatio： 0.1
2、 label: false

**Comment by liuajingliu** [comment]
好的 谢谢
