### ISSUE TITLE
🐛[BUG] 文档错误

### ISSUE THREAD

**Issue by MoYuM** [ant-design/ant-design-charts#351]
### 🐛 bug 描述 
https://charts.ant.design/demos/line?type=api
![image](https://user-images.githubusercontent.com/64450989/100533485-eae2e980-323f-11eb-9174-add7d0cc766c.png)
这里有两个container，第二个应该为html吧，和同事试了好久才试出来

**Comment by lxfu1** [comment]
能否到 https://github.com/antvis/g2plot 提个 PR一起贡献。
