### ISSUE TITLE
图表渲染依赖于其他组件渲染🐛

### ISSUE THREAD

**Issue by Una-Gao** [ant-design/ant-design-charts#352]
当前版本号 1.0.9
版本升级之后 card2按钮切换会导致card1折线图的渲染 折线图的数据没有发生任何变化
![image](https://user-images.githubusercontent.com/68375674/100708944-2b7d6700-33e8-11eb-81b5-f9490b8b9a16.png)

**Comment by lxfu1** [comment]
memo,  https://reactjs.org/docs/hooks-reference.html#usememo
