### ISSUE TITLE
🐛[BUG] Can't resolve '@antv/g2/lib/interaction/action/util'

### ISSUE THREAD

**Issue by ivonzhang** [ant-design/ant-design-charts#355]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

./node_modules/_@antv_g2plot@2.2.13@@antv/g2plot/esm/plots/pie/interactions/pie-statistic-action.js
Module not found: Error: Can't resolve '@antv/g2/lib/interaction/action/util' in '/Users/xxxx/Documents/learning/visage-demo/visage-demo/node_modules/_@antv_g2plot@2.2.13@@antv/g2plot/esm/plots/pie/interactions'

使用G2的版本："@ant-design/charts": "^1.0.9",
应用的react版本："react": "^16.6.3",

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

按照官网示例，使用component的方式，非function component

### © 版本信息

- ant-design-charts 版本: "@ant-design/charts": "^1.0.9",
- 浏览器环境： Chrome
- 开发环境 [ mac OS]

**Comment by lxfu1** [comment]
npm i @antv/util -S
