### ISSUE TITLE
🐛[BUG]网站上关于缩进树图的示例在移动端无法点击.

### ISSUE THREAD

**Issue by gnosuw** [ant-design/ant-design-charts#357]
### 🐛 bug 描述
    我这边在访问官网上缩进树示例时 ,发现示例在PC端可以正常响应点击事件,但在移动端访问时,点击没有反应
    https://charts.ant.design/demos/indented-tree
 

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/4464392/101120482-b8166800-3628-11eb-95e3-6dc0c356a213.png)

**Comment by lxfu1** [comment]
update 1.0.10
