### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by southorange1228** [ant-design/ant-design-charts#367]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/32590310/101462591-567f3200-3977-11eb-86f1-e069b50f4c8f.png)
仪表板刻度设置似乎无效

```ts
<Gauge
              percent={safetyData.score / 100}
              range={{ color: safetyData.color }}
              axis={{
                label: {
                  formatter: function formatter(v) {
                    return Number(v) * 100;
                  },
                },
                tickInterval: 20,
                min: 0,
                max: 100,
                nice: true,
              }}
              chartRef={ref => setChartRef(ref)}
              height={250}
              padding={[0, 4, 0, 4]}
              indicator={{
                pointer: { style: { stroke: safetyData.color } },
                pin: { style: { stroke: safetyData.color, lineWidth: 3, r: 4.75 } },
              }}
              startAngle={(-5 / 4) * Math.PI}
              endAngle={(1 / 4) * Math.PI}
            />
```

### © 版本信息

- ant-design-charts 版本: [1.0.11]
- 浏览器环境 chrome
- 开发环境 [ mac OS]

**Comment by southorange1228** [comment]
为什么刻度默认要设计成不均分的样式，不是很理解

**Comment by lxfu1** [comment]
https://github.com/antvis/G2Plot/pull/2085   这是个 bug  近期发布。

**Comment by southorange1228** [comment]
![image](https://user-images.githubusercontent.com/32590310/101614058-6f571880-3a47-11eb-834a-7088a5e410bf.png)
另一个问题，所有数据为空时，tooltip的formatter不会被调用？ @lxfu1

**Comment by lxfu1** [comment]
Pie 吗？ 有钉钉的话建议扫码进答疑群，README 页面有二维码。

**Comment by lxfu1** [comment]
> ![image](https://user-images.githubusercontent.com/32590310/101614058-6f571880-3a47-11eb-834a-7088a5e410bf.png)
> 另一个问题，所有数据为空时，tooltip的formatter不会被调用？ @lxfu1

先用 customContent
https://github.com/ant-design/ant-design-charts/pull/370/files
