### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by BeliefRC** [ant-design/ant-design-charts#368]
### 🐛 bug 描述 
柱状图，当label在顶部时，可能出现label被遮挡的问题

### 📷 复现步骤及代码
https://riddle.alibaba-inc.com/riddles/96860728
基础柱状图，配置了特殊的数据后，label被遮挡👆

https://riddle.alibaba-inc.com/riddles/1db52f11
官网的分组柱状图demo，将legend修改到底部，label设置成`{}`时，页面上展示的label被遮挡👆

### 🏞 期望结果 [描述你原本期望看到的结果]
label完全展示到页面中

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/24429723/101465249-a90e1d80-397a-11eb-9ed9-da00515ad7bc.png)
![image](https://user-images.githubusercontent.com/24429723/101465281-b4614900-397a-11eb-8840-94443b3b9432.png)

**Comment by lxfu1** [comment]
```ts
 label: {
  layout: [{
    type: 'limit-in-plot'
  }]
},
```
