### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by dany952** [ant-design/ant-design-charts#369]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
TypeError: Cannot read property 'show' of null
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/70162354/101527999-56216f80-3954-11eb-82aa-9130bd3fc00a.png)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
提供一下复现代码。

**Comment by dany952** [comment]
在加載組件並將鼠標懸停在圖形上時會發生這種情況


我的代碼是

import React, { useState, useEffect } from 'react';
import { Column } from '@ant-design/charts';

const DemoColumn: React.FC = () => {
  

var data = [
{timeDate:'12/04/20 7:47',
    name: 'Aprobada',
    totTrans: 1800,
    totAmount: 125,
    pesos: 1200,
    US: 5000,
  },{timeDate:'12/04/20 7:47',
    name: 'declinada',
    totTrans: 180,
    totAmount: 12,
    pesos: 1200,
    US: 5000,
  },
{timeDate:'12/04/20 7:48',
    name: 'Aprobada',
    totTrans: 1800,
    totAmount: 125,
    pesos: 1200,
    US: 5000,
  },{timeDate:'12/04/20 7:48',
    name: 'declinada',
    totTrans: 180,
    totAmount: 12,
    pesos: 1200,
    US: 5000,
  },
]
var config = {
    data: data,
    isStack: true,
    xField: 'timeDate',
    yField: 'totTrans',
    seriesField: 'name',
    tooltip: {
      customContent: (title, items) => {
        return (
          <div style={{ padding: '16px 8px' }}>
            <h5>Indicador Transaccional</h5>
            <br />
            <p>Tiempo：{title}</p>
            <p style={{ margin: 0 }}>
              Pesos： ${items[0] && items[0].data.pesos}
            </p>
            <br />
            <p style={{ margin: 0 }}>
              Dolares: ${items[0] && items[0].data.US}
            </p>
          </div>
        );
      },
    },
    xAxis: { label: { autoRotate: false } },
    slider: {
        start: 0.1,
        end: 0.2
    },
    label: {
        position: 'middle',
        layout: [
            { type: 'interval-adjust-position' },
            { type: 'interval-hide-overlap' },
            { type: 'adjust-color' }
        ]
    }
};
  return <Column {...config} />;
};

export default DemoColumn;

**Comment by lxfu1** [comment]
The code you provided is normal under version 1.0.11， It is recommended to upgrade the version.

**Comment by dany952** [comment]
Can you tell me how I update the code

**Comment by lxfu1** [comment]
Remove dependencies @ant-design/charts in the package.json ,  run 'npm i  @ant-design/charts -S' and then execute 'npm  update'.
