### ISSUE TITLE
为什么我安装的依赖中没有DualAxes？？？🧐[问题]

### ISSUE THREAD

**Issue by IversonTian** [ant-design/ant-design-charts#371]
![image](https://user-images.githubusercontent.com/38484790/101980922-f1dc1400-3ca3-11eb-8912-3d5642b0c7f9.png)

**Comment by IversonTian** [comment]
版本：
@ant-design/charts": "^0.9.13
已经删除package-lock.json和node_modules好多边了，还是没有这个图表，有遇到相同情况的吗？

**Comment by lxfu1** [comment]
用最新版本， package.json里面删除重新install。

**Comment by lxfu1** [comment]
> 版本：
> @ant-design/charts": "^0.9.13
> 已经删除package-lock.json和node_modules好多边了，还是没有这个图表，有遇到相同情况的吗？

使用1.x版本。

**Comment by IversonTian** [comment]
> > 版本：
> > @ant-design/charts": "^0.9.13
> > 已经删除package-lock.json和node_modules好多边了，还是没有这个图表，有遇到相同情况的吗？
> 
> 使用1.x版本。

好的 我试试，谢谢你
