### ISSUE TITLE
Possibility to hide a series by name (隱藏名稱的可能性)

### ISSUE THREAD

**Issue by cbojaca** [ant-design/ant-design-charts#373]
It would be a very good feature to be able to functionally hide a series, Example I have the following data set:
{
         assetid: 31796,
         daytimecount: 129,
         datagroupedby: '2014-01-03',
         failedcount: 3,
         invalidcount: 2,
         nullcount: 8,
         validcount: 6,
     },
     {
         assetid: 31796,
         daytimecount: 129,
         datagroupedby: '2014-01-10',
         failedcount: 17,
         invalidcount: 9,
         nullcount: 0,
         validcount: 7,
     },

I would only like to show the data from the failedcount and invalidcount fields, is this possible without filtering the data set

**Comment by lxfu1** [comment]
Use [DataSet](https://github.com/antvis/data-set)  ?
