### ISSUE TITLE
ant design chart 的条形图，通过tooltip.crosshairs设置了十字准星，如何给这条线添加文字跟随效果🧐[问题]

### ISSUE THREAD

**Issue by 839900146** [ant-design/ant-design-charts#375]
### 🧐 问题描述 
比如给十字准星的横轴最左边添加 ’x‘ 文字，竖轴的最上方添加 'y' 字，并且它会自动跟随十字准星的移动，就类似于数学中的坐标轴标识一样

### 💻 示例代码
	tooltip: {
		fields: ['type', 'DateRange', 'demand'],
		shared: true,
		showCrosshairs: true, // 展示 Tooltip 辅助线
		crosshairs: {
			// xy辅助线
			type: 'y',
			follow: true,
			text: {
				content: '666',
				// position: 'bottom',
			},
			// 辅助线样式
			line: {
				style: {
					stroke: 'red',
					lineWidth: 2,
					strokeOpacity: 0.7,
					shadowColor: 'black',
					shadowBlur: 10,
					shadowOffsetX: 5,
					shadowOffsetY: 5,
					cursor: 'pointer',
				},
			},
		},
	},

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![](https://pic.downk.cc/item/5fd71bda3ffa7d37b37fdfe9.jpg)

**Comment by lxfu1** [comment]
```ts
 crosshairs: {
          type: 'xy',
          text: (type, defaultText, items) => {
            const color = items[0].color;
            if (type === 'x') {
              return {
                offset: 5,
                position: 'end',
                content: defaultText + ' cm',
                style: {
                  textAlign: 'center',
                  textBaseline: 'top',
                  fontSize: 14,
                  fontWeight: 'bold',
                },
              };
            }
            return {
              offset: 5,
              content: defaultText + ' kg',
              style: {
                textAlign: 'start',
                fontSize: 14,
                fontWeight: 'bold',
              },
            };
          },
          textBackground: null,
        },
```
