### ISSUE TITLE
🐛[BUG] removeInteraction 禁用图例点击图表过滤效果 没反应

### ISSUE THREAD

**Issue by Quanzhitong** [ant-design/ant-design-charts#378]
removeInteraction： [{ type: 'legend-filter' }, { type: 'legend-visible-filter' }]
期望移除这两个交互，但移除不了

**Comment by lxfu1** [comment]
```ts
chartRef.removeInteraction('legend-filter');
```

**Comment by Me-Momo** [comment]
也可以设置 interactions:[{type:”xxx”, enable: false }]
文档暂未透出，这周会添加
