### ISSUE TITLE
🧐Tooltip customContent as React node

### ISSUE THREAD

**Issue by zohalmir** [ant-design/ant-design-charts#379]
### 🧐 
1. I would like to know if it is possible to pass in a React Node as a customContent for the tooltip of an AntV Chart? 
2. How can I change the styling of a single series in the tooltip. I want to specific stacked section of the bar I am hovering over to be in bold. Using itemTpl leads to all tooltip lines to be changed... In the example below, since I am hovering over the over region, I want the orange series name and value to be in bold! 
![image](https://user-images.githubusercontent.com/43083525/102235656-8c18a380-3ec0-11eb-9f38-769c825f098a.png)

**Comment by lxfu1** [comment]
https://charts.ant.design/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip
