### ISSUE TITLE
🧐[问题] 请问我要怎么通过pie的实例来自定义其他元素和pie的交互事件呢？

### ISSUE THREAD

**Issue by wood3n** [ant-design/ant-design-charts#383]
### 🧐 问题描述

因为pie原本的图例没法做到和画布本身宽度一样，我希望通过自定义pie的图例来达到原有pie的图例的交互效果，点击以后能过滤显示在pie中的数据

### 💻 示例代码

想在`click`事件里面通过pie的实例来定义交互效果

[![Edit festive-panini-p73oq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-panini-p73oq?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Me-Momo** [comment]
目前图表的局部更新还没处理好，两种解决方案：
1、根据外部自定义图例点击，来进行数据过滤，调用 `plot.update({ data: filteredData })`; 缺点是会导致图表重新渲染
2、根据外部自定义图例点击，来进行数据过滤，调用 `plot.chart.changeData(filteredData)`; 

这里的 plot 可以通过 chartRef 获取

**Comment by wood3n** [comment]
多谢，`changeData`效果不错，就差个`hover`图例高亮对应`pie`区域的交互了，不过无关紧要了

**Comment by DPGZl** [comment]
@wood3n 请教一下，请问 hover 图例高亮对应 pie 区域的交互，有找到解决方法吗，我也碰到了一样的问题

**Comment by wood3n** [comment]
> @wood3n 请教一下，请问 hover 图例高亮对应 pie 区域的交互，有找到解决方法吗，我也碰到了一样的问题

项目很久了，现在已经不做了
