### ISSUE TITLE
DagreGraph导出图片很模糊，使用官网提供的设置encoderOptions是个背景色？？？

### ISSUE THREAD

**Issue by fangoo** [ant-design/ant-design-charts#385]

**Comment by Yanyan-Wang** [comment]
模糊的问题，可以在 downloadImage 之前设置一下 graph 画布的 pixelRatio，大一些应该会清晰，比如 2，3 之类的

ref.current.get('canvas').set('pixelRatio', 2)

**Comment by zhangfu-git** [comment]
> 模糊的问题，可以在 downloadImage 之前设置一下 graph 画布的 pixelRatio，大一些应该会清晰，比如 2，3 之类的
> 
> ref.current.get('canvas').set('pixelRatio', 2)

为什么没有get方法，ref.current是在onReady中过去的吗？
