### ISSUE TITLE
🐛[BUG]当图表在flex item中时，若有多个元素则会出现图表高度无限变大

### ISSUE THREAD

**Issue by Joeoeoe** [ant-design/ant-design-charts#389]
### 📷 复现步骤
```
    <div style={{ display: "flex" }}>
      <div>
        <p>当图表在flex item中时，若有多个元素则会出现图表高度无限变大</p>
        <Line {...config} />
      </div>
    </div>
```

### 🏞 期望结果
图表高度不应该无限变大
![1](https://user-images.githubusercontent.com/35675374/102852258-d23dac00-4458-11eb-942a-90410a5e77e3.gif)

### 💻 复现代码
https://codesandbox.io/s/flexbujubugfuxian-s9133?file=/App.tsx

### © 版本信息
- ant-design-charts 版本: 1.013
- 浏览器环境：Chrome 87.0.4280.88
- 开发环境 Win10

**Comment by lxfu1** [comment]
容器给个高度。

**Comment by arcsin1** [comment]
父级容器需要给高度。codebox那个是没有高度的

**Comment by Joeoeoe** [comment]
@arcsin1 @lxfu1 嗯嗯，发现给个高度就可以了。试验时发现多个子元素会出现问题，单个子元素不会出现问题，以为是bug
