### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by ba-age** [ant-design/ant-design-charts#390]
使用分组柱状图时，设置了isGroup为true，也设置了groupField（也试过seriesField），但实现的效果还是和堆叠柱状图一样

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/50125958/102858066-96104880-4464-11eb-8b24-f2b03abe5632.png)
![image](https://user-images.githubusercontent.com/50125958/102858286-f4d5c200-4464-11eb-9ca4-318cdeb5a22c.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
![image](https://user-images.githubusercontent.com/50125958/102858299-fd2dfd00-4464-11eb-9d4f-1acf3c51d799.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
const staffEmploymentIntention = [{"sex":1,"typeName":"aa","count":6},{"sex":2,"typeName":"aa","count":5},{"sex":1,"typeName":"bb","count":2},{"sex":2,"typeName":"bb","count":3},{"sex":1,"typeName":"cc","count":3},{"sex":2,"typeName":"cc","count":3},{"sex":1,"typeName":"dd","count":13},{"sex":2,"typeName":"dd","count":17},{"sex":1,"typeName":"ff","count":3},{"sex":2,"typeName":"ff","count":4},{"sex":1,"typeName":"ee","count":4},{"sex":2,"typeName":"ee","count":3},{"sex":1,"typeName":"gg","count":3},{"sex":2,"typeName":"gg","count":6},{"sex":1,"typeName":"hh","count":3},{"sex":2,"typeName":"hh","count":4}]
<GroupedColumn 
    data={staffEmploymentIntention}
    xField='typeName'
    yField="count"
    isGroup={true}
    groupField="sex"
    forceFit={true}
    color={['#f64b78', '#64befd']}
    legend={false}
    meta={{
      typeName:{alias: '类型'},
      count: {alias: '数量'},
      sex: {alias: '性别'}
    }}
  />
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
你看到文档和版本不对应，0.x 版本官网： https://v0-charts.ant.design/

**Comment by ba-age** [comment]
> 你看到文档和版本不对应，0.x 版本官网： https://v0-charts.ant.design/

也没用，我现在版本用的是0.9.13，Column和GroupedColumn都试过了，效果一直像堆叠柱状图一样

**Comment by ba-age** [comment]
我知道了，只要我把sex对应的1和2换成男和女就可以了，很奇怪o(╥﹏╥)o
