### ISSUE TITLE
🐛[BUG] 柱状图坐标轴显示有问题

### ISSUE THREAD

**Issue by magiclee203** [ant-design/ant-design-charts#391]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在 Safari 浏览器上，柱状图的 x 坐标轴显示有问题，文字的下部分展示不全，官网上可见。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
https://charts.ant.design/demos/column/

### © 版本信息
- 浏览器环境
Safari

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1057" alt="截屏2020-12-23 上午8 18 05" src="https://user-images.githubusercontent.com/14924792/102945098-c1904300-44f7-11eb-8cb4-74ba02161f9d.png">

**Comment by lxfu1** [comment]
配置一下 appendPadding: 5,  有可能是默认字体大小读取错误。
