### ISSUE TITLE
🧐[问题] 散点图能够接受数据的最大限制

### ISSUE THREAD

**Issue by Una-Gao** [ant-design/ant-design-charts#393]
### 🧐 问题描述     利用散点图去渲染了一万五千多条数据, 抛出错误信息<超过调用栈限制>
(1)😩 想知道最多大概接受多少条数据呢？
(2) 这个问题会和电脑的一些配置有关系吗？

### 🚑 其他信息 
![image](https://user-images.githubusercontent.com/68375674/102963753-e64edf80-4524-11eb-8846-2a15606dbcbf.png)

**Comment by lxfu1** [comment]
```ts
const data = new Array(15000).fill('').map(()=>{
  return {
    x: Math.floor(Math.random()*10000),
    y: Math.floor(Math.random()*10000)
  }
});
const config = {
  data,
  xField: 'x',
  yField: 'y',
};
```
简单配置一万五可以正常使用哈，提供配置看看。

**Comment by hustcc** [comment]
Math.max，Math.min 是有数据量限制。这个问题在新版本修复，升级到最新应该可以的。 @Una-Gao
