### ISSUE TITLE
🧐[问题]升级到1.0.13，一堆warning提示

### ISSUE THREAD

**Issue by wangangngg** [ant-design/ant-design-charts#394]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
升级到1.0.13，一堆warning提示，能不能帮忙修复下
 warning  in ./node_modules/@antv/g2plot/node_modules/@antv/g2/esm/theme/util/create-by-style-sheet.js

"export 'TOOLTIP_CSS_CONST' was not found in '@antv/component'

 warning  in ./node_modules/@antv/g2plot/node_modules/@antv/g2/esm/theme/util/create-by-style-sheet.js

"export 'TOOLTIP_CSS_CONST' was not found in '@antv/component'

 warning  in ./node_modules/@antv/g2plot/node_modules/@antv/g2/esm/theme/util/create-by-style-sheet.js

"export 'TOOLTIP_CSS_CONST' was not found in '@antv/component'

 warning  in ./node_modules/@antv/g2plot/node_modules/@antv/g2/esm/theme/util/create-by-style-sheet.js

"export 'TOOLTIP_CSS_CONST' was not found in '@antv/component'

 warning  in ./node_modules/@antv/g2plot/node_modules/@antv/g2/esm/theme/util/create-by-style-sheet.js

"export 'TOOLTIP_CSS_CONST' was not found in '@antv/component'

 warning  in ./node_modules/@antv/g2plot/node_modules/@antv/g2/esm/theme/util/create-by-style-sheet.js

"export 'TOOLTIP_CSS_CONST' was not found in '@antv/component'

 warning  in ./node_modules/@antv/g2plot/node_modules/@antv/g2/esm/geometry/element/index.js

"export 'propagationDelegate' was not found in '@antv/component'

**Comment by lxfu1** [comment]
删除 node_modules 重新安装试试？

**Comment by hustcc** [comment]
还有删除 lock~

**Comment by wangangngg** [comment]
可以了，谢谢
