### ISSUE TITLE
👑 [需求]/@antv/g6的版本升级一下吧，webpack5下控制台好几个warning

### ISSUE THREAD

**Issue by YanYuanFE** [ant-design/ant-design-charts#400]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
![image](https://user-images.githubusercontent.com/17774285/103208100-c9f2de80-493a-11eb-81f7-05adba82ffcb.png)

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
升级g6到最新版

**Comment by lxfu1** [comment]
欢迎来个PR啊

**Comment by YanYuanFE** [comment]
发现问题是G6的一个包没有更新，详见如下issue：https://github.com/antvis/util/issues/46
给G6提issue了，尝试去修复了下，改了后跑不过test了，让他们修下吧。

**Comment by lxfu1** [comment]
1.0.14
