### ISSUE TITLE
🧐[问题] 堆叠分组柱状图能显示分组的求和总数吗？

### ISSUE THREAD

**Issue by zhangyongjiang** [ant-design/ant-design-charts#401]
<img width="658" alt="Screen Shot 2020-12-28 at 6 52 04 PM" src="https://user-images.githubusercontent.com/1043451/103255530-78e4e980-493e-11eb-9f88-25c70d2008ed.png">

**Comment by lxfu1** [comment]
https://charts.ant.design/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip

**Comment by zhangyongjiang** [comment]
It worked. Nice job. Thanks.
