### ISSUE TITLE
🐛[BUG] install 1.0.14版本 ,提示 IInteractorService is not exported,，编译失败

### ISSUE THREAD

**Issue by FanNanTx** [ant-design/ant-design-charts#406]
![image](https://user-images.githubusercontent.com/31879078/103404395-4fba9800-4b8e-11eb-8b3b-7d512286aa9c.png)

### © 版本信息

- ant-design-charts 版本: 1.0.14
- 浏览器环境
- 开发环境 ：
       react:17.0.0.1,
       node:14.4.0, 
      create-react-app,
      react-scripts:4.0.1

**Comment by xinghul** [comment]
Same error here, reverting back to 1.0.9 resolved it.

**Comment by magiclee203** [comment]
> Same error here, reverting back to 1.0.9 resolved it.

+1

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103432858-c5237880-4c21-11eb-97ee-013c2dc26e07.png)

**Comment by xqliu** [comment]
Same issue here, exactly same error as shown below

```
Creating an optimized production build...
Failed to compile.

./node_modules/@antv/g-webgpu-core/es/index.js 130:0-132:659
Attempted import error: 'IInteractorService' is not exported from './services/interactor/IIteractorService'.


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by lxfu1** [comment]
Reinstall,  npm i @ant-design/charts@1.0.13 -S.

**Comment by xqliu** [comment]
@lxfu1  Thanks, revert to 1.0.13 works
