### ISSUE TITLE
🐛[BUG] - The stock chart is showing candlesticks out of order when the array has more than 20 objects.

### ISSUE THREAD

**Issue by Marcosul** [ant-design/ant-design-charts#408]
### 🐛 bug description [Describe the bug in detail for everyone to understand]

The stock chart is showing candlesticks out of order when the array has more than 20 objects.

### 📷 Reproduction steps [Clearly describe the reproduction steps so that others can see the problem]

When the data array has 23 objects (candlestick), objectives with index 1 and 2 are shown at the end of the period, out of the correct order.

### 🏞 Expected results [describe what you expected to see]

All candlesticks are expected to be ordered on the chart equal to the data array

### 💻 Reproducible code [Provides reproducible code, deposit or example online]

DATA ARRAY:

ticksPreview: Array (23)
0: {time: 1609372800000, open: "7.22840000", high: "7.42160000", low: "7.14890000", close: "7.41990000",…}
1: {time: 1609374600000, open: "7.41990000", high: "7.55460000", low: "7.25660000", close: "7.26930000",…}
2: {time: 1609376400000, open: "7.26720000", high: "7.42140000", low: "7.12060000", close: "7.29780000",…}
3: {time: 1609378200000, open: "7.29680000", high: "7.43440000", low: "7.26100000", close: "7.42470000",…}
4: {time: 1609380000000, open: "7.42110000", high: "7.42470000", low: "7.30490000", close: "7.39790000",…}
5: {time: 1609381800000, open: "7.40260000", high: "7.41560000", low: "7.33440000", close: "7.36550000",…}
6: {time: 1609383600000, open: "7.36720000", high: "7.39960000", low: "7.31350000", close: "7.39530000",…}
7: {time: 1609385400000, open: "7.39530000", high: "7.51710000", low: "7.36650000", close: "7.39050000",…}
8: {time: 1609387200000, open: "7.39080000", high: "7.81920000", low: "7.39080000", close: "7.81310000",…}
9: {time: 1609389000000, open: "7.81290000", high: "8.10000000", low: "7.68560000", close: "7.92920000",…}
10: {time: 1609390800000, open: "7.92390000", high: "8.02220000", low: "7.82270000", close: "7.94930000",…}
11: {time: 1609392600000, open: "7.95360000", high: "8.13550000", low: "7.85000000", close: "8.08840000",…}
12: {time: 1609394400000, open: "8.08770000", high: "8.21900000", low: "8.06160000", close: "8.17780000",…}
13: {time: 1609396200000, open: "8.18110000", high: "8.18110000", low: "7.95660000", close: "7.99490000",…}
14: {time: 1609398000000, open: "7.99890000", high: "8.11630000", low: "7.87000000", close: "7.95750000",…}
15: {time: 1609399800000, open: "7.95990000", high: "8.06430000", low: "7.95990000", close: "8.04660000",…}
16: {time: 1609401600000, open: "8.04660000", high: "8.17000000", low: "7.96000000", close: "7.98070000",…}
17: {time: 1609403400000, open: "7.97560000", high: "8.09640000", low: "7.97560000", close: "8.05640000",…}
18: {time: 1609405200000, open: "8.05940000", high: "8.25610000", low: "7.93580000", close: "8.19460000",…}
19: {time: 1609407000000, open: "8.19910000", high: "8.34470000", low: "8.15460000", close: "8.31000000",…}
20: {time: 1609408800000, open: "8.30960000", high: "8.30960000", low: "8.15000000", close: "8.23650000",…}
21: {time: 1609410600000, open: "8.23540000", high: "8.23860000", low: "8.10400000", close: "8.18710000",…}
22: {time: 1609412400000, open: "8.18700000", high: "8.18800000", low: "8.17870000", close: "8.18280000",…}

GRAPHIC WITH THE SECOND AND THIRD OBJECT RENDERIZED AT THE END OF THE PERIOD:

![image](https://user-images.githubusercontent.com/4714018/103408849-0133dc00-4b43-11eb-9a3b-a2fecda6e1d8.png)

**Comment by Marcosul** [comment]
even with a number of candlesticks the chart is being lied out of the array order

![image](https://user-images.githubusercontent.com/4714018/103440494-eb96e300-4c24-11eb-9cba-506b6af21cfd.png)

**Comment by jinhuiWong** [comment]
Can you provide an online demo ？
[https://codesandbox.io/s/gallant-ride-9g4be?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/gallant-ride-9g4be?fontsize=14&hidenavigation=1&theme=dark)
