### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by liuajingliu** [ant-design/ant-design-charts#410]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
请问一下单轴折线图在数据只有一个月时，会默认居中展示
![截屏2021-01-04 上午10 44 54](https://user-images.githubusercontent.com/33769618/103496966-111d2a00-4e7b-11eb-865c-e7ea8d9e281c.png)
而双轴折线图在数据在数据只有一个月时，则不会
<img width="1133" alt="截屏2021-01-04 上午10 52 07" src="https://user-images.githubusercontent.com/33769618/103497028-301bbc00-4e7b-11eb-8d00-79415c8bf13c.png">
请问有什么属性可以设置为居中展示么

**Comment by lxfu1** [comment]
只有一个数据时手动设置一下range https://antv-g2plot.gitee.io/zh/docs/manual/faq

**Comment by Me-Momo** [comment]
> 只有一个数据时手动设置一下range https://antv-g2plot.gitee.io/zh/docs/manual/faq

让 艾因 看下，是否可以支持下；参考折线图

**Comment by liuajingliu** [comment]
应该是范围吧？
<img width="886" alt="截屏2021-01-05 上午10 05 32" src="https://user-images.githubusercontent.com/33769618/103598577-eb0c8e00-4f3d-11eb-9a16-e36074b702a9.png">
