### ISSUE TITLE
🐛[BUG] Zoom functionality doesn't work on column chart with both a custom color and slider

### ISSUE THREAD

**Issue by dougdellolio** [ant-design/ant-design-charts#411]
🐛 bug 描述 [详细地描述 bug，让大家都能理解]
When creating a basic column with a slider and custom colors, the zoom functionality of the chart and slider no longer works. 

📷 Reproduction steps [Clearly describe the reproduction steps so that others can see the problem]
Create a basic column. Define a custom color.  Add a slider. Move slider around 

🏞 Expected results [describe what you expected to see]
I expect the chart to zoom into the slider section when the slider is changed

💻 Reproducible code [Provides reproducible code, deposit or example online]
https://codesandbox.io/s/funny-wing-np3ob?file=/src/DemoColumn.js

The zoom in functionality seems to work only when removing the custom color section in the config from above. 

This library is excellent by the way, thanks for all the hard work.

**Comment by lxfu1** [comment]
Slider only work  on column, line, and area.

**Comment by dougdellolio** [comment]
This is for a column chart

**Comment by lxfu1** [comment]
update.

**Comment by dougdellolio** [comment]
what do I update to get this to work? I tried on version 1.0.17 and still seems to be an issue
