### ISSUE TITLE
🐛[BUG] 移动端将图表旋转90度，tooltip表现不正常

### ISSUE THREAD

**Issue by Y-HR** [ant-design/ant-design-charts#412]
有个需求是横屏查看图表，用了transform；但是横屏状态下图表项点击不了，tooltip也出不来，只有一小部分区域有反应

**Comment by Y-HR** [comment]
已经解决了，修改了supportCSSTransform属性

**Comment by wozien** [comment]
> 

你好请问下移动端是只在小程序还是h5？

**Comment by Y-HR** [comment]
> > 
> 
> 你好请问下移动端是只在小程序还是h5？

h5
