### ISSUE TITLE
🐛[BUG]图表组件使用报类型错误，几乎每个组件都有

### ISSUE THREAD

**Issue by NelsonYong** [ant-design/ant-design-charts#417]
例子：我使用官方的柱形图的例子，官方也吗明确支持ts，ts报类型不兼容，几乎每个组件都有

报错如下：
(alias) const Column: React.ForwardRefExoticComponent<ColumnConfig & React.RefAttributes<unknown>>
import Column
不能将类型“{ data: { type: string; sales: number; }[]; xField: string; yField: string; label: { position: string; style: { fill: string; opacity: number; }; }; meta: { type: { alias: string; }; sales: { alias: string; }; }; }”分配给类型“ColumnConfig”。
  属性“label”的类型不兼容。
    不能将类型“{ position: string; style: { fill: string; opacity: number; }; }”分配给类型“false | ({ readonly fields?: string[] | undefined; readonly callback?: LabelCallback | undefined; readonly formatter?: string | IGroup | IShape | GeometryLabelContentCallback | undefined; } & GeometryLabelCfg) | undefined”。
      不能将类型“{ position: string; style: { fill: string; opacity: number; }; }”分配给类型“{ readonly fields?: string[] | undefined; readonly callback?: LabelCallback | undefined; readonly formatter?: string | IGroup | IShape | GeometryLabelContentCallback | undefined; } & GeometryLabelCfg”。
        不能将类型“{ position: string; style: { fill: string; opacity: number; }; }”分配给类型“GeometryLabelCfg”。
          属性“position”的类型不兼容。
            不能将类型“string”分配给类型“"middle" | ((data: Record<string, any>, mappingData: MappingDatum, index: number) => IntervalGeometryLabelPosition) | ... 4 more ... | undefined”。ts(2322)

**Comment by NelsonYong** [comment]
急求

**Comment by NelsonYong** [comment]
问题已经解决，去到导出组件的地方，会有对应的类型导出
import type {ColumnConfig} from '@ant-design/charts/es/column/index.d'

**Comment by hustcc** [comment]
不用重复导出提 issue，也不要标题党，你认为的大 bug 很可能就是一个小问题，甚至不是问题。

**Comment by qianqianWXQ** [comment]
没有搞明白，你是怎么解决的，我也遇到了这个问题，请指教
