### ISSUE TITLE
👑 [需求]axis的label配置项能否支持如g2-v3一样的htmlTemplate呢

### ISSUE THREAD

**Issue by SpongeDad** [ant-design/ant-design-charts#419]
这是g2-v3的label配置，可以支持自定义html元素
但目前ant-design-chart好像只能利用formatter修改文案，不能自定义元素，请问什么版本或者以后可以支持呢
![image](https://user-images.githubusercontent.com/40929671/103986559-eeb24600-51c5-11eb-9d52-05bb3ecf1ef5.png)

**Comment by lxfu1** [comment]
G2 4.x、ant-design-chart 1.x 不再支持该属性。
