### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by songsng** [ant-design/ant-design-charts#423]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
scrollbar 水平滚动条配置 height 不生效
![image](https://user-images.githubusercontent.com/46083022/104095317-25c14e00-52d1-11eb-8c67-84902dbf8a9c.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
可以改变scrollbar的高度

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
"@ant-design/charts": "^1.0.11",
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
更新一下，或者使用 slider

```ts
slider | scrollbar: {
  start: 0.1,
  end: 0.2,
  height: 20
},
```
