### ISSUE TITLE
怎么设置图例分页按钮的大小

### ISSUE THREAD

**Issue by songsng** [ant-design/ant-design-charts#424]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://user-images.githubusercontent.com/46083022/104095483-0545c380-52d2-11eb-9e1b-2892ccf77bec.png)
按钮很难翻页

**Comment by lxfu1** [comment]
```ts
 legend: {
  pageNavigator: {
    marker: {
      style: {
        size: 20
      }
    }
  }
}
```
