### ISSUE TITLE
🧐[问题]请问饼图中events属性为什么不生效了？是删除了么？

### ISSUE THREAD

**Issue by yzy2857895027** [ant-design/ant-design-charts#429]
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

export default (props) => {
  const { data = [] } = props;

  data.map((item, index) => {
    let { value } = item;
    if (value === 0) {
      data.splice(index, 1);
    } else if (value) {
      item.value = parseInt(value);
    }
    return data;
  });

  const config = {
    appendPadding: 10,
    data: data || [],
    angleField: 'value',
    colorField: 'nameChinese',
    radius: 0.8,
    innerRadius: 0.64,
    // label: {
    //   type: 'inner',
    //   offset: '-0.5',
    //   content: '{percentage}',
    //   style: {
    //     fill: '#fff',
    //     fontSize: 14,
    //     textAlign: 'center',
    //   },
    // },
    statistic: {
      title: false,
      content: {
        style: { fontSize: 44 },
        formatter: function formatter() {
          return '';
        },
      },
    },
    label: {
      type: 'spider',
      content: '{percentage}',
    },
    legend: {
      layout: 'horizontal',
      position: 'bottom',
    },
    events:{
      onClick:(e)=>{
        console.log(e);
      }
    },
    'interactions': [{ type: 'element-selected' }, { type: 'element-active' }],
  };
  return <Pie {...config} />;

}

**Comment by Me-Momo** [comment]
1.x 版本，不再支持 `events` 属性，通过 `chartRef.on('事件名', callback)` 监听

**Comment by lxfu1** [comment]
https://charts.ant.design/zh-CN/guide/case#%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A
