### ISSUE TITLE
🧐[问题] chartRef和ref使用ts该如何定义？

### ISSUE THREAD

**Issue by zhangyu1818** [ant-design/ant-design-charts#43]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

组件的chartRef和ref的定义好像没有导出，该如何定义？

**Comment by xiaohuoni** [comment]
``` 
const chartRef = useRef<ChartProp>(null);
```

**Comment by zhangyu1818** [comment]
> ```
> const chartRef = useRef<ChartProp>(null);
> ```

ChartProp是哪里导出的呢，我只找到了图表的xxxConfig

**Comment by lxfu1** [comment]
chartRef 就是 React 的ref , 参考： https://charts.ant.design/guide#%E8%8E%B7%E5%8F%96-chart-%E5%AE%9E%E4%BE%8B

**Comment by zhangyu1818** [comment]
> chartRef 就是 React 的ref , 参考： https://charts.ant.design/guide#%E8%8E%B7%E5%8F%96-chart-%E5%AE%9E%E4%BE%8B

```
  const statisticsPlot = useRef();
  statisticsPlot.current?.changeData(statistics);
  // TS2339: Property 'changeData' does not exist on type 'never'.
```
我在ant design pro里使用，如果不标识useRef的类型不是会报错吗
想知道有没有类似`userRef<G2plotBar>()`这样的定义，现在我是用infer取的config里的chartRef定义

**Comment by xiaohuoni** [comment]
> > ```
> > const chartRef = useRef<ChartProp>(null);
> > ```
> 
> ChartProp是哪里导出的呢，我只找到了图表的xxxConfig

AreaConfig 就是 Prop 直接应该没有问题，我写的只是伪代码
