### ISSUE TITLE
🐛[BUG] 漏斗图的demo无法展示

### ISSUE THREAD

**Issue by lizhedyh** [ant-design/ant-design-charts#433]
### 🐛 bug 描述 
打开官方文档的漏斗图页面：https://charts.ant.design/demos/funnel
页面一片空白，控制台有红色报错提示，详见下图

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![WechatIMG76](https://user-images.githubusercontent.com/39264665/104450174-9ec6eb00-55da-11eb-8c57-675ec25188c5.jpeg)

**Comment by lxfu1** [comment]
已修复，刷新看看。
