### ISSUE TITLE
🧐[问题] 请问怎么实现折线图的Y轴反转？

### ISSUE THREAD

**Issue by qrk12** [ant-design/ant-design-charts#436]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
折线图正常是从高到低，现在需要从低到高的展示

**Comment by arcsin1** [comment]
你可以试试数组排序或者反转

**Comment by qrk12** [comment]
> 你可以试试数组排序或者反转

不是这个意思，现在折线Y轴数字从上到下是这样的10，5，3，0，现在需要Y轴数字上到下是0，3，5，10

**Comment by arcsin1** [comment]
sorry，目前，还没提供这个配置，你可以用g2写一个，你这个包里面是基于g2的，暂时急的话可以用g2定制一个这种图表哦。g2有转轴的配置，可以去看看哦，其实你的需求是吧x轴放到上面去，y轴从上往下

**Comment by qrk12** [comment]
> sorry，目前，还没提供这个配置，你可以用g2写一个，你这个包里面是基于g2的，暂时急的话可以用g2定制一个这种图表哦。g2有转轴的配置，可以去看看哦，其实你的需求是吧x轴放到上面去，y轴从上往下

以后会不会考虑加上这个配置？g2太麻烦了，我先用echarts配置一个参数就可以了

**Comment by arcsin1** [comment]
可以这么做，我刚才试了下，你拿到图表的实例： line.chart.coordinate('rect').reflect('y')

**Comment by arcsin1** [comment]
@qrk12  https://codesandbox.io/s/silly-kapitsa-j27rt?file=/App.tsx 可以看看，是你想要的哦！

**Comment by qrk12** [comment]
> @qrk12 https://codesandbox.io/s/silly-kapitsa-j27rt?file=/App.tsx 可以看看，是你想要的哦！

是的，非常感谢！！

**Comment by hzhijun** [comment]
> > @qrk12 https://codesandbox.io/s/silly-kapitsa-j27rt?file=/App.tsx 可以看看，是你想要的哦！
> 
> 是的，非常感谢！！
Y 轴翻转之后，想让 X 轴保留在底部，这个怎么实现呢？

**Comment by hzhijun** [comment]
我试了下使用这个方法将 X 轴保留在底部，实际效果是， X 轴还是在顶部，X 轴上的文字到了底部
chart.axis('Date', { position: 'top' });
