### ISSUE TITLE
🐛[BUG] 官网 - 「漏斗图页面」 访问异常

### ISSUE THREAD

**Issue by chenjunxyf** [ant-design/ant-design-charts#439]
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

页面白屏：https://charts.ant.design/demos/funnel/ 

### 🏞 期望结果 [描述你原本期望看到的结果]

正常显示

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
已修复，强制刷新一下。
