### ISSUE TITLE
🧐[问题] 图表网格线会跟随图例消失

### ISSUE THREAD

**Issue by Una-Gao** [ant-design/ant-design-charts#440]
### 🧐 问题描述 [详细地描述问题，让大家都能理解] 

双轴图和散点图的图例进行反选时，网格线会消失

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/68375674/104809816-f52a6880-582a-11eb-9039-552892ab3a71.png)

**Comment by lxfu1** [comment]
这个属于正常逻辑，可以配置 min max 来控制不更新 scale.
