### ISSUE TITLE
🧐[问题]TS类型报错

### ISSUE THREAD

**Issue by BigGoblin** [ant-design/ant-design-charts#441]
### 🧐 问题描述
TS类型报错
vscode 显示不存在属性
### 💻 示例代码
`<Pie colorField={"type"} />`

### 🚑 其他信息 
![image](https://user-images.githubusercontent.com/27881216/104869596-65e39900-5981-11eb-9dba-266907d781b9.png)

**Comment by visiky** [comment]
很多必选的属性还没有加上，比如 `data`, `angleField`

**Comment by BigGoblin** [comment]
> 很多必选的属性还没有加上，比如 `data`, `angleField`
 加了之后也是一样的
![image](https://user-images.githubusercontent.com/27881216/104870198-e3f46f80-5982-11eb-8463-e1cf27f18e56.png)
![image](https://user-images.githubusercontent.com/27881216/104870217-ea82e700-5982-11eb-9094-4d80c82fbad7.png)

**Comment by visiky** [comment]
是不是用错 antd-charts 版本？

**Comment by BigGoblin** [comment]
> antd-charts

使用的是1.0.13
![image](https://user-images.githubusercontent.com/27881216/104870668-09ce4400-5984-11eb-875d-59366764b8be.png)
