### ISSUE TITLE
🐛[BUG]yAxis设置max值后，直线图的点被覆盖

### ISSUE THREAD

**Issue by qlniu** [ant-design/ant-design-charts#446]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
给yAxis设置max值后，如果直线图中某个数据点的值是0或者是设置的max值， 折线上显示的点显示不全
![image](http://chuantu.xyz/t6/741/1611029826x-1922738960.png)
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
yAxis设置：
```
yAxis: {
    max: 100,
    tickInterval: 20,
  },
```
数据：
```
data=[{
key: '1', value: 20,
}, {
key: '2', value: 100,
}, {
key: '3', value: 0,
}, {
key: '4', value: 60,
}]
```

### 🏞 期望结果 [描述你原本期望看到的结果]
最值折现点不遮挡
![image](https://user-images.githubusercontent.com/46595240/104986920-50d53b80-5a4f-11eb-8e32-d6912256c7dc.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/fervent-snowflake-pu5gf?file=/App.tsx
### © 版本信息

- ant-design-charts 版本: [1.0.13]
- 浏览器环境 chrome
- 开发环境 [mac OS]

**Comment by lxfu1** [comment]
手动设置一下yAxis: {min: -10, max: 120} ?

**Comment by StoneCode5** [comment]
config设置这个属性limitInPlot为false
