### ISSUE TITLE
DualAxes 中 使用 slider 无法显示。

### ISSUE THREAD

**Issue by 3252152** [ant-design/ant-design-charts#447]
<DualAxes
        data={[rangePut, rangePercentPut]}
        xField="time"
        xAxis={{
          tickInterval: 60 * 30 * 1000,
          type: 'time',
          mask: 'HH:mm',
        }}
        padding="auto"
        yField={['value', 'count']}
        geometryOptions={[
          {
            geometry: 'line',
            seriesField: 'type',
            color: ['#2fc25b', '#1890ff'],
            point: {},
          },
          {
            geometry: 'line',
            seriesField: 'name',
            color: ['#facc14'],
            point: {},
          },
        ]}
        slider={{
          start: 0.1,
          end: 0.5,
        }}
      />

**Comment by lxfu1** [comment]
update.
