### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by xiaobindebingo** [ant-design/ant-design-charts#448]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
当动态改变图表width时，图表没有刷新;

### 🏞 期望结果 [描述你原本期望看到的结果]
期望当config中的width改变后，图表能重新渲染
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://riddle.alibaba-inc.com/riddles/581c9065
### © 版本信息

- ant-design-charts 版本: [1.0.13]
- 浏览器环境 [chorme]
- 开发环境 [mac OS]

**Comment by lxfu1** [comment]
把 width 设置在外层容器就好了; 
`<div style={{width}}><Line /></div>`
