### ISSUE TITLE
tooltip的formatter配置的出参格式

### ISSUE THREAD

**Issue by zogeli100** [ant-design/ant-design-charts#45]
疑问：
关于tooltip的formatter配置的出参格式可选值，文档里不够全。
目前只知道{ name: '',  value: '' , title: ''} 

补充疑问：
![image](https://user-images.githubusercontent.com/16754955/82985522-bc811900-a026-11ea-8c28-3d0f549d3349.png)
tooltips是否支持加配，将后面的百分比另起一行展示（  占比：  50%）
或则是在customContent里自定义？

**Comment by zogeli100** [comment]
新发现问题：
用customContent自定义的时候，首次hover不会触发回调，第二次后才看到自己补充的数据行。
（文档里为啥没有customContent，当然formatter直接支持多行自定义是极好的）
```
tooltip:{
      customContent:{
        callback:(container, cfg)=>{
          const { items } = cfg;
          items.push({
            ...items[0],
            name: '占比',
            value: '30%',
            marker: false,
              color: null,
          })
        }
    },
```

**Comment by lxfu1** [comment]
这个功能我们新增一下，tooltip 支持 ReactNode。

**Comment by lxfu1** [comment]
https://charts.ant.design/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip

**Comment by ChenWeihua123** [comment]
@zogeli100 大佬 Pie 组件 toolttip 你是怎么显示的百分比的呢

**Comment by zogeli100** [comment]
> @ zogeli100大佬Pie组件toolttip你是怎么显示的百分比的呢

https://g2plot.antv.vision/zh/docs/manual/plots/pie   官方文档里有，Pie - tooltip - formatter

**Comment by brushbird** [comment]
> https://charts.ant.design/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip

饼图获取不到数据，参数title和items是null，然后就报了个replace的错
![image](https://user-images.githubusercontent.com/20636542/86551491-bb250380-bf77-11ea-924e-0f2171d4c9b1.png)

**Comment by yueyang-kla** [comment]
@brushbird 我也遇到一样的情况，请问你解决了吗？

**Comment by yueyang-kla** [comment]
@lxfu1 饼图/环图自定义tooltip时，会有读不到title和items的bug，并报"typeError: str.replace is not a function"。折线图运行良好。请做下修改，谢谢！

**Comment by lxfu1** [comment]
update

**Comment by afc163** [comment]
update 是什么意思？

**Comment by areyouse7en** [comment]
解决了吗？
