### ISSUE TITLE
🐛[BUG]Ant-Charts 中的词云图页面崩了

### ISSUE THREAD

**Issue by yzy2857895027** [ant-design/ant-design-charts#450]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
点击词云图之后页面空白，console报错

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/64308038/105138397-c57fa700-5b2f-11eb-88dd-3b51cdc9fc74.png)

**Comment by YanYuanFE** [comment]
+1

**Comment by yzy2857895027** [comment]
![image](https://user-images.githubusercontent.com/64308038/105138465-e21bdf00-5b2f-11eb-803e-4fb5739e00f1.png)

**Comment by lxfu1** [comment]
底层升级出现的问题，今晚会发布。

**Comment by lxfu1** [comment]
强制刷新一下。
