### ISSUE TITLE
👑 [需求]给legend 增加tooltip

### ISSUE THREAD

**Issue by mrqiaobo** [ant-design/ant-design-charts#452]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
当数据量比较大，分配比较多的情况下，仅仅靠饼图的tooltip无法有效显示，并且legend显示不全type，此时如果能有一个tooptip悬浮在legend上，帮助用户看到这个是什么type

**Comment by circletop** [comment]
请问下这个功能能实现了吗，现在我这边也有这种需求，不知道如何着手，或者问一下，有其他曲线救国的方式吗
