### ISSUE TITLE
如何通过js去操作legend属性中的name显隐

### ISSUE THREAD

**Issue by lgf196** [ant-design/ant-design-charts#455]
我隐藏了legend属性，想自已写一个legend的标题，来控制显影，但是不知道怎么通过这个对象，去设置这个操作，如下
![image](https://user-images.githubusercontent.com/29600558/105163205-9593cc00-5b4e-11eb-9dd0-a6b862eb82a9.png)

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/432
