### ISSUE TITLE
🐛[BUG] 在 TypeScript 中使用时，无法导入接口定义

### ISSUE THREAD

**Issue by chhpt** [ant-design/ant-design-charts#456]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

在 TypeScript 中使用时，无法导入 Pie 的接口定义

![image](https://user-images.githubusercontent.com/19288423/105314675-2b843100-5bf9-11eb-9736-bb239ec52dfa.png)

### 🏞 期望结果 [描述你原本期望看到的结果]

支持导入组件的接口定义

### © 版本信息

- ant-design-charts 版本: 1.0.15
- 浏览器环境：Chrome 87
- 开发环境 macOS

**Comment by lxfu1** [comment]
import { PieConfig } from "@ant-design/charts/lib/pie";

**Comment by 985563349** [comment]
> 

这种方式找不到模块，目前我的导入方式：import type { PieConfig } from '@ant-design/plots/lib/components/pie';
