### ISSUE TITLE
🐛[BUG] scrollbar does not work for DualAxes 

### ISSUE THREAD

**Issue by zhaofinger** [ant-design/ant-design-charts#459]
## 问题描述
DualAxes 使用 scrollbar 不生效

## 示例代码
[codesandbox](https://codesandbox.io/s/throbbing-cache-t1spv?file=/App.tsx)

**Comment by lxfu1** [comment]
Use slider.

**Comment by Andrewuetyang** [comment]
> Use slider.

根据文档，DualAxes根本没有slider的配置，如何用呀，大佬？

**Comment by Andrewuetyang** [comment]
> Use slider.

@lxfu1 According to the documentation, there is no slider options, so could you please describe more detail about your solution? thank you so much.

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/489
