### ISSUE TITLE
👑 [需求] 请问支持 地图吗？

### ISSUE THREAD

**Issue by yilo** [ant-design/ant-design-charts#466]
### 🥰 需求描述
请问支持 地图吗？

**Comment by lxfu1** [comment]
近期会支持。

**Comment by yilo** [comment]
> 近期会支持。

嗯， 感谢。 
另外， 使用 BizChart4里面的Map 会和G2Plot 冲突吗？ G2已经有Map了， G2Plot会是一样的方式吗？后面可以平滑迁移吗？

**Comment by hustcc** [comment]
@yilo 如果不敏感的话，可以方便贴一下你们对于地图的需求粗略设计。

charts 中的地图，会直接依赖 L7 去实现，暂时不是以 G2 的简单的地图底图实现。

**Comment by wildwood151** [comment]
啥时候上？有这个需求，不想再引一个G2的包了

**Comment by lxfu1** [comment]
参考示例，直接从 maps 里面引入即可。

https://charts.ant.design/zh/examples/gallery#category-%E5%8C%BA%E5%9F%9F%E5%A1%AB%E5%85%85

```ts
import {xx} from '@ant-design/maps'
```
