### ISSUE TITLE
🐛[BUG]tickCount 设成0，页面会崩溃，可以做个参数校验吗

### ISSUE THREAD

**Issue by XiaoJiuDYS** [ant-design/ant-design-charts#47]
### 🐛 bug 描述 
设置坐标轴无意间设成了0，本来是想20改10的，删了2后触发页面自动刷新，然后整个页面就崩溃了。
后面看了下G2-plot也有这个问题。。。

### 📷 复现步骤 
设置xAxis 的tickCount为0

### 🏞 期望结果 
该tickCount 设置不生效，控制台给出警告信息

### © 版本信息

- ant-design-charts 版本:  0.9.4
- 浏览器环境Chrome 81.0.4044.138
- 开发环境  mac OS

**Comment by lxfu1** [comment]
可以的 下个版本加上
