### ISSUE TITLE
How to change bar color after a threshold value?

### ISSUE THREAD

**Issue by pranitv2stech** [ant-design/ant-design-charts#474]
Is it possible to change the color of bar after some threshold value (not using stacked bar chart)? 

I used the annotations to show different color on bar after some value, but the annotation line and region is starting from middle of first bar and ending at middle of last bar. any way to fix this and show different color on bar ?

![barChart](https://user-images.githubusercontent.com/51791997/105994252-6db3e380-60cd-11eb-8f51-37e3bf42e759.png)

my example: https://codesandbox.io/s/gallant-clarke-6dt2h?file=/App.tsx

**Comment by lxfu1** [comment]
```ts
annotations: [
      {
        type: "line",
        start: ["start", 100],
        end: ["end", 100],
        style: {
          stroke: "#FFA39E",
          lineWidth: 1
        }
      },
      {
        type: "regionFilter",
        start: ["start", "end"],
        end: ["end", 100],
        color: "l(0) 0:#FA8C16 1:#FA541C"
      }
    ]
```

**Comment by pranitv2stech** [comment]
@lxfu1 , Thank you. It worked.
