### ISSUE TITLE
🧐[问题]关于G6，是必须要包含的吗？

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design-charts#475]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我发现G6特别大，我只想引用charts，使用g2plot的react写法，G6并没有用到，但是默认引入了吧？
我发现那个G6.min有接近2M。
请问有办法删除这个依赖吗？

**Comment by lxfu1** [comment]
使用 CDN 的方式？ https://charts.ant.design/zh-CN/guide/start

**Comment by phoema** [comment]
主要是想不明白为什么依赖G6啊？
https://charts.ant.design/zh-CN/guide

**Comment by lxfu1** [comment]
> 主要是想不明白为什么依赖G6啊？
> https://charts.ant.design/zh-CN/guide

Charts  是 AntV 的上层库，图表类型不局限于 G2Plot ，npm 的方式如果没有用到 G6 相关的图表， 打包是不会把 G6 代码构建进去的。

**Comment by phoema** [comment]
别的都是按需，就这个是min.js文件

![image](https://user-images.githubusercontent.com/8730272/106101971-a7422880-6179-11eb-854c-d7624ee2fabf.png)

**Comment by arcsin1** [comment]
这个问题 确实是没有按需，打包肯定是打进去了，需要解决下 @lxfu1

**Comment by lxfu1** [comment]
G6的问题，下个版本会修复。

**Comment by lxfu1** [comment]
执行下 update.

**Comment by phoema** [comment]
版本号变了吗，ant-design/charts我从仓库看还是1.0.17

**Comment by lxfu1** [comment]
> 版本号变了吗，ant-design/charts我从仓库看还是1.0.17

底层依赖变了， 重新安装会更新底层依赖。

**Comment by phoema** [comment]
更新完，大了100K

yarn upgrade webpack   @ant-design/charts

"@ant-design/charts@1.0.17":
  version "1.0.17"
  resolved "https://registry.npm.taobao.org/@ant-design/charts/download/@ant-design/charts-1.0.17.tgz#1ec5a98f78ba7bd65137f3ba5581ae0d12527064"
  integrity sha1-HsWpj3i6e9ZRN/O6VYGuDRJScGQ=
  dependencies:
    "@antv/g2plot" "^2.2.11"
    "@antv/g6" "^4.1.1"
    "@antv/util" "^2.0.9"
    react-content-loader "^5.0.4"

"@antv/g6@^4.1.1":
  version "4.1.7"
  resolved "https://registry.npm.taobao.org/@antv/g6/download/@antv/g6-4.1.7.tgz#096144ee5896a6afa46dfb6b7ae6ba6ffd4603f8"
  integrity sha1-CWFE7liWpq+kbftreua6b/1GA/g=
  dependencies:
    "@antv/g6-pc" "^0.0.12"


min.js不在g6里了，跑到g6-pc里去了
![image](https://user-images.githubusercontent.com/8730272/106419389-58570480-6493-11eb-9f24-af85d6a2a61b.png)

**Comment by Yanyan-Wang** [comment]
> 更新完，大了100K
> 
> yarn upgrade webpack @ant-design/charts
> 
> "@ant-design/charts@1.0.17":
> version "1.0.17"
> resolved "https://registry.npm.taobao.org/@ant-design/charts/download/@ant-design/charts-1.0.17.tgz#1ec5a98f78ba7bd65137f3ba5581ae0d12527064"
> integrity sha1-HsWpj3i6e9ZRN/O6VYGuDRJScGQ=
> dependencies:
> "@antv/g2plot" "^2.2.11"
> "@antv/g6" "^4.1.1"
> "@antv/util" "^2.0.9"
> react-content-loader "^5.0.4"
> 
> "@antv/g6@^4.1.1":
> version "4.1.7"
> resolved "https://registry.npm.taobao.org/@antv/g6/download/@antv/g6-4.1.7.tgz#096144ee5896a6afa46dfb6b7ae6ba6ffd4603f8"
> integrity sha1-CWFE7liWpq+kbftreua6b/1GA/g=
> dependencies:
> "@antv/g6-pc" "^0.0.12"
> 
> min.js不在g6里了，跑到g6-pc里去了
> ![image](https://user-images.githubusercontent.com/8730272/106419389-58570480-6493-11eb-9f24-af85d6a2a61b.png)

G6 更新到 4.1.7 试试

**Comment by prettyboyweiwei** [comment]
+1， 1.0.17 同样的问题，而更早的1.0.7 没有此问题。

**Comment by mizhousoft** [comment]
+1， 1.0.17 同样的问题

**Comment by lxfu1** [comment]
https://github.com/antvis/G6/pull/2662

**Comment by lxfu1** [comment]
> [antvis/G6#2662](https://github.com/antvis/G6/pull/2662)

底层使用了browser，上层没法做按需，已经提PR.

**Comment by lxfu1** [comment]
先使用 lib 的方式， 或者使用 webpack 的 alias ， 近期提供插件支持按需。
```ts
import Bar from "@ant-design/charts/lib/bar";
```

**Comment by lxfu1** [comment]
https://github.com/ant-design/babel-plugin-import  
.babelrc
```ts
{
  "plugins": [
    ["import", {
      "libraryName": "@ant-design/charts",
      "libraryDirectory": "lib"
    }]
  ]
}
```

**Comment by phoema** [comment]
umi架构也是这种写法吗？

**Comment by lxfu1** [comment]
> umi架构也是这种写法吗？

是的

**Comment by phoema** [comment]
最新版本1.0.19也需要这样吗？

**Comment by lxfu1** [comment]
> 最新版本1.0.19也需要这样吗？

需要
方案一： 从 lib 或者 es 里面引入（import Bar from "@ant-design/charts/lib/bar";）
方案二：引入方式不变，添加 plugin （import { Bar } from "@ant-design/charts";）

**Comment by mizhousoft** [comment]
每发布一个版本，能不能写个changelog？

**Comment by lxfu1** [comment]
> > 最新版本1.0.19也需要这样吗？
> 
> 需要
> 方案一： 从 lib 或者 es 里面引入（import Bar from "@ant-design/charts/lib/bar";）
> 方案二：引入方式不变，添加 plugin （import { Bar } from "@ant-design/charts";）

https://charts.ant.design/zh-CN/guide/faq#6%E3%80%81%E6%89%93%E5%8C%85%E6%96%87%E4%BB%B6%E8%BF%87%E5%A4%A7%EF%BC%8C%E5%A6%82%E4%BD%95%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD
