### ISSUE TITLE
🧐[问题]桑基图source, target, 这两个字段 不论哪个是字符串类型的数字例如："123",都会有问题

### ISSUE THREAD

**Issue by sibyl1218** [ant-design/ant-design-charts#476]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
有数字的效果错误效果  ![image](https://user-images.githubusercontent.com/49046565/106106761-fb044000-6180-11eb-8fb4-7bbcae2c302d.png)

没有数字的效果  ![image](https://user-images.githubusercontent.com/49046565/106106883-271fc100-6181-11eb-9f7b-602b4a976b1e.png)

**Comment by lxfu1** [comment]
https://codesandbox.io/s/thirsty-currying-g4v9wq?file=/App.tsx
