### ISSUE TITLE
🐛[BUG] 漏斗图设置conversionTag

### ISSUE THREAD

**Issue by yilo** [ant-design/ant-design-charts#477]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
默认配置：        conversionTag: {offsetX: 10, offsetY: 0, formatter: (datum:any) => 'Rate:' + datum.$$percentage$$ * 100 + '%',},

如下图
![image](https://user-images.githubusercontent.com/3793679/106248982-b7770800-624c-11eb-8d25-5f677c5eb1e6.png)

不设置 conversionTag 很正常
![image](https://user-images.githubusercontent.com/3793679/106249056-cc539b80-624c-11eb-93bb-319daebe03e5.png)

另外：

宽度无法自适应？
![image](https://user-images.githubusercontent.com/3793679/106249256-19377200-624d-11eb-891e-d7b143b98e69.png)

### © 版本信息

- ant-design-charts 版本: [1.0.17]
- 浏览器环境 【chrome】
- 开发环境 [ mac OS]

**Comment by lxfu1** [comment]
```ts
 datum.$$percentage$$.toFixed(2) * 100
```
可以设置一下字体颜色。
