### ISSUE TITLE
Is it possible to hide axis and background lines in the Column chart?

### ISSUE THREAD

**Issue by rkazakov** [ant-design/ant-design-charts#479]
Hello,

![Screen Shot 2021-01-29 at 11 56 33 pm](https://user-images.githubusercontent.com/168863/106277979-042f0300-628e-11eb-81fc-2c2e58d75ffc.png)

Is it possible to hide axis and background lines in the Column chart? Please see the image attached above.

Thanks,

Ruslan

**Comment by pranitv2stech** [comment]
xAxis: {
      grid: null,
      label: null
},
yAxis: {
      grid: null,
      label: null
}

**Comment by rkazakov** [comment]
@pranitv2stech That's awesome! Thank you!
