### ISSUE TITLE
🐛[可优化]默认情况下x轴的标题与坐标轴的单位重合显示

### ISSUE THREAD

**Issue by XiaoJiuDYS** [ant-design/ant-design-charts#48]
### 🐛 bug 描述 
默认x轴标题会与坐标轴刻度显示重合，可以优化就优化下吧

### 📷 复现步骤
给x轴设置标题

### 🏞 期望结果
默认情况下x轴标题与刻度是分开的，不需要手动设置offset。 

### 💻 复现代码
https://codesandbox.io/s/kq0m6?module=/demo.tsx&file=/demo.tsx

### © 版本信息

- ant-design-charts 版本: 0.9.4
- 浏览器环境 chrome 81.0
- 开发环境  mac os

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/36301924/83225236-e155c780-a1b1-11ea-8b78-1218cbf2ac7a.png)

**Comment by lxfu1** [comment]
嗯嗯 我们修复一下

**Comment by lxfu1** [comment]
底层依赖已经更新了， update 一下。

**Comment by XiaoJiuDYS** [comment]
@lxfu1 
是不是还没推，依旧存在这个问题🧐
还是要等到下次发版的时候才会有

**Comment by XiaoJiuDYS** [comment]
已确认该问题已被修复
