### ISSUE TITLE
🧐[问题]charts支持按需引入样式吗？

### ISSUE THREAD

**Issue by lizhedyh** [ant-design/ant-design-charts#481]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
是否能像antd一样，通过在babel里进行如下配置，实现样式的按需引入
plugins: [
               ['import',[{  // 导入一个插件
                 libraryName: 'antd',   // 暴露的库名
                 style: true // 直接将ants样式文件动态编译成行内样式插入，就不需要每次都导入
               }]]
             ],
<img width="703" alt="截屏2021-02-01 下午12 09 12" src="https://user-images.githubusercontent.com/39264665/106414521-bc73cb80-6487-11eb-8b6e-650717ef2fec.png">

[](url)

**Comment by lxfu1** [comment]
没理解~

**Comment by lizhedyh** [comment]
> 没理解~

我更新了一下问题描述...

**Comment by lxfu1** [comment]
不支持。

**Comment by lizhedyh** [comment]
> 不支持。

以后会考虑支持吗？

**Comment by lxfu1** [comment]
Charts 里面样式比较少，支持的可能性不大。

**Comment by lizhedyh** [comment]
> Charts 里面样式比较少，支持的可能性不大。

好的，了解了
