### ISSUE TITLE
🐛[BUG] 环图 更新数据源数据 视图不更新

### ISSUE THREAD

**Issue by YuShengSenior** [ant-design/ant-design-charts#482]
### 🐛 bug 描述  
使用按钮改变环图数据源数据,点击按钮后视图无变化,无报错信息

### 📷 复现步骤  
点击按钮更改数据源数据,数据源已更改,视图未更新

### 🏞 期望结果  
点击按钮,数据源变化,视图随之改变

### 💻 复现代码 
https://codesandbox.io/s/quirky-carson-pkz92?file=/src/App.jsx

### © 版本信息

- ant-design-charts 版本: [1.0.17]
- react 版本 17.0.1
- 浏览器环境  Chrome 88.0.4324.104（正式版本） （64 位）
- 开发环境 [Windows 10]

**Comment by prettyboyweiwei** [comment]
this.config 不是响应数据，把 config 放在 render() 里就好了

**Comment by YuShengSenior** [comment]
> this.config 不是响应数据，把 config 放在 render() 里就好了

好用了好用了谢大佬
