### ISSUE TITLE
🐛[BUG]开启滚动条时柱状图数据更新后图表高度没有重新计算缩放

### ISSUE THREAD

**Issue by prettyboyweiwei** [ant-design/ant-design-charts#483]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
开启 scrollbar配置时，柱状图数据源 state.list 更新后，如果新加入的数据里有数字大于原有的数据，则会超出图表的 Y 轴显示

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
开启 scrollbar={{}}，setTimeout 后更新柱状图数据源

### 🏞 期望结果 [描述你原本期望看到的结果]
图表重新计算 Y 轴，使数据都在图表内

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/busy-oskar-ph19z?file=/App.tsx

### © 版本信息

- ant-design-charts 版本: [1.0.17]
- 浏览器环境 chrome [88.0.4324.96]
- 开发环境 [mac OS]

**Comment by prettyboyweiwei** [comment]
还有一个普遍的场景，应该是同样的原因导致的：
如果 state.list = [] ，请求完数据 state.list 才有数据，此时只有 X 轴能看到变化，Y 轴是空白没有变化。
https://codesandbox.io/s/nifty-dubinsky-fxxvi?file=/App.tsx

**Comment by boiboif** [comment]
摆了吗  快两年了没人修

**Comment by lxfu1** [comment]
很久很久之前就修复了，忘记回复，用最新的 plots `import { Column } from "@ant-design/plots";`
