### ISSUE TITLE
🐛[BUG] Treemap矩形树图无法从@ant-design/charts包中导出

### ISSUE THREAD

**Issue by Credv** [ant-design/ant-design-charts#487]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
引入矩形树图使用时报错
Attempted import error: 'Treemap' is not exported from '@ant-design/charts'.
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
import { Treemap } from '@ant-design/charts'; 
 <Treemap {...config} />; 
### 🏞 期望结果 [描述你原本期望看到的结果]
能够使用矩形树图

### © 版本信息

- ant-design-charts 版本: 1.0.1]
- 浏览器环境 chrome
- 开发环境 [win10]

**Comment by lxfu1** [comment]
update 1.0.17
