### ISSUE TITLE
Line 组件y轴数据大的时候，小数据的值看不到效果，在0刻度尺

### ISSUE THREAD

**Issue by lgf196** [ant-design/ant-design-charts#490]
![image](https://user-images.githubusercontent.com/29600558/106982253-b25f0f00-679e-11eb-9c0c-8fb0c39913bc.png)

**Comment by lgf196** [comment]
其实我有3组数据的值，但是数据小的类型，完全看不到效果，如上图

**Comment by hustcc** [comment]
@lgf196 这种数据的情况下，有两种办法：

1. y 轴使用 log 轴
2. 使用双轴图（左侧是 万 级别的数据，右侧是 个 级别的数据）

**Comment by lxfu1** [comment]
> @lgf196 这种数据的情况下，有两种办法：
> 
> 1. y 轴使用 log 轴
> 2. 使用双轴图（左侧是 万 级别的数据，右侧是 个 级别的数据）

我记得有个后门 ~
```ts
yAxis: {
    min: undefined,
},
```

**Comment by lgf196** [comment]
> @ lgf196这种数据的情况下，有两种方法：
> 
> 1. y轴使用log轴
> 2. 使用双轴图（左侧是万等级的数据，右侧是个等级的数据）
我设置了log但是不行，出现了如下图的情况
    yAxis:{
      tickCount: 10,
      tickMethod:'log'
    }
    
![image](https://user-images.githubusercontent.com/29600558/106985074-b7728d00-67a3-11eb-99bd-5476aac34a18.png)

**Comment by hustcc** [comment]
```ts
yAxis: {
  type: 'log',
  base: 100,
}
```

不过还是建议用双轴图。

**Comment by lgf196** [comment]
> ```ts
> yAxis: {
>   type: 'log',
>   base: 100,
> }
> ```
> 
> 不过还是建议用双轴图。

感谢 :blush: :rose: :rose:
