### ISSUE TITLE
🐛[slider] 调整区间的两个滑块不显示

### ISSUE THREAD

**Issue by taofeifanIT** [ant-design/ant-design-charts#497]
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
const DemoLine= () => {
  const [data, setData] = useState([]);
  useEffect(() => {
    asyncFetch();
  }, []);
  const asyncFetch = () => {
    fetch('https://gw.alipayobjects.com/os/bmw-prod/55424a73-7cb8-4f79-b60d-3ab627ac5698.json')
      .then((response) => response.json())
      .then((json) => setData(json))
      .catch((error) => {
        console.log('fetch data failed', error);
      });
  };
  var config = {
    data: data,
    xField: 'year',
    yField: 'value',
    seriesField: 'category',
    yAxis: {
      label: {
        formatter: function formatter(v) {
          return ''.concat(v).replace(/\d{1,3}(?=(\d{3})+$)/g, function (s) {
            return ''.concat(s, ',');
          });
        },
      },
    },
    color: ['#1979C9', '#D62A0D', '#FAA219'],
    slider: {},
  };
  return <Line {...config} />;
};
### © 版本信息

- ant-design-charts 版本: [1.0.17]
- 浏览器环境： 谷歌
- 开发环境 [window10]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/42193371/108450912-e22f0c00-72a0-11eb-8bd2-b01db9c9eb6e.png)

**Comment by lxfu1** [comment]
底层问题  @visiky 确认下什么时候发布。

**Comment by visiky** [comment]
已经发了

**Comment by lxfu1** [comment]
删除 node_modules 重新 install 一下。

**Comment by taofeifanIT** [comment]
好的，谢谢
