### ISSUE TITLE
使用line的时候build 报错：Uncaught (in promise) TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by mystery66** [ant-design/ant-design-charts#499]
本地使用1.0.17版本，没有问题。但是更新到1.0.18版本，就会出现Super expression must either be null or a function。版本固定后使用1.0.17build也会出现上面问题

**Comment by lxfu1** [comment]
错误截图发一下。

**Comment by mystery66** [comment]
![Uploading image.png…]()

**Comment by mystery66** [comment]
![image](https://user-images.githubusercontent.com/38375406/108652699-b8275500-74ff-11eb-912b-19a7068ca99c.png)

**Comment by mystery66** [comment]
找了几个版本都不行，一直降版本直到1.0.11版本，能正常运行

**Comment by lxfu1** [comment]
代码能上传 github 吗？感觉是底层问题

**Comment by mystery66** [comment]
代码是公司的项目不太方便，但是用官网上的demo也会出现这种问题，是不是line这个组件在高版本用了啥第三方的依赖，对方也更新了出现不兼容问题。
