### ISSUE TITLE
打包包错

### ISSUE THREAD

**Issue by XuHatcher** [ant-design/ant-design-charts#50]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
打包报错信息：
Failed to minify the code from this file:
 	./node_modules/d3-regression/src/utils/points.js:5
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
![image](https://user-images.githubusercontent.com/18131576/83355568-d017e100-a392-11ea-8807-43ed96bebfc0.png)
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
version：0.9.4

**Comment by lxfu1** [comment]
升级node 10+ 试试

**Comment by XuHatcher** [comment]
> 升级node 10+ 试试

本地node版本是10.15.3  也是报同样的问题

**Comment by lxfu1** [comment]
方便提供一下复现代码吗？

**Comment by XiangPeng1993** [comment]
我也遇到这个问题，react-create-app + Ant Design Charts  npm run build打包报错，但是 npm start本地运行是好的。 @XuHatcher  请问你是怎么解决的？

**Comment by ybzjsxh** [comment]
我也碰到了这个问题，node版本是12.18.0，@ant-design/charts: 0.9.6，请问要如何解决呢

**Comment by ybzjsxh** [comment]
> 我也碰到了这个问题，node版本是12.18.0，@ant-design/charts: 0.9.6，请问要如何解决呢

在g2/plot的[issues](https://github.com/antvis/G2Plot/issues/1023#issuecomment-628363097)里面的找到了方法，在webpack.config.prod.js里面配置alias，如下
```js
alias: {
    ...,
    'd3-regression': 'd3-regression/dist/d3-regression.js',
}
```
就能打包成功了👀

**Comment by rkumar1904** [comment]
> > I also encountered this problem, the node version is 12.18.0, @ant-design/charts: 0.9.6, how can I solve it?
> 
> Found a method in the [issues of](https://github.com/antvis/G2Plot/issues/1023#issuecomment-628363097) g2/plot , configure alias in webpack.config.prod.js, as follows
> 
> ```js
> alias: {
>     ...,
>     'd3-regression': 'd3-regression/dist/d3-regression.js',
> }
> ```
> 
> Can be packaged successfully👀

I've tried the above solutions but did not work... still the same issue!
