### ISSUE TITLE
Draw empty columns with Column chart

### ISSUE THREAD

**Issue by Acidic9** [ant-design/ant-design-charts#504]
(Sorry, this issue will be in Englush)

### 🧐 Problem description

Using the Column chart, I have a dataset for example:
```js
[
  { date: '01-01-2021', count: 3 },
  { date: '02-01-2021', count: 7 },
  { date: '03-01-2021', count: 0 },
  { date: '04-01-2021', count: 0 },
  { date: '05-01-2021', count: 0 },
  // ...
]
```
![Screenshot of current chart](https://imgur.com/4R8iuGd.jpg)

I would like to fill in the empty parts of the chart with a small so it is not completely empty.

For example:

![Screenshot of graph with filled in empty columns](https://imgur.com/G2MhYnC.jpg)

Is it supported? I simply want empty/0 values to be still drawn with a very small height.

**Comment by lxfu1** [comment]
Process 1% of data with a maximum value of 0 ？

**Comment by Acidic9** [comment]
@lxfu1 I'm not sure what you mean exactly

**Comment by lxfu1** [comment]
Configuration is not currently supported. Modify data manually.

**Comment by Acidic9** [comment]
Okay, I hope this could be added in the future

**Comment by lxfu1** [comment]
This is not a good idea and will not be supported.
