### ISSUE TITLE
使用自定义theme时，混合图的axis未按照theme设置的颜色显示🐛[BUG]

### ISSUE THREAD

**Issue by jwwwww** [ant-design/ant-design-charts#507]
### 🐛 bug 描述 使用自定义theme时，混合图的axis未按照theme设置的颜色显示

![image](https://user-images.githubusercontent.com/22487180/109132545-ea021b00-778e-11eb-87e6-c45d1e3aec32.png)

### 💻 复现代码 
**折线图** （可以只看加粗部分，其他的直接复制的例子）
var config = {
    data: data,
    padding: 'auto',
    xField: 'Date',
    yField: 'scales',
    **theme: darkTheme,
    onReady: (charts) => {
      console.log(charts)
    },**
    xAxis: {
      type: 'timeCat',
      tickCount: 5,
    },
  };
**混合图**
 var config = {
    data: [uvData, transformData],
    xField: 'time',
    yField: ['value', 'count'],
    **theme: darkTheme,
    onReady: (charts) => {
      console.log(charts)
    },**
   geometryOptions: [
      {
        geometry: 'column',
        columnWidthRatio: 0.4,
      },
      {
        geometry: 'line',
        seriesField: 'name',
      },
    ],
  };
 **darkThemeo配置：**
![image](https://user-images.githubusercontent.com/22487180/109133497-081c4b00-7790-11eb-9ae2-4e411cd7da69.png)

### © 版本信息

- ant-design-charts 版本:   "@ant-design/charts": "^1.0.16",
- 浏览器环境 谷歌 版本 88.0.4324.190（正式版本） （64 位）
- 开发环境 win10

**Comment by lxfu1** [comment]
双轴图是多 View 状态，不一致的建议先手动配置一下， 我们也同步跟进。

**Comment by jwwwww** [comment]
麻烦提供components的object详细说明，并且 环图的中间的HTML的颜色也是没得配置（或者说方式不对）
我目前是按照
onReady: (charts) => {
console.log(charts)
},
中的themeObj看到默认配置项才这么处理的。希望api详尽

**Comment by visiky** [comment]
G2Plot 2.3.17 版本发布：https://www.yuque.com/antv/g2plot/uo3ogo

看下你的问题解决了没

**Comment by joriewong** [comment]
> G2Plot 2.3.17 版本发布：https://www.yuque.com/antv/g2plot/uo3ogo
> 
> 看下你的问题解决了没

自定义theme的defaultColor都没生效

**Comment by visiky** [comment]
这个和 issue 标题描述不一致吧？主题 merge 的问题，你可以用 `theme: {  styleSheet: {  brandColor: 'red'  }  }` 解决

**Comment by joriewong** [comment]
> 这个和 issue 标题描述不一致吧？主题 merge 的问题，你可以用 `theme: { styleSheet: { brandColor: 'red' } }` 解决

是全局registerTheme，被默认的config merge了？registerTheme < config < theme: { ...styleSheet }
