### ISSUE TITLE
🧐 How can invert the legend color for the enable/disable state

### ISSUE THREAD

**Issue by cbojaca** [ant-design/ant-design-charts#508]
Im currently working on a chart using the ant Chart Design , however I would like to know if there is a property on the legend to invert the disable/enable color, currently using my Dark theme the Legend seems to be disabled. 

Thanks!

![image](https://user-images.githubusercontent.com/1653742/109315802-ef0bac80-7818-11eb-9ebd-af053b47e13d.png)

**Comment by lxfu1** [comment]
```ts
   legend: {
        itemName: {
          style:{
              fill: 'red'
          } 
        }
      }
```
