### ISSUE TITLE
🐛[BUG]: Worker is not defined in tests in latest version

### ISSUE THREAD

**Issue by Dorogonovvv** [ant-design/ant-design-charts#510]
I have a small private repo that's using the charts.
With 1.0.13 my jest tests are passing fine, but when I'm using a more fresh version like v.1.0.18 I see such error
![image](https://user-images.githubusercontent.com/12446170/109527246-1cc45000-7abc-11eb-9a3a-bcdb8e3c42cb.png)

**Comment by lxfu1** [comment]
To see which version G6 is in node_modules, you need to use the latest version of G6.

**Comment by Dorogonovvv** [comment]
So, tests are passing with `g6` v.3.8.5 but failed in `g6`  v4.1.12

**Comment by lxfu1** [comment]
https://github.com/facebook/jest/issues/3449

**Comment by lxfu1** [comment]
jest-setup.js
```ts
import "@testing-library/jest-dom";
import "jest-canvas-mock";
import "whatwg-fetch";

export class Worker {
  url;
  onmessage;
  constructor(stringUrl) {
    this.url = stringUrl;
    this.onmessage = () => {};
  }

  postMessage(msg) {
    this.onmessage(msg);
  }
}

Object.defineProperty(URL, "createObjectURL", {
  writable: true,
  value: jest.fn(),
});

window.Worker = Worker;

```
