### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by shixibao** [ant-design/ant-design-charts#511]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
可以做双Y轴的图表吗？设置哪个配置项？
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
无
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
类似这样的图：
<img width="1130" alt="iShot2021-03-02 12 04 23" src="https://user-images.githubusercontent.com/23250892/109595513-a07b4c80-7b4f-11eb-9518-c5013f782cfe.png">

**Comment by hustcc** [comment]
双轴图，看看官网的 demo 有的。
