### ISSUE TITLE
Ability to customise value steps for column graph

### ISSUE THREAD

**Issue by cyrusliew1** [ant-design/ant-design-charts#513]
The data value I have on my end is always an integer, the graph will display decimal value when the total value is only 2, as screenshot below.

Is there anyway to customise the step between value to not have decimal display on the graph? So it will be 0, 1, 2 instead of 0, 0.5, 1, 1.5, 2.

Many thanks!

![antd-charts-no-decimal](https://user-images.githubusercontent.com/76981692/109706619-0b835c80-7bfe-11eb-9887-f2f7332f11a2.jpg)

**Comment by lxfu1** [comment]
yAxis: {
 nice: false,
tickCounts: [0, 0.5, 1.5, 2]
}

**Comment by lxfu1** [comment]
meta: {
    [yField]: {
      nice: false,
      values: [0, 100, 200]
    }
  }

**Comment by cyrusliew1** [comment]
Thank you, that works perfectly!
