### ISSUE TITLE
Round Percent on Liquid Chart

### ISSUE THREAD

**Issue by Acidic9** [ant-design/ant-design-charts#517]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
The Liquid chart should support rounding. So `0.5` will print `50%` rather than `50.00%`.
液体图表应支持四舍五入。因此，`0.5`将输出`50％`而不是`50.00％`。

Perhaps a property: `precision` which you could specify `0` to remove the decimal places.
也许是一个属性：`precision`，您可以指定 `0` 以删除小数位。

I can do this with:
```js
statistic={{
  content: {
    formatter({ percent }) {
      return Math.round(percent * 100) + "%";
    },
  },
}}
```
But it would be better with a `precision` prop.

![Liquid Chart](https://i.imgur.com/9RICMjx.png)

**Comment by hustcc** [comment]
> format it by yourself is better the precision props.

after precision props, we need to add many similar prop for difference.

But we can do something: 0.5 formatted to 50%, remove redundant 0.
