### ISSUE TITLE
🧐[问题 漏斗图文本超出和文本颜色配置

### ISSUE THREAD

**Issue by FE-zj** [ant-design/ant-design-charts#520]
![image](https://user-images.githubusercontent.com/64066443/109943201-e54de180-7d0f-11eb-83a5-5868b527751e.png)
在漏斗图那的api文档看了很久 没找到相关配置 
希望获得解答

**Comment by lxfu1** [comment]
label: {
    style: {
      fill: 'red'
    }
  },
