### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by fv0008** [ant-design/ant-design-charts#521]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
https://charts.ant.design/demos/indented-tree/

渐进树在更新数据会，绘制点在左上角，挡住了一部分树的跟节点

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

![image](https://user-images.githubusercontent.com/18021905/109956472-a5dac180-7d1e-11eb-89c9-d7ac0b059d1d.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
不遮挡
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
就是原始例子
### © 版本信息

https://charts.ant.design/demos/indented-tree/
chrome 版本 88.0.4324.192（正式版本） (x86_64)
macmini 2018 3.2 GHz 六核Intel Core i7

**Comment by lxfu1** [comment]
是定义节点时 x y 坐标问题， 修改一下就好了。

**Comment by fv0008** [comment]
在哪里修改啊？
