### ISSUE TITLE
🧐 Color property on Bullet Chart is not available

### ISSUE THREAD

**Issue by cbojaca** [ant-design/ant-design-charts#523]
I'm currently using the Ant-Design Charts (React) , I was working on a bullet chart, however, whenever I'm trying to add the color prop it says that this prop doesn't exist. checking the code it seems that the color prop was removed from the exposed properties.

Thanks in advance!

![image](https://user-images.githubusercontent.com/1653742/110064211-ac773200-7d3a-11eb-9b01-5fdad7c15cbe.png)
![image](https://user-images.githubusercontent.com/1653742/110064240-b862f400-7d3a-11eb-8ac8-9bb30895c2ba.png)

**Comment by lxfu1** [comment]
Oh, indeed, it will be fixed in the next version，ignore it for a moment。 // @ts-ignore
