### ISSUE TITLE
👑 [需求] Ant Design Charts 中 Column 的带缩略轴案例，按照它的方法配置，数据也完全一样，最后效果并不是一样的，我是哪里出了问题吗？

### ISSUE THREAD

**Issue by glk-hll** [ant-design/ant-design-charts#524]
### 🚑 对比效果图 []

官网案例截图：
![image](https://user-images.githubusercontent.com/44257305/110077779-b1cb8f80-7dc1-11eb-8b7d-b02cedee124b.png)

本地效果截图：
![image](https://user-images.githubusercontent.com/44257305/110077736-9eb8bf80-7dc1-11eb-8abe-66c2f11025eb.png)

本地代码：
![image](https://user-images.githubusercontent.com/44257305/110077850-d58ed580-7dc1-11eb-8750-d704960fea87.png)

版本: "@ant-design/charts":  "^0.9.13",

**Comment by lxfu1** [comment]
版本太低了，你看到的是 1.0 的官网吧！
