### ISSUE TITLE
🧐[问题] - How to set Area to `startOnZero: false`?

### ISSUE THREAD

**Issue by MarkLyck** [ant-design/ant-design-charts#528]
in AntVis G2 I can run the following to make my Area chart start at a negative value.

```
chart
    .area({
      startOnZero: false,
    })
```
<img width="1114" alt="Screen Shot 2021-03-09 at 08 38 40" src="https://user-images.githubusercontent.com/6841110/110478976-e5a10080-80b2-11eb-856a-e3702e337e93.png">

But I haven't found a similar option for ant-design-charts :(

I've tried:

```
area: {
      startOnZero: false,
      options: {
        startOnZero: false,
      },
    },
options: {
      startOnZero: false,
    },
    startOnZero: false,
```

```
yAxis: {
      startOnZero: false
}
```

none of which worked.

Right now my chart looks terrible :/

<img width="1179" alt="Screen Shot 2021-03-09 at 08 02 09" src="https://user-images.githubusercontent.com/6841110/110474515-c3f14a80-80ad-11eb-8dcc-6032ed2c13b6.png">

How can I make the area draw from -100 and up?

**Comment by lxfu1** [comment]
```ts
  yAxis: {
    min: -100
  }
```

**Comment by MarkLyck** [comment]
@lxfu1 I have that already.

This is my yAxis:

```
yAxis: {
      startOnZero: false,
      min: -100,
      minLimit: -100,
      maxLimit: Math.ceil(maxLimit / 100) * 100,
      tickCount: 6,
      label: {
        labelLine: null,
        formatter: (v: string) => `${numberFormatter.format(Math.floor(Number(v)))}%`,
        style: {
          fill: '#A0A5B2',
        },
      },
      grid: {
        line: {
          style: {
            stroke: '#EFF4F7',
            lineWidth: 1,
          },
        },
      },
    },
```

**Comment by MarkLyck** [comment]
anyone 🙏 ?

**Comment by MarkLyck** [comment]
I still have not found a solution for this :(

@lxfu1 do you have any other ideas?

**Comment by lxfu1** [comment]
It's a problem,  It will be fixed soon.

**Comment by lxfu1** [comment]
https://github.com/antvis/G2Plot/pull/2444
