### ISSUE TITLE
🧐[问题] Sunburst outer ring with full circle

### ISSUE THREAD

**Issue by CaiYiLiang** [ant-design/ant-design-charts#530]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
sunburst 的外环有办法是一个完整的闭环圆吗？

Is it any way to make the outer ring of sunburst as a complete circle ring - same as inner ring, so two full circle?

![image](https://user-images.githubusercontent.com/14360297/110888054-4731cb00-8350-11eb-8bf0-7513d42f101c.png)

**Comment by lxfu1** [comment]
这个是个 bug ， 下个版本修掉。

**Comment by CaiYiLiang** [comment]
> 这个是个 bug ， 下个版本修掉。

谢谢，会留意版本升级。
