### ISSUE TITLE
混合图如何自定义tooltip的数据格式？比如：将其中一个Y轴类目的显示数值保留两位有效数字、另一个保留整数。

### ISSUE THREAD

**Issue by weimin2018** [ant-design/ant-design-charts#531]
尝试使用meta属性改，y轴刻度上显示的也被改掉了，需求是只自定义修改tooltip

**Comment by lxfu1** [comment]
https://charts.ant.design/zh-CN/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip

**Comment by lxfu1** [comment]
也可以试试 tooltip.formatter

**Comment by weimin2018** [comment]
> 也可以试试 tooltip.formatter
感谢回答、这个我也试了，官方文档默认返回的是一个包含name跟value的对象（而不是我预期的数组）：
我的设置如下，两行都显示销售值：
tooltip: {
      fields: ['Month', 'Sale', "Tax"],
      formatter: (datum) => {
        console.log('datum:',datum);
        return { value: datum.Sale + '亿元 '};
      }
    },

**Comment by weimin2018** [comment]
> https://charts.ant.design/zh-CN/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip
这个自定义内容可以，因为有item参数，感谢分享
