### ISSUE TITLE
🧐[问题]饼状图怎么配置多个图例？

### ISSUE THREAD

**Issue by 847225523** [ant-design/ant-design-charts#532]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

#
![image](https://user-images.githubusercontent.com/65758372/111098090-b7716400-857d-11eb-9e21-2191dd1c696a.png)
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/65758372/111098116-c2c48f80-857d-11eb-90ef-15a78958e40b.png)
这个是设计图
<img width="552" alt="截屏2021-03-15 上午11 03 21" src="https://user-images.githubusercontent.com/65758372/111098313-23ec6300-857e-11eb-9a5a-3efb73e77a8d.png">
这个是我配置的图例，只能展示一列，怎么配置能够展示2列？

**Comment by lxfu1** [comment]
饼图关闭 legend: false,  右侧自己实现一下。
