### ISSUE TITLE
🐛[BUG]饼图配置在TS检测下报类型错误

### ISSUE THREAD

**Issue by Lry0504** [ant-design/ant-design-charts#533]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
饼图配置图例legend时，只能使用false/true这种boolean类型，自定义对象形式的配置会报类型错误，直接在官方示例上加也会报这个错误
### © 版本信息

- ant-design-charts 版本: [1.0.21]
- 浏览器环境：谷歌浏览器
- 开发环境 [windows]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/38347779/111126840-1bac1c00-85ae-11eb-86aa-0afc4491620d.png)

**Comment by Lry0504** [comment]
如果加上// @ts-ignore忽略ts检测是可行的

**Comment by lxfu1** [comment]
这个是 ts 类型推断的问题，建议使用 as ， 例如：
```ts
legend: {
  position: "top" as const,
}
```
