### ISSUE TITLE
🧐[问题]图表缩小 x轴会自动省略

### ISSUE THREAD

**Issue by wangyongsong** [ant-design/ant-design-charts#534]
### 🧐 问题描述 

图表缩小 x轴会自动省略

![image](https://user-images.githubusercontent.com/58172091/111740015-f590bf80-88be-11eb-90af-4cfe51c5ed4a.png)
![image](https://user-images.githubusercontent.com/58172091/111740038-06d9cc00-88bf-11eb-9b27-239bf5004a1c.png)

我试了tickInterval 这个属性 不没有生效！还有什么方法吗？

还有一个建议，文档能不能补充一个完整的案例。

**Comment by lxfu1** [comment]
```ts
    xAxis: {
        label: {
          autoRotate: true,
          autoHide: false
        }
      },
```
