### ISSUE TITLE
🧐[问题]Pie label属性content只支持value选项嘛？

### ISSUE THREAD

**Issue by cuiyimeng** [ant-design/ant-design-charts#535]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
想更改label显示的内容，但是更换字段后无法成功

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
我自己的代码
![image](https://user-images.githubusercontent.com/25096779/111747296-1e6a8200-88ca-11eb-8dc2-b9d8ecb95b83.png)
官方示例
![image](https://user-images.githubusercontent.com/25096779/111747373-36da9c80-88ca-11eb-8776-dc2e3296e125.png)
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/25096779/111747322-27f3ea00-88ca-11eb-833c-529ad98ee306.png)

**Comment by lxfu1** [comment]
```ts
  content: '{name}:{value}'
```

**Comment by cuiyimeng** [comment]
> ```ts
>   内容：“ {name}：{value}”
> ```

非常感谢
