### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by accwill** [ant-design/ant-design-charts#543]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
```json
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "serve": "vite preview"
  }
```
1. 执行 npm run dev

### © 版本信息

- ant-design-charts 版本: 1.0.21
- 浏览器环境 Chrome 89.0.4389.90（正式版本） (x86_64)
- 开发环境 mac OS Big Sur

### 🚑 其他信息 
![image](https://user-images.githubusercontent.com/18046580/112251457-3cebc700-8c96-11eb-8048-6bd140d64c4d.png)

**Comment by lxfu1** [comment]
重新 install 试试，不行的话使用按需 https://charts.ant.design/zh-CN/guide/faq#6%E3%80%81%E6%89%93%E5%8C%85%E6%96%87%E4%BB%B6%E8%BF%87%E5%A4%A7%EF%BC%8C%E5%A6%82%E4%BD%95%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD
建议提供一下复现代码。

**Comment by accwill** [comment]
@lxfu1 暂时修复好了, 临时找了一种写法
