### ISSUE TITLE
Custom Icon for data point shape in line chart🧐[问题]

### ISSUE THREAD

**Issue by pranitv2stech** [ant-design/ant-design-charts#544]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
How to add custom icon as data point (react component / ant-design icon) in line chart?
![line](https://user-images.githubusercontent.com/51791997/112330982-8a8c2200-8cde-11eb-989e-d572f792060a.png)

Is is possible to achieve this without using custom-shape method

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
my chart config is:

`
{
        data: data,
        xField: 'date',
        yField: 'value',
        xAxis: {
            tickCount: 4,
            label: {
                formatter: function formatter(v: any) {
                    return moment(v, "YYYY-MM-DD hh:mm A").format("hh:mm A");
                },
                style: {
                    fill: "#6E759F",
                    fontSize: 9,
                    fontFamily: "SF-Pro-Display-Regular",
                }
            }
        },
        yAxis:{
            maxLimit: 200,
            label: {
                style: {
                    fill: "#9AA5B5",
                    fontSize: 9,
                    fontFamily: "SF-Pro-Display-Regular",
                }
            }
        },
        point: {
            size: 5,
            shape: 'circle',
            style: {
                fill: 'white',
                stroke: '#5B8FF9',
                lineWidth: 2,
            },
        },
        lineStyle:{
            stroke: "#2F54EB",
            lineWidth: 2
        }
    }
`

**Comment by lxfu1** [comment]
https://www.yuque.com/antv/g2plot/kdkyoc
