### ISSUE TITLE
🐛[BUG]引用@ant-design/charts就报错

### ISSUE THREAD

**Issue by CaptainJon** [ant-design/ant-design-charts#550]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

在React中才刚刚开始引入就报了一个错。
### © 版本信息

- ant-design-charts 版本: 1.1.1
- 浏览器环境 - 谷歌V89
- 开发环境 - win10 64位

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/51065061/112617670-3741dd00-8e60-11eb-9312-584ec7b65f27.png)

**Comment by lxfu1** [comment]
删除 node_modules 重新安装试试，感觉是底层依赖有冲突。
