### ISSUE TITLE
How to change total label in pie chart🧐[问题]

### ISSUE THREAD

**Issue by valen2510** [ant-design/ant-design-charts#552]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

Hello. I'm having problems finding a way to change the default label of the pie chart with an inner radius at the total of data. Basically, How can I change the total to set it "Total" in English?

![image](https://user-images.githubusercontent.com/65981858/113229148-f54bd900-925b-11eb-8426-fd72ca82a55d.png)
 
 Thanks for reading.

**Comment by lxfu1** [comment]
statistic.title

**Comment by lxfu1** [comment]
statistic: {
      title: {
        formatter:  () => 'hhh'
      }
    },

**Comment by valen2510** [comment]
I'm sorry, I should have clarified that I want to change the title to Total, but keeping the behavior of the chart. If I use "statistic" all the labels when I hover over the parts of the diagram will be changed at the same label.
I want to be able to hover over them and see their respective label, but when none has hovered I want to see the "total" label with the total value.

**Comment by lxfu1** [comment]
formatter:  (item) => xxx

**Comment by valen2510** [comment]
Oh! I know what you mean now. Sorry for the misunderstanding. 
Thank you so much for you help
