### ISSUE TITLE
🧐[How to sort stacked bar]

### ISSUE THREAD

**Issue by Lechevallier** [ant-design/ant-design-charts#554]
Is there a way of sorting stacked bar ?

Let's say I have the following configuration:
```JavaScript
const config = {
    data: [
        {
            x: 40,
            y: "foo",
            color: "yellow"
        },
        {
            x: 2,
            y: "foo",
            color: "red"
        },
        {
            x: 40,
            y: "bar",
            color: "yellow"
        }
    ],
    isStack: true,
    xField: 'x',
    yField: 'y',
    seriesField: 'color',
    color: (_ref: any) => _ref.color
};
```
I get this chart:
![image](https://user-images.githubusercontent.com/10246002/113731862-662a3f80-96f9-11eb-9417-87c744ee8f91.png)

How can I get the red bar at the left ?

If I use `.reverse()`, I succeed to get the red bar at the left, but `bar` gets displayed before `foo`, which is not what I want
![image](https://user-images.githubusercontent.com/10246002/113732587-008a8300-96fa-11eb-8987-8a66fe96cfe3.png)

If I use `.reverse()` and I reorder the inputed data (`bar` before `foo`), I get the same result as the first screenshot.

Any solution ?

Thanks for your help.

**Comment by lxfu1** [comment]
The default rule is from top to bottom, left to right, and you need to process the data yourself.

**Comment by Lechevallier** [comment]
Not sure to understand the "left to right" part 🤔 
Based on the example I wrote above, could you please give me the right `config` to get the desired result ?

**Comment by lxfu1** [comment]
Adjust Data order.

**Comment by Lechevallier** [comment]
I'm still not able to get the desired result reorganising data.

I created a [codepen](https://codepen.io/pen?template=eYgGZEE) with my example, could you please send me your solution ?

Expected result:
foo | [red][&emsp;&emsp;yellow&emsp;&emsp;]
bar | [&emsp;&emsp;&emsp; yellow&emsp;&emsp;&emsp;]

Thanks

**Comment by lxfu1** [comment]
Method 1: 
```ts
color: [ 'red', 'yellow']
```
Method 2:
```ts
{
    data: [
        {
            x: 2,
            y: "foo",
            color: "red"
        },
        {
            x: 40,
            y: "foo",
            color: "yellow"
        },
        {
            x: 40,
            y: "bar",
            color: "yellow"
        },
        {
            x: 0,
            y: "bar",
            color: "red"
        }
    ],
    isStack: true,
    xField: 'x',
    yField: 'y',
    seriesField: 'color',
    color: _ref => _ref.color
  }
```

**Comment by Lechevallier** [comment]
The second method is giving me the expected result, thanks!

So if I understand well, it is not only about adjusting data order, but as well about altering data array to make sure each `y` (foo & bar) has every kind of `series` ("yellow" & "red"), even if there is nothing to display (`x: 0`).

It could be good to write it somewhere in the documentation, or better, handle the case each `y` do not have every kind of series.

**Comment by lxfu1** [comment]
Welcome to supplement the documentation together.

**Comment by lxfu1** [comment]
![image](https://user-images.githubusercontent.com/31396322/196089243-3ff8c0ff-0af3-47a5-9f16-4b0e1d778f32.png)
