### ISSUE TITLE
🐛[BUG] ReferenceError: self is not defined in Next.js

### ISSUE THREAD

**Issue by robertosannazzaro** [ant-design/ant-design-charts#556]
I apologize, but the template for the issue is in Chinese and I don't understand it.

Basically, using SSR with Next.js, If I install the library and try to render a chart I get this error.

## Steps to reproduce:
- Clone [this](https://github.com/robertosannazzaro/ant-design-chart-bug)
- `npm install`
- `npm run dev`

Version: ant-design-charts ^1.1.1

<img width="1012" alt="Screenshot 2021-04-07 at 16 48 35" src="https://user-images.githubusercontent.com/32909143/113886589-19aa3700-97c1-11eb-8cdb-55472119c085.png">

Thanks for any help 😀

**Comment by lxfu1** [comment]
The code you provided does not include  AntDesignCharts.

**Comment by robertosannazzaro** [comment]
@lxfu1 Corrected, I apologize.

**Comment by lxfu1** [comment]
Use Lib first and we will follow up later.

**Comment by robertosannazzaro** [comment]
Thanks, @lxfu1 if I do as you suggested it works. What is the reason if this error?

P.S. Thanks for the fast reply and the awesome work you put into Ant!

**Comment by tony-stark-edith** [comment]
@robertosannazzaro 
By [nextjs](https://nextjs.org/docs/advanced-features/dynamic-import) documentation, the actual solution for undefined `window/self` reference is as follows:

```
import dynamic from "next/dynamic";
const Line = dynamic(
  () => import("@ant-design/charts").then((mode) => mode.Line),
  { ssr: false }
);
```

**Comment by snizemic** [comment]
I have the same issue even not in next.js environment.
We use esbuild to bundle our app and if I import chart as `import { Column } from '@ant-design/charts'` i get the `ReferenceError: self is not defined`.
If i try import from lib as `import Line from '@ant-design/charts/lib/line'` I get `Uncaught TypeError: tslib_1.__spreadArray is not a function`.
Any idea how to solve it, please?

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/576

**Comment by ShaifArfan** [comment]
`import Line from '@ant-design/charts/lib/plots/line';`

try to import from /libs/plots/ folder

**Comment by lxfu1** [comment]
The problem lies in `@ant-design/flowchart`, it is recommended to use subpackages or configure:

```ts
import dynamic from "next/dynamic";
const Line = dynamic(
  () => import("@ant-design/charts").then((mode) => mode.Line),
  { ssr: false }
);
```
