### ISSUE TITLE
🧐[问题]chrome最新版本(89.0.4389.114)无法打开官网 https://charts.ant.design

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design-charts#557]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
macos系统，升级chrome后，https://charts.ant.design 打开后显示空白，console中error信息如下
![image](https://user-images.githubusercontent.com/2271825/113960680-66d8e800-9857-11eb-9fc4-024d3acb40a2.png)

**Comment by PeachScript** [comment]
macOS 11.2.1 + 同版本的 Chrome 无法复现，用无痕模式看看是不是插件引起的

**Comment by codering** [comment]
Disable cache后，重新刷新可以了；
