### ISSUE TITLE
🧐[问题]组件库对于lodash的依赖？

### ISSUE THREAD

**Issue by southorange1228** [ant-design/ant-design-charts#558]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
1. 自定义webpack配置
2. 原来使用lodash，后准备切换lodash-es用于减少构建产物的体积。同时因为历史代码较多，所以在`tsconfig.json`配置了路径
```json
{
"paths": {
      "lodash": ["./node_modules/lodash-es"],
    }
}
```
3. 出现如图所示报错
![image](https://user-images.githubusercontent.com/32590310/113991473-10829e00-9885-11eb-8ac3-5285b567442b.png)

并且存在一个类似的issue #306 同样是lodash导致的，所以是因为组件库对lodash有什么依赖关系吗？这是否合理？

**Comment by lxfu1** [comment]
使用 babel-plugin-lodash ？

**Comment by southorange1228** [comment]
> 使用 babel-plugin-lodash ？

没有使用，仅仅是使用了lodash的esm版本。用于tree shaking。同时在tsconfig配置了paths

**Comment by lxfu1** [comment]
update
