### ISSUE TITLE
[Isssue] TypeError: Object(...) is not a function Group.Container.getBBox ./src/abstract/container.ts:93

### ISSUE THREAD

**Issue by susu-sub** [ant-design/ant-design-charts#559]
![image](https://user-images.githubusercontent.com/58883343/114000865-f7cab600-988d-11eb-8907-fc3e831a717b.png)

![image](https://user-images.githubusercontent.com/58883343/114000457-9acf0000-988d-11eb-9b0c-c1dd4570fab7.png)
本地代码允许demo 出现上述报错，请问有什么解决办法吗？感谢🙏

**Comment by lxfu1** [comment]
什么图表？  看下线上是否有问题  没有的话 update 试试。

**Comment by visiky** [comment]
删除 依赖 lock，重装

**Comment by susu-sub** [comment]
已解决，需要单独安装指定版本的@antv/util@2.0.13
