### ISSUE TITLE
🧐[问题]使用Line组件时 为什么无法显示title

### ISSUE THREAD

**Issue by susu-sub** [ant-design/ant-design-charts#561]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/58883343/114139711-f5c22f00-9941-11eb-8445-cfc8e6880b9c.png)

**Comment by lxfu1** [comment]
1.0 版本不再支持 title， 可以看下官网的升级文档。
