### ISSUE TITLE
🧐[问题]请问是否支持markLine绘制平均值的功能 

### ISSUE THREAD

**Issue by susu-sub** [ant-design/ant-design-charts#562]
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/58883343/114139892-2ace8180-9942-11eb-9e87-d69c9b72c949.png)

**Comment by lxfu1** [comment]
你这是 0. 9 版本？

**Comment by susu-sub** [comment]
目前在使用的是1.1.1 版本， 上面的截图是用echarts做的

**Comment by lxfu1** [comment]
```ts
 annotations: [
  {
    type: 'line',
    start: ['min', 'mean'],
    end: ['max', 'mean'],
    style: {
      stroke: '#F4664A',
      lineDash: [2, 2],
    },
  },
]
```

**Comment by lxfu1** [comment]
参考这个 ： https://charts.ant.design/demos/line#%E6%8A%98%E7%BA%BF%E5%9B%BE%E5%B8%A6%E5%9B%BE%E8%A1%A8%E6%A0%87%E6%B3%A8

**Comment by susu-sub** [comment]
额感觉不是想要的诶 有多条折线图需要分别绘制其均值线时 这个怎么解决

**Comment by lxfu1** [comment]
> 额感觉不是想要的诶 有多条折线图需要分别绘制其均值线时 这个怎么解决

多条折线按什么平均？ 自己插入一条数据？

**Comment by susu-sub** [comment]
自动计算每条折线的均值 然后画出均值

**Comment by susu-sub** [comment]
echarts有markLine可以支持画均值线  找了半天好像antd charts没有支持

**Comment by susu-sub** [comment]
> > 额感觉不是想要的诶 有多条折线图需要分别绘制其均值线时 这个怎么解决
> 
> 多条折线按什么平均？ 自己插入一条数据？

这个有解嘛大哥？

**Comment by lxfu1** [comment]
'mean' 是支持多折线图的

**Comment by lxfu1** [comment]
![image](https://user-images.githubusercontent.com/31396322/114142271-57d06380-9945-11eb-844f-77060643dc5c.png)

**Comment by lxfu1** [comment]
如过你要按 xField 平均的话就需要自己加一条线。

**Comment by susu-sub** [comment]
上图这个例子 如果要给5条线分别画出均值线 需要单独画？

**Comment by susu-sub** [comment]
谢谢大佬🙏

**Comment by lxfu1** [comment]
![image](https://user-images.githubusercontent.com/31396322/114143154-5d7a7900-9946-11eb-88da-9307b4fdc2d3.png)

**Comment by susu-sub** [comment]
我懂你的意思了 看来每条线的均值需要我自己单独先算出来才行
