### ISSUE TITLE
🧐[问题] ant-design-pro的打包问题

### ISSUE THREAD

**Issue by SixDayCoder** [ant-design/ant-design-charts#564]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
`1.引入import { Line } from '@ant-design/charts'`之后,执行npm run build导致打包出的size过大
![image](https://user-images.githubusercontent.com/13084718/114149142-29568680-994d-11eb-802a-2a00375516ca.png)
没有引入包时打出的包正常
2.打完包之后部署到静态资源服务器，无法显示界面，一直在载入状态，服务端和前端均无报错。

我怀疑是不是没有把charts包bundle进来?需要什么额外配置吗？

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
提示显示该页面size过大,只有该页面引入了包ant-design/charts
![image](https://user-images.githubusercontent.com/13084718/114149349-6589e700-994d-11eb-9f4e-d623a46c2daf.png)

package.json显示确实引入了该包
![image](https://user-images.githubusercontent.com/13084718/114149583-a681fb80-994d-11eb-89b4-6bbd7c93401c.png)

执行`npm run build`的配置
![image](https://user-images.githubusercontent.com/13084718/114149661-ba2d6200-994d-11eb-94c5-0c2aaf249422.png)

**Comment by SixDayCoder** [comment]
刚才又试了好几种情况，发现并不是没有打包进去，好像和浏览器的版本有关系。
同样的接口，低版本chrome就一直无法加载，edge确定可以。
------------------------------------------------------------------
版本是45.0.254.101m

**Comment by lxfu1** [comment]
打包大看下这个： https://charts.ant.design/zh-CN/guide/faq#6%E3%80%81%E6%89%93%E5%8C%85%E6%96%87%E4%BB%B6%E8%BF%87%E5%A4%A7%EF%BC%8C%E5%A6%82%E4%BD%95%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD
