### ISSUE TITLE
🧐[问题] OrganizationTreeGraph组件的leftIcon自定义问题

### ISSUE THREAD

**Issue by LL1314520** [ant-design/ant-design-charts#565]
### 🧐 请问如何设置leftIcon的图片的属性，比如宽高，位置和radius等属性

![image](https://user-images.githubusercontent.com/39017634/114151209-7b001080-994f-11eb-803b-bb4fb6a0fad4.png)

**Comment by Yanyan-Wang** [comment]
目前 icon-node 这种节点的宽高位置是固定的。有需要定制的话可以考虑自定义节点：

import G6 from @antv/g6

https://g6.antv.vision/zh/docs/manual/middle/elements/nodes/custom-node/#gatsby-focus-wrapper

**Comment by LL1314520** [comment]
感谢您的回答，但如果又想使用OrganizationTreeGraph组件，又想自定义节点，是不是暂时没有解决方案了呢

**Comment by lxfu1** [comment]
最新版本已经支持
