### ISSUE TITLE
How to Repaint/Reload Chart?

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design/ant-design-charts#566]
Hi guys

I am trying to use the charts. all the examples work without problems, but the examples are designed so that the data is only loaded when the app is started.
In reality, however, you have a few filters and depending on the filter settings, a chart should then be generated.

Unfortunately, I could not find an example where a chart is loaded with new data, e.g. via a button. Therefore, I tried to implement this myself and discovered that there is an @ref tag, which apparently represents a reference to the chart. This reference can then be used to call a few methods, including repaint and render. I tried this, but the diagram is not reloaded. However, when I call the method UpdateConfig(), the diagram is repainted with new values.

Is this correct with using UpdateConfig or am I using the Render method incorrectly? How should it be programmed correctly?

Thanks

**Comment by lxfu1** [comment]
The UpdateConfig logic has been built-in, you only need to care about config, Charts will be automatically repaint, if you think it is a problem, it is recommended to provide an online Demo.

**Comment by true-perfect-code** [comment]
Thanks
