### ISSUE TITLE
🧐[问题]图像直接超出容器，x轴也看不到

### ISSUE THREAD

**Issue by taofeifanIT** [ant-design/ant-design-charts#567]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我想到的解决办法是调整y轴的显示区间，但不知道antchar如何设置这一属性
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
`  var salaryConfig = {
    data: obj.salaryData,
    xField: 'year',
    yField: 'value',
    seriesField: 'category',
    xAxis: { type: 'time'},
    yAxis: {
      label: {
        formatter: function formatter(v) {
          return ''.concat(v).replace(/\d{1,3}(?=(\d{3})+$)/g, function (s) {
            return ''.concat(s, ',');
          });
        },
      },
    },
  };`
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/42193371/114377108-ded94200-9bb8-11eb-8c5a-35f832c8cd96.png)

**Comment by lxfu1** [comment]
yAxis: {min: 0, max: xxx}
