### ISSUE TITLE
🐛[BUG] Title disappear when "seriesField" is missing

### ISSUE THREAD

**Issue by Lechevallier** [ant-design/ant-design-charts#568]
Title disappear when configuration field `seriesField` is missing.

Here is a [codePen](https://codepen.io/MaximeL/pen/wvgmEZq) where you can try to comment / uncomment field `seriesField`.

**Comment by lxfu1** [comment]
For stackBar, seriesField is required,  normal Bar has no legend.

**Comment by Lechevallier** [comment]
Why normal bar does not take property `legend` into account like stacked bar ?
