### ISSUE TITLE
👑 [需求] 迷你面积图中的customContent，可以返回react的Element

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-charts#570]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

> 文档上这么写
https://charts.ant.design/zh-CN/demos/tiny-area?type=api

支持自定义模板。

{
  tooltip: {
    customContent: (title, data) => {
      return `<div>${title}</div>`;
    };
  }
}

### 我实验了一下，是可以返回一个React对象的。

**Comment by fanhualei** [comment]
这个图片是我做出的效果，感觉只用在代码中，把customContent的返回值类型设置一下，就可以了。
![QQ截图20210412120104](https://user-images.githubusercontent.com/34436863/114667804-862db480-9d32-11eb-9545-ab9840a135a6.png)

**Comment by lxfu1** [comment]
我看了一下是可以的，你用的那个版本？

**Comment by fanhualei** [comment]
> 我看了一下是可以的，你用的那个版本？

我用的是这个版本：
```tsx
"@ant-design/charts": "^1.1.1",
```
程序可以正常执行，只不过在vscode中提示语法错误。见下图。

![aaaa](https://user-images.githubusercontent.com/34436863/114689825-b1230300-9d48-11eb-8dcb-8625104559f3.png)

**Comment by lxfu1** [comment]
先临时解决一下
1: as string
2: // @ts-ignore

**Comment by fanhualei** [comment]
明白，这是一个好方法

**Comment by fanhualei** [comment]
明白，这是一个好方法
