### ISSUE TITLE
🐛[BUG]股票图xAxis.label日期时间部分显示不出来

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design-charts#572]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
股票图xAxis.label日期时间部分显示不出来
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
设置下padding: [100]

**Comment by laolaolulu** [comment]
xAxis.label.formatter参数值都只有日期部分,没有时间部分

**Comment by lxfu1** [comment]
```ts
 xAxis: {
    type: 'cat'
  }
```
