### ISSUE TITLE
🐛[BUG]  饼图配置height:250，autofix: false, 饼图数据 0和1， resize饼图时，饼图会消失在显示无动画。

### ISSUE THREAD

**Issue by Wster11** [ant-design/ant-design-charts#574]
### 🐛 bug 描述

饼图配置height:250，autofix: false, 饼图数据 0和1， resize饼图时，饼图会消失在显示无动画。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
拖动窗口,resize即可复现
### 🏞 期望结果 [描述你原本期望看到的结果]

正常resize

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/clever-clarke-ylsdw?file=/App.tsx
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
autofix => autoFit

**Comment by Wster11** [comment]
这样图表就不会resize了

**Comment by lxfu1** [comment]
删除lock文件，重新安装一下依赖。
