### ISSUE TITLE
🧐[问题]"export '__spreadArray' was not found in 'tslib'

### ISSUE THREAD

**Issue by assignali** [ant-design/ant-design-charts#576]
WARNING in ./node_modules/@antv/g6-core/es/util/validation.js 57:26-39
"export '__spreadArray' was not found in 'tslib'
![image](https://user-images.githubusercontent.com/82788275/115170719-e71f0900-a0f3-11eb-82a6-f7fd7bb30661.png)
![image](https://user-images.githubusercontent.com/82788275/115170731-ef774400-a0f3-11eb-89c1-ec8c969d513f.png)

**Comment by lxfu1** [comment]
https://github.com/antvis/G6/issues/2702

**Comment by birdycn** [comment]
@lxfu1 请问这个问题应该怎么解决，没看懂

**Comment by hustcc** [comment]
> @lxfu1 请问这个问题应该怎么解决，没看懂

点到这个地址：https://github.com/antvis/G6/issues/2702

然后进去看，里面有说明解法。

**Comment by birdycn** [comment]
> > @lxfu1 请问这个问题应该怎么解决，没看懂
> 
> 点到这个地址：[antvis/G6#2702](https://github.com/antvis/G6/issues/2702)
> 
> 然后进去看，里面有说明解法。
> 
> ![image](https://user-images.githubusercontent.com/7856674/118942700-8d755d00-b985-11eb-9692-72433da3cd11.png)

我使用 npm i tslib，安装失败，请问你们是怎么安装的

**Comment by lxfu1** [comment]
npm install tslib  --save

**Comment by birdycn** [comment]
> npm install tslib --save

报错

```
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path \node_modules\tslib
npm ERR! dest  \node_modules\react-easy-crop\node_modules\tslib
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename '\node_modules\tslib' -> '\node_modules\react-easy-crop\node_modules\tslib'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by lxfu1** [comment]
> > npm install tslib --save
> 
> 报错
> 
> ```
> npm ERR! code ENOENT
> npm ERR! syscall rename
> npm ERR! path \node_modules\tslib
> npm ERR! dest  \node_modules\react-easy-crop\node_modules\tslib
> npm ERR! errno -4058
> npm ERR! enoent ENOENT: no such file or directory, rename '\node_modules\tslib' -> '\node_modules\react-easy-crop\node_modules\tslib'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> ```

删除 node_modules 安装试试

**Comment by birdycn** [comment]
删除lock.json好了

**Comment by liho00** [comment]
不能，最新版本，为什么还是用不到

**Comment by guguji5** [comment]
> npm install tslib --save

![image](https://user-images.githubusercontent.com/17986248/147334616-8872d473-b7cb-4d94-9b56-84a4d426077f.png)

我的tslib是"version": "2.3.1"。解决了一个报错，又出来另一个报错。

**Comment by lxfu1** [comment]
> > npm install tslib --save
> 
> ![image](https://user-images.githubusercontent.com/17986248/147334616-8872d473-b7cb-4d94-9b56-84a4d426077f.png)
> 
> 我的tslib是"version": "2.3.1"。解决了一个报错，又出来另一个报错。

用的什么图？
