### ISSUE TITLE
🧐[问题] ScatterPlot with Dual Axes

### ISSUE THREAD

**Issue by cbojaca** [ant-design/ant-design-charts#578]
Hi , I was using the scatter plot chart, however I have a required on my company to add some curve lines just like the following picture is there any way to accomplish this ? 

thanks in advanced

![image](https://user-images.githubusercontent.com/1653742/115260502-ce692000-a100-11eb-8e5a-815c61168122.png)

**Comment by hustcc** [comment]
@visiky MultiView/Mix can help
