### ISSUE TITLE
🧐[问题] Missing documentation for annotations

### ISSUE THREAD

**Issue by yanckst** [ant-design/ant-design-charts#579]
### Introduction
Hi, Thanks for this amazing library! 

When looking into the docs, I noticed a missing documentation.
I'm not sure if it's the right place to publish the issue, but that will be awesome to have the missing doc.

Thanks!

---

### 🧐 Problem description
Missing Annotations API documentation on the website

Step to reproduce : 
- Go to this [https://charts.ant.design/demos/multi-view/?type=api](https://charts.ant.design/demos/multi-view/?type=api)
- Go to IView.annotations
![image](https://user-images.githubusercontent.com/30554401/115296878-86aabe80-a129-11eb-8d1c-db4d801b7cb8.png)
- Click on the `Annotations API` link

Actual behavior: 
An empty page
![image](https://user-images.githubusercontent.com/30554401/115297028-b3f76c80-a129-11eb-8395-c2b0ec7f0381.png)

Expected behavior:
Having a page containing the information about annotation's API 

### 💻 Sample code
None

### 🚑 Other information
None

**Comment by lxfu1** [comment]
https://charts.ant.design/demos/line?type=api

**Comment by yanckst** [comment]
Thanks! In that case, should we update the website to redirect to the URL you gave me?
