### ISSUE TITLE
🐛[BUG]Pie饼图resize处bug

### ISSUE THREAD

**Issue by liforgithub** [ant-design/ant-design-charts#581]
![image](https://user-images.githubusercontent.com/20366895/115520220-82fb7100-a2bc-11eb-98a2-2d65949b0a24.png)
我打开chrome开发者工具后，页面会resize，这个时候饼图这边就会报这种错误,重新刷新页面后恢复，我用的是官方的样例测试
"react": "^16.13.1",
"@ant-design/charts": "^1.0.17",
"antd": "^4.9.0",

**Comment by lxfu1** [comment]
https://github.com/antvis/G2/pull/3378   近期会发布

**Comment by lxfu1** [comment]
删除 lock.json，重新安装下依赖。
