### ISSUE TITLE
👑 [需求]圆形的词云图，不通过imagemask实现,希望spiral增加圆形的option

### ISSUE THREAD

**Issue by IIIzz** [ant-design/ant-design-charts#582]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
圆形的词云图，不通过imagemask实现,希望spiral增加圆形的option
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/29473782/115837678-6e011800-a44b-11eb-8528-2a76018d4c82.png)

**Comment by lxfu1** [comment]
[V2](https://ant-design-charts-next.antgroup.com/examples/statistics/wordCloud/#wordCloud)

```ts
layout: { spiral: 'archimedean' },
```
