### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by MihaiWill** [ant-design/ant-design-charts#583]
### 🐛 bug description [Describe the bug in detail so that everyone can understand]
Sankey theme config dont work properly 

### 📷 Reproduction steps [Clearly describe the reproduction steps so that others can see the problem]
     <Sankey {...config} />

**WORK**
```
const config = {
  data: dummyData,
  sourceField: "source",
  targetField: "target",
  weightField: "value",
  nodeWidthRatio: 0.005,
  nodePaddingRatio: 0.03,

  theme: "dark",
};
```
**DONT WORK**
```
const config = {
  data: dummyData,
  sourceField: "source",
  targetField: "target",
  weightField: "value",
  nodeWidthRatio: 0.005,
  nodePaddingRatio: 0.03,

  theme: {
    defaultColor: "dark",
  },
};
```

Also whole `Theme Attributes` API doesn't work: [Sankey API](https://charts.ant.design/demos/sankey?type=api)

### 🏞 Expected results [Describe what you expected to see]
I want to change theme color via object, and modify `tooltip` and `label` components
### © Version Information

`    "@ant-design/charts": "^1.1.2"`

-Browser environment
`Version 1.16.68 Chromium: 86.0.4240.111 (Official Build) (64-bit)`

### 🚑 Other information [Other information such as screenshots can be posted here]
i am using nextjs and i import chart components from lib as is recommended in prev issues: 
`import Sankey from "@ant-design/charts/lib/sankey";`

**Comment by lxfu1** [comment]
```ts
theme: {
  styleSheet: {
    backgroundColor: '#000'
  },
},
```
