### ISSUE TITLE
🧐[问题]cpu被占满

### ISSUE THREAD

**Issue by Zeng-J** [ant-design/ant-design-charts#584]
### 💻 
```javascript
import React from 'react';
import { Line } from '@ant-design/charts';

const DataAnalysis: React.FC = () => {
  const data = [
    { year: '1991', value: 3 },
    { year: '1992', value: 4 },
    { year: '1993', value: 3.5 },
    { year: '1994', value: 5 },
    { year: '1995', value: 4.9 },
    { year: '1996', value: 6 },
    { year: '1997', value: 7 },
    { year: '1998', value: 9 },
    { year: '1999', value: 13 },
  ];
  const config = {
    data,
    height: 400,
    xField: 'year',
    yField: 'value',
    point: {
      size: 5,
      shape: 'diamond',
    },
  };
  return <Line {...config} />;
};

export default DataAnalysis;
```
![image](https://user-images.githubusercontent.com/48742371/115985848-4db69200-a5e0-11eb-8eef-79608fc51d58.png)

**Comment by lxfu1** [comment]
https://charts.ant.design/zh-CN/guide/faq#6%E3%80%81%E6%89%93%E5%8C%85%E6%96%87%E4%BB%B6%E8%BF%87%E5%A4%A7%EF%BC%8C%E5%A6%82%E4%BD%95%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD   看下这个  正在做优化

**Comment by Zeng-J** [comment]
> https://charts.ant.design/zh-CN/guide/faq#6%E3%80%81%E6%89%93%E5%8C%85%E6%96%87%E4%BB%B6%E8%BF%87%E5%A4%A7%EF%BC%8C%E5%A6%82%E4%BD%95%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD 看下这个 正在做优化

ha

**Comment by Zeng-J** [comment]
> https://charts.ant.design/zh-CN/guide/faq#6%E3%80%81%E6%89%93%E5%8C%85%E6%96%87%E4%BB%B6%E8%BF%87%E5%A4%A7%EF%BC%8C%E5%A6%82%E4%BD%95%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD 看下这个 正在做优化

感谢
