### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by JimLeeee** [ant-design/ant-design-charts#585]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
如何从网络获取数据并展示?

**Comment by lxfu1** [comment]
看看 demo 代码, https://charts.ant.design/zh-CN/demos/line#%E6%8C%87%E5%AE%9A%E6%8A%98%E7%BA%BF%E9%A2%9C%E8%89%B2
