### ISSUE TITLE
🧐[问题]如何让数据展示完全

### ISSUE THREAD

**Issue by JimLeeee** [ant-design/ant-design-charts#586]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我的数据是这种带时间格式的，当我展示的时候，发现柱形图里或者折线图里都合并成一列了，如何让他们展示完全呢？
┌───────────────────t─┬─COUNT(1)─┐
│ 2021-04-25 23:59:00 │  2078983 │
│ 2021-04-25 23:58:00 │  2056080 │
│ 2021-04-25 23:57:00 │  2039857 │
│ 2021-04-25 23:56:00 │  2061787 │
│ 2021-04-25 23:55:00 │  2042405 │
│ 2021-04-25 23:54:00 │  2045827 │
│ 2021-04-25 23:53:00 │  2055083 │
│ 2021-04-25 23:52:00 │  2045474 │
│ 2021-04-25 23:51:00 │  2017425 │
│ 2021-04-25 23:50:00 │  2029098 │
![image](https://user-images.githubusercontent.com/46155146/116049738-273b3a00-a666-11eb-811e-a353a1756eb7.png)

**Comment by lxfu1** [comment]
Can you provide an online demo ?

**Comment by JimLeeee** [comment]
应该是后端数据返回错误导致的，麻烦了
![image](https://user-images.githubusercontent.com/46155146/116052185-f67df380-a6ab-11eb-80c7-b0b1c8973fb6.png)
