### ISSUE TITLE
👑 [需求]IndentedTree的树状图动态刷新能否增加一个属性取消展开收缩的动画

### ISSUE THREAD

**Issue by daidaic** [ant-design/ant-design-charts#589]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
IndentedTree的树状图动态刷新能否增加一个属性取消展开收缩的动画, 引用websocket更新data数据,实时更新,数据更新一次 树状图就会收缩展开一次,影响用户体验
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
暂无
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
暂无

**Comment by lxfu1** [comment]
暂时不支持， 后续会新增。

**Comment by lxfu1** [comment]
来源去向图可以满足你的需求。

**Comment by daidaic** [comment]
> 来源去向图可以满足你的需求。

感谢再次回复...后面改需求 自己用g6写了..
