### ISSUE TITLE
🐛[BUG]引入Ant Design Charts的demo在umi的react就启动不了

### ISSUE THREAD

**Issue by Mrchenyiyang123** [ant-design/ant-design-charts#592]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

umi的react版本引入Ant Design Charts
的demo报TypeError: Object(...) is not a function

### © 版本信息
"react": "^17.0.0",
"react-dom": "^17.0.0",
"umi": "^3.2.14",
- ant-design-charts 版本: [e.g. 0.9.0]
-  "@ant-design/charts": "^1.1.2",
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/20673102/116181431-2d581600-a74d-11eb-806c-cb7c3eada79e.png)

**Comment by lxfu1** [comment]
能提供一下最小复现吗？

**Comment by lzxxxxx** [comment]
同样的问题，想问解决了吗？

**Comment by vVvlife** [comment]
同样的问题+1

**Comment by lxfu1** [comment]
看下这个是否能解决， https://charts.ant.design/zh-CN/guide/faq#2%E3%80%81object-is-not-a-function

**Comment by vVvlife** [comment]
> 看下这个是否能解决， https://charts.ant.design/zh-CN/guide/faq#2%E3%80%81object-is-not-a-function

![image](https://user-images.githubusercontent.com/20148964/121497194-c39a7f80-ca0d-11eb-9336-763748720fe4.png)
部署会报这些warning，是npm的版本问题吗？

**Comment by lxfu1** [comment]
删除 lock.json 重新安装。

**Comment by vVvlife** [comment]
> 删除 lock.json 重新安装。

解决了，thanks
