### ISSUE TITLE
🐛[BUG] Missed labels in Columns if they are belong to the same type

### ISSUE THREAD

**Issue by EvgenBabenko** [ant-design/ant-design-charts#593]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Missed labels in Columns if they are belong to the same type
And strange labels behaviour, label shows 1, but tooltip shows 3 on this area (sometimes they are shown correctly)

### 🏞 期望结果 [描述你原本期望看到的结果]
Show all labels, even they are belong to the same type

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/intelligent-smoke-wpwvu?file=/App.tsx

**Comment by EvgenBabenko** [comment]
Hi, any progress of this?

**Comment by lxfu1** [comment]
[V2](https://ant-design-charts-next.antgroup.com)

```ts
const config = {
    data,
    xField: 'year',
    yField: 'value',
    stack: true,
    label: {
      text: 'value',
      position: 'inside'
    },
    legend: false,
  };
```
