### ISSUE TITLE
🧐How to remove white spaces from area chart?

### ISSUE THREAD

**Issue by pranitv2stech** [ant-design/ant-design-charts#594]
### 🧐 How to remove white spaces from area chart?
The Area chart component doesn't starts at 0 and leaves space at start and end of chart. how to remove the what space and render the chart end to end?

### 💻 chart config
`
const config = {
    data: data,
    height: 268,
    xField: "date",
    yField: "value",
    seriesField: "type",
    colorField: "type",
    fillOpacity: 1,
    smooth: true,
    legend: false,
    yAxis: {
      tickInterval: 40,
      label: {
        style: {
          fill: "#6E759F",
          fontSize: 9
        }
      },
      grid: {
        line: {
          style: {
            stroke: "#F2F4F6",
            lineWidth: 1
          }
        }
      }
    },
    xAxis: {
      label: {
        formatter: function formatter(v) {
          return moment(v).format("dddd");
        },
        style: {
          fill: "#6E759F",
          fontSize: 9
        }
      }
    },
    areaStyle: function areaStyle() {
      return { fillOpacity: 0.1 };
    }
  };
`

### 🚑 screenshot and codesandbox link
![Screenshot from 2021-04-27 16-55-56](https://user-images.githubusercontent.com/51791997/116236880-33fe8180-a77d-11eb-943f-7ab0b6fe37a6.png)

https://codesandbox.io/s/area-chart-8c4uo

**Comment by hustcc** [comment]
```
{
  meta: { [xField]: { range: [0, 1] } },
}
```
