### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by timhuebener** [ant-design/ant-design-charts#602]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
The demos don't work. The yField does not want to accept a string[]

https://github.com/ant-design/ant-design-charts/edit/master/docs/demos/box.md

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![Screenshot 2021-04-28 at 17 06 05](https://user-images.githubusercontent.com/17812251/116427134-0a5c5d80-a844-11eb-8e5b-f85af9be6e54.png)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
// @ts-ignore
Ignore the ts error first.

**Comment by timhuebener** [comment]
// @ts-ignore
this works thanks! but I guess it should also work without?!

**Comment by lxfu1** [comment]
```ts
import { Box, BoxConfig } from "@ant-design/plots";

const config: BoxConfig = {xx}
```
