### ISSUE TITLE
🧐[问题]请问分组柱状图 组与组之间的间距可以根据内容自适应吗？

### ISSUE THREAD

**Issue by Ezra-Chan** [ant-design/ant-design-charts#605]
![image](https://user-images.githubusercontent.com/26107204/116644950-4956f400-a9a7-11eb-8a87-d580d04d53a4.png)
目前组与组之间的间距是等分的，内容少的组存在比较大的空白空间，内容多的组就太挤了

**Comment by lxfu1** [comment]
目前不能

**Comment by lxfu1** [comment]
不合理需求
