### ISSUE TITLE
🧐[问题]Wrapping y axis label 

### ISSUE THREAD

**Issue by IJustWantToPass195** [ant-design/ant-design-charts#607]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
I have a really long y axis label and i would like to wrap it into two lines so that it does not mess up the width of the graph

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/63994042/117172247-335d8f00-adfe-11eb-89ad-79a1a45adcfc.png)

**Comment by lxfu1** [comment]
```ts
  yAxis: {
    label: {
      formatter: () => 'a\nb'
    }
  },
```

**Comment by IJustWantToPass195** [comment]
thank you
