### ISSUE TITLE
🧐[问题] How to set color to grouped stacked bar chart and access all data in tooltip

### ISSUE THREAD

**Issue by pranitv2stech** [ant-design/ant-design-charts#608]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
How to set color to bar on basis of groupField and seriesField and show data all on tooltip ?

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

My chart configuration is 

`
{
    data: data,
    isGroup: true,
    isStack: true,
    xField: "type",
    yField: "value",
    seriesField: "subType",
    groupField: "name",
    minColumnWidth: 20,
    legend: false,
    columnStyle: (a) => {
      // console.log(a);
      let color = "";
      if (a.subType === "Draft") {
        color = "#1D39C4";
      }
      if (a.subType === "Inactive") {
        color = "#2F54EB";
      }
      if (a.subType === "Active") {
        color = "#597EF7";
      }
      let radius = a.subType === "Active" ? [4, 4, 0, 0] : [0, 0, 0, 0];
      return {
        radius: radius,
        fill: color
      };
    }
  }
`

and data is 
`[
    { type: "Access", subType: "Active", value: 300, name: "Analytic" },
    { type: "Access", subType: "Inactive", value: 400, name: "Analytic" },
    { type: "Access", subType: "Draft", value: 500, name: "Analytic" },
    { type: "Access", subType: "Active", value: 320, name: "Activity" },
    { type: "Access", subType: "Inactive", value: 300, name: "Activity" },
    { type: "Access", subType: "Draft", value: 270, name: "Activity" },
    { type: "Data", subType: "Active", value: 350, name: "Analytic" },
    { type: "Data", subType: "Inactive", value: 360, name: "Analytic" },
    { type: "Data", subType: "Draft", value: 370, name: "Analytic" },
    { type: "Data", subType: "Active", value: 350, name: "Activity" },
    { type: "Data", subType: "Inactive", value: 320, name: "Activity" },
    { type: "Data", subType: "Draft", value: 300, name: "Activity" },
    { type: "Security", subType: "Active", value: 310, name: "Analytic" },
    { type: "Security", subType: "Inactive", value: 320, name: "Analytic" },
    { type: "Security", subType: "Draft", value: 330, name: "Analytic" },
    { type: "Security", subType: "Active", value: 390, name: "Activity" },
    { type: "Security", subType: "Inactive", value: 370, name: "Activity" },
    { type: "Security", subType: "Draft", value: 340, name: "Activity" }
  ]`

I have done the grouping by type and stacked by name.

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
Link to codesandbox for current implementation
https://codesandbox.io/s/stackedgroupedbar-lxhc3?file=/App.tsx:123-1452

I want to achieve something like this
![Screenshot from 2021-05-06 12-30-55](https://user-images.githubusercontent.com/51791997/117255318-21fc9d00-ae67-11eb-881e-2cf34a147e31.png)

The blue color represents the Analytic and purple color represents the Activity.
How to set these colors? and Is my data structure correct?

**Comment by lxfu1** [comment]
https://charts.ant.design/demos/column#%E5%A0%86%E5%8F%A0%E5%88%86%E7%BB%84%E6%9F%B1%E7%8A%B6%E5%9B%BE

**Comment by pranitv2stech** [comment]
> https://charts.ant.design/demos/column#%E5%A0%86%E5%8F%A0%E5%88%86%E7%BB%84%E6%9F%B1%E7%8A%B6%E5%9B%BE

I have updated the data structure and changed the configuration according to this example, now it's working
