### ISSUE TITLE
👑 [需求]当点击Pie Legend时饼状图会调用默认的handleLegendClick，我希望该方法可自定义

### ISSUE THREAD

**Issue by annilq** [ant-design/ant-design-charts#610]

**Comment by lxfu1** [comment]
https://charts.ant.design/zh-CN/guide/common#%E4%BA%8B%E4%BB%B6%E7%9B%91%E5%90%AC 这个能否解决你的问题？

**Comment by annilq** [comment]
![QQ截图20210507095145](https://user-images.githubusercontent.com/6497194/117386651-db1baf80-af19-11eb-8b85-9a96f5c0d091.png)
网站好像挂了呀

**Comment by annilq** [comment]
![QQ截图20210507095145](https://user-images.githubusercontent.com/6497194/117386703-eb338f00-af19-11eb-9023-7b1395eba1fb.png)
网站好像挂了呀

**Comment by lxfu1** [comment]
> ![QQ截图20210507095145](https://user-images.githubusercontent.com/6497194/117386703-eb338f00-af19-11eb-9023-7b1395eba1fb.png)
> 网站好像挂了呀

恢复了

**Comment by annilq** [comment]
没能按照网站说明配置好，我还是改了本地的源码，将handleLegendClick传进去了
