### ISSUE TITLE
🧐[问题] How to customize the sankey chart

### ISSUE THREAD

**Issue by pranitv2stech** [ant-design/ant-design-charts#614]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
I want to customise the Sankey chart with custom node and edge color. for that I'm using nodeStyle and edgeStyle property in configuration. But when I use nodeStyle and edgeStyle as function, it does not give all the keys in data. it only gives name, x and y values.

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
chart config
`
const config: any = {
        data: data,
        sourceField: 'source',
        targetField: 'target',
        weightField: 'value',
        nodeStyle: (a: any) => {
            if (a.name.includes("User")) {
                return {
                    fill: "#597EF7"
                }
            } else if (a.name.includes("Automation")) {
                return {
                    fill: "#03838B"
                }
            } else if (a.name.includes("Action")) {
                return {
                    fill: "#C41D7F"
                }
            }else if (a.name.includes("Rule")) {
                return {
                    fill: "#722ED1"
                }
            } else {
                return {
                    fill: "#CED5EE"
                }
            }
        },
        edgeStyle: (datum:any)=>{
            console.log(datum);
        }
        // nodeWidthRatio: 0.008,
    }
`

data object 
`
{
        "source": "Rule 2",
        "target": "Automation 3",
        "value": 35,
        type: "rule"
    }
`

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
console log
![log](https://user-images.githubusercontent.com/51791997/117634505-98b5d500-b19c-11eb-97a2-72367febfe06.png)

I want to customize chart as below
![Screenshot from 2021-05-10 14-39-25](https://user-images.githubusercontent.com/51791997/117635788-ccddc580-b19d-11eb-8bcb-1f5751031ee6.png)

I want to customize the node and edge based on type. I'll use gradient for edges.
But how to access value, type (source and destination) inside nodeStyle and edgeStyle function to style node and edge?

current implementation
codesandbox: https://codesandbox.io/s/sankey-lxhc3

**Comment by lxfu1** [comment]
https://github.com/antvis/G2Plot/pull/2533  , Recently released.

**Comment by pranitv2stech** [comment]
> [antvis/G2Plot#2533](https://github.com/antvis/G2Plot/pull/2533) , Recently released.

looks great. 
It's not there in current version of G2Plot (2.3.19).
will this feature available in Ant Design Charts ?

**Comment by lxfu1** [comment]
Delete node_modules and reinstall.

**Comment by mantra-sanathra** [comment]
How we can pass the raw fields and use the value given by the data object into nodeStyle function? Is there any example available for this? I want to customize the color based on both the source and destination both.
