### ISSUE TITLE
👑 [需求]api文档

### ISSUE THREAD

**Issue by Benny-Chan** [ant-design/ant-design-charts#617]
个人感觉 相对于echarts   api文档不够清晰吧   echarts的文档使用对象一层层的  看ant的  很多属性不知道该填哪里 我靠试出来的...

**Comment by visiky** [comment]
antd charts 是 G2Plot 的上层 react 封装，可以看下：https://g2plot.antv.vision/zh/docs/api 这里的API 文档是否可以满足，有什么建议可以到 G2Plot issue 上提
