### ISSUE TITLE
🧐[问题] what is the correct rotation angle and how do i stop it from overlapping into the graph

### ISSUE THREAD

**Issue by IJustWantToPass195** [ant-design/ant-design-charts#618]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
im trying to rotate the names in the x axis by only 10 to 20degrees but i cannot get the correct angle also it seems to overlap into the graph is there a way to stop it from overlapping

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
xAxis: {
			label: {
				style: {
					fontSize: 14,
					fontWeight: 'bold',
					textAlign: 'center',
				},
				// autoEllipsis: true,
				rotate: 20,
			},
			// verticalLimitLength: 24,
		},
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/63994042/117909892-9cb53480-b30d-11eb-8ef2-25e8b2aea7ab.png)

**Comment by lxfu1** [comment]
textAlign: 'start',
