### ISSUE TITLE
👑 [需求]迷你柱状图鼠标移入之后的黑色边框能去掉吗

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/ant-design-charts#621]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
我想要去掉迷你柱状图鼠标移入之后的黑框，本来想通过移除事件解决，但是迷你柱状图没有提供API
![image](https://user-images.githubusercontent.com/33271366/118112843-218c7500-b418-11eb-8ff9-7f113ed8c5b0.png)

**Comment by lxfu1** [comment]
```ts
 onReady: (plot) => {
  plot.chart.removeInteraction('element-active');
}
```

**Comment by hustcc** [comment]
或者直接：

```ts
interactions: [{type: 'element-action', enabled: false  }]
```

**Comment by PLUTO06210331** [comment]
thanks

**Comment by PLUTO06210331** [comment]
@hustcc  感谢您的帮助，但是您提供的这种方式没有生效，不知道是不是我的写法有问题
![Uploading image.png…]()

**Comment by PLUTO06210331** [comment]
@hustcc  代码如下

const DemoTinyColumn = () => {
  var data = [
    274,
    337,
    81,
    497,
    666,
    219,
    269,
    122,
    334,
    24,
    45,
    109,
    123,
    234,
    100,
    123,
    423,
    211,
    67,
    54,
  ];
  var config = {
    height: 50,
    autoFit: true,
    padding: [10, 0, 10, 0],
    data: data,
    onReady: (plot) => {
      plot.chart.removeInteraction('element-active');
    },
    // interactions: [{ type: 'element-action', enabled: false }],
    
    // tooltip: {
    //   customContent: function customContent(x, data) {
    //     var _data$, _data$$data;
    //     return 'NO.'
    //       .concat(x, ': ')
    //       .concat(
    //         (_data$ = data[0]) === null || _data$ === void 0
    //           ? void 0
    //           : (_data$$data = _data$.data) === null || _data$$data === void 0
    //           ? void 0
    //           : _data$$data.y.toFixed(2),
    //       );
    //   },
    // },
  };
  return <TinyColumn {...config} />;
};

export default DemoTinyColumn;

**Comment by visiky** [comment]
> @hustcc  感谢您的帮助，但是您提供的这种方式没有生效，不知道是不是我的写法有问题
> 
> ![Uploading image.png…]()
> 
> 

用第二种写法 element-active

**Comment by PLUTO06210331** [comment]
@visiky  好的 谢谢啦

**Comment by PLUTO06210331** [comment]
@visiky  您好 文档中也是这么操作的 
var config = {
    height: 50,
    autoFit: true,
    padding: [10, 0, 10, 0],
    data: data,
    // onReady: (plot) => {
    //   plot.chart.removeInteraction('element-active');
    // },
    interactions: [{ type: 'element-active', enabled: false }],
  };
但是我的demo中还是会出现黑框

**Comment by visiky** [comment]
> @visiky  您好 文档中也是这么操作的 
> 
> var config = {
> 
>     height: 50,
> 
>     autoFit: true,
> 
>     padding: [10, 0, 10, 0],
> 
>     data: data,
> 
>     // onReady: (plot) => {
> 
>     //   plot.chart.removeInteraction('element-active');
> 
>     // },
> 
>     interactions: [{ type: 'element-active', enabled: false }],
> 
>   };
> 
> 但是我的demo中还是会出现黑框

enable

**Comment by PLUTO06210331** [comment]
@visiky  sorry 是我大意了
