### ISSUE TITLE
onlyChangeData无效

### ISSUE THREAD

**Issue by zaki1991** [ant-design/ant-design-charts#627]
版本: 1.1.4
Area图表使用onlyChangeData，data改变后图表还是会重新渲染

**Comment by lxfu1** [comment]
data 改变会渲染是正常逻辑， 1.1.4不再支持 onlyChangeData， 内部已经做处理， 建议配合 React.memo 使用。

**Comment by zaki1991** [comment]
> data 改变会渲染是正常逻辑， 1.1.4不再支持 onlyChangeData， 内部已经做处理， 建议配合 React.memo 使用。

使用React.memo，data改变后图表还是会闪烁，有办法可以不让图表闪烁吗

**Comment by lxfu1** [comment]
关闭动画？

**Comment by zaki1991** [comment]
> 关闭动画？

动态更新的效果和@antv/g2plot v2.x版本不一样，ant design是会闪烁，但是@antv/g2plot不会闪烁

**Comment by zaki1991** [comment]
@lxfu1 图表动态更新的效果可以做到和@antv/g2plot 2.x版本一致吗

**Comment by visiky** [comment]
或许是自己写的代码 导致组件重新渲染了？

**Comment by zaki1991** [comment]
> 或许是自己写的代码 导致组件重新渲染了？

没有，我把ant design charts改为@antv/g2plot，图表动态更新就变得很平滑了，使用ant design charts的时候，会出现闪烁的效果

**Comment by zaki1991** [comment]
@visiky 我是通过interval去后台拉取的数据，在不操作页面的情况下，只有这个拉取的data是改变的，也只有这个data的改变能触发组件重新渲染，<Area {...config}/> 这个的重新渲染是通过changeData改变的吧

**Comment by lxfu1** [comment]
跪求提供一个在线demo ~

**Comment by zaki1991** [comment]
> 跪求提供一个在线demo ~

@lxfu1 找到原因了，

**Comment by lxfu1** [comment]
formatter 是function类型的，底层没法判断是否修改了，所以每次走 update 而不是 changeData , 使用 React.memo 第二个参数就好了。

**Comment by zaki1991** [comment]
> formatter 是function类型的，底层没法判断是否修改了，所以每次走 update 而不是 changeData , 使用 React.memo 第二个参数就好了。

第二个参数 (prevProps, nextProps) => prevProps === nextProps 这样用吗，可以给个例子吗

**Comment by zaki1991** [comment]
@lxfu1 config不在props里，使用 React.memo 第二个参数没有效果吧

**Comment by WShawn1900** [comment]
`// 父组件页面
import React, { useMemo, useState } from 'react';
const ParentComponent = () => {
    
    const [lineData, setLineData] = useState([]);

    return(
        <>
        <ChildComponent lineData={
            // 观察依赖是否变化，决定是否使用之前缓存数据
            useMemo( () => lineData, [lineData]);
        }/>
        </>
    )

}

// 子组件页面
import React,{ memo } from 'react';
import { Line } from '@ant-design/charts';

const ChildComponent = (props) => {
    const { lineData } = props;
    
    const lineConfig = {
        data: lineData,
        xField: 'time',
        yField: 'value',
        .....
    }
    
    return(
        <>
            <Line {...lineConfig} />
        </>
    )
}
// memo 会检查 props 是否变化，决定是否使用之前缓存的组件。
export default memo(ChildComponent);`

**Comment by lxfu1** [comment]
> ```js
> // memo 会检查 props 是否变化，决定是否使用之前缓存的组件。
> export default memo(ChildComponent);
> ```

// memo 会检查 props 是否变化，决定是否使用之前缓存的组件。
export default memo(ChildComponent, (pre, next) => { 
    // 返回 true 则不更新组件， 返回 false 则更新组件
    return _.isEqual(pre.data, next.data);
 });
