### ISSUE TITLE
🧐[问题] 如何实时刷新图形数据？

### ISSUE THREAD

**Issue by ly020044** [ant-design/ant-design-charts#630]
🧐 问题描述 [请问如何才能实时刷新已渲染的图形？比如通过定时器生成随机数据重新渲染图形]

谢谢

**Comment by lxfu1** [comment]
setState data

**Comment by ly020044** [comment]
好的，谢谢！我也是这样用的，但未生效，我自己在试试。

**Comment by juzhiyuan** [comment]
> setState data

该方式会导致图表闪烁，期望的是数据在 x 轴滚动。
