### ISSUE TITLE
🧐[问题]y坐标刻度如何自动适应数据

### ISSUE THREAD

**Issue by BigGoblin** [ant-design/ant-design-charts#634]
y坐标刻度如何自动适应数据
数据集中在大数上，y坐标依旧从0开始，无法反应数据变换趋势

因为含有 slider，手动算出最大最小值 也不是当前展示的最大最小值。无法进行min,max的赋值

![image](https://user-images.githubusercontent.com/27881216/119087880-60cf4d00-ba3a-11eb-8e8e-3927d704a791.png)

**Comment by lxfu1** [comment]
```ts
yAxis: {
  min: null
},
```

**Comment by BigGoblin** [comment]
> ```ts
> yAxis: {
>   min: null
> },
> ```

感谢感谢

**Comment by nonevx** [comment]
找了半天....为什么不写在文档里....黑魔法啊...
