### ISSUE TITLE
🐛[BUG] ./node_modules/@antv/algorithm/es/gaddi.js Attempted import error: '__spreadArray' is not exported from 'tslib'.

### ISSUE THREAD

**Issue by hikhyper** [ant-design/ant-design-charts#637]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
```
Failed to compile.

./node_modules/@antv/algorithm/es/gaddi.js
Attempted import error: '__spreadArray' is not exported from 'tslib'.
```
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/80023612/119436361-9af86180-bd4e-11eb-8e69-e36394a0d066.png)

### © 版本信息

- ant-design-charts 版本: 1.1.4
- 浏览器环境
- 开发环境: Windows 10

**Comment by lxfu1** [comment]
https://github.com/antvis/G6/issues/2702
