### ISSUE TITLE
👑 (Demand)

### ISSUE THREAD

**Issue by hmz22** [ant-design/ant-design-charts#638]
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]

Hi,
can check stack column tooltip when use  interactions: [{ type: 'element-highlight-by-color' }] must tooltip just show one item highlight but show all column in tooltip

[https://codesandbox.io/s/sparkling-sun-ehz1o](url)

![Screenshot (17)_LI](https://user-images.githubusercontent.com/36853974/119443538-033f4700-bd3f-11eb-9b21-1dff5b79d9bb.jpg)

**Comment by lxfu1** [comment]
```ts
  tooltip: {
      shared: false
    },
```
