### ISSUE TITLE
🧐 (Questions) How to regionFilter annotation with diagonal line

### ISSUE THREAD

**Issue by haikyuu** [ant-design/ant-design-charts#639]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
I have a line chart and I want to color parts of it that are above a diagonal line (displayed with annotation) in red.
![image](https://user-images.githubusercontent.com/8558836/119486291-9ed4b580-bd47-11eb-9f0a-b9fb97cc9d16.png)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
Here is a sample codesandbox with a diagonal line and failing regionFilter annotation https://codesandbox.io/s/new-architecture-ynmhh

**Comment by lxfu1** [comment]
```ts
start: ['min', 'min'],
end: ['max', 'max'],
```

**Comment by haikyuu** [comment]
@lxfu1 Thanks for your reply.
Unfortunately, that colors all the line in red. I want only the portion above the dotted line

**Comment by lxfu1** [comment]
RegionFilter can only set ranges, can't use base line,  you need to use custom shapes, reference [Custom Line](https://zhuanlan.zhihu.com/p/204832999).
