### ISSUE TITLE
🧐(Questions) How to increase the dots in the chart on mouse hover? (MultiView)

### ISSUE THREAD

**Issue by yanckst** [ant-design/ant-design-charts#640]
Hi,

I want to know if it's possible to increase the size of the dot in the chart when the element is active.

![image](https://user-images.githubusercontent.com/30554401/119555711-2a603d80-bd6c-11eb-8718-02f5773ef798.png)

----

I've followed the [documentation](https://g2.antv.vision/en/docs/api/general/interaction) and I saw that it's possible the put a `hightlight-element` using `G2` interactions as follow : 

```
G2.registerInteraction('data-highlight-element', {
    start: [{ trigger: 'element:mouseenter', action: 'element-highlight:highlight' }],
    end: [{ trigger: 'element:mouseleave', action: 'element-highlight:reset' }],
})
```
This is highlighting the element. I just want to see if it's possible to increase the size as well.

----

I also saw that you can change the style on the fly inside the `Geometry` as follow:
```
state: {
    active: {
        style: (element: any) => {
            const el = { ...element }
            el.geometry.attributes.size.values = [6]
            el.model.size = 6
            return el
        },
    },
},
```
![image](https://user-images.githubusercontent.com/30554401/119556252-c38f5400-bd6c-11eb-81ac-e1a5ef3c568b.png)

The only problem using this approach is the dot is being updated after leaving the active element. Also, all the dots keeps their new size instead of falling back their original value.

 Any inputs on this?
 
 Thanks 🙂

**Comment by lxfu1** [comment]
You changed the state of the element. Unrecoverable change. Simulation.
```ts
state: {
  active: {
    style: {
      fill: 'red',
      lineWidth: 2,
      shadowBlur: 10,
      shadowColor: 'red',
    },
  },
},
```

**Comment by yanckst** [comment]
Okay thanks!

I saw that you have a property `r` which corresponds to the radius of the circle. By increasing the value in the state, it's increasing the size.
