### ISSUE TITLE
🧐(Questions) Why we are losing the tooltip in-between feature when we sync the views?

### ISSUE THREAD

**Issue by yanckst** [ant-design/ant-design-charts#641]
Hi,

I have a question regarding the Multiview chart. When combining 2 views that are different (dots and a line), Why when we synchronize the views together we are losing the ability to view the tooltip value on hover between the values?

Ant Chart version : 1.1.6

----
Example without the synchronization `sync` parameter (we have duplicate values the the axes, not what I want)
![capture](https://user-images.githubusercontent.com/30554401/119854144-d45fd700-bede-11eb-9944-9c29ab3dbee0.gif)

----

Example with the synchronization  `sync` parameter
![capture](https://user-images.githubusercontent.com/30554401/119855046-957e5100-bedf-11eb-84ca-6b0e22296fd4.gif)

The problem is that you need to be on the exact value to see the tooltip.

----

Is that an expected behavior or it's a bug?

---

Code sample : 

```
var subData = data.slice(0, 400);
var config = {
    syncViewPadding: true,
    views: [
        {
            data: subData,
            meta: {
                price: {
                    nice: true,
                    sync: "price"
                },
                carat: {
                    nice: true,
                    sync: "carat"
                }
            },
            axes: {},
            geometries: [
                {
                    type: "point",
                    xField: "carat",
                    yField: "price",
                    mapping: {}
                }
            ]
        },
        {
            data: otherData,
            meta: {
                carat: {
                    nice: true,
                    sync: "carat"
                },
                price: {
                    nice: true,
                    sync: "price"
                }
            },
            axes: {},
            geometries: [
                {
                    type: "line",
                    xField: "carat",
                    yField: "price",
                    mapping: {}
                }
            ]
        }
    ]
};
```

I've also create a code sample here :  https://codesandbox.io/s/trusting-grothendieck-0xsc7?file=/App.tsx

Any input on this?

Thanks 🙂

**Comment by yanckst** [comment]
Turn out that if you remove the `sync` in the other view it's working. You don't have duplicate values on the axes and the feature is working as expected. 👍

**Comment by yanckst** [comment]
Reopening the issue because the data is offsync so we really need the `sync` option

**Comment by lxfu1** [comment]
```ts
if (!data.length) return;
```
