### ISSUE TITLE
能否实现迷你柱状图渐变色

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/ant-design-charts#642]
UI设计图
![image](https://user-images.githubusercontent.com/33271366/120060781-445f9000-c08c-11eb-81c9-70770598ef79.png)
nengdo
能实现吗，没有找到对应的Api

**Comment by lxfu1** [comment]
```ts
 color: (item)=>{
    return  'l(90) 0:#f00 1:#ff0'
  },
```

**Comment by PLUTO06210331** [comment]
感谢
