### ISSUE TITLE
🧐[问题] How to remove "转化率" from Funnel Charts?

### ISSUE THREAD

**Issue by uchihamalolan** [ant-design/ant-design-charts#643]
<img width="624" alt="Screenshot 2021-05-31 at 17 49 16" src="https://user-images.githubusercontent.com/24520586/120192218-86c5d000-c238-11eb-9325-bf68b2c56dab.png">

Here there's a tick with Label Text: "转化率". I don't know how to remove it. Couldn't find anything helpful in the docs regarding that.

Thanks

**Comment by ma101an** [comment]
Closing it as I figured out setting `conversionTag: false` removes it. 👍

**Comment by uchihamalolan** [comment]
Closing it as I figured out setting conversionTag: false removes it. 👍
