### ISSUE TITLE
图表父元素设置zoom属性后，造成坐标系错乱🐛[BUG]

### ISSUE THREAD

**Issue by 1263536889** [ant-design/ant-design-charts#649]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
图表父元素设置zoom属性后，造成坐标系错乱
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/40379830/120407728-4f623b00-c380-11eb-9fe7-efae486a0e62.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
坐标系正常

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
看复现图片，给父级元素加个zoom就能成功复现

### © 版本信息

- ant-design-charts 版本: [1.1.2]
- 浏览器环境
- Google Chrome   91.0.4472.77（正式版本） （64 位）

- 开发环境 [Windows 10]

**Comment by paisleyliu** [comment]
我也遇到同样的问题，期望能够解决

**Comment by lxfu1** [comment]
这么用的目的是啥？

**Comment by lxfu1** [comment]
![image](https://user-images.githubusercontent.com/31396322/120432049-eb556c00-c3ab-11eb-9ff2-7599db0f0f56.png)

**Comment by 1263536889** [comment]
@lxfu1 需求是页面一屏显示完全，不能有滚动条，让整个页面适当缩小，来兼容低分辨显示出现滚动条的情况

**Comment by 1263536889** [comment]
@lxfu1 是否可以兼容？兼容写法应该和 supportCSSTransform 这个兼容差不太多，如若不能兼容的话这俩天回复一下，我换种写法，把项目中的zoom去除，麻烦老哥了

**Comment by 1263536889** [comment]
@lxfu1 后面zoom有没有兼容的想法？ 好吧， zoom 转为 transform 项目不太适用，我重写一下项目页面吧 ，凄凄惨惨

**Comment by 1263536889** [comment]
@lxfu1 改完了，谢谢大哥

**Comment by Hz-Cool** [comment]
> @lxfu1改完了，谢谢大哥

铁铁，你是改了写法还是怎么解决的这个问题

**Comment by spring-xql** [comment]
我也遇到这个问题了，公司项目需要整体缩放：
用transform或zoom都会错位
html{
  //transform:scale(.75)
  zoom:(.80);
}
这个问题如何解决的呀？
