### ISSUE TITLE
能否按需加载？？？

### ISSUE THREAD

**Issue by ChubbyH** [ant-design/ant-design-charts#65]
### 💻 
import { Line } from '@ant-design/charts';

### 🚑
这是引入后组件打包之后的大小 

![image](https://user-images.githubusercontent.com/22996621/83848542-9a7f4900-a740-11ea-94d4-db8018b7e793.png)

这是引入之前组件的大小
![image](https://user-images.githubusercontent.com/22996621/83849114-812acc80-a741-11ea-9ba1-7f794b3ba882.png)

**Comment by lxfu1** [comment]
这个是因为 Line 底层的依赖比较多， 我们在底层处理哈。

**Comment by ChubbyH** [comment]
这个按需加载什么时候发版呢？？

**Comment by Airkro** [comment]
用了 `babel-plugin-import` 之后稍微好了一点，但 `@ant-design/charts` 内部似乎没有对 `g2plot` 进行按需加载

**Comment by lxfu1** [comment]
https://charts.ant.design/guide/faq
