### ISSUE TITLE
为什么饼图和折线图设置想用图例符号 Square 饼图显示实心的，折线图是空心

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/ant-design-charts#653]
项目中引入了饼图和折线图，设置了相同的图例符号Square，但是饼图是实心的，折线图是空心的

![image](https://user-images.githubusercontent.com/33271366/120622042-0b129000-c491-11eb-965d-a9dad639d924.png)
![image](https://user-images.githubusercontent.com/33271366/120622079-12d23480-c491-11eb-9745-d3bf33701411.png)

**Comment by lxfu1** [comment]
折线图自己设置一下
```ts
  legend: {
    marker: {
      symbol: 'square',
      style: (item)=> ({
        ...item,
        fill: item.stroke
      })
    }
  }
```

**Comment by 1165656731** [comment]
怎么配置 两个图例 线颜色一致，一个虚线 一个实线呢

**Comment by lxfu1** [comment]
lineDash: [2,4]

**Comment by 1165656731** [comment]
legend marker 里面的

**Comment by 1165656731** [comment]
![image](https://user-images.githubusercontent.com/65803424/147453918-9b2d85a9-fa51-4c1c-bb96-dd51bcef8ae0.png)
marker: {
        // symbol:""
        symbol: (item) => {
           if (item.name === 'Q-Note 3 VSI' || item.name === 'Q-Note 1 VSI' || item.name === 'EM VSI') {
            return {

           }
           }
        }

      
这种 要区分 怎么配置呢
