### ISSUE TITLE
🐛[BUG] Moving/Dragging the chart data cause an offsync of data

### ISSUE THREAD

**Issue by yanckst** [ant-design/ant-design-charts#655]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

Moving/Dragging the chart data cause an offsync of data when using the MultiView

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

Before dragging
![image](https://user-images.githubusercontent.com/30554401/120711202-16fc5300-c48d-11eb-9f1a-a4ef073663b3.png)

After dragging

![image](https://user-images.githubusercontent.com/30554401/120711286-31363100-c48d-11eb-8a23-8375275e3ee7.png)

Feature : 
![capture](https://user-images.githubusercontent.com/30554401/120711618-968a2200-c48d-11eb-8499-58a0cdb1fd35.gif)

### 🏞 期望结果 [描述你原本期望看到的结果]

When doing a mousezoom or dragging the data, it should stay synchronize 

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://codesandbox.io/s/blissful-hellman-et87z?file=/App.tsx

### © 版本信息

- ant-design-charts 版本: [e.g. 1.1.7]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
Looks like a bug,  use Scatter?

**Comment by yanckst** [comment]
No because I really need to use the `MultiView` because I have a complex chart to create.

**Comment by lxfu1** [comment]
The bug has been around for too long. You can try the V2 version. If there are still issues, we will open it again.
