### ISSUE TITLE
🐛[BUG] Annotations not working for Progress bar component

### ISSUE THREAD

**Issue by seerocode** [ant-design/ant-design-charts#656]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

Example code in the documentation for Mini progress bar-target value does not work with the provided annotations.  

'Types of property 'annotations' are incompatible' in typescript.

```
(alias) const Progress: React.ForwardRefExoticComponent<ProgressConfig & React.RefAttributes<unknown>>
import Progress
Type '{ height: number; width: number; autoFit: boolean; percent: number; barWidthRatio: number; color: string[]; annotations: { type: string; start: string; end: string; style: { stroke: string; lineWidth: number; }; }[]; }' is not assignable to type 'ProgressConfig'.
  Types of property 'annotations' are incompatible.
    Type '{ type: string; start: string; end: string; style: { stroke: string; lineWidth: number; }; }[]' is not assignable to type 'Annotation[]'.
      Type '{ type: string; start: string; end: string; style: { stroke: string; lineWidth: number; }; }' is not assignable to type 'Annotation'.
        Type '{ type: string; start: string; end: string; style: { stroke: string; lineWidth: number; }; }' is not assignable to type 'DataRegionOption'.
          Types of property 'start' are incompatible.
            Type 'string' is not assignable to type 'AnnotationPosition'.
```
### 🏞 期望结果 [描述你原本期望看到的结果]

Annotations should work as described in the documentation: https://charts.ant.design/demos/progress

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://codesandbox.io/s/optimistic-fast-14rnr?file=/App.tsx

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by seerocode** [comment]
I fixed this by importing and setting the type of config to `ProgressConfig` as follows instead of the suggestion [here](https://github.com/ant-design/ant-design-charts/issues/485#issuecomment-842993974) to cast:

```typescript
import { Progress } from "@ant-design/charts";
import { ProgressConfig } from "@ant-design/charts/es/progress";

const config: ProgressConfig = {
    height: 30,
    width: 300,
    autoFit: false,
    percent: 0.536,
    barWidthRatio: 0.8,
    color: ["#F4664A", "#E8EDF3"],
    annotations: [
      {
        type: "line",
        start: ["80%", "0%"],
        end: ["80%", "100%"],
        style: {
          stroke: "#f00",
          lineWidth: 2,
        },
      },
    ],
  };
```

**Comment by lxfu1** [comment]
![image](https://user-images.githubusercontent.com/31396322/120734970-57ef7880-c51c-11eb-9347-7f540f2d5ad8.png)

**Comment by seerocode** [comment]
Just a note for anyone viewing this issue is that yes the above code renders the graph in JS but it still returns a type error so this would not work and **did not work** in Typescript for me until I specified the type.
