### ISSUE TITLE
🐛[BUG] 多折线图Y轴数值没有随着字段值变大，而是直接附上了

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/ant-design-charts#662]
###  我设置了两条折线图，分别获取到了values值并且付给yField作为值，但是结果却xians显示为下图
![image](https://user-images.githubusercontent.com/33271366/120784285-8130f880-c55e-11eb-9115-9771cd9a7ae4.png)

###  代码如下
![image](https://user-images.githubusercontent.com/33271366/120784399-9e65c700-c55e-11eb-8736-cf12a9f488cc.png)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by PLUTO06210331** [comment]
稍等

**Comment by PLUTO06210331** [comment]
https://codesandbox.io/s/autumn-dust-y6tqf?file=/App.tsx   @lxfu1  看这个老师

**Comment by lxfu1** [comment]
yField 需要是 number  类型

**Comment by PLUTO06210331** [comment]
谢谢好的
