### ISSUE TITLE
🧐[问题] How to add border-radius to bar and control xAxis value 

### ISSUE THREAD

**Issue by sirbully** [ant-design/ant-design-charts#663]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
This is the design (Google Translate: 这是设计)
<img width="516" alt="Screen Shot 2021-06-04 at 8 24 52 PM" src="https://user-images.githubusercontent.com/29673385/120801866-52258180-c574-11eb-81f8-6354c43b8499.png">

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
CodeSanbox link: https://codesandbox.io/s/late-frog-9es0q?file=/src/App.tsx

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
package:
`@ant-design/charts@1.1.9`

This is my current solution (Google Translate: 这是我目前的解决方案)
<img width="549" alt="Screen Shot 2021-06-04 at 8 38 55 PM" src="https://user-images.githubusercontent.com/29673385/120802612-35d61480-c575-11eb-9785-d77e613ddbc6.png">

**Comment by visiky** [comment]
Q1: https://g2plot.antv.vision/en/docs/manual/plots/bar#set-corner-radius-of-bar

**Comment by sirbully** [comment]
> Q1: https://g2plot.antv.vision/en/docs/manual/plots/bar#set-corner-radius-of-bar

Thank you!!

**Comment by sirbully** [comment]
I'm also using `tickInterval` now to change the xAxis value. It is now increasing +5 instead of +10.

```
xAxis: {
    tickInterval: 5
    ...
}
```
<img width="553" alt="Screen Shot 2021-06-05 at 9 27 28 AM" src="https://user-images.githubusercontent.com/29673385/120875793-42438700-c5e0-11eb-8c70-4b6245e4f0f3.png">

I just need to change the color of one specific column

**Comment by lxfu1** [comment]
https://charts.ant.design/demos/bar#basic-bar-chart---custom-color ?

**Comment by sirbully** [comment]
Hello, we're using `annotations` instead.  Custom color is for the bar color but we need to color the grid line.

```
annotations: [
      {
        type: "line",
        start: ["33.3%", "100%"],
        end: ["33.3%", "0%"],
        style: {
          stroke: "red",
        }
      }
    ]
```

<img width="475" alt="Screen Shot 2021-06-08 at 11 50 39 AM" src="https://user-images.githubusercontent.com/29673385/121120236-c18ac200-c84f-11eb-836d-e4a10865367b.png">

**Comment by lxfu1** [comment]
```ts
xAxis: {
      grid: {
        line: {
          style: (point, index, pionts)=>{
            console.log(point, index, pionts);
            return {
              stroke: 'red'
            }
          }
        }
      }
    }
```

**Comment by sirbully** [comment]
Yay, thank you! I did not know we could use a function ✨
