### ISSUE TITLE
🐛[BUG] Tooltip formatting is not working in heatmap

### ISSUE THREAD

**Issue by khjabir** [ant-design/ant-design-charts#664]
### 🐛 Unable to format the tooltip using formatter in HeatMap.

<img width="1440" alt="Screenshot 2021-06-04 at 7 53 42 PM" src="https://user-images.githubusercontent.com/10330142/120817974-cf022c80-c56f-11eb-98cd-e6b9a86366c3.png">

The `title` and `showMarkers` props works as intended. But the formatter is not appending `%` to the value.

### © Version Information

- ant-design-charts 1.1.9
- Safari
- MacOS

**Comment by visiky** [comment]
Will be solved in the next version.

**Comment by lxfu1** [comment]
Latest version.

**Comment by yuekaidi** [comment]
I'm still facing this issue with version 1.2.14

**Comment by khjabir** [comment]
> I'm still facing this issue with version 1.2.14
@yuekaidi 
This specific issue is working fine for me.
Refer this [CodeSandBox](https://codesandbox.io/s/heatmap-tooltip-forked-p8m35?file=/App.tsx)
