### ISSUE TITLE
🧐[问题] 雷达图 tooltip marker 颜色如何指定

### ISSUE THREAD

**Issue by zj1024** [ant-design/ant-design-charts#666]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
查看了 api 文档 和 ts 类型，没找到雷达图 tooltip marker 自定义颜色的地方
https://charts.ant.design/zh-CN/demos/radar?type=api

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/34162213/120957498-588c4700-c788-11eb-92ca-2601c087f275.png)

**Comment by lxfu1** [comment]
https://charts.ant.design/zh-CN/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip
