### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by Sherry0012** [ant-design/ant-design-charts#67]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
图表中的点击事件，例如柱状图点击事件

onColumnClick:() => console.log('====='),是无法有打印结果的。应该如何使用图表时间

**Comment by lxfu1** [comment]
放到 events 里面
events: {
  onColumnClick: () => {
     console.log(213)
  }
}

**Comment by Sherry0012** [comment]
谢谢呀，非常感谢


| |
谢青
|
|
邮箱：18729580582@163.com
|

签名由 网易邮箱大师 定制

在2020年06月09日 09:45，kevin 写道：

放到 events 里面
events: {
onColumnClick: () => {
console.log(213)
}
}
