### ISSUE TITLE
🐛[BUG]折线图&柱状图xField设置为'index'读取数组下标而非item.index字段

### ISSUE THREAD

**Issue by briage** [ant-design/ant-design-charts#672]
### 📷 复现步骤 
![image](https://user-images.githubusercontent.com/48514074/121316279-bca33c80-c93b-11eb-95af-c36ca5ad91e2.png)

### 💻 复现代码 const data = [{"time":"2021-06-04 14:35:20","index":1,"desc":"水位：13、qps：10","operationId":1436,"value":13},{"time":"2021-06-04 14:37:40","index":2,"desc":"水位：1183、qps：816","operationId":1437,"value":1183},{"time":"2021-06-04 14:41:10","index":3,"desc":"水位：2885、qps：2002","operationId":1438,"value":2885},{"time":"2021-06-04 14:46:45","index":4,"desc":"水位：4660、qps：3701","operationId":1439,"value":4660}];
const config = { data, xField: 'index', yField: 'value' };

### © 版本信息

- ant-design-charts 版本: 1.1.4
- 浏览器环境 chrome
- 开发环境  mac OS

**Comment by lxfu1** [comment]
index 使用 string 类型。
