### ISSUE TITLE
🐛 [BUG] Zoom / slider not working on StockChart

### ISSUE THREAD

**Issue by MarkLyck** [ant-design/ant-design-charts#674]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

When using the StockChart, and adding a slider to allow zooming. The slider does not appear.

```
  var config = {
    width: 400,
    height: 500,
    data: chartData,
    legend: false,
    xField: 'date',
    yField: ['close', 'open', 'high', 'low'],
    xAxis: { tickCount: 5 },
    slider: {
      start: 0.1,
      end: 0.5,
    },
  }
```
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

<img width="1537" alt="Screen Shot 2021-06-09 at 11 34 10" src="https://user-images.githubusercontent.com/6841110/121394094-9e771580-c916-11eb-94a3-2be68d6b970d.png">

As a user, I would expect to be able to add zoom functionality to the Stock Chart.

I also tried the horizontal scroll which did not work either.

**Comment by lxfu1** [comment]
Use the latest version.
