### ISSUE TITLE
🐛[BUG] Stock Slider handling is reversed

### ISSUE THREAD

**Issue by MarkLyck** [ant-design/ant-design-charts#676]
### 🐛 bug 

When adding a `slider` to the Stock chart, the dates / handling of it is reversed.

Dragging the slider to the left (towards the beginning) moves the chart to the right (towards the end).

Dragging it to the right towards the end, moves the chart to the beginning.

This is very confusing.

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

<img width="649" alt="Screen Shot 2021-06-09 at 19 37 38" src="https://user-images.githubusercontent.com/6841110/121446894-2df1e800-c95a-11eb-9ec6-f99784fde2c4.png">

Here's a codesandbox with reproduction: https://codesandbox.io/s/cold-rgb-pms68?file=/App.tsx

using the latest version: 1.1.12 released today.

**Comment by lxfu1** [comment]
First manually sort the data, will be fixed in the near future.

**Comment by lxfu1** [comment]
[V2](https://ant-design-charts-next.antgroup.com/examples/statistics/stock/#basic)

```ts
slider: {
      x: {}
    },
```
