### ISSUE TITLE
🧐[问题]柱状图的事件都不响应

### ISSUE THREAD

**Issue by ra24bit** [ant-design/ant-design-charts#68]
https://antv-g2plot.gitee.io/zh/docs/manual/plots/column#%E5%9B%BE%E5%BD%A2%E6%A0%87%E7%AD%BE%E4%BA%8B%E4%BB%B6

onColumnClick 应该在哪声明，如何声明，我在config里面声明，没有效果

const config = {
            title: {
                visible: true,
                text: '业务分母'
            },
            forceFit: true,
            data: this.state.data,
            padding: 'auto',
            xField: 'model',
            yField: 'count',
            xAxis: {
                title: {
                    visible: false
                }
            },
            yAxis: {
                title: {
                    text: "分母数量"
                }
            },
            label: {
                visible: true
            },
            onColumnClick: () => {console.log("eee")},
        };

**Comment by lxfu1** [comment]
放到 events 里面
events: {
        onColumnClick: () => {
          console.log(213)
        }
   }
