### ISSUE TITLE
请问何时能支持facet图，谢谢！

### ISSUE THREAD

**Issue by sherjf** [ant-design/ant-design-charts#689]
G2中有相关图表，引用的代码中也有，但好像目前不支持。

**Comment by visiky** [comment]
G2Plot 已经接入了，估计 charts 会在下个版本提供

**Comment by lxfu1** [comment]
稍等片刻，我发个版本。

**Comment by lxfu1** [comment]
v:  1.1.16， https://charts.ant.design/zh-CN/demos/facet
