### ISSUE TITLE
使用折线图时在配置里添加guideLine配置辅助线, 传入一个空数组会直接报错🐛[BUG]

### ISSUE THREAD

**Issue by malusama** [ant-design/ant-design-charts#69]
### © 版本信息

- ant-design-charts 版本: 0.9.4
- 浏览器环境: edge
- 开发环境 mac os

**Comment by malusama** [comment]
https://codesandbox.io/s/reverent-raman-fmw6t?fontsize=14&hidenavigation=1&theme=dark

**Comment by malusama** [comment]
> 能提供下复现代码吗 难到是浏览器不兼容？

提供了. 可以看一下是不是我使用的问题?

**Comment by lxfu1** [comment]
1.0 版本， 参考： https://charts.ant.design/demos/area#%E5%B8%A6%E4%B8%AD%E4%BD%8D%E7%BA%BF%E6%A0%87%E6%B3%A8%E7%9A%84%E5%9F%BA%E7%A1%80%E9%9D%A2%E7%A7%AF%E5%9B%BE
