### ISSUE TITLE
🧐[问题] why draw wrong ????

### ISSUE THREAD

**Issue by amirdoulat** [ant-design/ant-design-charts#692]
I pass data to Line chart . data have 3 parameters.
![001](https://user-images.githubusercontent.com/74908660/122207065-f5e92880-ceb6-11eb-9089-463ecd786c52.jpg)

![002](https://user-images.githubusercontent.com/74908660/122206538-bd494f00-ceb6-11eb-9b65-d97f42c601bb.jpg)

![003](https://user-images.githubusercontent.com/74908660/122206403-92f79180-ceb6-11eb-84e9-0494be5a58fd.jpg)

what can i do?

**Comment by lxfu1** [comment]
This doesn't seem to be a problem. Can you offer an online demo on CodeSandbox?
