### ISSUE TITLE
🧐[问题] DualAxes chart custom tooltip disappears in-between points

### ISSUE THREAD

**Issue by evybauer** [ant-design/ant-design-charts#694]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
DualAxes chart custom tooltip disappears in-between some points. It should show up all the time while hovering the chart lines. Is it a bug?

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
Here's a reproduction of the issue:
https://codesandbox.io/s/cool-wright-fixmb?file=/App.tsx

This is the exact point where the tooltip disppears:
<img width="709" alt="Screenshot 2021-06-16 at 4 17 53 PM" src="https://user-images.githubusercontent.com/48938870/122307362-08676000-cebf-11eb-8429-17c8bcdeebb5.png">

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
⚠️ In my project, the tooltip does not appear in-between any points. It only shows up when hovering the specific points.

**Comment by evybauer** [comment]
When hovering the chart lines in other sport the tooltip shows up without a problem:
![Screenshot 2021-06-16 at 4 30 00 PM](https://user-images.githubusercontent.com/48938870/122307974-41ec9b00-cec0-11eb-9dc3-7f4e59af1f54.png)

**Comment by lxfu1** [comment]
I found it is normal! [demo](https://codesandbox.io/s/sad-sutherland-dmsgk?file=/App.tsx)

**Comment by evybauer** [comment]
Hey @lxfu1, thanks for the quick reply. 
So it should be expected for the tooltip to disapear while hovering the line charts?
I do not see this problem in any of the Dual Axes [demos](https://charts.ant.design/demos/dual-axes). 🤔

**Comment by lxfu1** [comment]
I can't  understand what you mean, you expected disappears or appears?

**Comment by evybauer** [comment]
I expect it to appear all the time

**Comment by wqsworks** [comment]
> I can't understand what you mean, you expected disappears or appears?

同样一个封装好的DualAxes chart组件，在两个不同的页面中，有一个tooltip无法通过hover触发，必须点击才能触发，并且无法点击图标外的区域关闭。并且我看你们的ts定义中也没有triggerOn这个属性。

**Comment by lxfu1** [comment]
[Upgrade to V2](https://ant-design-charts-next.antgroup.com/examples/statistics/dual-axes/#dual-line)
