### ISSUE TITLE
🐛[BUG] 折线图y轴小数后会出现多位数字

### ISSUE THREAD

**Issue by iambool** [ant-design/ant-design-charts#697]
### 🐛 bug 描述 
折线图y轴数据没有精确到小数点后某位，出现超长浮点数，看起来很不舒服
![image](https://user-images.githubusercontent.com/30134533/122372419-3c13ba00-cf93-11eb-9720-e11ca9f7856d.png)

### 📷 复现步骤 
https://codesandbox.io/s/condescending-ganguly-0re62

### 🏞 期望结果 
1.0.18版本的显示是正常的，如下图
![image](https://user-images.githubusercontent.com/30134533/122372336-2dc59e00-cf93-11eb-962c-5cb982c2ced3.png)
更新依赖至最新后出现此问题

### 💻 复现代码 
https://codesandbox.io/s/condescending-ganguly-0re62

### © 版本信息
- ant-design-charts 版本: @ant-design/charts@1.1.16
- 浏览器环境 Chrome最新版本
- 开发环境 [e.g. windows10]

**Comment by lxfu1** [comment]
先用 yAxis.label.formatter 处理一下，大概率是底层 scale 出问题了。

**Comment by pearmini** [comment]
这个是应该是哪一次升级把获得 ticks 的 wilkinson-extended 改出了问题，我之后看看能不能解决，如果使用 r-pretty 就没有问题了。

**Comment by alicekahei** [comment]
在比较特定的数据下会出现，y=1.0,1.1.    如果是y=1.0  y=2.1则不会出现

**Comment by hustcc** [comment]
已经解决，删除 lock，重新安装依赖。保证安装的 scale 版本是 0.3.11。
