### ISSUE TITLE
🐛[BUG]Area图，若yField中存在负数，则坐标轴显示不正确，建议修正。

### ISSUE THREAD

**Issue by sherjf** [ant-design/ant-design-charts#699]
如下图，A1与A2相差的比例不对，也与坐标不对应。
<img width="733" alt="截屏2021-06-17 20 34 57" src="https://user-images.githubusercontent.com/37824950/122397393-830da980-cfab-11eb-93ed-c4acae463f91.png">

**Comment by lxfu1** [comment]
startOnZero: false

**Comment by sherjf** [comment]
加了，没有效果。

**Comment by lxfu1** [comment]
Sorry,   isStack: false.

**Comment by sherjf** [comment]
OK，可以了，谢谢！
