### ISSUE TITLE
🐛[BUG]yAxis里面的设置参数没有生效

### ISSUE THREAD

**Issue by zhu-ml** [ant-design/ant-design-charts#70]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
yAxis: {
        min: 0,
        max: 100,
        tickCount: 5,
        tickInterval: 20
      }
想设置纵轴的刻度单位，但是没有生效
且不论设不设置yAxis，折线图的点趋势展示都不正确
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
import React, { useMemo } from 'react';
import { Line } from '@ant-design/charts';

export type MonthlyTrendProps = {
  lineProps?: any;
};

const MonthlyTrend: React.FC<MonthlyTrendProps> = props => {

  const data = [
    {month: 'Jan', score: '20'},
    {month: 'Feb', score: '50'},
    {month: 'Mar', score: '80'},
    {month: 'Apr', score: '70'},
    {month: 'May', score: '60'},
    {month: 'Jun', score: '40'},
    {month: 'Jul', score: '20'},
    {month: 'Aug', score: '30'},
    {month: 'Sep', score: '40'},
    {month: 'Oct', score: '60'},
    {month: 'Nov', score: '80'},
    {month: 'Dec', score: '90'}
  ]

  const config = useMemo(() => {
    return {
      data: data,
      title: {
        visible: true,
        text: 'test'
      },
      xField: 'month',
      yField: 'score',
      point: {
        visible: true,
      },
      color: '#FA8C16',
      yAxis: {
        min: 0,
        max: 100,
        tickCount: 5,
        tickInterval: 20
      }
    }
  }, [data])

  return <Line {...config} />;
};

export default MonthlyTrend;

### 🏞 期望结果 [描述你原本期望看到的结果]
Y轴的刻度从0-100，间隔为20展示，整个折线趋势正常展示，而不是后面的数值少的展示的比前面数值多的高

### © 版本信息

- ant-design-charts 版本: [0.9.4]
- 浏览器环境[Chrome]
- 开发环境 [win10]

**Comment by lgxZJ** [comment]
> data: score 用 number 类型

Damn it, searched for a long while...
