### ISSUE TITLE
🐛[BUG]Mix图表中，柱子的columnWidthRatio设置不起作用

### ISSUE THREAD

**Issue by sherjf** [ant-design/ant-design-charts#701]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
在view中，使用type: interval，柱子的宽度只能通过mapping的size调整，无法使用columnWidthRatio调整。
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
```ts
 args: {
  minColumnWidth: 100,
},
```
