### ISSUE TITLE
🐛[BUG] Line 在 React 17 有 TS 语法错误

### ISSUE THREAD

**Issue by wottery** [ant-design/ant-design-charts#704]
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

https://codesandbox.io/s/angry-glitter-z2v8t?file=/App.tsx

### 🏞 期望结果 [描述你原本期望看到的结果]

BugFix

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
  - 1.1.17
- 浏览器环境
  - chrome 最新版
- 开发环境 [e.g. mac OS]
  - mac OS

**Comment by wottery** [comment]
有人看么？

**Comment by visiky** [comment]
截图呢？

**Comment by lxfu1** [comment]
先 // @ts-ignore 解决问题，再来个错误截图，你提供的在线链接没有复现。

**Comment by lxfu1** [comment]
提供的在线链接没有看到任何 ts 问题。
![image](https://user-images.githubusercontent.com/31396322/123216450-23a82000-d4fc-11eb-9dd4-8c8d83d34087.png)
