### ISSUE TITLE
如何设置 X 轴标签文字的颜色🧐[问题]

### ISSUE THREAD

**Issue by ly020044** [ant-design/ant-design-charts#705]
### 🚑 其他信息：如下图红色部分文字
![image](https://user-images.githubusercontent.com/26132388/122853704-3c220a00-d345-11eb-93aa-7b46af615cc9.png)

**Comment by lxfu1** [comment]
xAxis.label.style.fill: 'red'

**Comment by ly020044** [comment]
谢谢！

**Comment by 1165656731** [comment]
不可以 给指定的字段换颜色么
