### ISSUE TITLE
🐛[BUG] Typing on chartRef is wrong

### ISSUE THREAD

**Issue by Altareos** [ant-design/ant-design-charts#706]
### 🐛 bug 描述
`chartRef` in charts expects a `ChartRefOptions` which accepts `React.MutableRefObject<G2PlotConfig | undefined>`, but the ref is actually a `import('@antv/g6-pc').IGraph`

### 📷 复现步骤
- Initiate a TypeScript React project
- Create a chart
- Take its ref with the expected G2PlotConfig object: attributes are `undefined`
- Try to access an attribute or a method from a g6-pc IGraph: it works

### 🏞 期望结果
chartRef should accept a `React.MutableRefObject<IGraph | undefined>` because it is what is actually passed to the ref

### 💻 复现代码
https://codesandbox.io/s/icy-leftpad-bsgnh?file=/src/App.tsx
Try removing the `// @ts-expect-error` on line 49

### © 版本信息

- ant-design-charts 版本: 1.1.17
- 浏览器环境 : Firefox
- 开发环境 : Linux, Node 16.3.0, React 17.0.2, TypeScript 4.3.4

**Comment by lxfu1** [comment]
There is a problem with the current type definition, recently fixed.

**Comment by lxfu1** [comment]
v: 1.1.18 ,  Don't recommend chartRef.
```ts
import { PieConfig } from "@ant-design/charts/es/pie";
import { Plot } from "@ant-design/charts/es/interface";


<Pie
  {...config}
  onReady={(plot: Plot<PieConfig>) => {
    plot.on("element:click", (event) => setName(event.data.data.type));
  }}
/>
```
