### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by jixindong** [ant-design/ant-design-charts#708]
### © 版本信息

- ant-design-charts 版本: [1.1.17]
- 浏览器环境 [Chrome 88.0.4324.96]
- 开发环境 [windows 10]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/61441236/122910601-f5560380-d388-11eb-855a-6cc588c9f7b6.png)
![image](https://user-images.githubusercontent.com/61441236/122910633-0141c580-d389-11eb-96c6-e4aa74cafb16.png)

**Comment by lxfu1** [comment]
词云图建议关闭 autoFit.
```ts
  autoFit: false,
  width: 600,
  height: 400,
```
