### ISSUE TITLE
🧐[问题] 折线图数据按分类排序，得到的图表会乱

### ISSUE THREAD

**Issue by iambool** [ant-design/ant-design-charts#713]
### 🧐 问题描述 
当给到折线图的数据是按分类排序的时候，画出的折线图，横坐标不是从所有数据中最小的开始的，这个是规定吗？
比如，数据按分类排序如下：
![image](https://user-images.githubusercontent.com/30134533/123222812-e6935c00-d502-11eb-8066-3c8ac26c2742.png)

得到的图表横坐标是从分类第一项的横坐标开始的
![image](https://user-images.githubusercontent.com/30134533/123222517-9b794900-d502-11eb-82d9-723183b8ce6a.png)

### 💻 示例代码
https://codesandbox.io/s/priceless-chatelet-uv0e7?file=/App.tsx

**Comment by edisonLzy** [comment]
我也有类似的问题 请问你这个 issue解决了吗

**Comment by iambool** [comment]
> 我也有类似的问题 请问你这个 issue解决了吗

前端还没有解决，也没有回复。只能后端数据先做好排序，再给到前端，这样子
