### ISSUE TITLE
An issue with showing wordcloud elements in the first wordcloud render (or when I hard refresh) 🐛[BUG]

### ISSUE THREAD

**Issue by edelveiss** [ant-design/ant-design-charts#715]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Hi,
There is an issue with showing wordcloud elements. I am using a mask. In the config variable I send data with an array of 300 elements.plot.oprions.data gives an array of 300 elements.
But ref.current.getChart().chart.geometries[0].elements gives an array of 230 length, and therefore, wordcloud shows 230. When I re render the wordcloud it shows all 300 elements. In the first wordcloud render (or when I hard refresh) it always shows less elements than I send to config data, so this is the main issue that I am having. Could you please check it out and see if there are any issues that can be fixed? Thank you

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1.render more than 300 elements in a wordcloud with a mask
2. Hard refresh the page

### 🏞 期望结果 [描述你原本期望看到的结果]
1.render more than 300 elements in a wordcloud with a mask
2. Hard refresh the page
3. See all 300 elements in a wordcloud

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- "@ant-design/charts": "^1.1.4",
- 浏览器环境
- Google Chrome Version 91.0.4472.114 (Official Build) (x86_64)
- 开发环境 [e.g. mac OS]
- macOS Catalina version 10.15.7

**Comment by grandsilence** [comment]
any fix for the issue?

**Comment by edelveiss** [comment]
No

**Comment by lxfu1** [comment]
The `Wordcloud`  will filter data that cannot be display, algorithm determined.
