### ISSUE TITLE
🐛[BUG] 图例过多时出现分页按钮，点击分页按钮，图例不切换

### ISSUE THREAD

**Issue by jim-tian** [ant-design/ant-design-charts#717]
### © 版本信息

- ant-design-charts 版本: [1.1.10]
- 浏览器环境[Chrome 90.0.4430.212]
- 开发环境 [windows 10]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![图1](https://user-images.githubusercontent.com/53417037/123360393-d1203f80-d59f-11eb-8b2e-07c7faf6753d.png)
点击下一页，功能正常
![图2](https://user-images.githubusercontent.com/53417037/123360446-e9905a00-d59f-11eb-9700-28cdaaefa0e9.png)
此时再次点击上一页，图例不会变化
![图3](https://user-images.githubusercontent.com/53417037/123360504-03ca3800-d5a0-11eb-9ef8-8ca84648c8b0.png)

BTW，这个图例分页按钮的颜色，可以配置吗？

**Comment by jim-tian** [comment]
补充下，似乎只会在 renderer: 'svg' 下出现这种情况 ...

**Comment by lxfu1** [comment]
[Upgrade to V2](https://ant-design-charts-next.antgroup.com/)
