### ISSUE TITLE
🧐[问题]如何设置Facet图表中多view之间的联动交互？

### ISSUE THREAD

**Issue by sherjf** [ant-design/ant-design-charts#720]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
FacetCfg.interactions只能设置view自身的交互，association-active等联动交互失效，请问要如何设置才有效？

**Comment by lxfu1** [comment]
参考下这个：[tooltip联动](https://charts.ant.design/zh-CN/guide/case#tooltip-%E8%81%94%E5%8A%A8)
