### ISSUE TITLE
🧐[问题]尝试自定义折线图交互时，action 初始化抛出异常

### ISSUE THREAD

**Issue by chihane** [ant-design/ant-design-charts#728]
### 🧐 问题描述

<img width="450" alt="iShot2021-07-01 17 21 26" src="https://user-images.githubusercontent.com/6443418/124100269-e827cb80-da90-11eb-82cb-f542ff850a82.png">

异常见图片。

异常在渲染图表时抛出，去除 `cfg` 则问题消失。

看错误提示，问题应当出在使用 `tooltip:show` 创建 `TooltipAction` 时没有传入 `context`。

搜索了 issues 和 G2Plot 的 issues，没有类似问题，应该是我代码写错了，但不知道错在哪，请求帮助。

### 💻 示例代码

**核心在 `config` 的 `interactions` 一节。**

```javascript
function buildChart(historiesLoading, histories) {
    const max = Math.max(...histories.map(h => h.点位));
    const min = Math.min(...histories.map(h => h.点位));
    const yPadding = (max - min) * 0.05;

    const config = {
        data: histories,
        xField: '日期',
        yField: '点位',
        seriesField: '维度',
        lineStyle: {
            lineWidth: 1,
        },
        yAxis: {
            label: null,
            grid: {
                line: null,
            },
            minLimit: isFinite(yPadding) ? min - yPadding : 0,
            maxLimit: isFinite(yPadding) ? max + yPadding : 0,
        },
        xAxis: {
            tickMethod: scale => {
                const ticks = [];

                let prevDate = new Date(scale.values[0]);
                scale.values.forEach(dateString => {
                    const d = new Date(dateString);
                    if (d.getFullYear() !== prevDate.getFullYear()) {
                        ticks.push(dateString);
                        prevDate = d;
                    }
                });

                return ticks;
            },
            label: {
                formatter: date => new Date(date).getFullYear(),
            },
        },
        interactions: [
            {
                type: 'tooltip',
                cfg: {
                    start: [{trigger: 'plot:mousemove', action: 'tooltip:show'}],
                    end: [{trigger: 'plot:mouseleave', action: 'tooltip:hide'}],
                },
            },
        ],
    };
    return (
        <div>
            <Spin size='middle' spinning={historiesLoading}>
                <Line {...config} />
            </Spin>
        </div>
    );
}

function HistoryChart(props) {
    const [historiesLoading, setHistoriesLoading] = useState(false);
    const [histories, setHistories] = useState([]);

    useEffect(() => {
        loadHistories(props.type, props.code, props.fromDate, props.toDate, setHistoriesLoading, setHistories)
    }, [props.type, props.code, props.fromDate, props.toDate]);

    return buildChart(historiesLoading, histories);
}

export default HistoryChart;
```

**Comment by lxfu1** [comment]
不建议使用 interactions， 可以描述一下你的需求。

**Comment by chihane** [comment]
> 不建议使用 interactions， 可以描述一下你的需求。

我想要实时地在鼠标所在位置绘制横线，标出 y 值

**Comment by lxfu1** [comment]
> > 不建议使用 interactions， 可以描述一下你的需求。
> 
> 我想要实时地在鼠标所在位置绘制横线，标出 y 值

实时绘制会多次渲染，建议通过绑定事件的方式获取鼠标位置在容器上加个浮层。https://charts.ant.design/zh-CN/guide/case#%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A

**Comment by chihane** [comment]
> > > 不建议使用 interactions， 可以描述一下你的需求。
> > 
> > 
> > 我想要实时地在鼠标所在位置绘制横线，标出 y 值
> 
> 实时绘制会多次渲染，建议通过绑定事件的方式获取鼠标位置在容器上加个浮层。https://charts.ant.design/zh-CN/guide/case#%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A

尝试了一下，应该可以曲线救国。

为什么不建议使用 interactions？

**Comment by lxfu1** [comment]
> > > > 不建议使用 interactions， 可以描述一下你的需求。
> > > 
> > > 
> > > 我想要实时地在鼠标所在位置绘制横线，标出 y 值
> > 
> > 
> > 实时绘制会多次渲染，建议通过绑定事件的方式获取鼠标位置在容器上加个浮层。https://charts.ant.design/zh-CN/guide/case#%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A
> 
> 尝试了一下，应该可以曲线救国。
> 
> 为什么不建议使用 interactions？

文档问题。

**Comment by chihane** [comment]
> > 不建议使用 interactions， 可以描述一下你的需求。
> 
> 我想要实时地在鼠标所在位置绘制横线，标出 y 值。
> 
> 默认的 tooltip 只能标出 x 位置对应的数据的值，而我想标出的是鼠标所在的 y 位置值。

https://github.com/antvis/G2Plot/issues/2673

最终通过配置 tooltip 的 crosshair 实现了上面的需求，在这边留一个引用以备其他人万一需要。
