### ISSUE TITLE
🧐 How remove unnecessary height

### ISSUE THREAD

**Issue by MaximusFT** [ant-design/ant-design-charts#729]
### 🚑 
![Screenshot_4](https://user-images.githubusercontent.com/587509/124368262-b153e000-dc5f-11eb-97fd-29b3cb23cb3d.png)

**Comment by lxfu1** [comment]
```ts
yAxis: {
  min: null
}
```

**Comment by MaximusFT** [comment]
> ```ts
> yAxis: {
>   min: null
> }
> ```

Thanks!
