### ISSUE TITLE
Plot both line and scatter on same plot

### ISSUE THREAD

**Issue by vaasu070** [ant-design/ant-design-charts#73]
I am using scatter plot to plot my data. But I need line plot on it as well.

I have been going through g2plots documentation , I have not found a single example where I can plot Scatter and line on same plot.

Please help me out , How can I do that(better if explained with example) ? and also How can I detect click event on points in scatter plot?
![scatter plot here](https://user-images.githubusercontent.com/33760706/84355456-4660e280-abe0-11ea-8b42-694918248bb0.PNG)

**Comment by lxfu1** [comment]
events: {
       onPointClick: (params) => {
          console.log(params);
       }
}

**Comment by lxfu1** [comment]
Line + Scatter is not implemented at present.
