### ISSUE TITLE
🐛[BUG] Treemap drilldown property ignored

### ISSUE THREAD

**Issue by HenriqueMCastro** [ant-design/ant-design-charts#731]
### 🐛 When trying to setup a treemap with the drilldown interaction, the drilldown property has no effect. Drilldown configuration is defined here: https://charts.ant.design/demos/treemap?type=api

It should be possible to activate drilldown by doing this:
`<Treemap
    drilldown={{
        enabled: true,
        breadCrumb: {
            rootText: 'root'
         }
      }}
/>`
But this ignored and the only way to enable the drilldown is like this:
`<Treemap
    interactions={[{type: 'treemap-drill-down'}]}
/>`
But this doesn't give you the ability to change the rootText so it doesn't fix my use case.

- ant-design-charts: 1.1.20
- Chrome
- Windows

**Comment by lxfu1** [comment]
https://codesandbox.io/s/suspicious-galileo-05qji?file=/App.tsx

**Comment by HenriqueMCastro** [comment]
Thanks for the example. The difference seems to be that I return a Treemap instance even when I'm waiting for the data and then when the data arrives the drilldown does not work. But I have worked around it by putting the Treemap inside a Card with the loading property set properly and now the drilldown works.
