### ISSUE TITLE
🐛[BUG]打包报错./node_modules/@antv/algorithm/es/gaddi.js Attempted import error: '__spreadArray' is not exported from 'tslib'.

### ISSUE THREAD

**Issue by AdmiralPanFeng** [ant-design/ant-design-charts#732]
### 🐛 bug 描述 ./node_modules/@antv/algorithm/es/gaddi.js
Attempted import error: '__spreadArray' is not exported from 'tslib'.

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
issue 里面查询一下  tslib ，之前有很多类似问题。
