### ISSUE TITLE
👑 [需求]flow-grap节点多时支持收缩

### ISSUE THREAD

**Issue by bi-kai** [ant-design/ant-design-charts#733]
https://charts.ant.design/demos/dagre-fund-flow-graph/#%E6%BC%94%E7%A4%BA%E7%BB%93%E6%9E%9C

当节点很多时，是否能像思维导图一样，收缩、展开节点呢。
![图片](https://user-images.githubusercontent.com/15070379/124915039-a6180000-e023-11eb-9d0b-795c4bb27295.png)

是否能实现散开再汇聚到一个节点的效果？
![图片](https://user-images.githubusercontent.com/15070379/124914889-72d57100-e023-11eb-8197-bb575bb4a36d.png)

**Comment by lxfu1** [comment]
流向图和思维导图数据结构是不一样的，最近正在重构，能详细描述下你的需求吗？

**Comment by bi-kai** [comment]
@lxfu1 你好，我描述一下：

**Comment by lxfu1** [comment]
最新版本已经支持。
