### ISSUE TITLE
🧐 How to trigger plot.toDataURL() after animation?

### ISSUE THREAD

**Issue by laptopisasset** [ant-design/ant-design-charts#734]
### 🧐 Plot View Life Cycle events not working properly
I am trying to genarate pdf which include ant-design-charts using [react-pdf](https://react-pdf.org/), For constructing document i am in need of charts data url just after rendering it, when i use plot.on("afterrender", () => {}) from onReady, it is not triggering it, if so it triggers the dataUrl generated is empy think so it is due to animation, I am in need of either of two ways to solve this.

* is there any Api or lifecylce hook, which runs just after the animation end, I did searched for such an event landed on afterrender, which is not working properly i dont know why please correct me if i am wrong code will attached
* Or is any other way to achieve this

### 💻 Code Snippets
```
App.js

import { useState } from "react";
import { Pie } from "@ant-design/charts";

import { Document, Page, Image, PDFDownloadLink } from "@react-pdf/renderer";

const data = [
  {
    type: "Classification One",
    value: 27,
  },
  {
    type: "Classification Two",
    value: 25,
  },
  {
    type: "Classification Three",
    value: 18,
  },
  {
    type: "Classification Four",
    value: 15,
  },
  {
    type: "Classification Five",
    value: 10,
  },
  {
    type: "Other",
    value: 5,
  },
];

const config = {
  appendPadding: 10,
  data: data,
  angleField: "value",
  colorField: "type",
  radius: 0.75,
  label: {
    type: "spider",
    labelHeight: 28,
    content: "{name}\n{percentage}",
  },
  interactions: [{ type: "element-selected" }, { type: "element-active" }],
};

function MyDoc({ chartDataURL }) {
  return (
    <Document>
      <Page wrap>
        <Image src={chartDataURL} />
      </Page>
    </Document>
  );
}

function App() {
  const [dataUrl, setDataUrl] = useState("");

  return (
    <>
      {dataUrl ? (
        <PDFDownloadLink
          document={<MyDoc chartDataURL={dataUrl} />}
          fileName="report.pdf"
        >
          {({ loading }) => (loading ? "Loading Document" : "Download now!")}
        </PDFDownloadLink>
      ) : null}
      <Pie
        {...config}
        onReady={(plot) => {
          plot.on("afterrender", () => {
            setDataUrl(plot.toDataURL());
          });
        }}
      />
    </>
  );
}

export default App;

```

### 🚑 AdditionalInfo[Screenshots]

![Screenshot from 2021-07-08 17-24-44](https://user-images.githubusercontent.com/43651329/124917579-a0192380-e011-11eb-83d4-98f8330f2ea0.png)

As you can see download link is not generated since afterrender is not triggered

**Comment by laptopisasset** [comment]
Hi @lxfu1, can u please help me in this.

**Comment by lxfu1** [comment]
OnReady is completed after afterrender, closing animate or using setTimeout.

**Comment by laptopisasset** [comment]
Thanks @lxfu1, will try.

**Comment by laptopisasset** [comment]
Hi I did as u said, i dont know why two differnt plots returns same dataURL, can u help me pls @lxfu1
