### ISSUE TITLE
🧐How can I align to top Pie

### ISSUE THREAD

**Issue by MaximusFT** [ant-design/ant-design-charts#735]
### 🧐
I use Pie chart. When content is different in Data, I have strange look. How can I align different Pies to the top?

### 💻
https://codesandbox.io/s/clever-villani-s8zwe?file=/App.tsx

### 🚑
![image](https://user-images.githubusercontent.com/587509/124953958-e2dcfa80-e015-11eb-8fb2-4c7b0059814c.png)

**Comment by lxfu1** [comment]
Set the same height and padding.
```ts
  const padding = [0, 20, 50, 20];
  const height = 300;
```

**Comment by MaximusFT** [comment]
Thanks for this solution. This is not a perfect solution. Because the problem is responsive. I updated the example and you can see it when moving screen width.
But globally will be great to add props (like align vertical and horizontal, padding and others) to control Donut and control items separately.
