### ISSUE TITLE
🧐[问题]使用html2canvas的时候，饼环图中间的文字会偏移

### ISSUE THREAD

**Issue by LouisTsang-jk** [ant-design/ant-design-charts#737]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

使用html2canvas给页面进行截图的时候发现饼环图中间的文字发生了偏移

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://codesandbox.io/s/youthful-dream-5h41t?file=/App.tsx
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/20528651/125258540-08794500-e331-11eb-9f50-0dd61b8b01a8.png)

**Comment by lxfu1** [comment]
试试 downloadImage https://charts.ant.design/zh-CN/guide/case#%E5%9B%BE%E8%A1%A8%E4%B8%8B%E8%BD%BD

**Comment by LouisTsang-jk** [comment]
> 试试 downloadImage https://charts.ant.design/zh-CN/guide/case#%E5%9B%BE%E8%A1%A8%E4%B8%8B%E8%BD%BD

我目前的需求是对页面截图，所以用dowloadImage可能不符合
另外我试了一下原生g2是可以的
https://codesandbox.io/s/busy-feather-ktbno?file=/index.ts

**Comment by lxfu1** [comment]
中间的文字是DOM实现的，感觉是样式冲突。

**Comment by LouisTsang-jk** [comment]
> 中间的文字是DOM实现的，感觉是样式冲突。

是的，我试了一下是中间的文字使用了`text-shadow:0px 0px 0px;`的原因，具体为什么html2canvas没有正常渲染的原因我可能还要再看看。
目前我先用annotations去解决问题了
谢谢

**Comment by visiky** [comment]
> > 中间的文字是DOM实现的，感觉是样式冲突。
> 
> 是的，我试了一下是中间的文字使用了`text-shadow:0px 0px 0px;`的原因，具体为什么html2canvas没有正常渲染的原因我可能还要再看看。
> 目前我先用annotations去解决问题了
> 谢谢

感谢帮忙定位问题。

**Comment by LouisTsang-jk** [comment]
是`html2canvas`的问题，v.1.0.0后面都可以复现，已向`html2canvas`的仓库提issues.
