### ISSUE TITLE
🧐[问题]求助一个关于仪表盘设置的问题

### ISSUE THREAD

**Issue by shine135235** [ant-design/ant-design-charts#738]
![image](https://user-images.githubusercontent.com/18108307/125386651-3745f880-e3cf-11eb-97a5-b8a3020e38be.png)
像这样的图,我只想再开始的位置标注个最小值是0 然后再在结束的位置标注一个自定义的数值.
该怎么设置啊.API上找不到.

**Comment by lxfu1** [comment]
不支持这种配置， absolute 一下吧。
