### ISSUE TITLE
🧐[问题]图例legend可以自定义么？

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/ant-design-charts#739]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![WX20210714-143814](https://user-images.githubusercontent.com/33448924/125575007-6c8e936f-118d-4f64-a4f2-02ecc9fb122a.png)
环图的图例可以自定义么？具体怎么实现？

**Comment by harveyLXH** [comment]
假设传感器数据为0，能隐藏吗？

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/315
