### ISSUE TITLE
🧐[问题]如何设置Legend的字体不同的颜色

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/ant-design-charts#740]
### 🧐 问题描述
如何设置Legend的字体不同的颜色
### 💻 示例代码 
https://codesandbox.io/s/silent-architecture-km2x9?file=/src/App.tsx

### 🚑 其他信息 
![image](https://user-images.githubusercontent.com/33448924/125580890-8158d6ff-8779-4e78-bbb3-eb446e5135fd.png)

**Comment by lxfu1** [comment]
目前不支持，只能关闭legend自己实现。
