### ISSUE TITLE
World Map

### ISSUE THREAD

**Issue by pieterbergmans** [ant-design/ant-design-charts#744]
Hi...I noticed that antd has World Map displayed on one of their dashboard examples.  Here is a link to the image:

https://gw.alipayobjects.com/zos/antfincdn/Ls0j%26N%24i4A/4fcb4e43-5b33-4f3e-83ee-07b308c192ff.png

How can I implement this map?  I don't see documentation on it.

Thanks in advance.

**Comment by Shamann** [comment]
A world map is just a background view containing a polygon drawn from geo data. There are several [demos](https://g2.antv.vision/zh/examples/gallery) for G2, which you may have a look.
You also can adopt them to ant-design charts by using a Mix component:
<https://codesandbox.io/s/affectionate-lovelace-dk0vh?file=/App.tsx>

**Comment by lxfu1** [comment]
World map is not supported at present, I will support it before 1122.
