### ISSUE TITLE
🐛[BUG] legend selected does not work on Dual Axes chart

### ISSUE THREAD

**Issue by askurat** [ant-design/ant-design-charts#745]
### 📷 Reproductions Steps
```
legend: {
    selected: {
       bill: false,
    },    
}
```

### 🏞 Expected Results - bill should be disabled by default
![image](https://user-images.githubusercontent.com/9997087/125861172-14738655-2318-4ef6-8068-684ab192ce29.png)

### © 版本信息

- ant-design-charts: 1.1.20
- Browser: Chrome

**Comment by lxfu1** [comment]
Not support at current.

**Comment by lxfu1** [comment]
V2 版本，参考 https://codesandbox.io/p/sandbox/sleepy-hamilton-cfxyqw
