### ISSUE TITLE
🧐[问题]饼图默认选中怎么实现，以及再点击不允许取消选中

### ISSUE THREAD

**Issue by weiman-133** [ant-design/ant-design-charts#747]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
希望能够实现默认选中，并且永远保持有且只有一个选中，不允许再点击取消选中

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/86717611/125904156-15fc477f-bd13-47d5-8243-39d27dad70c9.png)
如图，保持这种选中效果

**Comment by lxfu1** [comment]
```ts
onReady: (plot)=>{
    plot.setState('selected', (item)=>{
    return item.type === '分类一';
  })
}
```

**Comment by xixiqnmb** [comment]
> ```ts
> onReady: (plot)=>{
>     plot.setState('selected', (item)=>{
>     return item.type === '分类一';
>   })
> }
> ```

这没用啊，获得不到item啊
