### ISSUE TITLE
👑 [需求]ChartLoading 组件支持传入样式

### ISSUE THREAD

**Issue by 2018Cool** [ant-design/ant-design-charts#748]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
想让ChartLoading背景为透明，这样图表刷新的时候没有明显的闪烁。目前ChartLoading不支持传入样式来修改背景
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
ChartLoading支持传入样式来修改加载状态组件样式

**Comment by lxfu1** [comment]
loadingTemplate
