### ISSUE TITLE
官网一些实例跳转错误啊🐛[BUG]

### ISSUE THREAD

**Issue by malusama** [ant-design/ant-design-charts#75]
### 🐛 bug 描述 
图表联动
https://charts.ant.design/demos/global#%E5%9B%BE%E8%A1%A8%E8%81%94%E5%8A%A8

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
我们补充一下

**Comment by lxfu1** [comment]
1.0 已解决。
