### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by WenDaaa** [ant-design/ant-design-charts#754]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
在使用antdcharts的流程图的时候，鼠标hover或者点击的时候可以出现一个自定义的tooltips

### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
希望antdCharts的流程图可以像G6一样有一个透出一个getContent的方法去添加tooltips的方式。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
https://g6.antv.vision/zh/docs/api/Plugins#dom-tooltip

**Comment by lxfu1** [comment]
```tsx
    tooltipCfg: {
      show: true,
      customContent: () => '123'
    },
```
