### ISSUE TITLE
🧐[问题] error TS1128: Declaration or statement expected.

### ISSUE THREAD

**Issue by zhirong2016** [ant-design/ant-design-charts#757]
### 💻 示例代码 项目引入Line 组件
![image](https://user-images.githubusercontent.com/18457728/126275367-a2f0bc8c-933f-4636-9a0b-ccfceaa897a6.png)
set NODE_ENV=production&&set GENERATE_SOURCEMAP=false&&react-app-rewired build --scripts-version react-scripts-ts
编译失败

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/18457728/126275265-12843511-e1de-420a-8798-f7627458de2c.png)
![image](https://user-images.githubusercontent.com/18457728/126275280-78508401-4ae3-4f1b-859f-e184f1c66cc6.png)

**Comment by zhirong2016** [comment]
![image](https://user-images.githubusercontent.com/18457728/126276156-95a1da1e-fa23-4382-b856-858d6bfd25ea.png)

**Comment by lxfu1** [comment]
看不出问题，可以提供一下复现地址吗？

**Comment by zhirong2016** [comment]
typescript版本3.3
安装最新版本1.2.2&nbsp; 里面的依赖包检查报错
***@***.***/g2plot 里面的.d.ts文件了编译检查报错了 里面export type {types}提示了这个错误error TS1128: Declaration or statement expected.
&nbsp;









李志嵘
皑瑞齐


 联系我









&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Joel Alan"; 
Date: 2021年7月21日(星期三) 中午11:03
To: "ant-design/ant-design-charts"; 
Cc: "李志嵘"; "Author"; 
Subject: Re: [ant-design/ant-design-charts] 類[问题] error TS1128: Declaration or statement expected. (#757)

&nbsp;


 
看不出问题，可以提供一下复现地址吗？

**Comment by zhirong2016** [comment]
或者说我需要修改成使用哪个版本才能正常使用这个ant-design-charts&nbsp; ts版本是3.4.5

&nbsp;









李志嵘
皑瑞齐


 联系我









&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Joel Alan"; 
Date: 2021年7月21日(星期三) 中午11:03
To: "ant-design/ant-design-charts"; 
Cc: "李志嵘"; "Author"; 
Subject: Re: [ant-design/ant-design-charts] 類[问题] error TS1128: Declaration or statement expected. (#757)

&nbsp;


 
看不出问题，可以提供一下复现地址吗？

**Comment by lxfu1** [comment]
试试子包， @ant-design/plots ，还有问题的话提供一下复现链接再打开。
