### ISSUE TITLE
🧐[问题] 配置legend，是否有参数可以设置图例的大小？

### ISSUE THREAD

**Issue by harveyLXH** [ant-design/ant-design-charts#758]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
- 配置legend，是否有参数可以设置图例的大小？官方的g2 的legend配置有三个参数，分别是shape,color,size
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```
  var config = {
    data: data,
    isStack: true,
    xField: 'year',
    yField: 'value',
    seriesField: 'type',
    label: {
      style: {
        fontWeight: 800,
      },
      position: 'middle',
      layout: [
        { type: 'interval-adjust-position' },
        { type: 'interval-hide-overlap' },
        { type: 'adjust-color' },
      ],
    },
    legend: {
      layout: 'horizontal',
      position: 'bottom',
    },
  };

 <Column {...config} />
```

**Comment by visiky** [comment]
https://g2plot.antv.vision/zh/docs/api/components/legend#itemwidth

`itemWidth`, `maxWidth`, `maxWidthRatio` 总有适合你的

**Comment by harveyLXH** [comment]
设置图例里面marker的大小



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月23日(星期五) 上午8:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-charts] 🧐[问题] 配置legend，是否有参数可以设置图例的大小？ (#758)





 
https://g2plot.antv.vision/zh/docs/api/components/legend#itemwidth
 
itemWidth, maxWidth, maxWidthRatio 总有适合你的

**Comment by lxfu1** [comment]
```ts
legend: {
  items: [
    {
      id: 'xx',
      name: '月份',
      value: '月份',
      marker: {
        symbol: 'circle',
        style: {
          fill: '#f20',
          r: 6
        }
      }
    }
  ]
},
```
