### ISSUE TITLE
🧐[问题]：是否有计划添加中国地图呢？

### ISSUE THREAD

**Issue by wenslo** [ant-design/ant-design-charts#76]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
如题，是否有计划添加中国地图的图表呢

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
如果有计划，别忘了南海诸岛

**Comment by lxfu1** [comment]
中国地图属于地理可视化了，可以参考哈 L7, https://l7.antv.vision/zh

**Comment by wenslo** [comment]
好的，谢谢，没你们弄得容易上手，哈哈
