### ISSUE TITLE
🧐[问题] 怎么创建一个多Y轴图表

### ISSUE THREAD

**Issue by wuqingabc** [ant-design/ant-design-charts#760]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我们需求有个图表，X轴是同一时期的时间坐标，Y轴有几种不同的数据，刻度都不一样，但我们想放一起，以便能直接看出几种不同曲线变化之间的规律。查询文档看到有双轴DualAxes函数，但超过双轴的似乎找不到。所以想请教一下大家是怎么实现这个需求的？ 我们考虑过多图联动，但曲线不映射在一个坐标系里面很难进行直观比较。
可以像Echart这么使用么？ https://www.cnblogs.com/hao-1234-1234/p/14180540.html
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
https://www.cnblogs.com/hao-1234-1234/p/14180540.html

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![111248_0aQd_2911530](https://user-images.githubusercontent.com/4350871/126462677-93beb632-1032-432e-9b79-c93edf5ae17a.png)

**Comment by qingfengmy** [comment]
yField: ['value', 'value1']

**Comment by liuxingling** [comment]
请问这个最后是怎么解决的

**Comment by visiky** [comment]
需要等新版支持

**Comment by little-time** [comment]
> 

啥时候上呢

**Comment by lxfu1** [comment]
https://ant-design-charts-next.antgroup.com/zh/examples/statistics/dual-axes/#multi-line
