### ISSUE TITLE
Use different color for negative values in column graph

### ISSUE THREAD

**Issue by ShashwatMDas** [ant-design/ant-design-charts#764]
I have added a graph and want to fill the color of graphs with different colors, yellow when the value is positive and red when value is negative.

![image](https://user-images.githubusercontent.com/43996845/126608600-df2daa17-c218-4363-b265-9d60ac73d91c.png)

Is it possible to do so?

**Comment by lxfu1** [comment]
https://charts.ant.design/demos/column#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9F%B1%E7%8A%B6%E5%9B%BE%E9%A2%9C%E8%89%B2
