### ISSUE TITLE
🐛[BUG] Right to left legend overflows

### ISSUE THREAD

**Issue by Daisuke-sama** [ant-design/ant-design-charts#765]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

Hello Dear,
We are utilizing your lib for drawing plots, and we are from Israel. Our content direction is from right to left, but the legend and markers of a plot overflow. Can you make a fix, please?
The issue is probably living here https://g2plot.antv.vision/en/docs/api/components/legend and here https://github.com/antvis/G2/blob/master/src/util/legend.ts

### © 版本信息

- ant-design-charts 版本: "@ant-design/charts": "1.1.4"
- Chrome browser, Safari
- windows, macos

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image_2021_07_22T06_06_00_726Z](https://user-images.githubusercontent.com/16666335/126614740-5a3dde2e-c51f-4550-b2ee-e8ac6de684e8.png)

**Comment by lxfu1** [comment]
https://charts.ant.design/guide/case#custom-tooltip

**Comment by dramoturg** [comment]
we have problem with legend component. not tooltip
