### ISSUE TITLE
🧐How can I make pie chart to display contrast colors for the labels?

### ISSUE THREAD

**Issue by simplycodepix** [ant-design/ant-design-charts#767]
My config:
```
const options = {
    data: chartData,
    angleField: 'value',
    colorField: 'label',
    color: customColors || colors,
    radius: 1,
    innerRadius: 0.6,
    position: 'left',
    label: {
      type: 'inner',
      offset: '-50%',
      style: {
        textAlign: 'center',
        fontSize: 14,
      },
    },
    appendPadding: 0,
    padding: [0, 0, 0, -150],
    interactions: [{ type: 'element-selected' }, { type: 'element-active' }],
    statistic: {
      title: false,
    },
  };
```

The chart looks like this, right now:
![image](https://user-images.githubusercontent.com/16935043/126649808-0cc84284-4aef-41c7-962e-0c771f36500a.png)

I want the "billable" label to show the value in black color. How can I do that?

**Comment by visiky** [comment]
see: https://g2plot.antv.vision/en/examples/component/legend#legend-item-cfg

**Comment by simplycodepix** [comment]
Thanks, it's cool. But the question is about labels, not legends. For legends, there is some documentation that describes how we can customize those things. But for labels, it seems like we can't change values dynamically, please, see - https://g2plot.antv.vision/en/docs/api/components/label/#gatsby-focus-wrapper

I want this value to be in black 
![image](https://user-images.githubusercontent.com/16935043/126745287-3a2ea2b2-d36e-4806-8e05-a4354138479c.png)

**Comment by simplycodepix** [comment]
The config with solution looks like this:

```
const config = {
    label: {
      layout: [
        { type: 'adjust-color' },
      ],
    },
};
```

![image](https://user-images.githubusercontent.com/16935043/126975551-21ad4a2d-c30c-4d7b-ad03-7bd739b6aeba.png)
