### ISSUE TITLE
🧐 Is it possible to change position of the marker?

### ISSUE THREAD

**Issue by simplycodepix** [ant-design/ant-design-charts#772]
I want the marker to be at the right of legend, but I don't see information about such customization in the docs. Can I create custom legends? Is it even possible? 
Example of how legends should look:
![image](https://user-images.githubusercontent.com/16935043/126983504-a757ad8b-2ac3-4072-852b-50729c0d21e6.png)

**Comment by lxfu1** [comment]
Not currently, you can use custom Legend.

**Comment by lxfu1** [comment]
https://codesandbox.io/s/funny-kowalevski-z2kymb?file=/index.js
