### ISSUE TITLE
🐛[BUG]来源去向图的数据类型定义错误

### ISSUE THREAD

**Issue by WenDaaa** [ant-design/ant-design-charts#774]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
按照官网的数据格式 定义的数据组件提示类型异常

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/44088914/127129761-f1ead59a-dcaf-49e0-a8bb-374d53415be5.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
期望value类型是对象的时候不提示类型异常

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
data={{ nodes: [
          { id: '1',
            value: {
            title: '32',
              items: [{ text: '12', value: '22' }]
            }
          }
        ], edges: [] }}

### © 版本信息

- ant-design-charts 版本: [e.g. 1.2.2]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
V: 1.2.4
