### ISSUE TITLE
🐛[BUG] 双轴图的 scale 计算问题

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design-charts#779]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

柱形图可以完美计算比例

![image](https://user-images.githubusercontent.com/7971419/127289781-94a3e86d-efef-4a1f-ad0a-b4312c61d317.png)

但是双轴图，总会少计算一个

![image](https://user-images.githubusercontent.com/7971419/127289877-fe6c1394-f582-449e-90cf-960c5b56ebdd.png)

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

如图

### 🏞 期望结果 [描述你原本期望看到的结果]
双轴图可以计算出 1000

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
官网即可
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
```ts
  meta: {
    y: { nice: true },
  },
```

**Comment by crazyair** [comment]
这个不应该去最大值吗？不是自动的吗，还需要配置 nice？

**Comment by lxfu1** [comment]
> 这个不应该取最大值吗？不是自动的吗，还需要配置 nice？

不完全是最大值，有时最大值很难满足刻度的需求，nice之后会进行调整，[2.0 默认是 true]ttps://ant-design-charts-next.antgroup.com/examples)

**Comment by crazyair** [comment]
> > 这个不应该取最大值吗？不是自动的吗，还需要配置 nice？
> 
> 不完全是最大值，有时最大值很难满足刻度的需求，nice之后会进行调整，[2.0 默认是 true]ttps://ant-design-charts-next.antgroup.com/examples)

好的，2.0 默认是 true，那就没问题了
