### ISSUE TITLE
👑 [需求]能否有导出图片的功能

### ISSUE THREAD

**Issue by lgh-qt** [ant-design/ant-design-charts#78]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
我没有再api中看到有导出为图片的选项，是否可以加上这个🤔

**Comment by lxfu1** [comment]
![image](https://user-images.githubusercontent.com/31396322/84643536-8f8e9a80-af30-11ea-860c-9426f62a05bc.png)

目前没有内置，先自己实现一下。
  const ref = useRef();
  useEffect(() => {
    const time = setTimeout(() => {
      const base64 = ref.current?.canvas.cfg.el.toDataURL();
      let a = document.createElement('a');
      a.href = base64;
      a.download = 'test.png';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      a = null;
    }, 100);
    return () => {
      if (time) {
        clearTimeout(time);
      }
    };
  }, []);

  return <Line {...config} chartRef={ref} />;

**Comment by lxfu1** [comment]
v: 0.9.5,  https://charts.ant.design/guide/case
