### ISSUE TITLE
🧐[问题]FlowAnalysisGraph markerCfg中引用的data不会随着数据更新而更新

### ISSUE THREAD

**Issue by chenzio** [ant-design/ant-design-charts#780]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
FlowAnalysisGraph markerCfg中引用的data不会随着数据更新而更新
版本：
@ant-design/charts 1.2.2
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
    markerCfg: (cfg) => {
      const { edges } = data;
      return {
        position: 'right',
        show: edges.find((item) => item.source === cfg.id),
        collapsed: !edges.find((item) => item.source === cfg.id),
      };
    },

**Comment by lxfu1** [comment]
看图

![image](https://user-images.githubusercontent.com/31396322/127424239-51aeac64-7931-4783-9526-37cfc3fdfbb0.png)
