### ISSUE TITLE
🧐[问题] Area 面积图标如何隐藏描边线

### ISSUE THREAD

**Issue by cyanwin** [ant-design/ant-design-charts#781]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
描边线的配置stroke 设置为 null 并没有生效，修改任何色值也无效，如何正确的关闭面积图的边框线
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
<Area
    data={data}
    xField="time"
    yField="memberNumber"
    tooltip={{
        formatter: datum => ({
            name: '在线人数',
            value: [datum.memberNumber](url)
        })
    }}
    [height={40}](url)
    smooth
    xAxis={false}
    yAxis={false}
    areaStyle={{
        fill: 'rgba(133, 67, 224, 0.85)',
        fillOpacity: 1,
        stroke: null,
        strokeOpacity: .5
    }}
/>
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/45061152/127314694-55d967ee-0d09-4d89-9adf-01844e060bf6.png)

"@ant-design/charts": "^1.2.3"

**Comment by lxfu1** [comment]
```ts
line: {
  size: 0
}
```
