### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by hendrickhan** [ant-design/ant-design-charts#784]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
if i the measure data (65) is bigger than the target data(20), how to set the color of the measure data bar to red color? 
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
[
![Screenshot from 2021-07-30 14-14-31](https://user-images.githubusercontent.com/9595258/127653223-d4a36d63-7502-466d-974a-c1e4c3074bc9.png)
](url)

**Comment by lxfu1** [comment]
```ts
  color: {
    range: ['#FFbcb8', '#FFe0b0', '#bfeec8'],
    measure: ['#5B8FF9', '#61DDAA'],
    target: '#39a3f4',
  },
```

**Comment by hendrickhan** [comment]
is it possible to change color of the measure bar? 
I understand by referring the measure color, we will know where the measure value is located. It could be better that we can change the color of the bar.
