### ISSUE TITLE
Failed to parse source map from '../@antv/layout/src/util/object.ts' file

### ISSUE THREAD

**Issue by matrixcloud** [ant-design/ant-design-charts#786]
### 🐛 bug 描述

一直报下面的 Warning

`
WARNING in ./node_modules/@antv/layout/es/util/object.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from `../@antv/layout/src/util/object.ts'  file: Error: ENOENT: no such file or directory, open ''
`/node_modules/@antv/layout/src/util/object.ts'
`

### © 版本信息

- ant-design-charts 版本: 1.2.4
- 浏览器环境: Chrome
- 开发环境: Mac OS

**Comment by lxfu1** [comment]
换个安装方式试试。

**Comment by matrixcloud** [comment]
> 换个安装方式试试。

Hi, 感谢你的回复，方便明说下么，什么样的安装方式，我现在直接 `npm install` 的。

**Comment by hustcc** [comment]
@baizn  https://github.com/antvis/layout/blob/master/package.json#L9-L13 layout repo 在发布 npm 的时候，没有包含 src 源码。

**Comment by baizn** [comment]
> @baizn https://github.com/antvis/layout/blob/master/package.json#L9-L13 layout repo 在发布 npm 的时候，没有包含 src 源码。

是的，layout 发布时是没有包含 src 目录，什么场景下会引用到  /node_modules/@antv/layout/src/util/object.ts 下文件？ 引用es或lib下的不可以吗？

**Comment by brickmaker** [comment]
> ### 🐛 bug 描述
> 一直报下面的 Warning
> 
> `WARNING in ./node_modules/@antv/layout/es/util/object.js Module Warning (from ./node_modules/source-map-loader/dist/cjs.js): Failed to parse source map from`../@antv/layout/src/util/object.ts' file: Error: ENOENT: no such file or directory, open ''
> `/node_modules/@antv/layout/src/util/object.ts' `
> 
> ### © 版本信息
> * ant-design-charts 版本: 1.2.4
> * 浏览器环境: Chrome
> * 开发环境: Mac OS

这个如何复现呢？在什么场合下会报着个warning？

**Comment by matrixcloud** [comment]
> > ### 🐛 bug 描述
> > 一直报下面的 Warning
> > `WARNING in ./node_modules/@antv/layout/es/util/object.js Module Warning (from ./node_modules/source-map-loader/dist/cjs.js): Failed to parse source map from`../@antv/layout/src/util/object.ts' file: Error: ENOENT: no such file or directory, open ''
> > `/node_modules/@antv/layout/src/util/object.ts' `
> > ### © 版本信息
> > 
> > * ant-design-charts 版本: 1.2.4
> > * 浏览器环境: Chrome
> > * 开发环境: Mac OS
> 
> 这个如何复现呢？在什么场合下会报着个warning？

感谢你的回复，如果正常没有问题的话，那就行了~
我也很难描述，工程是 `react`+ `typescript`, 就 webpack 编译期间会报 warning

**Comment by hustcc** [comment]
@brickmaker 因为打包开启了 sourcemap，然后会去找底层依赖库的源码，但是安装的 layout 模块发布 npm 的时候，没有包含 src，所以找不到。

@matrixcloud 这个 warning 不会带来问题，只不过调试的时候，如果遇到底层 layout 的问题，没有源码调试而已。但是依然还是有打包后的源码的。不影响正常使用。

**Comment by matrixcloud** [comment]
> @brickmaker 因为打包开启了 sourcemap，然后会去找底层依赖库的源码，但是安装的 layout 模块发布 npm 的时候，没有包含 src，所以找不到。
> 
> @matrixcloud 这个 warning 不会带来问题，只不过调试的时候，如果遇到底层 layout 的问题，没有源码调试而已。但是依然还是有打包后的源码的。不影响正常使用。

嗯，确实不影响。

**Comment by wilsonyiyi** [comment]
> 换个安装方式试试。

换个方式怎么安装？我现在快600个warning，虽然不影响使用，但开发体验太差

**Comment by lxfu1** [comment]
> > > ### 🐛 bug 描述
> > > 一直报下面的 Warning
> > > `WARNING in ./node_modules/@antv/layout/es/util/object.js Module Warning (from ./node_modules/source-map-loader/dist/cjs.js): Failed to parse source map from`../@antv/layout/src/util/object.ts' file: Error: ENOENT: no such file or directory, open ''
> > > `/node_modules/@antv/layout/src/util/object.ts' `
> > > ### © 版本信息
> > > 
> > > * ant-design-charts 版本: 1.2.4
> > > * 浏览器环境: Chrome
> > > * 开发环境: Mac OS
> > 
> > 
> > 这个如何复现呢？在什么场合下会报着个warning？
> 
> 感谢你的回复，如果正常没有问题的话，那就行了~ 我也很难描述，工程是 `react`+ `typescript`, 就 webpack 编译期间会报 warning.
> 
> 只引用了其中的一个 chart
> 
> ```js
> import { Line } from '@ant-design/charts';
> ```

如果只使用了统计图表，建议直接使用 plots （charts 的子包）
```ts
  import { Line } from '@ant-design/plots';
```

**Comment by yangzai316** [comment]
我也遇到了，满屏的warning，好难受，问一下，有找到解决方法吗 ？

**Comment by hustcc** [comment]
> > @baizn https://github.com/antvis/layout/blob/master/package.json#L9-L13 layout repo 在发布 npm 的时候，没有包含 src 源码。
> 
> 是的，layout 发布时是没有包含 src 目录，什么场景下会引用到 /node_modules/@antv/layout/src/util/object.ts 下文件？ 引用es或lib下的不可以吗？

业务上打包的时候，一般在 dev 模式下， webpack 会开启 sourcemap，便于浏览器调试，所以会去寻找依赖包的源码生成 sourcemap，不会 error，但是会出现 warn，所以建议所有子包发布 npm 的时候都带上 src。

参考这个：https://github.com/antvis/util/blob/master/package.json#L9-L14

**Comment by matrixcloud** [comment]
> 我也遇到了，满屏的warning，好难受，问一下，有找到解决方法吗 ？

物理解决了，换了 https://bizcharts.taobao.com/products/bizCharts.

**Comment by xams-creator** [comment]
如果用的是 react-scripts 5.x ，可以把 GENERATE_SOURCEMAP=false 添加到 .env文件中
