### ISSUE TITLE
bundle size huge, including whole @antv in bundle

### ISSUE THREAD

**Issue by neevany** [ant-design/ant-design-charts#788]
bundle size same in both cases below, I am using the latest version of [umi](https://github.com/umijs/umi) to build.

`import Column from "@ant-design/charts/es/plots/column";`
`import { Column } from "@ant-design/charts";`

tried these https://charts.ant.design/guide/faq/

https://codesandbox.io/s/clever-gould-ls3fl?file=/App.tsx

**Comment by lxfu1** [comment]
At present, only plots and graphs are classified, and the bottom layer is still the full package, which will be optimized later.

**Comment by dimbslmh** [comment]
![image](https://user-images.githubusercontent.com/745635/131981899-d2d3ba4b-9695-44f3-926e-a61ba6937005.png)

**Comment by caoqiqi** [comment]
> At present, only plots and graphs are classified, and the bottom layer is still the full package, which will be optimized later.

how about the optimization?

**Comment by lxfu1** [comment]
[Try the V2 version](https://ant-design-charts-next.antgroup.com/examples)

**Comment by hugobarragon** [comment]
> [Try the V2 version](https://ant-design-charts-next.antgroup.com/examples)

Hello, v2 still not solved using vite, with tree shaking, is therer any configm anything to solve this bundle size problem?   
![image](https://github.com/user-attachments/assets/02c441d8-9741-4f8e-88dd-a608e45e68a9)
