### ISSUE TITLE
🧐[问题] 图表Config参数问题

### ISSUE THREAD

**Issue by Meruem117** [ant-design/ant-design-charts#789]
### 问题描述
您好，我在使用Ant Design Charts的过程中，遇到了一些问题，希望能得到解答
当我配置图表的config，遇到参数类型为指定的一些字符串时，比如 `position` 的值只能为 `'bottom'`, `'top'`等，就会有如下报错
#### 截图
![image](https://user-images.githubusercontent.com/51747309/128395927-691bbf14-daa8-4dcf-80d2-955813d2d372.png)
#### 代码
```jsx
var config = {
    data: data,
    xField: 'type',
    yField: 'value',
    seriesField: 'type',
    radius: 0.9,
    legend: { position: 'bottom' }
};
return <Rose {...config} />;
```
在我看来，报错原因是我定义的`position`被识别为`string`类型，而非图表规定的类型
我使用以下方式可以消去这个报错
```jsx
type pos = 'bottom'
const position: pos = 'bottom'
var config = {
    data: data,
    xField: 'type',
    yField: 'value',
    seriesField: 'type',
    radius: 0.9,
    legend: { position: position }
};
return <Rose {...config} />;
```
但官方文档的Demo中并不需要这样指定类型
我想知道如何能避免这种报错，是否是我的TS配置的问题
谢谢

**Comment by lxfu1** [comment]
'bottom' as 'bottom'
