### ISSUE TITLE
我想加个点击事件,

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-charts#79]
![image](https://user-images.githubusercontent.com/32530210/84720170-f30bdd00-afaf-11ea-971d-d7dc1d851563.png)
我想在生成的char上面加个点击事件,官网上没找到什么事件的DEMO,
也不知道住哪里加.

还请各位老师指点下

**Comment by lxfu1** [comment]
https://github.com/ant-design/ant-design-charts/issues/74

**Comment by xyzabc0004** [comment]
谢谢，谢谢！
