### ISSUE TITLE
🧐[问题]自定义legend图例名无效

### ISSUE THREAD

**Issue by hetianqun** [ant-design/ant-design-charts#791]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
使用组件为折线图line，因后端数据返回value是英文，想根据英文自定义对应的图例名，但是在config中设置legend后无效，想请问下正确的设定方法
### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
seriesField: 'type'    type传入的是英文

**Comment by hetianqun** [comment]
问题已解决，原来直接配置legend是无效的。

**Comment by Tomlili43** [comment]
怎么解决呢？ 上一下代码可以吗
