### ISSUE TITLE
饼图的legend如何自定义配置🧐[问题]

### ISSUE THREAD

**Issue by cyanwin** [ant-design/ant-design-charts#795]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
想要自定义展示legend的内容文本，但是没找到配置项在哪里修改。
并且colorField如果不是字符串 legend 会变成滑块
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
"@ant-design/charts": "^1.2.3"
![image](https://user-images.githubusercontent.com/45061152/128878371-c3ef1b35-f64b-4ac0-9fe5-c03edb6fe648.png)

**Comment by lxfu1** [comment]
有相关 issue ，你搜索一下。
