### ISSUE TITLE
🐛[BUG] 当使用柱状图xField和yField字段所指向的值都为数字时会发生堆叠

### ISSUE THREAD

**Issue by aFUZHOU** [ant-design/ant-design-charts#796]
### 🐛 bug 描述 
当使用柱状图x轴和y轴的值都为int类型的时候 第一个柱状图会随机与一个柱状图堆叠

### 📷 复现步骤 
```
const data =[
  {
      "num": 1,
      "day": 2
  },
  {
      "num": 2,
      "ay": 17
  },
  {
    "num": 7,
    "day": 18
  }
];

<Column padding="auto"  data={data}  xField="day" yField="num" />
```

### 🏞 期望结果
不发生堆叠

### 💻 复现代码 
[https://codesandbox.io/s/relaxed-knuth-5ij43](https://codesandbox.io/s/relaxed-knuth-5ij43)

### © 版本信息

- ant-design-charts 版本: [1.2.5]

### 🚑 
![image](https://user-images.githubusercontent.com/35911837/128962337-81595200-24ea-434d-a430-d366c26dbde7.png)

**Comment by lxfu1** [comment]
"day": "2",  string 类型
