### ISSUE TITLE
🐛[BUG] strange behaviour with Line

### ISSUE THREAD

**Issue by mpapenbr** [ant-design/ant-design-charts#797]
### 🐛 bug
I encountered some strange behaviour when plotting lines.

```
import "./styles.css";
import { Line } from "@ant-design/charts";

export default function App() {
  const config = {
    data: [
      { no: 1, myValue: 100 },
      { no: 2, myValue: 120 },
      { no: 3, myValue: 130 }
    ],
    xField: "no",
    yField: "myValue"
  };
  return <Line {...config} />;
}
```

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/41362745/129174676-9005a269-8118-4528-8e1a-fef9932ce258.png)

Other variant with values for "no" changed to 2,3,4:
![image](https://user-images.githubusercontent.com/41362745/129174862-4354e159-e256-4cbf-aac8-a723f8fab1fb.png)

ant-design-charts 1.2.5

codsandbox: https://codesandbox.io/s/ant-chart-line-broken-5vj0n?file=/src/App.js

Changing the values for "no" to 10,20,30 produces an entry for each column.

**Comment by AO19** [comment]
I have the same issue in version 1.2.7, also in Area Charts. In your example the hover tooltip is also wrong, it shows the current hover - 1.  If you hover on 3, it shows 2.

**Comment by Shamann** [comment]
It seems like you should use string type for x axis data. Please, consider answer to this [issue](https://github.com/ant-design/ant-design-charts/issues/796)

**Comment by lxfu1** [comment]
xField should be string type.
