### ISSUE TITLE
is it possible to set customized axis label in Gauge in antd chart ? 🧐[问题]

### ISSUE THREAD

**Issue by hendrickhan** [ant-design/ant-design-charts#798]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

is it possible to set the tick labels to be [0.125,0.25,0.375,0.5,0.625,0.75,0.875,1]?
instead of having it by default as [0.2, 0.4, 0.6, 0.8, 1]
![image](https://user-images.githubusercontent.com/9595258/129038735-0ecb46b2-d228-409a-a9c3-9c6717be293e.png)

**Comment by Shamann** [comment]
@hendrickhan , there are multiple ways to achieve what you want using [ticks options](https://charts.ant.design/guide/common#metaoptionticks). Here is an example showing two of possible solutions: tickInterval and arbitrary ticks array: <https://codesandbox.io/s/practical-thunder-shdq0?file=/App.tsx>

**Comment by hendrickhan** [comment]
> @hendrickhan , there are multiple ways to achieve what you want using [ticks options](https://charts.ant.design/guide/common#metaoptionticks). Here is an example showing two of possible solutions: tickInterval and arbitrary ticks array: https://codesandbox.io/s/practical-thunder-shdq0?file=/App.tsx

thanks a lot!
