### ISSUE TITLE
🧐[问题] 能不能把文档优化一下？

### ISSUE THREAD

**Issue by ChangJin0520** [ant-design/ant-design-charts#803]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
现在的文档查找不是很方便，影响使用。必须要搭配 G2 的文档才能看懂怎么配置。

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
比如这里：
![image](https://user-images.githubusercontent.com/17997339/129314751-3047f932-33cd-4632-9b97-be1fc80bc1d8.png)
annotations 中的有些属性是要和 type 对应的，文档中体现不出这一点，使用不是很方便

这个是 G2 的文档中截的
![image](https://user-images.githubusercontent.com/17997339/129314941-2464cdfb-f5bf-47a0-8b44-be0da1c0d428.png)

**Comment by qlibp** [comment]
十分同意，配置的层级完全看不懂，不知道是哪层套哪一层。哪怕是最基本的缩紧都能大大提高看文档的效率...

**Comment by lxfu1** [comment]
近期忙完会优化一波，同时也欢迎一起贡献。
- .umirc.ts 里面可以简答配置样式。
- 直接迁到 AntV  官网

**Comment by MonsterTan** [comment]
十分同意，我越看越乱。

**Comment by visiky** [comment]
收到~~ 后面几个月会优化 annotation 这一块，顺便重新看下文档

**Comment by XiaoqianLeeLee** [comment]
十分同意，我也是看得好吃力

**Comment by monologue-web** [comment]
十分赞同, 层级非常的不清晰, 看的迷糊

**Comment by lxfu1** [comment]
看下最新官网

**Comment by jx-zyf** [comment]
> 看下最新官网

flowchart 的文档有空更新一波么？目前的稍微有点简介，很多配置只能参考类型定义文件
