### ISSUE TITLE
🐛[BUG] Can't get actual component state from plot on event callback

### ISSUE THREAD

**Issue by JustPieceOfMeat** [ant-design/ant-design-charts#806]
### 🐛 Describe the bug

Can't get actual component state from plot on event callback

### 💻 Reproducible code

https://codesandbox.io/s/epic-fermat-sfgm8?file=/src/App.js

### © Version information

- ant-design-charts 1.2.7
- Browser environment: Microsoft Edge (chromium) v. 92.0.902.73
- Development environment: Windows 10

### 🚑 Add other information [Such as screenshots and other information can be posted here]

I wrote about the expected result in code comments, see Reproducible code

**Comment by lxfu1** [comment]
```ts
  const countRef = useRef();
  countRef.current = counter;
```

**Comment by Shamann** [comment]
@JustPieceOfMeat , what you're doing is actually using a closure with the counter value (which is also a component's state) as an event handler for the plot, so it becomes unaware of subsequent state updates triggered by the button clicks. To actualize the event handler you should make use of useEffect hook (pay attention to the return value or you'll spam the chart with handlers!): <https://codesandbox.io/s/delicate-feather-107c1?file=/src/App.js>
