### ISSUE TITLE
🧐[问题]基础柱状图-缩略图能否获得slider的取值

### ISSUE THREAD

**Issue by Hsirius** [ant-design/ant-design-charts#81]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

基础柱状图-缩略图能否获得slider的取值呢？

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

给当前的chart加了ref，但是也没有找到相应的slider值，请大佬指教

**Comment by lxfu1** [comment]
暂时没有，后续会加上。

**Comment by lxfu1** [comment]
更新到 1.0 版本，参考： https://charts.ant.design/guide/case#%E4%BA%8B%E4%BB%B6%E7%BB%91%E5%AE%9A 
```ts
 ref.current.on('slider:valuechanged', (view)=>{
       console.log(view?.event)
    })
```
