### ISSUE TITLE
🐛[BUG] Tooltip disappearing on data updates

### ISSUE THREAD

**Issue by tothandras** [ant-design/ant-design-charts#815]
#### bug description

https://codesandbox.io/s/friendly-jang-oxrwn?file=/App.tsx

1. hover over the chart, leave your cursor there
2. wait for a data update
3. [bug] tooltip usually disappears or the marker appears at an incorrect position

*ant-design-charts: `1.2.9`*

#### note

In the G2 docs, the tooltip behaves as expected: https://g2plot.antv.vision/en/docs/api/plot-api/#4-changedata

**Comment by ZLester** [comment]
@tothandras Did you ever find a fix for this?

**Comment by ZLester** [comment]
@lxfu1 This appears to still be an issue in 1.3.6 for the `DualAxes` chart as well

**Comment by tothandras** [comment]
@ZLester Unfortunately, no. It wasn't a priority for us, just annoying from a user perspective.

**Comment by lxfu1** [comment]
The link you provided is normal, https://codesandbox.io/s/friendly-jang-oxrwn?file=/App.tsx
