### ISSUE TITLE
🐛[BUG] iOS15 Safari 图形无法显示

### ISSUE THREAD

**Issue by shyray** [ant-design/ant-design-charts#817]
### 🐛 bug 描述 
iOS 15 Safari 图形无法显示

### © 版本信息
iOS 15 PB 6

- ant-design-charts 版本: [e.g. 1.2.9]
- 浏览器环境 Safari
- 开发环境 [e.g. mac OS]

**Comment by bmw335** [comment]
图表data里中文导致，不可思议。
官方的Bar demo可复现此bug看，bar名称为中文。 https://charts.ant.design/demos/bar
官方的Radar demo正常，bar名称为英文。https://charts.ant.design/demos/radar
