### ISSUE TITLE
无法监听到annotation-region:click点击事件

### ISSUE THREAD

**Issue by AlisaBen** [ant-design/ant-design-charts#818]
使用官方demo稍作修改:https://codesandbox.io/s/crptb?file=/App.tsx
增加了annotation的事件监听，却无法监听到点击事件
  ```
onReady={(chart) => {
        chart.on("annotation-region:click", (evt) => {
          console.log(evt);
        });
      }}
```

**Comment by lxfu1** [comment]
不确定你要做什么，文档上没有这类事件哈  https://g2plot.antv.antgroup.com/api/options/events
