### ISSUE TITLE
🐛[BUG] 对封装了一层的图表组件，不能传递ref参数

### ISSUE THREAD

**Issue by iambool** [ant-design/ant-design-charts#824]
### 🐛 bug 描述
工程中有一些图表的配置是一致的，所以特别在原始图表组件基础上做了独有配置的图表组件（其实就是在原始图表组件上包了一层）
但是发现传递ref对象的时候会报错：Cannot read property 'appendChild' of undefined
（使用ref主要是用于图片下载等操作）

特别需要提醒的是：1.2.8版本是没有这个问题的

### 📷 复现步骤
（1）对Line组件包装一层；
（2）在其他组件中引入包装好的Line组件；
（3）传入ref对象至charRef；

### 🏞 期望结果 [描述你原本期望看到的结果]
期望能正常传入ref对象

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/optimistic-carson-3rozt?file=/App.tsx

### © 版本信息
    "@ant-design/charts": "^1.0.8",
    "react": ">=16.8.4",
    "react-dom": ">=16.8.4"

**Comment by lxfu1** [comment]
先这样用一下 chartRef={(plot) => (chartRef.current = plot)} ， 后续我们兼容一下。

**Comment by lxfu1** [comment]
传递 ref 需要使用 forwardRef
