### ISSUE TITLE
🐛[BUG] 指标拆解图节点过大时出现遮挡

### ISSUE THREAD

**Issue by lxfu1** [ant-design/ant-design-charts#825]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/31396322/130454335-9e45bbc2-671b-43a3-82b1-cf52f17496ae.png)

**Comment by oumingliang** [comment]
![image](https://user-images.githubusercontent.com/23456323/180118104-4dd37a21-7328-426e-9b64-47b743895d8e.png)
1: 节点过大 会遮挡
2： 能否自定义每个节点之间的 间距？

**Comment by lxfu1** [comment]
调整一下layout 配置
