### ISSUE TITLE
FlowAnalysisGraph 点击节点拉取数据节点无法高亮

### ISSUE THREAD

**Issue by yzg1025** [ant-design/ant-design-charts#828]
onReady: (graph: IGraph) => {
          graph.on('node:click', (e) => {
            const clickNodes = graph.findAllByState('node', 'click');
              console.log('clickNodes', clickNodes, graph)
              clickNodes.forEach((cn) => {
                graph.setItemState(cn, 'click', false);
              });
              const nodeItem = e.item as Item;
              console.log('nodeItem', nodeItem)
              graph.setItemState(nodeItem, 'click', true);

              // @ts-ignore
              // eslint-disable-next-line no-underscore-dangle
              const params = nodeItem._cfg?.model.value.node === undefined ? nodeItem._cfg?.model.id : nodeItem._cfg?.model.value.node
              getGraphParams(params)
          });
}

部分代码

分析原因
getGraphParams 是一个函数 参数是用了state接收
如果注释getGraphParams 一切正常
当点击节点时 graph.findAllByState('node', 'click') 返回值一直是空数组
则 graph.setItemState(nodeItem, 'click', true); 设置无效
原因 每点击一次node节点 整个画布都要重新执行

**Comment by lxfu1** [comment]
```tsx
const fetchData = () => {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve({
            nodes: [
              {
                id: Math.random().toString(),
                value: {
                  title: '来源页面99',
                  items: [
                    {
                      text: '曝光PV',
                      value: '10.30万',
                      icon: 'https://gw.alipayobjects.com/zos/antfincdn/iFh9X011qd/7797962c-04b6-4d67-9143-e9d05f9778bf.png',
                    },
                  ],
                },
              },
              {
                id: Math.random().toString(),
                value: {
                  title: '来源页面999',
                  items: [
                    {
                      text: '曝光PV',
                      value: '10.30万',
                      icon: 'https://gw.alipayobjects.com/zos/antfincdn/iFh9X011qd/7797962c-04b6-4d67-9143-e9d05f9778bf.png',
                    },
                  ],
                },
              },
            ],
            edges: [],
          });
        }, 1000);
      });
    };
    const asyncData = async () => {
      return await fetchData();
    };

    const chartProps = {
      data: FlowData,
      fitCenter: false,
      nodeCfg: {
        asyncData,
      },
      markerCfg: (cfg) => {
        return {
          position: 'right',
          show: true,
        };
      },
      behaviors: ['drag-canvas', 'zoom-canvas', 'drag-node'],
    };
(<FlowAnalysisGraph {...props} />
```
