### ISSUE TITLE
🧐 Is it possible to add a legends for Sunburst Chart?

### ISSUE THREAD

**Issue by simplycodepix** [ant-design/ant-design-charts#829]
Hey. I need to render legends on the side for Sunburst chart like on the screenshot below. Is it possible or not?
If it's not possible by default, can you send me an example of how can I create a custom implementation?
![image](https://user-images.githubusercontent.com/16935043/130772893-87858f0e-a47e-4f9d-9da9-ac9d59c15015.png)

**Comment by Shamann** [comment]
@simplycodepix, no, the legend for the Sunburst component is deliberately omitted internally.
A total value can be placed in the center via the annotation (provided that you've calculated it elsewhere):
<https://codesandbox.io/s/hungry-cherry-4hz8m?file=/App.tsx>

**Comment by simplycodepix** [comment]
Okay, thanks a lot for example.
