### ISSUE TITLE
ERROR in vendor-xx.min.js from UglifyJs in Production 

### ISSUE THREAD

**Issue by ramavilli** [ant-design/ant-design-charts#83]
ERROR in vendor-xx.min.js from UglifyJs
Unexpected token: operator (>) [./node_modules/import-glob!./node_modules/d3-regression/src/utils/points.js:5,0][vendor-xx.min.js:106179,24]

**Comment by lxfu1** [comment]
It's seem to compile error. https://github.com/JeffreyWay/laravel-mix/issues/790
