### ISSUE TITLE
🧐Need some help with TinyArea config

### ISSUE THREAD

**Issue by Sirri69** [ant-design/ant-design-charts#834]
### 🧐 How do I control `stroke color`, `stroke width` and `opacity` of a TinyArea graph ?

I have already tried config values given on [this](https://charts.ant.design/guide/graphic-style) page.

Thanks for the help.....

**Comment by Shamann** [comment]
@Sirri69, you may do it via the areaStyle and line configuration properties:
<https://codesandbox.io/s/jz21i?file=/App.tsx>
Please, consider the Plot Style section for the list of style attributes:
<https://g2plot.antv.vision/en/examples/tiny/tiny-area#filled-area>

**Comment by lxfu1** [comment]
```ts
    line: {
      color: "red",
      size: 2,
    },
```
