### ISSUE TITLE
🐛[BUG]  there is a bug when you want to use a chart that called Flow Analysis Graph 

### ISSUE THREAD

**Issue by rezaesmaeili** [ant-design/ant-design-charts#835]
hi I think there is a bug when you want to use a chart that called Flow Analysis Graph from this link:
https://charts.ant.design/demos/flow-analysis-graph
when you create component exactly same example the type of  props is not acceptable and throw error when I changed the the file from this path :
node_modules\@ant-design\charts\es\graphs\flowAnalysisGraph\index.d.ts
this part:

export declare type FlowAnalysisNodeData = NodeData<{
    title?: string;
    items?: CardItems;
}[]>;

to:
export declare type FlowAnalysisNodeData = NodeData<{
    title?: string;
    items?: CardItems[];
}>;
the data type get acceptable and chart appeared and the problem gets solved.
but the problem is we don't put node_modules in our source control !!

**Comment by lxfu1** [comment]
Use the latest version.
