### ISSUE TITLE
The Slider is removing the Region Annotation if the edges of the region is not in the interval of the Slider

### ISSUE THREAD

**Issue by yusuf-yilmaz-scopely** [ant-design/ant-design-charts#838]
Hello, when i use Area charts with region annotations, and when i add slider to this charts( or brush interaction), it is not working as i expected. Here i have added a slider to the official examples of ant design charts. https://codesandbox.io/s/distracted-mirzakhani-98185?file=/App.tsx
If you zoom with slider to the point 8, region is vanishing. Because, start and end point of the region is 7 and 9 but I want to be able to see half of the region even if i'm at point 8. I have checked document but i couldn't find any solution, is there any solution for this ?

**Comment by yusuf-yilmaz-scopely** [comment]
<img width="1691" alt="Screenshot 2021-08-31 at 11 38 54" src="https://user-images.githubusercontent.com/72988091/131480129-8026ccf4-5c4f-43cf-8373-4b8218b82af2.png">
<img width="1691" alt="Screenshot 2021-08-31 at 11 39 56" src="https://user-images.githubusercontent.com/72988091/131480223-aa28d11d-1fb3-4ac2-a716-b4f9fd223b87.png">

**Comment by lxfu1** [comment]
Design it this way so that it can listen to the changes of the slider and configure a new region.
