### ISSUE TITLE
🧐[问题] 数据data更新的时候会rerender整个图表现为“闪烁”，是否可以只刷新增量数据

### ISSUE THREAD

**Issue by EGBAR** [ant-design/ant-design-charts#84]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
在使用Chart的过程中有数据更新的需求， 把数据放在component的state或者是从外部props传入更新， 每次更新所有的值都在rerender。 包括slider插件也会reset。 但是自己封装G2 和 G2Plot 用instence.changeData() 的时候就没有这种问题。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```javascript
import React, { Component } from 'react';
import {Button} from 'antd';
import { Line } from '@ant-design/charts';
class Page extends Component {
    constructor(props){
        super(props);
        this.state={
            year:1999,
            value: 15, 
            data: [],
        }
    }
  render() {
    const config = {
      data:this.state.data,
      title: {
        visible: true,
        text: '折线图',
      },
      xField: 'year',
      yField: 'value',
      theme: 'dark'
    };
    return (<div>
        <Line {...config} />
        <Button onClick={()=>{
            let year = this.state.year;
            let value = this.state.value;
            let data = this.state.data;
            year +=1;
            value +=1;
            data.push({year: year, value:value});
            this.setState({
                year: year,
                value: value,
                data: data
            })
        }}>
            ADD POINT
        </Button>
        </div>);
  }
}
export default Page;
```

请教一下为什么会有这样的问题， 以及如何避免， 谢谢！

**Comment by lxfu1** [comment]
容器先给个高度解决下闪烁的问题， 后续我们做个优化处理，针对 changeData 做特殊处理。

**Comment by EGBAR** [comment]
@lxfu1  与高度无关， “闪烁” 主要表现为data变了里面的数据内容就会重新rerender一遍， 图标会有一个消失再出现的过程， 然后interaction里面slider的状态也会被重置。 对于需要动态更新的使用场景不友好。
我觉得data数据的change直接bind到G2Plog instence的changeData()里面， 如果需要rerender的话， 可以通过ref来手动实现。

**Comment by lxfu1** [comment]
npm update,    <Line {...config} onlyChangeData={true} />

**Comment by EGBAR** [comment]
@lxfu1  这个change可以满足现有的需求了， 十分感谢， 更新也太快了， 点赞！

**Comment by juzhiyuan** [comment]
> onlyChangeData

请问 Area 支持吗？

**Comment by Dawnwangzi** [comment]
我也遇到这个问题，但是onlyChangeData这个看源码没有暴露出来，有啥别的解决方案吗

**Comment by lxfu1** [comment]
参考下这个，https://codesandbox.io/s/pedantic-lucy-tylzl?file=/App.tsx

**Comment by huadee1108** [comment]
这样也太麻烦啦，每个图形组件都要包一层memo

**Comment by miaoweiwei** [comment]
> npm update, <Line {...config} onlyChangeData={true} />

这个不顶用啊

**Comment by miaoweiwei** [comment]
> npm update, <Line {...config} onlyChangeData={true} />
这样不行啊
![image](https://user-images.githubusercontent.com/20410007/198526977-a23776ae-60e6-495f-aeb2-3213a76676ad.png)
