### ISSUE TITLE
👑 [需求] 在使用基础水平方向对称条形图中，在数据量大的时候需要滚动条的配置

### ISSUE THREAD

**Issue by thelaurelyy** [ant-design/ant-design-charts#843]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]

在业务中使用基础水平方向对称条形图，由于类别比较多，因此在固定高度范围内，左侧X轴展示的效果是间隔元素展示。
![image](https://user-images.githubusercontent.com/27723220/131629473-41523b6d-9206-42d5-a241-81b3564937e0.png)

请问是否能够支持滚动条，滑动展示所有元素呢？ 期待您的回复......

**Comment by lxfu1** [comment]
对称条形图目前不支持 scrollbar ， 后续看下。

**Comment by lxfu1** [comment]
V2 
```ts
scrollbar: {
  x: {},
  y: {]
}
```
