### ISSUE TITLE
How to fill background in bar chart in region filter annotation ?

### ISSUE THREAD

**Issue by imaaditya-stack** [ant-design/ant-design-charts#847]
Hi,

I want to fill background in bar chart in region filter annotation like below. How to do it ? 

![Selection_047](https://user-images.githubusercontent.com/59827782/131679019-ae767a44-194a-4d0f-901b-ee9ff219fb61.png)

Below is the sandbox link

https://codesandbox.io/s/affectionate-noether-utfx2?file=/App.tsx

**Comment by lxfu1** [comment]
```ts
annotations: [
  {
    type: 'region',
    start: ['min', 40],
    end: ['max', 60],
    style: {
      fill: '#f20',
      fillOpacity: 0.3
    }
  },
]
```
