### ISSUE TITLE
How to show custom icons for scatter plot data points?

### ISSUE THREAD

**Issue by imaaditya-stack** [ant-design/ant-design-charts#848]
Below is an example of my scatter plot
![Selection_054](https://user-images.githubusercontent.com/59827782/131786341-862b72a0-2f28-47a7-bc82-9b08b9871e3b.png)

I want to show custom icons for each data point based on a data point in my data like below

![Selection_055](https://user-images.githubusercontent.com/59827782/131786488-4e6e95bb-5301-4ab2-8511-c76817018c63.png)

My chart config

```
  var config = {
    data: data,
    xField: "date",
    yField: "score",
    xAxis: {
      tickCount: 4,
      label: {
        formatter: function formatter(v: any) {
          return moment(v, "YYYY-MM-DD hh:mm A").format("hh:mm A");
        },
        style: {
          fill: "#6E759F",
        },
      },
    },
    yAxis: {
      label: {
        style: {
          fill: "#9AA5B5",
        },
      },
    },
    meta: {
      score: {
        min: 0,
        max: 100,
        tickInterval: 25,
      },
    },
  };
```

My data structure

```
  {
    "id": ,
    "date": "2021/05/20 12:03:00 PM",
    "Application": "",
    "Activity": "",
    "score": 50
  }
```
 
The icon should be based on Activity in the data structure above.
For eg -> If Activity is Login then login icon will show for the data point.

**Comment by lxfu1** [comment]
https://charts.ant.design/guide/case#custom-shape

**Comment by imaaditya-stack** [comment]
@lxfu1 I don't want custom shape, I want to show a custom Ant Design Icon as the data point

**Comment by imaaditya-stack** [comment]
> https://charts.ant.design/guide/case#custom-shape

@lxfu1 I don't want custom shape, I want to show a custom Ant Design Icon as the data point

**Comment by lxfu1** [comment]
Not supported, such as the Icon method.
