### ISSUE TITLE
How to show ant design icon inside an annotation of type html?

### ISSUE THREAD

**Issue by imaaditya-stack** [ant-design/ant-design-charts#850]
My annotation config

```
      {
        type: "html",
        position: { date: "2021/05/21 11:45:00 AM", score: "max" },
        html: (a: any, b: any) => {
          return `<svg width="24" height="24">
                    <circle cx="12" cy="12" r="11" fill='${"#ff1a1a"}' />
                    <text x="50%" y="50%" text-anchor="middle" fill="white" font-size="12px" font-family="Arial" dy=".3em">
                    '${(<InfoOutlined />)}'</text>
                    Sorry, your browser does not support inline SVG.
                </svg>`;
        },
        offsetX: -12,
        offsetY: -5,
      },
```

I want to show icon inside an annotation like this
![Selection_059](https://user-images.githubusercontent.com/59827782/131953734-df8656bf-1c1c-4cef-97af-917bdb49ed82.png)

But my above annotation implementation is not working, it shows like this

![Selection_060](https://user-images.githubusercontent.com/59827782/131953805-da8d8d52-8fe4-498b-83a6-9a7eefe75826.png)

How do I achieve this ?

**Comment by lxfu1** [comment]
https://www.yuque.com/antv/g2plot/kdkyoc#MryMU
