### ISSUE TITLE
Issue with stacked grouped column chart border radius and custom tooltip ?

### ISSUE THREAD

**Issue by imaaditya-stack** [ant-design/ant-design-charts#851]
I want to add rounded border to the stacked grouped column chart, but it's giving border to each chart in the stack. How to resolve it ?

Here's my codesandbox:

https://codesandbox.io/s/priceless-wilson-rum8h?file=/App.tsx

**Comment by lxfu1** [comment]
```ts
 columnStyle: (arg) => {
    if (arg.subtype !== "Analytic-Active") {
      return {};
    }
    return {
      radius: [6, 6, 0, 0]
    };
  },
```
