### ISSUE TITLE
🐛[BUG] Safari 15 无法加载图表，造成整个页面无法加载

### ISSUE THREAD

**Issue by zy-dys** [ant-design/ant-design-charts#855]
### 🐛 bug 描述 
升级safari后图表无法加载，造成整个页面也加载不了

### 📷 复现步骤 
1. 使用Safari Technology Preview Release 131  或 Monterey版本系统中的Safari更新到最新版

### © 版本信息
- ant-design-charts 版本: ^0.9.4
- 浏览器环境 Safari Technology Preview Release 131 (Safari 15.0, WebKit 16612.2.2)
- 开发环境 macOS 11.5.2

### 🚑 其他信息 
<img width="931" alt="image" src="https://user-images.githubusercontent.com/34826507/132196690-609cc0b3-8d14-40b4-bac3-1b67e3d260ef.png">

<img width="739" alt="image" src="https://user-images.githubusercontent.com/34826507/132196616-99fccb56-75cb-4ea8-aa5f-f4616d387159.png">

**Comment by bmw335** [comment]
图表data里中文导致，不可思议。
官方的Bar demo可复现此bug看，bar名称为中文。 https://charts.ant.design/demos/bar
官方的Radar demo正常，bar名称为英文。https://charts.ant.design/demos/radar

**Comment by bmw335** [comment]
有人在苹果社区发帖，得到这个回答：
"关闭safari的GPU Processing: Canvas Rendering"
实测关闭后就能显示图表，但不解决问题。

https://developer.apple.com/forums/thread/685866

![image](https://user-images.githubusercontent.com/6522231/133412922-24dae052-b3c7-42e6-ba32-c47bbc01a1e8.png)

**Comment by lxfu1** [comment]
删除 lock，更新一下依赖。保证底层 G2 版本是 4.1.28 及更新。参考 issue [antvis/G2#3635](https://github.com/antvis/G2/issues/3635)
