### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by razk87** [ant-design/ant-design-charts#856]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

Im trying to set the Area chart to not have margin/padding on the sides so my chart will perfectly fit inside the wrapping container, the canvas is taking the whole div but on the screen the chart has it's margin on the sides  - for some reason i couldn't find the attribute for that on the documentation. 

Also i would like the Chart to start from 0 on the Y axis i tried the "beginAtZero" attribute but also didnt worked

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

these are my configurations:

const config = {
    height: 60,
    data: volumeData,
    autoFit: true,
    xField: "date",
    yField: "count",
    padding: [5],
    xAxis: false,
    yAxis: false,
    color: "#916afc",
    legend: false,
    point: {
      shape: 'circle'
    },
  };

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

https://stackoverflow.com/questions/69072615/ant-design-area-chart-remove-canvas-margins
![image](https://user-images.githubusercontent.com/83636963/132210217-347f7968-0f2b-4d8c-9cde-497c59e184ea.png)

**Comment by hustcc** [comment]
You should set the scale.min of y field to 0.

```ts
{ 
  /* ... */
  meta: {
    count: { min: 0 }
  }
}
```

Then the y axis will start wiht zero. Also reply on [stackoverflow](https://stackoverflow.com/questions/69072615/ant-design-area-chart-remove-canvas-margins/69074278#69074278).
