### ISSUE TITLE
How to customise axis labels order ?

### ISSUE THREAD

**Issue by imaaditya-stack** [ant-design/ant-design-charts#857]
I want to achieve the order of x-axis like below

![Selection_080](https://user-images.githubusercontent.com/59827782/132283348-f5f21873-fb39-4a25-904f-585355eeb743.png)

Currently My chart looks like this

![Selection_081](https://user-images.githubusercontent.com/59827782/132283389-661cea06-2696-44ba-928f-1aa4abec56f5.png)

I want 1 to be in center then go towards right and continue from extreme left

This is my chart config

```
  var config: any = {
    data: modifyData(data),
    xField: "date",
    yField: ["count", "value"],
    legend: false,
    xAxis: {
      label: {
        style: {
          fill: "#6E759F",
        },
      },
    },
    yAxis: {
      count: {
        label: {
          style: {
            fill: "#6E759F",
          },
        },
      },
      value: {
        label: {
          style: {
            fill: "#03838B",
          },
        },
      },
    },
    geometryOptions: [
      {
        geometry: "line",
        color: ["#2F54EB", "#9254DE"],
        seriesField: "type",
      },
      {
        geometry: "line",
        color: "#2AABAB",
        seriesField: "type",
      },
    ],
  };
```

**Comment by vaibhav-systango** [comment]
@imaaditya-stack any updates on this ?

**Comment by deketh** [comment]
> @imaaditya-stack any updates on this ?

just order the elements in the data array
