### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by 245570565** [ant-design/ant-design-charts#858]
### © 版本信息 1.2.10

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="990" alt="EA85DB15-A857-4393-887A-8F418785BA50" src="https://user-images.githubusercontent.com/31842755/132304119-68db8a9a-6ff4-4bf6-b27e-668dfccc5d6f.png">
<img width="1277" alt="ED48CC3F-A28C-438D-BAE7-3F45087C79FA" src="https://user-images.githubusercontent.com/31842755/132304132-3c704dc3-7abd-4a27-95a5-5610e0174f66.png">

**Comment by lxfu1** [comment]
```ts
onReady: (graph) => {
  setTimeout(()=>{
    graph.zoom(0.5)
  }, 200)
}
```
