### ISSUE TITLE
🧐[问题]xField,yField能否支持object嵌套

### ISSUE THREAD

**Issue by kilik52** [ant-design/ant-design-charts#860]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

如果我的data是这样的：
````json
[{
    "product": {
        "name": "prod01"
    },
    "value": 1000
}]
````

我希望xField是product里面的name属性。我试了一下，并不能实现。

希望可以是 xField: ['product', 'name']。 antd的table也有类似的用法。
不知道xField能否支持这样的需求？

**Comment by lxfu1** [comment]
目前不支持
