### ISSUE TITLE
🐛[BUG]  Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.

### ISSUE THREAD

**Issue by joon08** [ant-design/ant-design-charts#861]
"@ant-design/charts": "^1.2.11",
  "typescript": "^3.8.3",

运行的时候报 Cannot find type definition file for '_gl-matrix@3.3.0@gl-matrix'.

![image](https://user-images.githubusercontent.com/50821370/132480249-f64a7ecf-9349-46ab-ae88-034e79b07c25.png)

![image](https://user-images.githubusercontent.com/50821370/132479222-40c5240c-e984-4965-a6be-e5ea7fe1d879.png)

网上找到一种解决办法，tsconfig.json里添加配置项
"skipLibCheck":true,

但是忽略类型检查 不确定后面会不会产生什么不好的影响
所以希望作者可以从根本上解决这个问题

**Comment by lxfu1** [comment]
这个问题很久之前已经解决，重新安装下依赖即可
