### ISSUE TITLE
Invert Y axis at 'Line' chart and others

### ISSUE THREAD

**Issue by v-kh** [ant-design/ant-design-charts#862]
Hello! Is there any way to invert Y axis at 'Line' chart? To show bigger values (at chart) lower than smaller values. For example, to show depth. Chart line should go down with growth of values instead of standart behavior, when growth of values makes chart go up. Didn't find this option for antd chart anywhere.

**Comment by lxfu1** [comment]
https://codesandbox.io/s/inspiring-field-7c2ff?file=/App.tsx

**Comment by MachinePoetry** [comment]
> https://codesandbox.io/s/inspiring-field-7c2ff?file=/App.tsx

Yes, it works but it's not a solution. Not good for production code. Other charts allow you just to add one row to chart config and here it is.

**Comment by WesleyMiller1998** [comment]
I'd appreciate this feature as well. In regards tot he work around, having to alter data to fit the chart API seems horribly hacky.
