### ISSUE TITLE
请问缩略图的详细配置有么，可以定制缩略图么，当前问题如下🧐[问题]

### ISSUE THREAD

**Issue by RichieChoo** [ant-design/ant-design-charts#863]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
![image](https://user-images.githubusercontent.com/17178139/132616471-f5c94654-6d59-442d-8cc0-d78bd1721833.png)

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
可以看到当缩略图到右侧时，起始位置的标识重叠了

**Comment by lxfu1** [comment]
https://charts.ant.design/zh-CN/demos/column?type=api  #slider

**Comment by RichieChoo** [comment]
但是滑动到右侧，最大最小的文字 还是重叠，

**Comment by lxfu1** [comment]
可以选择关闭文本哈
