### ISSUE TITLE
Type '{ ... }' is not assignable to type 'ColumnConfig'.🐛[BUG]

### ISSUE THREAD

**Issue by RichieChoo** [ant-design/ant-design-charts#864]
如图所示，导致编译出错

Type '{ data: never[]; isStack: boolean; xField: string; yField: string; seriesField: string; minColumnWidth: number; maxColumnWidth: number; padding: number[]; height: number; autoFit: boolean; legend: { position: string; }; meta: { ...; }; }' is not assignable to type 'ColumnConfig'.🐛[BUG]

![image](https://user-images.githubusercontent.com/17178139/132835057-ee16fe74-0e35-449d-92a2-f20eab052575.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/silly-voice-64hiq?file=/App.tsx
### © 版本信息

- ant-design-charts 版本: 1.2.11
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
```ts
legend: {
  position: "top-left" as "top-left"
},
```
