### ISSUE TITLE
🧐[问题] 圆角堆叠柱状图的实现

### ISSUE THREAD

**Issue by lvvlan** [ant-design/ant-design-charts#866]
### 🧐 问题描述

我想实现一个圆角堆叠柱状图，类似官网给的[分组圆角柱状图的例子](https://codesandbox.io/s/6bo9e?file=/App.tsx)，但实现起来好像有点儿问题，如下图所示
![image](https://user-images.githubusercontent.com/10861084/133057210-b713371a-4a33-4147-971c-1b1a712eb643.png)

想实现一个顶角圆角，且柱子宽度不固定，圆角根据柱子宽度自适应的圆角堆叠柱状图，这个该怎么做呢？

**Comment by lxfu1** [comment]
```ts
columnStyle:  (arg) => {
   // if xx return xxx
   return {
      radius: [20, 20, 0, 0],
    },
}
```

**Comment by lvvlan** [comment]
感谢回复。但是这样实现的圆角不是类似半圆的那样的圆角，想实现一个顶角类似半圆的圆角并且根据柱子宽度自适应的这种圆角。感觉是不是要使用自定义图形了？

**Comment by borie88** [comment]
而且如果顶部数据的值很小就没办法看到圆角。这个实现方式理想
