### ISSUE TITLE
想给Bar图添加 一个loading

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-charts#87]
各位老师，我想给<Bar {...config} />;加一个loading，就是在点击查询按钮后，
bar有个loading的效果，

还请各位老师指点下。谢谢！

**Comment by lxfu1** [comment]
if(loading){
    return <div>loading</div>
  }

  return <Line {...config} />

**Comment by xyzabc0004** [comment]
啊......

**Comment by xyzabc0004** [comment]
我还以为在Bar上加loading属性呢，谢谢

**Comment by lxfu1** [comment]
> 我还以为在Bar上加loading属性呢，谢谢，谢谢

想法不错，我考虑哈。

**Comment by lxfu1** [comment]
业务层加一下吧

**Comment by afc163** [comment]
loading 最好有统一的设计。
