### ISSUE TITLE
Supports for Wind Rose

### ISSUE THREAD

**Issue by yanckst** [ant-design/ant-design-charts#870]
Hi,

I want to know if it's possible to have a WindRose. A lot of libraries support a built-in WindRose chart and I didn't find any charts close to that. The only "close" charts would be the [Rose](https://charts.ant.design/demos/rose/) and [Radar](https://charts.ant.design/demos/radar/).

Here's a picture of a Wind Rose.
![image](https://user-images.githubusercontent.com/30554401/133309245-9a13fc52-1a18-4091-b3d3-0f5337c494f3.png)

Any input on how we can create this? Is it a missing feature?

Thanks 🙂

**Comment by lxfu1** [comment]
https://codesandbox.io/s/wind-rose-f4b3i?file=/App.tsx

**Comment by yanckst** [comment]
Great thanks! Will it be a good idea to create a documentation on the website?
