### ISSUE TITLE
Support for horizontalFactor in charts

### ISSUE THREAD

**Issue by yanckst** [ant-design/ant-design-charts#872]
Hello, 

I found the `verticalFactor` option where you can move the axe vertically, but I don't see a `horizontalFactor` to move the axe horizontally.

Here's a screenshot on what I try to achieve
![image](https://user-images.githubusercontent.com/30554401/133479318-98bb6a15-1491-4b7a-b003-7f69cbde6ada.png)

I want to move this axe horizontally like the image below : 
![image](https://user-images.githubusercontent.com/30554401/133479167-f92cd8ff-240b-431f-8452-362395c81bdf.png)

I've create a [Code sample](https://codesandbox.io/s/kind-merkle-m8ytd)

Anyone has any input on how we achieve this?

Thanks 🙂

**Comment by lxfu1** [comment]
```ts
    startAngle: 0,
    endAngle:  Math.PI * 2,
    yAxis: {
      verticalFactor: 1,
      xxx
    },
```

**Comment by yanckst** [comment]
The only thing here is if you have label and you do this configuration, all labels are rotating

Before the configuration
![image](https://user-images.githubusercontent.com/30554401/134054872-81801d60-b167-4f60-946f-bcb0a3407a0c.png)

After
![image](https://user-images.githubusercontent.com/30554401/134054936-d06a3f69-9cf0-41d6-b565-dbd1873a3974.png)

As you can see the `1991` label moved and shouldn't. It should stay at the place

[https://codesandbox.io/s/cool-hugle-wo5z9](https://codesandbox.io/s/cool-hugle-wo5z9)
