### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by xiuyangzhe** [ant-design/ant-design-charts#874]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
最新版本，不显示title
![image](https://user-images.githubusercontent.com/27839342/133547275-e6797386-2f91-4c86-890c-af7ee52c0729.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
可以显示标题
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
    const data = [
        { year: '1991', value: 3 },
        { year: '1992', value: 4 },
        { year: '1993', value: 3.5 },
        { year: '1994', value: 5 },
        { year: '1995', value: 4.9 },
        { year: '1996', value: 6 },
        { year: '1997', value: 7 },
        { year: '1998', value: 9 },
        { year: '1999', value: 13 },
    ];

    const config = {
        data,
        title: {
            visible: true,
            text: '123212223213123',
        },
        xField: 'year',
        yField: 'value'
    };
<Line {...config} />
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
最新版本已经不再支持 title 配置，建议看下升级指南。
