### ISSUE TITLE
🐛[BUG]Facet图表中分view设置padding无效

### ISSUE THREAD

**Issue by sherjf** [ant-design/ant-design-charts#877]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Facet图表的padding设置只适用于整体图层，在eachView中针对单独view设置无效，希望能修复下。

**Comment by Aarebecca** [comment]
尝试配置[syncViewPadding](https://g2.antv.vision/zh/docs/api/general/chart/#viewcfg)为回调方法来选项替代padding

**Comment by sherjf** [comment]
在eachView中设置view.padding似乎解决了问题。
