### ISSUE TITLE
🧐[问题]将数据编程后后端获取的数据时报错，报错内容为：Error: data must be defined first

### ISSUE THREAD

**Issue by hanchenxu** [ant-design/ant-design-charts#878]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
将数据编程后后端获取的数据时报错，报错内容为：Error: data must be defined first
![image](https://user-images.githubusercontent.com/36257490/133633505-f65393ba-1513-41a1-b3b8-2d654d0fac63.png)

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
import React from 'react';
import  {FlowAnalysisGraph}  from '@ant-design/charts';
export default class MyTempDemo extends React.Component{
    state:{
        effectData:{}
    }
    componentDidMount() {
        //在此处发起请求后，将返回值通过调用this.setState给effectData复制
    }

    render() {
        const {effectData} = this.state
        const config = {
            effectData,
            nodeCfg: {
                size: [200, 25],
                anchorPoints: [
                    [0.5, 1],
                    [0.5, 0],
                ],
                title: {
                    style: {
                        fill: '#000',
                        fontSize: 12,
                        autoEllipsis:false
                    },
                },
                items: {
                    // padding: [6, 0, 0],
                    containerStyle: {
                        fill: '#fff',
                        fontSize: 8,
                    },
                    style: (cfg, group, type) => {
                        const styles = {
                            icon: {
                                width: 0,
                                height: 0,
                            },
                            value: {
                                width: 0,
                                height: 0,
                                fill: '#f00',
                            },
                            text: {
                                fill: '#aaa',
                            },
                        };
                        return styles[type];
                    },
                },
                nodeStateStyles: {
                    hover: {
                        stroke: '#1890ff',
                        lineWidth: 2,
                    },
                },
                style: {
                    radius: [2, 2, 2, 2],
                },
            },
            edgeCfg: {
                type: 'polyline',
                label: {
                    style: {
                        fill: '#aaa',
                        fontSize: 12,
                        fillOpacity: 1,
                    },
                },
                endArrow: {
                    fill: '#ddd',
                },
                edgeStateStyles: {
                    hover: {
                        stroke: '#1890ff',
                        lineWidth: 2,
                    },
                },
            },
            layout: {
                rankdir: 'TB',
                ranksepFunc: () => 20,
            },
        };

        return (
            <div>
                <FlowAnalysisGraph {...config} />
            </div>
        );
    }
}

**Comment by lxfu1** [comment]
给个默认值  {nodes: [], edges: []}，或者 if(!data)  return null;
