### ISSUE TITLE
🧐[问题]柱状堆积图每段柱子上的文字可以分别设置不同的颜色吗

### ISSUE THREAD

**Issue by zaomiao66** [ant-design/ant-design-charts#879]

**Comment by lxfu1** [comment]
label.style: () => xx

**Comment by zaomiao66** [comment]
> label.style: () => xx

我在项目里这样用了之后，柱状堆积图上的数字就不显示了。
label: {
    style:  () => ({
       fill: 'red'
    })
}
label.content可以这样用，但是不支持返回reactnode

**Comment by xuniuniu** [comment]
我也是不能定制化
