### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by sgy123456** [ant-design/ant-design-charts#882]
### 🐛 报错Failed to minify the code from this file:  ./node_modules/d3-hierarchy/src/hierarchy/each.js:2 

npm run build时候报错
使用版本：
 "@ant-design/charts": "^1.2.13"
node -v  
v14.16.1
npm -v
6.14.12

具体报错：
 npm run build

> @ build /Users/admin/git_code/h-qa-platform
> roadhog build

Build completed in 40.733s

Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/d3-hierarchy/src/hierarchy/each.js:2 

Read more here: http://bit.ly/2tRViJ9

[graceful-process#1750] exit with code:1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `roadhog build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2021-09-18T07_32_42_234Z-debug.log

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wangfeili** [comment]
问题解决了吗？我也碰到同样的问题

**Comment by lxfu1** [comment]
更新到最新版本试试，还有问题的话提供个复现
