### ISSUE TITLE
🧐[问题]Mix图表中的stack为何无法像柱图实现同类统计？

### ISSUE THREAD

**Issue by sherjf** [ant-design/ant-design-charts#885]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Mix图表功能强大，但无法实现分组层叠，且层叠的同类数据无法自动汇总统计，很不方便，有什么办法解决吗？
<img width="397" alt="截屏2021-09-21 09 22 28" src="https://user-images.githubusercontent.com/37824950/134098191-5fb5cb52-8788-45d7-9b9d-8b30e6c4c40b.png">

**Comment by lxfu1** [comment]
V2 的多轴图可以满足
