### ISSUE TITLE
🐛[BUG] IOS 15 safari 环境下报表页面奔溃

### ISSUE THREAD

**Issue by fromacetozed** [ant-design/ant-design-charts#886]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
IOS 15 safari 环境下报表页面奔溃

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

在IOS safari浏览器中打开任意报表页面，如下面官方demo页面
https://charts.ant.design/zh-CN/demos/column

### 🏞 期望结果 [描述你原本期望看到的结果]
正常打开页面

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
无
### © 版本信息

- ant-design-charts 版本: 1.2.13
- 浏览器环境: IOS 15 safari
- 开发环境  mac OS

**Comment by fanguangpeng** [comment]
遇到了同样的问题  官方什么时候可以修复？

**Comment by dengguibao** [comment]
Mac OS  safari 15 pie组件同样奔溃

**Comment by fanguangpeng** [comment]
> Mac OS safari 15 pie组件同样奔溃

不知道什么时候可以修复

**Comment by dcdlove** [comment]
同样遇到了，没升级ios 15前都是好的

**Comment by sunwenli** [comment]
g2 发新版了，这个仓库是不是也得发个新版，才能解决 👁

**Comment by lxfu1** [comment]
更新一下试试
