### ISSUE TITLE
🐛[BUG]Bar图表层叠的颜色排序与Column图表顺序相反，建议修正统一。

### ISSUE THREAD

**Issue by sherjf** [ant-design/ant-design-charts#887]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
当使用Bar图表层叠功能时，层叠顺序与Column图表一致，均为以坐标轴为参照，从上到下，但设置了seriesField后，赋予的颜色顺序却与Column图表相反，Column也是从上到下，Bar却是从下到上。建议修正统一。

**Comment by lxfu1** [comment]
V2 默认可以，也支持 sort
