### ISSUE TITLE
🧐[问题] how to set y axis range in column Charts  

### ISSUE THREAD

**Issue by Gopisuresh-Akula** [ant-design/ant-design-charts#889]
i need to set y axis range in column Chart   if  i add   range  to my column chart  i can show  every month  data properly

**Comment by Shamann** [comment]
@Gopisuresh-Akula , you should use min and max of the meta configuration property. Here is a quick example:
<https://codesandbox.io/s/nervous-bardeen-jkiun?file=/App.tsx>
You also may use ticks properties to set arbitrary ticks within your y-axis range.

**Comment by lxfu1** [comment]
V2
```ts
scale: {
  y: { domain: [min, max]}
}
```
