### ISSUE TITLE
🐛[BUG] 折线图设置formatter，部分数据没有显示

### ISSUE THREAD

**Issue by iambool** [ant-design/ant-design-charts#890]
### 🐛 bug 描述
折线图每个数据点对应一个数据，设置 label: formatter 后，有一些数据节点没有显示对应数据值

### 🏞 期望结果
期望每个数据点都能按照formatter显示数据

### 💻 复现代码
https://codesandbox.io/s/dazzling-pascal-6x5th?file=/App.tsx

### © 版本信息

- ant-design-charts 版本: [e.g. 1.2.13]
- 浏览器环境 crhrome
- 开发环境 [e.g. win10]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/30134533/134318807-cc098e93-72b5-44bc-9ded-8d881a5350a1.png)

**Comment by lxfu1** [comment]
```ts
label: {
  formatter: (text: any) => `${text.value}%`,
  layout: [{type: 'limit-in-plot'}]
},
```
