### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by zhi114** [ant-design/ant-design-charts#891]
### 🐛 bug 描述 
Line组件在坐标点比较少的时候，x坐标系的第一个点不是从最左侧0开始的，显示时第一个x坐标点离最左侧有个padding。
![1632378483045](https://user-images.githubusercontent.com/4452972/134463231-27cba66b-6557-4881-ac14-acf7125503dc.jpg)

### 🏞 期望结果
Line组件在坐标点比较少的时候，没有最左侧的padding，x坐标系的第一个点可以从最左侧开始。

### 💻 复现代码 
function TwoLine({ data }: { data: Trend[] }) {
    const { formatMessage } = useIntl()
    const f = (id: string) => formatMessage({ id })
    const { pageMode } = useSelector((state: AppState) => state.userInfo);
    const config = {
        data: data,
        xField: 'time',
        yField: 'value',
        seriesField: 'category',
        lineStyle: LINESTYLE_WIDTH,
        theme: pageMode === 'dark' ? ANT_CHARTS_DARK : undefined,
        yAxis: {
            label: {
                formatter: (time: string) => {
                    return formatYAxis(time, f);
                },
            },
        },
        padding: [40, 25, 70, 40],
        slider: {
            start: 0,
            end: 1,
        },
        tooltip: {
            title: 'time'
        },
        color: ['#62daaa', '#5b8ff9']
    }

    return (
        <Line
            {...config}
            style={{ height: '320px' }}
            fallback={
                <div
                    style={{
                        width: '100%',
                        height: '200px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                    }}
                >
                    <Spin tip="Loading..."></Spin>
                </div>
            }
        />
    );
}

### © 版本信息

- ant-design-charts 版本: 1.0.18
- 浏览器环境 chrome
- 开发环境 mac OS

**Comment by lxfu1** [comment]
[FAQ](https://charts.ant.design/zh-CN/guide/faq#4%E6%80%8E%E4%B9%88%E8%AE%BE%E7%BD%AE%E6%A8%AA%E8%BD%B4%E4%BB%8E-0-%E5%BC%80%E5%A7%8B)

**Comment by zhi114** [comment]
thanks a lot!
