### ISSUE TITLE
how to build g2 smaller , it is too large 🧐[问题]

### ISSUE THREAD

**Issue by caoqiqi** [ant-design/ant-design-charts#892]
![image](https://user-images.githubusercontent.com/20336355/134489153-28a0e14f-d287-475f-9fdd-be5ba9a7ceae.png)
when I bundle antd-design-charts, it will bundle g2 too. g2 is too large for me. how can i make it smaller?

**Comment by lxfu1** [comment]
Using [CDN](https://charts.ant.design/guide/start#cdn-mode),

**Comment by caoqiqi** [comment]
I think this may not be the cdn problem. At present,  the bottom layer is the full package, I wonder when it will be optimized ?

**Comment by lxfu1** [comment]
[Try the V2](https://ant-design-charts-next.antgroup.com/examples)
