### ISSUE TITLE
单轴好像没有图例，可以自己控制么

### ISSUE THREAD

**Issue by hhlcom** [ant-design/ant-design-charts#895]
![image](https://user-images.githubusercontent.com/71809799/134767819-dd74dacf-798e-4bea-b29f-c823eb263f97.png)
柱形图的代码，单轴没有图例，可以自己配置加么？

![image](https://user-images.githubusercontent.com/71809799/134767864-e44f64e7-948d-45a1-9b10-e76776a2bd56.png)
然后就是想单轴也能拥有图例进行点击展示或者隐藏的效果

**Comment by lxfu1** [comment]
单一数据没有图例、
