### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by 2018Cool** [ant-design/ant-design-charts#899]
### 分组柱状图配置了dodgePadding，当数据为单个分组时，柱图不显示
- ant-design-charts 版本:1.2.13
- 浏览器环境 chrome
- 开发环境 mac OS

### 链接
[codesandbox链接](https://codesandbox.io/s/eager-tesla-6k2dq?file=/App.tsx)

**Comment by Oliver-GMJ** [comment]
还有个问题，有时候改了数据，并且配置dodgePadding时，刷新一下页面柱状图又没显示了
重装依赖包才恢复

**Comment by lxfu1** [comment]
重装包的问题，应该是有依赖冲突，建议检查下用到的可视化库
