### ISSUE TITLE
👑 [需求] 组件用法讨论

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-charts#9]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
现在 G2Plot 和 antd/charts 的用法是常规的config的形式。
如
```tsx

  const config = {
    title: {
      visible: true,
      text: '百分比堆叠面积图',
    },
    data,
    meta: {
      year: {
        range: [0, 1],
      },
    },
    xField: 'year',
    yField: 'value',
    stackField: 'country',
  };
  return <PercentStackedArea {...config} />;
```
我自己比较不喜欢这种用法，理由有三：
1、config 太长，层级关系阅读起来很凌乱
2、config 与图表脱离，基本上使用的时候全靠复制。
3、同一个 config 里面没有重点，很难直观的体现
### 🧐 解决方案 [如果你有解决方案，在这里清晰地阐述]
我自己期望的用法是
```tsx
 return (
    <PercentStackedArea data={data}>
      <Title text="百分比堆叠面积图" />
      <Description text="这是一段图表的描述" />
      <Legend position='botto-left' /> 
    <PercentStackedArea>
)
```
于是我搞了一个库 https://github.com/alitajs/g2charts/issues/8
文档：https://g2charts.alitajs.com/
有几个我自己比较喜欢的点。
1、增加配置就增加组件，自我感觉比较清晰
2、配置和组件绑定，书写的时候可以联想，还能设置图表的默认值
3、默写有特定作用的配置，比如单行折线图变成多行折线图，配置的时候多了一个拆分字段，这个从阅读文档api的时候，很难体现。
4、组件的使用方式，后续如果需要增加辅助工具或调试工具，只要新建一个组件就能扩展。
5、增加图表标注或者是覆盖物的时候，可以自定义组件。（感觉与第4点重复了）
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
不知道你们觉得这种设计方式和使用方式如何？

**Comment by chenshuai2144** [comment]
加了个语法糖，你可以搞一个库试试，我比较喜欢配置的，拷代码和迁移比较简单

**Comment by xiaohuoni** [comment]
当然配置的方式都是保留着的。主要是这么写，后面还能在这基础上构建辅助工具，比如 [AVA](https://github.com/antvis/AVA) ，感觉现在里面的 [auto-plot](https://github.com/antvis/AVA/blob/master/packages/chart-advisor/src/auto-plot.ts) 也是重复的内容。

**Comment by lxfu** [comment]
用法还是建议用config，现在市场上比较流行的其它几个库都是这种使用模式，例如echarts、highcharts等，较大改动可能适得其反。

**Comment by xiaohuoni** [comment]
好的，那这个库1.0 版本需要做啥，整理一下吧。
