### ISSUE TITLE
[问题]是否有计划添加南丁格尔玫瑰图

### ISSUE THREAD

**Issue by gudaoqingfen** [ant-design/ant-design-charts#90]
这种可传递两种参数的，半径与宽度
![image](https://user-images.githubusercontent.com/50326583/85488547-10205b80-b601-11ea-98e9-3afa34d76db5.png)

**Comment by afc163** [comment]
https://charts.ant.design/demos/rose

**Comment by gudaoqingfen** [comment]
> https://charts.ant.design/demos/rose

我看到这种的玫瑰图了，这种只能设置两个参数

radiusField 📌
必选, string

功能描述：扇形切片半径长度所对应的数据字段名。

categoryField 📌
必选, string

功能描述：扇形切片分类所对应的数据字段名（每个扇形的弧度相等）。

还需要一个关于扇形切片角度的参数

**Comment by gudaoqingfen** [comment]
> https://charts.ant.design/demos/rose

我看到这种的玫瑰图了，这种只能设置两个参数

无线电场📌
必选，字符串

功能描述:扇形切片半径长度所对应的数据字段名.

范畴域📌
必选，字符串

功能描述:扇形切片分类所对应的数据字段名(每个扇形的弧度相等)。

还需要一个关于扇形切片角度的参数

**Comment by gudaoqingfen** [comment]
> https://charts.ant.design/demos/rose

需要传递一个关于扇形内角角度的参数
如下图：
![image](https://user-images.githubusercontent.com/50326583/85522134-d61e7c00-b637-11ea-88cb-5eae6b6a3d51.png)
