### ISSUE TITLE
🧐[问题]Legend的itemValue如何设置和自定义？

### ISSUE THREAD

**Issue by sherjf** [ant-design/ant-design-charts#904]
<img width="1091" alt="截屏2021-10-01 10 01 53" src="https://user-images.githubusercontent.com/37824950/135554209-93798b94-f254-49ec-9854-9181b4c772ea.png">
能否给个设置和自定义例子供学习和参考。

**Comment by Shamann** [comment]
Here is a quick ant-design charts [example](https://codesandbox.io/s/dazzling-panka-z332g) adopted from [this ](https://g2plot.antv.vision/en/examples/component/legend#legend-item-cfg) G2Plot example.

**Comment by lxfu1** [comment]
https://ant-design-charts-next.antgroup.com/examples/statistics/column/#legend
