### ISSUE TITLE
🐛[BUG] gl-matrix/vec2 module error in react build

### ISSUE THREAD

**Issue by indermerit** [ant-design/ant-design-charts#908]
Hi Guys,
Thanks for this awesome module.

I have been using ant-designs-charts in one of my site and it was working fine from last 6months, but today it's giving me the below error while generating the react build, i tried adding the dependencies but nothings seems to be working. Could you please help me out to resolve this issue?

Any help will much appreciated!

Thanks & Regards
Inder

![image](https://user-images.githubusercontent.com/91962704/136038182-0d18a230-9437-4a31-b617-8a6f2c7efc9b.png)

**Comment by playergs** [comment]
需要 gl-matrix 模块而不是 gl-matrix/vec2
接下来的问题需要看 issues #907

**Comment by lxfu1** [comment]
https://github.com/antvis/G2Plot/issues/2889 ， Try  to update.
