### ISSUE TITLE
使用Heatmap 当xField被解析为时间类型是会崩溃🐛[BUG]

### ISSUE THREAD

**Issue by malusama** [ant-design/ant-design-charts#91]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
类似
data的源是
[{
      name: "2020-06-24",
      type: "type",
      value: 27,
}]
时会报 Uncaught TypeError: Cannot read property 'x' of undefined 的错误

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
用法不对，xField 用 name 或者 type
