### ISSUE TITLE
🐛[BUG] DualAxes 内存泄漏和性能问题

### ISSUE THREAD

**Issue by shuangquanhuang** [ant-design/ant-design-charts#910]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

`DualAxes`在重新render几次后，点击Legend会变得非常卡，甚至卡死。

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

1. 使用类似如下的代码：
```
import React, { useState } from "react";
import { DualAxes } from "@ant-design/charts";
import { config1, config2 } from "./data.js";
import { Button } from "antd";
import "antd/dist/antd.css"; // or 'antd/dist/antd.less'
import md5 from "md5";

export default function App() {
  const [config, setConfig] = useState(config1);
  return (
    <div>
      <Button
        onClick={() => {
          if (config === config1) {
            setConfig(config2);
          } else {
            setConfig(config1);
          }
        }}
      >
        Rerender
      </Button>
      <div key={md5(JSON.stringify(config))}>
        <DualAxes {...config} />
      </div>
      <div>
        <DualAxes {...config} />
      </div>
    </div>
  );
}

```
2. 上面的代码有两个图，点击render按钮会切换`DualAxes`的参数，随着点击的次数增多（大概三五次之后）下面的图会变得非常卡。

上面的图是一个Workaround，不是期望的用法，它每次都销毁DIV并重新创建实例，期望的是实例不变的时候更新config不会有性能问题。

<img width="1149" alt="Screenshot 2021-10-06 at 11 40 48 AM" src="https://user-images.githubusercontent.com/26765347/136137223-b1924517-3619-4517-a06a-4ec7057aed80.png">

3. 附上视频和内存泄漏图

https://user-images.githubusercontent.com/26765347/136152124-a3cc5837-cc21-4ea4-af7e-2b059c0801a0.mp4

<img width="922" alt="Screenshot 2021-10-06 at 11 45 41 AM" src="https://user-images.githubusercontent.com/26765347/136137517-4559bbf4-ddfc-48fa-8a21-5bd422bf136c.png">

### 🏞 期望结果 [描述你原本期望看到的结果]

我试过直接用G2Plot，有同样的问题，在不`destroy`的情况下，直接调用`plot.update(options: Partial<PlotOptions>);` 更新图表，会有同样的问题。

期望结果：
1. G2Plot的DualAxes在不`destroy`的情况下，直接调用`update`之后，不会有性能问题和内存泄漏问题
2. ant-design/charts，在不销毁div的情况下，不会有性能问题和内存泄漏问题。

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

下面两个ZIP，第一个是代码。第二个是Chrome的Profile，解压得到json文件，从Chrome开发控制台的Performance导入即可看到

[dual-axex-performance-issue.zip](https://github.com/ant-design/ant-design-charts/files/7290681/dual-axex-performance-issue.zip)
[mem_leak_chrome_profile.zip](https://github.com/ant-design/ant-design-charts/files/7290683/mem_leak_chrome_profile.zip)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
你这个链接刷新了很多次也没发现问题，看下是不是新版本已经修复了
![image](https://user-images.githubusercontent.com/31396322/179737088-099f187e-b1cf-4226-a82c-263e0b49b6af.png)

**Comment by shuangquanhuang** [comment]
> 你这个链接刷新了很多次也没发现问题，看下是不是新版本已经修复了 ![image](https://user-images.githubusercontent.com/31396322/179737088-099f187e-b1cf-4226-a82c-263e0b49b6af.png)

我刚试了一下，还是卡的，步骤如下：
1. 点击Render按钮几次，次数越多月卡，你可以点击五次以上试试
2. 点击下方的图的Legend，观察曲线增加、删除，都需要很长时间才能完成
3.

**Comment by visiky** [comment]
你把 point 设置为 false，看下是不是不会卡了（point 的渲染会有些性能影响，但应该不是内存泄漏）

**Comment by visiky** [comment]
point 不是设置在这一层吧

**Comment by shuangquanhuang** [comment]
我不太熟悉point这个参数，你能直接改一下 https://codesandbox.io/s/dual-axex-performance-issue-lwbje?file=/src/App.js

**Comment by laolaolulu** [comment]
请问解决了没呢？ 我也出现了这种情况：数据量比较大直接用setState来更新的数据，内存吭哧吭哧往上涨，简单分析了下感觉是数据更新了旧的没销毁
