### ISSUE TITLE
🧐[问题] [Help] How to add inner and outer shadows to donut chart

### ISSUE THREAD

**Issue by kiennguyen1101** [ant-design/ant-design-charts#911]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
How do I add inner and outer shadows to donut chart?
### 🚑 其他信息 [如截图等其他信息可以贴在这里]
Wanted outcome:
![image](https://user-images.githubusercontent.com/1303314/136500461-7d66bf4b-7aae-4d31-9671-e64eee3f4238.png)

**Comment by lxfu1** [comment]
```ts
  pieStyle: {
    stroke: 'red',
    lineWidth: 10,
    // strokeOpacity: 0.2,
  },
```

**Comment by kiennguyen1101** [comment]
thanks, lxfu1. Since the inside+outside is wider, is it possible to have different `lineWidth` for lines between sectors and line inside+outside of chart?

**Comment by lxfu1** [comment]
Not Supported.
