### ISSUE TITLE
🧐[问题] How to add date range or min/max date on xAxis ticks ?

### ISSUE THREAD

**Issue by pranit-madhavi-v2stech** [ant-design/ant-design-charts#915]
### 🧐 While showing the data on chart, chart shows the default date ticks on xAxis from data. As shown in below image.
![Screenshot from 2021-10-11 17-18-03](https://user-images.githubusercontent.com/51791997/136785174-3ea16398-4963-4bcb-b022-f5a705173a8c.png)
Suppose the date range for data is 1st July to 30th Oct, but the available data is for 3 Aug - 11 Oct, But I want to show the date range of 1st July to 30th Oct on xAxis as shown in below Image. How to add the different date on xAxis ticks?
![c19d4593-f9df-4c9c-9bdc-583698282290](https://user-images.githubusercontent.com/51791997/136785744-cca8064d-640a-4a2d-aead-3082a83e934c.png)

My xAxis configuration
```
xAxis: {
            label: {
                formatter: function formatter(v: any) {
                    return moment(v).format("ddd (MM/DD h:mm A)");
                },
                style: {
                    fill: "#6E759F",
                    fontSize: 9,
                }
            }
        },
```

**Comment by pranitv2stech** [comment]
> https://charts.ant.design/guide/faq#4how-do-i-set-the-horizontal-axis-to-start-at-0

I want to start the axis from a different date than start at 0. the range value in meta config is 0~1, what I want to achieve is the min date and max date on xAxis
Here is my complete config
`
{
        data: chartData,
        height: 268,
        xField: 'date',
        yField: 'value',
        meta: { 'date': { range: [0, 1] } },
        seriesField: 'type',
        colorField: 'type',
        fillOpacity: 1,
        smooth: true,
        legend: false,
        color: ({ type }: { type: string }) => {
            if (type === "Potential risk") {
                return "#2AABAB"
            }
            if (type === "Actual risk") {
                return "#FA8C16"
            }
        },
        yAxis: {
            tickInterval: 40,
            label: {
                style: {
                    fill: "#6E759F",
                    fontSize: 9,
                    fontFamily: "SF-Pro-Display-Regular"
                }
            },
            grid: {
                line: {
                    style: {
                        stroke: "#F2F4F6",
                        lineWidth: 1
                    }
                }
            }
        },
        xAxis: {
            label: {
                formatter: function formatter(v: any) {
                    return moment(v).format("ddd (MM/DD h:mm A)");
                },
                style: {
                    fill: "#6E759F",
                    fontSize: 9,
                    fontFamily: "SF-Pro-Display-Regular",
                },
            }
        },
        areaStyle: function areaStyle() {
            return { fillOpacity: 0.10 }
        },
    }
`

Codesandbox link: https://codesandbox.io/s/goofy-torvalds-7utup?file=/App.tsx

**Comment by Shamann** [comment]
@pranitv2stech, you can specify the date range using the meta config property by combining ticks and min/max options:
<https://codesandbox.io/s/unruffled-fire-ms8h2?file=/App.tsx>
Or you can just add two data points with null values, one for each end of the desired interval:
<https://codesandbox.io/s/peaceful-phoebe-q00l2?file=/App.tsx>
