### ISSUE TITLE
Heatmap热力图 窗口大小发生变化后，报错🐛[BUG]

### ISSUE THREAD

**Issue by wangzhiming** [ant-design/ant-design-charts#92]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Heatmap生成热力图之后
![image](https://user-images.githubusercontent.com/5162195/85735861-98e9e500-b730-11ea-96f5-7fa5ed31bca0.png)
对浏览器窗口大小进行调整，就会报错
![image](https://user-images.githubusercontent.com/5162195/85735980-af903c00-b730-11ea-9f6e-b07e4d40fb73.png)
固定width和height就不会有这样的报错
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wangzhiming** [comment]
如果设定 legend = false就不会出现这样的问题了
  legend: {
    visible: false,
    position:'left-top',
  },

**Comment by lxfu1** [comment]
升级到 1.0 
```ts
width: 500,
height: 500,
autoFit: false
```
