### ISSUE TITLE
折线图+缩略轴显示异常🐛[BUG]

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design-charts#920]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

在我这个例子中，缩略轴添加后导致曲线绘制错乱：

正常曲线：
![image](https://user-images.githubusercontent.com/49147660/136902532-434a5105-4d8b-47c7-81b4-f1b6861b8a3f.png)

添加缩略轴后：
![image](https://user-images.githubusercontent.com/49147660/136902581-32852722-eb08-4fe4-8e27-969accb3c7c7.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://codesandbox.io/embed/naughty-wright-l9bqj?fontsize=14&hidenavigation=1&theme=dark

**Comment by lxfu1** [comment]
xField 使用 string 类型， "0"、"1"

**Comment by CNFeffery** [comment]
> xField 使用 string 类型， "0"、"1"

已解决，谢谢😀
