### ISSUE TITLE
👑 [需求] remove ellipsis from  legend at Pie chart

### ISSUE THREAD

**Issue by evgeniya-osmakova** [ant-design/ant-design-charts#925]
### 🥰 I need to remove ellipsis from legend at Pie chart and show full items names. I've found no option how to make it

<img width="787" alt="Screen Shot 2021-10-13 at 21 29 38" src="https://user-images.githubusercontent.com/5876576/137192049-be53e70a-8559-4b4b-81fb-2e39077e8066.png">

**Comment by lxfu1** [comment]
```ts
    legend: {
      maxItemWidth: 1,
      maxWidthRatio: 1
    },
```
