### ISSUE TITLE
I couldn't use the lib

### ISSUE THREAD

**Issue by titipignataro** [ant-design/ant-design-charts#929]
Hello,
I've installed this library following the steps listed in
https://charts.ant.design/guide/start

So I made yarn add @ant-design/charts
But when used the Pie Chart, the following message came up to me and I couldn't use the chart.

export __spreadArray was not found in 'tslib'

![image](https://user-images.githubusercontent.com/19999197/137392246-e8605508-da51-4488-ad04-eeefe17bacd8.png)

**Comment by lxfu1** [comment]
Upgrade tslib [npm install tslib --save](https://github.com/ant-design/ant-design-charts/issues/576)

**Comment by titipignataro** [comment]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/19999197/137789862-f943ed4c-4230-4b4b-899c-3089905ea92b.png">
![image](https://user-images.githubusercontent.com/19999197/137789908-43e09d72-7ee4-4688-b947-c04156fbadc9.png)
![image](https://user-images.githubusercontent.com/19999197/137789933-bc682ec2-a2a0-4182-b8c1-17ddcd64d98a.png)

**Comment by titipignataro** [comment]
The problem was not resolved

**Comment by mboettcher** [comment]
I'm facing the same issue. Even after adding latest tslib via `yarn add tslib` antd charts is not working.

**Comment by mboettcher** [comment]
Fixed the issue by removing tslib from `yarn.lock` and running yarn again. Previously `tslib@^2` was resolved to 2.0.3 instead of the lastest version. 

However, I'm still facing issues with Jest.

**Comment by lxfu1** [comment]
> Fixed the issue by removing tslib from `yarn.lock` and running yarn again. Previously `tslib@^2` was resolved to 2.0.3 instead of the lastest version.
> 
> However, I'm still facing issues with Jest.

https://github.com/ant-design/ant-design-charts/issues/518
