### ISSUE TITLE
🧐 tooltip 的辅助线文本框圆角如何设置，及最后一个数据的辅助线文本未显示完全

### ISSUE THREAD

**Issue by lindsay135** [ant-design/ant-design-charts#932]
### 🧐 面积图辅助线有两个问题，一直找不到解决方法，请大佬们帮忙协助下：
1. 辅助线文本的背景圆角如何设置
2. 最后一个数据的 X 轴辅助线文本有一部分未显示，如何解决

### 💻 示例代码 
[https://codesandbox.io/s/elegant-brown-idvoy?file=/App.tsx:0-2909](url)
<img width="384" alt="222" src="https://user-images.githubusercontent.com/53045287/137451049-bf53ca5d-f26e-4621-9c7a-6550f8f04131.png">

### 🚑 其他信息 
<img width="703" alt="11111" src="https://user-images.githubusercontent.com/53045287/137449727-b24b14d8-d8cd-45a0-ad18-0139834735b8.png">

**Comment by lxfu1** [comment]
```ts
        text: (type: string, defaultContent: any) => {
          const position = type === "x" ? "end" : "start";
          return {
            type,
            content: defaultContent,
            autoRotate: false,
            position: position,
            offset: 10,
            style: {
              fill: "#FFFFFF",
              textAlign: "end", // 动态设置
              textBaseline: "bottom",
              r: 6
            }
          };
        },
        textBackground: {
          padding: [5, 4, 2, 4],
          style: {
            radius: 10,
            fill: "#5381FB",
            stroke: "red",
            lineCap: "round"
          }
        }
```
