### ISSUE TITLE
🐛[BUG] DualAxes中使用silder时显示异常

### ISSUE THREAD

**Issue by iambool** [ant-design/ant-design-charts#939]
### 🐛 bug 描述
DualAxes配置silder：
（1）拖动滚动轴后，图像撑出区域；
（2）切换数据源，折线全缩在左侧，没有正常显示；

### 📷 复现步骤
使用DualAxes时配置slider，然后拖滚动条

### 🏞 期望结果 [描述你原本期望看到的结果]
无论是拖动滚动条还是切换数据，都能渲染正确的折线图

### 💻 复现代码
https://codesandbox.io/s/objective-alex-h1ebw?file=/MutiyFieldLine.tsx

### © 版本信息

- ant-design-charts 版本: 1.2.11
- 浏览器环境 chrome
- 开发环境 win10

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![bug](https://user-images.githubusercontent.com/30134533/138019329-babf2f21-4afc-45ee-9565-fd8f3851d655.gif)

**Comment by soundjxy** [comment]
同样的问题，怎么解决的？

**Comment by iambool** [comment]
> https://codesandbox.io/s/objective-alex-h1ebw?file=/MutiyFieldLine.tsx

配置中增加这一堆：
![image](https://user-images.githubusercontent.com/30134533/221758916-8bbe975b-a80a-4bd4-b824-3e660cc37801.png)

**Comment by jypblue** [comment]
同样的问题怎么解决的？

**Comment by iambool** [comment]
> 同样的问题怎么解决的？

上面的配置就是解决办法
