### ISSUE TITLE
🧐[问题] 设置formatter后，定时刷新数据会导致图表闪烁，不断重新render

### ISSUE THREAD

**Issue by goomadao** [ant-design/ant-design-charts#940]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]

通过useEffect刷新数据，在设置了formatter的情况下，即使刷新出来的数据没有变化，图表也会重新render，表现为每次刷新数据时图表都会闪烁。

不设置formatter则正常，刷新数据时不会闪烁。

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]

基于[官方示例](https://charts.ant.design/zh-CN/demos/line#%E6%8C%87%E5%AE%9A%E6%8A%98%E7%BA%BF%E9%A2%9C%E8%89%B2)，加上数据的定时刷新，图表会闪烁，注释掉y轴的formatter后就不再闪烁了。
[codesandbox](https://codesandbox.io/s/misty-fast-1mpl1?file=/App.tsx:696-921)

**Comment by zhaoqiang1024** [comment]
解决了吗？我貌似也出现了这个问题，但是我的更奇怪用嵌套setTimeout来定时更新时会有问题，用setInterval定时更新时没有问题

**Comment by zhaoqiang1024** [comment]
> 定时刷新出来的数据有可能是会变化的，memo只能解决数据没有变化的情况。
> 
> 在定时刷新数据发生变化的情况下，如果设置了formatter，每次刷新，折线都会有一个从开始到末尾的render动画，并且tooltip会消失，而如果没有设置formatter，则是直接出现变化后的折线，tooltip也不会消失。

解决了吗，我也是这个问题

**Comment by lxfu1** [comment]
formatter 没法检测是否变化，所以会走刷新逻辑，在memo里面做判断就好。

**Comment by wozien** [comment]
mark

**Comment by wozien** [comment]
> > 定时刷新出来的数据有可能是会变化的，memo只能解决数据没有变化的情况。
> > 在定时刷新数据发生变化的情况下，如果设置了formatter，每次刷新，折线都会有一个从开始到末尾的render动画，并且tooltip会消失，而如果没有设置formatter，则是直接出现变化后的折线，tooltip也不会消失。
> 
> 解决了吗，我也是这个问题

最后解决了吗

**Comment by lxfu1** [comment]
> 用到的图表组件都需要使用React.memo套一下？

可以统一包裹一下
