### ISSUE TITLE
🐛[BUG] Using "@ant-design/charts" and  "@antv/graphin" at the same time generates double layout registration.

### ISSUE THREAD

**Issue by luismvargasg** [ant-design/ant-design-charts#941]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

Importing those two libraries makes the function "registerLayout" run twice, warning the user that it will override the layout names.

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

- Create a React-App
- Install and import @ant-design/charts
- Install and import @antv/graphin
- Import and create one component from each library

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

https://codesandbox.io/s/silly-dawn-rk3zc?file=/App.tsx:48-61

### © 版本信息

"@ant-design/charts": "^1.2.14",
"@antv/graphin": "^2.4.2",
"react": "^17.0.2",
"react-dom": "^17.0.2"

### 🚑 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/60363752/138188149-458853d2-f662-45ad-8cd0-3aca249c0513.png)

**Comment by lxfu1** [comment]
The underlying layer relies on G6. It is recommended to choose either one or use the V2 version.
