### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by lindsay135** [ant-design/ant-design-charts#942]
### 🧐 请问有没有这样的图表，有两个 y 轴 一个 x 轴和一条折线
1、我目前使用双折线图 DualAxes ，其中一条折线的颜色设置透明来实现的，但是遇到了下面问题：
      toolTip 显示时 透明折线有个白色的圆圈圈，这个圈圈怎么取消
       
<img width="329" alt="11" src="https://user-images.githubusercontent.com/53045287/138407354-cde74df3-dfa1-4176-bffb-3c63fcb91c39.png">

2、有没有可以直接实现这个需求的图表？或者其他方法可以实现此需求

### 💻 示例代码
https://codesandbox.io/s/great-saha-mebg3?file=/App.tsx

![image](https://user-images.githubusercontent.com/53045287/138407275-3bc56072-759b-4de5-a949-ab75d1803e50.png)

**Comment by lxfu1** [comment]
你这个使用自定义tooltip就行了，https://ant-design-charts.antgroup.com/manual/case#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip
