### ISSUE TITLE
Chart alignment

### ISSUE THREAD

**Issue by Valtas** [ant-design/ant-design-charts#947]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
Problems with the Diagram.
1) How do I align the chart to the left? In the screenshot, you can see a lot of empty space to the left of the diagram, which shouldn't be.

2) The legends on the right are truncated, although there is space on the right. Why did the diagram cut off the text of the legend?

3) There is an empty space between the legend and the diagram, which should not be. How to remove it?

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```
const data = [
    { type: "Состоявшиеся диалоги", value: 2100 },
    { type: "Пропущенные диалоги", value: 115 },
];

const config: PieConfig = {
    height: 170,
    data,
    angleField: "value",
    colorField: "type",
    color: ["#fabc68", "#fa898b"],
    radius: 1,
    innerRadius: 0.6,
    label: {
        type: "inner",
        offset: "-50%",
        content: "{value}",
        autoRotate: false,
        style: {
            textAlign: "center",
            fontSize: 12,
        },
    },
    interactions: [
        { type: "element-active" },
    ],
    statistic: {
        title: {
            content: "Всего",
            offsetY: -4 - 2,
            style: { fontSize: "11px" },
        },
        content: {
            offsetY: -4,
            style: { fontSize: "20px" },
        },
    },
};
```

```
<div><Pie {...config} /></div>
```

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
"@ant-design/charts": "1.2.14"

CodeSanbox example - https://codesandbox.io/s/ant-chart-alignment-problem-2vsq2

![localhost_3000_ru - Google Chrome 2021-10-29 15 22](https://user-images.githubusercontent.com/14878109/139434926-90b63790-a1b8-45c3-9db3-17b3f52bd0e5.png)

**Comment by lxfu1** [comment]
The legend can be positioned, but the chart defaults to starting from the middle. The container width can be adjusted.
