### ISSUE TITLE
data的大小有限制吗？🧐[问题]

### ISSUE THREAD

**Issue by glve1027** [ant-design/ant-design-charts#949]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
我从网络端获取了62.5kb大小的数据，直接赋值给data，发现浏览器都直接crash了

### 💻 示例代码 [如果有必要，展示代码，线上示例，或仓库]
```js
 const config = {
    data, // 62.5kb
  };

<Line {...config} />;
```

**Comment by lxfu1** [comment]
和 data 大小关系不大，看下里面的数据是不是有特殊。

**Comment by glve1027** [comment]
数据 还会导致浏览器crash吗？
我看终端报错信息是这个：
```shell
[1103/092527.025681:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x16f3fc000, 0x8000): (os/kern) protection failure (2)
```
我减少了数据，就没问题了

**Comment by glve1027** [comment]
demo: https://codesandbox.io/s/musing-zeh-tujtq?file=/src/App.js  
codepen 也crash了

**Comment by glve1027** [comment]
确实是数据有问题。

**Comment by hustcc** [comment]
> 确实是数据有问题。

可以描述一下是什么样的异常数据～

**Comment by glve1027** [comment]
> > 确实是数据有问题。
> 
> 可以描述一下是什么样的异常数据～


![pro](https://user-images.githubusercontent.com/49513119/140005451-0ac0f89b-0a81-467b-8f82-290d1ac76771.jpg)
