### ISSUE TITLE
🧐[问题]关于玫瑰图如何实现同时传递半径与弧度参数

### ISSUE THREAD

**Issue by gudaoqingfen** [ant-design/ant-design-charts#95]
### 🧐 问题描述 [详细地描述问题，让大家都能理解]
需要实现如下图功能
![image](https://user-images.githubusercontent.com/50326583/86098470-bcbe7980-bae8-11ea-8915-41aa6dd177b4.png)

如下图
![image](https://user-images.githubusercontent.com/50326583/86098737-2048a700-bae9-11ea-9455-7c2168062b39.png)
翻了很久api文档，不知道如何传递弧度的这个参数

**Comment by lxfu1** [comment]
这什么需求～，底层的 [G2 ](https://g2.antv.vision/zh/)支持， G2Plot 规划中。

**Comment by gudaoqingfen** [comment]
> 这什么需求~，底层的[G2](https://g2.antv.vision/zh/)支持，G2Plot规划中.

已经使用G2实现了，抽空封装一下

**Comment by hustcc** [comment]
> > 这什么需求~，底层的[G2](https://g2.antv.vision/zh/)支持，G2Plot规划中.
> 
> 已经使用G2实现了，抽空封装一下

可以大概描述一下你的业务场景吗，用来去可视化什么数据？

**Comment by gudaoqingfen** [comment]
> > > 这什么需求~，底层的[G2](https://g2.antv.vision/zh/)支持，G2Plot规划中.
> > 
> > 
> > 已经使用G2实现了，抽空封装一下
> 
> 可以大概描述一下你的业务场景吗，用来去可视化什么数据？

此图为医院各个MDC组的覆盖情况，半径入组例数，宽度是组数。

**Comment by gudaoqingfen** [comment]
> 这什么需求～，底层的 [G2 ](https://g2.antv.vision/zh/)支持， G2Plot 规划中。

`import { Chart, Geom, Axis, Tooltip, Legend, Guide, Coord, Label, G2 } from 'bizcharts';
import React from 'react';

const { Html } = Guide;
const SnailRose= props => {
  const { values } = props;
  let max = 0;
  if (values && Object.keys(values).length) {
    values.forEach(obj => {
      if (obj.pop > max) {
        max = obj.pop;
      }
    }); // 自定义 other 的图形，增加两条线
  }
  G2.Shape.registerShape('interval', 'sliceShape', {
    draw(cfg, container) {
      // alert(JSON.stringify(cfg));
      const { points } = cfg;
      // eslint-disable-next-line no-underscore-dangle
      const origin = cfg.origin._origin;
      const percent = origin.pop / max;
      const xWidth = points[2].x - points[1].x;
      const width = xWidth * percent;
      let path = [];
      path.push(['M', points[0].x, points[0].y]);
      path.push(['L', points[1].x, points[1].y]);
      path.push(['L', points[0].x + width, points[2].y]);
      path.push(['L', points[0].x + width, points[3].y]);
      path.push('Z');
      // eslint-disable-next-line react/no-this-in-sfc
      path = this.parsePath(path);
      return container.addShape('path', {
        attrs: {
          fill: cfg.color,
          path,
        },
      });
    },
  });

  return (
    <div>
      <Chart height={700} data={values} forceFit>
        <Coord type="theta" radius={0.8} innerRadius={0.2} />
        <Guide>
          <Html
            position={['50%', '50%']}
            html={
              "<div style='color:#8c8c8c;font-size:1.16em;text-align: center;width: 10em;'><span style='color:#262626;font-size:1.5em'>MDC</span></div>"
            }
            alignX="middle"
            alignY="middle"
          />
        </Guide>
        <Axis name="pop" line={null} label={null} tickLine={null} />
        <Legend position="left-center" offsetX={200} />
        <Tooltip title={null} crossLine={{ stroke: '#f00' }} />
        <Geom
          type="intervalStack"
          position="pop"
          color="idxName"
          shape="sliceShape"
          tooltip={[
            'idxName*pop*yoy',
            (idxName, pop, yoy) => ({
              // eslint-disable-next-line no-irregular-whitespace
              // 自定义 tooltip 上显示的 title 显示内容等。
              title: `MDC类型：${idxName}`,
              name: `总病历数：${pop}`,
              value: `DRG组数：${yoy}`,
            }),
          ]}
        >
          <Label content="idxName" />
        </Geom>
      </Chart>
    </div>
  );
};

export default SnailRose;
`

**Comment by lxfu1** [comment]
使用 Rose ， 设置一下 innerRadius: 0.2 。

**Comment by visiky** [comment]
就是 半径和弧度都参与映射就行了；先用 G2Plot 的开发插件实现，优化的开放图表 我们会考虑内置
