### ISSUE TITLE
🐛[BUG]分组柱状图显示问题

### ISSUE THREAD

**Issue by LxShine** [ant-design/ant-design-charts#950]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/11518817/140002949-f8223a5c-9873-428c-937a-bffc67375e04.png)
薪资在第一个没有显示，而且数值是从第一个的数值开始，加了Y轴数值从0开始也是一样
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lxfu1** [comment]
数据需要是 number 类型

**Comment by LxShine** [comment]
好的，谢谢
