### ISSUE TITLE
🐛[BUG] Legend types crashing typescript project

### ISSUE THREAD

**Issue by antonyleme** [ant-design/ant-design-charts#952]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
Legend position is causing app crash when using with typescript in Bar and Columns.

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
Just copy and paste the examples from the docs in a typescript project. I can even reproduce the crash on the official doc's codesandbox.

### 🏞 期望结果 [描述你原本期望看到的结果]
Work properly.

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://codesandbox.io/s/4yz1s?file=/App.tsx:0-989

### © 版本信息

- ant-design-charts 版本: 1.2.14
- 开发环境 typescript react project

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/36122235/140258919-aab0ff5b-c90d-4b7b-8307-d0092c3df034.png)
![image](https://user-images.githubusercontent.com/36122235/140258971-87c9994b-75c9-4214-80ea-d7f830495ca7.png)

**Comment by santoshvijapure** [comment]
+1 @antonyleme

**Comment by lxfu1** [comment]
var config = {xx}  as const;

**Comment by IanLunn** [comment]
@lxfu1 Can you explain how this solves the issue please?

**Comment by BrickerZou** [comment]
> +1 @antonyleme

+1
any solution?
