### ISSUE TITLE
👑 [需求] How to remove title / text from x axis and y axis on bar chart? please help me :( 

### ISSUE THREAD

**Issue by david1312** [ant-design/ant-design-charts#956]
<img width="1116" alt="Screen Shot 2021-11-11 at 15 38 07" src="https://user-images.githubusercontent.com/31871913/141265992-57c19b0e-2e98-4f00-a49e-57b92d2d1a1d.png">

**Comment by SukhachevN** [comment]
add to config 
`meta:{
  fieldName:{
  formatter: (value, index) => {}
}
}`

**Comment by david1312** [comment]
okay thaknyou, found it already here maybe useful for others how to remove label from x and y axis
xAxis: {
      label: '',
      grid: {
        line: {
          style: {
            lineWidth: 0,
          },
        },
      },
    },
    yAxis: {
      label: '',
      grid: {
        line: {
          style: {
            lineWidth: 0,
          },
        },
      },
    },
