### ISSUE TITLE
图表中的title设置无效果

### ISSUE THREAD

**Issue by MachoManCk** [ant-design/ant-design-charts#958]
const data = [
        {
            date: '2018/8/1',
            type: 'DAC',
            value: 4623,
        },
        {
            date: '2018/8/1',
            type: 'GMV',
            value: 2208,
        },
        {
            date: '2018/8/2',
            type: 'DAC',
            value: 6145,
        },
        {
            date: '2018/8/2',
            type: 'GMV',
            value: 2016,
        },
        {
            date: '2018/8/3',
            type: 'DAC',
            value: 508,
        },
        {
            date: '2018/8/3',
            type: 'GMV',
            value: 2916,
        },
        {
            date: '2018/8/4',
            type: 'DAC',
            value: 6268,
        },
        {
            date: '2018/8/4',
            type: 'GMV',
            value: 4512,
        },
        {
            date: '2018/8/5',
            type: 'DAC',
            value: 6411,
        },
        {
            date: '2018/8/5',
            type: 'GMV',
            value: 8281,
        },
        {
            date: '2018/8/6',
            type: 'DAC',
            value: 1890,
        },
        {
            date: '2018/8/6',
            type: 'GMV',
            value: 2008,
        },
        {
            date: '2018/8/7',
            type: 'DAC',
            value: 4251,
        },
        {
            date: '2018/8/7',
            type: 'GMV',
            value: 1963,
        },
        {
            date: '2018/8/8',
            type: 'DAC',
            value: 2978,
        },
        {
            date: '2018/8/8',
            type: 'GMV',
            value: 2367,
        },
        {
            date: '2018/8/9',
            type: 'DAC',
            value: 3880,
        },
        {
            date: '2018/8/9',
            type: 'GMV',
            value: 2956,
        },
        {
            date: '2018/8/10',
            type: 'DAC',
            value: 3606,
        },
        {
            date: '2018/8/10',
            type: 'GMV',
            value: 678,
        },
        {
            date: '2018/8/11',
            type: 'DAC',
            value: 4311,
        },
        {
            date: '2018/8/11',
            type: 'GMV',
            value: 3188,
        },
        {
            date: '2018/8/12',
            type: 'DAC',
            value: 4116,
        },
        {
            date: '2018/8/12',
            type: 'GMV',
            value: 3491,
        },
        {
            date: '2018/8/13',
            type: 'DAC',
            value: 6419,
        },
        {
            date: '2018/8/13',
            type: 'GMV',
            value: 2852,
        },
        {
            date: '2018/8/14',
            type: 'DAC',
            value: 1643,
        },
        {
            date: '2018/8/14',
            type: 'GMV',
            value: 4788,
        },
        {
            date: '2018/8/15',
            type: 'DAC',
            value: 445,
        },
        {
            date: '2018/8/15',
            type: 'GMV',
            value: 4319,
        }
    ];
    const config = {
        title: {
            text: '多折线图',
            color:'#000000'
        },
        description: {
            visible: true,
            text: '通过回调函数指定折线颜色',
        },
        data,
        xField: 'date',
        yField: 'value',
        legend: { position: 'bottom' },
        seriesField: 'type',
        point: { visible: true },
        color: ['#6a99d0', '#de8344'],
        animation: { appear: { animation: 'clipingWithData' } },
        responsive: true,
        label: {
            visible: true
        },
        smooth: true,
    };

**Comment by MachoManCk** [comment]
![image](https://user-images.githubusercontent.com/34299788/141417521-cb768d61-518e-4b95-a30a-1e08525961cd.png)

**Comment by MachoManCk** [comment]
"@ant-design/charts": "1.2.11",

**Comment by lxfu1** [comment]
1.x 版本不再支持 title 配置，看下升级指南。

**Comment by 1977474741** [comment]
> 1、Title组合在外部实际的话，可以实际丰厚的形式和交互（如果内部设置的话，一般会是比较简单的形式，也会希冀是底层倚靠，现实）2、图表底层依赖G2 4.0 ，目前不支持（下一个版本升级，会重新支持标题）

我看目前还是不支持的，调了半天都不行，原来是废弃了！可以默认不开启，怎么能直接干掉了！大多数场景就是一个纯标题展示而已，价值还是很大的啊，服气

**Comment by changfu2015** [comment]
这体验，官网的例子都没更新

**Comment by jy1989** [comment]
看半天  原来没更新文档。。。。。
