### ISSUE TITLE
🐛[BUG] Donut圆环图value为null

### ISSUE THREAD

**Issue by kiwenlau** [ant-design/ant-design-charts#96]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/10240841/86308042-d2e44b00-bc4a-11ea-8f1f-218c47bee3db.png)

### 📷 复现步骤

仓库：[https://github.com/kiwenlau/g2plot-donut-demo](https://github.com/kiwenlau/g2plot-donut-demo)
直接运行即可

### 🏞 期望结果

![截屏2020-07-02 上午10 02 50](https://user-images.githubusercontent.com/10240841/86308233-366e7880-bc4b-11ea-833b-fb65361da51f.png)

### 💻 复现代码

仓库：[https://github.com/kiwenlau/g2plot-donut-demo](https://github.com/kiwenlau/g2plot-donut-demo)

我用setTimeout模拟了HTTP请求，核心代码如下：

```javascript
import React, { useEffect, useState } from "react";
import { Donut } from "@ant-design/charts";

const setTimeoutPromise = ms => new Promise(resolve => setTimeout(resolve, ms));

export default function App(props) {
  const [data, setData] = useState([]);
  const { time } = props;

  useEffect(() => {
    const fetchData = async () => {
      const res = await setTimeoutPromise(time).then(() => [
        {
          type: "Google",
          value: 25
        },
        {
          type: "Facebook",
          value: 25
        },
        {
          type: "Alibaba",
          value: 25
        },
        {
          type: "Tencent",
          value: 25
        }
      ]);
      setData(res);
    };
    fetchData();
  }, [time]);

  const config = {
    forceFit: true,
    radius: 0.8,
    data,
    angleField: "value",
    colorField: "type"
  };

  return (
    <div className="App">
      <Donut {...config} />
    </div>
  );
}
```

### © 版本信息

- ant-design-charts 版本: 0.9.6
- @antv/g2plot版本：1.1.8
- 浏览器环境：Chrome
- 开发环境 macOS

### 🚑 其他信息

应该是@antv/g2plot@1.1.8导致的BUG，我通过package-lock.json将@antv/g2plot的版本锁定为1.1.7时就没有问题了

**Comment by lxfu1** [comment]
这个是依赖问题，G2Plot 下个版本修复。

**Comment by afc163** [comment]
修复了么？

**Comment by liujiayu10** [comment]
> 修复了么？

还没有修复，唉

**Comment by lxfu1** [comment]
你更新试试呢，这个是依赖的 bug ， 依赖已经发布新版本。

**Comment by liujiayu10** [comment]
> 你更新试试呢，这个是依赖的 bug ， 依赖已经发布新版本。

谢谢大大！

**Comment by kiwenlau** [comment]
我确认了一下，问题已修复：

```bash
npm list | grep @ant-design/charts
├─┬ @ant-design/charts@0.9.10 

npm list | grep g2plot 
│ ├─┬ @antv/g2plot@1.1.22
```
