### ISSUE TITLE
👑 [需求] G6版本更新

### ISSUE THREAD

**Issue by qjekingstar** [ant-design/ant-design-charts#960]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
G6那边修复了不少bug，charts这边有计划大概什么时间会更新G6的版本吗？谢谢

**Comment by lxfu1** [comment]
charts 目前有遇到明确问题吗？ 之前锁版本是因为  G6 中途出了个问题，短时间内没有修复掉。

**Comment by qjekingstar** [comment]
[#2863](https://github.com/antvis/G6/issues/2863)
我的项目中需要snapline的功能，目前是直接从G6那边复制到项目中作为自定义plugin的
