### ISSUE TITLE
👑 [需求]是否支持尖底漏斗图，shape="pyramid"

### ISSUE THREAD

**Issue by yangjie2021** [ant-design/ant-design-charts#961]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
`<Funnel
      data={funnelData}
      xField="eventName"
      yField="num"
      shape="pyramid"
    />`
想要通过配置shape="pyramid"实现尖底漏斗图，如下链接所示

https://g2.antv.vision/zh/examples/funnel/funnel#pyramid

**Comment by lxfu1** [comment]
应该很久之前就支持，忘记关闭issue
