### ISSUE TITLE
changing legend marker size and position

### ISSUE THREAD

**Issue by SukhachevN** [ant-design/ant-design-charts#962]
Hello! Is it possible to change marker size and position? I read docs( https://g2.antv.vision/zh/docs/api/general/legend/#legendoptionmarker ), but didnt undersand how change marker size and how change marker position. Can anyone say how i can change it? 

what i have:
![image](https://user-images.githubusercontent.com/43090884/141803478-8ff787ca-cbe1-42fb-a9f7-f5d1a7263ed2.png)

what i want:
![image](https://user-images.githubusercontent.com/43090884/141803391-5888066d-fe18-4c35-a6eb-653ceea37ad4.png)

[Here](https://github.com/ant-design/ant-design-charts/issues/772)  i had read that can use custom legend, but i didnt found info how to use it.

**Comment by lxfu1** [comment]
I'm very sorry, I couldn't deal with it in time， refer to https://codesandbox.io/s/funny-kowalevski-z2kymb?file=/index.js
