### ISSUE TITLE
🐛[BUG] 双Y轴数据缺少时不展示X轴及slider

### ISSUE THREAD

**Issue by jiandan1989** [ant-design/ant-design-charts#963]
### 🏞 期望结果 [描述你原本期望看到的结果]
1. 针对双Y轴, 无论是左侧或右侧无数据时内部做兼容, 仅一侧有数据时正常 Slider 和 X轴刻度显示

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
<img width="1083" alt="123" src="https://user-images.githubusercontent.com/16014141/141806862-d18656d1-8aff-4487-bbb5-9a5783b9352f.png">

**Comment by lxfu1** [comment]
双轴图目前用的左侧数据来映射 xAxis，需要确保左侧有数据。

**Comment by lxfu1** [comment]
建议升级到 V2 版本
