### ISSUE TITLE
🐛[BUG] legend 设置 marker 不生效

### ISSUE THREAD

**Issue by jiandan1989** [ant-design/ant-design-charts#965]
### 🏞 期望结果 [描述你原本期望看到的结果]
自定义设置内置的 symbol 正常显示

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息 [如截图等其他信息可以贴在这里]
官方文档
<img width="1061" alt="12345" src="https://user-images.githubusercontent.com/16014141/141818437-cf5a7666-a34e-4718-a828-5624df26a2fd.png">

DEMO 截图
<img width="514" alt="symbol" src="https://user-images.githubusercontent.com/16014141/141818492-4b34e44a-c8c9-4528-be64-8db174bb4047.png">

**Comment by lxfu1** [comment]
1.x 双轴图存在部分问题，2.x 支持任意组合，可在示例页面查看自定义legend
