### ISSUE TITLE
🧐[问题] 手机端长按图标时整张图表被选中，如何去掉选中效果

### ISSUE THREAD

**Issue by lindsay135** [ant-design/ant-design-charts#967]
### 🧐 手机端长按 Area 图表，整个图表会被选中，如何去掉长按选中效果

长按后会出现下图的交互，期望长按时没有此交互
<img width="149" alt="1" src="https://user-images.githubusercontent.com/53045287/142146680-7a2286d7-bf40-42b9-81be-965eee659904.png">

**Comment by lxfu1** [comment]
设置一下容器事件， point-events: none

**Comment by lindsay135** [comment]
此问题已解决，感谢大佬 @lxfu1 的帮助
