### ISSUE TITLE
🐛[BUG] useChart文件中useEffect太暴力了

### ISSUE THREAD

**Issue by arcsin1** [ant-design/ant-design-charts#97]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 
![image](https://user-images.githubusercontent.com/13724222/86341097-69832d00-bc88-11ea-98b7-001e2fb379aa.png)

**Comment by lxfu1** [comment]
如果可以确定更新项的话使用 metaData , https://charts.ant.design/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E8%A1%A8%E6%9B%B4%E6%96%B0
