### ISSUE TITLE
🧐[问题] useChart内部useEffect依赖问题

### ISSUE THREAD

**Issue by ILovePing** [ant-design/ant-design-charts#98]
### 🧐 问题描述 
useChart内部直接通过`JSON.stringify(config)`来进行是否更新的判断，
![image](https://user-images.githubusercontent.com/13430709/86341238-99323500-bc88-11ea-8087-524b968b11fb.png)

那么如果config内部使用正则、Date，function等类型的话，不会有问题么？
![image](https://user-images.githubusercontent.com/13430709/86341979-9257f200-bc89-11ea-9c3c-3e5a387bb7b0.png)

**Comment by lxfu1** [comment]
这种情况需要指定一下 memoData, https://charts.ant.design/guide/case#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E8%A1%A8%E6%9B%B4%E6%96%B0   欢迎提 PR 。
