### ISSUE TITLE
🐛[BUG]官网一直转圈，看不了文档了

### ISSUE THREAD

**Issue by yueduz** [ant-design/ant-design-charts#980]
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by visiky** [comment]
试一下打开：https://charts.ant.design/zh （估计部署有问题）

**Comment by yueduz** [comment]
这个网址能开

Visiky ***@***.***> 于 2021年11月21日周日 22:14写道：
