### ISSUE TITLE
🐛[BUG]   yField数组长度超过一个无法显示折线。

### ISSUE THREAD

**Issue by yueduz** [ant-design/ant-design-charts#981]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
yField数组长度超过一个无法显示折线。
### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
`yField: ['value','value1']` 此代码不能显示出折线，`yField: ['value']`或`yField: ['value1']` 可以显示。
### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
这个链接是有问题的示例
https://codesandbox.io/s/upbeat-nash-s356u
### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by labike** [comment]
@yueduz yField只能是字符串

**Comment by yueduz** [comment]
> @yueduz yField只能是字符串

长度为1的数组也行啊

**Comment by labike** [comment]
@yueduz 这个是相当坑的 文档里说只能是字符串, 结果数组里有一个字符串元素就行, 超过两个就无法渲染了

**Comment by yueduz** [comment]
> @yueduz 这个是相当坑的 文档里说只能是字符串, 结果数组里有一个字符串元素就行, 超过两个就无法渲染了

https://charts.ant.design/zh/docs/manual/faq#5%E5%8F%8C%E8%BD%B4%E5%9B%BE%E5%A6%82%E4%BD%95%E5%85%B1%E7%94%A8%E4%B8%80%E4%B8%AA-y-%E8%BD%B4  这里官方示例是使用的数组，长度为2

**Comment by labike** [comment]
@yueduz 我刚好也碰到这个问题 试了半天发现都不行

**Comment by yueduz** [comment]
> @yueduz 我刚好也碰到这个问题 试了半天发现都不行

百度的也有问题，我才来搞这个，没想到这个也有问题。

**Comment by labike** [comment]
@yueduz g2官网还推荐了两个react封装的图标库 可以试试

**Comment by labike** [comment]
@yueduz https://codesandbox.io/s/recursing-fire-7i0mi?file=/src/App.js

**Comment by visiky** [comment]
文档没有说”数组“可以哦，并不是说刚好可以 就可以的；多度量的折线图可以用数据转换的方式进行实现

**Comment by lxfu1** [comment]
['y1', 'y2'] 适用于双轴图， `DualAxes`，其它折线图都是 string 类型。

**Comment by labike** [comment]
ant design charts文档写的实在是坑

**Comment by lxfu1** [comment]
已经推出了新文档，建议用无痕浏览器打开看看。

**Comment by yueduz** [comment]
> g2官网
这个能用
谢谢！

**Comment by yueduz** [comment]
> @yueduz https://codesandbox.io/s/recursing-fire-7i0mi?file=/src/App.js

这个能用，谢谢！
