### ISSUE TITLE
🐛[BUG] CDN 引入有问题，window.charts 是 undefined

### ISSUE THREAD

**Issue by mzl980425** [ant-design/ant-design-charts#983]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
CDN 引入有问题，window.charts 是 undefined

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/22958600/142821635-c438a95a-e37b-4ae8-8e38-6a1a5f4d85ef.png)

### 🏞 期望结果 [描述你原本期望看到的结果]
window.charts 有东西

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/@ant-design/plots@latest/dist/plots.min.js"></script>
</head>
<body>
    <script>
        const { Line } = window.charts;
    </script>
</body>
</html>
```

### © 版本信息

- ant-design-charts 版本: latest
- 浏览器环境：Chrome 96
- 开发环境：mac OS

**Comment by mzl980425** [comment]
![image](https://user-images.githubusercontent.com/22958600/142821820-03548865-cc5e-429f-9b69-6018bf40d25b.png)

**Comment by lxfu1** [comment]
指定版本试一下： https://unpkg.com/@ant-design/charts@1.2.12/dist/charts.min.js

**Comment by lxfu1** [comment]
之前没注意， plots.min.js 需要是哟 window.Plots ,

**Comment by ImmortalZ** [comment]
> 之前没注意， plots.min.js 需要是哟 window.Plots ,

确定有效吗...

**Comment by matiasfacio** [comment]
@lxfu1 this still doesn't work. Could you please reopen this issue?
