### ISSUE TITLE
🐛[BUG]双轴图 显示异常，一个时间段的值显示在另一个时间段内,而不是本身对应的时间段内

### ISSUE THREAD

**Issue by Donlei** [ant-design/ant-design-charts#984]
### 🐛 bug 描述 
本身 虚线位置这段时间预测数据是不存在的 ，上面显示是从2021/11/22 4:39开始虚线的，但是 实际数据中是从2021/11/22 16:39才有的预测数据，为什么2021/11/22 16:39数据会在2021/11/22 4:39上显示呢，我们不是 24小时吗？难道没法区分是上午还是下午吗？是我配置问题还是？而且 像这种点非常密集的图形，柱状图会显示成面积图，折线图也会成面积图，除了slider选择一小段范围展示，有没有其他属性 解决这个密集点（一分钟一个点，要显示2天的数据就是2880个点）位显示难看的问题，因为现在给的数据值好多为零，所以图上看不出来

### 📷 复现步骤 

![1637575814](https://user-images.githubusercontent.com/24711571/142962909-4991f89e-e67e-42b3-8f9b-0e543916362a.png)
![1637575814(1)](https://user-images.githubusercontent.com/24711571/142962914-c86c1098-d042-4df4-b8ab-02fb835fa9f7.png)
![1637575814(2)](https://user-images.githubusercontent.com/24711571/142962921-69b2a0a7-fa6e-4220-a621-8f46254a192d.png)

### 💻 复现代码 
复现的链接
https://codesandbox.io/s/nifty-taussig-8rlpf?file=/src/App.tsx

### © 版本信息

- ant-design-charts 版本: CodeSandbox用的 "@ant-design/charts": "1.2.11"，项目中用的是@ant-design/charts": "1.2.14
- 浏览器环境 chrome
- 开发环境 antd-pro v5

**Comment by lxfu1** [comment]
看了一下，你数据里面有 "2021/11/23 9:03"  的数据

**Comment by Donlei** [comment]
> 看了一下，你数据里面有 "2021/11/23 9:03" 的数据

是的 ，这个数据有什么问题吗？会导致出现这种问题？

**Comment by Donlei** [comment]
@lxfu1 请问是这条数据的问题？我不太明白

**Comment by Donlei** [comment]
![1637635866(1)](https://user-images.githubusercontent.com/24711571/142965140-b5870fc0-00d5-4b2f-9733-e31595d86106.png)
@lxfu1 像这种密集点位的显示成这种效果，除了slider截取还有没有其他更好的办法解决呢

**Comment by lxfu1** [comment]
目前只能通过 silder 处理
