### ISSUE TITLE
🐛[BUG]双轴图 显示异常，滑动slider，折线跑到坐标轴外面

### ISSUE THREAD

**Issue by Donlei** [ant-design/ant-design-charts#985]
### 🐛 bug 描述 
双轴图，有一个柱状图，2条折线，其中一条折线值为0,，滑动slider扩大显示范围，值为0折线跑到坐标轴外面，还有对于密集点位的 显示，柱状图会变成面积图

![1637648005(1)](https://user-images.githubusercontent.com/24711571/142979308-729f53fb-71ec-450f-83db-c10813356b32.png)
![1637648033(1)](https://user-images.githubusercontent.com/24711571/142979317-4feb4bd9-0898-4fca-9f55-c631ec225f74.png)

### © 版本信息

- ant-design-charts 版本: ant-design/charts": "^1.2.14"
- 浏览器环境 chrome

**Comment by lxfu1** [comment]
```ts
  slider: {},
  limitInPlot: false,
  padding: [20, 20, 50, 20],
  meta: {
    [xField]: {
      sync: false,
    },
  },
```

**Comment by Donlei** [comment]
@lxfu1 谢谢大佬指点，我试了，这个只和padding有关，用appendPadding都不行，底部padding设置大点就好了

**Comment by htaoji1988** [comment]
加了padding 底部空了很多，跟另外一个图表不对齐了。
