### ISSUE TITLE
🐛[BUG] 描述使用词云图时，数据过长时会消失，未显示。

### ISSUE THREAD

**Issue by get5678** [ant-design/ant-design-charts#989]
### 🐛 bug 
使用词云图时，当窗口大小变化，数据过长时消失，未显示。
![image](https://user-images.githubusercontent.com/37957869/143161546-163ee284-a4e6-428d-be9e-941c56ba53da.png)

### 📷 复现步骤 
![image](https://user-images.githubusercontent.com/37957869/143161385-a8b5986b-3ac7-46d7-8e4c-bef395c865a5.png)

### © 版本信息

- ant-design-charts 版本:  1.0.9
- 浏览器环境 chrome 96.0.4664.45
- 开发环境  macOS Big Sur 11.3.1

**Comment by lxfu1** [comment]
算法限制，展示不下的会被过滤掉
