### ISSUE TITLE
🐛[BUG] 常规 webpack loader 无法解析代码

### ISSUE THREAD

**Issue by zfben** [ant-design/ant-design-charts#995]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]

ERROR in ./node_modules/mana-syringe/src/inversify/index.ts 1:12
Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import type { interfaces } from 'inversify';
| import { Container } from 'inversify';
| import { Syringe, Utils } from '../core';
 @ ./node_modules/mana-syringe/dist/index.esm.js 1:0-119 2:0-73 2:0-73 2:0-73 2:0-73 2:0-73 1410:26-37 1414:18-30 1435:9-17 1438:9-16 1683:27-38
 @ ./node_modules/@antv/xflow-core/es/index.js 2:0-44 3:0-23
 @ ./node_modules/@ant-design/flowchart/es/components/canvas-scale-toolbar/config.js 37:0-73 42:4-17 43:4-17 44:4-17 45:4-17 46:4-17 47:4-17 48:42-74 49:43-75 50:47-79 51:47-79 69:58-90 81:58-90 94:58-90 106:58-90 123:45-72 130:41-68
 @ ./node_modules/@ant-design/flowchart/es/components/canvas-scale-toolbar/index.js 14:0-66 16:17-26 19:0-59
 @ ./node_modules/@ant-design/flowchart/es/graph/index.js 53:0-72 145:48-66
 @ ./node_modules/@ant-design/flowchart/es/index.js 2:0-32 5:0-172
 @ ./node_modules/@ant-design/charts/es/index.js 2:0-38 2:0-38

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

1. 使用 `@sucrase/webpack-loader`
2. 正常引入 Line 组件就报错了

### 🏞 期望结果 [描述你原本期望看到的结果]

正常使用

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]

```tsx
import React from 'react'
import { Line } from '@ant-design/charts'

export default function () {
  return <Line
          data={ [
            {
              value: 10,
              date: '2021-01-01'
            },
            {
              value: 12,
              date: '2021-01-02'
            }
          ] }
          xField='date'
          yField='value' />
}
```

### © 版本信息

- ant-design-charts 版本: 1.3.0
- 浏览器环境
- 开发环境 Linux

**Comment by lxfu1** [comment]
重新安装一下依赖试试，或者直接使用 `@ant-design/plots`
```ts
import { Line } from '@ant-design/plots'
```

**Comment by zfben** [comment]
> 重新安装一下依赖试试，或者直接使用 `@ant-design/plots`
> 
> ```ts
> import { Line } from '@ant-design/plots'
> ```

可以了，看来是mana-syringe的bug
