### ISSUE TITLE
请问官网条形图的文档怎么缺失了？

### ISSUE THREAD

**Issue by fireworksflyaway** [ant-design/ant-design-charts#999]
https://charts.ant.design/zh/examples/gallery#category-%E5%9F%BA%E7%A1%80%E6%9D%A1%E5%BD%A2%E5%9B%BE
最近急着要用条形图，怎么没有文档啊

**Comment by lxfu1** [comment]
和柱图是一样的，晚点解决，先用一下
- https://charts.ant.design/zh/examples/column/basic#basic
- https://lxfu1.github.io/charts-beta/zh-CN/demos/bar
![image](https://user-images.githubusercontent.com/31396322/143426922-c215cc5b-931c-429c-b41a-672cd2dbf241.png)

**Comment by qiansimin88** [comment]
@lxfu1 能不能修复一下啊  第一次用 想看下  条形图的文档 ？  重新部署下很难吗 宝贝

**Comment by lxfu1** [comment]
无痕打开
